### ISSUE TITLE
Nothing mentions that influxDB doesn't work on <RHEL6

### ISSUE THREAD

**Issue by warmfusion** [influxdb/influxdb#1037]
Installing influx DB on rhel 5 fails as it initially doesn't setup the influxdb user account, and even when this is created prior to RPM install, the binary itself won't start due to

    ./influxdb: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ./influxdb)
    ./influxdb: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by ./influxdb)
    ./influxdb: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./influxdb)

Can the documentation make it more clear that the RPM won't work on RHEL5, or perhaps update the packaging so it won't install.

**Comment by otsuarez** [comment]
@tjyang  The rpm package will be installed (as shown, besides the useradd error). 
But the binary will not run.
```
./influxdb: /lib64/libc.so.6: version `GLIBC_2.6' not found 
```
Problem is:
```
$ ls -al /lib64/libc.so.6
lrwxrwxrwx 1 root root 11 Jun  9  2011 /lib64/libc.so.6 -> libc-2.5.so
```
Centos/RedHat 5 ships with glib 2.5. influxdb requires glibc 2.6 or upper. While there might solutions, I support @warmfusion proposal for explicitly stating on the doc/download pages the package is not available for version 5.
