### ISSUE TITLE
select with merge(regex) doesn't work with continuous queries

### ISSUE THREAD

**Issue by ikreymer** [influxdb/influxdb#1062]
It seems the merge function somehow gets dropped when the into clause is present:

```sql
select * from merge(/raw.data/) into daily.data
Error: Failed to parse continuous query: select * from  into daily.data
```

Listing the series does work:
```sql
select * from merge("raw.data.1", "raw.data.2", "raw.data.3") into daily.data
```

**Comment by dreampuf** [comment]
+1

If there is a way to cache these series data and apply the aggregation function to template summary series ?
