### ISSUE TITLE
Query with hyphen fails when redirected to another node

### ISSUE THREAD

**Issue by IngaFeick** [influxdb/influxdb#1073]
Hi,
we have a setup of a couple of influxdb nodes in a small cluster and would like to run a query which is supposed to pull data from only one shard. When I run the query in the admin panel on the same server that the shard lives on, the query works fine. I get the data that I expect. When I send the same query to another node in the cluster, which does not have the respective data shard, I can observe two things:
1) the admin panel returns the error message "Cannot find user root" (which is faulty in itself because I'm logged in as root)
2) more importantly: in the log on the shard having the desired data, the following error message regarding a hyphen somewhere in the query pops up:

	[2014/10/29 16:10:11 CET] [DEBG] 
	(github.com/influxdb/influxdb/coordinator.(*ProtobufServer).handleReques 
	t:123) Received id:35840 type:QUERY database:"foobar_metrics" shard_id:1 
	query:"select median(value) from 
	springfield04.statsd.gauge-PS.0.gc.ps_old_gen.memory_used_before_kb 
	merge 
	springfield04.statsd.gauge-PS.250.gc.g1_old_gen.memory_used_before_kb 
	where (time < 1414515424000000000) AND (time > 1414501024000000000) 
	group by time(30s) order asc" user_name:"root" is_db_user:true 
	[2014/10/29 16:10:11 CET] [EROR] 
	(github.com/influxdb/influxdb/coordinator. 
	(*ProtobufRequestHandler).handleQuery:75) Error parsing query: %!(EXTRA 
	*parser.QueryError=Error at -469359824:52 -469359824:53. syntax error, 
	unexpected '-', expecting $end) 

The issue is reproducible. We are running version 0.8.4 rc1. Please let me know if I can provide any further details. Thank you!

**Comment by joelgriffiths** [comment]
Shouldn't you wait until 0.9 is released before you stop fixing bugs on the current "stable" version?
