### ISSUE TITLE
Possible improvements to admin interface

### ISSUE THREAD

**Issue by mre** [influxdb/influxdb#1079]
Here are some suggestions on how to improve the admin interface.
In my opinion this would really help in the day-to-day work.
I know that you are probably working on it, but maybe it helps to have a little wishlist here. :smile: 
The list is roughly ordered by importance.

* Increase the text field height for the query input in the data interface. Currently everything is in one line. This gets a bit confusing with longer queries.
* Show last executed queries (e.g. when clicking on the text field)
* Leave error messages open after a failed query. Currently they disappear after a couple of seconds.
* Show success message after *drop series* command
* Show current database in data interface
* Show current leader in cluser dashboard
* Back button not working (e.g. inside "database" view)
* Add line break to long series names
* Auto-Completion of query commands
* Human readable timestamps in select queries (tables)
* Show timestamp in shards

**Comment by toddboom** [comment]
The admin updates in #2746 should be released with v0.9.1 and will resolve most of the requests stated above. Thanks!
