### ISSUE TITLE
Aperiodic timestamp when grouping with interval-selection

### ISSUE THREAD

**Issue by Uepsilon** [influxdb/influxdb#1088]
I've run into an Issue with aggregated data, grouped by time when using a specific time interval.

For example when selecting something like
```
SELECT MEAN(result_count) AS mean_result_count, user_id FROM testdata GROUP BY time(1M), user_id fill(0) WHERE time > '2014-05-01' AND time < '2014-11-04'
```
I'd expect the results to be between 2014-05-01 and 2014-11-04, grouped by month and user_id. So it would contain one result per user_id for each month with the timestamp pointing to the first of each month

Instead the result looks like this
```
1414800000000 -> 2014-11-01 01:00:00 +0100
1412208000000 -> 2014-10-02 02:00:00 +0200
1409616000000 -> 2014-09-02 02:00:00 +0200
1407024000000 -> 2014-08-03 02:00:00 +0200
1404432000000 -> 2014-07-04 02:00:00 +0200
1401840000000 -> 2014-06-04 02:00:00 +0200
1399248000000 -> 2014-05-05 02:00:00 +0200
1396656000000 -> 2014-04-05 02:00:00 +0200
```

Not only is the first day off by some days, not even the same amount each time. There is also an additional result line for __April__. 
Furthermore the grouping is not correct. According to the result I had no data in October. But there was - see full set of test data below.

I'm not sure if this happens because I don't have any data before 2014-10-28 or I'm just missing something out. Could you please take a look into it. 

Full Result: 

| time | mean_result_count | user_id |
| ----- | ----- | ----- |
| 1414800000000 | 100 | 96 |
| 1414800000000 | 191.33333333333334 | 97 |
| 1412208000000 | 0 | 96 |
| 1412208000000 | 0 | 97 |
| 1409616000000 | 0 | 96 |
| 1409616000000 | 0 | 97 |
| 1407024000000 | 0 | 96 |
| 1407024000000 | 0 | 97 |
| 1404432000000 | 0 | 96 |
| 1404432000000 | 0 | 97 |
| 1401840000000 | 0 | 96 |
| 1401840000000 | 0 | 97 |
| 1399248000000 | 0 | 96 |
| 1399248000000 | 0 | 97 |
| 1396656000000 | 0 | 96 |
| 1396656000000 | 0 | 97 |

Full Testdata

| time | sequence_number | result_count | user_id |
| ----- | ----- | -----: | -----: |
| 1415024544033 | 20550001 | 374 | 97 |
| 1415024342723 | 20250001 | 374 | 97 |
| 1415024287458 | 20130001 | 374 | 97 |
| 1415024253709 | 20030001 | 100 | 97 |
| 1415024240783 | 19990001 | 100 | 97 |
| 1415011154867 | 10170001 | 100 | 97 |
| 1415011145773 | 10130001 | 100 | 97 |
| 1415011142784 | 10090001 | 100 | 97 |
| 1415011138780 | 10050001 | 100 | 97 |
| 1415011113664 | 9980001 | 100 | 96 |
| 1415004952933 | 5920001 | 100 | 96 |
| 1414515608840 | 5400001 | 100 | 97 |
| 1414515543761 | 5300001 | 100 | 97 |
| 1414515536570 | 5260001 | 100 | 97 |
| 1414515531561 | 5240001 | 100 | 97 |
| 1414505594993 | 50001 | 100 | 96 |
| 1414505575943 | 10001 | 100 | 97 |

I'm running InfluxDB 0.8.5, if this helps any. 

Thanks guys

**Comment by beckettsean** [comment]
Daylight savings and logical month boundaries vs. 30 day months seem to explain everything. Addressed in #2074 and others.
