### ISSUE TITLE
mean(10 * A + 10 * B + 10 * C) != mean(10*(A + B + C))

### ISSUE THREAD

**Issue by mradamczyk** [influxdb/influxdb#1095]
Config: cluster of 10 nodes, 0.8.3.

![s1](https://cloud.githubusercontent.com/assets/2982247/4912163/48cbf0d0-6499-11e4-9a46-a03900ca52eb.jpg)
![s2](https://cloud.githubusercontent.com/assets/2982247/4912164/4bca62e4-6499-11e4-8a20-2c97b4ce7380.jpg)

I've tried to extract 10m of data and reproduce the bug in separate series, but it surprisingly works then.
Here are raw data from this series: https://gist.github.com/d4aeecfa88525a4cab91

**Comment by beckettsean** [comment]
@mjdesa can you try to repro with 0.9.2?

**Comment by mjdesa** [comment]
@beckettsean with a cluster of 3 or just a single node?

**Comment by beckettsean** [comment]
yes ;)

Start with 1 node and move to 3 if you can't repro. I suspect this is a non-issue in 0.9.2

**Comment by mjdesa** [comment]
kk

**Comment by mjdesa** [comment]
Math inside of mean no longer works
