### ISSUE TITLE
Add support for an offset on limit queries

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#1103]
Should be able to do a query like

```sql
select * from events limit 10 offset 20
```

**Comment by fouksf** [comment]
+1

**Comment by claudemamo** [comment]
+1 to this as well. I'm writing an event store and I'm blocked by this missing feature. Is there a workaround until this gets added?

**Comment by claudemamo** [comment]
What I've done for now is to add an offset field and populate it with current count. I've looked at the master source code and it seems that offset selection was added. Can you confirm that this will be available in v0.9.0?

**Comment by pauldix** [comment]
Offset will be supported in 0.9.0

**Comment by xigang** [comment]
+1
