### ISSUE TITLE
Build debian packages for i386 (latest is v0.7.0)

### ISSUE THREAD

**Issue by masterkorp** [influxdb/influxdb#1107]
The [lastest](http://s3.amazonaws.com/influxdb/influxdb_latest_i386.deb) is version 0.7.0

```
# influxdb -v
InfluxDB v0.7.0 (git: 696d61d) (leveldb: 1.15
```

MD5 of the file I tested:  c011c674fce6dd8880eee31e052ae62b

**Comment by otoolep** [comment]
We don't plan to officially support 32-bit packages.
