### ISSUE TITLE
Select series_name in continuous queries

### ISSUE THREAD

**Issue by obeleh** [influxdb/influxdb#1111]
This would allow us to build fanin queries.

Fanout version:
```sql
select mean(value), percentile(90, value) as percentile_90, percentile(99, value) as percentile_99 
from /^stats.*/ group by time(10m) into 10m.:series_name
```

Fanin version:
```sql
select series_name, mean(value), percentile(90, value) as percentile_90, percentile(99, value) as percentile_99 
from /^stats.*/ group by time(10m) into 10m
```

**Comment by pootzko** [comment]
+1 for this. It would allow us to merge results from a couple of different series by making a single call rather than having to make a couple of calls. Client would then know which row belongs to which series.
