### ISSUE TITLE
Influxdb wont restart after kill -9

### ISSUE THREAD

**Issue by theonlydoo** [influxdb/influxdb#1114]
Test pattern
======

* Install influxdb and feed it with graphite for a couple of days
* do a unwise ``select`` like : 
```bash
var="select * from /.*/"
curl -G "http://localhost:8086/db/graphite/series?u=graphite&p=graphite"  --data-urlencode "$var"
``` 
or something like that (you want to retrieve a huge amount of data with that select)
* Watch influxdb grow up in memory until it's no longer possible
* do a ``kill -9 $(pidof influxdb)``
* ``service influxdb restart``
* It will restart, but then it will output a huge amount of ``[EROR]`` :
  * ``github.com/influxdb/influxdb/api/graphite.(*Server).handleClient:258) GraphiteServer:%!(EXTRA *strconv.NumError=strconv.ParseFloat: parsing "0.53.": invalid syntax)``
* And it will never start properly again :-(

**Comment by otoolep** [comment]
This is no longer an issue in 0.9.0.
