### ISSUE TITLE
Stalled daemon (writes okay, but no reads)

### ISSUE THREAD

**Issue by hworld** [influxdb/influxdb#1116]
I'm having an issue where InfluxDB stops accepting query requests from HTTP after about a day.

Writes still happen and get recorded through the graphite plugin I'm using, but when I send in a select query, it never returns. Doesn't time out, either. cURL just sits there waiting for a response.

And there's absolutely nothing in the logs.

And to shut it down for a restart, I have to `kill -kill` it. It starts back up fine though and then runs for another day or so before somehow going back into the exact same state.

Any ideas? I'm kind of at a loss. It's currently in its bad state so I can try to debug, but I can't keep it that way for long, since I need to see server stats soon.

Version: "InfluxDB v0.8.5 (git: 9485e99) (leveldb: 1.15)"
Using RocksDB.
On CentOS 6.
Installed from the RPM.

**Comment by shanemhansen** [comment]
I am now seeing this same issue on another server (using leveldb). I did manage to capture a partial stack trace. I apologize that the data is truncated. I strace'd the process and reconstructed this from the write calls to stderr, and strace wasn't capturing the whole string. This is using the 0.8.7-1 RPM.

https://gist.github.com/shanemhansen/8e77955d9dc9a7900287

**Comment by shanemhansen** [comment]
Now seeing the same issue linux/x86_64 with 0.8.8

**Comment by parallelthought** [comment]
I'm observing this too. Here is my instance info (InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)). However as per the blog on v0.9, they have acknowledged this issue (number of open files opened by InfluxDB) and say that this will be optimized.
