### ISSUE TITLE
Wishlist: MQTT method for writing data

### ISSUE THREAD

**Issue by njh** [influxdb/influxdb#1127]
Hello,

I am interested in using MQTT as a method for writing data to InfuxDB. One of the benefits that I am interested in is to avoid data loss when clients are temporarily offline.

There is MQTT support for Go available from the Paho project:
http://www.eclipse.org/paho/clients/golang/

Any feedback before I try to implement it?

nick.

**Comment by beckettsean** [comment]
@njh we're nearing the final release of 0.9.0. Can we convince you to submit a PR?

**Comment by toddboom** [comment]
For fun and discussion: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

**Comment by njh** [comment]
Hm, I would have to learn Go first!

**Comment by KrishnaPG** [comment]
While looking for MQTT support for InfluxDB, came across this. Wondering if this was done and if so where to find it.

**Comment by njh** [comment]
No, sorry, I have not done any work on this.

**Comment by beckettsean** [comment]
It would be better to make an MQTT plugin for [Telegraf](https://github.com/influxdb/telegraf). Telegraf plugins are the preferred way to add inputs to InfluxDB
