### ISSUE TITLE
RPM Contains no description

### ISSUE THREAD

**Issue by spuder** [influxdb/influxdb#1152]
This is pretty minor, but if you search for influxdb with yum, there is no description of the RPM.. 

```
$ yum search influxdb
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * epel: mirror.prgmr.com
epel/pkgtags                                                                                                                                                | 1.3 MB     00:00
============================================================================== N/S Matched: influxdb ==============================================================================
...
influxdb.x86_64 : no description given

```

There isn't a spec file that I can find. It would be nice if the RPM showed what influxdb was so people know they are installing the correct package.

**Comment by otoolep** [comment]
Fixed for the 0.9.0 release by https://github.com/influxdb/influxdb/commit/387b91cce35588a7f3f6e16337d9ad69105bc58c
