### ISSUE TITLE
Ping endpoint can't be trusted

### ISSUE THREAD

**Issue by chmac** [influxdb/influxdb#1161]
As per #1140 InfluxDB can end up in a state where it will accept incoming connections but will never respond to them. In that state, the `/ping` endpoint returns `{"status":"OK"}` which is clearly not the case!

Not sure how it works internally, but I guess the `/ping` endpoint should perform some more extensive checks to verify that things really are working.

**Comment by willejs** [comment]
@chmac @toddboom i think maybe including a /healthcheck endpoint for more extensive checks, especially cluster wide health would be more beneficial. 

I like ping endpoints to return 200OK when the service is started and running, and return 404 when shutting down, these endpoints are primarily for load balancers. If something like the bug referenced to happens, the process should raise an exception, and exit non zero surely?

**Comment by corylanou** [comment]
We have two endpoints right now with somewhat similar responsibilities.  `/ping` quite literally just responds if the http endpoint is up.  It should , as well, mean the server is in good shape, but currently doesn't.

The other endpoint `/status` will offer a much more comprehensive look in the server moving forward, very much like a health check.  It will likely take optional parameters that will determine the depth and breadth of what it reports as well.  Currently it returns the id and current index of the node.

**Comment by beckettsean** [comment]
`/ping` no longer returns a 200 with a payload, just a 204 with a version string in the headers.

**Comment by garceri** [comment]
What's the status on this? i want a simple (truthy!) healtcheck that i can use from my AWS ELB. /status doesn't seem to return any meaningful "status"

**Comment by prakash-shanbhag** [comment]
Is there any workaround for this ? Both /status and /ping returns 204, which is not recognized by AWS ELB.

**Comment by adampetrovic** [comment]
+1 here, 204 is considered unhealthy when sitting behind an ELB.

**Comment by kshcherban** [comment]
@prakash-shanbhag @adampetrovic ALB/NLB supports custom http codes for health check.
