### ISSUE TITLE
Migration code removed

### ISSUE THREAD

**Issue by blalor** [influxdb/influxdb#1178]
I'm trying to upgrade from 0.7.3 to 0.8.6.  The migration code was stripped out in aeea03e362feb126a78659a92b77280d1e7c405c.  Given that the [docs](http://influxdb.com/docs/v0.8/advanced_topics/upgrading.html) still have those steps, I'm a bit surprised.  So it looks like I need to use 0.8.3 in order to actually migrate my data.

**Comment by toddboom** [comment]
Because we're moving towards v0.9.0, we won't be re-introducing the migration code into the later v0.8.x releases. We'll have a tool for exporting data from any v0.8.x instance for import into v0.9.0.
