### ISSUE TITLE
derivative function returns null values

### ISSUE THREAD

**Issue by jabbors** [influxdb/influxdb#1181]
The derivate function does not return any values for a simple counter series whereas the other functions do. I've tested with versions 0.8.5 and 0.8.6, both returning null values.

I collected metrics every 10th second in the sample and grouped by 20 seconds in the queries.

This is what my test data looks like. 
![screen shot 2014-11-27 at 11 59 05](https://cloud.githubusercontent.com/assets/1805094/5216250/75057570-7639-11e4-99f2-aae34d11034b.png)

Result from mean function.
![screen shot 2014-11-27 at 11 59 16](https://cloud.githubusercontent.com/assets/1805094/5216257/7998d8a2-7639-11e4-869c-b162b5c5b60e.png)

Result from derivative function.
![screen shot 2014-11-27 at 11 59 29](https://cloud.githubusercontent.com/assets/1805094/5216270/86309d0c-7639-11e4-9053-a5e5b8bf45a4.png)

Null values are not printed via the admin interface but when I query via the HTTP API I get lots of null values in the JSON result.
<pre>
[
    {
        "name":"packets",
        "columns":["time","derivative"],
        "points":[
            [1417082200000,null],
            [1417082180000,null],
            [1417082160000,null],
            [1417082140000,null],
            [1417082120000,null]
        ]
    }
]
</pre>

Result from difference function.
![screen shot 2014-11-27 at 11 59 38](https://cloud.githubusercontent.com/assets/1805094/5216271/8b6ddae6-7639-11e4-96d8-b5cdfc9ee5fc.png)

**Comment by dmelina** [comment]
In 0.8.8, all my derivative graph are correct

**Comment by Millnert** [comment]
With 0.8.8-1 running, i'm still experiencing exactly what i describe in #1104 with no change, for the DIFFERENCE operator

**Comment by Millnert** [comment]
derivative, mean does not work either

**Comment by allertec** [comment]
I`m using InfluxDB 0.8.6 and having the same problem with DERIVATIVE function

**Comment by tothandor** [comment]
Same issue here with difference aggregation, version 0.8.8.

**Comment by eveliovila** [comment]
0.9.rc seems to have the same issues

**Comment by xo4n** [comment]
we have seen that if you use a group by time higher than the sampling rate then derive gives results, so for the example above where the sample rate is 20s using group by time(21s) should give results for derive

**Comment by tothandor** [comment]
I'm using 5 minutes sampling rate and won't get results for derive or
difference even for aggregation on an hour or a day, though I have data for
a week.

-- 
Bests,
Andor

2015.03.02. 15:45 ezt írta ("xo4n" <notifications@github.com>):

**Comment by Millnert** [comment]
@toddboom  what's the status on this one?  is there *any* way to influence fixing priority on this issue?

**Comment by eveliovila** [comment]
Hi @toddboom, any news here? We would really like to see this working, until then we cant actually use influxdb!

**Comment by jwestboston** [comment]
I'm hitting this too.  DERIVATIVE() and DIFFERENCE() functions are not working.

**Comment by makapuf** [comment]
+1 for me, graphing CPU with collectd is not possible with this. Would upgrading to 0.9 fix this ?

**Comment by beckettsean** [comment]
DERIVATIVE is re-written and wired up in 0.9.0 final. Please report any issues in a new issue.
