### ISSUE TITLE
influxdb fails silently in restart

### ISSUE THREAD

**Issue by lucidbee** [influxdb/influxdb#1183]
I had to change the default config.toml file because we were using too much memory. So I dropped the number of max open files. But when I did this I made a typo.

When I tried to restart influxdb it failed silently. Nothing in any log: syslog, boot.log, the influxdb log file.  Init reported that it had started but it wasn't running. When I looked into the init script /etc/init.d/influxdb this is the line that was starting influxdb:

nohup start-stop-daemon --chuid influxdb:influxdb -d / --start --quiet --oknodo --pidfile $pidfile --exec $daemon -- -pidfile $pidfile -config $config > /dev/null 2>&1 &

I redirected the output going to /dev/null to a file and discovered my syntax error with nice message and line number. 

I removed the  '> /dev/null 2>&1' in this command.

I also added this to the beginning of /etc/init.d/influxdb:
exec 1> >(logger -s -t $(basename $0)) 2>&1

I like this because the error msg goes to syslog. Not sure if it is appropriate for an init script.

**Comment by otoolep** [comment]
Log messages now go to a file in 0.9.0.
