### ISSUE TITLE
Inner join query returning only one point since >0.8.3

### ISSUE THREAD

**Issue by ikreymer** [influxdb/influxdb#1184]
I have an inner join query which works perfectly in 0.8.3 but has not worked in any version since.

The query performs a division on two fanout queries (where X is a template set via grafana)
```sql
select 100.0 * C.count / T.count from agg.crashes.$X as C inner join agg.users.$X as T
```

The two series are created with continuous fanout queries, aggregated across same interval (1m):
```sql
select prod,count(distinct(id)) from /^raw.data$/ group by time(1m),prod into agg.users.[prod]
select prod,count(action) from /^raw.data$/ where action =~ /.*crash.*/ group by time(1m),prod into agg.crashes.[prod]
```

In 0.8.3, the divide query returns a point per minute, as expected..
In 0.8.6, the divide query returns only one point always.
After downgrading 0.8.6 -> 0.8.3 on the same cluster, the query started working again..

I tried adding a `group by time(1m)` to the end of the divide query but that had no effect.

This is preventing us from using the latest version of InfluxDB.

**Comment by beckettsean** [comment]
Join functionality is significantly re-written in 0.9.0. This should no longer be an issue

**Comment by liyichao** [comment]
I hate the tag 'obsoleted by v0.9.0'.
