### ISSUE TITLE
Archives contain unexpected directory name

### ISSUE THREAD

**Issue by JoeHazzers** [influxdb/influxdb#1187]
I would expect that extracting the archive `influxdb-0.8.6.amd64.tar.gz` would result in a new directory called `influxdb-0.8.6`.

However, the current downloads contain a directory called `build` instead, which is a bit unexpected.

Perhaps this could be an improvement to packaging?

Example:
```
[joe@ryuko ~]$ wget --quiet http://s3.amazonaws.com/influxdb/influxdb-0.8.6.amd64.tar.gz
[joe@ryuko ~]$ tar -zxvf influxdb-0.8.6.amd64.tar.gz 
build/benchmark_config.toml
build/config.toml
build/influxdb
build/influxdb-benchmark
build/scripts/
build/scripts/influxdb-daemon.sh
build/scripts/init.sh
build/scripts/post_install.sh
[joe@ryuko ~]$ 
```

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/commit/387b91cce35588a7f3f6e16337d9ad69105bc58c
