### ISSUE TITLE
merge() with table alias

### ISSUE THREAD

**Issue by kimor79** [influxdb/influxdb#1213]
On a query like `select sum(value) from merge(/some_regex/) group by time(5m)` the returned series name is 'merged'. I would like to be able change that to something more appropriate by doing `select sum(value) from merge(/some_regex/) as foo group by time(5m)` but that results in `syntax error, unexpected AS, expecting $end`

**Comment by ThomasKurz** [comment]
+1

**Comment by beckettsean** [comment]
Tags effectively replace MERGE
