### ISSUE TITLE
Add support for an offset for TOP queries

### ISSUE THREAD

**Issue by YaronWittenstein** [influxdb/influxdb#1219]
I'd like to add an issue similar to issue #1103 

being able to receive the TOP results but starting from non-zero index
```
select top(user_id_hits, 10), user_id from events group by time(1d) offset 20
```

**Comment by beckettsean** [comment]
0.9.0 has support for LIMIT and OFFSET. OFFSET for TOP will be addressed when TOP is re-implemented.
