### ISSUE TITLE
Detect data anomally 

### ISSUE THREAD

**Issue by kureikain** [influxdb/influxdb#1224]
Hi,

Do we have any built-in method to detect anomal data in a time series? I'm thinking of using median, then a threshold to detect anomally? Such as [median] +/- [threshold value]? Or probably using Percentile?

**Comment by pauldix** [comment]
There isn't anything built in and we don't plan on building anomaly detection into the database. Rather, our plan is to build the tools so that you'll be able to do it yourself.
