### ISSUE TITLE
Improve the readme for influxdb/client

### ISSUE THREAD

**Issue by epelc** [influxdb/influxdb#1225]
After looking at the [godocs](http://godoc.org/github.com/influxdb/influxdb/client) for influxdb/client I'd assume it's the best way to get data into influxdb from go. However the readme is practically empty and if your googling for a go client for influxdb the only other one that comes up is [this](https://github.com/rossdylan/influxdbc) one which seems abandoned. Anyways it isn't very inviting to new people if your using go see a dead pkg and the official looking client has little docs.

I'd be happy to write an example once I get up and running but for now I thought I'd at least open an issue. Also the setup was very easy and I love the grafana integration it should be perfect for what I need.

**Comment by otoolep** [comment]
We just overhauled this.

https://github.com/influxdb/influxdb/commit/221097b1cca3734af078b82867f523902aea6210
