### ISSUE TITLE
Send a huge Collectd packet and InfluxDB dies (MaxPacketSize)

### ISSUE THREAD

**Issue by ymettier** [influxdb/influxdb#1231]
Hello,

Here is how to crash InfluxDB with Collectd input plugin enabled

### 1/ Configure InfluxDB with Collectd Input plugin
```
  # Configure the collectd api
  [input_plugins.collectd]
  enabled = true
  address = "0.0.0.0" # If not set, is actually set to bind-address.
  port = 25826
  database = "collectd"
  # types.db can be found in a collectd installation or on github:
  # https://github.com/collectd/collectd/blob/master/src/types.db
  # typesdb = "/usr/share/collectd/types.db" # The path to the collectd types.db file
  typesdb = "/usr/share/collectd/types.db"
```

### 2/ Configure Collectd normally
Configure Collectd with MaxPacketSize unset or set to 1452.

### 3/ Run InfluxDB and Collectd
Yeah, it's working. Metrics are coming and are stored normally in the DB.
Thanks you all, you are doing a wonderful job... :)

### 4/ Reconfigure Collectd network plugin
In Collectd configuration file, in the `network` plugin section, set MaxSize to a bigger value than the default

```
<Plugin network>
  Server "127.0.0.1" "25826"

# Default value 1452
#  MaxPacketSize 1452
# Let's crash InfluxDB with a bigger value
  MaxPacketSize 65535

  # proxy setup (client and server as above):
  Forward true
</Plugin>
```

### 5/ Restart Collectd
No need to restart InfluxDB. InfluxDB is already running...

### 6/ Crash !
Wait (less than 10 minutes) and see InfluxDB crash.

Of course we should not use so huge UDP packets. However this is an easy way to do some nasty things...

### Additionnal information

Collectd is working (as a concentrator) with that size of packets. At least, configure Collectd with `MaxPacketSize 65535` on the concentrator and it will accept such huge packets.

InfluxDB v0.8.6 (git: a0fd0cd) (leveldb: 1.15)
Tested with Collectd-5.4.0 and Collectd-5.4.1.690.g83f88a1

Regards,
Yves

**Comment by otoolep** [comment]
@corylanou -- since you just re-worked the collectd plugin, do you want to see if the new software suffers from this issue? Perhaps a unit test would be in order?

**Comment by corylanou** [comment]
@otoolep there is this comment in the collectd plugin code:

```
// From https://collectd.org/wiki/index.php/Binary_protocol                                                                                                                                                                                                              
//   1024 bytes (payload only, not including UDP / IP headers)                                                                                                                                                                                                           
//   In versions 4.0 through 4.7, the receive buffer has a fixed size                                                                                                                                                                                                    
//   of 1024 bytes. When longer packets are received, the trailing data                                                                                                                                                                                                  
//   is simply ignored. Since version 4.8, the buffer size can be                                                                                                                                                                                                        
//   configured. Version 5.0 will increase the default buffer size to                                                                                                                                                                                                    
//   1452 bytes (the maximum payload size when using UDP/IPv6 over                                                                                                                                                                                                       
//   Ethernet). 
```

This sounds like a collectd issue, not a udp issue, but since they document what their upper bound is, we also match that in our buffer
[Collectd binary protocol](https://collectd.org/wiki/index.php/Binary_protocol)
```go
buffer := make([]byte, 1452) 
```

I'm not that familiar with collectd, but from what the doc says this seems like the correct behavior.  I could easily be missing something though.

**Comment by otoolep** [comment]
Thanks @corylanou -- what will happen if we send a 10K byte UDP packet to our collectd input?

**Comment by corylanou** [comment]
@otoolep We'll have to run some stress tests on it once we are ready.  A couple things could happen.  1) We might just lose data.  2) It might be inefficient to process.  3) It could clog up the endpoint and crash.

**Comment by otoolep** [comment]
Yeah, it'll be interesting to see how the Go handles this.

**Comment by otoolep** [comment]
I'm pretty sure this has been fixed. Please let me know if I am incorrect.

**Comment by ymettier** [comment]
No crash now, but :

```
[collectd] 2015/09/17 08:34:04 Collectd parse error: Invalid packet
```

So please either
* accept big packets
* update the doc to say that bigger UDP packets (as configured in Collectd with `MaxPacketSize`) are not supported (I'm thinking about this : https://influxdb.com/docs/v0.9/write_protocols/collectd.html)

I have not seen the InfluxDB code, but I think Collectd plugin has a short (normal UDP size) sized buffer and part of the big UDP packet will be dropped. So the buffer contents is truncated and considered as "invalid packet".

However, I agree that there is no more crash. You probably don't need to reopen this issue.

Regards,
Yves

**Comment by dmilith** [comment]
I have this issue too. A lot of "Collectd parse error: Invalid packet"

**Comment by beckettsean** [comment]
@ymettier @dmilith since the panic is fixed this issue should stay closed. Please [open a new issue](https://github.com/influxdb/influxdb/issues/new) regarding the invalid packet errors.

@ymettier if you think this can be addressed by documentation, please [open an issue on the docs repo](https://github.com/influxdb/influxdb.com/issues/new) with details. I don't grok collectd/UDP well enough to do so myself, but I can get someone who does grok it to update the docs.

**Comment by ymettier** [comment]
Hello,

Now, please follow issue https://github.com/influxdb/influxdb.com/issues/381

Regards,
Yves
