### ISSUE TITLE
Document "order asc" query syntax in Query language documentation page

### ISSUE THREAD

**Issue by harobed** [influxdb/influxdb#1243]
Hi,

I found "order asc" feature in github issue : 

```
select * from abc where time < now() limit 100 order asc
```

I didn't find it in [Query language](http://influxdb.com/docs/v0.8/api/query_language.html) documentation.

I suggest to document "order asc" in [Query language](http://influxdb.com/docs/v0.8/api/query_language.html) page.

**Comment by beckettsean** [comment]
closed in favor of #2022
