### ISSUE TITLE
New aggregate function for sum normalization

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [influxdb/influxdb#1245]
Hello,
I let me explain the problem, I have request:
SELECT sum(hits) FROM .... GROUP BY time(10m)
Now, this returns me the cumulative number of hits for 10 minute intervals, but I do actually want to se it as hits per second, so obviously I need to do something like that:
SELECT sum(hits)/600 FROM .... GROUP BY time(10m),
But that is not very user friendly and is error prone, so what about something like that:
SELECT sumX(hits,1s) FROM .... GROUP BY time(10m),
which will do it automatically.

Thank you and best regards,
Dragomir

**Comment by beckettsean** [comment]
Not on the roadmap but we will consider a PR
