### ISSUE TITLE
Query Time Serie WHERE UNDEFINED

### ISSUE THREAD

**Issue by patricklehmann** [influxdb/influxdb#1246]
Hy there,

Firstful: InfluxDB is awesome.
I've a time series there is always a value product_id and an optional value for bundle_id.
is there a possibility to query something like

SELECT * FROM series WHERE bundle_id = UNDEFINED AND product_id = 'iphone-6'

To get the products without bundles?

Thanks!!

**Comment by toddboom** [comment]
@patricklehmann You should be able to get the number of unique values by using `DISTINCT()`.

**Comment by patricklehmann** [comment]
@toddboom Hey, i just included the UNDEFINED text for these values now i can look for these. thanks!
