### ISSUE TITLE
Expvar support?

### ISSUE THREAD

**Issue by mperham** [influxdb/influxdb#1252]
Go provides a way to track and publish built-in memory metrics in the [expvar package](https://www.mikeperham.com/2014/12/17/expvar-metrics-for-golang/).  Since this is the official way to do it, would InfluxDB consider enabling it so visualization tools like Inspeqtor Pro can provide realtime dashboards for this data?  I'd love to see this automatically supported for InfluxDB:

![dashboard](https://www.mikeperham.com/wp-content/uploads/2014/12/mem-viz.png)

**Comment by pauldix** [comment]
Closing this since it's covered by #1936, which will be in soon.
