### ISSUE TITLE
Expose internal InfluxDB statistics as JSON

### ISSUE THREAD

**Issue by auxesis** [influxdb/influxdb#126]
Per #123, it would be helpful for smarter load balancers to have insight into the performance of individual InfluxDB nodes.

**Comment by Ynguibjoerg** [comment]
+1 for exposing statistics and health info via any api. Would really love to have this so that we could write a collectd plugin to monitor the db performance.

**Comment by mre** [comment]
+1

**Comment by candoom** [comment]
+1

**Comment by damm** [comment]
This issue was originally created December 30th, 2013.  It's really :( to see +1's with no new contributions here.

**Comment by otoolep** [comment]
This is going to be part of the 0.9 release:

https://github.com/influxdb/influxdb/issues/1470
https://github.com/influxdb/influxdb/issues/1252

**Comment by ixmatus** [comment]
That is wonderful news.
ᐧ

On Tue, Feb 10, 2015 at 3:28 PM, otoolep <notifications@github.com> wrote:

> This is going to be part of the 0.9 release:
>
> #1470 <https://github.com/influxdb/influxdb/issues/1470>
> #1252 <https://github.com/influxdb/influxdb/issues/1252>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/126#issuecomment-73787531>.
>



-- 
Parnell Springmeyer
parnell@digitalmentat.com | digitalmentat.com | 0xDCCF89258EAD874A
<http://pgp.mit.edu/pks/lookup?op=get&search=0xDCCF89258EAD874A>

**Comment by damm** [comment]
@otoolep would have never known as they were not referenced at all.  But thank you for sharing :)

**Comment by XANi** [comment]
metrics as internal "virtual" database would be pretty elegant solution, then continous query could be used to persist wanted stats.

**Comment by beckettsean** [comment]
done in #1936
