### ISSUE TITLE
sum(value) is multiplied by "group by time()"

### ISSUE THREAD

**Issue by zzzuzik** [influxdb/influxdb#1262]
I was searching for an answer for the question from here #728, when `sum(value) is multiplied if the group by time() value is multiplied`
As you know, Grafana supports dynamic "group by time" to reduce the load on the server if you look at the data like last ~24 hours.. (my data is gathered every 3 sec) 
I cannot use continues queries because all dashboards are generated on the fly based on passed args, and these args are used to query InfluxDB..
Thus, if I need to get  `select sum(value) from /server.*.connections/ group by time($INTERVAL)` where $INTERVAL could be between 3s and 1min, all graphs displayed different data that has been multiplied by $INTERVAL.. 
How can I display the same SUM for different $INTERVAL?

**Comment by ekle** [comment]
is there now a solution to this ?

**Comment by def324** [comment]
I'd be interested in finding a solution for this as well...

**Comment by mathfool** [comment]
Any solution to this?

**Comment by ekle** [comment]
you can use $__interval_ms and the math functions in grafana.
https://github.com/grafana/grafana/issues/7190
