### ISSUE TITLE
influxdb out of memory

### ISSUE THREAD

**Issue by nashasha1** [influxdb/influxdb#1278]
Hi.my influxdb version is 0.8.8.
I insert into influxdb 1000 rows/s. after a few minutes,I find the memory increase to 80+%.then it crashed. screen output shows "out of memory".
I restart influxdb,not insert data.after a few minutes,it crash again.
then I restart then crash.. over and over.
I want to know,how should I limit the memeory cost of influxdb,or some other way to make sure influxdb not crash.
Thanks!~~

**Comment by pauldix** [comment]
What version are you using? What does the data look like that you're inserting? Are you running any queries? Do you have any continuous queries created?

There is no way to set a memory limit on InfluxDB. However, 2GB is plenty for a number of use cases. It all depends on what you're doing.

**Comment by nashasha1** [comment]
my version:0.8.8
my data like this {"name":"logs","columns":["machine","name", "type","data","app_id","instance_id"]}
I just insert，not query.
but I have a continuous query:select * from "logs" into logs.[app_id].[instance_id].
I insert into about 200000 - 300000 rows.It crashed

**Comment by prune998** [comment]
> [4560634.804398] Out of memory: Kill process 974247 (influxdb) score 843 or sacrifice child
> [4560634.804436] Killed process 974247 (influxdb) total-vm:60442768kB, anon-rss:57177376kB, file-rss:0kB

My influxDB (no cluster, version 0.0.8) is taking 57 GIG of resident memory (real RAM used...)

**Comment by prune998** [comment]
![image](https://cloud.githubusercontent.com/assets/1110398/5801745/73b62b2c-9fbc-11e4-86fe-6b60c8bacb36.png)
This is the memory usage of the server.
This mainly happen when using a "derivative" function in a dashboard...

**Comment by damm** [comment]
What is the query and hmm what's it look like? that's a crazy amount of ram just for derivative.

**Comment by pauldix** [comment]
This is likely fixed in 0.9.0 and we won't be making fix releases for the 0.8 line. Please test against the latest 0.9.0 RC and let us know if there's an issue.
