### ISSUE TITLE
group by sanity question

### ISSUE THREAD

**Issue by somebody32** [influxdb/influxdb#1288]
Hi!

I'm testing InfluxDB for various use cases and stumbled across strange (for my understanding) `group by` behaviour.

I have a shard space with settings for 45d retention and 7d size (52d of data). The earliest event has `time` equal to 1415836800000 (13 Nov 2014).
When I try to run the `select count(id) from created group by time(90d)` I get 2 points in response.   

![screenshot 2015-01-05 14 39 49](https://cloud.githubusercontent.com/assets/25742/5612596/bacacf60-94e8-11e4-8e02-d7d0e0a1e6c3.png)

Timestamps are: 

* 1417651200000 (4 Dec 2014)
* 1409875200000 (5 Sep 2014)
 
Could you please clarify an underlying logic for that behaviour?

**Comment by pauldix** [comment]
The `90d` group by time creates buckets of 90 days. The first bucket is 5th Sept - 3rd Dec and the second bucket is the 4th Dec + 90 days. You're getting two points because you have data points in both buckets of time.

**Comment by somebody32** [comment]
@pauldix Thanks for the answer, but could you describe a little bit more why these time-periods were chosen? Why not time of the first event + 90 days, or time of the last one - 90?

**Comment by pauldix** [comment]
The method for computing buckets of time is just the `timestamp % bucket size in seconds`. So the windows are consistent regardless of when you're sending the query.

**Comment by somebody32** [comment]
@pauldix got it, thanks again!
