### ISSUE TITLE
valid series names and quoting changed between 0.7.x and 0.8.x

### ISSUE THREAD

**Issue by joelandman** [influxdb/influxdb#1291]
Hi folks:  

  We used to have no trouble at all with series names like this  usn-03-1g.tcpinfo.udperrs, and we were previously able pass them in to queries without quoting.  This has changed.  Now, when we use a query like this:

select * from usn-03-1g.tcpinfo.udperrs limit 10

we get a syntax error:

D[16058] Scalable::TSDB::_send_chunked_get_query error mesg  = 'syntax error, unexpected '-', expecting $end
select * from usn-03-1g.tcpinfo.udperrs limit 10
                 ^'
D[16058] Scalable::TSDB::_send_chunked_get_query -> mapping 0.000004s 
D[16058] influxdb-cli.pl; DB query 'select * from usn-03-1g.tcpinfo.udperrs limit 10' took 0.004232s
ERROR:
	message	= 'syntax error, unexpected '-', expecting $end
select * from usn-03-1g.tcpinfo.udperrs limit 10
                 ^'
	rc	= '400'

I tried using single quotes and got this:

D[16058] Scalable::TSDB::_send_chunked_get_query error mesg  = 'syntax error, unexpected STRING_VALUE
select * from 'usn-03-1g.tcpinfo.udperrs' limit 10
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^'
D[16058] Scalable::TSDB::_send_chunked_get_query -> mapping 0.000004s 
D[16058] influxdb-cli.pl; DB query 'select * from 'usn-03-1g.tcpinfo.udperrs' limit 10' took 0.004279s
ERROR:
	message	= 'syntax error, unexpected STRING_VALUE
select * from 'usn-03-1g.tcpinfo.udperrs' limit 10
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^'
	rc	= '400'

though forward slashes for a regex did work, as well as double quotes.  

Please clarify proper quoting and any quoting changes you might be implementing.  

Thanks!

**Comment by pauldix** [comment]
If you have `.` in the column name or series name, you'll need to wrap them in double quotes in your queries.

**Comment by joelandman** [comment]
Ok, though this doesn't help with names with periods, dashes, and a regex.  I can open a different ticket if it helps.
