### ISSUE TITLE
Continuous query not filtering columns?

### ISSUE THREAD

**Issue by blakepettersson** [influxdb/influxdb#1297]
Since I haven't received any reply on [Stackoverflow](https://stackoverflow.com/questions/27572443/continuous-query-not-filtering-columns-in-influxdb) nor [the mailing list](https://groups.google.com/forum/#!topic/influxdb/zc-x3ZphrOw) I'll ask here..

I'm using the Metrics InfluxDB reporter, which outputs its series with these columns:

`time, one_minute, five_minute, fifteen_minute,mean_rate,count`

I'm only interested in the `one_minute` column, so figured that I could use a continuous query to filter out the irrelevant columns (and hopefully save some disk space):

`select time,one_minute from /vp\.production\.?.*\.meter$/ into :series_name.1m`

I thought that doing this would only return the columns defined in the continuous query but when querying the series that have been created by it, I still get the columns that are present in the "parent" series, i.e

`select * from "vp.production[...].meter.1m"` and `select * from "vp.production[...].meter"` returns the exact same resultset, with all the columns. 

Am I missing something or is this some kind of bug? I'm using InfluxDB 0.8.7.

**Comment by pauldix** [comment]
What happens if you don't select `time`? This looks like a bug of some kind and if so, it will be fixed in 0.9.0

**Comment by blakepettersson** [comment]
The same thing applies when only `one_minute`is selected.
