### ISSUE TITLE
Derivative problem

### ISSUE THREAD

**Issue by allertec** [influxdb/influxdb#1314]
Hello,

I`m trying to run following query against my database:
select derivative("server01.value" + "server02.value") from "server01" INNER JOIN "server02" group by time(1m)

However I don`t get any output, graph, message etc. Literally nothing. Is this a bug, or wrong query?
If this is a bug, then is there any work around?

My InfluxDB version is 0.8.6. 

Thank you

**Comment by davidblewett** [comment]
Possible duplicate of #438.

**Comment by damm** [comment]
@allertec try adding `fill(0)` to your query.

I find without `fill(0)` or `fill(null)` there is nothing returned.
