### ISSUE TITLE
DB lost after restart

### ISSUE THREAD

**Issue by jonira** [influxdb/influxdb#1315]
My current installation looses all data after restart

1. create a new db (name 'test') through web ui
2. ````$ sudo /etc/init.d/influxdb restart````
3. db is gone, log.txt does not tell what went wrong (default config.toml)

influxdb v0.8.7, tried to change db between rocksdb and leveldb - no effect

**Comment by jonira** [comment]
as a workaround did manual reinstall:

1. ````$ rm -rf /opt/influxdb````
2. fetch new deb package & install (v.0.8.8)

seems to work now. Closing ticket.

**Comment by toddboom** [comment]
@jonira Thanks for the update. It's possible that the initial database creation wasn't actually being persisted to disk, so the restart would have just reverted the original state. In any event, it's good to know that a fresh data directory fixed everything.

**Comment by syunusic** [comment]
Hi, I have the same problem. I restarted the server before without that problem. Now the DB is gone, but is still in the hard drive. I have 120GB in /var/opt/influxdb/data/mydb (my DB is called mydb). How can I make Influx to read that again?

**Comment by r9liucc** [comment]
@syunusic Do you resolve your problem? I have a similar problem with you. The difference is that I can find the database via 'show databases', but there is no measurements in there. I can also find the data in the filesystem.

**Comment by rwb196884** [comment]
This has just happened to me.
System appears to have reset to default after the computer restarted. Lost lots of data, and dashboards, tasks and notifications.

But there's 200MB in `/var/lib/influxdb/engine/data` so maybe there's hope?
What's causing this problem?
