### ISSUE TITLE
Unavailable immediately upon start?

### ISSUE THREAD

**Issue by rebyn** [influxdb/influxdb#1319]
Hi, I'm seeing some weird behavior upon trying to install & start InfluxDB on my CI server (Ubuntu 64).

```
$ sudo /etc/init.d/influxdb start
Setting ulimit -n 65536
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
```

Then if I do:

```
$ cat /opt/influxdb/shared/influxdb.pid
cat: /opt/influxdb/shared/influxdb.pid: No such file or directory cat /opt/influxdb/shared/influxdb.pid returned exit code 1
```

I have to `sleep 1` and only until then it works:

```
$ sudo /etc/init.d/influxdb start && sleep 1 && cat /opt/influxdb/shared/influxdb.pid
Setting ulimit -n 65536
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
8079
```

**Comment by toddboom** [comment]
@rebyn Is this for a new installation or is there existing data when you start it up?

**Comment by rebyn** [comment]
@toddboom this is a fresh install on a fresh instance :)

**Comment by 256dpi** [comment]
I experienced similar issues while installing influxdb on circle.ci: The server almost never started with on first `sudo service influxdb start`. My workaround was to issue that command two times in a row.

**Comment by rebyn** [comment]
> I experienced similar issues while installing influxdb on circle.ci: The server almost never started on the first sudo service influxdb start. My workaround was to issue that command two times in a row.

My CI server = CircleCI :). Their support kindly suggested me to `sleep 1` before doing anything else, that worked. Weird thou.
