### ISSUE TITLE
select w from x where y group by fill(z) statement doesn't return any data when where statement cannot match a single datapoint

### ISSUE THREAD

**Issue by thomasbernard88** [influxdb/influxdb#1335]
Hi,

InfluxDB version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15)

We noticed the interesting behaviour in InfluxDB that at the point where you do a select statement and the where statement cannot get any datapoint, no data is returned. The select statement contains a group by and a fill(x) statement.

Here's a sample output. I'm only printing the .points[]

Snippet from the script to give a sense of what the query looks like:
```
CURL_STRING=`curl -G -m 5 "https://<InfluxDB server>:48086/db/metrics_prod/series?p=<InfluxDB user password>&u=<InfluxDB username>&time_precision=s" \
                --data-urlencode "q=select count(value) from <Create File Durations metric> where time > now() - 1h  and value > [-N value] group by time(5m) fill(-1) order desc" \
                --compressed 2> /dev/null`
    CURL_STRING=`echo ${CURL_STRING} | jq -r -c '.[].points[] ' 2> /dev/null`
    echo "CURL_STRING = ${CURL_STRING}"
```

Commands:
If I check on datapoints higher than 2000 (see -N):
```
CURL_STRING = [1421691600,-1]
[1421691300,1]
[1421691000,1]
[1421690700,1]
[1421690400,-1]
[1421690100,-1]
[1421689800,-1]
[1421689500,1]
[1421689200,-1]
[1421688900,-1]
[1421688600,-1]
[1421688300,-1]
[1421688000,-1]
```

If I check for datapoints higher than 5000 (see -N, but there are no datapoints in the past hour that are higher than this point):
```
CURL_STRING = 
```

Graph that suggest that in the past hour there were no datapoints higher than 5000.
![screen shot 2015-01-19 at 11 40 32 am](https://cloud.githubusercontent.com/assets/10604224/5808170/d9d993b4-9fe7-11e4-9777-d1fef14caf6a.png)

The first command suggests that the resultset is devided into timeframes that may or may not have data. If there is no data the value you provided to the fill(x) in your select statement is used. 
However when you increase that threshold to the point where no datapoints match, you get no data back. What I would expect in this case is that the fill(x) kicks in and all values in the dataset are the ones you provided to fill(x).

Thanks for looking into it!

**Comment by somebody32** [comment]
Got the same problem today, as for me it is totally unexpected behaviour. Any plans to change it for 0.9?
