### ISSUE TITLE
YUM repo

### ISSUE THREAD

**Issue by jtyr** [influxdb/influxdb#1338]
It's not very convenient to install InfluxDB from URL pointing to a specific RPM package. It would be much better if you could create a YUM repo in AWS which the users could use to install and upgrade their InfluxDB installation.

**Comment by otoolep** [comment]
We will  re-do packaging for the 0.9.0 release (and later), which should address this issue.

**Comment by njh** [comment]
:+1:

**Comment by rossmcdonald** [comment]
We've just setup an official repository for new InfluxDB packages. For `yum`, you can run the following command (as root):

``` bash
cat <<EOF>/etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/centos/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
EOF
```

And then a `sudo yum install influxdb`. Let us know if you run into any issues!

**Comment by betandr** [comment]
:+1:

**Comment by steverweber** [comment]
please add the details to:
https://influxdata.com/downloads/

**Comment by rossmcdonald** [comment]
@steverweber Links to the package installation instructions have been added. Thanks!

**Comment by betimd** [comment]
Is this working still on AWS?
Can you point to the doc link?

**Comment by rossmcdonald** [comment]
@betimd The instructions have since been moved to the Install documentation [here](https://docs.influxdata.com/influxdb/latest/introduction/installation/#installation).
