### ISSUE TITLE
Collectd plugin disabled 

### ISSUE THREAD

**Issue by oublackberry** [influxdb/influxdb#1355]
Here's the error...

[2015/01/23 09:15:03 CST] [INFO] (github.com/influxdb/influxdb/server.(*Server).ListenAndServe:178) Collectd input plugins is disabled

Here's the snip from my config...
[input_plugins]

  [input_plugins.collectd]
  enabled = true
  port = 8096
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db"

Not sure what to do next. Any thoughts? Below is the full config file.  And here's my version number.

InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)

--------- Full config ----------
bind-address = "0.0.0.0"

[logging]
# logging level can be one of "debug", "info", "warn" or "error"
level  = "debug"
file   = "/opt/influxdb/shared/log.txt"         # stdout to log to standard out

[admin]
port   = 8083              # binding is disabled if the port isn't set
assets = "/opt/influxdb/current/admin"

[api]
port     = 8086    # binding is disabled if the port isn't set

read-timeout = "5s"

[input_plugins]

  [input_plugins.collectd]
  enabled = true
  port = 8096
  database = "collectd"
  typesdb = "/usr/share/collectd/types.db"

  [input_plugins.graphite]
  enabled = true
  port = 2003
  database = "collectd"
  udp_enabled = true

  [input_plugins.udp]
  enabled = true
  port = 4444
  database = "collectd"

[raft]
port = 8090
dir  = "/opt/influxdb/shared/data/raft"

[storage]
dir = "/opt/influxdb/shared/data/db"
write-buffer-size = 10000

[cluster]
protobuf_port = 8099
protobuf_timeout = "2s" # the write timeout on the protobuf conn any duration parseable by time.ParseDuration
protobuf_heartbeat = "200ms" # the heartbeat interval between the servers. must be parseable by time.ParseDuration
protobuf_min_backoff = "1s" # the minimum backoff after a failed heartbeat attempt
protobuf_max_backoff = "10s" # the maxmimum backoff after a failed heartbeat attempt
write-buffer-size = 10000

max-response-buffer-size = 100

concurrent-shard-query-limit = 10
[leveldb]

max-open-files = 40
lru-cache-size = "200m"
max-open-shards = 0
point-batch-size = 100

[sharding]
replication-factor = 1

  [sharding.short-term]
  duration = "7d"
  split = 1

  [sharding.long-term]
  duration = "30d"
  split = 1

[wal]

dir   = "/opt/influxdb/shared/data/wal"
flush-after = 1000
bookmark-after = 1000
index-after = 1000

requests-per-logfile = 10000

------ End config ------

**Comment by otoolep** [comment]
With your config (as much as I could test with it) the Collectd plugin
starts fine. Please check that you are actually using the configuration
file you think you are using.

Philip

**Comment by otoolep** [comment]
Closing this as the config works fine and the plugin is started.

**Comment by oublackberry** [comment]
That was it. Ps showed it was pulling from /shared directory instead of /current directory.
