### ISSUE TITLE
select max(value) from <time_series> not returning max values

### ISSUE THREAD

**Issue by thomasbernard88** [influxdb/influxdb#1356]
Hi,

InfluxDB version: InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15)

We recently noticed that selecting the max value over a given time period doesn't return the max value. Mean, percentile, median, etc seem to be fine, but max isn't. Usually it's returning a value that is much lower than mean, or percentile(97 in our case), which according to the math is not possible. Also we notice that sometimes there doesn't seem to be a value available for max (fill(0) kicks in), where this doesn't seem to be a problem for mean, percentile, etc. See also screenshots.

We noticed this behaviour in Grafana 1.9.1, as well as older Grafana versions like 1.8.1. 

We provide the values to InfluxDB as a float.

Sample query the way we do it in Grafana:
```
select mean(value) from <time series x> where $timeFilter group by time($interval) fill(0) order asc
select median(value) from <time series x> where $timeFilter group by time($interval) fill(0) order asc
select percentile(value, 97) from <time series x> where $timeFilter group by time($interval) fill(0) order asc
select max(value) from <time series x> where $timeFilter group by time($interval) fill(0) order asc
```

Screenshots:
![screen shot 2015-01-23 at 2 45 52 pm](https://cloud.githubusercontent.com/assets/10604224/5883444/a483b93a-a30f-11e4-8019-b376adb32f3b.png)
![screen shot 2015-01-23 at 2 38 57 pm](https://cloud.githubusercontent.com/assets/10604224/5883443/a482ce26-a30f-11e4-9a44-a53af9a44119.png)

Thanks in advance looking into the problem!

**Comment by thomasbernard88** [comment]
Will close this one. I made a couple curl calls to InfluxDB and based on the timeframes I get back it lets me believe this is more a Grafana issue, rather than InfluxDB.

**Comment by torkelo** [comment]
Strange. would like to confirm  that this is a grafana  issue. can you open chrome dev tools / network tab and show me the query sent to influx and the response (for the max query)
