### ISSUE TITLE
influxdb fills log space

### ISSUE THREAD

**Issue by ogreface** [influxdb/influxdb#1359]
Almost as soon as I start the db, the logs jump to over a gig in size. It's filled with this message repeating:
[2015/01/24 20:41:35 UTC] [EROR] (github.com/influxdb/influxdb/api/graphite.(*Server).Serve:120) GraphiteServer: Accept: %!(EXTRA *errors.errorString=use of closed network connection)

Influxdb itself seems to be up, working and fine. But I can't really let it run with how fast it fills the logs. This is on an EC2 instance.

**Comment by ogreface** [comment]
Sorry, appears to be a dupe.

**Comment by tdensmore** [comment]
A dupe of which ticket number? I landed here via an internet search so that info would be very helpful
