### ISSUE TITLE
some comments on the deb package

### ISSUE THREAD

**Issue by sanga** [influxdb/influxdb#1362]
I just made a simple PR to include a bit more metadata in the packages but there I still a few things I find odd.

```
⇒  dpkg --contents influxdb_0.9.sampti_amd64.deb
drwx------ 0/0               0 2015-01-25 20:18 ./
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./usr/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./usr/share/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./usr/share/doc/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./usr/share/doc/influxdb/
-rw-r--r-- 0/0             145 2015-01-25 20:18 ./usr/share/doc/influxdb/changelog.Debian.gz
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./opt/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./opt/influxdb/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./opt/influxdb/versions/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./opt/influxdb/versions/0.9.sampti/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./opt/influxdb/versions/0.9.sampti/scripts/
-rw-r--r-- 0/0            4546 2015-01-25 20:17 ./opt/influxdb/versions/0.9.sampti/scripts/init.sh
-rwxr-xr-x 0/0         9842032 2015-01-25 20:17 ./opt/influxdb/versions/0.9.sampti/influxd
-rwxr-xr-x 0/0         6372424 2015-01-25 20:17 ./opt/influxdb/versions/0.9.sampti/benchmark-multi-series
-rwxr-xr-x 0/0         6780992 2015-01-25 20:17 ./opt/influxdb/versions/0.9.sampti/benchmark
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./etc/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./etc/opt/
drwxr-xr-x 0/0               0 2015-01-25 20:18 ./etc/opt/influxdb/
-rw-r--r-- 0/0            6432 2015-01-25 20:17 ./etc/opt/influxdb/config.sample.toml

```

In no particular order:
- do you really want to include the benchmarking scripts?
- and the sample config.toml file?
- is it worth having the version in the path? (I guess this is so that one can have multiple versions installed on the same file system, but for me in practice, that 's more annoying than anything else)
- I noticed that have init.sh in /opt/... and link to it during post install - is that standard practice? It would be simpler to just drop it into /etc/init.d wouldn't it?

Please take these with a grain of salt as I'd hardly describe myself as the most experience debian admin ever but nonetheless just some things I noticed and thought I'd mention.

**Comment by otoolep** [comment]
Thanks for the questions, @sanga. Responses inline. Pleas be aware that our packaging process is not considered complete, but is work-in-progress like the rest of the 0.9.0 release.

-- the exact contents of the package are still influx.
-- yes, we want to include a working config, again some work in this area is to place.
-- the ability to downgrade quickly is very important on production systems, so we're just following the exiting process right now. It may change.
- if you look inside `/etc/init.d` on many systems -- Ubuntu 14.04 for example -- you will see lots of symlinks of this nature.

**Comment by otoolep** [comment]
Closing for now, as there is nothing actionable here right now, and packaging will continue to evolve.
