### ISSUE TITLE
Replace `mapper.fn` with functor

### ISSUE THREAD

**Issue by politician** [influxdb/influxdb#1365]
The type definition for [mapper](https://github.com/influxdb/influxdb/blob/master/influxql/engine.go#L437) includes a field `fn mapFunc` which implements the appropriate transform across a sequence of values (although apparently only `count` and `sum` are currently supported as of [eced3a347](https://github.com/influxdb/influxdb/blob/eced3a347c7851842da378e227c037ef868426af/influxql/engine.go)?). If this field were redefined as a functor (a stateful function), then implementing operations that require intermediate state (e.g. moving averages) would be straightforward.  

More generally, it looks like the processing pipeline in 0.9.0 supports operations that can be implemented as a combination of map and reduce steps, but could easily be extended to support operations that are a combination of map, scan, and reduce steps.  

Is this something that you guys have already noticed or planned for?  If not, would it be worth my time to implement this myself or is this current design in a lot of flux?

Related: https://github.com/influxdb/influxdb/issues/77

**Comment by otoolep** [comment]
@politician -- the 0.9.0 code is definitely in flux right now, and it would probably be a better use of your time to hold for a little while yet, before making major changes.

**Comment by beckettsean** [comment]
Pretty sure this is fixed with the distributed queries merge #2202.
