### ISSUE TITLE
Invalid default password in web ui

### ISSUE THREAD

**Issue by simao** [influxdb/influxdb#1368]
Hello,

After installing influxdb I am trying to access the web interface using http://localhost:8083/, but using `root/root` as credentials returns `Couldn't authenticate user: Invalid username/password`.

Am I doing something wrong?

Thank you

**Comment by otoolep** [comment]
Without more information, it's difficult to know. What version are you running? Can you provide a screen shot?

Philip

----------------------------------
http://www.philipotoole.com

**Comment by simao** [comment]
I am using v0.8.8 on ubuntu, I followed the "installing" instructions from the documentation.

here is attached a screenshot

![screenshot from 2015-01-26 17 20 19](https://cloud.githubusercontent.com/assets/203575/5919702/a86119f6-a636-11e4-9465-e35424ad18e3.png)

**Comment by otoolep** [comment]
Set the port, you haven't done that.

**Comment by simao** [comment]
I am using the default  port, 8086, and setting it in this interface doesn't change it.

**Comment by otoolep** [comment]
OK.

At this stage I suggest you fire up the developer tools on your browser and
see if you can learn more about what is coming back from InfluxDB, because
what you are doing should work fine, and there have been no other reports
of problems.

Philip

**Comment by simao** [comment]
Hi,

In developer tools I just see that the server returns a 401:

![screenshot from 2015-01-27 19 56 53](https://cloud.githubusercontent.com/assets/203575/5924766/bddbb070-a65e-11e4-9414-9012c18bd90e.png)

Thanks

**Comment by otoolep** [comment]
To be absolutely sure, I just installed the latest deb package on a 64-bit
Ubuntu VM. Everything works absolutely fine, and the system comes up with
root/root as the default. I can access the Admin UI. I can only suggest
that the credentials are not root/root, and your installation is broken.
Try re-installing, possible on a different machine.

Philip
