### ISSUE TITLE
Go driver missing from master

### ISSUE THREAD

**Issue by codepope** [influxdb/influxdb#1402]
I've been building go code that imports the go driver as

import (
	"github.com/influxdb/influxdb/client"
)

Which takes from the master repo. On the Jan 22, all the code disappeared from that directory and was replaced by what appears to be an incomplete, in development, replacement driver. Unfortunately this breaks any code that depends on it when someone wants to build from a clean development tree or updates their go src directory. I do understand that I could implement vendoring on my own code to snapshot a working version of the old code. I would have normally expected the development work to be carried out in a branch, but as this is not the case, any idea when the new driver will be complete or if there'll be a copy of the old code added to the tree which we can import from instead?

Dj

**Comment by otoolep** [comment]
@codepope -- initial development of 0.9.0 is moving along, we should be finished shortly. If you would like to vendor the code, you can find it in 0.8.8 tag.

**Comment by pauldix** [comment]
Ah, sorry about that, @codepope. This development cycle is a one off unicorn that won't be repeated again. You can find the old client here: https://github.com/influxdb/influxdb/tree/v0.8.8/client

Apologies for causing problems, I know how annoying that can be when one of your dependencies hoses your project.

0.9.0 coming soon!

**Comment by codepope** [comment]
Thanks @pauldix - would I be right in assuming it's worth vendoring the 0.8.8 code now as the 0.9.0 driver is going to have a different API?

**Comment by pauldix** [comment]
That's right, the 0.9.0 API is making breaking changes.
