### ISSUE TITLE
Implement batch writes

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1434]
writes into the server should be able to batch together. This should be behind the `WriteSeries` function call. Multiple calls to `WriteSeries` should be buffered for an amount of time.

There should be two config settings to set the max number of points to buffer before sending or the max duration to buffer before flushing.

This should be a tunable setting. The `WriteSeries` method on `Server` should be able to take a collection of points across multiple measurements. There should be an option in the `Write` struct that specifies if the write is ok to be buffered on the data node or if it should be written to the brokers immediately and a success returned before a 200 is returned to the client.

This way batches can either be handed in InfluxDB, with the risk of data loss, or batches can be handled on the client side. It should be tunable on a per write request basis.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/commit/15228425328f6816dabf07bf32a7e64d84453031
