### ISSUE TITLE
tests/siege/urlgen is mac specific

### ISSUE THREAD

**Issue by bketelsen** [influxdb/influxdb#1437]
the date format for linux is different.  See http://stackoverflow.com/questions/10990949/convert-date-time-string-to-unix-timestamp-in-bash-command

**Comment by benbjohnson** [comment]
Thanks, Brian. I expended all my bash skillz on the `getopts` switch and didn't get to OS-specific date formats. I thought about just rewriting the damn script in Go. :)

**Comment by bketelsen** [comment]
If I was any good in bash, I would have already sent a PR to fix it. :)

**Comment by pcn** [comment]
The above _date function should work (I don't have influxdb building at home, so I can't run these tests).

**Comment by pcn** [comment]
@bketelsen the script isn't in bash, so it's /bin/sh on mac, and dash on ubuntu (don't have fedora or centos to test).

**Comment by bketelsen** [comment]
Doesn't work in linux.  Can't test Mac now.

the linux date function expects "01/01/01 00:00:00" format, but as written
it's passing the "jan 01" style format.

Also, the TIME=TIME+INTERVAL function fails on Linux.

and sh complains about the let statements, too.  wish I was more help.

**Comment by pcn** [comment]
Messed up my testcase.  BRB.

**Comment by pcn** [comment]
Tested on ubuntu 12.04 and macos x 10.10.

**Comment by rothrock** [comment]
#1818 takes care of this. We now have a Go version of urlgen. See tests/urlgen/urlgen.go.
