### ISSUE TITLE
Test 3 node cluster running for multiple hours

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1440]
Write data against a 3 node cluster for multiple hours and ensure there aren't any memory leaks or it doesn't go down.

**Comment by steverweber** [comment]
related issues:
https://github.com/influxdb/influxdb/issues/1278
https://github.com/influxdb/influxdb/issues/1228
https://github.com/influxdb/influxdb/issues/941

**Comment by pauldix** [comment]
Going to close this as we're actively doing this already on the 0.9.0 release.
