### ISSUE TITLE
stucked with  option  -profile 

### ISSUE THREAD

**Issue by tictak** [influxdb/influxdb#1442]
I'm locating  a  memory leak issue   with  the -profile option ,but cpu will be stucked in a while.
then stracing the pid ,it is  on  futex_wait  state  with null timeout , childs  futex_wait on ETIMEOUT  the whole time.  [0.8.5 verison]

Scenario  as follows:
  Write frequency is about  3000*50series/min ,and each serie has one point with 90 columns.
  totally  about 20,000  series in one db, rarely query call.
  When normally started , the memory usage changes slowly, (12-15GiByte)but after two or three    day.mem will boom and oom killed by kernel. so I restarted  it,but it will stucked on the log message 
"[INFO] (github.com/influxdb/influxdb/datastore.(*ShardDatastore).GetOrCreateShard:158) DATASTORE: opening or creating shard /opt/influxdb-test/shared/data/db/shard_db_v2/00001"
 for a long long long time,more than hours (can not wait that long ) whith  100GB data in one db.
 so I strace the pid , it is reading the  LOG  file  slowly.

**Comment by pauldix** [comment]
This won't apply to 0.9.0 since it doesn't use any of the same stuff. Closing since we won't be putting more work into the 0.8 line.

**Comment by tictak** [comment]
0.9.0 will be relased soon as   described on  influxdb.com  home page   ^ & ^  ?

**Comment by pauldix** [comment]
Yes, soon. Early builds for testing next week. Full release in 4-8 weeks
