### ISSUE TITLE
Log unauthorized requests

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1444]

**Comment by corylanou** [comment]
@pauldix Do you want just the http endpoints to log this, or is this a lower level message that the server will log when `Authorize` fails.

If it is the latter, what type of details do you want in the message:

- time
- node id (I think we are going to add this to all logging at the server level)
- user
- query
- database

**Comment by pauldix** [comment]
I think it should probably be lower level, since we want to be protocol agnostic. The things you mention logging sound good.
