### ISSUE TITLE
if metrics is too many, how to disign db?

### ISSUE THREAD

**Issue by rfyiamcool** [influxdb/influxdb#1462]
if many server metrices , how to design db？

for instance  1000 server   ，each server have 20 metrices ，total 2000个metrics ，how to design db?

**Comment by otoolep** [comment]
I presume you mean how should the metrics be named? Check out the link
below for some advice for the 0.8 release:

http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html

http://influxdb.com/docs/v0.8/api/reading_and_writing_data.html

**Comment by pauldix** [comment]
Also, this question should be asked on the Google Group here: https://groups.google.com/forum/#!forum/influxdb
