### ISSUE TITLE
Make queries distributed

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1467]
Currently queries aren't distributed. The code around `CreateIterators` probably needs a bit of a refactor.

It should be able to plan an entire query, which should look up what shards need to be hit and which series ids in each of those shards needs to be queried.

There should be some sort of intermediate query struct that describes the query for a particular shard. That'll include the series ids and the filter information if filtering on a field e.g. `WHERE value > 20`.

This intermediate object is something that can be sent in a request to whatever data node has this shard.

So this will require adding a new data node endpoint that can get one of these and execute it.

**Comment by toddboom** [comment]
This was finished with PRs #2202 and #2301.
