### ISSUE TITLE
Wire up database backups

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1468]
Users need to be able to backup their metastore data and the shard data.

There should be something in the query language to back up the metastore do a given file. And to backup each shard to a given file. When executed, it would save that file on the server that received the query.

**Comment by pcn** [comment]
This seems like it should be configurable, or at least restricted to administrators to prevent a DoS by filling up filesystems that the user may not even have access to.

**Comment by pauldix** [comment]
Added in RC16
