### ISSUE TITLE
Add show stats on server

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1470]
Users should be able to show statistics for a given server through the query:

```sql
show stats on serverA
-- or
show stats on "129.23.56.2"
```

The stats should include queries per second, writes per second, values per second (different than writes if they're batching), last heartbeat time, free hd space on the data drive, number of hearbeat failures in the last 5 minutes, and replication delay (last time it received either a heartbeat or write)

I'm sure we'll think of other things to add over time.

**Comment by otoolep** [comment]
Let me take on stuff like this.

**Comment by otoolep** [comment]
A design we should consider is that the InfluxDB system has a special database e.g. "internal" into which stats about the Servers themselves are written. This would allow the system to provide historical information about itself. This is a common design in other systems.

**Comment by pauldix** [comment]
Yeah, at some point we may want to enable that. For now I just wanted an in
memory structure that could track some of these things.

**Comment by schmurfy** [comment]
I like the in-memory approach !
If a self write feature is added later please make it optional, if not used it just become useless work the server is doing.

**Comment by pauldix** [comment]
Now you can show stats by hitting a specific server. This is lower priority since there are other ways to do it so pushing it out past 0.9.0

**Comment by otoolep** [comment]
This is done, the framework is there, just need to add more and more stats as we need them.

The story for accessing across the cluster, from any node, is to query the `_internal` database. We could expand the syntax in the future to support querying other nodes, but that will require dealing with authentication.

**Comment by pauldix** [comment]
@otoolep what's the retention policy of the `_internal` database? I'm thinking we should make it 7 days by default and make it configurable.

**Comment by otoolep** [comment]
Good idea -- I mean to add that monitor config, but it slipped out of my mind. I'll take care of it.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/4015
