### ISSUE TITLE
Wire up spread aggregate function

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1476]

**Comment by corylanou** [comment]
@pauldix I'm not 100% sure on how this calculation works.  Do you have something I can reference?  I found a couple different definitions on the internet.

**Comment by pauldix** [comment]
Spread is the difference between the min and the max in an interval of time. So if the max is 23 and the min is 2, then the spread is 21. It's always a positive number

**Comment by sv** [comment]
Naming note: I think many people would expect max(series)-min(series) to be called range (http://en.wikipedia.org/wiki/Range_(statistics)) which is one of the measures for dispersion(spread) - http://en.wikipedia.org/wiki/Statistical_dispersion .
