### ISSUE TITLE
Wire up non_negative_derivative function

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1477]
This is an odd one because it can behave either like an aggregate function or not. If given a group by time, the user will have to nest another aggregate function like this:

```sql
SELECT non_negative_derivative(max(value)) from key_count
WHERE time > now() - 1h
GROUP BY time(5m)
```

If they don't supply a group by time, it should act as a transformation function that computes the derivate between one point and the next. Like this:

```sql
SELECT non_negative_derivative(value) from key_count
WHERE time > now() - 1h
GROUP BY time(5m)
```

**Comment by mercury2269** [comment]
guys any work around on performing non_negative_derivative function manually right now until 0.9.0 is released?

**Comment by hordecore** [comment]
still waiting for this cool feature :)

**Comment by jwilder** [comment]
@hordecore It's already available in the current release. See #2569.
