### ISSUE TITLE
Admin Interface

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1484]
Hi all,

I did a build of the latest influxdb git. Works fine sofar but I cannot access the admin interface. In the influxdb.conf the admin port is set 8083 but actually it is only listening to 8086. Do I miss something?

**Comment by ezotrank** [comment]
:+1:

**Comment by otoolep** [comment]
EIther your config is wrong, or you are not running the config you think. Please follow up on the mailing list if you can't make any progress, and attach your config.

**Comment by pauldix** [comment]
Were you building master or the 0.8.8 branch? If you're talking about master then this is a known issue. We haven't put the admin interface back into the build. See #1439 to track the progress on that.

The config file from previous versions of Influx won't work with 0.9.0. There is a new config file in `etc/config.sample.toml`

**Comment by otoolep** [comment]
@pauldix -- thanks.

@Sineos -- I had assumed you were building a release version from the source, 0.8.8 for example, if you are building master the Admin UI is still pending. As @pauldix, master is still in development. If you wish the build the latest released code, check out this tag: https://github.com/influxdb/influxdb/tree/v0.8.8
