### ISSUE TITLE
Wire up INTO queries

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1493]
INTO queries let the user do a select and put the resulting data into another db, retention policy, and/or measurement name. We use them in continuous queries. However, they can also be used in a general select statement to run a once off query.

These could also be used to recompute the results of a previous segment of time for a continuous query.

See the syntax for INTO queries in the INFLUXQL.md

**Comment by fxstein** [comment]
+1 
@pauldix Thank you for driving all of these critical features.

**Comment by caligula1989** [comment]
Wouldn't it be a good idea to remove CQs and the into clause from the documentation, until this is closed?

If I understand correctly, neither are working ATM.

**Comment by beckettsean** [comment]
@caligula1989 CQs work fairly well for many people, although there are still bugs to be fixed.

I don't see any references to INTO in the 0.9 documentation except as regards continuous queries, and it is already valid syntax for them. 

Also, please open documentation issues on the docs repo: influxdb/influxdb.com

**Comment by ivanscattergood** [comment]
How does this differ from #4409 ?

**Comment by pauldix** [comment]
thanks for pointing that out @ivanscattergood, this is done! :)
