### ISSUE TITLE
Joining nodes may need to retry connecting to leader

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1495]
In automated environments, it is very useful for all nodes to come up simultaneously and allow the cluster to come together. This means that nodes passed `-join` may actually come up first. This needs to be tested.

**Comment by otoolep** [comment]
This does not appear to be the case with the current code. It seems most convenient for users performing automated cluster deployments if a node that was attempting to join a cluster would retry if the target node was not up. At least, this could be configurable. This would allow them to bring up nodes in any order.

**Comment by pauldix** [comment]
The tricky part is that at some point, one of the nodes has to decide to create a cluster. Which one will it be? If the goal is to have the Puppet/Ansible/Chef configs that are the same across three machines, I don't think we can achieve that.

One of the servers has to be told to create a new cluster. But I agree that any node that has `-join` should continue to retry until it successfully joins a cluster.

**Comment by bklei** [comment]
Can the first one to come up create the cluster?  IE if it can't reach anyone else in the list, create the cluster?  Or are you worried about a second/third... node(s) coming up when an existing cluster happens to be down, and creates a competing cluster...

**Comment by otoolep** [comment]
@bklei -- that could be a concern. It's difficult to tell the difference between wanting a cluster to form something with itself if it's the first one to come up, versus a network outage causing temporary problems.

**Comment by pauldix** [comment]
It's also a race condition. The two servers could come up at roughly the
same time and one creates the cluster, but doesn't complete and start
listening for other servers before the other one tries.

**Comment by otoolep** [comment]
Not applicable with cluster-rewrite.
