### ISSUE TITLE
Admin interface does not honour configured ports

### ISSUE THREAD

**Issue by Xiol** [influxdb/influxdb#1508]
Hi,

I've had a bit of a nightmare changing the admin and API ports. I suspect there are two separate issues here.

I'd been running a standalone v0.8.8 (on CentOS 7) for a bit testing things, and wanted to change the admin and API ports due to our restrictive office firewall. I changed `[admin]`->`port` to 8443 and `[api]`->`port` to 2087 in `/opt/influxdb/shared/config.toml` and restarted influxdb, but neither port was listening when checked with `lsof`. Changing the ports back and restarting still left influxdb not listening on any port but 8090. I think this is similar to issue #198 which was for a very old version.

In the end, I had to blow away the data directory to get influxdb listening again on the ports I'd configured (8443/2087). So that's issue one - changing ports seems to require the data directory to be purged.

The main issue here though is that the admin interface is not honouring the API port. When I managed to get the ports changed and listening correctly, trying to login via the admin interface I can see the interface trying to connect to the server via port 8086 in browser dev tools, rather than the port I've configured (2086).

**Comment by pauldix** [comment]
Did you put in the new port number on the spot on that login page? It doesn't get populated automatically, so if you change the port, it's up to you to put it in the admin interface when you want to log in.
