### ISSUE TITLE
WHERE clause not effective for SHOW metadata queries

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1511]
`WHERE` clauses are not yet effective for certain `SHOW` metadata queries. `SHOW TAG KEYS` for example.

**Comment by beckettsean** [comment]
works for `SHOW TAG KEYS` and `SHOW MEASUREMENTS`. Does not work for `SHOW FIELD KEYS` but that makes sense, as it would require a full scan of all points.
