### ISSUE TITLE
On cluster join, leader heartbeat connect failures

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1521]
Start up 1 node as leader. Start up 2nd node and have it join. The leader then continually logs the following messages:

`[raft] localhost:8086 2015/02/05 16:01:32 heartbeat: Get http://localhost:8087/raft/heartbeat?commitIndex=6&leaderID=1&term=1: dial tcp 127.0.0.1:8087: connection refused`

All further operations are blocked such as "create database".

**Comment by otoolep** [comment]
@corylanou -- would it possible to enhance the new integration test, such that this failure would be exposed? If so, we fix the failure and the integration test would ensure it doesn't re-occur.

cc @benbjohnson

**Comment by corylanou** [comment]
@otoolep Yes, I think we need a `/status` endpoint that can get the current indexes of each node.  Once that is in play, we can construct pretty solid multi-node testing.  I'll get to the status endpoint first, then create a multi-node integration test.

**Comment by otoolep** [comment]
Fixed.
