### ISSUE TITLE
fill(0) return some strange value

### ISSUE THREAD

**Issue by mingio** [influxdb/influxdb#1533]
Hi, I'm newbie to influxdb. Recently I meet a strange issue.
My data is:
time	sequence_number	src
1383489299000	128230001	23
1383489299000	128220001	23
1383489199000	128210001	23
1383489198000	128200001	23

when I run :select count(src) from demo group by time(1m) fill(0), I get the result:
time	count
0	0
-60000	0
0	0
-60000	0
0	0
-60000	0
1383489240000	2
1383489180000	2

I don't know the how the -60000 and 0 come into time column?

**Comment by pddenhar** [comment]
I am also receiving this kind of strange data when running fill(0) with a group by 30s:

I get normal timepoints and then
time value
0	0
-30000	0

as the last two datapoints in the selection.
