### ISSUE TITLE
Support types other than floats for "values"

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1536]
Currently only numeric types are supported as "values" within the write.

https://github.com/influxdb/influxdb/blob/master/shard.go#L183

**Comment by otoolep** [comment]
@pauldix -- I presume a key part of this work is to return an error if someone tries to perform, say, a `mean` on a non-numeric field.

**Comment by otoolep** [comment]
We also need to cope with data that attempts to change the type i.e. a field that comes in first as a string, then next as a float. We can either reject the write outright, or attempt to cast it.

**Comment by otoolep** [comment]
If a field is a string, and then comes in as a number, casting it to a string is doable. The reverse may be more difficult.

I presumed this was addressed in 0.8. What is the policy there?

**Comment by otoolep** [comment]
cc @benbjohnson

**Comment by pauldix** [comment]
In 0.8 we didn't keep type information. If they try to write a field as a different data type, they should get an error. This check should be done before a write is sent through the broker. Basically, if the field exists in the metastore, verify that the type is the same.

**Comment by pauldix** [comment]
And yes, for numeric functions, we should verify the type of the field is either a float or an int. Actually, we may need an implementation for each data type that it supports.

Punt on that part of it for now. We can address it later.

**Comment by benbjohnson** [comment]
I talked to @philips separately but, for posterity, I'll post it here too. We can create a `FieldEncoder` and `FieldDecoder` that has a static map of fields and move the `marshalValues()` and `unmarshalValues()` onto there:

```
type FieldEncoder struct {
    Fields map[uint8]*Field
}

func (enc *FieldEncoder) EncodeField(fieldID uint8, value interface{}) (n int, err error) 
```

```
type FieldDecoder struct {
    Fields map[uint8]*Field
}

func (dec *fieldDecoder) DecodeField(fieldID uint8, b []byte) (value interface{}, n int, err error) 
```

**Comment by philips** [comment]
@benbjohnson I don't remember talking about this, wrong Philips? :)

**Comment by otoolep** [comment]
He means me. :-)

@benbjohnson and I did discuss this this morning, and clarified some stuff, about how to use the Metatstore for field-type mapping.

**Comment by benbjohnson** [comment]
lol, my bad. :)
