### ISSUE TITLE
With `ulimit -n 1024`, writing approximately 800 points in a single query crashes the influxd process

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdb/influxdb#1551]
We're on a Linux box with influxd built from source from commit 632461e20689fd0c5fcf8abdd3a120f0376da78a.  We have a script that attempts to seed the database, and we've found that when writing approximately 800 points in a single query, the influxd process usually crashes.

The individual points in the query look roughly like this:

```
{
        timestamp: time,
        precision: 'ms',
        values: { value: Math.random() },
        name: 'random_measurement_' + measurementIndex,
        tags: {
          host: 'server' + randomIndex()
        }
}
```

[Here's a gist of the stack trace from the crashed influxd](https://gist.github.com/mark-rushakoff/0c3b8d984242172ac737).  The very top of the stack trace is:

```
[srvr] 2015/02/10 11:33:59 http: Accept error: accept tcp [::]:8086: too many open files; retrying in 5ms
panic: open /root/.influxdb/broker/meta: too many open files

goroutine 7 [running]:
github.com/influxdb/influxdb/messaging.(*Broker).mustSave(0xc208038410)
	/home/mark/go/src/github.com/influxdb/influxdb/messaging/broker.go:220 +0xe7
github.com/influxdb/influxdb/messaging.(*brokerFSM).MustApply(0xc208038410, 0xc2082fa180)
	/home/mark/go/src/github.com/influxdb/influxdb/messaging/broker.go:561 +0x2eb
github.com/influxdb/influxdb/raft.funcÂ·009(0x0, 0x0)
	/home/mark/go/src/github.com/influxdb/influxdb/raft/log.go:1087 +0x8f6
github.com/influxdb/influxdb/raft.(*Log).applier(0xc208084000, 0xc2080401e0)
	/home/mark/go/src/github.com/influxdb/influxdb/raft/log.go:1095 +0x198
created by github.com/influxdb/influxdb/raft.(*Log).Open
	/home/mark/go/src/github.com/influxdb/influxdb/raft/log.go:255 +0x803
```

**Comment by otoolep** [comment]
If this happens again, run `lsof > openfiles` so we can see what is happening. We'll then take a look at what it is opening.

In the event this is a network connection issue, you should also run `netstat -n -A inet >conns`, and send that file to us too.

**Comment by otoolep** [comment]
@mark-rushakoff -- I presume you are writing a single point per HTTP request? Each of those will result in a TCP connection and may eat up the file descriptors.

**Comment by otoolep** [comment]
Closed in error.

**Comment by mark-rushakoff** [comment]
We're writing all 800 points in a single request. However, since influxd crashes partway through that request, and AFAIK `lsof` and `netstat` both take measurements at "an instant in time", will that data be meaningful?

**Comment by otoolep** [comment]
If the process has exited, probably not. But you can try writing 600 points and taking a look at the output of the commands. Or try 700 etc.

**Comment by benbjohnson** [comment]
What's the interval between timestamps and what's the duration of the retention policy?

**Comment by mark-rushakoff** [comment]
[Here's a new gist](https://gist.github.com/mark-rushakoff/2240921b1c2710f2414b) that is a little easier to use to reproduce the issue. (You may need to use the [raw view](https://gist.githubusercontent.com/mark-rushakoff/2240921b1c2710f2414b/raw/e26de0e692a2fd0e415fa56137de1eb7ae026551/influx_seed_data.json) of the JSON data because GitHub doesn't seem to render it correctly.)

With influxd built from a61baeafc2152f6ac3fc67752c93727ea8bbfd60, having run `rm -rf ~/.influxdb` and `ulimit -n 1024` before starting influxd, running the setup.sh script in the gist appears to reliably crash influxd.  The data in the JSON file should cover every minute in a 24-hour period for a total of 1440 data points. The retention policy set up in the script is duration 1h, replication 3.

**Comment by mark-rushakoff** [comment]
Now with the recent changes on master for better batching support, here's what we've found when `ulimit -n` is 1024:

Points inserted during single request | Query Duration (ms) | Server stays alive?
-------------------------- | -----------------------| -------
1440 | 352 | Yes
2880 | 269 | Yes
8640 | 688 | Yes
17280 | 1239 | Yes
43200 | 2874 | Yes
49372 | 4007 | Yes
52364 | 3602 | Yes
55742 | 3917 | Yes
86400 | 4914 | Yes
96000 | 5435 | Yes
108000 | 6242 | Yes
144000 | 9191 | Yes

(The query durations were all a sample size of 1 and should not be considered scientific :) )

As we further increased the points inserted in a single request, our system (with 1GB of RAM) was running out of memory. It looks like the ulimit issue is fixed.
