### ISSUE TITLE
"DROP" data commands return incorrect error messages

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1553]
`DROP MEASUREMENT <name>`, returns the following error: `{"error":"error parsing query: found MEASUREMENT, expected SERIES, CONTINUOUS at line 1, char 6"}`. This output needs to include all valid targets for `DROP` commands.

**Comment by beckettsean** [comment]
Output seems correct now:

```
> drop measurement
ERR: error parsing query: found EOF, expected identifier at line 1, char 18

> drop measurement foobar
ERR: measurement not found: foobar

> drop
ERR: error parsing query: found EOF, expected SERIES, CONTINUOUS, MEASUREMENT at line 1, char 6
> 
```
