### ISSUE TITLE
After inserting data with tags, querying that data returns out of order

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdb/influxdb#1582]
[Here's a gist to reproduce the issue](https://gist.github.com/mark-rushakoff/4bee61321d54f4fbd5f6).

Run `ruby issue.rb | less` and see that the timestamps appear in random order.

We reproduced this on InfluxDB built from commit 13c437ab6ccfa6871e58b37d0dcc802991ba4b19. If you comment out the `host: 'server'` line in the script and re-run it, the data comes back in order.

**Comment by otoolep** [comment]
I am deep in this code at the moment. Let me take a look.

**Comment by otoolep** [comment]
Just for kicks, can you try increasing the sleep delay in that gist to 10 seconds?

**Comment by mark-rushakoff** [comment]
When we increase the sleep from 1 second to 10 seconds, the data does arrive in order.

**Comment by otoolep** [comment]
Right, so this is what I saw too last night when I attempted to repro your failure. I have been seeing this kind of behaviour for a while now -- either it's latencies in our system, or something OS-level like file cache flushing (though, in both cases, 10 seconds is an eternity). @benbjohnson may know more.

**Comment by mark-rushakoff** [comment]
Our reduced test case from the script does work better with the 10 second sleep, but we noticed that our real use is still coming back out of order, even well after 10 seconds. Right now, we're not sure what's different other than having a larger data set, so we'll play around with this a little more.

**Comment by 121watts** [comment]
here's the updated code and findings:

https://gist.github.com/121watts/1c589032047671cdc952

**Comment by pauldix** [comment]
I don't think the sleep has anything to do with it. Here's an updated script that will give you more info: https://gist.github.com/pauldix/adc059e066addba3d305

What we're seeing here is multiple issues:

1.  The writes don't actually complete. The request times out before all the points get written.
2.  The query to return the raw values returns them out of order (this should be an easy fix)
3. The count aggregate query is returning intervals with zero counts when it shouldn't (fill isn't implemented and even then wasn't specified)
4.  The mean aggregate query isn't returning any data

If you drastically reduce the number of points being written. Set `earlier = now - (60 * 60)`, then you see that all the writes succeed. Further, the mean query will actually return data.

So there may be a problem where a write is getting corrupted, which causes the mean function to not work. And if you're writing a bunch of stuff in a single request, it just fails in the middle and not everything gets written.

**Comment by otoolep** [comment]
@pauldix -- as for point 2, I presume this is only a problem when the raw data is coming from multiple series? Every individual series is written in time-ordered on the disk after all, so explicitly ordering a read of a single series should not strictly be necessary, correct? Can you confirm?
