### ISSUE TITLE
Create database doesn't work

### ISSUE THREAD

**Issue by cmizzi** [influxdb/influxdb#1584]
Hi!

I just tried InfluxDB 0.9 and I cannot create database. I tried with CLI, with Curl and the script just turning a while, wihout result.

Curl : 
```curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"```

InfluxDB (CLI) : 
```CREATE DATABASE mydb```

I looked the Influx log and when I execute queries like above, I don't have any print of it.

```
[http] ::1 - - [12/Feb/2015:07:52:05 +0100] POST /write?u=root&p=root HTTP/1.1 500 33 - curl/7.37.1 a795e9eb-b283-11e4-a03d-74d4359d9237
[http] ::1 - - [12/Feb/2015:07:52:29 +0100] GET /query?u=root&p=root HTTP/1.1 200 2 - curl/7.37.1 b6686289-b283-11e4-a03d-74d4359d9237
[http] 127.0.0.1 - - [12/Feb/2015:07:52:37 +0100] GET /query?db=mydb&q=show+databases HTTP/1.1 200 59 - Go 1.1 package http bb248d83-b283-11e4-a03d-74d4359d9237
[http] 127.0.0.1 - - [12/Feb/2015:07:53:02 +0100] GET /query?db=mydb&q=show+databases HTTP/1.1 200 59 - Go 1.1 package http c9a5a68d-b283-11e4-a03d-74d4359d9237
[srvr] 2015/02/12 07:55:31 retention policy enforcement check commencing
```

With a ruby script, I have the following error (timeRequest) : 
```
#!/usr/bin/env ruby

require 'net/http'
require 'uri'
require 'json'

http = Net::HTTP.new('localhost', 8086)
http.get('/query?' + URI.escape('q=CREATE DATABASE mydb'))
```
```
/usr/lib/ruby/1.9.1/net/protocol.rb:146:in `rescue in rbuf_fill': Timeout::Error (Timeout::Error)
	from /usr/lib/ruby/1.9.1/net/protocol.rb:140:in `rbuf_fill'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:122:in `readuntil'
	from /usr/lib/ruby/1.9.1/net/protocol.rb:132:in `readline'
	from /usr/lib/ruby/1.9.1/net/http.rb:2563:in `read_status_line'
	from /usr/lib/ruby/1.9.1/net/http.rb:2552:in `read_new'
	from /usr/lib/ruby/1.9.1/net/http.rb:1320:in `block in transport_request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `catch'
	from /usr/lib/ruby/1.9.1/net/http.rb:1317:in `transport_request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1294:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1287:in `block in request'
	from /usr/lib/ruby/1.9.1/net/http.rb:746:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1027:in `get'
	from influx.rb:9:in `<main>'
```

**Comment by otoolep** [comment]
Please show us the entire output from `curl`. For example:

$ curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE
mydb"
{"results":[{}]}
$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode
"q=SHOW DATABASES"
{
    "results": [
        {
            "rows": [
                {
                    "columns": [
                        "name"
                    ],
                    "values": [
                        [
                            "mydb"
                        ]
                    ]
                }
            ]
        }
    ]
}

**Comment by cmizzi** [comment]
All is right now.
I've downloaded and compiled from Git with InfluxDB 0.8 installed (but not running). I saw that InfluxDB 0.9 took my InfluxDB 0.8 file configuration. I think it was the problem.

**Comment by pbooth** [comment]
Is the "right way" for influxdb 0.9 with Ruby to use the ruby API, generate HTTP requests, or just use the CLI?

**Comment by cmizzi** [comment]
It's better to use API or CLI because of maintainability with often upgrades insteads of simples HTTP requests (you have to rewrite HTTP request everywhere if the syntax is changed and parse everything handly)

**Comment by yasha145** [comment]
@eelectron I am also getting same error... How to proceed?
