### ISSUE TITLE
Negative Lookaheads

### ISSUE THREAD

**Issue by DaveBlooman** [influxdb/influxdb#1586]
Hi, I'm trying to use a negative lookahead in order to match queries that do not include strings in my capture group.  Here is the query

```sh
select mean(value) from /.*example.query.for.data.(?!(?:Home|BBC_News)).*/ where $timeFilter and value > 2000 group by time($interval) order asc
```
Where my matches are

```sh
example.query.for.data.BBC_News_-_UK
example.query.for.data.babwaewae       -match
example.query.for.data.davey343434     -match
example.query.for.data.Home
```

I am using Grafana for the front end, is this feature supported in InfluxDB?

**Comment by beckettsean** [comment]
Series names + tags in 0.9.0 are substantially different from 0.8.8 series names. The need for this is likely substantially if not totally mitigated with a 0.9.0 schema.

**Comment by ushuz** [comment]
@DaveBlooman maybe because Go regex doesn't support negative lookahead, see http://stackoverflow.com/questions/26771592/negative-look-ahead-go-regular-expressions
