### ISSUE TITLE
Wire up difference aggregate function

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1590]
Takes the difference between one group by interval and another. The user should be able to stack this to specify the behavior like this:

```sql
SELECT difference(mean(value)) from key_count
WHERE time > now() - 1h
GROUP BY time(5m)
```

If no group by time is given, then it should be a transformation function that takes the difference between one point and another. In that case they shouldn't be able to nest function calls like this.

**Comment by dgnorton** [comment]
Closing.  Duplicate of #1825
