### ISSUE TITLE
build link broken

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1617]
[Here](https://github.com/influxdb/influxdb#building) the link [follow along on our docs](https://github.com/influxdb/influxdb/blob/master/docs/contributing.md) is broken. What is best way to build from source? I am following [this](https://github.com/influxdb/influxdb/blob/master/docs/packaging.md) instead.

**Comment by corylanou** [comment]
We recently moved that link.  I'll do a PR to update the docs.  Good catch!  Thanks!

**Comment by otoolep** [comment]
Ah, OK -- thanks. This was due to a recent change in the location of that file. Looks like @corylanou is on it.

**Comment by dashesy** [comment]
sorry to re-open but [link](http://github.com/influxdb/influxdb/blob/master/contributing.md) is still broken, it should be all capital like [this](https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md). 

Also while you are at it can you add a line `go get golang.org/x/tools/cmd/cover` because the last test requires cover tool.

**Comment by otoolep** [comment]
Fixed:

https://github.com/influxdb/influxdb/commit/bc1640f78abc329d2252f81116f7d5ee21e5365c

**Comment by corylanou** [comment]
@otoolep I'll open a new PR to update for the cover tool unless you are already doing it.

**Comment by otoolep** [comment]
Go for it @corylanou

**Comment by corylanou** [comment]
Added go cover reference in https://github.com/influxdb/influxdb/pull/1619
