### ISSUE TITLE
Defaulting port on admin interface

### ISSUE THREAD

**Issue by DustinChaloupka** [influxdb/influxdb#1621]
Hey all,

Was wondering if there was a way to not specify a port on the admin interface or have it not worry about it in a config some place?  It looks like it just defaults to `8086` if not specified.  I have influxdb sitting behind a proxy service and would like to only give the host and have it properly connect.

The current workaround is to just give a port that is open so that it does not get a connection refused and properly configuring the proxy config so that it handles the host header fine.

**Comment by otoolep** [comment]
What version of InfluxDB are you talking about?

**Comment by DustinChaloupka** [comment]
0.8.5 is the version I am running.

**Comment by toddboom** [comment]
@DustinChaloupka Do you mean that when you have the admin interface running, you'd like it to be usable without having to enter username/password/host/port?

**Comment by DustinChaloupka** [comment]
Just the port.

As an example: currently without the port it makes a GET request to `http://some.host.com:8086/cluster_admins/authenticate?u=root&p=root` when instead, with my proxy service, I would like it to be `http://some.host.com/cluster_admins/authenticate?u=root&p=root`.

**Comment by rubbish** [comment]
@DustinChaloupka and I ran into this because we're running influxdb behind a load balancer that runs on port 80. So if we configure the influxdb admin interface to a certain port and change the reverse proxy to handle that, however, influxdb 0.8.5 wants to keep appending the port onto the URLs it generates, which then won't work if the loadbalancer is listening on a specific hostname/port. 

Is there any configuration for an "advertised" url? Or for the links to actually be relative instead of absolute?

**Comment by n1tr0g** [comment]
:+1:

**Comment by Gurado** [comment]
:+1:

**Comment by toddboom** [comment]
I'm curious if this will still be an issue once #2746 is merged. Does changing the port to `:80` solve the problem?

**Comment by adamdecaf** [comment]
@toddboom If it was 80 by default? No, we setup all our applications to just grab a random port available on the node they're launched on and register it. Then we have our load balancers discover and group the apps and their registered ports. So we'd still like to have the option to pick and launch from a random port in the mainline source.

**Comment by beckettsean** [comment]
probably fixed by new admin interface. Please try with 0.9.1. There will be no further development on 0.8.x

**Comment by adamdecaf** [comment]
@beckettsean Would `bind-address` be the proper config to override in this case? It seems like a few subprojects in there use that. (Found that [over in the docs](https://influxdb.com/docs/v0.9/administration/config.html))

**Comment by beckettsean** [comment]
@adamdecaf that is correct for 0.9.x. The original report from @DustinChaloupka was for 0.8.5.
