### ISSUE TITLE
write & select after retention policy check

### ISSUE THREAD

**Issue by dgnorton** [influxdb/influxdb#1622]
After retention policy cleans up old data, `SELECT` from newly written data returns no rows.

Repro steps:

- `rm -rf ~/.influxdb`   (will delete ALL data)
- `./influxd -config issue1622.toml`  (toml file https://gist.github.com/dgnorton/f8d9e6765c30ba95887d)
- in a separate terminal window, `./issue1622.sh`  (shell scirpt https://gist.github.com/dgnorton/71c37265159c96fe5664)

**Comment by otoolep** [comment]
I can't repro this, I think it should be closed. The script is continually writing into the past.
