### ISSUE TITLE
Add flag to config that disables running CQs

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1633]
This is useful if the user gets into a state where some CQ is crashing their system because of memory problems or something.

If this flag is set to true, both the brokers and data nodes should ignore any CQ processing. Then the user will be able to drop the offending CQ and re-enable things.

**Comment by corylanou** [comment]
I don't know if we have addressed "hot restarts" yet, but I think our system is close to supporting this.  Would it be useful if this could be changed without downing the server?

**Comment by pauldix** [comment]
Not really since this feature is really only for the use case in which running CQs has taken your server down. Basically, they'll already be down. They need to set this so it'll come back up without immediately going down again.

**Comment by otoolep** [comment]
CC @rothrock

**Comment by rothrock** [comment]
commit f9a90f2
