### ISSUE TITLE
Support wildcards with explicit fields in SELECT

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1634]
The system should support query statements such as:

`SELECT *,value FROM cpu`

**Comment by otoolep** [comment]
This is not critical, but other SQL-like engines support it, so ours should for completeness' sake.

**Comment by pauldix** [comment]
This doesn't make sense to me since `*` will include `value`. I'm comfortable breaking with SQL on this one. Particularly since we have in other places as well.
