### ISSUE TITLE
500: json: cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1635]
I created a database without default retention policy, when trying to push to it at first it gave this error:
`No default retention policy` which makes sense.
However upon third try (still no retention policy) I get this:
`500: json: cannot unmarshal number into Go value of type string`

It would be helpful to know which row caused this latter error, but nevertheless I wonder why the error changed. With no retention policy specified it rejected the write (and rightly so) but did it keep something that now is causing the second error message instead of keep returning the same error?

I will try to make this reproducible with a smaller dataframe than what I have now.

P.S. this is master branch

**Comment by dashesy** [comment]
Ok I found the problem, in the top-level `tags` (that is shared by all the points) I have this:
```python
{'age': 42,
 'loc': u'r',
 'pk': u'0663b21bc0124f32a10fbd20ba1d1f55'}
```

As you can see `age` is a number and not a string, (it means tags should be all strings). What is interesting is that when it is not so, no other error is processed, not retention policy, and even not even if the database exists. When I make that a string I get those errors (as expected).

**Comment by corylanou** [comment]
Json is wrapped in double quotes as, not single quotes.

You can see that the data fails in a basic decode in this example due to single quotes:

http://play.golang.org/p/v47ljPOsjy

But this will work:

http://play.golang.org/p/wiVcPQoDoh


As to not checking retention policies, etc, this is by design.  If we can't parse the data we were sent, there is no need to move further into the code and check retention policies, etc, as we already know we can't parse the data to be written.


Let me know if I can help further.

**Comment by dashesy** [comment]
sorry for confusion but the above is the Python dict (which then is then converted to json), what is sent as json is this:
`{"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": "42", "loc": "r"}`

and what results in error is this:
`{"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": 42, "loc": "r"}`

**Comment by dashesy** [comment]
In fact this is the entire json:
```json
{"points": [{"timestamp": 1423291014371, "values": {"value": 0.9106188398244797}, "name": "amiigo.bio.P"}, {"timestamp": 1423291014371, "values": {"value": 1743.64183908829}, "name": "amiigo.bio.amp.pp.pp"}, {"timestamp": 1423291014371, "values": {"value": 47.033864620753555}, "name": "amiigo.bio.bpm"}, {"timestamp": 1423291014371, "values": {"value": 0.9907836920022964}, "name": "amiigo.bio.delta"}, {"timestamp": 1423291014371, "values": {"value": 149.7373706779106}, "name": "amiigo.bio.hrv.rms.low"}, {"timestamp": 1423291014371, "values": {"value": 132.23647784354355}, "name": "amiigo.bio.hrv.rms.low.err"}, {"timestamp": 1423291014371, "values": {"value": 18}, "name": "amiigo.bio.ir.offset"}, {"timestamp": 1423291014371, "values": {"value": 44.317652371928986}, "name": "amiigo.bio.pp.vol"}, {"timestamp": 1423291014371, "values": {"value": 6.868486073127329}, "name": "amiigo.bio.pp.vol.err"}, {"timestamp": 1423291014371, "values": {"value": 7.878352479068912}, "name": "amiigo.bio.pp.volv"}, {"timestamp": 1423291014371, "values": {"value": 27.838762786567006}, "name": "amiigo.bio.stemp"}, {"timestamp": 1423291014371, "values": {"value": "2015-02-07 06:36:54.371000+00:00"}, "name": "amiigo.bio.boz"}, {"timestamp": 1423291434371, "values": {"value": 0.9195439863032023}, "name": "amiigo.bio.P"}, {"timestamp": 1423291434371, "values": {"value": 4.9714878984201265}, "name": "amiigo.bio.brdb"}, {"timestamp": 1423291434371, "values": {"value": 17.0}, "name": "amiigo.bio.brpm"}, {"timestamp": 1423291434371, "values": {"value": 16}, "name": "amiigo.bio.ir.offset"}, {"timestamp": 1423291434371, "values": {"value": 33.00223625747619}, "name": "amiigo.bio.stemp"}, {"timestamp": 1423291434371, "values": {"value": "2015-02-07 06:43:54.371000+00:00"}, "name": "amiigo.bio.boz"}, {"timestamp": 1423291853371, "values": {"value": 0.8865420697240272}, "name": "amiigo.bio.P"}, {"timestamp": 1423291853371, "values": {"value": 5.094478435823308}, "name": "amiigo.bio.brdb"}, {"timestamp": 1423291853371, "values": {"value": 17.0}, "name": "amiigo.bio.brpm"}, {"timestamp": 1423291853371, "values": {"value": 16}, "name": "amiigo.bio.ir.offset"}, {"timestamp": 1423291853371, "values": {"value": 33.63311537066874}, "name": "amiigo.bio.stemp"}, {"timestamp": 1423291853371, "values": {"value": "2015-02-07 06:50:53.371000+00:00"}, "name": "amiigo.bio.boz"}], "precision": "ms", "tags": {"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": 42, "loc": "r", "sex": "m"}}

```

**Comment by corylanou** [comment]
Ok, let me take a look and see what I can find. Thanks!

**Comment by corylanou** [comment]
It looks like we need to update our documentation more for the 0.9.0 as it pertains so the data structure.

Tags can only be strings (key and value).  They are defined in the system as `Tags map[string]string`.

Here is the full data structure:

```go
// Point defines the values that will be written to the database                                                                                                                                                                                                               
type Point struct {                                                                                                                                                                                                                                                            
  Name      string                 `json:"name"`                                                                                                                                                                                                                               
  Tags      map[string]string      `json:"tags"`                                                                                                                                                                                                                               
  Timestamp Timestamp              `json:"timestamp"`                                                                                                                                                                                                                          
  Values    map[string]interface{} `json:"values"`                                                                                                                                                                                                                             
  Precision string                 `json:"precision"`                                                                                                                                                                                                                          
}  
```

Special thanks to @mark-rushakoff for digging into this one.

Let me know if there is anything else I can help with.

**Comment by dashesy** [comment]
@corylanou thanks for clarification, so this a documentation issue as long as it is specified it is all good, thanks.

**Comment by otoolep** [comment]
FWIW, this restriction on tag key and value types *is* specified in the 0.9
documentation. However, anything we can do to make it clearer is definitely
worthwhile.

Philip

**Comment by dashesy** [comment]
Ah silly me now I see it (with `must`)! I think a better error message could help but this issue is fixed

**Comment by ReetiR** [comment]
```func writePoints(con *client.Client) error { var ( shapes = []string{"circle", "rectangle", "square", "triangle"} colors = []string{"red", "blue", "green"} sampleSize = 1000 pts = make([]client.Point, sampleSize) ) rand.Seed(42) for i := 0; i < sampleSize; i++ { pts[i] = client.Point{ Measurement: "shapes", Tags: map[string]string{ "color": strconv.Itoa(rand.Intn(len(colors))), "shape": strconv.Itoa(rand.Intn(len(shapes))), }, Fields: map[string]interface{}{ "value": rand.Intn(sampleSize), }, Time: time.Now(), Precision: "s", } } bps := client.BatchPoints{ Points: pts, Database: MyDB, RetentionPolicy: "default", } _, err := con.Write(bps) if err != nil { log.Fatal(err) } return err }```

This gives an error: json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }

What is the solution?
