### ISSUE TITLE
Don't store number of fields in encoded data

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1636]
It's not clear that the code needs to store the number of fields in the encoded field-values. Instead, when decoding, the system could just iterate over the slice. This would save a byte per encoded field-values.

@benbjohnson -- any reason this wouldn't work?

cc @pauldix

**Comment by otoolep** [comment]
Fixed.

**Comment by tisba** [comment]
@otoolep The CHANGELOG.md states that this is a breaking change. Will there be a migration path from 0.8.x?

**Comment by pauldix** [comment]
@tisba there will be a migration path. See http://influxdb.com/docs/v0.8/advanced_topics/schema_design.html#migration-to-0.9.0 for details on how to structure things in 0.8 to make the migration to 0.9 clean. We haven't written the migration tool yet, but will do so before the full 0.9.0 release.
