### ISSUE TITLE
Parsing timestamp string offset

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1638]
Parsing shared timestamp in shared location (top-level) does not consider `precision` and fails.
This is the error:
```500: parsing time "1423291014371" as ""2006-01-02T15:04:05Z07:00"": cannot parse "1423291014371" as """```

And this is the json string:
```json
'{"timestamp": 1423291014371, "points": [{"values": {"value": 0.9106188398244797}, "name": "amiigo.bio.P"}, {"values": {"value": 1743.64183908829}, "name": "amiigo.bio.amp.pp.pp"}, {"values": {"value": 47.033864620753555}, "name": "amiigo.bio.bpm"}, {"values": {"value": 0.9907836920022964}, "name": "amiigo.bio.delta"}, {"values": {"value": 149.7373706779106}, "name": "amiigo.bio.hrv.rms.low"}, {"values": {"value": 132.23647784354355}, "name": "amiigo.bio.hrv.rms.low.err"}, {"values": {"value": 18}, "name": "amiigo.bio.ir.offset"}, {"values": {"value": 44.317652371928986}, "name": "amiigo.bio.pp.vol"}, {"values": {"value": 6.868486073127329}, "name": "amiigo.bio.pp.vol.err"}, {"values": {"value": 7.878352479068912}, "name": "amiigo.bio.pp.volv"}, {"values": {"value": 27.838762786567006}, "name": "amiigo.bio.stemp"}], "precision": "ms", "tags": {"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": 42, "loc": "r"}}'
```

As can be seen `"precision": "ms"` is specified so time should be `'2015-02-06T22:36:54.371-0800'
` and not 2006, also it seems it cannot parse it anyways.

[Here](https://gist.github.com/dashesy/4fe11ffd2d057dafcd98) is a gist to try writing this.

**Comment by dashesy** [comment]
This is perhaps another issue, but related:

To find a workaround I tried using the string representation of timestamp but now I get this:
```500: parsing time ""2015-02-06T22:36:54.371000-0800"" as ""2006-01-02T15:04:05Z07:00"": cannot parse "-0800"" as "Z07:00"
```
[documentation](http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#timestamp-format) does specify timezone can be specified

**Comment by corylanou** [comment]
I suspect your invalid tags are causing this error.  I see in our system that we are throwing the wrong error message as a result of it, which is for sure a bug, but the actual cause of this is the invalid tag data yet.

I'll open a PR to fix the error message.

**Comment by dashesy** [comment]
Yes, fixing the tags solves the original issue, but the second one (using the utc string) still persists.
This is the json:
```json
'{"timestamp": "2015-02-07T06:36:54.371000+0000", "points": [{"values": {"value": 0.9106188398244797}, "name": "amiigo.bio.P"}, {"values": {"value": 1743.64183908829}, "name": "amiigo.bio.amp.pp.pp"}, {"values": {"value": 47.033864620753555}, "name": "amiigo.bio.bpm"}, {"values": {"value": 0.9907836920022964}, "name": "amiigo.bio.delta"}, {"values": {"value": 149.7373706779106}, "name": "amiigo.bio.hrv.rms.low"}, {"values": {"value": 132.23647784354355}, "name": "amiigo.bio.hrv.rms.low.err"}, {"values": {"value": 18}, "name": "amiigo.bio.ir.offset"}, {"values": {"value": 44.317652371928986}, "name": "amiigo.bio.pp.vol"}, {"values": {"value": 6.868486073127329}, "name": "amiigo.bio.pp.vol.err"}, {"values": {"value": 7.878352479068912}, "name": "amiigo.bio.pp.volv"}, {"values": {"value": 27.838762786567006}, "name": "amiigo.bio.stemp"}], "precision": "ms", "tags": {"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": "42", "loc": "r"}}'
```
And first line in [this gist](https://gist.github.com/dashesy/4fe11ffd2d057dafcd98) shows it.

**Comment by corylanou** [comment]
Precision probably should not play a part when not specifying time in epoch.  If you are using the RFC3339Nano or RFC3339 the parser will recognize it and parse accordingly.

This data will work:

```sh
curl -XPOST 'http://localhost:8086/write' -d '{"timestamp": "2015-02-07T06:36:54.371000000-00:00", "points": [{"values": {"value": 0.9106188398244797}, "name": "amiigo.bio.P"}, {"values": {"value": 1743.64183908829}, "name": "amiigo.bio.amp.pp.pp"}, {"values": {"value": 47.033864620753555}, "name": "amiigo.bio.bpm"}, {"values": {"value": 0.9907836920022964}, "name": "amiigo.bio.delta"}, {"values": {"value": 149.7373706779106}, "name": "amiigo.bio.hrv.rms.low"}, {"values": {"value": 132.23647784354355}, "name": "amiigo.bio.hrv.rms.low.err"}, {"values": {"value": 18}, "name": "amiigo.bio.ir.offset"}, {"values": {"value": 44.317652371928986}, "name": "amiigo.bio.pp.vol"}, {"values": {"value": 6.868486073127329}, "name": "amiigo.bio.pp.vol.err"}, {"values": {"value": 7.878352479068912}, "name": "amiigo.bio.pp.volv"}, {"values": {"value": 27.838762786567006}, "name": "amiigo.bio.stemp"}], "tags": {"pk": "0663b21bc0124f32a10fbd20ba1d1f55", "age": "42", "loc": "r"}}'
```

You still need to specify a database in the query yet, but the data will unmarshal properly now.

I will open a PR that to update documentation that precision only should matter if you send in epoch time.  I'll also fix the code to not try to change precision on RFC3339 and RFC3339Nano parsed date/times.

**Comment by corylanou** [comment]
@pauldix this issue arose as we allow precision to be specified even if they send in the date in a non-epoch format.  Go can translate most formats, but if we want to support some type of `RFC3339Microsecond` (I made that up) we would need some custom marshaling.

As I'm not that clear on the use case for something like that, I'll let you decide if we should support it or not.

I think this issue specifically arose out of documentation not being clear that Precision is ignored if the time is not in epoch time (integer value).

**Comment by dashesy** [comment]
There is also always a chance that one may mix and match, like providing a shared timestamp in utc string format (which must be in nano second to work then) but some data points could override timestamp. If that mode is supported then it is always useful to be able to always specify `precision` in the top block.

**Comment by corylanou** [comment]
If you specify an actual point in epoch with precision, that is supported, even if the top level is in RFC3339Nano.

**Comment by dashesy** [comment]
On a second look, it seems `2015-02-06T22:36:54.371000000-0000` even though it is in nanoseconds is not supported, it is more the timezone string `0000` vs `00:00` , I am going to see why Python converts timestamp like this, if that is the case this issue is also resolved, sorry for the noise.

**Comment by dashesy** [comment]
Yes, it is the time offset string `00:00` is accepted but `0000` is not, [both valid](http://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) in RFC3339 but apparently Python likes the second form.

**Comment by contentfree** [comment]
Are tags only allowed to be strings? I can't find any mention of that in the docs. (What made @dashesy's tags invalid originally?)

**Comment by otoolep** [comment]
@contentfree -- here you go.

http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#tags

**Comment by contentfree** [comment]
Thanks @otoolep. Must've been blind…

**Comment by beckettsean** [comment]
JSON write path deprecated, line protocol only accepts UNIX epoch timestamps.
