### ISSUE TITLE
CQ unit test needs to be re-enabled

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1643]
At some point we need to look into why this change had to be made:

https://github.com/influxdb/influxdb/pull/1640/files

and fix the underlying issue.

@corylanou @pauldix

**Comment by corylanou** [comment]
My bad, I should of logged an issue when I did the PR.  I'll be more diligent moving forward.

**Comment by corylanou** [comment]
Duplicate of #1666
