### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1646]
Posting a write with 2395 points in about 44 series (when it does not crash) results in this error:

```
500: Post http://dashesy:8086/messaging/messages?topicID=0&type=80: dial tcp 127.0.0.1:8086: too many open files
```

my ulimit is unlimited, should I bump something else too?

P.S. should I post bugs I see here, or you prefer we wait because I know you are working hard on the master for 0.9 release and in the meanwhile it may not be suitable for testing? Also if you have some verbose logging I can enable to help you that will help, I have no experience in go but I can get a look myself for small patches perhaps after reading some of the commits.

**Comment by otoolep** [comment]
Thanks @dashesy -- filing issues is very helpful, you can continue to do so. 

In this case, are you sure `ulimit` is unlimited? How did you check this? How are launching `influxd`?

**Comment by dashesy** [comment]
I launch it not as a demon like this: `~/xdev/gocodez/bin/influxd -config /home/dashesy/influxdb.conf` inside the conf file I have all files to be written to `/home/dashesy/.influxdb` so that I can delete and try other things.

When I run `ulimit` in command line it responds `unlimited` and I am running `influxd` as my user (like above), so it should have same restrictions as me.

**Comment by otoolep** [comment]
Please show me the output of `ulimit -a`.

**Comment by otoolep** [comment]
Closed in error.

**Comment by dashesy** [comment]
Here it is:

```text
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 95667
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by pcn** [comment]
```
open files                      (-n) 1024
```

**Comment by dashesy** [comment]
ah I see now! thanks
