### ISSUE TITLE
error parsing query with regexp for series

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1651]
When I try to get all series like this `select * from /.*/`:

```bash
curl -G 'http://localhost:8086/query' --data-urlencode "q=SELECT * FROM /.*/" --data-urlencode "db=processed"
```
I get this error: `400: error parsing query: found /, expected identifier at line 1, char 15`

**Comment by btashton** [comment]
I am seeing this as well on RC4, it blocks further testing of this release for us as we extensively query via regex.

**Comment by btashton** [comment]
Looks like this has been fixed?

**Comment by dashesy** [comment]
I tried `'SELECT * from /.*/'` and I get `500: unknown field or tag name in select clause: age` which is a weird error because I did not specify `age` there.

**Comment by dashesy** [comment]
Just so that all can see the error perform `'SELECT * from /.*/'` on `_internal` database:
```
query_indb_df(auth, 'SELECT * from /.*/', database="_internal")
```
results in:
```
500: unknown field or tag name in select clause: alloc
```

**Comment by btashton** [comment]
I just pulled down rc18 and ran this:
```bash
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

# Write your data to your new database.
curl -XPOST 'http://localhost:8086/write' -d '
{
    "database": "mydb",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
}
'
curl -G http://localhost:8086/query --data-urlencode "q=select * from /.*/" --data-urlencode "db=mydb"

{"results":[{"series":[{"name":"cpu_load_short","columns":["time","value"],"values":[["2009-11-10T23:00:00Z",0.64]]}]}]}


```

**Comment by dashesy** [comment]
ok I am running `rc17` will update tonight and test again, if you know this is a fix in `rc18` then please go ahead and close the issue.
