### ISSUE TITLE
"LIMIT" not functioning

### ISSUE THREAD

**Issue by jnutzmann** [influxdb/influxdb#1652]
When running this query: 

`SELECT value FROM my_data_series LIMIT 2` 

the same results (115 points) are returned as this query:

`SELECT value FROM my_data_series`

I'm running on the latest version of master.

**Comment by jnutzmann** [comment]
Here is a shell script to reproduce the problem (with data):

https://gist.github.com/jnutzmann/8ecdf6b5de8edb63da32

A query that has "LIMIT 10" specified, returns all the data.

**Comment by pauldix** [comment]
We need documentation around how LIMIT work. LIMIT works on the number of series returned in the result, not the number of data points returned per series. For that limit the query based on time or we'll have additional limits for the number of points per series later. See #1709

**Comment by duylong** [comment]
Yes, I have the same confusion. I want to use "LIMIT" in order to limit the results but with lots of data, my browser crashes. How to limit the number ?
