### ISSUE TITLE
mean(...) query fails when using group by time with no data in one time period

### ISSUE THREAD

**Issue by jnutzmann** [influxdb/influxdb#1654]
When running a query for the mean value with a `GROUP BY time(...)` specified, no data is returned when one of the time periods has no data present.  For example, this query fails to return data (HTTP 200 with no response payload):

`SELECT mean(value) FROM my_data_series GROUP BY time(10h)`

because there is a 10 hour gap in data, whereas this query succeeds (and returns the average for the 11 hour periods)

`SELECT mean(value) FROM my_data_series GROUP BY time(11h)`

Perhaps it should return `NaN` or simply no point for that time period?

**Comment by jnutzmann** [comment]
Here is a shell script to reproduce the problem (with data):

https://gist.github.com/jnutzmann/afbf9ceea90bec24df66

We notice the first query succeeds, but the second returns no data.

**Comment by pauldix** [comment]
Can you try again on RC6 and let us know if it's still a problem? We fixed some bugs there. Thanks!

**Comment by jnutzmann** [comment]
Fixed now in master.  Thanks!
