### ISSUE TITLE
Add http endpoint `/index`

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#1655]
Add an endpoint for `/index` that we can query the current index of each node.  This is primarily for testing.

This could initially return a `uint64` as the body of the response.

@benbjohnson please add any additional requests you would like to see on this and I'll knock it out.

**Comment by pauldix** [comment]
Would this be more useful if you could pass in an index number that it should block and wait for and the return after that?

**Comment by corylanou** [comment]
I think that's fair.  If you pass in an id like `/?id=10` the endpoint could poll.  I would think we would want some type of timeout, maybe 5s, or something, to force an error (maybe shorter).  Then, just by getting `http.StatusOK` you know the condition was satisfied and you can move on.  Would make for really simple testing.

**Comment by pauldix** [comment]
yeah, +1
