### ISSUE TITLE
time precision if only in shared segment is ignored

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1657]
If using epoch time `"precision":"ms"` must be accompanied in all of the points and cannot be only specified in the shared segment even if it is the same for all.

If write this:
```json
'{"points": [{"timestamp": 1422921600000, "values": {"value": 1}, "name": "my.test", "precision": "ms"}, {"timestamp": 1423008000000, "values": {"value": 2}, "name": "my.test", "precision": "ms"}], "precision": "ms", "database": "processed"}'
```

I get this in the logs (all good 2015 year)
```text
[write] 1 2015-02-03 16:00:00 -0800 PST
[write] 1 2015-02-02 16:00:00 -0800 PST
```
But if I write this (notice I have `precision` only on the shared block)
```json
'{"points": [{"timestamp": 1422921600000, "values": {"value": 1}, "name": "my.test"}, {"timestamp": 1423008000000, "values": {"value": 2}, "name": "my.test"}], "precision": "ms", "database": "processed"}'
```

Then most likely it crashes but if not I get this (notice the year):
```text
[write] 1 2052-08-31 00:38:44.365 -0800 PST
[write] 1 2049-12-05 00:38:44.365 -0800 PST
```

**Comment by imreACTmd** [comment]
in RC29 if I only specify precision in the shared segment ('ms') and use millisecond epoch timestamps in the points, the points do not get recorded, although the response is 200 OK.

{
    "database": "metric",
    "time_precision": "ms",
    "points": [
        {
            "name": "login.counter",
            "timestamp": 1431016410000,
            "fields": {
                "value": 3
            }
        }
    ]
}

**Comment by otoolep** [comment]
The JSON API is deprecated, and this issue is unlikely to be addressed.
