### ISSUE TITLE
Allow a user to control data point overwrite

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1660]
A point may come in with exactly the same timestamp as another (assuming series ID is the same). The user should be able to specify replace or append.

**Comment by dashesy** [comment]
If a point comes with same exact time but different tags it should not be treated like same point though. Otherwise I think an option is very much needed, thanks.

**Comment by otoolep** [comment]
Dupe of https://github.com/influxdb/influxdb/issues/1920
