### ISSUE TITLE
Feedback on 0.9

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1673]
I've been running 0.8.8 quite successfully and now started to test the pre 0.9 release. Here I'm facing various problems (maybe due to my own faults). Currently running ccc15b8

<b>Retention Policies</b>
![clipboard04](https://cloud.githubusercontent.com/assets/4459312/6315489/faa7807a-ba03-11e4-904b-d56763ed5174.png)
I have created above retention policies:
- Duration "inf" does not work. Leads to "Failed to create retention policy: {"error":"error parsing query: found inf, expected duration at line 1, char 48"} "
- There is no way to delete a retention policy in the web ui
- At first I did not set a policy to default. Following query failed
```
curl -G 'http://localhost:8086/query' --data-urlencode "db=vz2" --data-urlencode "q=SELECT value FROM power"
{"results":[{"error":"default retention policy not set for: vz2"}]}
```
- When adding a default policy the error is gone
- The documentation here http://influxdb.com/docs/v0.9/query_language/database_administration.html#show-existing-retention-polices has some typos "polices"

![clipboard05](https://cloud.githubusercontent.com/assets/4459312/6315531/7fab8ce8-ba05-11e4-851d-a673d0d302f3.png)
- this query returns empty on the web ui and also if called from the console via curl

<b>Writing Data</b>

- Via a script I generated following json data:
```
{
	"points" : [{
			"timestamp" : 1424299281369,
			"values" : {
				"value" : "806.5"
			},
			"name" : "power",
			"precision" : "ms"
		}, {
			"values" : {
				"value" : "798.9"
			},
			"timestamp" : 1424299283153,
			"name" : "power",
			"precision" : "ms"
		}, {
			"values" : {
				"value" : "800.2"
			},
			"timestamp" : 1424299284938,
			"name" : "power",
			"precision" : "ms"
		}
	],
	"database" : "vz2",
	"retentionPolicy" : "mytest",
	"tags" : {
		"source" : "ehz",
		"location" : "total",
		"type" : "delta"
	}
}
```
- The curl command has been accepted without error
- Querying the DB vz2 in the web ui leads to
![clipboard07](https://cloud.githubusercontent.com/assets/4459312/6316220/5f278c5a-ba1f-11e4-9936-9cd5edcad0f7.png)

<b>Creating Users</b>
- Creating a user in the web ui just does nothing. No error message and no user created

<b>Log file</b>
- My influxdb.log is spammed with
```
[srvr] 2015/02/21 23:17:40 broker cq: error hitting data node: : Post http:///process_continuous_queries: http: no Host in request URL
[srvr] 2015/02/21 23:17:40 broker cq: error hitting data node: : Post http:///process_continuous_queries: http: no Host in request URL
[srvr] 2015/02/21 23:17:40 broker cq: error hitting data node: : Post http:///process_continuous_queries: http: no Host in request URL
```

**Comment by pauldix** [comment]
Thanks for taking a look @Sineos, but 0.9 isn't in a testable state at the moment. We'll be cutting a release with some functionality in the next few days. The current RC isn't meant for general consumption.

We'll be sending out an announcement on Monday about the new RC, but it'll only be the start of something to test with, not a real release candidate. After that's out please log issues where you list one problem per issue with a descriptive title. Give steps to reproduce, what the expected result is, and what you received instead.

However, the release won't be complete so please search through issues before logging a new one. It may be something we already know about that we haven't gotten to yet.

If you have general feedback on the API, please send that to the Google Group.
