### ISSUE TITLE
custom admin port get ignored

### ISSUE THREAD

**Issue by n1tr0g** [influxdb/influxdb#1678]
Hello,

i am running influxdb version 0.8.8 and whatever value I enter for the admin port in /opt/influxdb/current/config.toml it will always use the default value 8083. Can someone confirm if he/she has the same error ?

I will try to rebuild the influxdb from the source code, to confirm if I still have the same issue.

**Comment by toddboom** [comment]
@n1tr0g I think you need to edit the config file in the shared folder - `/opt/influxdb/shared/config.toml`

**Comment by n1tr0g** [comment]
tnx that worked, however can you explain me the logic behind that ? 

I am also the author of https://forge.puppetlabs.com/golja/influxdb and looks like I will need to adjust my module to reflect that, but honestly I though that the /opt/influxdb/current/config.toml  has the highest priority.
