### ISSUE TITLE
Dimension aware select statement

### ISSUE THREAD

**Issue by kevinslin** [influxdb/influxdb#1686]
Is it possible to select units when querying InfluxDB?

For example, if I'm plotting latencies and want to switch from plotting micro seconds to seconds (assuming all latencies are stored micro seconds), is there a query I can run to get the results in seconds? Would be neat if I could execute any of the code below
```sql
-- assuming all latencies are stored in microseconds 
select duration from latencies as seconds where name = foo
-- or this: 'custom' takes in custom functions
select custom(duration / 1000) from latencies where name = foo
```

**Comment by pauldix** [comment]
you can do math on values: `select duration * 1000 from latencies where name = 'foo'`. Is that what you mean?
