### ISSUE TITLE
InfluxDB v0.9.0 will lost all data on those databases which are recreated after reboot

### ISSUE THREAD

**Issue by flowbehappy** [influxdb/influxdb#1690]
system: osx 10.9.5
version: InfluxDB v0.9.0 (git: 7b4d2675b0f29195a3a75c6d0ba37189b2b4b04c), compiled from source

repro step:

1. start InfluxDB by
`./influxd`

2. create a database and default retention policy
`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root" --data-urlencode "q=create database test3"`

`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root" --data-urlencode "q=create retention policy seven_days on test3 duration 7d replication 1 default"`

3. write some data into it 
```
curl -XPOST 'http://localhost:8086/write?u=root&p=root' -d '
{
    "database": "test3",
    "points": [
        {
            "name": "aaa",
            "tags": {
                "host": "not a host",
                "region": "us-west"
            },
            "values": {
                "value": 0.333
            }
        }
    ]
}
'
```

and try if it works
`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root&db=test3" --data-urlencode  "q=select * from aaa"`

should show something like
```
{
    "results": [
        {
            "rows": [
                {
                    "name": "aaa",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-02-19T13:35:56.224636567Z",
                            0.333
                        ]
                    ]
                }
            ]
        }
    ]
}
```

4. drop the database
`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root" --data-urlencode "q=drop database test3"`

5. recreate the database
`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root" --data-urlencode q=create database test3"`
`curl -G "http://localhost:8086/query?pretty=true&u=root&p=root --data-urlencode "q=create retention policy seven_days on test3 duration 7d replication 1 default"`

6. write some data again
```
curl -XPOST 'http://localhost:8086/write?u=root&p=root' -d '
{
    "database": "test3",
    "points": [
        {
            "name": "aaa",
            "tags": {
                "host": "not a host",
                "region": "us-west"
            },
            "values": {
                "value": 0.333
            }
        }
    ]
}
'
```
everything is fine so far
```
curl -G "http://localhost:8086/query?pretty=true&u=root&p=roo&db=test3" --data-urlencode  "q=select * from aaa"
{
    "results": [
        {
            "rows": [
                {
                    "name": "aaa",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-02-19T13:39:05.512209925Z",
                            0.333
                        ]
                    ]
                }
            ]
        }
    ]
}
```

7. kill the InfluxDB by `ctr+c`, and start it again by `./influxd`
8. try query
```
curl -G "http://localhost:8086/query?pretty=true&u=root&p=root&db=test3" --data-urlencode  "q=select * from aaa"
```
got empty result:
```
{
    "results": [
        {}
    ]
}
```

**Comment by otoolep** [comment]
Thanks for the great bug report @flowbehappy -- I'll take a look at this.

**Comment by otoolep** [comment]
This has already been fixed on master, as of commit https://github.com/influxdb/influxdb/commit/4dbd1541f73b9579f790621e1059af58fe702e7a
