### ISSUE TITLE
Make field encoding more efficient

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1703]
Currently, the field data encoding writes an id. This is actually unnecessary. We should just be writing the raw data and use the field id as an offset into the `[]byte` data array.

For instance, if they write an `int64` and a `string` on their first write into a measurement. Put all the fixed width fields first. Then we know that id `1` is a 4 byte type so it'll be at `data[:4]`. We know that id `2` is a string and that it comes after a 4 byte type. So first we get the size `data[4:6]` assuming we use a `uint16` to store the size of the string.

For fields that are written in later, they'll go in the end of the byte array. If there are variable length fields that come before them, we'll have to walk the byte array to get to them. So that's a bit expensive, but it's not something that I think would be common.

Also, if they have 3 fields defined and they don't write data for one of them, we'll have to write null bytes in.

Finally, on queries that access fields that were created after the initial creation of the measurement, we'll have to do bounds checking on the data array before looking them up.

So, we should add the creation time of fields to what we store.

So create these test cases:

* Write single value multiple times and query out
* Write float and string multiple times and query out
* Write float, then add a new float field and query each out individually
* Write float and string, then add a new float and query each out individually
* Write float and string and then do writes that omit one or the other and then query each

**Comment by otoolep** [comment]
After further discussion, this change is on hold.

cc @benbjohnson

**Comment by otoolep** [comment]
Closing this since field encoding will be quite different going forward.
