### ISSUE TITLE
Update LIMIT and OFFSET to SLIMIT and SOFFSET and implement LIMIT and OFFSET

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1709]
`LIMIT` and `OFFSET` currently set the limit and the offset on the series that are returned. We need another layer of limiting, which is the number of data points in each of those series. Change the series limit and offset to `SLIMIT` and `SOFFSET` and update the current `LIMIT` and `OFFSET` to be limits and offsets for the points within each series.

This means that if you do a group by on a tag, you could potentially still get a ton of data back if the tag has a high cardinality.

**Comment by otoolep** [comment]
If this is all about paging through points in a series with a lot of data, and narrower time ranges are still not sufficient, seems like we do need it. No other command comes to mind.

**Comment by Ynguibjoerg** [comment]
+1 on the functionality. It is very much needed indeed, but I would suggest to switch the names as I'd expect limiting on the database to be the more frequently used case (at least from the way that I use the database).

**Comment by Ynguibjoerg** [comment]
Also I think using the LIMIT for the datapoint limit instead of the series is more compatible with sql tradition and previous versions of influxdb. Maybe use SLIMIT for a series limit instead?

**Comment by jnutzmann** [comment]
+1 for SLIMIT

I agree with Ynguibjoerg. To me, LIMIT should control the number of rows
returned. Also, I thought LIMIT was used this way in 0.8, so changing
meaning is confusing.

**Comment by pauldix** [comment]
I think I'm sold on that. `LIMIT` and `SLIMIT`. Besides, it's easier to say "slimit" than "plimit", no?

**Comment by mre** [comment]
+1 Awesome!

**Comment by nemesisdesign** [comment]
:+1: for `LIMIT` and `SLIMIT`
