### ISSUE TITLE
0.9.0-rc3 can't create new databases

### ISSUE THREAD

**Issue by hawson** [influxdb/influxdb#1714]
Using either the web interface or HTTP POST requests, I can't create new databases.  

Using the web interface, on a new installation (new code, no existing databases, etc), with the root user, creating a database returns the following error:

    Failed to create database: �	n���V*J-.�))V���VJ-*�/R�R��OWH��/NMQ�����:�E$

Something similar happens when trying a POST request to do the same thing, it also fails, although there's no garbage, and a "log closed" error.

The logs show a 500 HTTP code:

    [http] 127.0.0.1 - - [24/Feb/2015:17:23:03 +0000] GET /query?db=storage&q=create+database+storage HTTP/1.1 500 60 - InfluxDBShell/0.9.0-rc3 c9e061cd-bc49-11e4-a7fc-b8ca3a5e3760

When using the `influx` CLI client, I get something similar:

    > [influxdb@storstat11 influxdb]$ ~/current/influx
    InfluxDB shell 0.9.0-rc3
    Connected to http://localhost:8086 version 0.9.0-rc3
    > show databases
    name	tags	name
    ----	----	----
    > create database storage
    ERR: log closed
    Warning: It is possible this error is due to not setting a database.
    Please set a database with the command "use <database>".
    > use foo
    Using database foo
    > create database storage
    ERR: log closed

**Comment by toddboom** [comment]
@hawson did you build this from source or install from a package? also, what OS is this on?

**Comment by hawson** [comment]
Both source and package.  (golang 1.4, when built form source).  Centos 6.6 in either case.

**Comment by hawson** [comment]
I had similar problems with rc2 as well.

**Comment by hawson** [comment]
I think this is resolved as part of #1713
