### ISSUE TITLE
SHOW TAG VALUES should support keys wrapped in double quotes

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1729]
This should work:

```
SHOW TAG VALUES WITH KEY = "host"
```

**Comment by rothrock** [comment]
You want both of these to do the same thing?

SHOW TAG VALUES WITH KEY = host
SHOW TAG VALUES WITH KEY = "host"

Only in the context of the 'show tag values' statement?

Or identifiers should be treated this way generally?

**Comment by hawson** [comment]
I think that they should either:
1. be treated the same
2. *force* the usage of quotes (either single or double)

**Comment by cannium** [comment]
```
SHOW TAG VALUES WITH KEY = host
SHOW TAG VALUES WITH KEY = "host"
```
both work, but `SHOW TAG VALUES WITH KEY = 'host'` doesn't. If this is the expected behaviour, we might need to update [INFLUXQL.md](https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md#show-tag-values)

**Comment by cannium** [comment]
Also, INFLUXQL.md says it's `WITH TAG`.
