### ISSUE TITLE
found REPLICATION, expected DURATION at line 1, char 42

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1730]
Invalid policy creation in repo's main docs [here](https://github.com/influxdb/influxdb#setting-up-the-databases-retention-policy).

This query `CREATE RETENTION POLICY mypolicy ON mydb REPLICATION 7d DEFAULT`,  results in this error: `found REPLICATION, expected DURATION at line 1, char 42`.

Correct one should be `CREATE RETENTION POLICY mypolicy ON mydb duration 7d REPLICATION 1 DEFAULT`

**Comment by otoolep** [comment]
@dashesy - any chance you could generate a PR that fixes in the influxdb.org repo? :-)

**Comment by otoolep** [comment]
Actually, I believe I have fixed the `README.md` as required. Please re-open if not.

**Comment by dashesy** [comment]
I was about to do the PR against the repo (not .org) but saw your fixes, thanks :)
