### ISSUE TITLE
Create retention policy automatically when creating database

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1732]
Since a database is *useless* without a retention policy, why don't we just have the system create one by default when a database is created? We can pick reasonable defaults such as the name "default" and a period of 7d, and a replication factor equal to the number of nodes in the system.

It reduces the number of steps a user must perform before he can write data into a new system by 50%. We could have a config flag allow admins to disable this is they wish, but it would not be disabled by default.

@pauldix -- have we considered this? If we have, and ruled it out, please close.

**Comment by toddboom** [comment]
I do think this is a good idea, in some fashion. It does seem silly to create a database and then be unable to write data into it from the get-go. Maybe the default retention policy is infinite?

**Comment by corylanou** [comment]
I believe we came to the following:

Name: `default`
Duration: `INF` or `0` (infinite)
Replication Factor: `1`

This will require a change so that the parser will understand the new options for creating a retention policy as well.

**Comment by otoolep** [comment]
Make sure we have a config option to disable auto-creation of RPs. Some people won't want it.

**Comment by dashesy** [comment]
It is certainly good idea, it took me by surprise when I could not push to newly created db first time, I assumed if no retention policy is given it should keep things forever like normal dbs do.

**Comment by otoolep** [comment]
This has been done.
