### ISSUE TITLE
No idea how I'm supposed to regex values.

### ISSUE THREAD

**Issue by sherl0k** [influxdb/influxdb#1744]
I'm having a really difficult time trying to figure out how to use regex to get values of the same series from different hosts. or even values from the same host, for example.

I have a series in influxdb sent from collectd, CPU usage, for instance.

/localhost/cpu-0/cpu-idle
/localhost/cpu-1/cpu-idle
/localhost/cpu-2/cpu-idle

But there's no way to grab all the cores information via regex, I keep getting errors. What is supposed to be the proper regex to return all the values?

I've tried 
/localhost/cpu-\*/cpu-idle
/localhost/cpu-.\*/cpu-idle
/localhost/\*/cpu-idle

I'm no fool to SQL, or regex. But there's no implementation of sql's LIKE, I can't find a way to fuzzy match these values. Even your examples reference "app.*" but there isn't a single value being collected that splits values out by periods, only slashes. Maybe that's another issue I need to address first?

**Comment by dgnorton** [comment]
What version of influxdb are you using?

**Comment by sherl0k** [comment]
I'm running 0.8.8.
