### ISSUE TITLE
UDP+JSON not supported anymore?

### ISSUE THREAD

**Issue by palkan** [influxdb/influxdb#1755]
As I can see, UDP server had been _panically_ commented out  in 0.9. And there is also a note: "TEMPORARILY REMOVED FOR PROTOBUFS".

Can you, please, clarify, what are your plans on UDP write support? Will it be included in final release?

**Comment by pauldix** [comment]
We can add it into the final release. The JSON format will take the same form that the HTTP API now takes.

**Comment by pauldix** [comment]
This is fixed by #1848. However, the format now reflects the new format for HTTP writes. Will be in RC8.
