### ISSUE TITLE
0.9.0-rc4 does't create $HOME/.influx_history

### ISSUE THREAD

**Issue by hawson** [influxdb/influxdb#1760]
The `influx` shell doesn't write out `$HOME/.influx_history`.  A command history is kept while the shell is open, so it's obvious the command history buffers are getting filled, but the history file is never opened at start, nor written to when the process stops.

**Comment by corylanou** [comment]
A couple of things could be happening.

We should state that history is disabled if we can't determine the user for some reason:

https://github.com/influxdb/influxdb/blob/master/cmd/influx/main.go#L85

We write history EVERY time a command is issued, so if this fails, we don't report either:

https://github.com/influxdb/influxdb/blob/master/cmd/influx/main.go#L103

So if history is enabled, we should report if we fail to write it.

I'm guessing that for some reason it couldn't determine the user in this case (just guessing).  

What OS are you on @hawson ?

**Comment by hawson** [comment]
This is running on a Centos 6.6 box.  I don't think I did anything to explicitly disable tracking history.  I'll double-check permissions on $HOME later on.

I will note that I'm running the daemon under a dedicated service account with a shell set to /bin/false.  Could that have something to do with it?

**Comment by corylanou** [comment]
It's possible.  If the user that the cli runs under doesn't have a `$HOME` directory, the cli doesn't know where to put the history file.  I'll have to do some research to figure out what the standard practice for history files is in that situation.  This first version was just a "punt" on where to keep the history files as it should work for most people, but I figured at some point it would need some more robustness.

Thanks for bringing this to our attention.

**Comment by hawson** [comment]
Sorry, I wasn't clear:  the user ("influxdb") *does* have a `$HOME` directory.  It's just the shell that is set to `/bin/false`.

IME, if a process can't write a history file for some reason, the current behavior of the `influx` CLI program is correct:  keep an in-RAM history while the process is running, but that is lost when the program ends.

**Comment by hawson** [comment]
Permissions and such are all fine.  It's a logic problem, not something related to filesytems/users/etc.

I'll submit a pull request for a possible fix.

**Comment by hawson** [comment]
Replaced by #1836
