### ISSUE TITLE
0.9.0-RC6: SELECT mean(value) crashes influx

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1792]
Running 8eefdba here on Ubuntu 14.04

The query: 
```
curl -G http://localhost:8086/query --data-urlencode "db=vz2" --data-urlencode "q=SELECT value from power WHERE type = 'consume'"
```
works fine. Whereas:
```
curl -G http://localhost:8086/query --data-urlencode "db=vz2" --data-urlencode "q=SELECT mean(value) from power WHERE type = 'consume'"
curl: (52) Empty reply from server
```
immediately crashes influx.

**Comment by otoolep** [comment]
Can you please provide a full test case for this including creation of a database, retention period, and writing of a data point

**Comment by Sineos** [comment]
Umm, now it is kind of official that I have no clue about git:
Somehow the test case for this issue is now also referenced in #1797 
Sorry I have no clue how to create two different PRs out of it

**Comment by pauldix** [comment]
@Sineos, are you saying that this is what reproduces the crash? https://github.com/Sineos/influxdb/commit/2e5cd895f68739972cd896cff6e0f7d156fe9713

**Comment by Sineos** [comment]
@pauldix, yes this test case will reproducible crash my influxdb build

**Comment by otoolep** [comment]
Real crash, confimed. Trace from 1st goroutine:
```
[http] 127.0.0.1 - - [02/Mar/2015:19:38:44 -0800] GET /query?db=test_crash&q=SELECT%20value%20FROM%20power%20WHERE%20type%20%3D%20%27consume%27%20AND%20location%3D%27eg%27%20AND%20source%3D%27s1%27 HTTP/1.1 200 528 - curl/7.35.0 cb30e4e3-c156-11e4-993e-54ee75168d03
panic: interface conversion: interface is string, not float64

goroutine 1698 [running]:
github.com/influxdb/influxdb/influxql.MapMean(0x7fc2da69ea28, 0xc20800b040, 0xc20802fb20, 0x0)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/influxql/engine.go:699 +0xbb
github.com/influxdb/influxdb/influxql.(*Mapper).run(0xc20801f440, 0xc20802fb20)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/influxql/engine.go:460 +0x1b9
created by github.com/influxdb/influxdb/influxql.(*Mapper).Map
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/influxql/engine.go:429 +0x9b

goroutine 1 [chan receive (nil chan)]:
main.execRun(0xc20800a010, 0x4, 0x4)
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:121 +0x780
main.main()
        /home/philip/Dropbox/repos/influxdb/src/github.com/influxdb/influxdb/cmd/influxd/main.go:70 +0x35b
```

**Comment by otoolep** [comment]
The fundamental issue here is that the test data has some quoted numbers. Numbers that are quoted are interpreted as strings, and calculating a mean of string values doesn't make sense.

https://github.com/influxdb/influxdb/pull/1828 will fix this issue. Whether it's the right thing to do or not is open to debate.

@pauldix @benbjohnson

**Comment by Sineos** [comment]
Many thanks for the hint with the wrong type I fixed my script to provide integer / float.

My personal opinion is to rather throw a meaningful error message like: "Error: Wrong arguments passed to arithmetical / calculus function. Expected numerical, received string type"

This way a user can fix the problem and provide correct data. Otherwise you will have the same issue with boolean values. What is the mean value of "true" - half true or 0.5?

**Comment by pauldix** [comment]
This should get validated at the time of query planning. Logged #1845 to track it.
