### ISSUE TITLE
package.sh

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1793]
In package.sh line 169 the check reads:
```
if [ ! -L /etc/init.d/influxdb ]; then
```
This does not work because -L check if file exists AND is symbolic. So if it does not exist at all nothing will happen.
I'd rather do something like 
```
if [ -e /etc/init.d/influxdb ]; then
    #remove existing regardless if link or regular file
	rm /etc/init.d/influxdb
	ln -s $INSTALL_ROOT_DIR/init.sh /etc/init.d/influxdb
	chmod +x /etc/init.d/influxdb
else 
	ln -s $INSTALL_ROOT_DIR/init.sh /etc/init.d/influxdb
	chmod +x /etc/init.d/influxdb
fi

#move runlevel stuff outside of above if loop
if which update-rc.d > /dev/null 2>&1 ; then
	update-rc.d -f influxdb remove
	update-rc.d influxdb defaults
else
	chkconfig --add influxdb
fi
```
The chmod is probably surplus since it points to an executable file anyway.

**Comment by otoolep** [comment]
Thanks @Sineos -- how about a PR with your suggestions? We could merge it.

**Comment by Sineos** [comment]
See #1797 
I have never used git for anything else than cloning to my hdd for local builds let alone creating PR.
So please bear with me if I did mess it up.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/1809
