### ISSUE TITLE
0.9.0-RC6: derivative missing and strange error message from web ui

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1794]
The derivative function seems to be completely missing
```
curl -G http://localhost:8086/query --data-urlencode "db=vz2" --data-urlencode "q=SELECT derivative(value) from power WHERE type = 'consume' AND location='eg' AND source='s1'"
{"results":[{"error":"function not found: \"derivative\""}]}
```
When called from the web ui a strange error message is displayed:
![clipboard02](https://cloud.githubusercontent.com/assets/4459312/6426629/485b88a0-bf65-11e4-9754-06a616aa2ed5.png)

Running 8eefdba on Ubuntu 14.04

**Comment by pauldix** [comment]
Please log only a single issue per report. Also, please search before logging an issue. Derivative is already on the list: #1477.

For the UI bug, please give exact steps to reproduce and we'll try to get it fixed ASAP.
