### ISSUE TITLE
0.9.0-RC6: Create Infinite Retention Policy 

### ISSUE THREAD

**Issue by Sineos** [influxdb/influxdb#1796]
Creating an Infinite Retention Policy seems not possible. Both "0" or "INF" is rejected:
```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY blubb ON test DURATION 'INF' REPLICATION 1 DEFAULT"
{"error":"error parsing query: found INF, expected duration at line 1, char 47"}

curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY blubb ON test DURATION 0 REPLICATION 1 DEFAULT"
{"error":"error parsing query: found 0, expected duration at line 1, char 48"}
```
Strange enough following is accepted:
```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY blubb2 ON test DURATION 0h REPLICATION 1 DEFAULT"
{"results":[{}]}
```

In addition it would be nice if the web ui offers to 
- edit retention policies
- remove retention policies

Running 8eefdba on Ubuntu 14.04

**Comment by dmerino-va** [comment]
Would it be possible that the default retention policy for all databases is infinite if not specified?

**Comment by nemesisdesign** [comment]
I agree that it would be nice both to have infinite retention policy and inifinite as default behaviour.

**Comment by otoolep** [comment]
We have had discussions about this, which are relevant.

https://github.com/influxdb/influxdb/issues/1732

**Comment by otoolep** [comment]
Pass `INF` for infinite retention policies.
