### ISSUE TITLE
Queries should rewrite any tag keys in the select clause into the group by clause

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1798]
When selecting data, tag keys can only appear in either the `GROUP BY` or `WHERE` clause. For instance if we have tag keys `region` and `host` on a measurement called `cpu`.

```sql
-- valid
select mean(value) from cpu group by region, host

-- not valid
select mean(value), region, host from cpu

-- should automatically rewrite to this since it's what the user most likely wanted
select mean(value) from cpu group by region, host
```

**Comment by dashesy** [comment]
I think the rewrite will be useful because only then I can use time bins like this:

```sql
select mean(value), region, host from cpu group by time(10m)
```

**Comment by pauldix** [comment]
You can already do this now. The query rewriting will change change that query to:

```sql
select mean(value) from cpu group by time(10m), region, host
```

Query rewriting is only about usability, not functionality. This won't enable any new behavior.

**Comment by pauldix** [comment]
I'm actually changing my mind on this one. I think we should support it this way if that's what people want.
