### ISSUE TITLE
can't drop series with "#" as part of the series name.

### ISSUE THREAD

**Issue by gitRahul** [influxdb/influxdb#1800]
I'm using version 0.8.8

I cannot drop a series name with a "#", note that I'm able to create it, just can't drop it.

syntax error, unexpected $undefined, expecting $end
drop series bridge.eqbatman_nyk_prd.nykpsol1021n02.#bridge/v:nykpsol1020n01/eqbatman_nyk_prd/5.EQ.NONPRD.stats

**Comment by pauldix** [comment]
We won't be fixing this in 0.8.x and it's fixed in 0.9.
