### ISSUE TITLE
Move getting started info out of README.md

### ISSUE THREAD

**Issue by matschaffer** [influxdb/influxdb#1803]
I lost a little time this morning figuring out why the steps listed in README.md don't work on the latest release.

My guess is that the in-repo readme tracks master but this doesn't appear to be stated anywhere in the doc.

It could save some time to be explicit about this or perhaps remove the getting started from the repo entirely and instead reference release documentation similar to what https://github.com/mozilla-services/heka does.

**Comment by otoolep** [comment]
Thanks @matschaffer -- I have made this explicit in the README file.

https://github.com/influxdb/influxdb/commit/d55c850b0eefce79bc227833a06b340661e17efb
