### ISSUE TITLE
Status of 0.9

### ISSUE THREAD

**Issue by napalm272** [influxdb/influxdb#1807]
What is the status of 0.9?  Can I assume all the end points will remain the same after the production version is released?  For example, in 0.8.8 the end point for creating a database is 
curl -X POST 'http://localhost:8086/db?u=root&p=root' \
  -d '{"name": "site_development"}'
In 0.9, it is 
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE mydb".
Can I assume the -G won't be changed to a -X POST?

**Comment by otoolep** [comment]
0.9.0 is now available for early testing.


http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html

The API is changing significantly between 0.8.x and 0.9.0. You can find
full details here:

    http://influxdb.com/docs/v0.9/introduction/overview.html

Of course, we plan to keep the API stable post 0.9.0.

Philip

**Comment by napalm272** [comment]
Thanks for replying Philip. I know there are big changes from 0.8.8 to 0.9. But I want to know if there is going to be big changes (e.g. end point) between 0.9.0_rc5 and the stable 0.9.0

**Comment by otoolep** [comment]
To quote the blog post:

"The new API should reflect what the 1.0 release of InfluxDB later this
year will look like. There may be additions, but we are unlikely to make
any breaking API changes after 0.9.0 is released."

Hopefully this answers your question.

Philip

**Comment by otoolep** [comment]
In general, the mailing list is the best place for questions like this. Please send any more questions to the list.

**Comment by pauldix** [comment]
To be a bit more specific, the API of 0.9.0 is completely different from
the API of 0.8. We made many breaking changes.

However, we're reasonably sure that the API of 0.9.0_rc4 will be the same
as the API of the 0.9.0 production release.
