### ISSUE TITLE
Wire up DISTINCT aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1815]
Query looks like this:

```sql
select distinct id from user_events
where time > now() - 24h
group by time(1h)
```

You'd get back the distinct user ids for each hour bucket of time for the last 24 hours.

With distinct you can either pass in a `field` or a `tag`. The query engine will have to do wildly different things to get the result depending on what they do.

If it's a tag and no time limitation was specified, then the metastore can answer the query directly. If a time limit was specified, you'll have to run a query.

If it's a field, then you'll have to run a query and run through the whole engine.

**Comment by corylanou** [comment]
For this current iteration (and based on internal discussions), I'm proposing the following:

## Supported

```sql
#SELECT DISTINCT <field> FROM <measurement>
SELECT DISTINCT value FROM cpu

# SELECT DISTINCT <tag> FROM <measurement>
SELECT DISTINCT host FROM cpu

#SELECT DISTINCT <tag> FROM <measurement> WHERE time > now() - 24h
SELECT DISTINCT host FROM cpu WHERE time > now() - 24h

# SELECT DISTINCT <field> FROM <measurement> GROUP BY time(1h) where time > now() - 1d
SELECT DISTINCT value FROM cpu GROUP BY time(1h) where time > now() - 1d
```

## Not currently implemented (might in the future, but no promises)

```sql
#SELECT DISTINCT <field>, <field> FROM <measurement>
SELECT DISTINCT id, value FROM cpu

#SELECT DISTINCT <tag>, <tag> FROM <measurement>
SELECT DISTINCT host, region FROM cpu

# No aggregate functions with a select distinct (sum, count, mean, max, etc.)

#SELECT DISTINCT <field>, count(<field>) FROM <measurement>
SELECT DISTINCT id, sum(bytes) FROM network

#SELECT DISTINCT <tag>, count(<field>) FROM <measurement>
SELECT DISTINCT host, sum(bytes) FROM network

#SELECT DISTINCT <tag>, <tag> FROM <measurement>
SELECT DISTINCT id, value FROM cpu
```

**Comment by beckettsean** [comment]
@corylanou Can we update <field> and <tag> to <field key> and <tag key> so they are more explicit?

**Comment by andyxning** [comment]
@pauldix any plan to support distinct on tag key, see #3880 for more info. We do really need that functionality.

>#SELECT DISTINCT <tag key>, <tag key> FROM <measurement>
