### ISSUE TITLE
Wire up BOTTOM aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1820]
Users should be able to do a query like this:

```sql
select bottom(value), time, host
from cpu
limit 5
```

Will return a single series with 5 data points containing the time, the value, and the host.

If you do a query like this:

```sql
select bottom(value), time, host from cpu
where time > now() - 24h
group by time(1h)
```

You'd get a single series with 24 total data points. That's 1 data point in each time bucket (but it would have the point original timestamps), the value, and the host.

If you want to do a query where you get the bottom N series, look at issue #1819

**Comment by mail2fish** [comment]
Is that mean we don't have top fun at 0.9.2 yet?

**Comment by pauldix** [comment]
Should also be able to do:

```sql
select top(mean(value), 5), host from cpu where time > now() - 2h
```

This query would first compute the mean of each host in the range, then select the top 5.

Query parsing validation will have to be updated to enable this since we currently throw an error. See #3407 for more context.

**Comment by pauldix** [comment]
@mail2fish it's not in 0.9 yet. We'll hopefully start this for the 0.9.4 cycle, but not sure yet.
