### ISSUE TITLE
Wire up DERIVATIVE aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1822]
If the query is like this:

```sql
SELECT DERIVATIVE(value)
FROM cpu
WHERE time > now() - 4h
```

It will compute the rate of change between each data point.

If the query is like this:

```sql
SELECT DERIVATIVE(MEAN(value))
FROM cpu
WHERE time > now() - 4h
GROUP BY time(5m)
```

It will take the rate of change of the mean of 5 minute buckets of time.

**Comment by CMGS** [comment]
so where is derivative?

**Comment by regit** [comment]
+1 or is there another way to access to derivative/speed on data ?

**Comment by anandmani-lab49** [comment]
I am using rc25 and I don't see the derivative function. Get the following error: 
ERROR: {"results":[{"error":"function not found: \"DERIVATIVE\""}]}
Here is my query: 
SELECT DERIVATIVE(value) FROM "my.series" WHERE time > now() - 15m GROUP BY time(10s) ORDER BY asc
Any ideas please?

**Comment by otoolep** [comment]
@anandmani-lab49 -- keep an eye on this ticket. Once the functions are implemented, this ticket will be closed.
