### ISSUE TITLE
Wire up MEDIAN aggregate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1824]

**Comment by neonstalwart** [comment]
what would you want the median to be for an even number of samples?

* the mean of the 2 mid-points
* the larger of the 2 mid-points
* the smaller of the 2 mid-points

**Comment by beckettsean** [comment]
Mathematically the answer is the mean of the 2 mid-points. Let's start with that and then see what challenges that raises.

**Comment by toddboom** [comment]
i agree with @beckettsean

**Comment by neonstalwart** [comment]
> Mathematically the answer is the mean of the 2 mid-points.

done.  #2411 is ready for a look.

**Comment by toddboom** [comment]
added as part of rc29
