### ISSUE TITLE
per-tag and per-series user access control

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1830]
It would be great to have a hierarchical user access control, and for that I think tags can act like Unix user groups. If for example I make sure all records have a tag called `group_id`. Then will be useful to give user `foo` access to all records that their associated `group_id` is e.g. `1` but give user `manager` access to groups of `[1,3,10]`. 
Lets assume there is a forward-looking electricity company that wants to engage the users by giving them more data. If for example the sensor is sensing apartment electricity consumption (series be `electricity.watts` and tags be `group_id=1`), each tenant should be able to query her own electricity consumption (perhaps do average in month, join with `electricity.bills`, ...) but the electricity company may need to do higher level data mining and should be able to access all homes and apartments and commercial places. A renting apartment complex manager should be able to only see apartments in his complex.
One way to control this hierarchy would be to have separate databases, but question becomes what is the granularity? Do we need one database per apartment/user?
Having many databases makes the job of the electricity company harder because they will need to join from multiple databases (not even different tables), which bring up per-series user access control: per-series authentication is better than per-database because series are like tables. However they become ugly because all series will have to be encoded instead like `userN.electricity.watts` and `user25452124.*` will look like a hack really and not proper Linux user access rights.

There is nothing set in stone and there may be better ways to handle this, any idea is appreciated.

**Comment by pauldix** [comment]
This level of access control is out of scope of the database for us. We'll be putting out a product later this year that will give you this level of control, but it's something that will sit outside the database itself and act as a proxy. Like ElasticSearch's Shield product.

In the meantime, the best thing to do is to create an authorization proxy on your own that gives you the level of control you need.

**Comment by cmben** [comment]
+1
