### ISSUE TITLE
Create influxdump

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1833]
We need a tool to dump and load data from the database. It should use the API to pull data from the database and write to a file. Users should be able to specify a specific measurement to pull out, or pull out all of them. They should also be able to specify the time range they want to pull.

They should be able to also dump all other schema information like the databases, users, and continuous queries created.

The tool should also be able to take a dump file and load it into the database.

Data in the file should be split out to one JSON object per line. When pulling the data for a measurement, it should use time limits to pull out the data gradually. Or possibly the chunked response API, but that's not wired up yet.

**Comment by beckettsean** [comment]
functionality exists in the CLI.
