### ISSUE TITLE
client.Write() is broken

### ISSUE THREAD

**Issue by georgmu** [influxdb/influxdb#1844]
client.Write has multiple problems:

https://github.com/influxdb/influxdb/blob/v0.9.0-rc7/client/influxdb.go#L97
```
b := []byte{}
err := json.Unmarshal(b, &d)
```
Here, the client should not unmarshal, but marshal the request:
```
b, err := json.Marshal(&d)
```

Additionally, the json produced generates errors in the core. If I see it correct, host:8086/write does not accept an array, but only a single object. Thus, the signature should change to Write(write Write) and the for loop generating d should be replaced with:
```
d := data{Points: write.Points, Database: write.Database, RetentionPolicy: write.RetentionPolicy}
```

**Comment by georgmu** [comment]
I tested your changes and it looks good :)

**Comment by corylanou** [comment]
Fixed in https://github.com/influxdb/influxdb/pull/1868
