### ISSUE TITLE
Query should validate that the aggregate function works on the field data type

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1845]
For instance, if the user tries to compute a `mean` against a field that is a string, the query should return an error that says they can't do this.

We also need to implement all numerical aggregates for `int64` in addition to floats. It would probably be best to keep a map of which data types each aggregate function is able to process.

**Comment by wladekb** [comment]
It might be cool to have an option to SKIP_INVALID_TYPES so that if I write a point with string when all other values are ints/floats I'll still be able to get a meaningful result that skips the string without any error message.

**Comment by pauldix** [comment]
You can't write with different types. Once you've written the first value
for a given field on a measurement, all future values for that field on
that measurement must be the same type.

**Comment by dashesy** [comment]
What about nans? IOW, how are missing values marked/handled? Some applications may want to record missing values to keep track of time itself.

**Comment by wladekb** [comment]
@pauldix 
[OT]
1. so is this change introduced in 0.9? I'm using 0.7 and it doesn't have this check.
2. What is the type granularity? If I push something that looks like int and then float will this get rejected?

**Comment by beckettsean** [comment]
closing in favor of #3818
