### ISSUE TITLE
parseInt: value out of range exception while adding data points using graphite protocol

### ISSUE THREAD

**Issue by phagunbaya** [influxdb/influxdb#1851]
The timestamp I'm trying to send is in millis.

Shouldn't "math/big" package be used instead of "strconv" package for parsing long integers ?
Ref : https://github.com/influxdb/influxdb/blob/master/graphite/graphite.go#L81

**Comment by otoolep** [comment]
Can you please provide the logs which show this error occurring? Are you running 0.9? If so, what version?

**Comment by phagunbaya** [comment]
Influx version : 0.8.8
Data : sample.falkonry.internal.PNT004 100 1425877738380
Log : [2015/03/09 10:37:16 IST] [EROR] (github.com/influxdb/influxdb/api/graphite.(*Server).handleClient:261) GraphiteServer:%!(EXTRA *strconv.NumError=strconv.ParseUint: parsing "142560000099": value out of range)
[2015/03/09 10:37:16 IST] [DEBG] (github.com/influxdb/influxdb/api/graphite.(*Server).handleClient:258) GraphiteServer: Client closed graphite connection
