### ISSUE TITLE
[v0.9.0-rc7]-No cluster section in the web GUI

### ISSUE THREAD

**Issue by zmathe** [influxdb/influxdb#1853]
I am a new user of influxdb. I tried to set up a 3 node cluster. I installed http://get.influxdb.org/influxdb-0.9.0_rc7-1.x86_64.rpm to the first node
I set the hostname and I added(/etc/opt/influxdb/influxdb.conf):
```
[sharding]
replication-factor = 3
after the [cluster] section.
I started the cluster: /etc/init.d/influxdb start
After I setup the 2 and 3 nodes.
I added the configuration file:
[cluster]
# Location for cluster state storage. For storing state persistently across restarts.
dir = "/tmp/influxdb/development/state"

seed-servers = ["xxx.xxx.xxx.xx:8090"] #this is the IP address of the 1th node.

[sharding]
replication-factor = 3
```

When I open the GUI, I can not see the cluster:
![screen shot 2015-03-05 at 17 02 41](https://cloud.githubusercontent.com/assets/981448/6508532/a367d4ae-c359-11e4-8574-346c18229520.png)

What I am doing wrong? How I can setup a cluster?
Thanks,
Zoltan

**Comment by zmathe** [comment]
I have setup a cluster using InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15). I can see the cluster section in the WUI:
![screen shot 2015-03-09 at 15 48 08](https://cloud.githubusercontent.com/assets/981448/6557260/fc61bff8-c673-11e4-8d07-86389628db4b.png)

I do not know why I can not see the cluster section using v.0.9?

I also noticed that the database is very slow. I have 3 nodes 4 CPU and 8GB memory. I only have ~16 million data-points. Which is equivalent two days of monitoring data. It takes ~5 minutes to make the following plot:
![screen shot 2015-03-09 at 16 05 27](https://cloud.githubusercontent.com/assets/981448/6557554/255fe374-c676-11e4-9e98-5a495546dd94.png)

**Comment by toddboom** [comment]
The admin interface is changing significantly as part of #2746. You'll be able to pull server and cluster details via the query language, so there won't be a dedicated section for those any longer.
