### ISSUE TITLE
build issue: cannot find package statik/example/statik

### ISSUE THREAD

**Issue by areski** [influxdb/influxdb#1854]
I'm getting the following issue:

    go get -d -v -t ./...
    import "assert": import path does not contain a slash
    package assert: unrecognized import path "assert"
    github.com/kr/pty (download)
    github.com/rakyll/statik (download)
    package github.com/kr/pty
    	imports github.com/rakyll/statik/example/statik
    	imports github.com/rakyll/statik/example/statik
    	imports github.com/rakyll/statik/example/statik: cannot find package "github.com/rakyll/statik        /example/statik" in any of:
    	/home/areski/.gvm/gos/go1.4/src/github.com/rakyll/statik/example/statik (from $GOROOT)
    	/home/areski/projects/influxdb/influxdb/src/github.com/rakyll/statik/example/statik (from $GOPATH)
    github.com/stretchr/objx (download)

I opened a PR to fix it on statik: https://github.com/rakyll/statik/pull/10

I thought it will be important to track this issue here.

**Comment by toddboom** [comment]
Not sure there's anything to be done by us here, and it's not causing problems for the normal build process.

**Comment by odeke-em** [comment]
Please get/look at the latest code from https://github.com/rakyll/statik, this issue got addressed in the latest of the repo. Thanks.
