### ISSUE TITLE
Backfill for continuous query should happen in chunks

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#186]
The backfill for continuous queries could blow up if there is already a lot of data in the db that matches the query. Do this to make sure it happens in chunks and doesn't explode.

Regex queries should do a query with limit 1 to pull back all the series then fill each one like so:

Find out the first group to file by doing limit 1 order desc. Then do chunks of groups. If it's group by 1d, do each day at a time. Otherwise grab somewhere around an hour or two at a time.

**Comment by inthecloud247** [comment]
+1
