### ISSUE TITLE
Regexp for database selection (feature request)

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#1865]
It would be extremely useful if I could select multiple databases in one query, this way having multiple databases will not affect the power of the InfluxDB and it would be possible to control access rights.

**Comment by pauldix** [comment]
You want to be able to select multiple databases in a query? Why do you have so many databases that it makes sense to use a regex?

**Comment by dashesy** [comment]
1- I want to see if I can use this for fine-grained user control, admin will be able to query them all but individual users will query their own.
2- I thought (you know better) this might help scaling, among users, instead of adding them all in one timeseries and using `user_id` as a tag I could give each a separate database. Lets say for 5000 users this will make 5000 databases instead of a long time series.

**Comment by pauldix** [comment]
I think it's going to be better to have `user_Id` as a tag. Otherwise I would recommend having some sort of middle layer that adds some sort of authorization on top. Having even a hundred databases would probably not be a very good idea.
