### ISSUE TITLE
UI error when "database not found"

### ISSUE THREAD

**Issue by areski** [influxdb/influxdb#1878]
This is happening on v0.9-RC9.

See screenshot for visual support.
![screenshot from 2015-03-07 00 22 52](https://cloud.githubusercontent.com/assets/53455/6538473/fff0066a-c462-11e4-95cf-ca4867f1967a.png)

**Comment by toddboom** [comment]
It looks like this is a result of new headers being sent after they were already written. I think #1985 has solved this, so I'm closing it out.
