### ISSUE TITLE
archive / rollup / precision tuning feature

### ISSUE THREAD

**Issue by jwestboston** [influxdb/influxdb#1884]
Many time series databases allow one to configure data retention policies which adjust the resolution of metrics after a certain period of time.  For example, I may want to keep metrics from 1+ years ago in my database, but I don't every single metric to a resolution of every data point every 10 seconds.  Instead, I'd like to have a resolution of an average() over every 5 minutes or so.

Will InfluxDB support this feature in the future?  It can really assist with data storage requirements -- as in not having to continuously add disks and scale if my retention policy is INF.

For reference, basically I'm looking for a feature like:  http://graphite.readthedocs.org/en/latest/whisper.html#archives-retention-and-precision

Thanks.

**Comment by beckettsean** [comment]
Downsampling is a core feature of InfluxDB:  http://influxdb.com/docs/v0.9/concepts/continuous_queries.html#downsampling-continuous-queries

Retention Policies also allow for automated expiry of old data.

**Comment by jwestboston** [comment]
@beckettsean Awesome, thank you.
