### ISSUE TITLE
play.influxdb.org is down?

### ISSUE THREAD

**Issue by AdoHe** [influxdb/influxdb#1885]
LGTM.

**Comment by henadzit** [comment]
The registration failed for me

![error message screenshot]
(http://i.imgur.com/gb4PgYK.png)

**Comment by toddboom** [comment]
I'll take a look at this.

**Comment by AdoHe** [comment]
@toddboom thanks very much :)

**Comment by toddboom** [comment]
@AdoHe this should be fixed now. thanks for letting us know!
