### ISSUE TITLE
Measurement still present after series deleted (0.9rc8)

### ISSUE THREAD

**Issue by nemesisdesign** [influxdb/influxdb#1887]
Suppose we have:

```
> select * from cpu_load_short
name            tags    time                            value
----            ----    ----                            -----
cpu_load_short          2009-11-10T23:00:00Z            1
cpu_load_short          2015-03-05T17:56:13.1015442Z    2
cpu_load_short          2015-03-05T17:58:06.07456592Z   1
cpu_load_short          2015-03-05T17:58:11.28167864Z   1
cpu_load_short          2015-03-05T17:58:19.4094144Z    2
cpu_load_short          2015-03-05T17:58:37.41576324Z   3
cpu_load_short          2015-03-05T17:58:46.73646848Z   4
cpu_load_short          2015-03-05T18:00:47.01290668Z   10
```

Let's drop the series cpu_load_short:
```
> drop series 7
```

I expect correctly "show series" to not show anything anymore,
```
> show series
```
I expect correctly that the previous query will return nothing
```
> select * from cpu_load_short
```
I expect that "show measurements" will show nothing but I'm wrong:
```
> show measurements
name		tags	name
----		----	----
measurements		cpu_load_short
```

It seems this is not intentional, at least according to the ML thread: https://groups.google.com/d/msg/influxdb/-MTytaEABpk/v9yAzsV6GlQJ

Tested on Ubuntu 14.04 LTS with 0.9rc8 (deb package).

**Comment by corylanou** [comment]
I believe this is working properly and by design.

The possible combinations for DROP SERIES are as follows:

`DROP SERIES <series id>`

`DROP SERIES FROM <measurement name>`

`DROP SERIES WHERE host = 'hosta.influxdb.org'`

`DROP SERIES FROM <measurement name> WHERE host = 'hosta.influxdb.org'`

Based on those possible scenarios, a measurement won't always be empty.  Also, we can't assume that you actually want the measurement to go away, as you asked to drop series data, not the measurement. It may be that the user intended to delete only a set of series data, and is going to begin re-inserting new data with the existing measurement.

To drop a measurement, use `DROP MEASUREMENT`

@otoolep was there something more to this that you thought was not correct that I'm not seeing?

**Comment by pauldix** [comment]
That's right, if you want the measurement gone you want to use `DROP MEASUREMENT foo`

**Comment by rafiti** [comment]
I am running with InfluxDB version 0.10.3-1,

I am expressing the same problem:
 drop series (from ... where...) doesn't work proparly, you can see my example below.
Please let me know if there is a work arround without the need to drop the measurment.
Thanks! 

> select log_time,memory_allocated from pnodes_info;
name: pnodes_info
-----------------
time                    log_time        memory_allocated
1458232823767000000     1458232823      6.442450944e+09
1458232823767000000     1458232823      6.442450944e+09
1458232823768000000     1458232823      4.294967296e+09
1458232823768000000     1458232823      4.294967296e+09
1458232823768000000     1458232823      4.294967296e+09
1458232836964000000     1458232836      6.442450944e+09
1458232836964000000     1458232836      6.442450944e+09
1458232836965000000     1458232836      4.294967296e+09
1458232836965000000     1458232836      4.294967296e+09
1458232836965000000     1458232836      4.294967296e+09

> drop series from pnodes_info where log_time < 1458232836;
> select log_time,memory_allocated from pnodes_info;
name: pnodes_info
-----------------
time                    log_time        memory_allocated
1458232823767000000     1458232823      6.442450944e+09
1458232823767000000     1458232823      6.442450944e+09
1458232823768000000     1458232823      4.294967296e+09
1458232823768000000     1458232823      4.294967296e+09
1458232823768000000     1458232823      4.294967296e+09
1458232836964000000     1458232836      6.442450944e+09
1458232836964000000     1458232836      6.442450944e+09
1458232836965000000     1458232836      4.294967296e+09
1458232836965000000     1458232836      4.294967296e+09
1458232836965000000     1458232836      4.294967296e+09
