### ISSUE TITLE
show strings as string literals in the data explorer

### ISSUE THREAD

**Issue by Wilfred** [influxdb/influxdb#1898]
![influxdb_strings](https://cloud.githubusercontent.com/assets/70800/6566739/9b44b5ee-c6b5-11e4-9882-d571102157e4.png)

In this picture, I actually had strings written to my database, but it's not at all clear and I wondered why all my graphs were at zero. It would be great if influxdb showed `"123"` rather than `123` in this case.

**Comment by beckettsean** [comment]
fixed
