### ISSUE TITLE
SHOW SERIES needs some output improvement

### ISSUE THREAD

**Issue by areski** [influxdb/influxdb#1901]
This is the output of series `events.stats.us.east-1`:

    > SHOW SERIES FROM "events.stats.us.east-1"
    name			tags	id	server_name	tag1	tag2	tag3
    ----			----	--	-----------	----	----	----
    events.stats.us.east-1		4	us.east-1			
    events.stats.us.east-1		5	us.east-1	2	2	10

When using influx on shell, the current result of `SHOW SERIES` is:

    > SHOW SERIES
    name			tags	id	continent	host		region
    ----			----	--	---------	----		------
    cpu_load_short			1			server01	us-west
    cpu_load_short			2	asia		server02	
    cpu_load_short			3	europe		server02	
    ----			----	--	---------	----		------
    events.stats.us.east-1		4	us.east-1				
    events.stats.us.east-1		5	us.east-1	2		2	10

A better result will be:

    > SHOW SERIES
    name			tags	id	continent	host		region
    ----			----	--	---------	----		------
    cpu_load_short			1			server01	us-west
    cpu_load_short			2	asia		server02	
    cpu_load_short			3	europe		server02	
    ----			----	--	---------	----		------
    name			tags	id	server_name	tag1	tag2	tag3
    ----			----	--	-----------	----	----	----
    events.stats.us.east-1		4	us.east-1				
    events.stats.us.east-1		5	us.east-1	2		2	10

**Comment by yogeswaran** [comment]
It will be also nice to capture the output into a file. I have thousands of series and when I run "SHOW SERIES" it is impossible to review the result.

**Comment by corylanou** [comment]
I meant to log a bug on the row names not being re-printed, so glad you did :-).

I think it would also be nice if you could run the CLI as a passthrough command.  That is coming likely in a future release hopefully.

As for outputting to a file, you could use the curl command for now and do something like:

```sh
curl -G http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=SHOW SERIES" 
```

And direct that to a file, etc.

Let me know if that helps for now.

**Comment by yogeswaran** [comment]
yes, I am using curl to dump to a file, this is good for now, thanks
