### ISSUE TITLE
GROUP BY TIME(...) not functioning

### ISSUE THREAD

**Issue by jnutzmann** [influxdb/influxdb#1904]
Just build the latest master and this query:

`SELECT COUNT(value) FROM my_series where device_id='8' GROUP BY TIME(1d)` 

returns the same as:

`SELECT COUNT(value) FROM my_series where device_id='8'`

These are the results:

`
{
    "results": [
        {
            "series": [
                {
                    "name": "my_series",
                    "columns": [
                        "time",
                        "MEAN"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            0.7957797837326895
                        ]
                    ]
                }
            ]
        }
    ]
}
`

**Comment by jnutzmann** [comment]
This is new in 0.9.0-rc10.  It worked as expected in 0.9.0-rc9.

**Comment by pauldix** [comment]
What did you get in RC9? Because as of RC10 the first query is a very bad idea. Without a time bound you're asking for 1 day summaries since 1970. What you actually should have received on the first query was an error stating that you requested too many summary intervals.

**Comment by jnutzmann** [comment]
The data in the series I am querying spans 30 days (2/10/15-3/11/15), so I get 30 rows back, one for each day (on the day boundaries) in RC9.  Whereas in the current master, I just get the one row with timestamp 0.

I just ran this query, however, in master and got a result like RC9:

`select mean(value) from current_melter where device_id='1' and time > '2015-02-10T00:00:00Z' group by time(1d)`

Do the buckets now start exactly at the minimum time specified, rather than on the natural boundaries?  If so, that might solve #1837 (and indirectly #388).

Instead of returning one record in RC10, perhaps it should return an error?

**Comment by pauldix** [comment]
You should now get back the number of buckets that you ask for. If you specify a group by time without limiting the time boundaries, you should get back an error. The times of the buckets are always modulo the group by time size.

Master doesn't solve those other issues, but the new implementation will make solving those issues possible.

**Comment by pauldix** [comment]
What happens on master if you issue that query without a where time specified?

**Comment by jnutzmann** [comment]
I'm not getting an error back on master (like you mentioned), just the one point starting at timestamp 0 (see below).  I am, however, getting buckets on the natural boundaries again when I specify time.

`
{
    "results": [
        {
            "series": [
                {
                    "name": "my_series",
                    "columns": [
                        "time",
                        "COUNT"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            275255
                        ]
                    ]
                }
            ]
        }
    ]
}
`

**Comment by nemesisdesign** [comment]
hey @pauldix, I checked the documentation for the 0.9.0 version:
http://influxdb.com/docs/v0.9/query_language/querying_data.html#group-by
If I'm not wrong, it does not advise to specify a time range.

I came on this issue after a case like the following one:

2 data points:

```
> select value from email.sent
name: email.sent
----------------
time				value
2015-03-13T14:22:57.78856772Z	1
2015-03-13T14:35:02.78533948Z	1
```

grouping by time without specifying a time range:

```
> SELECT count(value) FROM email.sent GROUP BY TIME(1m)
name: email.sent
----------------
time			count
1970-01-01T00:00:00Z	2
```

1970-01-01T00:00:00Z looked wrong.. so I started asking to myself: why is that? After reading your responses now is clearer, so I tried:

```
> SELECT count(value) FROM email.sent WHERE time > now() - 1h GROUP BY TIME(10m)
name: email.sent
----------------
time			count
2015-03-13T14:00:00Z	0
2015-03-13T14:10:00Z	0
2015-03-13T14:20:00Z	1
2015-03-13T14:30:00Z	1
2015-03-13T14:40:00Z	
2015-03-13T14:50:00Z	
```

It seems there are a few things that might be improved here.

First thing, I would advise to specify a time range in the documentation, and that's why I just opened a pull request there: https://github.com/influxdb/influxdb.org/pull/105

I hope it helps.

**Comment by pauldix** [comment]
Fixed in the docs https://github.com/influxdb/influxdb.org/pull/112
