### ISSUE TITLE
Poor performance before restarting Influxdb

### ISSUE THREAD

**Issue by yogeswaran** [influxdb/influxdb#1905]
Problem:
-----------
After installing Influxdb, I was able to ingest metrics at the rate of ~1000 metrics per second, I ran this test for 1 hour, after that I restarted Influxdb, now within couple of minutes, I was able to ingest ~6000 metrics per second. I wiped out the installation and tried few more times and it always had very poor performance in the beginning but after restarting Influxdb, performance seems to improve a lot.

Environment:
-----------------
* Influxdb version 0.9 RC9
* 1 VM with 4 CPUs and 8 GB RAM
* Ubuntu 14.04

**Comment by beckettsean** [comment]
Can you retry with a newer RC? Many performance-affecting components have been rewritten.
