### ISSUE TITLE
Add funnel type query

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#191]
Multiple people have asked for the ability to easily do funnel type queries with InfluxDB. Given users who visited, how many clicked to the pricing page, how many signed up, how many did x...

I think it's important enough to exist as a concept in the query language. Here's a proposal for how that might look.

```sql
select funnel(
  (type="visit", type="signup", visitor_id, 3d),
  (type="signup", type="paid", user_id, 7d))
from user_events
where time > "2014-01-20" and time < "2014-01-27"
group by time(1d)
```

What that query says is to return a time series of funnels. 7 days of them to be exact. Where the first stage of the funnel is a visit that turns into a signup. `visitor_id` is the field that joins the two events. The visit has 3 days to turn into a signup. So if we're looking at 2014-01-20, we'd look at all the visits from that day and then look for signups for that day and the following 2 days.

The second stage of the funnel is signups that turn into paid accounts. We'd look up to 7 days in the future of the initial visit for those conversions. This query would return something like this:

```json
[
{
  "name": "user_events",
  "columns": ["visit", "signup", "paid", "time"],
  "points": [
    [103, 21, 2, 1388552400],
    [122, 34, 3, 1388638800],
    ...
  ]
}
]
```

That would have 7 points, one for each day. Another option would be to have that funnel query return all of the actual raw events for the funnel. So you'd be able to see which actual users fell off at each stage.

Feedback welcome!

**Comment by alexjv89** [comment]
Is this funnel function implemented?

**Comment by jappievw** [comment]
Nope, it's marked as `revisit in the future`.

**Comment by alexjv89** [comment]
hmm.. Is there a known workaround this?

**Comment by jappievw** [comment]
Unfortunately not that I'm aware of :(.

**Comment by alexjv89** [comment]
ok.. I am trying to make it work for funnels. Will post if I figure out a way to do this.

**Comment by kzarzycki** [comment]
Hi! I see this post has been closed long time ago with a label "revisit in the future". I'm very interested in this feature, do you know if anyone started to work on it? Thanks!

**Comment by oliverjanik** [comment]
Any news?

**Comment by jnordberg** [comment]
The future is here! Let's revisit?
