### ISSUE TITLE
0.9.0-rc10 change  8086 port  causing a lot error

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#1927]
when change the data port  to 8087,the admin ui still query from 8086 port 
I saw the log show me 8086 still using for query
[srvr] 2015/03/12 17:16:33 broker cq: error hitting data node: http://mon:8086: Post http://pc-mon01:8086/process_continuous_queries: dial tcp 10.70.181.216:8086: connection refused

**Comment by Strekerud** [comment]
+1

**Comment by marcosnils** [comment]
@Strekerud @huhongbo if you specify the correct port when connecting to the database the UI works ok.

![image](https://cloud.githubusercontent.com/assets/1578458/7276617/3a921b6c-e8e1-11e4-89e8-b61d3544767e.png)

Make sure you re-connect using the correct port (clear cache just in case also). You shoudln't have any problems

**Comment by toddboom** [comment]
This should be better once #2746 is merged, which should be part of v0.9.1.
