### ISSUE TITLE
Windows 0.9.0-rc11: influx connects to wrong broker IP

### ISSUE THREAD

**Issue by andig** [influxdb/influxdb#1938]
Creating database fails (see https://github.com/influxdb/influxdb/issues/1886#issuecomment-78977882):

    Post http://machine:8086/messaging/messages?topicID=0&type=16: dial tcp 192.168.56.1:8086:     ConnectEx tcp: No connection could be made because the target machine actively refused it.

Connection to the broker is refused. However, influx chose the wrong IP address. This is my lan config:

	Drahtlos-LAN-Adapter Drahtlosnetzwerkverbindung:

	   Verbindungsspezifisches DNS-Suffix: fritz.box
	   IPv4-Adresse  . . . . . . . . . . : 192.168.0.54

	Ethernet-Adapter VirtualBox Host-Only Network:

	   Verbindungsspezifisches DNS-Suffix:
	   Verbindungslokale IPv6-Adresse  . : fe80::f1a0:b3da:f96e:426d%27
	   IPv4-Adresse  . . . . . . . . . . : 192.168.56.1

influx did actually grab the ip of a VirtualBox installation on my machine that isn't even running.... New Issue?

**Comment by andig** [comment]
Update: as of rc15, influx does seem to catch the right IP:

	2015/03/22 12:19:35 reconnecting to broker: url={http  <nil> HP20030235:8086 /messaging/messages index=0&streaming=true&
	topicID=0 }, err=Get http://machinename:8086/messaging/messages?index=0&streaming=true&topicID=0: dial tcp 192.168.0.54:8
	086: ConnectEx tcp: No connection could be made because the target machine actively refused it.

However, as the machine is running a firewall software, the broker cannot bind to `0.0.0.0` but only to `127.0.0.1`. For this purpose we'd need a config setting for the broker address or bind address to force it to localhost.

**Comment by beckettsean** [comment]
Hostname management and config is substantially updated in RC28. Can you try to repro on that version?
