### ISSUE TITLE
Tags cannot be numbers

### ISSUE THREAD

**Issue by nemesisdesign** [influxdb/influxdb#1939]
Trying something like the following:
```
write('logins', fields={'value': 1}, tags={'tag1': 1})
```

Getting back:

```
InfluxDBClientError: 500: {"error":"json: cannot unmarshal number into Go value of type string"}
```

Substituting `1` with `'1'` in `tags` works though:

```
write('logins', fields={'value': 1}, tags={'tag1': '1'})
```

**Comment by otoolep** [comment]
This is by design. Check out the docs here:

http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#tags

Any questions, let us know.

Philip

**Comment by nemesisdesign** [comment]
Ok sorry I missed that bit in the docs.

So in case I wanted to have a column that is a number but is also indexed as a tag I should make it both a (typecasted) tag and a column, right? Or maybe this doesn't make sense at all and there are better ways?

Thanks

**Comment by otoolep** [comment]
Yes, you can use set a tag to the string version of a number, but it not may make sense. You'd need to provide more details on your data, so we can provide schema advice. Please send a message to the mailing list since it's not a bug, just a question.

**Comment by nemesisdesign** [comment]
hey @otoolep this is the question i've sent on the ML: https://groups.google.com/d/msg/influxdb/DoP8gV9IBA8/gEQdlsWWlpoJ
