### ISSUE TITLE
installer should add logrotate config at installation time

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#1943]
When installing the code on POSIX systems it should drop a valid logrotate config into /etc/logrotate.d. Presumably the filename should be influxd.

Here's a proposal for the file contents:
```
/var/log/influxdb/influxd.log {
	daily
	rotate 7
	missingok
	dateext
	copytruncate
	compress
}
```
This will rotate logs daily, keeping a week's worth and compressing all non-active logs. It will date-stamp the compressed log files. The copytruncate command means the original log filehandle never changes. If the startup scripts are altered we may be able to eliminate that command. It does carry a small chance of missed log events.

**Comment by otoolep** [comment]
A logrotate file will be part of the 0.9.4 package.
