### ISSUE TITLE
Implement backpressure for topics that are full

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1946]
The brokers can buffer a certain amount of data on disk per topic (in segment files). There should be a setting for the max size a topic can get up to before the broker starts returning errors for writes to that topic. Those errors should get pushed back to the client writing data as 500 errors.

Note that the brokers should be able to accept writes to other topics that aren't backed up.

**Comment by otoolep** [comment]
No longer applicable in new design.
