### ISSUE TITLE
New data node should be able to request a topic that has been truncated

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1948]
As the brokers truncate the topic logs, they won't have a copy of the entire topic. When a data node connects to a broker and requests a topic from an index before what the broker has, it should respond to the data node with a list of other data nodes to request the topic from.

Once it copies that topic from another data node, it should be able to connect to the broker and pick up replication from the last written index.

**Comment by otoolep** [comment]
Initial work for this feature is here: https://github.com/influxdb/influxdb/pull/2433

Still needs some testing and tweaking. The corresponding work is have the client data node respond correctly to the 301.

**Comment by otoolep** [comment]
Remaining work here:

https://github.com/influxdb/influxdb/pull/2477
https://github.com/influxdb/influxdb/pull/2470

Trying two approaches, each quite similar to the other, but the former makes more use of channels.

**Comment by otoolep** [comment]
Not longer applicable.
