### ISSUE TITLE
Data nodes should poll for updates on old topics

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1949]
Currently, data nodes have an open connection to a broker for each topic they have a copy of. In a normal database there will be hundreds of topics on a single data node. All but 2-5 of these topics will be cold for writes so they won't be getting updates.

We shouldn't keep connections open for all those topics. Instead we should occasionally poll for updates. Would be best to batch the poll for all those topics up in a single request.

**Comment by otoolep** [comment]
No longer applicable in new design.
