### ISSUE TITLE
Retention Policies problem.

### ISSUE THREAD

**Issue by spaiter** [influxdb/influxdb#1953]
If I have several retention policies and write data to them, I only can get values from DEFAULT Retention Policy. When i trying to get data from series with not default retention policy server send me only keys with no value.

**Comment by otoolep** [comment]
Can you please show the sequence of `curl` commands that demonstrate this problem?

https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#bug-reports

**Comment by spaiter** [comment]
#How we can see we have 3 series (sessions, streams and system_stats)
curl -G "%host%/query?u=root&p=root&q=show%20series&db=database"
{"results":[{"series":[{"name":"sessions","columns":["id","country","stream"],"values":[[3,"RU","800/1sky.stream3"]]},{"name":"streams","columns":["id","host","stream"],"values":[[1,"host1.net","800/1sky.stream3"]]},{"name":"system_stats","columns":["id","host"],"values":[[2,"host1.net"]]}]}]}

#And we also have 3 retention policies (default, sessions and status). Police sessions marked as "default".
#Data to series session wroted with "sessions" policy, and data for stream and system_stats sersies was writed with "status" policy.
curl -G "%host%/query?u=root&p=root&q=SHOW%20RETENTION%20POLICIES%database&db=database"
{"results":[{"series":[{"columns":["name","duration","replicaN","default"],"values":[["default","0",1,false],["sessions","672h0m0s",1,true],["status","672h0m0s",1,false]]}]}]}

#When I'm trying to get data from sessions series all is normal.
curl -G "%host%/query?u=root&p=root&q=select%20*%20from%20sessions&db=database"
{"results":[{"series":[{"name":"sessions","columns":["time","type","created_at","deleted_at","ip","bytes_sent","user_agent"],"values":[["2015-03-14T13:26:48Z","rtmp",1.426339607785e+12,1.426339609719e+12,"83.222.69.181",997895,"Flash WIN 17,0,0,134"]]}]}]}

#But when I'm trying to get data from others series (streams or system_stats) I'm get only keys withoyt value.
curl -G "%host%/query?u=root&p=root&q=select%20*%20from%20system_stats&db=database"
{"results":[{"series":[{"name":"system_stats","columns":["time","total_input","total_output","cpu_usage","total_memavail","total_memused","total_memusage"]}]}]}

**Comment by pauldix** [comment]
I think this is just a question about querying. If you want to select from the other retention policies, you have to scope it in your query:

```sql
select * from status.stream
```

If you're querying data from the non-default policy, you need to put it in the from clause.
