### ISSUE TITLE
can we multiply values while query ?

### ISSUE THREAD

**Issue by related2blog** [influxdb/influxdb#1958]
hi,

i'm using influxdb + grafana, to analyse cloud vm usage. So i have scripts which query aws api s and gives me the no. of vms running and disk usage etc.... 

now my problem is  let's say i have 10 vms running, where i get charged $1 for each vm per hour.  I just want to visualize the charges also.

do i need to do calculations in my script and convert it into values and show on grafana or i can do any modifications in existing queries on grafana .

let me  be clear 
```
---------
[
  {
    "name": "aws",
    "columns": ["running vms"],
    "points": [ 5 ]
  }
]
-----------
```
i have query like  from a  given series 'aws' select 'running vms', so ill get '5' and it will be shown in graph. now i want to convert 5*$1 so it gives '20'. 

my purpose is i ran 5 vms for an hour and i'm charged $20 which needs to be graphed.

please help me.

thanks in advance.

**Comment by beckettsean** [comment]
Until InfluxDB is more mature this is more appropriately handled by the client reading the data.
