### ISSUE TITLE
Admin interface broken in 0.9.rc11

### ISSUE THREAD

**Issue by sammy007** [influxdb/influxdb#1961]
Getting "unauthorized request" in logs while trying to use it, no way to create database, no way to create users. Admin interface enabled in logs. Using debian package.

**Comment by toddboom** [comment]
@sammy007 i just tried this on a fresh ubuntu 14.04 image and it worked with no issues. if you've got data from a previous release candidate installation, you may need to remove it before upgrading to a newer version.

**Comment by sammy007** [comment]
I deleted everything with <code>sudo find ./ -iname '*influxdb*' | sudo xargs rm -rf</code>. What I missed?

**Comment by dstrek** [comment]
I got this issue too on a fresh debian vm using rc10. It was giving back garbage responses if your request had the header Accept-Encoding: gzip. Calls using curl work fine.

**Comment by dstrek** [comment]
Oh the problem is the Content-Type response header returned is incorrect.

```
Access-Control-Allow-Headers:Accept, Accept-Encoding, Authorization, Content-Length, Content-Type, X-CSRF-Token, X-HTTP-Method-Override
Access-Control-Allow-Methods:DELETE, GET, OPTIONS, POST, PUT
Access-Control-Allow-Origin:http://x.x.x.x:8083
Content-Encoding:gzip
Content-Length:66
Content-Type:application/x-gzip
Date:Mon, 16 Mar 2015 17:37:10 GMT
Request-Id:131cd244-cc03-11e4-819e-040144494101
X-Influxdb-Version:0.9.0-rc10
```

It's returning a json error in this instance so it should be application/json.

**Comment by ffosselle** [comment]
I'm having the same issue, fresh install and garbage upon return
0.9 rc10

**Comment by sammy007** [comment]
<code>
unauthorized request | user: "" | query: "SHOW DATABASES" | database ""\n
</code>
