### ISSUE TITLE
Windows 0.9.0-rc11 : unable to query new data after restart

### ISSUE THREAD

**Issue by adriencarbonne** [influxdb/influxdb#1964]
Hello,

When I run InfluxDB 0.9.0-rc11 on windows, it can insert and query data and everything is running well.

However, when I restart InfluxDB and insert data again, these new data points cannot be queried (the query SELECT * FROM xxx returns only the old data points inserted before the restart.

**Comment by adriencarbonne** [comment]
After studying more closely this problem, it seems that I can insert data points by specifying an "old" timestamp (several days ago) but not a recent timestamp.

**Comment by adriencarbonne** [comment]
Also reported by tangdunbin@gmail.com on Google Groups

**Comment by zzj1213** [comment]
same issue here

**Comment by beckettsean** [comment]
Is this still relevant with 0.9.0 RC26?
