### ISSUE TITLE
Upgrade - failed to open broker - checksum error

### ISSUE THREAD

**Issue by easyrasta** [influxdb/influxdb#1965]
Hi,
I upgraded from rc9 to rc12, influxdb wont start. I get failed to open broker: open meta: meta0 error: checksum error

If I move raft directory, then restart, I get on writing data: {"error":"create shard(mypolicy/2015-03-12T00:02:00Z): log closed"} and cluster seem don t working.

**Comment by pauldix** [comment]
You'll have to start fresh with rc12. We're not at a point yet where upgrades between RCs are guaranteed to be safe.

**Comment by jd** [comment]
FWIW I have the same error with – AFAIK – no data from previous RC – or I am unable to find where those data are.
