### ISSUE TITLE
rc12: since stats were implemented you can't call a db 'stats'

### ISSUE THREAD

**Issue by sanga** [influxdb/influxdb#1966]
Or at least that's what I guess is happening as this worked against rc10:

```
⇒  curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE stats"
{"error":"error parsing query: found STATS, expected identifier at line 1, char 17"}% 
```

In my opinion you should be allowed to call a db 'stats', but if that makes things too complex to parse then I accept that it's a bit of an edgecase.

**Comment by sanga** [comment]
Or actually I think I'm being overly anal here. You can't call databases 'select' or other reserved keywords I'm sure either in many dbs.

**Comment by pauldix** [comment]
I think it's worth picking a different name for our built in system database though. Since many people probably use `stats`. Maybe `system` @otoolep?

**Comment by corylanou** [comment]
This is part of the query language now, it has nothing to do with the database name.  The internal name is `_stats` I believe or something like that.

We would have to change it from `SHOW STATS` to something like `SHOW SYSTEM-STATS`, etc.  I'm not sure if they can still create a database name called "stats" by quoting it.  This is the same now as trying to create a database name called "select", or "drop", etc.

**Comment by pauldix** [comment]
ah right, `SHOW STATS`. Ok, never mind what I said :)
