### ISSUE TITLE
error parsing query: found INTO, expected ;, EOF

### ISSUE THREAD

**Issue by apoydence** [influxdb/influxdb#1976]
I am trying to use continuous queries, however when I use the CLI to run example query: 

```
SELECT COUNT(name) FROM clicks GROUP BY time(1h) INTO clicks.count.1h
```

I get the following error:

```
error parsing query: found INTO, expected ;, EOF
```

Is this a doc bug or something deeper?

**Comment by toddboom** [comment]
@apoydence The syntax of the continuous queries has changed for v0.9.0. You'll need to do something like this:

https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md#create-continuous-query
