### ISSUE TITLE
Error with parsing CQ 

### ISSUE THREAD

**Issue by apoydence** [influxdb/influxdb#1981]
I tried the Continuous Query example from the [docs](https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md#create-continuous-query) in the CLI: 

```
CREATE CONTINUOUS QUERY 10m_event_count ON db_name BEGIN SELECT count(value) INTO 10m.events FROM events GROUP BY time(10m) END
```

But I get the following error:

```
ERR: error parsing query: found 10m, expected identifier at line 1, char 25
```

**Comment by pauldix** [comment]
That's because the example is wrong. Names with digits in them need to be double quoted. Fixed in #2049
