### ISSUE TITLE
Constant background writing to disk without any input - v0.9.0-rc12

### ISSUE THREAD

**Issue by dprime** [influxdb/influxdb#1986]
I'm running a test influx with default configs and I've written a few MB of data to it and queries now crawl. Additionally there is constant background writing to disk at a rate of approx 50Kb/sec. Why would influx be writing to disk when there's no input from senders?

**Comment by toddboom** [comment]
Closing this out for now because it no longer seems to be an issue. Please let us know if you still see it with RC27 or higher and we can reopen.
