### ISSUE TITLE
implement `SELECT tagName FROM m`

### ISSUE THREAD

**Issue by dgnorton** [influxdb/influxdb#1989]
Implement selecting tag values to be displayed in the results.

**Comment by pauldix** [comment]
A related issue is #1997. This may just fix things.

Also note that we'll need some validation here. It doesn't make sense to return the tag values if they have a `GROUP BY time`. If they have a group by time, any tags that show up in the select clause should actually be taken out of there and put into the group by clause.

**Comment by ReAzem** [comment]
+1! yay :)
