### ISSUE TITLE
RRD

### ISSUE THREAD

**Issue by hoffoo** [influxdb/influxdb#1991]
Currently our major use for influx is to store metrics across our clusters, and its excellent.

What we would like is have an RRD style database which aggregates statistics on each series based on a configuration (for example average out the last minute worth of data that is older than a day). I can imagine how we would go about making this ourselves, but I was curious if this had been brought up before?

**Comment by pauldix** [comment]
Please ask stuff like this on the Google Group: The feature you're looking for is continuous queries: http://influxdb.com/docs/v0.8/api/continuous_queries.html

In 0.9.0 you can pair that with retention policies. There will be more docs on that as we get closer to release.
