### ISSUE TITLE
database name cannot start with an int

### ISSUE THREAD

**Issue by robbyt** [influxdb/influxdb#1993]
In 0.9 rc12, it seems that database names are being inferred incorrectly if they start with an integer. e.g., I am unable to create a database named "1hello" but I can create one called "hello1"

The error I get from the former is `{"error":"error parsing query: found 1h, expected identifier at line 1, char 17"} `

**Comment by beckettsean** [comment]
database names starting with non-alpha characters require double-quoting. The docs will reflect this soon ;)
