### ISSUE TITLE
Special Characters in INNER JOIN

### ISSUE THREAD

**Issue by pedrojimenez** [influxdb/influxdb#1995]
Hi i have been looking for info about special characters in your Issues. I have found the #267 one and it is working perfectly in a select statement.

I am using `influxdb 0.8.8` and the problematic is this:

I want to SUM the values of several series to show a single value, i mean, 2 differents traffic_in series and show the sum value of both.

I have found that when **forward slash** is contained in the interface name i can't perform the **inner join**. I will expose it with 2 examples:

Working Example:
```
select s1.value + s2.value
from "device01.Traffic_GigabitEthernet0.GigabitEthernet0_traffic_in" as s1
inner join "device01.Traffic_GigabitEthernet9.GigabitEthernet9_traffic_in" as s2
where time > now() -1h
```

Not Working Example:
```
select s1.value + s2.value
from "device02.Traffic_GigabitEthernet0_1.GigabitEthernet0/1_traffic_in" as s1
inner join "device02.Traffic_GigabitEthernet0_2.GigabitEthernet0/2_traffic_in" as s2
where time > now() -1h
```

The query does not return a error message, just return nothing. I have added quotes to different parts of the query but nothing returned either.

Could you help me ?

**Comment by pauldix** [comment]
Joins have changed in 0.9.0 so this won't be an issue there. We won't be fixing this in 0.8.x

**Comment by pedrojimenez** [comment]
Ok thanks Paul
