### ISSUE TITLE
Document if/how 'password' string should be escaped

### ISSUE THREAD

**Issue by jamshid** [influxdb/influxdb#2011]
I know the entire string gets url-escaped, but how should the characters in the password be escaped? I.e. can an apostrophe be used in a password and is it escaped like SQL `''` or with backslash?
```
CREATE USER <username> WITH PASSWORD '<password>'
```

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/influxdb.com/issues/123 on the docs repo.
