### ISSUE TITLE
Server shard map not reloaded on restart

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2012]
cc @benbjohnson 

My testing shows this to be true. It's loaded when a shard is created, but not when the metastore is re-loaded.

**Comment by pauldix** [comment]
@otoolep can you give more detail on this? I'm not quite sure what this means.

**Comment by otoolep** [comment]
Specifically, when a shard group is created, this code is executed:

https://github.com/influxdb/influxdb/blob/master/server.go#L1024

which updates:

https://github.com/influxdb/influxdb/blob/master/server.go#L73

but when this function is executed:

https://github.com/influxdb/influxdb/blob/master/server.go#L271

the map is not updated. I hit this during stats work, and planned to fix it as I continued my work on stats.

**Comment by otoolep** [comment]
This is my hypothesis. All I have actually seen is that the map goes to `[]` after a restart and reload from metastore.

**Comment by pauldix** [comment]
So wait, does that mean after restart none of the shards are there?

**Comment by pauldix** [comment]
That's what I'm more interested in. What happens and what the severity of
the issue is.

**Comment by otoolep** [comment]
Queries continue to work fine after a restart, so it's not that serious. The system uses a different path when it comes to finding shards for reads and writes, this map is not actually that critical. I believe it's just for the purposes of optimization (some early idea we had), and the authoritative data is in the database and retention policy objects. In fact I was considering *removing* it since it seems like cruft. @benbjohnson might know better of course.

**Comment by otoolep** [comment]
Fixed.
