### ISSUE TITLE
list series with negative regex cause to exception

### ISSUE THREAD

**Issue by evgygor** [influxdb/influxdb#2014]
I'm trying to list series except those that name starts with string "1min" by next query:

list series /^(?!1min).*/

The error is "error parsing regexp: invalid or unsupported Perl syntax: `(?!`"

**Comment by pauldix** [comment]
This is fixed in 0.9.0 with the `~! /some regex/` operator in the where clause. We won't be making any new fixes to the 0.8 line.

**Comment by evgygor** [comment]
Thanks

**Comment by saidimu** [comment]
@pauldix So there is no way to accomplish regex negation in the 0.8 series?

**Comment by pauldix** [comment]
@saidimu not with 0.8

**Comment by hiveonline** [comment]
@pauldix Typo in your answer (`!~` not `~!`) which threw me, but thank you!

**Comment by jontejj** [comment]
@pauldix 
For 

SELECT mean("75-percentile") * mean("count") FROM /^.*DbMapper.*$/ WHERE ~! /^size.*$/ AND time > now() - 7d GROUP BY time(5m) fill(null)
--

 {
  "error": "error parsing query: found ~, expected identifier, string, number, bool at line 1, char 74",
  "message": "error parsing query: found ~, expected identifier, string, number, bool at line 1, char 74"
}

How to specify the name of the measurement in the where clause?
