### ISSUE TITLE
Implement "SHOW DIAGNOSTICS"

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2018]
This complements `SHOW STATS`. It will show diagnostic, as opposed to statistical information. 

Common for all nodes:
- uptime.
- free disk stats.
- number of file descriptors.
- Go GC stats.
- Process memory usage.

Example diagnostic data on data node.
- last Raft log index processed by data node.
- last heartbeat sent.
- number of inbound and outbound network connections.
- number of topics.
- number of "active" topics ("active" TBD")

Example diagnostic data on broker:
- number of connected data nodes.
- number of connected Broker nodes.
- leader or not.
- received heartbeat stats.

**Comment by toddboom** [comment]
can we call it `SHOW DIAGNOSTICS` instead?

**Comment by toddboom** [comment]
verbosity == :heart:

**Comment by otoolep** [comment]
Sure, fine with that.

**Comment by otoolep** [comment]
Data nodes:

- last time each shard was written to.
- last time each shard was read.
- last time a shard was a created.
- last time a shard was deleted.

**Comment by otoolep** [comment]
- Metastore details, though much of this information is also available through `SHOW SERIES`. 
- Size of each shard on disk.

**Comment by otoolep** [comment]
Maybe you want `SHOW STATISTICS` @toddboom ?

**Comment by toddboom** [comment]
@otoolep I wouldn't mind it, but I'm willing to relent on that one - I feel like `STAT` is a more generally accepted abbreviation than `DIAG`.

**Comment by otoolep** [comment]
- software version and commit.

**Comment by otoolep** [comment]
- shard group start and end times.

**Comment by otoolep** [comment]
Gone as far as we're going to go now, for the first version.
