### ISSUE TITLE
Wire up ORDER BY

### ISSUE THREAD

**Issue by apoydence** [influxdb/influxdb#2022]
```
> select statusCode from SeriesName order by time desc limit 10
name: HttpRequestRate
---------------------
time				statusCode
2015-03-19T20:09:14.667313352Z	200
2015-03-19T20:09:14.667531825Z	200
2015-03-19T20:09:14.674292103Z	200
2015-03-19T20:09:14.674539615Z	200
2015-03-19T20:09:23.334009887Z	200
2015-03-19T20:09:23.334241444Z	200
2015-03-19T20:09:23.33466066Z	200
2015-03-19T20:09:38.333210425Z	200
2015-03-19T20:09:38.333536172Z	200
2015-03-19T20:09:38.334099221Z	200

> select statusCode from SeriesName order by time asc limit 10
name: HttpRequestRate
---------------------
time				statusCode
2015-03-19T20:09:14.667313352Z	200
2015-03-19T20:09:14.667531825Z	200
2015-03-19T20:09:14.674292103Z	200
2015-03-19T20:09:14.674539615Z	200
2015-03-19T20:09:23.334009887Z	200
2015-03-19T20:09:23.334241444Z	200
2015-03-19T20:09:23.33466066Z	200
2015-03-19T20:09:38.333210425Z	200
2015-03-19T20:09:38.333536172Z	200
2015-03-19T20:09:38.334099221Z	200
```

**Comment by cannium** [comment]
+1

**Comment by neonstalwart** [comment]
i hate to just +1 so here's a shell script.  i hope this isn't overlooked for 0.9

```sh
echo "creating database"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"

echo "inserting data"
curl -d "{\"database\" : \"foo\", \"points\": [{\"name\": \"cpu\", \"tags\": {\"region\":\"uswest\",\"host\": \"server01\"},\"fields\": {\"value\": 100}}]}" -H "Content-Type: application/json" -ipv4 http://localhost:8086/write

echo "inserting data"
curl -d "{\"database\" : \"foo\", \"points\": [{\"name\": \"cpu\", \"tags\": {\"region\":\"uswest\",\"host\": \"server01\"},\"fields\": {\"value\": 300}}]}" -H "Content-Type: application/json" -ipv4 http://localhost:8086/write

echo "inserting data"
curl -d "{\"database\" : \"foo\", \"points\": [{\"name\": \"cpu\", \"tags\": {\"region\":\"uswest\",\"host\": \"server01\"},\"fields\": {\"value\": 200}}]}" -H "Content-Type: application/json" -ipv4 http://localhost:8086/write

sleep 1

echo "querying data"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=select * from cpu order by value asc" --data-urlencode "pretty=true"

echo "querying data"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=select * from cpu order by value desc" --data-urlencode "pretty=true"
```

**Comment by neonstalwart** [comment]
@beckettsean could this get put into the 0.9.0 milestone?

**Comment by ReAzem** [comment]
Same issue here.

**Comment by CrazyJvm** [comment]
really wanna know how this issue going?

**Comment by pauldix** [comment]
This will have to wait for a refactoring we're about to do on the query engine. Pushed to 0.9.1

**Comment by krylovsk** [comment]
So what is the "get the latest value of measurement X" workaround until then?

**Comment by pauldix** [comment]
Unfortunately, there is no good way to get it until we have that set up. If you have a regular sampling interval and you know it, then you can limit the time scope of your query accordingly.

**Comment by Jhors2** [comment]
Not sure if you would like a new issues recorded or not, but doing an order by tag keys alpha sort would be VERY valuable for visualization. 

Something like:
select value from "cpu" where hostname =~ /http.*/ group by hostname order by hostname asc

**Comment by pauldix** [comment]
@Jhors2 returned series are already returned in a consistent order so I'm not sure if this adds anything for that case.

**Comment by beckettsean** [comment]
@pauldix if `LIMIT` is used the series are not returned in consistent order:

```
> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	4444.15625

> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	4455.140625

> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	34324.8046875

> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	34706.5703125

> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	34324.8046875

> select value from cpu_system limit 1 
name: cpu_system
----------------
time				value
2015-06-26T19:21:54.661779022Z	4444.15625
```

Also, in conjunction with `LIMIT` and `SLIMIT`, `ORDER BY DESC` vs `ORDER BY ASC` has real merit, even if the ordering is deterministic otherwise, at least until #1577 is solved and possibly even beyond.

**Comment by Jhors2** [comment]
I'll echo @beckettsean comments.  The other instance that I currently have is as follows:
I write a few points as follows:
```as_path_bps,as_path=122_366_444,pop=iad01 value=121312 192318012331```
```as_path_bps,as_path=122_366_444,pop=iad01 value=132423 123717273123```
```as_path_bps,as_path=1_333_654,pop=arn01 value=1239951 1290881203128```

The order by would be able to always return POP tag keys in order.  Meaning, top to bottom we return ARN01 first, and iad01 second.  This is even with multiple group by where I could do a query as follows:

```select sum(value) from as_path_bps where time > now() - 10m group by as_path,pop fill(0)```

Currently it appears that they are turned consistently in the same order, however it appears to sort by my as_path tag key regardless of the way that I query it.

**Comment by zhulinhong** [comment]
Why don't support this ? I think it is very useful in my case.
So how can we get the newest point? @pauldix

**Comment by aviau** [comment]
> Why don't support this ?

It's in the roadmap. Don't worry.

**Comment by runner-mei** [comment]
It's in the roadmap. 9.2?

**Comment by zhulinhong** [comment]
Thanks for your reply, so when can we get that version?

**Comment by beckettsean** [comment]
@zhulinhong we do not publish release dates for features. The 0.9.2 release will be out on July 23rd and this issue is currently scheduled for that release, but that doesn't mean it will be in that version. This issue contains ALL relevant info about the schedule and progress.

**Comment by dswarbrick** [comment]
0.92rc1 has an odd sense of humour.

```
> select derivative(value) from "interface_rx" where host='host.example.com' and instance='eth0' and type='if_octets' and time < now() - 1h group by time(1m) order by asc;
ERR: only ORDER BY ASC supported at this time
```

**Comment by jacekgrzybowski** [comment]
did it make it into 0.9.2?

**Comment by gunnaraasen** [comment]
Working `ORDER BY` did not make it into 0.9.2. The distributed query engine rewrite ended up taking the whole 0.9.2 development cycle to complete. Hooking up `ORDER BY` is a high priority for 0.9.3.

@dswarbrick That error will be not be in 0.9.2 final (see #3409).

**Comment by CrazyJvm** [comment]
seem will not make it into 0.9.3 still...... really need this feature. Any related PR or solution discussion?

**Comment by beckettsean** [comment]
@CrazyJvm this is the only relevant issue for ORDER BY. I am unaware of a working PR yet.

**Comment by bal2ag** [comment]
Without orderby desc, is there a simple way to get the latest point for a given series? Right now it seems like I have to select all the points in the series and take the last one in my application. Not difficult but it's a lot of extra reads against the DB. I can cut it down by filtering on time but this comes at the possible cost of accuracy/data correctness in my use case (I won't always known how far back the "latest" point will be).

**Comment by jacekgrzybowski** [comment]
You can use `last()` function, if you don't need the timestamp.

**Comment by pauldix** [comment]
yeah, but the way the `last` function works would be very inefficient. Realistically, we need to have this done so people can get the most recent data point in a series efficiently.

**Comment by beckettsean** [comment]
@jwilder are you just wiring up ASC and DESC for ORDER BY time, or will you also add ORDER BY tag in this iteration?

**Comment by jwilder** [comment]
@beckettsean Just time.

**Comment by beckettsean** [comment]
Added https://github.com/influxdb/influxdb/issues/3954 for ORDER BY tag
