### ISSUE TITLE
SHOW RETENTION POLICIES is non-deterministic

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2035]
Currently, it does not sort the results, so the tests fail intermittently here:

https://github.com/influxdb/influxdb/blob/master/httpd/handler_test.go#L306

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/2059/files

**Comment by otoolep** [comment]
All fixed.

https://github.com/influxdb/influxdb/commit/db28814e3248dc9f88b373daa0431c14eb5b1013
