### ISSUE TITLE
Queries with relative times seem to be off

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2045]
From this thread: https://groups.google.com/forum/?#!msg/influxdb/WLPOANOb0B8/HWC239vQbJUJ

Looks like queries with `WHERE time > now() - 1h` or something like that are doing weird things. Maybe a timezone thing? Something else? Please to investigate.

**Comment by jnutzmann** [comment]
My apologies, but it looks like this is a bug that was mistakenly introduced in PR #2016.  That said, there were issues with how the time for these queries was computed before (and the bucket problem).

When I added the code to `NextInterval` in tx.go, I assumed that `interval` was only greater than zero if there was truly an interval (group by in use).  This is not the case, as `Execute` in engine.go sets it to the span between min time and max time.  Therefore, `NextInterval` incorrectly tries to normalize the start time to a natural boundary when it shouldn't.

I think the solution is getting rid of `m.interval = m.TMax - m.TMin` on line 97 of engine.go, adding a check for zero on line 132 like this:

```go
if m.interval > 0 {
	startTimeBucket = m.TMin / m.interval * m.interval
} else {
	startTimeBucket = m.TMin
}
```
then, in tx.go we can add an else case in `NextInterval` like this:

```go
if interval > 0 {
	// Make sure the bottom of the interval lands on a natural boundary.
	intervalBottom = intervalBottom / interval * interval
	l.tmax = intervalBottom + interval - 1
} else {
	l.tmax = l.job.TMax
}
```
I have a local version running now and am working on testing it.

**Comment by jnutzmann** [comment]
This solution causes some group by queries to fail when a minimum time is not specified.  I am tied up in meetings for the next few hours, but can get back to it after that.

**Comment by pauldix** [comment]
This is fixed in RC16.

**Comment by nemesisdesign** [comment]
tested! :+1:
