### ISSUE TITLE
Frequently starts swapping until process gets killed

### ISSUE THREAD

**Issue by jheusser** [influxdb/influxdb#2051]
Influxdb regularly starts swapping until all swap is used and then gets killed by the kernel. This happens regularly (every day) when used in conjunction with Grafana. It perhaps runs 4 queries, all time constrained with a where-clause to 1 or 2 days of secondly data. There's no heavy write activity.

System info:
- InfluxDB v0.8.3 (git: fbf9a47) (leveldb: 1.15) from apt repo
- Linux 3.13.0-32 64bit VPS Ubuntu 
- 1gb of ram and 1gb of swap

I already constrained the settings to
```
[storage.engines.rocksdb]
max-open-files = 300
lru-cache-size = "200m"
```

Are there any other resources/ulimit or similar that I could constrain so this does not happen? Can I make Influxdb log more so I could attach useful information here? And should this happen at all given that I'm not querying a huge amount of data points?

Thanks

**Comment by pauldix** [comment]
Not sure what this is, but we won't be making any more releases to the 0.8 line. This almost certainly isn't a problem in the upcoming 0.9 release.
