### ISSUE TITLE
TestServer_RawDataReturnsInOrder

### ISSUE THREAD

**Issue by jfzw42** [influxdb/influxdb#2052]
I compiled the latest branch on raspberry and started the tests. First error occurs on 
=== RUN TestServer_RawDataReturnsInOrder
--- FAIL: TestServer_RawDataReturnsInOrder (10.52s)
        server_test.go:1406: unexpected row(0) during COUNT: {"series":[{"name":"cpu","columns":["time","count"],"values":[["1
970-01-01T00:00:00Z",271]]}]}

**Comment by jfzw42** [comment]
please note : count value differs on every test I run.

**Comment by otoolep** [comment]
Thanks @jfzw42 -- fix should be coming shortly.
