### ISSUE TITLE
Queries don't work in 0.9 rc15

### ISSUE THREAD

**Issue by NikolaBorisov** [influxdb/influxdb#2054]
I'm trying to test 0.9 rc15 and I think something is broken.
I tried to insert one point like this coping from the documentation page

```
curl -XPOST 'http://localhost:8086/write' -d '
{
    "database": "test",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "timestamp": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
}
'
```

Next again coping from the website I do:
```
curl -G 'http://localhost:8086/query' --data-urlencode "db=test" 
--data-urlencode "q=SELECT value FROM cpu_load_short WHERE region=us-west"
```
but I get this:
```
{"results":[{"error":"unknown field or tag name in where clause: us"}]}
```
When I do SHOW SERIES, I get this which means something is working.
```
{"name":"cpu_load_short","columns":["id","host","region"],"values":[[5,"server01","us-west"]]}
```

**Comment by otoolep** [comment]
Thanks Nikola -- seems like the docs are not quite right. You must
single-quote the tag value like so:

curl -G 'http://localhost:8086/query' --data-urlencode "db=test"
--data-urlencode "q=SELECT value FROM cpu_load_short WHERE region='us-west'"

I have corrected the docs, and they will be published soon.

https://github.com/influxdb/influxdb.org/commit/86e27c2e149b371f1cf07015cf6c49688beae39c

Philip
