### ISSUE TITLE
Loss of all data in influx database

### ISSUE THREAD

**Issue by Johnneren** [influxdb/influxdb#2056]
Hi.

I have a grafana + collectd + influxdb setup on my homemade linux NAS and yesterday I lost all data in my influx DB.

I accidentally performed a select of ALL series / data for all time (1-2 months worth, 400 series, 1 point each, 10sec log interval... database was about 1 GB in size) I executed this select a few times before i saw the problem. (Line 606 in log)

This caused the influx DB to burn CPU and so I tried restarting the service, which didn't help and then I rebooted the NAS.
After this all data in the collectd + grafana databases was lost.

I'm not 100% sure but rsync might also have been in the progress of backing up the database folder to a USB drive. (my backup became corrupt also)

Log is here:
https://gist.github.com/Johnneren/88c2d041571ffcf96e9a
Did I do something wrong? (And was it 'so' wrong that flush of all data was to be expected)

v0.8.8 - stable

**Comment by pauldix** [comment]
I'm not sure what the problem was here. It sounds like something was corrupted, but I don't know. Did you have a backup?

We won't be putting out any more releases in the 0.8 line and this is almost certainly not a problem in 0.9 so I'm closing this for now.
