### ISSUE TITLE
Prohibit numerical functions on non-numerical data

### ISSUE THREAD

**Issue by anaray** [influxdb/influxdb#2062]
Following test case brings down the influxdb server
It happens when incompatible query function is applied on a column.

curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE stats.memory"

echo "creating retention policy"
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY stats_sret ON stats.memory DURATION 1h REPLICATION 3 DEFAULT"

echo "inserting data"
curl -d '{"database":"mule.stats","points":[{"name":"mule.stats.memory","fields":{"share":"1.8M","resident":"4.6M","size":"794M"}}]}' -H "Content-Type: application/json" http://localhost:8086/write
curl -d '{"database":"mule.stats","points":[{"name":"mule.stats.memory","fields":{"share":"2.8M","resident":"5.6M","size":"779M"}}]}' -H "Content-Type: application/json" http://localhost:8086/write

echo "querying data"
curl -G http://localhost:8086/query --data-urlencode "db=mule.stats" --data-urlencode "q=select max(share) from mule.stats.memory"

Please note function max is applied on column share which is a string. I pulled the latest code before doing this test.

From logs :

[http] 2015/03/24 10:51:44 127.0.0.1 - - [24/Mar/2015:10:51:44 +0530] POST /write HTTP/1.1 0 0 - curl/7.22.0 (i686-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3 a92acc93-d1e5-11e4-a019-b888e3366f06 379.952µs
panic: interface conversion: interface is string, not float64
github.com/influxdb/influxdb/influxql.MapMax(0xb777ed40, 0x18b5dd90, 0x0, 0x0)
	/home/msi/dev/others/git/influx/src/github.com/influxdb/influxdb/influxql/functions.go:241 +0x80

**Comment by otoolep** [comment]
Thanks @anaray -- this is a known issue, but we had not opened a ticket for it, as far as I can tell. I have updated this ticket with a specific title.

The system needs to behave sensibly in this case, and not panic. What it will do is refuse to execute the query. The system supports this kind of checking, but it has not been implemented yet.

**Comment by otoolep** [comment]
A clear error message should now be returned, instead of a panic.
