### ISSUE TITLE
can't create a database, results is "error":"log closed"

### ISSUE THREAD

**Issue by jfzw42** [influxdb/influxdb#2066]
Hello
Compiled and passed tests of the current branch. influxd starts fine. 
The command :
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE mydb"
results in the following result
{"results":[{"error":"log closed"}]}

searcing into the code, this seems to be related to raft but I have no clue on the root cause.

**Comment by jfzw42** [comment]
i found the root cause.
Here is my config:
[broker]
# Where the Raft logs are stored. The user running InfluxDB will need read/write access.
dir  = "/var/influxdb/broker"
port = 8086

I created the /var/influxdb/broker manually before starting influxd ==> I got a message "log pending"
I deleted the "broker" directory ==> influxd starts, creates the directory and all is OK, I can create a database, etc.

**Comment by dashesy** [comment]
@jfzw42 perhaps when you manually created the directory you forgot to give influxdb user access to the log file?

```bash
sudo chown +R  influxdb:influcdb /var/influxdb
```

**Comment by jfzw42** [comment]
@dashesy, user and group were ok, and influxd created the subdirectory raft and the meta file but not the other directory (named '0' in my case).

**Comment by beckettsean** [comment]
should be fixed in latest version.
