### ISSUE TITLE
Add static binary to distribution

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2070]
We need to also distribute the static binaries for anyone that doesn't want to use an installer.

**Comment by corylanou** [comment]
This will address https://github.com/influxdb/influxdb/issues/2069#issuecomment-86021740

**Comment by quantbits** [comment]
This might be helpful: http://stackoverflow.com/questions/29346093/how-to-create-a-static-go-binary-which-runs-on-every-distro

**Comment by beckettsean** [comment]
Closed. This is done, just need to document it: https://github.com/influxdb/influxdb.com/issues/76

**Comment by smebberson** [comment]
@beckettsean, where can I find the static binaries?

**Comment by rossmcdonald** [comment]
@smebberson Standalone binaries are available through the downloads page here:

https://influxdata.com/downloads/#influxdb

**Comment by smebberson** [comment]
@rossmcdonald, thanks for getting back to be. But I was hoping for a static binary? I could be doing something wrong, however, the following outputs shows downloading the file and inspecting with `ldd` and it seems as though those binaries haven't been statically compiled?

```
vagrant@ubuntu-14:/src$ wget https://s3.amazonaws.com/influxdb/influxdb_0.9.6.1_x86_64.tar.gz
--2015-12-14 10:16:36--  https://s3.amazonaws.com/influxdb/influxdb_0.9.6.1_x86_64.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.82.36
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.82.36|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13386496 (13M) [application/x-tar]
Saving to: ‘influxdb_0.9.6.1_x86_64.tar.gz’

2015-12-14 10:16:55 (771 KB/s) - ‘influxdb_0.9.6.1_x86_64.tar.gz’ saved [13386496/13386496]

vagrant@ubuntu-14:/src$ tar xvfz influxdb_0.9.6.1_x86_64.tar.gz
./
./influxdb_0.9.6.1_x86_64/
./influxdb_0.9.6.1_x86_64/usr/
./influxdb_0.9.6.1_x86_64/usr/bin/
./influxdb_0.9.6.1_x86_64/usr/bin/influx
./influxdb_0.9.6.1_x86_64/usr/bin/influx_stress
./influxdb_0.9.6.1_x86_64/usr/bin/influxd
./influxdb_0.9.6.1_x86_64/usr/bin/influx_inspect
./influxdb_0.9.6.1_x86_64/usr/lib/
./influxdb_0.9.6.1_x86_64/usr/lib/influxdb/
./influxdb_0.9.6.1_x86_64/usr/lib/influxdb/scripts/
./influxdb_0.9.6.1_x86_64/usr/lib/influxdb/scripts/influxdb.service
./influxdb_0.9.6.1_x86_64/usr/lib/influxdb/scripts/init.sh
./influxdb_0.9.6.1_x86_64/etc/
./influxdb_0.9.6.1_x86_64/etc/influxdb/
./influxdb_0.9.6.1_x86_64/etc/influxdb/influxdb.conf
./influxdb_0.9.6.1_x86_64/etc/logrotate.d/
./influxdb_0.9.6.1_x86_64/etc/logrotate.d/influxdb
vagrant@ubuntu-14:/src$ ldd ./influxdb_0.9.6.1_x86_64/usr/bin/influx
	linux-vdso.so.1 =>  (0x00007ffff93d1000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4b1a38e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b19fc8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b1a5b4000)
vagrant@ubuntu-14:/src$ ldd ./influxdb_0.9.6.1_x86_64/usr/bin/influxd
	linux-vdso.so.1 =>  (0x00007fff62ece000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4374f14000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4374b4e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f437513a000)
```

**Comment by otoolep** [comment]
Those libraries are standard libraries dynamically linked by almost all non-trivial Go programs. When Go claims to be a statically linked system, it means except for those libraries shown above. This is not something special to InfluxDB.

**Comment by smebberson** [comment]
Okay, cool. I'm trying to get InfluxDB up and running on Alpine Linux. I'm building it locally...

**Comment by smebberson** [comment]
@otoolep, this article seems to explain how to build a static go binary, http://blog.hashbangbash.com/2014/04/linking-golang-statically/. Can that apply to InfluxDB?

**Comment by otoolep** [comment]
You could try it @smebberson :-) None of us have in here however.

**Comment by smebberson** [comment]
@otoolep, yeah, I did try it, but it didn't succeed (the binary was created, but the output from `ldd` was the same). I'm not that familiar with Go (unfortunately) so I didn't bother pushing forward with it. I got it to build on Alpine Linux without too many issues, https://hub.docker.com/r/smebberson/alpine-influxdb/ and that is all I really needed. Thanks for your input along the way.

**Comment by otoolep** [comment]
Great.
