### ISSUE TITLE
Non-negative difference and non-negative derivative aggregate functions

### ISSUE THREAD

**Issue by weiyin** [influxdb/influxdb#2073]
Difference() and Derivative() are great for getting the changes in a variable such as a packet counter. Some variables, however, wrap around or reset to zero (such as after a server reboot).

I would find it very useful to have NonNegativeDifference() and NonNegativeDerivative(), where a negative change is regarded as a zero or NaN change.

**Comment by toddboom** [comment]
@weiyin We've already got an issue open for this - see #1477.
