### ISSUE TITLE
Graphite plugin decodes Unix time to incorrect local time value

### ISSUE THREAD

**Issue by salsa-dev** [influxdb/influxdb#2077]
Hi,
Using master branch and Graphite plugin enabled I get the following:
```
root@grid-monitoring:~# echo "example.foo.bar 3 `date +%s`"|nc localhost 2003

root@grid-monitoring:~# curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=graphite" --data-urlencode "q=SELECT * FROM example.foo.bar"
{
    "results": [
        {
            "series": [
                {
                    "name": "example.foo.bar",
                    "columns": [
                        "time",
                        "example.foo.bar"
                    ],
                    "values": [
                        [
                            "1970-01-17T12:28:44.244Z",
                            3
                        ]
                    ]
                }
            ]
        }
    ]
}
```
The same incorrect time values I get using [collectl](http://collectl.sourceforge.net/) with InfluxDB.

I'm quite new to golang and thus I presume there is just some typo in [graphite.go#L97](https://github.com/influxdb/influxdb/blob/master/graphite/graphite.go#L97) in function parameters to [time.Unix](http://golang.org/pkg/time/#Time.Unix) where seconds are set to zero.
Is it justified to change the line to:
`timestamp := time.Unix(unixTime, 0)`
?

**Comment by otoolep** [comment]
@corylanou

**Comment by sitano** [comment]
heh, i thought it is a feature, not a bug ;)
