### ISSUE TITLE
Support explicit integers in the API

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2082]
Internally our system uses `int` to store numerical values.

https://github.com/influxdb/influxdb/blob/master/database.go#L750

ints are only guaranteed to be no smaller than 32 bits. They are not guaranteed to be larger.

http://golang.org/pkg/builtin/#int

Doesn't this mean we might overflow? For example, the Go memstats are uint64 bits. During the diags work I've had to cast them to ints to store them. It's OK, I presume, on my 64-bit box, but it might be an issue on 32-bit machines, right? Do we have an issue here?

**Comment by otoolep** [comment]
@pauldix @benbjohnson

**Comment by pauldix** [comment]
We should be using int64. The field types should be int64, bool, float64, string, and []byte

**Comment by otoolep** [comment]
I will fix this up after query-engine raw refactoring is complete.

**Comment by otoolep** [comment]
@rw-influxdb and I worked through this today, to ensure there is no issue with receiving values larger than 32-bit on a 32-bit machine. According to the Golang docs, all JSON numbers are unmarshaled to float64, and our serialization to disk (in the FieldCodec) is performed using float64.

This does mean that we don't intrinsically support integers yet, but it does mean data encoding will not change when this is fixed, which means it doesn't block the next release. Integers will simply get a new `influxql` field type. 

To be clear Go JSON unmarshaling always decodes numeric values into float64. Our API needs changes to allow users to specifically request an integer field type, and more generally specify the types of fields -- or we need to try to work it out in the code.

**Comment by otoolep** [comment]
This is now a maybe, since the Go libraries force number to a float64. If we want explicit support int64, the API might need some way to allow users to request that.

**Comment by otoolep** [comment]
Alternatively for every numeric value we need to see if it contains a decimal point. If it does not, we can interpret it as a int64. This may involve a conversion to a string, and back again, which will consume CPU cycles.

**Comment by pauldix** [comment]
We only need to do this the very first time a field is created, no? After that we can assume the number is whatever the field has defined.

The problem people had with only `float64` support was that there are numbers they can't represent that they can in `int64`.

Are you saying that currently nothing is being represented as an int? Only as a float? That makes sense given that all of our aggregators cast to float and nothing fails.

**Comment by otoolep** [comment]
We need to check the type of every number that comes in to see if it conflicts with the existing type for the field, though that might be done using type assertion -- I'd need to check. After the field comes in for the first time, and if we've detected that it's an integer, we can simply perform an int64 type assertion on later fields, and if fails, reject the write.

Right now any numeric value that comes in is being stored as a float64.

**Comment by otoolep** [comment]
Actually, I should be clearer. It is possible a type assertion of a float value to int would work (I need to check) so the user might silently see his float data getting truncated. If we specify the desired behaviour, and we can then code it. An explicit API setting seems awkward, but is the least ambiguous.

**Comment by pauldix** [comment]
Ok, if everything is a float64 now then let's shelve this for after 0.9.0 is out the door. So officially 0.9.0 supports fields that are bool, float64, and string. We'll add support for int64 and []byte later.

**Comment by otoolep** [comment]
Internal encoding support was added here:

https://github.com/influxdb/influxdb/pull/2261/files

It may require some use with `UseNumber` to do this right. 

cc @dgnorton

**Comment by otoolep** [comment]
JSON API will soon be deprecated, and the line protocol already supports integers.
