### ISSUE TITLE
Strange behavior of GROUP BY

### ISSUE THREAD

**Issue by mementor** [influxdb/influxdb#2089]
I am decided to try 0.9 version and faced with strange behavior of GROUP BY.

Just show some logs:

    $ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=SELECT sum(value) FROM cpu GROUP BY time(1m)"

    {
        "results": [
            {
                "series": [
                    {
                        "name": "cpu",
                        "columns": [
                            "time",
                            "sum"
                        ],
                        "values": [
                            [
                                "1970-01-01T00:00:00Z",
                                410
                            ]
                        ]
                    }
                ]
            }
        ]
    }
But:

    curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu"

    {
        "results": [
            {
                "series": [
                    {
                        "name": "cpu",
                        "columns": [
                            "time",
                            "value"
                        ],
                        "values": [
                            [
                                "2015-03-25T23:00:00Z",
                                125
                            ],
                            [
                                "2015-03-25T23:20:00Z",
                                100
                            ],
                            [
                                "2015-03-25T23:30:00Z",
                                100
                            ],
                            [
                                "2015-03-25T23:35:00Z",
                                85
                            ]
                        ]
                    }
                ]
            }
        ]
    }

May be I do something wrong, but cant see exactly what.

Tested on 035500fb9ff1d8a8fb4f20762e14ed672a0c1d6e (version 0.9.0-rc16) and 9b357291e494bff6b384b85e72aab893a28a99ec -- same problem.

**Comment by jnutzmann** [comment]
See #1904... This is the desired behavior.  You need to specify a minimum time in your query for group by to work correctly.

Details updated on the docs here: http://influxdb.com/docs/v0.9/query_language/querying_data.html#group-by

**Comment by mementor** [comment]
I think this is not intuitive enough.

If we try do something like this:

    curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT sum(value) FROM cpu where time > '1970-01-01 00:00:00' group by time(1s)"

and got the answer:

    {"results":[{"error":"too many points in the group by interval. maybe you forgot to specify a where time clause?"}]}

May be better would be make some default value to "time >" if client not pointed this clause?

I mean when I do query without "where time" -- better to get "too many points in the group by interval" error, then one interval where all of data aggregated without respect of "group by time()"

**Comment by pauldix** [comment]
@mementor Think about the query you're asking for and it should make sense. You're asking for `1s` summaries for every second from now to 1970. This would be an obscene amount of data. For what use case would you actually do a query like this?

Almost every query you issue to InfluxDB should have a qualifying time range.
