### ISSUE TITLE
snapshot.go doesnt compile anymore

### ISSUE THREAD

**Issue by jfzw42** [influxdb/influxdb#2106]
hello
just to let you know that I got these errors after pulling the last source:
./snapshot.go:591: cannot use boltTxCloser literal (type *boltTxCloser) as type SnapshotFileWriter in return argument:
        *boltTxCloser does not implement SnapshotFileWriter (missing WriteTo method)
./snapshot.go:612: cannot use boltTxCloser literal (type *boltTxCloser) as type SnapshotFileWriter in return argument:
        *boltTxCloser does not implement SnapshotFileWriter (missing WriteTo method)

**Comment by otoolep** [comment]
BoltDB has recently changed. Execute `go get -f -u .` from within your source tree to update your local copy of BoltDB.

**Comment by jfzw42** [comment]
Hello, sorry for the noobish mistake. Thanks a lot.
