### ISSUE TITLE
Rename timestamp to time for consistency

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#2108]
`time` is shorter. While the query results return `time`, write endpoint expects `timestamp` for points.

**Comment by pauldix** [comment]
Yep, we even talked about this internally yesterday. We'll be changing to `time`, but we may keep `timestamp` in there as an undocumented one. Have to check with a few early partners that this might cause an issue with.

**Comment by otoolep** [comment]
@pauldix -- this is a much simpler code change if we don't have to support `timestamp` because we can just use straightforward Go marshalling. Go doesn't allow a field to have two possible keys in the JSON.

Please check with the partners when you get a chance.

**Comment by imreFitos** [comment]
upvote

**Comment by corylanou** [comment]
@pauldix is it ok to only have `time` and not support both `time` and `timestamp`?  Just checking if we got an answer on it so we can update this ticket.

**Comment by imreACTmd** [comment]
checking in if this will happen

**Comment by otoolep** [comment]
Yes, it's going to happen.

**Comment by imreACTmd** [comment]
cool, waiting for this to drop.
