### ISSUE TITLE
Unable to start influxdb on CentOS 6.5 system running 32bit

### ISSUE THREAD

**Issue by gcaccia** [influxdb/influxdb#2109]
I followed web site instructions for installing influxdb.  Target system is running CentOS 6.4 32bit.

wget https://s3.amazonaws.com/influxdb/influxdb-latest-1.i686.rpm
sudo rpm -ivh influxdb-latest-1.i686.rpm

After this, I ran sudo /etc/init.d/influxdb start

This indicates OK.

After this, I ran sudo /etc/init.d/influxdb status

This indicates FAILED

Log file is empty.

**Comment by otoolep** [comment]
Once this is merged:

https://github.com/influxdb/influxdb/pull/2114

can you re-test? I am pretty sure this will address the start-up issue on Centos. Please re-open if it does not.

**Comment by gcaccia** [comment]
I wasn't sure how to get the merged build.  The latest on your site for download is only for 64bit and I'm on a 32bit system. I tried modifying my init.sh script with the single line change but it still fails to start.  I removed the last part of the line for directing output to STDOUT and the error I see is: 

nohup: failed to run command '/usr/bin/influxdb' : no such file or directory. 

If I do a directory listing at /usr/bin/, I see this... 

lrwxrwxrwx 1 root root 30 Mar 29 16:24 influxdb -> /opt/influxdb/current/influxdb

**Comment by gcaccia** [comment]
How do I reopen this?

**Comment by otoolep** [comment]
Latest does not point to the 0.9 release, it only points to the 0.8 release. Check http://influxdb.com/download/ to get the latest 64-bit 0.9 release. As of this time, we are not building 32-bit releases, so you must build 32-bit yourself.

**Comment by gcaccia** [comment]
looks good.  fix verified.  thanks!
