### ISSUE TITLE
Switch away from code.google.com/p/go-uuid

### ISSUE THREAD

**Issue by mattrobenolt** [influxdb/influxdb#2110]
I'm not sure what the best resolution for this is, but since this is going away, as noted in (https://github.com/influxdb/influxdb/pull/1351), I've noticed cloning this repo becoming more and more unstable. And eventually, it's going to go away entirely.

Not sure what the best resolution for this is, but the repo can be mirrored into the influxdb org, then referenced from there. Meaning, import changes to `github.com/influxdb/go-uuid/uuid` or we can reference an existing clone from one of the random people on the internet who have already done so.

I'd argue that the project should be mirrored into this org to prevent any accidental API changes from using an unofficial/untrusted mirror though.

For reference, when trying to submit https://github.com/Homebrew/homebrew/pull/38163, the build errored trying to clone `go-uuid`:
http://bot.brew.sh/job/Homebrew%20Pull%20Requests/23465/version=yosemite/testReport/junit/brew-test-bot/yosemite/fetch___devel_influxdb/

I've also seen this happen a number of times on my own projects.

**Comment by otoolep** [comment]
@corylanou -- I think you introduced this dependency. Thoughts?

**Comment by corylanou** [comment]
We probably need to find an alternative, or find out where this library is going to be officially hosted going forward.  Most of the code from google has been migrated somewhere else (github for example) for a lot of this.  I'll check out there and if it exists, just point to the new reference.

**Comment by mattrobenolt** [comment]
fwiw, this is only used in literally 1 place, and it's used to generate a uuid for a `Request-Id` header which gets used for logging.

This can ditch the uuid1 and just use a random string, or it's trivial enough that it can just be vendored from something like: https://github.com/gocql/gocql/blob/master/uuid.go#L115-L144

If it were used for more critical components, I'd probably have a different opinion. :)

**Comment by corylanou** [comment]
@mattrobenolt I think that's a great solution.  Are you interested in doing a PR on it?  If not, we'll add this to our queue.

Thanks!

**Comment by mattrobenolt** [comment]
@corylanou I proposed two options, which do you prefer? I can do a PR for either.

Vendorizing a uuid1 function, or just using a random string?

**Comment by corylanou** [comment]
My recommendation would be to not even vendorize, just simply create a package called `uuid` in our system that creates the only needed UUID.

http://play.golang.org/p/BRXO11IU5H

And then reference the appropriate license for where we got it.

Thoughts?

**Comment by mattrobenolt** [comment]
Yep, works for me. PR coming up.
