### ISSUE TITLE
HTTP API should support secure (HTTPS) access

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2115]
All user-accessible endpoints must support HTTPS.

**Comment by jwilder** [comment]
Would we also want to support HTTPS for internal cluster endpoints (`/raft`/ `/messages`, etc..)?

**Comment by otoolep** [comment]
I believe so.

**Comment by dtriphaus** [comment]
Is it actually possible to get SSL to work with 0.9? Trying to get SSL working with rc20 but without success. Not even an error in the logs, it seems to just ignore SSL settings in config (ssl-port / ssl-cert).

**Comment by otoolep** [comment]
@dtriphaus -- not it's not support quite yet.

**Comment by dtriphaus** [comment]
Thanks for the quick reply!

**Comment by toddboom** [comment]
This is done in v0.9.2.
