### ISSUE TITLE
Querying continuous query with time condition

### ISSUE THREAD

**Issue by ebereketoglu** [influxdb/influxdb#2119]
I'm trying to querying some data from a continuous query with time condition. When I run the following query it gives "Field time doesn't exist in series test". Is this the expected behaviour?

select value from test where time>"2015-03-26 18:03:247.010"

**Comment by ebereketoglu** [comment]
The continuous query is
select mean(value) as value,time from "M00010000167A0C58.channelA" group by time(1h) into test

**Comment by otoolep** [comment]
You must wrap the time string in single-quotes, as explained here:

http://influxdb.com/docs/v0.9/query_language/querying_data.html#date-time-strings

Philip
