### ISSUE TITLE
v0.9.0-rc17 continuous queries does not work

### ISSUE THREAD

**Issue by ebereketoglu** [influxdb/influxdb#2129]
Hi,

I created two continuous queries . When I show continuous queries they are listed. But when I try to query "select * from test" or "select * from test10"  I get the "measurement not found error". What can cause this problem?

CREATE CONTINUOUS QUERY test ON mote_db 
BEGIN 
SELECT mean(value), time INTO "default" FROM M00010000167A0C58_channelA GROUP BY time(1m) 
END;

CREATE CONTINUOUS QUERY test10 ON mote_db
BEGIN 
SELECT mean(value) AS value, time INTO rp30d FROM M00010000167A0C58_channelA GROUP BY time(1m) 
END 

Thanks,
Erdinc

**Comment by manusvs650** [comment]
+1

**Comment by ebereketoglu** [comment]
https://github.com/influxdb/influxdb/issues/2162
