### ISSUE TITLE
rc17 retention policy deletion kicks in too early

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#2133]
I have a retention policy of 7d:
```
      name  duration  replicaN default
0  default         0         1    True
1    short  168h0m0s         1   False
```

A few minutes after I push data to "short".amiigodev I see this in the logs:
```
[srvr] 2015/03/31 23:38:30 retention policy enforcement check commencing
[srvr] 2015/03/31 23:38:30 shard group 41, retention policy short, database amiigodev due for deletion
[srvr] 2015/03/31 23:48:31 retention policy enforcement check commencing
```

And if I query the data it is in fact gone.
I had a single point in the db that was in the future 2015-04-01, that point did not show up in any query (that I wanted to file an issue for it), and now only that point is returned

**Comment by otoolep** [comment]
Can you please show us a sequence of curl commands that bring this out -- create a database, create an retention period, write the data in, query it to show that is there, wait until retention kicks in, and then query again. You can shorten the retention enforcement period by changing your config file. It defaults to 10 minutes, but you could make it 30 seconds.

**Comment by dashesy** [comment]
@otoolep I think I found what happens. The date of the data I push is old (2014), when retention period enforcement kicks in it removes them all! 
I was under the impression that the records get deleted not based on their timestamp but by when they are recorded, this makes the application of retention period limited to when system has up-to-date records and cannot be used with any historical data. IOW it will depend heavily on clock time.
I use the "short" retention policy for a temporary space to keep some information computed for some time, It would be teremendously helpful if this behavior could be selected (to delete records based on how long they have been in database and not their actual timestamp).

**Comment by otoolep** [comment]
This is what I suspected was happening. Retention policy enforcement is based on event time, not reception (recording) time. This means if you stream data into the past, it may be deleted very quickly if you do not have retention policy covering the timeframe in question.

Right now this is how it works, so I am closing the issue, but I understand your request. You might like to open a ticket, describing exactly what you want.
