### ISSUE TITLE
stable version  of v0.9.0

### ISSUE THREAD

**Issue by ebereketoglu** [influxdb/influxdb#2139]
Hi,

When do you plan to release the stable version of v0.9?

Thanks,
Erdinc

**Comment by dashesy** [comment]
+1 to know. rc17 runs with no crash (second day), to me it is stable enough, rest is feature addition and performance enhancements perhaps. Kudos for a really nice piece of software.

**Comment by yujinqiu** [comment]
+1.  I'm planing to migrate from OpenTsdb, let me know if you are ready to release, so I can make a plan in advance. Current features are enough for me,   stability and performance  really matter to me. Thanks all  for your  work.

**Comment by pauldix** [comment]
The current version is still alpha software. We will be making a breaking underlying data change in the next week. However, we're getting closer. See this post I put up today about our path to 0.9.0: http://influxdb.com/blog/2015/04/01/InfluxDB-v0_9_0-release-plan.html
