### ISSUE TITLE
Continuous queries cannot be dropped

### ISSUE THREAD

**Issue by btashton** [influxdb/influxdb#2141]
RC18 looks like it should have this functionality, but when I run a simple test on dropping a continuous query I get a 500 back.  I have a full shell example here:
https://gist.github.com/btashton/0ed2712c8738770238f5

**Comment by toddboom** [comment]
@btashton I'll take a look at this in the morning. I implemented this, so my handiwork is probably at fault.

**Comment by neonstalwart** [comment]
i see that there is some code missing at https://github.com/influxdb/influxdb/blob/03d5ffc0bb428c5fe446b4f33fd8767fcd2ba6d7/server.go#L2206

@toddboom is it just a matter of adding 

```go
res = s.executeCreateContinuousQueryStatement(stmt, user)
```
