### ISSUE TITLE
InfluxDB storage design

### ISSUE THREAD

**Issue by ebereketoglu** [influxdb/influxdb#2148]
I want to learn how InfluxDB stores data. What is the size of a timestamp in database? Does it store timestamp for each datapoint?

Thanks,
Erdinc

**Comment by toddboom** [comment]
@ebereketoglu opening up an issue isn't really appropriate for this, since it's not a feature request or bug report - i'd recommend asking this on the mailing list or waiting until the v0.9.0 release is finalized so that we can provide more documentation about this.
