### ISSUE TITLE
Influxd process with stats enabled crashing with 'Unsuported protocol scheme for ""'

### ISSUE THREAD

**Issue by wfro** [influxdb/influxdb#2152]
cc: @otoolep 

I ran into this on master (HEAD at 734e57a) running `influxd` with [this config file](https://gist.github.com/wfro/1bb361248c10c4fe1fff) (The only change was setting stats `enabled = true`).

To repoduce:

* create a new config file and set `enabled = true` under `[statistics]`
* start influxd with `$ influxd -config /path/to/config.toml`

The process exited completely (running Ubuntu 14.10):

![f5943a0c-d929-11e4-9350-b47b8fb33004](https://cloud.githubusercontent.com/assets/6454987/6983164/82f1471e-d9cf-11e4-8d38-72327f04fc73.png)

Let me know if you need more detail.

**Comment by corylanou** [comment]
@otoolep This may be fixed with a commit we are soon to merge: https://github.com/influxdb/influxdb/commit/c694d3da889875f20790679a69ffe53708084fa3

**Comment by otoolep** [comment]
Got it @corylanou -- thanks.
