### ISSUE TITLE
Database wasted after reboot, default /tmp for data is a joke

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2161]
Seriously, what is a reason to use <code>/tmp</code> as default data directory even if 0.9.0-rc18 currently still alpha software? Installed from .deb

**Comment by toddboom** [comment]
@wildchild definitely agree with you. we'll get that fixed in the packages.

**Comment by wildchild** [comment]
Also clustering <code>dir = "/tmp/influxdb/development/state"</code>.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/2163
