### ISSUE TITLE
Unable to create continuous query on 0.9.0-rc18

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2162]
Is there any working dummy example of how to create continuous query from web admin or even maybe a success story from anyone. <code>SELECT sum(val) from ... GROUP BY ... INTO ... </code> results in query error because it think that 'INTO' is wrong keyword.

There are no tests in tests directory where I can figure out how to use particular features. This database scheduled for production ready release in this month and core features are seems completely broken, please point me to tests. maybe I am searching in wrong place.

**Comment by toddboom** [comment]
@wildchild this is already an open issue - #2129 

we actually disabled continuous queries temporarily to finish some clustering rewrites - these will be re-enabled in one of the upcoming release candidates.

**Comment by wildchild** [comment]
Re-enabled as of #2200 but still does not work for me.

**Comment by wildchild** [comment]
Got it working by <code>CREATE CONTINUOUS QUERY...</code>. Docs are outdated, no examples how to create CQ and how to use it.

**Comment by beckettsean** [comment]
Appreciate you digging in, wildchild. We know the docs aren't ready for prime time yet, thanks for pointing out another gap.
