### ISSUE TITLE
Add integration test that shows error on non-scoped group by time queries

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2171]
A query like this:

```
select mean(value) from foo group by time(10s)
```

Should return an error response. The code should be 200, but the response json object for that statement should have an error that the query must scope the time because the group by interval would have it returning a data point for every 10s interval from 1970 to now.

**Comment by beckettsean** [comment]
related to #2702

**Comment by beckettsean** [comment]
Already done:

```
> select mean(value) from slashy group by time(10s)
ERR: error parsing query: aggregate functions with GROUP BY time require a WHERE time clause
```
