### ISSUE TITLE
High CPU usage when broker leader fails over

### ISSUE THREAD

**Issue by jwilder** [influxdb/influxdb#2173]
When the broker leader fails over to another node, the data nodes get stuck in some kind of redirect loop here: https://github.com/influxdb/influxdb/blob/master/messaging/client.go#L334

This is causing very high CPU usage.  The only way I've been able to mitigate it is by forcing the brokers to failover again so that the original leader is the leader again and restarting the data nodes.

**Comment by otoolep** [comment]
No longer applicable in new design.
