### ISSUE TITLE
Crash after query SHOW DIAGNOSTICS on 0.9.0-RC20

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#2179]
Submitted via the mailing list:

Today I install Influxdb 0.9.0-RC20 on Debian 7.6-amd64 from package http://s3.amazonaws.com/influxdb/influxdb_0.9.0-rc20_amd64.deb
I try to query "SHOW DIAGNOSTICS" but suddenly, influxdb stop running. 

Here the log I get, https://gist.github.com/rizalmhn/4c2f5f6503ec779d6657 

FYI, I tried "SHOW DIAGNOSTICS" query on 0.9.0-RC18 before and it worked well. 

Regards,
--Rizal

**Comment by manusvs650** [comment]
Same issue with Ubuntu 14.04

```
panic: unsupported statement type: *influxql.ShowDiagnosticsStatement
```

**Comment by otoolep** [comment]
Fixed by PR 2181.

**Comment by toddboom** [comment]
This will be out in the next RC.
