### ISSUE TITLE
Crash on time > now() - 15m AND time < now() - 5m

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2184]
Added "AND..." to my query and influxdb completely crashed.

**Comment by pauldix** [comment]
Any chance you have the log output? Even better, would you be able to add a failing test here:  https://github.com/influxdb/influxdb/blob/master/cmd/influxd/server_integration_test.go#L396 in a PR?

**Comment by wildchild** [comment]
Log https://gist.github.com/wildchild/2031bfe961763753935a

Query: select sum(xxx) / 600 from yyy where time > now() - 1h and time < now() - 5m group by time(10m) fill(none)

**Comment by wildchild** [comment]
Same crash with <code>panic: runtime error: invalid memory address or nil pointer dereference</code> for query <code>select sum(zzz) from hhh where xxx = 'Z' and time > now() - 30m</code>.

**Comment by toddboom** [comment]
This should be fixed by PR #2288.
