### ISSUE TITLE
Wire up queries that must hit multiple shards in a shard group

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2188]
For example you would have this if you have an RF of 1 with a cluster of 3 nodes and you have 3 different series you're querying from. It should be easy to create a test like this: https://github.com/influxdb/influxdb/blob/distributed-queries/cmd/influxd/server_integration_test.go#L1334-L1349

Just change it so that it's RF1. Then you may need to add an integration test that writes to a measurement with three different tags. Then queries that.

The spot to wire that up is here: https://github.com/influxdb/influxdb/blob/distributed-queries/tx.go#L145-L178

**Comment by jwilder** [comment]
Fixed by #2353
