### ISSUE TITLE
Implement max chunk size for map responses

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2189]
When a remote mapper runs, it sends the results down as a response. Those should be limited in size by splitting up the results.

See here for where it gets marshaled and sent: https://github.com/influxdb/influxdb/blob/distributed-queries/httpd/handler.go#L735-L774

See here for where it gets unmarshaled: https://github.com/influxdb/influxdb/blob/distributed-queries/remote_mapper.go#L98-L115

**Comment by otoolep** [comment]
Part of the work for https://github.com/influxdb/influxdb/issues/3009

**Comment by beckettsean** [comment]
@otoolep @pauldix is this done?

**Comment by otoolep** [comment]
I am not sure what the status of this is, since the DQ refactor. Let me check.

**Comment by otoolep** [comment]
This is no longer applicable.
