### ISSUE TITLE
need update devel version in homebrew 

### ISSUE THREAD

**Issue by s7v7nislands** [influxdb/influxdb#2192]
need update devel version in homebrew, and may some error in formal file:

multi-versions:
 version "0.9.0-rc19"

but in build:
 system "go", "build", "-ldflags", "-X main.version 0.9.0-rc16 -X main.commit 035500fb9ff1d8a8fb4f20762e14ed672a0c1d6e", "./..."

**Comment by s7v7nislands** [comment]
brew install --devel influxdb
==> Downloading https://github.com/influxdb/influxdb/archive/v0.9.0-rc19.tar.gz
Already downloaded: /Library/Caches/Homebrew/influxdb-0.9.0-rc19.tar.gz
==> Cloning https://github.com/bmizerany/pat.git
Updating /Library/Caches/Homebrew/influxdb--github.com-bmizerany-pat--git
==> Checking out revision b8a35001b773c267eb260a691f4e5499a3531600
==> Cloning https://github.com/boltdb/bolt.git
Updating /Library/Caches/Homebrew/influxdb--github.com-boltdb-bolt--git
==> Checking out revision 8b138fd106636b40b4b6d43786e668ce658aa3d7
==> Cloning https://github.com/BurntSushi/toml.git
Updating /Library/Caches/Homebrew/influxdb--github.com-BurntSushi-toml--git
==> Checking out revision 443a628bc233f634a75bcbdd71fe5350789f1afa
==> Cloning https://github.com/kimor79/gollectd.git
Updating /Library/Caches/Homebrew/influxdb--github.com-kimor79-gollectd--git
==> Checking out revision 1d0fc88b7c2bf0ba79021ddca2b5f5fd9cc3a5a3
==> Cloning https://github.com/peterh/liner.git
Updating /Library/Caches/Homebrew/influxdb--github.com-peterh-liner--git
==> Checking out revision fc147570057cd703778924569c41923b28611ca2
==> Cloning https://github.com/rakyll/statik.git
Updating /Library/Caches/Homebrew/influxdb--github.com-rakyll-statik--git
==> Checking out revision 4a16c831de16fd27a38fab90ade0cf35844a31db
==> Cloning https://go.googlesource.com/crypto.git
Updating /Library/Caches/Homebrew/influxdb--golang.org-x-crypto--git
==> Checking out revision 1351f936d976c60a0a48d728281922cf63eafb8d
==> go build -ldflags -X main.version 0.9.0-rc16 -X main.commit 035500fb9ff1d8a8
==> go install ./...
==> Caveats
To have launchd start influxdb at login:
    ln -sfv /usr/local/opt/influxdb/*.plist ~/Library/LaunchAgents
Then to load influxdb now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.influxdb.plist
Or, if you don't want/need launchctl, you can just run:
    influxd -config /usr/local/etc/influxdb.conf
==> Summary
🍺  /usr/local/Cellar/influxdb/0.9.0-rc19: 4 files, 20M, built in 14 seconds

**Comment by toddboom** [comment]
This will be resolved by this PR:
https://github.com/Homebrew/homebrew/pull/38474

**Comment by MBaron007** [comment]
Can homebrew please be updated to reflect the existence of v0.9.0-rc27 as of 4/23/2015? Thanks!

**Comment by gunnaraasen** [comment]
I just submitted a PR to bump the homebrew `--devel` release to rc27.  It will probably be accepted sometime tomorrow.

With the frequency of releases, we don't want to inundate homebrew with an update on every new release.  Going forward, we'll update it once a week with the latest RC.

**Comment by toddboom** [comment]
The PR is here:
https://github.com/Homebrew/homebrew/pull/38989
