### ISSUE TITLE
show users privileges for specific databases

### ISSUE THREAD

**Issue by n1tr0g** [influxdb/influxdb#2212]
Since v0.9.0.RC* users are globally defined, so it means we will need a way how to expose the user privileges on a database level. The current show users command only lists the users, without the database rights. 

Honestly not sure what would be the best syntax. Maybe SHOW GRANTS FOR user ? There is a similar command in the SQL world (https://dev.mysql.com/doc/refman/5.0/en/show-grants.html).

**Comment by n1tr0g** [comment]
based on the feedback I will go ahead an implement the SHOW GRANTS FOR user syntax :)

**Comment by jtblin** [comment]
This one can be closed no?

**Comment by beckettsean** [comment]
yes, good catch, @jtblin!

**Comment by rca** [comment]
Is there a way to list all the users with privileges on a single database?

The command `SHOW PRIVILEGES FOR user` allows me to see what databases a user can access; I'd like to see what users have been given access to a database, for instance `SHOW PRIVILEGES ON db`.

**Comment by krishnakanthpps** [comment]
+1
