### ISSUE TITLE
node doesn't initialize if raft directory exists but is empty

### ISSUE THREAD

**Issue by imreACTmd** [influxdb/influxdb#2226]
I manually created the raft directory before starting influxd, and the node did not finish the leader selection. This is on on rc18, rc19 and rc20 

I have set the directory and permissions the same as the auto-created raft directory was set to.

This is the last message about the raft selection process:

srvr] 2015/04/09 20:22:21 broker opened at /opt/influxdb/raft
[raft] 62281cb498a0:8086 2015/04/09 20:22:21 log pending: waiting for initialization or join

**Comment by otoolep** [comment]
No longer applicable in new design.
