### ISSUE TITLE
Debian package to add log rotate

### ISSUE THREAD

**Issue by dashesy** [influxdb/influxdb#2248]
The log files could grow, a setting like this can be added to `/etc/logrotate.d/influxdb` to back them up:

```
/var/log/influxdb.log {
        weekly
        size 100M
        rotate 7
        compress
        delaycompress
        missingok
        notifempty
        create 644 influxdb influxdb
}
```

**Comment by otoolep** [comment]
I am reluctant to modify people's installed software without their explicit permission. I feel documentation is the best approach for stuff like this.

http://influxdb.com/docs/v0.9/concepts/logs.html#using-logrotate

**Comment by dashesy** [comment]
@otoolep this will add a config file, if someone decided not to use logrotate it will not be used. It is similar to the install package adding a unit to `init.d`. Alternatively something like `logging_collector` option of postgres can be used, but that requires implementation.

**Comment by otoolep** [comment]
I understand it's a config file, but it they are already using logrotate it means the installation process is changing the configuration of software the user installed, and may not want InfluxDB to touch, regardless of our good intentions.

I do see the potential value in something like this, I just don't think we should assume we can write configuration files for other pieces of software. We would need to check with the user. Make sense?

**Comment by otoolep** [comment]
Adding something to `init.d` is different -- it's a core part of installing any software on a Linux distro. But modifying some other application's `init.d` file, one shouldn't do that.

In any event, a sys-admin may have logrotate installed by Puppet, Chef etc. Modifying the file may only mean it's almost immediately corrected by the drift-detection that comes with those tools.

**Comment by dashesy** [comment]
makes sense, yes

**Comment by sammy007** [comment]
Nginx, haprixy, and other good software does and no one hurted so far.

**Comment by beckettsean** [comment]
dupe of #1943 which also has copytruncate, a necessary part of logrotate for influxd as it operates right now (it can't currently tolerate losing the filehandle to the open log)
