### ISSUE TITLE
Please review continuous queries

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2253]
There are just 2 tests for CQ: create and show https://github.com/influxdb/influxdb/blob/master/cmd/influxd/server_integration_test.go#L1260

A lot of pending issues for such core feature indicates that CQ is far from being usable. Please cover at least querying and deletion. I can't get <code>select</code> from measurement created by CQ working, so I can't write it myself. Docs are outdated, creation how it's described in docs does not work at all.

**Comment by beckettsean** [comment]
@wildchild CQs were unhooked for a significant part of 0.9.0 development. They have only recently been re-enabled and there is a lot of known work to cover before they are back to parity or better than 0.8.8, documentation included.

**Comment by MBaron007** [comment]
Just wanted to +1 this, as I'm unsuccessfully trying to apply "old style" continuous queries from .8.8 to my .9 DB and I'm not sure what the correct syntax is here.  Thanks!

**Comment by marcosnils** [comment]
@MBaron007 CQ's are unusable at this moment in 0.9. However if you want to check the syntax to create them you should use the Influxql(https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md) as a reference

**Comment by MBaron007** [comment]
@marcosnils Great, thanks!  Just to clarify: even if I construct and submit a continuous query to my 0.9 DB, you'er saying I currently shouldn't expect that to work, correct?  Thanks again.

**Comment by marcosnils** [comment]
Exactly. They most likely don't work

**Comment by MBaron007** [comment]
Alright gotcha, appreciate the clarification!

**Comment by beckettsean** [comment]
This is almost certainly fixed by #2552, which is included in RC30.
