### ISSUE TITLE
Passing timestamp as int does not work

### ISSUE THREAD

**Issue by NikolaBorisov** [influxdb/influxdb#2259]
According to the documentation of 0.9 you are allowed to insert data using integer timestamp like this:

```
"timestamp": 1428891461,
"precision": "s",
```

When I tried to use this I got this error
```
{"error":"parsing time \"1428891461\" as \"\"2006-01-02T15:04:05Z07:00\"\": cannot parse \"1428891461\" as \"\"\""}
```
I also tried using nano second precision and it didn't work.

**Comment by otoolep** [comment]
Could please show an entire `curl` request showing this problem?

@corylanou

**Comment by NikolaBorisov** [comment]
I'm using python script using time.time(). Exactly the same script works now.

**Comment by beckettsean** [comment]
can you share the relevant portion of the python script?
