### ISSUE TITLE
Looping log error on graphite

### ISSUE THREAD

**Issue by makapuf** [influxdb/influxdb#2262]
Hello, I'm running a test influxdb v0.8.8 have a very high CPU usage (around 600%) big log.txt (2G) with millions of times the same line : 

    [2015/04/13 11:16:43 CEST] [EROR] (github.com/influxdb/influxdb/api/graphite.(*Server).Serve:123) GraphiteServer: Accept: %!(EXTRA *errors.errorString=use of closed network connection)

my graphite config is the following :

    # Configure the graphite api
    [input_plugins.graphite]
    enabled = true
    # address = "0.0.0.0" # If not set, is actually set to bind-address.
    port = 2003
    database = "testdb"  # store graphite data in this database
    # udp_enabled = true # enable udp interface on the same port as the tcp interface

**Comment by beckettsean** [comment]
Since you are testing, we would advise you to wait for 0.9.0 release or start playing with the release candidates. 0.8.8 will be deprecated soon.

**Comment by seregasheypak** [comment]
Hi, met the same. What could be the solution? No services can report metrics though input_plugins.graphite
