### ISSUE TITLE
influxd panics when using sample config

### ISSUE THREAD

**Issue by wfro** [influxdb/influxdb#2264]
Occurred on master (261ff11), when running:

```
influxd -config etc/config.sample.toml
```

Stack trace:

![screen shot 2015-04-13 at 8 38 19 am](https://cloud.githubusercontent.com/assets/6454987/7119258/4c9e28f2-e1b9-11e4-9f50-3f16371e058c.png)

**Comment by otoolep** [comment]
I can't repro this. Are you sure your config file is unmodified?

**Comment by jwilder** [comment]
I wasn't able to reproduce either.  The logs saying `broker already member of cluster` means there was some existing data on disk.

**Comment by wfro** [comment]
I just tried to reproduce it locally and had no luck (OS X 10.10).  I ran into the issue on a droplet running Ubuntu 14.10 so I'm willing to chalk it up to some existing state on that machine.

**Comment by otoolep** [comment]
You wanna close?

**Comment by wfro** [comment]
Closing, thanks for taking a look.
