### ISSUE TITLE
inconsistent results for aggregate queries

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#2271]
```sh
yesterday=$(date -v -1d '+%FT%T.000Z')

echo "creating database"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"

echo "inserting data"
curl -d "{\"database\" : \"foo\", \"points\": [{\"name\": \"cpu\", \"tags\": {\"region\":\"uswest\",\"host\": \"server01\"},\"timestamp\": \"$yesterday\",\"fields\": {\"value\": 100}}]}" -H "Content-Type: application/json" -ipv4 http://localhost:8086/write

sleep 1

echo "querying data"
curl -G -ipv4 http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=select count(value) from cpu where time > now() - 2d group by time(6h)" --data-urlencode "pretty=true"
```

for some reason, the counts switch over to be `null` when i would have expected them to be `0` to be consistent with the earlier counts.

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "count"
                    ],
                    "values": [
                        [
                            "2015-04-11T18:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T00:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T06:00:00Z",
                            0
                        ],
                        [
                            "2015-04-12T12:00:00Z",
                            1
                        ],
                        [
                            "2015-04-12T18:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T00:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T06:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T12:00:00Z",
                            null
                        ],
                        [
                            "2015-04-13T18:00:00Z",
                            null
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by otoolep** [comment]
Please take a look at the "fill" documentation at the link below.

Thanks,

Philip

http://influxdb.com/docs/v0.9/query_language/querying_data.html#filling-intervals-with-no-data

**Comment by otoolep** [comment]
Just to be clear, the system is behaving as designed.

**Comment by neonstalwart** [comment]
it doesn't seem to be behaving the way the document suggests:

> By default, GROUP BY intervals that have no data will use null as the value

in this case, the default value for the early intervals is `0` and the default interval for the later intervals is `null`.  is that really the way it's supposed to work?

**Comment by otoolep** [comment]
OK, we'll look into it -- thanks @neonstalwart

**Comment by neonstalwart** [comment]
also, if i change the query to use `fill(null)`

```sh
curl -G -ipv4 http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode "q=select count(value) from cpu where time > now() - 2d group by time(6h) fill(null)" --data-urlencode "pretty=true"
```

i get the exact same results - early values are `0`, later values are `null`

however, if i use `fill(0)` i get all `0` values.

**Comment by neonstalwart** [comment]
i wonder if [`MapCount`](https://github.com/influxdb/influxdb/blob/03d5ffc0bb428c5fe446b4f33fd8767fcd2ba6d7/influxql/functions.go#L167-L173) needs to return `nil` when the count is 0 (like how [`MapSum`](https://github.com/influxdb/influxdb/blob/03d5ffc0bb428c5fe446b4f33fd8767fcd2ba6d7/influxql/functions.go#L176-L187) does)

**Comment by otoolep** [comment]
You might be right @neonstalwart -- I can check in the near future. PRs welcome. :-)

**Comment by neonstalwart** [comment]
@otoolep i would love to do a PR for this but i'm new to go so i may need some hand holding - you may be better doing it yourself :wink: 

let's see what i can come up with but don't wait on me if you're ready to do it.

**Comment by neonstalwart** [comment]
first question... where should i put a test for this?  i don't think i can find any unit tests for the map-reduce functions - i.e no influxql/functions_test.go
