### ISSUE TITLE
/run/influxdb not persistent

### ISSUE THREAD

**Issue by agreentree** [influxdb/influxdb#2273]
When rebooting an hLINUX system, the /run/influxdb does not get created at boot time (/run is a tmpfs filesystem). This causes influxdb to fail since it cannot create this folder as influxdb user, must be root; would suggest the /etc/init.d/influxdb script change to create this folder if it doesn't exist at boot time

**Comment by beckettsean** [comment]
Open question, is there a strong reason to write to the /run/influxdb directory vs anywhere else on the FS?

**Comment by tkuhlman** [comment]
A couple of clarifications, this is a Debian Jessie system and the package is really writing to /var/run it just so happens that is a link to /run. The reasoning behind Debian's setup is outlined at https://wiki.debian.org/ReleaseGoals/RunDirectory

/var/run is really the standard place for pid files so it makes sense as the location, it is also commonly tmpfs so doesn't stay around after a reboot so the making of /var/run/influxdb needs to be done in the init script not in the package install.

**Comment by beckettsean** [comment]
thanks for the clarifications, @tkuhlman. We'll discuss and try to have a well-reasoned package for the final 0.9.0. Most likely not a priority until we're much closer to release, though, so the RCs may require workarounds for a while, still.

**Comment by neonstalwart** [comment]
@tkuhlman see #2297 - i didn't know this issue was open.  i believe my PR would fix this.

**Comment by tkuhlman** [comment]
Yes I think your pull request will take care of it. Thanks.

**Comment by otoolep** [comment]
Will be fixed in RC26.
