### ISSUE TITLE
OpenTSDB input does not create "value" column in 0.9rc24

### ISSUE THREAD

**Issue by hmlth** [influxdb/influxdb#2280]
I use the OpenTSDB input to try to push from riemann, it works well but the value field has the same name as the series. I tried to use Grafana 2, and it expects a value field, so I have to manually edit queries for each series. This also make queries across multiple series more difficult (I'm still not sure it's even possible):

~~~
 curl -s -G 'http://localhost:8086/query' --data-urlencode "db=opentsdb_database" --data-urlencode "q=SELECT * FROM RIEMANN_load1 LIMIT 1" --data-urlencode "pretty=true" |less
{
    "results": [
        {
            "series": [
                {
                    "name": "RIEMANN_load1",
                    "columns": [
                        "time",
                        "RIEMANN_load1"
                    ],
                    "values": [
                        [
                            "2015-04-14T14:10:37Z",
                            1.59
                        ]
                    ]
                }
            ]
        }
    ]
}

~~~

I would expect the colum `RIEMANN_load1` to be named  `value` in all series.

**Comment by hmlth** [comment]
A request created by grafana2 by default:
~~~
SELECT mean(value) FROM "RIEMANN_load1" WHERE $timeFilter GROUP BY time($interval) ORDER BY asc
~~~

**Comment by tcolgate** [comment]
Yes, I noticed this yesterday. I think I need to explicitly name the field
Value. But couldn't see the other inputs doing it

Will update ASAP

**Comment by otoolep** [comment]
The name of the column is at the input module's discretion, but I agree, this doesn't look right. 

@tcolgate -- if you can make a change, I will review -- thanks.

**Comment by tcolgate** [comment]
@otoolep should be good to go
