### ISSUE TITLE
Unable to create database with name including dashes

### ISSUE THREAD

**Issue by zidekmat** [influxdb/influxdb#2284]
I'm unable to create database with name fe3f3e39-c7c. Its only possible if I put the name in the double quotes, but that makes database with name "fe3f3e39-c7c" which is not the thing I want.
[Documentation](http://influxdb.com/docs/v0.9/query_language/database_administration.html#creating-a-database) states that dashes are possible.

Query: curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE fe3f3e39-c7c"
Response: {"error":"error parsing query: found -, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER at line 1, char 25"}

Fails for single quotes as well:
Query: curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE 'fe3f3e39-c7c'"
Response: {"error":"error parsing query: found fe3f3e39-c7c, expected identifier at line 1, char 16"}

InfluxDB 0.9 rc24

**Comment by otoolep** [comment]
Thanks -- the documentation is actually incorrect. Dashes are not permitted
-- I'll fix up the docs.

Philip

**Comment by otoolep** [comment]
The docs have been updated.

http://influxdb.com/docs/v0.9/query_language/database_administration.html#creating-a-database
