### ISSUE TITLE
support multiple datadirs

### ISSUE THREAD

**Issue by Dieterbe** [influxdb/influxdb#229]
would be nice to support multiple datadirs, as to support servers with individual disks and/or volumes mounted in separate directories.

the algorithm that maps shards to datadirs should probably also take a weight per datadir into account. for now we could just keep those weights 1 and not expose weights through the config, but by having them implicitly set to 1 for now and including them in the hashing algorithm, if they get added later at least the algorithm will hash the same way and not cause any disruption.

also worth thinking about is server weights.

how about assigning shards to `server::datadir` directly? there's no need to hash (db, timeseries) to a server, and then hash again to go from server to a datadir.

the algorithm could probably take server as well as datadir weights into account relatively easy.

**Comment by beckettsean** [comment]
Not sure this has a place on the roadmap right now.
