### ISSUE TITLE
message stream error: file: seek to index: unexpected EOF

### ISSUE THREAD

**Issue by agreentree** [influxdb/influxdb#2296]
During extreme load testing in a 3-node cluster test environment, posting to 1 million unique metrics every 20 seconds for 12 hours,  I get the following error in the log file non-stop, and influxdb dies soon after restarting it:

unexpected eof(1): len=892546082, n=11216677, err=unexpected EOF
[srvr] 2015/04/15 18:36:33 message stream error: file: seek to index: unexpected EOF

I reproduced this in a Monasca influxdb environment running a 3 bare-metal node cluster.
I haven't tried to reproduce this in a stand-alone influxdb environment yet, wanted to report it to see if anybody recognizes that error message and has any thoughts an what might be causing it - perhaps an index that has grown too large ?

**Comment by toddboom** [comment]
@agreentree we just released rc25 with a bunch of fixes for clustering, one of which may have covered this. could you retest with rc25?

**Comment by agreentree** [comment]
I ran a similar extreme load test overnight with RC25, I did not see the same issue as reported above, but the 2 worker nodes in the 3 node cluster failed with this panic message in the logs:
panic: apply: broker apply: write message: stale write

**Comment by beckettsean** [comment]
We'd love to repro this. How are you running the load tests? Any way we can run this repeatably?

**Comment by agreentree** [comment]
here is how I run these load tests - I run a python script in a continuous loop that posts to a large number of unique metrics, usually overnight. In our largest scale Monasca test environment (3 clustered bare metal nodes), the script posts to 1M unique metrics ~ every 20 seconds. In a smaller scale Monasca test environment (3 clustered VM's), the script posts to 100K unique metrics ~ every 5 seconds. The python test scripts used are available from: https://github.com/hpcloud-mon/monasca-perf, in particular, perf.py is the script I've used for the metric post testing.

**Comment by otoolep** [comment]
No longer applicable in new design.
