### ISSUE TITLE
is there a conf file option to disable [http] logging ?

### ISSUE THREAD

**Issue by agreentree** [influxdb/influxdb#2302]
with 0.9.0, the influxdb log file on a Monasca system keeps filling with the following messages. I can't reproduce this with standalone influxdb because this comes from a Monasca specific component, the mon_persister. I can't find any documentation on how to disable this level of logging ?

[http] 2015/04/15 22:23:31 192.168.10.4 - mon_persister [15/Apr/2015:22:23:31 +0000] POST /write HTTP/1.1 200 23 - Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.7.0_75) 0c05bcfe-e3be-11e4-80c1-000000000000 9.473551ms

**Comment by beckettsean** [comment]
@agreentree I know there is some aggressive logging in place right now for a Monasca-specific customer deployment that's presenting some challenges. This issue will make sure we remember to revert to reasonable logging before prod 0.9.0

**Comment by otoolep** [comment]
Currently being implemented in https://github.com/influxdb/influxdb/pull/2246. Hoping this merge this very soon.

**Comment by otoolep** [comment]
All fixed. This option now exists.

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L111
