### ISSUE TITLE
Multiple results not supported by the Admin UI

### ISSUE THREAD

**Issue by jnutzmann** [influxdb/influxdb#2317]
Running a query like:

````sql
SELECT value FROM cpu_load_short; SELECT value FROM cpu_load_short2 
````

gets a correct response back from the server, but only displays a table for the first result in the set.

Here is an example of the response to the query:

````json
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2009-11-10T23:00:00Z",
                            0.64
                        ]
                    ]
                }
            ]
        },
        {
            "series": [
                {
                    "name": "cpu_load_short2",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2009-11-10T23:00:00Z",
                            0.64
                        ]
                    ]
                }
            ]
        }
    ]
}
````

**Comment by marcosnils** [comment]
I'd like to contribute to this functionality but all the admin code is minified and in some cases obfuscated. 
Is there a chance you release that code so it can be improved by others?

**Comment by beckettsean** [comment]
@marcosnils the admin code lives in its own open repo: https://github.com/influxdb/influxdb-admin. 

We encourage you to make pull requests there, thanks!

**Comment by toddboom** [comment]
@marcosnils also, that code will likely be completely rewritten in the next two weeks, so adding small features at this point may not be very valuable

**Comment by marcosnils** [comment]
Thx for the clarifications. I'll wait for the next release then

**Comment by beckettsean** [comment]
closing in favor of #3503
