### ISSUE TITLE
Configure series to not accept duplicate points or tool to efficiently dedupe series

### ISSUE THREAD

**Issue by pbooth** [influxdb/influxdb#2322]
I have been using influxdb as an alternative to graphite for quick and dirty devops tools to create one-off grafana dashboards. Often that involves repeatedly gathering and storing samples hardware where its likely that I will rewrite the same data point smultiple time sto a series:

time1 value1
time2 value 2
time3 value3
then 

time2 value 2 (again)

I dont want this to bias moving medians, not consume excessive space. Is there value in being able to define series that wont store duplicate points twice - or a straightforward way to dedupe such points in a series? I imagine that such a requirement could be very common.

**Comment by beckettsean** [comment]
@pbooth If you write the same point again it will silently overwrite the previous point. Points are uniquely identified by the series name and the tag set plus the timestamp. If your timestamp is equivalent and you are writing to the same series (same name, same tags and tag values), then InfluxDB doesn't create any duplicates at all, it just overwrites with the same value.

Note that this only applies to 0.9.0.

**Comment by pbooth** [comment]
Perfect. I love it when software just does TheRightThing !
