### ISSUE TITLE
Custom functions or absolute value

### ISSUE THREAD

**Issue by maxcanada** [influxdb/influxdb#2332]
Hello, 

I installed InfluxDB today and it works just great for my time series. I have a question though, is there anyway to define custom functions ? 
I need to compute the sum of all the values in absolute of a column. Something lilke sum(abs(quantity)) would be really great. I installed Grafana and couldn't manage to get it done.

Would you have a solution for me ?
Thanks a lot, 
Max

**Comment by beckettsean** [comment]
Closing in favor of #68
