### ISSUE TITLE
Test Partial replication is very problematic

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2334]
This test fails regularly in CircleCI and has been disabled. DQs need more work. This test must pass reliably before DQs can be considered functional.

@jwilder 
@pauldix 
@corylanou

**Comment by toddboom** [comment]
I think this is fixed with PR #2353.

**Comment by otoolep** [comment]
Unfortunately, we are still seeing issues with this test.

**Comment by otoolep** [comment]
Test disabled here:

https://github.com/influxdb/influxdb/pull/2373

**Comment by otoolep** [comment]
No longer applicable in new design.
