### ISSUE TITLE
How can I order by count(somecolumn)?

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#2341]
I was confused as I was trying to query and  order by some column but failed.

`select count(uuid) from mt group by ip order by count desc`

**Comment by marcosnils** [comment]
@airyland you need to make an alias of the column in order to by it . 

I.E: `select count(uuid) AS total from mt group by ip order by total [DESC|ASC]

**Comment by airyland** [comment]
I tried but still fail.
I'm using influx@0.8.8, does it support?

![image](https://cloud.githubusercontent.com/assets/559179/7224557/6eda7ddc-e766-11e4-8e52-8b0e98211e8a.png)

**Comment by marcosnils** [comment]
@airyland I was talking about 0.9. I have no idea how to do it in 0.8

**Comment by beckettsean** [comment]
Could not order by anything but time in 0.8.x versions.

**Comment by adriancuadros** [comment]
Hello @beckettsean, right now when trying to order by an alias of the column it also returns: "only ORDER BY time supported at this time". 

Was this feature removed?

**Comment by beckettsean** [comment]
@adriancuadros the functionality did not survive to the official 0.9.1 release and is not part of any 0.9 or 0.10 official release.

**Comment by adriancuadros** [comment]
sad to hear, found a workaround but this would have been pretty sweet. hope it turns up sometime soon.

**Comment by deepujain** [comment]
... order by numMappers 
ERR: error parsing query: only ORDER BY time supported at this time

**Comment by beckettsean** [comment]
@deepujain see https://github.com/influxdata/influxdb/issues/5688, https://github.com/influxdata/influxdb/issues/3954, and https://github.com/influxdata/influxdb/issues/4794

**Comment by mans2singh** [comment]
@adriancuadros - Can you please let us know what was the workaround ?  Thanks
