### ISSUE TITLE
influxd -hostname localhost

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#2350]
`influxd -hostname localhost` stopped working after #2233 was merged

https://github.com/influxdb/influxdb/pull/2333/files#r28724886

**Comment by otoolep** [comment]
@neonstalwart -- thanks.

It does look like this regressed, as we had to overhaul the test suite in a significant way for CI stability. We'll have to look at this shortly.

cc @jwilder @corylanou

**Comment by corylanou** [comment]
@otoolep I think the short fix is just to investigate what type of IP address it is, and if it's localhost, set it to that instead of the host name?  I've always thought we should do that anyway as the host name is usually not what you would expect right?

**Comment by neonstalwart** [comment]
also, on a slightly related note, i can't get tests to run locally because the test config keeps wanting to bind to `os.Hostname()` which doesn't resolve to anything for me so i want it to bind to `localhost`.

1. why does the code even try to bind to `os.Hostname()` at all when you could do `influxd -hostname `hostname` and achieve the same thing?  why not just make `'localhost'` the default value?
1. i'm developing on a mac, i assume maybe some of you also use macs for development, do you update /etc/hosts so that the hostname resolves to 127.0.0.1 or what do you do to get the tests running locally?
1.

**Comment by neonstalwart** [comment]
> the host name is usually not what you would expect right?

+1

**Comment by neonstalwart** [comment]
> ...`os.Hostname()` which doesn't resolve to anything for me...

to clarify, `os.Hostname()` returns the hostname but that name doesn't resolve to an IP address for me.
