### ISSUE TITLE
DiagnosticsAsRows(): panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jtakkala** [influxdb/influxdb#2369]
I'm running into this issue when running off the latest build from master. Since running with the fix I proposed in #2366 I now start seeing this. I don't think it's related as sometimes this comes up even without my int64 fix. This requires monitoring=true to trigger. I believe the problem occurs in DiagnosticsAsRows() when we append the path value at line 3310 to the slice of interfaces.

    panic: runtime error: index out of range
    
    goroutine 278 [running]:
    github.com/influxdb/influxdb.(*Server).convertRowToPoints(0xc20816c000, 0x9d4c10, 0xb, 0xc208041ce0, 0x0, 0x0, 0x0, 0x0, 0x0)
    	/Users/jari/go/src/github.com/influxdb/influxdb/server.go:3978 +0x7b7
    github.com/influxdb/influxdb.func·011()
    	/Users/jari/go/src/github.com/influxdb/influxdb/server.go:399 +0x5c0
    created by github.com/influxdb/influxdb.(*Server).StartSelfMonitoring
    	/Users/jari/go/src/github.com/influxdb/influxdb/server.go:412 +0x241

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/2376

**Comment by otoolep** [comment]
All fixed. Thanks to @jtakkala for the bug report.
