### ISSUE TITLE
Document AWS Setup recommendations

### ISSUE THREAD

**Issue by DaveBlooman** [influxdb/influxdb#2377]
With 0.9 nearly here, I was wondering if there are any guidelines for usage with AWS.  I am looking to introduce this to our team, with say a 3 EC2 instance setup.  

As I understand it, a cluster instance would need it's public IP address, which wouldn't be too hard to get, but could be handled by influxdb.  An IP address can be found by hitting `http://169.254.169.254/latest/meta-data/public-ipv4` on an instance, so an option in the config to use this IP address would be nice.
Also, a cluster needs a join URL, https://my.cluster.com:8086, which could be a cluster behind a load balancer.  If a single instance starts, hits that URL, then the load balancer, then it can become the master.  If another instance starts, hits the load balancer and returns itself, rather than the first instance, wont it assume master role as well?  In a situation where you might update the instances, you wouldn't always know the IP address, so setting that in the config wouldn't work.  I'm guessing that the join URL approach is based on the idea of knowing and using the IP address of an instance, rather than using domain names.

Are you considering offering a discovery tool similar to Elasticsearch that can looked for tagged instances , removing the need to set a join URL?

**Comment by beckettsean** [comment]
We will document for 0.9.0 best practices for setting up an EC2 cluster. Auto-discovery is already covered in #1065

**Comment by chaserelock** [comment]
I'd like to +1 this, as well as recommendations on EC2 Images/Types best suited for Influx (e.g. General/Memory/Storage optimized)

**Comment by beckettsean** [comment]
Closing in favor of https://github.com/influxdb/influxdb.com/issues/122 on docs repo.
