### ISSUE TITLE
Need tool to migrate data from 0.8.x to 0.9

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2378]
As part of the release of 0.9.0 Final we need a migration utility that can port data from an 0.8.x datastore into 0.9.0. Because 0.8.x supported multiple underlying datastores we cannot simply transform the data on disk. We believe it will be easiest to "replay" the data from the 0.8.x server into the 0.9.0 server as a series of reads and writes. This means all data from 0.8.x needs to be turned into valid JSON for 0.9.0.

We assume that 0.8.x series names are of the format 
```
<tagName>.<tagValue>.[<tagName>.<tagValue>.]<measurement>
```
For example: 
```
zone.us-west-1.host.serverA.cpu_load_short
``` 
Note that migrations for 0.8.x schemas outside this default may require custom solutions.

The corresponding 0.9.0 series would presumably be defined with `measurement` as the series name and the key-value tag pairs turned into explicit tags on the series but not as part of the series name. 

Continuing our example:
```
zone.us-west-1.host.serverA.cpu_load_short
```
becomes (given in partial JSON format as if for a write)
```
"name": "cpu_load_short",
"tags": {
       "host": "serverA",
       "zone": "us-west"
},
```
The associated timestamps and values can be rewritten into the 0.9.0 database without transformation. 

This suggests that the migration tool should pop the measurement name off the end of the 0.8.x series name and use it is the series name in 0.9.0. The tool should also pull key-value pairs out of the 0.8.x series name and make them tags on the new series in 0.9.0. 

Note that we do need to be careful about precision on timestamps. Ideally we would preserve the original precision from the 0.8.x series. At a minimum we can convert all 0.8.x timestamps to RFC3339Nano for injection into 0.9.0.

**Comment by gunnaraasen** [comment]
Also note that large batch writes should be avoided.  Anything over 5000(?) points per batch should be broken up into smaller chunks.

**Comment by tau0** [comment]
Any progress?

**Comment by corylanou** [comment]
@tau0 Finishing up today.  I had a release ready to go yesterday but when I was doing testing I found I forgot some minor steps.  I'm finishing the import side today and hopefully will release tomorrow. Expect a blog post on it.  Thanks for your patience!

**Comment by nornagon** [comment]
What's happening with this task? Is there an ETA on this?

**Comment by mabnz** [comment]
Also eagerly awaiting this, so I can upgrade to 0.9.

**Comment by kkwoker** [comment]
Same here ! Upvote.

**Comment by feliksik** [comment]
Yes,  this is much needed!

**Comment by mnietz** [comment]
:+1: i also have a 0.8.8 Version waiting for the Update

**Comment by corylanou** [comment]
This is completed and will be in the `0.9.3` release.

**Comment by corylanou** [comment]
This has been completed and should of been closed when https://github.com/influxdb/influxdb/pull/3477 was merged.
