### ISSUE TITLE
Broker topic files leak

### ISSUE THREAD

**Issue by jwilder** [influxdb/influxdb#2382]
When deleting a database, the shards on the data nodes are removed and subsequent broker topic streaming and heartbeating will end.  The broker will continue to keep these defunct topic files open and they will never get removed.  When restarting a broker, the existing topic files are read from disk and re-opened.

**Comment by otoolep** [comment]
Interesting issue.

Broker truncation may eventually take care of this, as we know we need brokers to remove topic segments when they get to a certain age, regardless if all data nodes have read the data. In other words, at some point the broker has to give up and delete the topic data. But I could see a lot of slop in the case of database deletion.

**Comment by jwilder** [comment]
Not sure if broker truncation will resolve this though.  Truncation would still keep some (small) topic file on disk, right?  Seems like we need some way for the broker to be notified that a topic is no longer needed and to permanently remove the topic files.

**Comment by otoolep** [comment]
When we add code that will remove all topic data after a certain time, regardless of whether it has been read or not, this would eventually clear it out. It may happen too slow, and I agree that deletion of database should really remove the data there and then.

**Comment by otoolep** [comment]
No longer applicable in new design.
