### ISSUE TITLE
Can't listen on multiple UDP ports writing to the same DB

### ISSUE THREAD

**Issue by jheusser** [influxdb/influxdb#2389]
With the config below, Influxdb starts up and listens on both ports as expected, however packets sent to the second port are not written to the database. When switching to the first port then they appear in Influxdb. Tested on 0.8.8.
```
  # Configure the udp api
  [input_plugins.udp]
  enabled = true
  port = 2222
  database = "db1"

  # Configure multiple udp apis each can write to separate db.  Just
  # repeat the following section to enable multiple udp apis on
  # different ports.
  [[input_plugins.udp_servers]] # array of tables
  enabled = true
  port = 3322
  database = "db1"
```

**Comment by toddboom** [comment]
@jheusser can you test this on one of the v0.9.0 RCs? We likely won't be making changes on v0.8.x, and i know that the plugins have all been rewritten a bit.

**Comment by jheusser** [comment]
@toddboom resolved and tested to be working fine (different udp port, same db, writing to both ports at the same time).
