### ISSUE TITLE
0.9.0-rc26 panics when node wants to join cluster

### ISSUE THREAD

**Issue by quhar** [influxdb/influxdb#2392]
I've installed influxdb 0.9.0-rc26 on two VMs to test cluster. Both VMs are clean and don't have any previous data or config. I started first node with following paramters and empty join-urls config
/opt/influxdb/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/influxdb.conf -hostname at-vie01a-osd02

Then I started second node with parameters:
/opt/influxdb/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/influxdb.conf -hostname at-vie01a-osd03

First node crashed with following stack trace:
https://gist.github.com/quhar/0ea75c25ac6ad674cf57

In logs of second node we have:
[srvr] 2015/04/22 20:00:19 GOMAXPROCS set to 8
[srvr] 2015/04/22 20:00:19 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/04/22 20:00:19 influxdb started, version 0.9.0-rc26, commit 5203e7f426c758b1ed9aaea164a6db5ec912caf8
[srvr] 2015/04/22 20:00:19 Cluster server listening on http://localhost:8086
[srvr] 2015/04/22 20:00:19 broker opened at /srv/influxdb/raft
[raft] 2015/04/22 20:00:19 log pending: waiting for initialization or join
[srvr] 2015/04/22 20:00:19 join: failed to connect to raft cluster: http://at-vie01a-osd02:8086: Get http://at-vie01a-osd02:8086/raft/join?url=http%3A%2F%2Flocalhost%3A8086: EOF
[srvr] 2015/04/22 20:00:19 join: failed to connect raft log to any specified server

**Comment by otoolep** [comment]
We made some clustering fixes in RC27. Can you retry with that?

**Comment by quhar** [comment]
It looks much better now, thanks!
