### ISSUE TITLE
Streaming api missing authentication?

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2395]
Authentication enabled in config. Server listening on "0.0.0.0". Then I pointed curl to <code>external-ip:8086/messaging/messages?index=...&streaming=true&topicID=0"</code> and receiving data from database. By design or this endpoint missing authentication handling? No one should be able to read data from database if there is
```
[authentication]
enabled = true
```

setting specified.

**Comment by wildchild** [comment]
Related to #1364

**Comment by beckettsean** [comment]
`/messaging` no longer exists
