### ISSUE TITLE
Unable to create database named 'stats'

### ISSUE THREAD

**Issue by tehnomaag** [influxdb/influxdb#2399]
I tried to create a new database with:

`curl -G http://127.0.0.1:8086/query --data-urlencode "q=CREATE DATABASE stats"`

And got error:

`{"error":"error parsing query: found STATS, expected identifier at line 1, char 17"}`

Other db names seem to be OK but `stats` is not for some reason. Probably a bug in query parser.

Using version 0.9.0-rc26.

**Comment by mark-rushakoff** [comment]
As an interim workaround, you can double-quote stats:

```
$ curl -G http://127.0.0.1:8086/query --data-urlencode 'q=CREATE DATABASE "stats"'
{"results":[{}]}
$ curl -G http://127.0.0.1:8086/query --data-urlencode 'q=SHOW DATABASES'
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["seedDatabase"],["seedDatabase2"],["stats"]]}]}]}
```

**Comment by otoolep** [comment]
It's a reserved keyword, as in SHOW STATS.

**Comment by otoolep** [comment]
We may have to reconsider if this is a huge pain.

**Comment by tehnomaag** [comment]
Thanks for the explanation. Would be nice to have this reserved keywords escaping mentioned in the docs too in the future.

**Comment by marcosnils** [comment]
@tehnomaag you should check the influxql repo README file (https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md). It usually get's updated more than the official docs page :wink:
