### ISSUE TITLE
First CQ ceased to update after another one created

### ISSUE THREAD

**Issue by wildchild** [influxdb/influxdb#2403]
1. Create 1 CQ -> ok
2. Create 2 CQ -> ok, 1st not ok
3. Delete 1 CQ, create it again -> ok, 2nd not ok

Both CQs downsampling to different measurement names but to the same RT "daily" from "hourly" RT. Same queries actually for both <code>group by time(1m)</code> for first, <code>10m</code> for 2nd.

**Comment by toddboom** [comment]
@wildchild can you provide the CQs you were using in these cases? i'm going to dig into these issues over the next few days, and the additional detail would be helpful. thanks!

**Comment by wildchild** [comment]
CREATE CONTINUOUS QUERY cq1m ON mydb BEGIN SELECT sum(val) AS mysum
    INTO "mydb"."daily".down1m FROM "mydb"."hourly".myseries GROUP BY time(1m), type END

CREATE CONTINUOUS QUERY cq10m ON mydb BEGIN SELECT sum(val) AS mysum
    INTO "mydb"."daily".down10m FROM "mydb"."hourly".myseries GROUP BY time(10m), type END

**Comment by beckettsean** [comment]
Believed fixed in RC28, can you repro?

**Comment by otoolep** [comment]
Should be fixed by PR #2552

**Comment by otoolep** [comment]
Almost certainly fixed in RC30.
