### ISSUE TITLE
Interrupting influxdb first startup after install prevents login

### ISSUE THREAD

**Issue by kenatbasis** [influxdb/influxdb#2406]
On ubuntu 12.04, running the following commands:
```
wget http://get.influxdb.org/influxdb_0.8.8_amd64.deb
dpkg -i influxdb_0.8.8_amd64.deb
service influxdb start && service influxdb restart
```
results in ```curl 'http://localhost:8086/cluster_admins?u=root&p=root'``` returning ```Invalid username/password```

Restarting the service does not fix the failed default login. Totally reinstalling does fix it, ie 
```
service influxdb stop
dpkg --purge influxdb
rm -rf /opt/influxdb
dpkg -i influxdb_0.8.8_amd64.deb
service influxdb start #no immediate restart
```

Adding a 1 second sleep between the service start and restart seems to be enough time for the db to avoid getting in a bad state.

Ran into this because saltstack's ```service``` state does a ``start && restart`` without a sleep in between.

**Comment by beckettsean** [comment]
We are not actively developing on the 0.8 branch, and this is a somewhat arbitrarily created corner case which has a trivial workaround.
