### ISSUE TITLE
Unable to drop measurement

### ISSUE THREAD

**Issue by tehnomaag** [influxdb/influxdb#2409]
With `SHOW MEASUREMENTS` I can see:

`{ "results": [ {
            "series": [ {
                    "name": "measurements",
                    "columns": [ "name" ],
                    "values": [ ["stats.tables"], ...etc`

But doing `DROP MEASUREMENT "stats.tables"` returns:
`{"results":[{"error":"bucket not found"}]}`

While `SELECT * FROM "stats.tables"` returns:
`{"results":[{}]}`

How can I get rid of this measurement?

Using InfluxDB 0.9-rc26.

**Comment by marcosnils** [comment]
@tehnomaag just tested that in rc27 and seems to be working.

**Comment by marcosnils** [comment]
here you have a container with latest rc working: mantika/tutum-docker-influxdb:staging-0.9.0-rc

**Comment by tehnomaag** [comment]
I'll upgrade to rc27 today to check again.

**Comment by tehnomaag** [comment]
Couldn't drop these measurements on rc27 either on first try. But after adding a new record to those measurements via /write call, then the drop started working without errors. So I'm closing the issue.
