### ISSUE TITLE
"value" column to collectd

### ISSUE THREAD

**Issue by kimor79** [influxdb/influxdb#2412]
https://github.com/influxdb/influxdb/blob/master/collectd/collectd.go#L174 adds a column named &lt;plugin>_&lt;value name> with the value. Some tools expect there to be a column named "value" with the value. Since the plugin and value name are already the name of the point, what about changing that line to

```
fields["value"] = data.Values[i].Value
```

Based on conversation in https://groups.google.com/d/msg/influxdb/JxRmWPom6ao/QAIw0H8Vi5QJ

(I would have submitted this as a patch but I don't have a dev/test environment at the moment)

**Comment by mnuessler** [comment]
Same applies for the graphite plugin. When sending a value for a metric named, say "cpu_load_short", the value is stored in a column "cpu_load_short" instead of "value".

Example:
```echo "host.server02.region.us-east.cpu_load_short 0.64 `date +%s`" | nc -q0 localhost 2003```

Query:
```SELECT * FROM cpu_load_short```

Result:
```json
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "cpu_load_short"
                    ],
                    "values": [
                        [
                            "2015-04-27T13:07:37Z",
                            0.99
                        ]
                    ]
                }
            ]
        }
    ]
}
```

Shouldn't the value stored in a column named 'value'? Otherwise in i.e. Grafana you have to create queries such as ```SELECT mean(cpu_load_short) FROM cpu_load_short  GROUP BY time(10s) ORDER BY asc``` which seems kind of redundant.

**Comment by otoolep** [comment]
All fixed in RC29.
