### ISSUE TITLE
Query parallelization

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#2413]
It seems that we may not be optimally parallelizing our queries. In other words, a long-running query seems to be blocking simpler queries from finishing.

I tested this with some customer data by running a quick (~100ms) query repeatedly. Then, I ran a longer-running query (~10m) and re-ran the quicker query at the same time. They both finished at approximately the same time, which leads me to believe that the second wasn't executed until the first finished.

**Comment by ecables** [comment]
+1, ran into this today where a runaway query wouldn't stop and new queries weren't able to be processed. I ended up manually restarting influxdb to get out of the broken state. In addition to parallelization, I'd also like a way to manually kill a long running query, either via the CLI or through the data interface.

**Comment by toddboom** [comment]
@ecables can you give me a little bit more information about how you caused this to happen and also what version it happened on?

using RC30, i'm no longer able to replicate this issue as i originally observed it. i've tested it locally with both a single node and a 3-node cluster and can't cause it to happen. i also went back to the original data source (now running RC29) and also couldn't make it happen again.

i am seeing some query delays that seem to be based on some sort of resource contention, but i don't believe it's really due to a lock in the query execution. i'm going to deprioritize this for now until we get a clearer grasp on an actual issue.

**Comment by ecables** [comment]
I am using rc29.

I can reproduce this problem when the dataset returned is very large and/or takes a long time to process (I'm not sure which is the cause). I've reproduced this with both `select value` and `select sum(value)` queries, against results that are >150k rows. I've generated this output by simply matching more patterns in a `=~` query or by extending the `time > now() - ...` time period to 12h, 1d, 1w, and so on.

Here's an example of a very large query, which returned 1.69 million rows and completed in 5m 12s:
```
Returned rows: 1692882

real	5m12.955s
user	0m18.473s
sys	0m9.025s
```

Another query run against the same node, while the above query was running, and normally returns in 0.047s but instead returned in 1m 36s, and returns only 6 rows:
```
Returned rows: 6

real	1m36.127s
user	0m0.008s
sys	0m0.004s
```

Here's the same query run when the system is not processing a large query:
```
Returned rows: 6

real	0m0.045s
user	0m0.004s
sys	0m0.004s
```

The above simple query, which returns 6 rows, is basically: 
`SELECT sum(value) FROM <measurement> WHERE time > now() - 1m AND <tag1> =~ /regexhere/ GROUP BY time(60s) fill(0)`

The complex query, which returns 1.6 million rows, is similar, but without the sum function and more complex/longer duration:
`SELECT value FROM <measurement> WHERE time > now() - 12h AND <tag1> =~ /regexhere|regexhere2/ fill(0)`

**Comment by ecables** [comment]
I'll add that re-creation seems to be hit or miss. Sometimes I'll see one query get delayed, while the prior and subsequent query return normally, and sometimes I won't see any delay on any queries. I've increased the results returned by the query with varying results, but things mostly work... except when they don't.

**Comment by toddboom** [comment]
@ecables thanks for the additional info! when you get a chance, could you also try it against rc30?

**Comment by otoolep** [comment]
@toddboom -- I don't think this is an issue anymore, since our query engine is almost completely changing.
