### ISSUE TITLE
Select Into Not Work on sample data

### ISSUE THREAD

**Issue by yank1** [influxdb/influxdb#2414]
HI. I use the data in the readme.md.

	> select * from cpu
	name: cpu
	---------
	time			value
	2014-11-10T23:00:00Z	100

When I execute the select into query. It seems not work

	> select * into another_cpu from cpu
	> select * from another_cpu
	ERR: measurement not found: "mydb"."default".another_cpu

version : 0.9.0-rc27

Is there any hero can help me?
Thanks

**Comment by beckettsean** [comment]
@yank1 were you perhaps using the 0.8 documentation? Also, the syntax should be `SELECT * FROM foo INTO bar`, not `SELECT * INTO` as you have it.

In any event, the INTO statement does not work in 0.9 except as part of creating a continuous query.

**Comment by saiello** [comment]
Hi @beckettsean there's a way in 0.9 to downsample past data? I started collecting without a "rollout continuous query" and now I would like to aggregate series and insert them into a different measure.
I really appreciate some help. 

Thanks

**Comment by rossmcdonald** [comment]
@saiello You can aggregate and backfill data outside of a CQ using an `INTO` query. 

For example, if you have Telegraf installed (which has a `mem_used` measurement), you can downsample the last week's worth of `mem_used` data by taking the average of every hour like so:

```
select mean(value) as value into mean_mem_used_1h from mem_used where time >= now() - 7d group by time(1h) fill(0)
```

Where we are taking the `mean(value)` every hour from the past 7 days, and inserting it into the `mean_mem_used_1h` measurement.

Let me know if that doesn't make sense.

**Comment by saiello** [comment]
@rossmcdonald all is right. That kind of select was my first attempt, but it didn't work. Instead of the expected outcome, with the inserted record count, influx shows my the select results.

I updated influxdb from the 0.9.4.2 to the latest stable version 0.9.6.1 and now it works, even though
> the INTO statement does not work in 0.9 except as part of creating a continuous query. 

as @beckettsean said.

**Comment by rossmcdonald** [comment]
@saiello Yes, support for ad-hoc `INTO` queries has now been enabled with 0.9.5. This issue dates back to April of last year, so a lot has changed since then. You can see the most recent changes by looking at the [CHANGELOG](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md).

**Comment by beckettsean** [comment]
Also, any information in a closed issue should be suspected stale.
