### ISSUE TITLE
The points disappeared.

### ISSUE THREAD

**Issue by tau0** [influxdb/influxdb#2419]
Hi! We have a production cluster. With a lot of data. And today it've eaten all cpu on our server. So we decided to reboot it. After service influxdb stop. Some influxdb processes were still working. So we decided reboot the machine. But after reboot the influxdb started but there is no any data. I can see shards in viewer, I can see databases. But when I try to ask for some data (such as "SELECT * FROM /.*/ LIMIT 1;") it returns empty response (on grafana dashboard) or request freezes (on data table). I haven't find any errors in log. Version 0.8.8. Ubuntu. 

May be you have some ideas how to recover data? For example somehow copy shards to the new or to the same instance from backup which has created two weeks ago?

some part of logs:
https://gist.github.com/tau0/c950e6dc08d2b7808ce9

Also I want to add that I was forced to add hostname as described here for the start after crash:
https://github.com/influxdb/influxdb/issues/914#issuecomment-55775456
because we move our database to a new server two weeks ago.

**Comment by beckettsean** [comment]
@tau0 what results do you see if you query the database directly with curl commands? It's possible that only the admin console is impaired, given that you can see databases and shards.

**Comment by tau0** [comment]
HTTP requests are giving empty series.

**Comment by beckettsean** [comment]
Anything in the logs?
