### ISSUE TITLE
Tags incur too much memory and degrade performance 

### ISSUE THREAD

**Issue by marcosnils** [influxdb/influxdb#2425]
I'm writing 1000000 points in batches of 1000 to a database in influx and I've decided to add a tag which is a string of 12bytes. After adding the tag i've noticed that the insertion rate really decreased (almost 2x) and that the memory is not efficiently handled. 

After adding one tag with values of 12bytes the memory of the influx process went up to x1000 times more than without it. Attached you'll find the timing results of the 1M points insertion as well as `go tool pprof heap` results. 

Without using tags:

real    3m15.122s
user    1m20.434s
sys     0m1.486s

![image](https://cloud.githubusercontent.com/assets/1578458/7329744/3be4d0e8-eab9-11e4-9e69-ef9dd54dd055.png)

https://github.com/marcosnils/influxdb/blob/perf/notags.svg (download and open in browser)

With tags: 

![image](https://cloud.githubusercontent.com/assets/1578458/7329953/7cb936c4-eabc-11e4-99d0-dc76505fad54.png)

real    5m34.459s
user    1m25.126s
sys     0m1.457s

https://github.com/marcosnils/influxdb/blob/perf/tags.svg (download and open in browser)

**Comment by otoolep** [comment]
How many unique values does your tag have?

Philip

**Comment by marcosnils** [comment]
Hey @otoolep one value per row.

**Comment by marcosnils** [comment]
@otoolep your question reminded me about this: http://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html#tags-and-cardinality I guess i should find some other way to achieve what I'm trying to do :smile:.

**Comment by otoolep** [comment]
Yes, that kind of data means a new series every write, and a large increase in the in-RAM inverted index. Data with that kind of cardinality should really be fields.

**Comment by marcosnils** [comment]
@otoolep  I already had them as fields but I added a tag because some of my points have exactly the same timestamp (I'm drawing payments) and I needed a way for influx not to replace them. I guess I can modify my point's timestamp by adding microseconds (which was the ugly alternative) so they don't get overwritten, what do you think?

**Comment by otoolep** [comment]
That will work. We are planning to add the ability for the system to automatically append in the manner you describe, but for now what you propose is the best thing to do.

**Comment by marcosnils** [comment]
@otoolep amazing, thx for the quick response!.

**Comment by marcosnils** [comment]
@otoolep  Just to be clear about your last comment, you're working in a way that if two points have the same timestamp you'll be able to reflect both on the system right?. This was supported in 0.8 by using sequence numbers, right?. May I ask which was the reason to remove it in 0.9?

BTW: Do you think this feature will be available in 0.9?. For the system we're building this is an important subject. 

Thanks!.

**Comment by otoolep** [comment]
The plan is to support appending in the 0.9 release.
