### ISSUE TITLE
Add support for compressed timeseries

### ISSUE THREAD

**Issue by mbrade** [influxdb/influxdb#2434]
we are using compressed timeseries within our projects. Very often we store timeseries for 50 years in 15 minute granularity which consist of only one value at the start of the timeseries and means that this value is valid until another value is stored.

Even if not beeing able to store such values in this way. It could be a great performance enhancement transferring such timeseries compressed and expand them on server side.

**Comment by neonstalwart** [comment]
is `fill(previous)` what you're asking for? http://influxdb.com/docs/v0.9/query_language/querying_data.html#filling-intervals-with-no-data

**Comment by mbrade** [comment]
Hi

at first I wanted to say no. But I reread the manual and I found that previous argument. Well it seems that this is exactly what I was looking for. So I could use the 'group by time fill previous ' feature to if needed.

Best regards
Marco

**Comment by beckettsean** [comment]
Marco, fill(previous) was built for exactly your use case. Should there be rough edges please let us know.
