### ISSUE TITLE
Clustering - broker/data alone couldn't start

### ISSUE THREAD

**Issue by easyrasta** [influxdb/influxdb#2437]
If I set data enabled=false the influxdb couldn't start. Log: 
```
failed to start reporting because not running as a broker and a data node
```
0.9-rc27

**Comment by easyrasta** [comment]
Same if I set a first machine with broker and data node and second one if I set only data enabled
[srvr] 2015/04/27 13:42:15 influxdb started, version 0.9.0-rc27, commit c887dfe2a86ca7dc6a06710b6a787d37734a23b4
[srvr] 2015/04/27 13:42:15 Cluster server listening on [::]:8086
[srvr] 2015/04/27 13:42:15 data node(0) opened at /var/opt/influxdb/db
[messaging] 2015/04/27 13:42:15 connected to broker: http://172.17.0.2:8086/messaging/messages?index=3&streaming=true&topicID=0
[srvr] 2015/04/27 13:42:16 join: failed to connect data node: http://localhost:8086: unable to join
[srvr] 2015/04/27 13:42:16 join: failed to connect data node to any specified serv

**Comment by jwilder** [comment]
Try adding:

```
reporting-disabled = true
```

to your broker config.

**Comment by easyrasta** [comment]
ok it is working in disable reporting

but if you dont set hostname in data node, it registered with localhost, Then if you set it, broker continue  to hitting it:
```
broker cq: error hitting data node: http://localhost:8086: request returned status 307 Temporary Redirect
```

**Comment by jwilder** [comment]
You'll need to wipe out your data dirs and restart w/ the correct hostname.  #1471 is not implemented yet so there is no way to remove a node yet.

**Comment by otoolep** [comment]
Brokers are no longer part of the design - closing this issue.
