### ISSUE TITLE
Aggregate functions won't return result

### ISSUE THREAD

**Issue by neuront** [influxdb/influxdb#2444]
I've tested `max` and `mean`. Influxd is built from [f50b2a0](https://github.com/influxdb/influxdb/commit/f50b2a0a982d0c64aec2d43cb30b98d141cdcea2) on Ubuntu 14.04

    % curl -G "http://localhost:8086/query?pretty=true" \
         --data-urlencode "db=test" --data-urlencode "q=SELECT * FROM cpu"
    {
        "results": [
            {
                "series": [
                    {
                        "name": "cpu",
                        "columns": [
                            "time",
                            "value"
                        ],
                        "values": [
                            [
                                "2014-11-10T23:00:00Z",
                                100
                            ]
                        ]
                    }
                ]
            }
        ]
    }

    % curl -G "http://localhost:8086/query?pretty=true" 
        --data-urlencode "db=test" \
        --data-urlencode "q=SELECT max(value) FROM cpu GROUP BY TIME(2s)"
    {
        "results": [
            {
                "series": [
                    {
                        "name": "cpu",
                        "columns": [
                            "time",
                            "max"
                        ],
                        "values": [
                            [
                                "1970-01-01T00:00:00Z",
                                null
                            ]
                        ]
                    }
                ]
            }
        ]
    }

    % curl -G "http://localhost:8086/query?pretty=true" \
        --data-urlencode "db=test" \
        --data-urlencode "q=SELECT mean(value) FROM cpu GROUP BY TIME(2s)"
    {
        "results": [
            {
                "series": [
                    {
                        "name": "cpu",
                        "columns": [
                            "time",
                            "mean"
                        ],
                        "values": [
                            [
                                "1970-01-01T00:00:00Z",
                                null
                            ]
                        ]
                    }
                ]
            }
        ]
    }

**Comment by marcosnils** [comment]
@neuront try specifying a time condition in your query for example:

`SELECT mean(value) FROM cpu where time > '2014-11-08T23:00:00Z'  GROUP BY TIME(10m). 

That should do it

**Comment by neuront** [comment]
@marcosnils It works. Thanks. I think in this case influxd should report "too many points in the group by interval. maybe you forgot to specify a where time clause?", which actually shows up when time span is very large and group by a time interval that is too small.

**Comment by neonstalwart** [comment]
#2540 fixes this. the error is:

```
"error parsing query: aggregate functions with GROUP BY time require a WHERE time clause"
```

**Comment by toddboom** [comment]
@neonstalwart good catch - thanks!
