### ISSUE TITLE
create database shouldn't cause an error when the database already exists

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#2458]
i have a number of clients trying to connect to a single database via HTTP.  each client queries `SHOW DATABASES` to see if the database exists already.  if the database does not exist the client should create it.

the problem is that if more than one of these clients start at the same time and discover that the database does not exist, they will each try to create the database.  the first one will succeed but the others will get an error.  i can look at the error message and ignore it if it indicates that the database already exists but it feels kind of brittle to rely simply on an error message to determine whether or not i should ignore this error - e.g. the error message may change over time.

i'd rather have the server indicate a success even if the database exists.  in fact, i'd rather skip the `SHOW DATABASES` query and just blindly fire off `CREATE DATABASE foo` to ensure the database exists every time each client starts.  

if there was some reason the database couldn't be created then that should be an error.

i can take a crack at updating the code if there is consensus to change this behavior.  if there are good reasons not to do this, please explain - thanks.

**Comment by otoolep** [comment]
I don't consider this a good idea. If the error messages are not usuable (and they may meet your needs) we should fix that. I would hold off from making any changes like this until more of the team can offer an opinion.

**Comment by neonstalwart** [comment]
the error message is usable in the sense that it's descriptive and readable, i just wasn't sure what guarantees you offer about maintaining those exact messages from version to version.  if i can rely on that text not changing (i.e. they are part of the public API) then that will work for me.

**Comment by neonstalwart** [comment]
@otoolep also, *why* do you think it's not a good idea for create to succeed even if the db already exists? i'd like to understand if you've got time to explain.

**Comment by otoolep** [comment]
I'd rather be explicit in this case as it can mask bugs in a system or client. Perhaps a developer knows that if `CREATE DATABASE` is called more than once, it's a sign that something bad is going on. By not returning this error, the developer can't use this to guarantee correctness.

**Comment by beckettsean** [comment]
The error code should not be a 5xx class error, more likely a 4xx error. However, the consensus on the team is that this should throw an error, not a success.

In addition we could update the query language to offer `CREATE DATABASE IF NOT EXISTS`

**Comment by neonstalwart** [comment]
> The error code should not be a 5xx class error, more likely a 4xx error. However, the consensus on the team is that this should throw an error, not a success.

that's fine - maybe 409?


> In addition we could update the query language to offer CREATE DATABASE IF NOT EXISTS

that suits my needs too.

let me know if i can start on either of these things.

**Comment by otoolep** [comment]
I don't think the HTTP status code approach is what we want. We want to move away from status codes to indicate something in the system, and instead have richer responses in the body.

A PR to add `IF NOT EXISTS` is definitely something we'd consider merging, but we would need to reach consensus across the team.

**Comment by pauldix** [comment]
This now returns a 200 response code with an error message in the JSON. I think this will work, let me know if you think we need something else.

**Comment by beckettsean** [comment]
Response is now `200` with an error. Seems reasonable.
```
$ curl -iG http://localhost:8086/query --data-urlencode "db=droptest"  --data-urlencode "q=create database test"; echo
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: 64ec1145-4d07-11e5-86ab-000000000000
X-Influxdb-Version: 0.9.2
Date: Thu, 27 Aug 2015 22:03:05 GMT
Content-Length: 49

{"results":[{"error":"database already exists"}]}
```
