### ISSUE TITLE
Cannot query tags containing non-alphabetic characters

### ISSUE THREAD

**Issue by rbrndt** [influxdb/influxdb#2463]
I put in some data which I can find in the database, but I cannot query it using the tag value if the tag name or value contains non-alphabetic characters such as a dash. I also see this when the tag name or value contains numbers and/or unicode characters.

Here are the curl commands I used to produce this:

-create the point
curl -XPOST 'http://192.168.10.4:8086/write' -d '{"database": "mydb", "retentionPolicy": "default", "points": [{"name": "cpu_load_short","tags": {"host": "server01", "region": "us-west"}, "timestamp": "2009-11-10T23:00:00Z", "fields": {"value": 0.64}}]}'

-query the point (this returns records)
curl –G ‘http://192.168.10.4:8086/query?q=show%20series%20from%20%22cpu_load_short%22&db=mydb’

-query the point by tag (this does not return any records)
curl -G 'http://192.168.10.4:8086/query?q=show%20series%20from%20%22cpu_load_short%22%20where%20%27region%27%3D%22us-west%22&db=mydb'

influx: rc-28
OS: 64-bit Ubuntu 14.04

**Comment by beckettsean** [comment]
SHOW SERIES is not the correct statement to retrieve points. That only shows the names of the series that match the WHERE clause. You should use SELECT statement to retrieve points: http://influxdb.com/docs/v0.9/query_language/querying_data.html#select-and-time-ranges

It's possible that SHOW SERIES has some parser issues with non-alphabetical characters.

**Comment by beckettsean** [comment]
The proper syntax for the query uses double-quotes around "region". Single quotes are only for strings used as values, identifiers are double-quoted. You had the two reversed. The correct syntax would be `show series from "cpu_load_short" where "region"='us-west'` However, you don't need to quote any of the strings in that query as all have only legal characters.
