### ISSUE TITLE
Empty respones from server when using chunked responses

### ISSUE THREAD

**Issue by Jackkoz** [influxdb/influxdb#2466]
Operating system: Ubuntu 64bit 14.10
InfluxDB version:  0.9.0 rc26 (built from sources, also present in RC 25)

Description: When using chunked respones with a sample query such as:
curl -G '<HOST>:<PORT>/query?u=root&p=root&db=toto&q=select%20*%20from%20cpu_load_short%20limit%203;&chunked=true' 

the server returns an empty response. However, adding flag '--compressed' results in a proper result. The very same query without the 'chunked=true' flag returns a proper result with and without '--compressed'. Further investigation proved that the culprit is a missing method 'Flush()' in the httpd.responseLogger class. Server log attached below as a proof. Additionally, this error is not caught by tests included in the repository as they might probably disable logging and/or use compressed responses. 

I have also included an implemented solution in this pull request: https://github.com/influxdb/influxdb/pull/2465

[http] 2015/04/18 11:39:06 83.9.126.18 - - [18/Apr/2015:11:39:06 +0000] GET /query?u=root&p=root&db=toto&q=select%20*%20from%20cpu_load_short%20limit%203;&pretty=true HTTP/1.1 200 1025 - curl/7.40.0 8518ce18-e5bf-11e4-803c-000000000000 1.289ms
[srvr] 2015/04/18 11:39:20 http: panic serving <IP>:<PORT>: interface conversion: *httpd.responseLogger is not http.Flusher: missing method Flush
goroutine 44250327 [running]:
net/http.func·011()
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc2081c28c0, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:267 +0x97b
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7f3fe7665010, 0xc208108a40, 0xc208160c30, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:111 +0x4f
github.com/influxdb/influxdb/httpd.func·004(0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:881 +0x77
net/http.HandlerFunc.ServeHTTP(0xc2081082e0, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:925 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc2080c1260, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:941 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc208108320, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:974 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080c12d0, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:984 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080c12f0, 0x7f3fe7665010, 0xc208108a40, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x7f3fe7665010, 0xc2081089e0, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:992 +0x123
net/http.HandlerFunc.ServeHTTP(0xc208108340, 0x7f3fe7665010, 0xc2081089e0, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·010(0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:1002 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc208108360, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208130690, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2081c28c0, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/httpd/handler.go:183 +0x4a
main.(*Handler).serveAPI(0xc208108000, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:150 +0x1e5
main.(*Handler).ServeHTTP(0xc208108000, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:70 +0x556
net/http.serverHandler.ServeHTTP(0xc2080d6600, 0x7f3fe764f198, 0xc2081d6500, 0xc208160c30)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208176640)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

**Comment by otoolep** [comment]
All fixed -- thanks @Jackkoz
