### ISSUE TITLE
should Call.Name be normalized to lower case?

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#2471]
works:
```
select percentile(value, 95) from foo
```
doesn't work (`"error": "expected one argument for PERCENTILE()")`:
```
select PERCENTILE(value, 95) from foo
```

there seems to be quite a few places in the code that compare to the lowercase version of `Call.Name`.  would it be better to normalize `Call.Name` to be lowercase when it's created or even to store the original as well as a normalized?

**Comment by otoolep** [comment]
All functions should be case-insenstive. It's on our list to do, but we need to look into solving it at a global level (perhaps at the parser or scanner level) and try to avoid fixing it for individual functions if possible.

**Comment by toddboom** [comment]
@neonstalwart i think this is a good idea. i'm kicking the build on your PR now.

**Comment by neonstalwart** [comment]
ok, so my first thought is to change things like 
```go
&Call{Name: expr.Name, Args: args}
```
 to 
```go
&Call{Name: strings.ToLower(expr.Name), Args: args}
```
would that be a good start?
