### ISSUE TITLE
"Writing multiple points" not working

### ISSUE THREAD

**Issue by xavierpenya** [influxdb/influxdb#2483]
Using v0.9.0-rc11, single node setup.

After some days exploring the capabilities of InfluxDb, and writing a wrapper in c#, I have come to the conclusion that "Writing multiple points" does not work. At least not in the form as shown in the documentation example: http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#writing-multiple-points

This forces "tags" and "fields" to be repeated inside each point structure, which I guess is terribly inefficient for both bandwith and data classification.

**Comment by neonstalwart** [comment]
@xavierpenya do you have the same issue with v0.9.0-rc28?  i believe `"fields"` is the only thing needed to be on each point since the fields are the value you are recording for that point.

**Comment by beckettsean** [comment]
Please try with RC28. If you still have issues, please provide reproducible steps and relevant log lines.

**Comment by xavierpenya** [comment]
Unfortunately, I find myself completely unable to compile the source code under windows (I've been trying for the last two days while off work). This is why I was using an older version, which was provided by another user online. 

I am highly interested in this time-value db, and I already had a fairly advanced development of a wrapper written in c#. But now I find myself trapped between a malfunctioning release and an unreachable last version.

I have been following the relevant links that provide information about that:
http://stackoverflow.com/questions/26116711/how-to-install-inflxdb-in-windows
https://groups.google.com/forum/#!topic/influxdb/Z9LewrSNPfk

...but Go does not make things easy for Windows users... which might be related to why influxdb does not have a windows binary of the latest release available on the website.

I will report all necessary data if I ever get past this hurdle.

**Comment by beckettsean** [comment]
@xavierpenya windows binaries will be part of the final release but we're not building them for every intermediate package. RC11 is old enough now that testing on it is not particularly meaningful, and errors found may not have any bearing on the new releases.

Our testing does suggest InfluxDB won't ever be compatible with 32-bit Windows. Are you trying to compile for 64-bit?

**Comment by xavierpenya** [comment]
@beckettsean 

I was finally able to compile it (64-bit). In my case it was more a golang issue than a InfluxDb issue. Now I have RC28 up and running under Windows.

Regarding the error I was reporting at the beginning of this thread, it persists in this last version:

While the "write single point" example works fine, the "write multiple points" (as written in the documentation example: http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#writing-multiple-points ) produces an "internal server error" response, while the influxd.exe console does not provide any useful information about the error: 

> [http] 2015/05/07 01:06:36 ::1 - - [07/May/2015:01:06:36 +0200] POST /write?u=ro
ot&p=root&db=mydb HTTP/1.1 500 123 http://localhost:8083/ Mozilla/5.0 (Windows N
T 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari
/537.36 8bdb28f9-f444-11e4-8004-000000000000 2.0145ms

How can I provide more detailed information about the error? 

In the previous version, I had configured the following lines (which worked well):

[logging]
level = "debug"
file = "influxdb.log"
write-tracing = true

...in the r28 version, this does not seem to have any effect.

**Comment by xavierpenya** [comment]
...anyway, I have created a quick "how to" guide in StackOverflow for those like me struggling with compiling InfluxDb on Windows:

http://stackoverflow.com/a/30127377/831138

**Comment by beckettsean** [comment]
@xavierpenya Thanks for the link to the Windows compile doc. I'll stash that for later documentation. 

As to the recurring error there's a simple and slightly embarrassing explanation. The documentation for inserting multiple points is incorrect. It has an epoch timestamp inside double-quotes, which renders it a string, which is not a valid RFC3339 timestamp, so it fails. Simply removing the double-quotes from the number, i.e. `"timestamp": "1422568543702900257",` becomes `"timestamp": 1422568543702900257,` should allow you to write the example points. 

I'm updating docs today to remove or rework examples that are broken. This one is already fixed but I'm going to push them together in a big batch.
