### ISSUE TITLE
load testing causes panic on 3-node cluster

### ISSUE THREAD

**Issue by agreentree** [influxdb/influxdb#2490]
influxdb 0.9.0-rc28
test - posting to 100K unique metrics every 5-10 seconds, influxdb on node 2 of a 3-node cluster eventually panics
influxdb.log: panic: assert failed: log entry skipped(2): idx=10636, prev=10615
total measurements = 656944.0

**Comment by beckettsean** [comment]
Thanks for the load test, agreentree. That's at the upper bound of what influxdb can currently ingest. We're implementing a backpressure feature to let clients know the db is saturated for writes.

Please try RC29 as soon as we release that. We've made some improvements that should increase write stability.
