### ISSUE TITLE
0.9.0-rc28 -- process_continuous_queries "use of closed network connection" error

### ISSUE THREAD

**Issue by ecables** [influxdb/influxdb#2493]
Seeing these errors in influxd.log with 0.9.0-rc28 w/ a 3-node cluster:
[srvr] 2015/05/05 15:58:08 broker cq: error hitting data node: http://testdb2.local:8086: Post http://testdb2.local:8086/data/process_continuous_queries: read tcp 10.1.20.30:8086: use of closed network connection

I don't have any continuous queries configured at this time.

**Comment by spynode** [comment]
Seeing this on rc31. After upgrading from rc30 to rc31, log is full of "[srvr] 2015/05/25 14:45:33 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: read tcp 127.0.0.1:8086: use of closed network connection" messages. Configured Graphite database is not created automatically, it is impossible to create databases using API/UI. There are no continious queries configured and rc31 was installed both, as upgrade from rc30 and as a fresh install after deleting all previous data.
