### ISSUE TITLE
InfluxDB 0.9.0 Documentation is Incorrect Regarding the Default Value for "Precision" Set Through the Client

### ISSUE THREAD

**Issue by MBaron007** [influxdb/influxdb#2494]
From http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html: 
![image](https://cloud.githubusercontent.com/assets/3818452/7486118/de603170-f354-11e4-9ea6-30e39350767b.png)
"If no precision is specified, seconds is assumed."

This can be disproved by looking at the following function used to set precision https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L524:

![image](https://cloud.githubusercontent.com/assets/3818452/7486135/2421a996-f355-11e4-99a7-28922febdc5a.png)

Here, it is clear that if no "Precision" is specified at a Point or BatchPoints level, it just returns the time.Time object, which is in nanoseconds ("n") by default since RFC3339Nano is being used in MarshalJSON (https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L316).  This also explains why nothing is done in "case n:".

In general, I think the InfluxDB 0.9.0 documentation needs to be accurate and updated more often, maybe at least after every X number of release candidates (especially since this issue held me up for a long time)?  Thanks for your help!

**Comment by neonstalwart** [comment]
@MBaron007 the docs do need some more love but i think you may actually be wrong about this (which would mean the docs are right).  if you provide an integer value as a timestamp then https://github.com/influxdb/influxdb/blob/934a5be1c927206afe37f21f5f7020a74749f022/client/influxdb.go#L366 is the path taken by the code when unmarshalling a point.  that path uses `EpochToTime` which by default uses `"s"` as the precision https://github.com/influxdb/influxdb/blob/934a5be1c927206afe37f21f5f7020a74749f022/client/influxdb.go#L500-L502

the path you're showing is taken when you provide an RFC3339 timestamp.

do you have any curl commands to show that the behavior is not consistent with the docs?

**Comment by MBaron007** [comment]
@neonstalwart ah ok I see, so in the case of an RFC3339 timestamp "Precision" is nanoseconds by default, but when the timestamp is specified as an integer value then "Precision" is seconds by default.  I see how that makes sense given the integer value will inherently be in seconds and it is possible to specify an RFC3339 timestamp down to the nanosecond.  Now that that's been cleared up, I don't believe I can produce any curl statements that would disprove anything in the docs - though perhaps this stipulation about "Precision" could be more explicitly stated in the docs?  Thanks for your help!

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/influxdb.com/issues/124
