### ISSUE TITLE
rc-29 on ubuntu via deb not working?

### ISSUE THREAD

**Issue by paaland** [influxdb/influxdb#2497]
Upgraded my rc-28 installation to rc-29 via deb package (dpkg -i).
Was still able to write data, but non of my queries returned any data.
Downgraded to rc-28 again and my queries started working again.

was using the influx shell to test queries (format column, pretty)

**Comment by beckettsean** [comment]
Anything in the logs when running rc29 and not getting data back?

**Comment by beckettsean** [comment]
Any chance you can provide curl statements to reproduce this? We are unable to repro here.

**Comment by paaland** [comment]
I'll upgrade and try again to check the logs.

fre. 8. mai 2015, 00.59 skrev Sean Beckett <notifications@github.com>:

**Comment by paaland** [comment]
On rc28:

$curl -G 'http://localhost:8086/query?u=root&p=root' --data-urlencode "db=myDB" --data-urlencode "q=select * from Site_32 where channelId='9' limit 10"
{
	"results": [{
		"series": [{
			"name": "Site_32",
			"columns": ["time",	"value"],
			"values": [["2013-03-29T05:10:00Z",	0.5],
			["2013-03-29T05:15:00Z", 1],
			["2013-03-29T05:20:00Z", 0],
			["2013-03-29T05:25:00Z", 1.1],
			["2013-03-29T05:30:00Z", 0.5],
			["2013-03-29T05:35:00Z", 0],
			["2013-03-29T05:40:00Z", 0.1],
			["2013-03-29T05:45:00Z", 0],
			["2013-03-29T06:00:00Z", 0.7],
			["2013-03-29T06:05:00Z", 0.4]]
		}]
	}]
}

On rc29 (note service is running, log has no errors):
influxd.log:
[srvr] 2015/05/08 06:24:18 GOMAXPROCS set to 2
[srvr] 2015/05/08 06:24:18 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/05/08 06:24:18 influxdb started, version 0.9.0-rc29, commit b8cf01dd4a140a6d777d005add703e4838663319
[srvr] 2015/05/08 06:24:18 Cluster server listening on [::]:8086

$curl -G 'http://localhost:8086/query?u=root&p=root' --data-urlencode "db=myDB" --data-urlencode "q=select * from Site_32 where channelId='9' limit 10"
server unavailable

**Comment by paaland** [comment]
Did a reboot. Now the log contains:

[srvr] 2015/05/08 07:05:52 GOMAXPROCS set to 2
[srvr] 2015/05/08 07:05:52 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/05/08 07:05:52 influxdb started, version 0.9.0-rc29, commit b8cf01dd4a140a6d777d005add703e4838663319
[srvr] 2015/05/08 07:05:52 Cluster server listening on [::]:8086
[srvr] 2015/05/08 07:08:12 no broker or server configured to handle data endpoints

Installing rc28 makes it work again.

**Comment by paaland** [comment]
Could there be something thing left in the config from rc28 that makes rc29 not work?

**Comment by paaland** [comment]
Left the server sitting there for a couple of hours. Came back and now it works. 

Can see this in the log:

[srvr] 2015/05/08 06:24:18 GOMAXPROCS set to 2
[srvr] 2015/05/08 06:24:18 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/05/08 06:24:18 influxdb started, version 0.9.0-rc29, commit b8cf01dd4a140a6d777d005add703e4838663319
[srvr] 2015/05/08 06:24:18 Cluster server listening on [::]:8086
[srvr] 2015/05/08 06:24:31 no broker or server configured to handle data endpoints
[srvr] 2015/05/08 06:31:54 broker opened at /var/opt/influxdb/raft
[raft] 2015/05/08 06:31:54 stopped[1]: log open: created at /var/opt/influxdb/raft/raft, with ID 1, term 1, last applied index of 32766861
[raft] 2015/05/08 06:31:54 log open: promoting to leader immediately
[srvr] 2015/05/08 06:31:54 broker already member of cluster.  Using existing state and ignoring join URLs
[srvr] 2015/05/08 06:31:54 Loading metadata index for myDB
[messaging] 2015/05/08 06:31:55 connected to broker: http://localhost:8086/messaging/messages?index=13038324&streaming=true&topicID=938

So service was started at 06:24, but did not start responding before 06:31.....
