### ISSUE TITLE
Issue clustering influxdb (3 nodes) with docker/docker-compose

### ISSUE THREAD

**Issue by tywkeene** [influxdb/influxdb#2503]
I've been trying to get a influxdb cluster up and running using docker and docker-compose but have run into a problem when running the cluster. 

I have one 'seed' node (called node0) and 2 'child' nodes (called node1 and node2), as you can tell from the docker-compose.yml file, nodes 1 and 2 are linked to and require node0 to be online to run successfully. 

So node0 comes up, and one of the two child nodes comes up and joins node0 in the cluster. The problem seems to arise when the other child node attempts to join the cluster, throwing a 'duplicate node url' panic, and bringing down the entire cluster. This causes me to believe that the cluster can't handle two nodes with the same hostname, so I've had to split both the influxdb configuration file, and the dockerfiles for the seed server and the child nodes in an attempt to get different hostnames on the child nodes. (config_seed.toml/config_node.toml and Dockerfile.seed/Dockerfile.node) 

I'm really out of ideas here, I'm a bit rusty with docker and don't have a whole lot of time with compose so any light anyone can shed on this problem would be great.

The files are here: https://gist.github.com/SaviorPhoenix/46df40f0f5ffb19b9c09

You can reproduce this behavior by installing both [docker](https://docs.docker.com/installation/) and [docker-compose](https://docs.docker.com/compose/install/), and running `./build.sh`, this will build the docker images for the seed and child nodes. You can then run `docker-compose up` in the same directory as the `docker-compose.yml` file.

This is the log output I get: https://gist.github.com/SaviorPhoenix/2d655bdd61222e95ae41

Cheers.

**Comment by jwilder** [comment]
Closing since this appears to be related to the old clustering implementation.  I would suggest trying the latest release.

**Comment by nicolargo** [comment]
Hi @tywkeene , your gist link to the docker-compose file is outdated.
Please can you publish it again, it will help me to configure a InfluxDB cluster.

**Comment by tywkeene** [comment]
Hi @nicolargo.
I'm going to have to do some digging and remembering (it's been a while), but I will get these files back up for you as soon as I can. Sorry for the inconvenience.
