### ISSUE TITLE
Creating new database immediately after starting instance and turning auth on fails... sometimes

### ISSUE THREAD

**Issue by tbaudais-va** [influxdb/influxdb#2504]
Here's how I reproduce this issue:

1. Create a new influxdb 0.9 server rc27 (our env uses docker on Compute Engine n1-standard-1 instances). Our config defaults to auth enabled.
2. Login, disable auth, stop and start docker container.
3. Create a temp table "temp"
4. Enter commands into web query interface:
  CREATE USER uuuu WITH PASSWORD 'xxxx'
  GRANT ALL PRIVILEGES TO uuuu
5. Log into instance enable auth, stop and start docker container.
6. Re-login to web interface with above creds. Try to create new database. THIS FAILS FOR US (But doesn't show an error)
7. Wait a few minutes and try again THIS (MOSTLY) SUCCEEDS FOR US.

If you have problems reproducing, let me know and maybe I can help you out. It's pretty consistent with our setup.

**Comment by beckettsean** [comment]
Is this reproducible using direct curl statements rather than the web UI?

**Comment by tbaudais-va** [comment]
Yes. That's how I was originally doing it.

**Comment by beckettsean** [comment]
@tbaudais-va can you please share the curl statements to repro the issue? That will greatly simplify our characterization of the issue.
