### ISSUE TITLE
Can't delete DB with GUI, if it has a hyphen in the name.

### ISSUE THREAD

**Issue by etarasoff-va** [influxdb/influxdb#2505]
Can't delete database from the GUI's X-button, if it's got a hyphen in the name.
> e.g. "foo-1"

Get this error:
> Failed to remove database: {"error":"error parsing query: found -, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 22"}

![influx-error](https://cloud.githubusercontent.com/assets/9092193/7504874/b6af032a-f40a-11e4-9124-026705066464.png)

**Comment by marcosnils** [comment]
@etarasoff-va probably is not quoting dbname when deleting. Don't expect this to be resolved soon, influx guys are working on a new frontend...

**Comment by beckettsean** [comment]
This is an issue only with the web UI. Using quoted strings with the CLI or curl works fine to create or delete a database.

**Comment by etarasoff-va** [comment]
No problem. We can delete the DBs with DROP commands. If the frontend is getting a rework, then that'd fix this. (eventually) Thanks for the reply! :)
