### ISSUE TITLE
influxdb restore fails with rc28

### ISSUE THREAD

**Issue by agreentree** [influxdb/influxdb#2506]
backup works, but restore fails as follows:
vagrant@mini-mon:~$ /opt/influxdb/influxd backup /tmp/mysnapshot
2015/05/06 22:18:03 influxdb backup, version 0.9.0-rc28, commit f50b2a0a982d0c64aec2d43cb30b98d141cdcea2
2015/05/06 22:18:03 backup complete
vagrant@mini-mon:~$ /opt/influxdb/influxd restore -config /etc/opt/influxdb/influxdb.conf /tmp/mysnapshot
2015/05/06 22:18:26 influxdb restore, version 0.9.0-rc28, commit f50b2a0a982d0c64aec2d43cb30b98d141cdcea2
[srvr] 2015/05/06 22:18:26 Near line 0 (last key parsed ''): Bare keys cannot contain '/'.

**Comment by neonstalwart** [comment]
fyi - i see the same thing with rc29

**Comment by neonstalwart** [comment]
the error message is coming from the toml parser... so maybe it's an easy fix.

**Comment by agreentree** [comment]
looks like the problem was introduced in rc24. Hoping it can be fixed ASAP...
