### ISSUE TITLE
Very slow reads and writes after while

### ISSUE THREAD

**Issue by zidekmat** [influxdb/influxdb#2519]
This happened to me before, so yesterday I started off with fresh installation of RC29 on amb64 Debian to reproduce the issue.
Every 30s I insert about 7500 new points in batches of max 2500. Each point has 5-11 tags and there is one CQ since when I put more not even one CQ works, but thats not the issue I want to report. The CQ selects 1 minute means from 10h retention policy to one day.
Now its running for about 16 hours and its performance is terrible. RAM consumption is about 2GB (VMs maximum) and even takes up about 1GB swap space, CPU usage is alright.

Logs say this about write time: 
````
[http] 2015/05/08 12:33:28 127.0.0.1 - test_admin [08/May/2015:12:31:39 +0200] POST /write HTTP/1.1 200 
23 - Ruby 6952ea8f-f56d-11e4-b972-000000000000 1m48.91801908s
````
this about read times (query generated by Grafana) :
````
[http] 2015/05/08 12:34:48 127.0.0.1 - - [08/May/2015:12:28:46 +0200] GET /query?db=test&p=test_admin&q=SELECT+mean(value)+FROM+%22test%22.%22ten_hours%22.%22MEM_USAGE%22+WHERE+time+%3E+now()+-+10h+GROUP+BY+time(30s)+fill(null)+ORDER+BY+asc&u=test_admin HTTP/1.1 200 8149 http://147.251.253.36:3000/dashboard/db/mem_usage Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36 021a7676-f56d-11e4-b94c-000000000000 6m1.938578839s
````
and there are plenty of errors for CQ:
````
[srvr] 2015/05/08 12:33:59 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: net/http: request canceled while waiting for connection
````

Here is a graph from Grafana showing that less and less points are written and there are even some gaps with no points:
![mem_usage](https://cloud.githubusercontent.com/assets/3611530/7534923/d5efe18e-f57f-11e4-9e37-14c0c2ce3647.png)

Here are some stats:
![stats](https://cloud.githubusercontent.com/assets/3611530/7535027/f26d1646-f580-11e4-8857-40892edb65ee.png)

**Comment by zidekmat** [comment]
Thinking this was problem with CQ I removed it and tried to save data just in 10h retention policy. I deleted all data, reinstalled influx and started the pushing script. Since then RAM usage went up to limit as before. The retention policy is full and data ingestion behaves the same as before, so it inserts new data only about every hour. CQ errors mentioned above are still there.

Can you give me some status of this? I would really appreciate it since in production I'd like to have about 5 times more retention policies but now it seems as if it won't work even with more server resources.

**Comment by toddboom** [comment]
@zidekmat can you give us more information about the data you're sending? sample data would be ideal. also, if you can provide the continuous queries you're using, we'll try to replicate this in our testing environment.

**Comment by zidekmat** [comment]
Ofcourse. Here is the only setup for database:
```
CREATE DATABASE test;
CREATE USER test_admin WITH PASSWORD 'test_admin';
CREATE RETENTION POLICY ten_hours ON test DURATION 10h REPLICATION 1;
```
The issue exists even if there are no continuous queries. I tried. [Here](https://www.copy.com/s/IKjZugpmOhieZ6xV) is sample in 3 batches, it should be 5913 new points.

And if you want to reproduce it completely, [here](https://github.com/zidekmat/one2influx) is the script I'm using. If you use the database and the user above, you just need to run test/one2influx_fake if you have ruby dependency installed.

Let me know if you need anything else.

**Comment by mcsquaredjr** [comment]
I have the same issue, performance is terribly slow after upgrading to RC29.

**Comment by toddboom** [comment]
@mcsquaredjr can you send us a sample of the log file during the time period that the slow writes are occurring?

**Comment by mcsquaredjr** [comment]
I’m running influxdb from a script together with some other services so its output is mixed with logging from other systems. I looked at /opt/influxdb/shared/log.txt but it’s empty. Is there any other place I should be looking at?


On May 12, 2015 at 10:49:41 AM, Todd Persen (notifications@github.com) wrote:

@mcsquaredjr can you send us a sample of the log file during the time period that the slow writes are occurring?

**Comment by toddboom** [comment]
is there anything in `/var/log/influxdb/influxd.log`?

**Comment by mcsquaredjr** [comment]
Nope, the directory is empty. 


On May 12, 2015 at 11:00:52 AM, Todd Persen (notifications@github.com) wrote:

/var/log/influxdb/influxd.log

**Comment by beckettsean** [comment]
@mcsquaredjr how did you install influxDB? How are you starting the process?

**Comment by mcsquaredjr** [comment]
It’s standard debian package for 64-bit Linux, I’m running it on Ubuntu 14.0.1. The process starts as  influxd without any arguments with defaults configuration. Let me re-emphasize that several older versions were (and still are) working just fine, I noticed the difference (and it’s slower by a factor of 50-60) after I decided to try the most recent build. The previous build I used was RC17. I’m not loading huge amount of data btw, few hundreds of data points with 10 tags or so.

Hope it helps.

On May 12, 2015 at 3:22:51 PM, Sean Beckett (notifications@github.com) wrote:

@mcsquaredjr how did you install influxDB? How are you starting the process?

**Comment by zidekmat** [comment]
**Update for RC30**
I upgraded server resources to 4GB RAM which didn't help at all and then to 8GB and that seem to do the trick. Now it's working flawlessly although the memory consumption is around 4GB which I consider really high since there are about 7,5 million points and I want  around 30 millions.
While it's working I added some CQs because they are finally functional in this release and  from time to time there are still these errors:
```
[srvr] 2015/05/18 15:45:15 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: read tcp 127.0.0.1:8086: use of closed network connection
```

**Comment by otoolep** [comment]
@zidekmat -- are you running a clustered system?

**Comment by zidekmat** [comment]
No, I can't figure out how to set it up. Would it help?

**Comment by otoolep** [comment]
No, knowing you are running a single-node is helpful as it limits the range of possibilities under which this could happen. I'm currently looking into why these errors occur.

**Comment by toddboom** [comment]
thanks for all the feedback on this. i'm going to close it out for now because the read and write paths are changing in v0.9.0 and i think this issue will go away. please let me know if you see it after RC32 is released and we'll reopen this it.
