### ISSUE TITLE
no series or measurements after `CREATE CONTINUOUS QUERY` in 0.9.0-rc28

### ISSUE THREAD

**Issue by lawrancejing** [influxdb/influxdb#2529]
HI:

i install influxdb-0.9.0_rc28-1.x86_64 in my CentOS 7 node, now i create one CQ like below:

name			query
100m_event_count	CREATE CONTINUOUS QUERY "100m_event_count" ON test BEGIN SELECT count(value) INTO "test"."rollup_15m".disk_write_bytes FROM "test"."rollup_5m"./2fcb05f5-d7dd-4330-ab08-aaa32c8eb9a5.disk.write.bytes/ GROUP BY time(10m) END

after few hours, there is no series or measurements about disk_write_bytes via `show series`
am i missing something about the execution of CQ?

**Comment by marcosnils** [comment]
There are tons of issues about CQ's not working in 0.9. 

https://github.com/influxdb/influxdb/issues/2253
https://github.com/influxdb/influxdb/issues/2529
https://github.com/influxdb/influxdb/issues/2510

Please close duplicated issues and run a search before opening a new one.

**Comment by toddboom** [comment]
@marcosnils thanks for putting that list of issues together - i'm going to experiment with this a little bit over the next few days to see if we can sort these out.

@lawrancejing i'm going to close this issue out since it's a dupe, but thanks for letting us know!

**Comment by lawrancejing** [comment]
@marcosnils & @toddboom thanks a lot, will try asap.
