### ISSUE TITLE
Not writing multiple data points in a batch

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2533]
Use this gist: https://gist.github.com/Urth/24c635dbd52c9dcf9a35

The SELECT statement should be returning all 3 data points that were written in.

**Comment by beckettsean** [comment]
possibly related #2027 #2450

**Comment by Urth** [comment]
I'm not able to make it fail with the data from that gist anymore but if I change the timestamp on the last point to todays date it will fail as before.

**Comment by pauldix** [comment]
This one looks like I've been chasing my tail. After closer investigation, it looks like the data point that wasn't showing up in the query was being written with a time in the future. Looking at the timestamp of the linked Gist backs this up.

If you want future data to show up in a query,  you have to explicitly set an end time like:

```sql
select * from foo where time < '2100-01-01'
```

I'm guessing you didn't want to post future data. If you did, please lend us your time machine so we can give up on this whole software thing and sit on a beach with our earnings from perfect knowledge of the stock market ;)

Otherwise, any library that is posting data should always be converting the time to UTC if they are specifying the time of their data points. Data points posted without a timestamp don't have this problem since the server converts to UTC.

Let me know if it can reproduced in some other way, but that's what it's looking like.

@beckettsean: those other issues look like they're related to the broker replication issue. We're looking into that now :)
