### ISSUE TITLE
go client Ping function need determine the version

### ISSUE THREAD

**Issue by lostz** [influxdb/influxdb#2544]
Today I forget set the port in client.Config.url.
But the ping function return err and version both nil.
Because I hava nginx.
I suggest  determine the version to avoid the same question

**Comment by beckettsean** [comment]
@lostz how did you install influxDB? Can you share the first ~100 lines of your log file?

Are you proxying localhost:8086 via nginx?

**Comment by lostz** [comment]
use rpm
Yes , I am proxying localhost:8086 via nginx.
So I suggest return version info as json.

**Comment by beckettsean** [comment]
This is most likely an nginx configuration issue. If nginx is stripping the headers that would remove the required version info before it gets to the client. The `X-InfluxDB-Version` value must be preserved.
