### ISSUE TITLE
Cannot query points in the future

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2551]
Points can be written with timestamps in the future, but those points do not return within aggregations or as individual points when queried. As soon as their timestamp is in the past they start returning in queries.

To repro (assuming it is now epoch 1431467300):
1. write points to a new series with timestamps of 1431467400, 1431467460, and 1431467520 
2. query a count of the points in the series
3. before 1431467400 the count is 0. Between 1431467400 and 1431467460 the count is 1. Between 1431467460 and 1431467520 the count is 2. After 1431467520 the count is and remains 3.

Adding or excluding a time portion in the WHERE clause has no effect on the results.

**Comment by beckettsean** [comment]
Adding a `WHERE time < now() + 1d` to the query does return the points. 

Closing issue, flagging for documentation.

**Comment by pga23** [comment]
thx
