### ISSUE TITLE
User interface SyntaxError in Chrome

### ISSUE THREAD

**Issue by felixrabe** [influxdb/influxdb#2556]
I've installed InfluxDB 0.8.8 via `brew install influxdb` on OS X 10.9.5.

When navigating to http://localhost:8083/ in Chrome (42.0.2311.90 (64-bit)) I get a nonfunctional interface with a lot of placeholders and a SyntaxError in the console:

![screen shot 2015-05-13 at 09 17 59](https://cloud.githubusercontent.com/assets/400795/7605535/fd34e3fa-f950-11e4-8d43-a334e39eade4.png)

Firefox (37.0.2) works fine and looks as shown in http://influxdb.com/docs/v0.8/introduction/getting_started.html#logging-in-and-creating-your-first-database (interestingly using Chrome in that screenshot).

**Comment by felixrabe** [comment]
InfluxDB is running using `influxdb -config=/usr/local/etc/influxdb.conf` and the default configuration provided in the Homebrew formula.

**Comment by toddboom** [comment]
@felixrabe can you try doing a hard refresh in the browser (or opening it up in an incognito window)? the assets are statically compiled into the binary and that version hasn't been changed in about 6 months.
