### ISSUE TITLE
High CPU system load when receiving Graphite metrics

### ISSUE THREAD

**Issue by spynode** [influxdb/influxdb#2561]
We have application sending Graphite metrics through carbon-c-relay to InfluxDB 0.9.0 RC29, RC30 database in format e.g. env3.server6.app.internal.socket.latency.count (no naming pattern which would resemble key.value pattern), with standart InfluxDB setting # name-separator = "-", metrics were not received and in logs there were reported errors:

[graphite] 2015/05/06 12:08:47 unable to parse data: received "carbon.relays.idbtest.destinations.10_30_5_76:2003.wallTime_us" which doesn't conform to format of key.value.key.value.name or name

After changing InfluxDB setting to name-separator = " ", InfluxDB can receive data and it can be queried. Problem arises after short period of time, when CPU sys load goes up to 85% on the machine and we see following in InfluxDB log (several per second, could be on each received metric):

[graphite] 2015/05/07 12:39:40 failed to write data point to database "graphite": do: Post http://localhost:8086/messaging/messages?topicID=1&type=128: dial tcp 127.0.0.1:8086: cannot assign
requested address

InfluxDB still responds to queries and returns data, but is slower and whole system is under serious load until InfluxDB restart.

I am not sure if later error and InfluxDB overloading system is anyhow connected to it receiving Graphite metrics or this "workaround" setting name-separator = " ". Nontheless, how to configure InfluxDB to use whole series name, including dots, as a InfluxDB metric name? And of course, if this is not a bug, how to avoid InfluxDB problems with load, described above. 
I initially commented in #2310, but this doesn't look like the same issue.

Edit: There are 24526 connections in TIME_WAIT state. Could be that InfluxDB does not handle connections properly or perhaps Graphite mode connections in particular. It could be connected to #2310 after all.

Edit: Here is partial output from netstat -tn|grep TIME_WAIT:
```
tcp        0      0 127.0.0.1:48640             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:59550             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:48768             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:33611             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:49971             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:34761             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:38815             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:38597             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:53362             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:45795             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:41548             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:41256             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:55164             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:52887             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:48540             127.0.0.1:8086              TIME_WAIT   
tcp        0      0 127.0.0.1:58659             127.0.0.1:8086              TIME_WAIT   
```

Here is partial output from netstat -nptu:
```
tcp        0      0 127.0.0.1:44486             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:42942             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:37236             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:37269             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45971             127.0.0.1:8086              TIME_WAIT   -                   
tcp      142      0 127.0.0.1:53980             127.0.0.1:8086              ESTABLISHED 29850/influxd       
tcp        0      1 127.0.0.1:58926             127.0.0.1:8086              SYN_SENT    29850/influxd       
tcp        0      0 127.0.0.1:50732             127.0.0.1:8086              ESTABLISHED 29850/influxd       
tcp        0      0 127.0.0.1:57955             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:58281             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:52583             127.0.0.1:8086              TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44251             127.0.0.1:8086              TIME_WAIT   -     
```

**Comment by liyichao** [comment]
Have a look at https://github.com/influxdb/influxdb/blob/master/graphite/graphite.go. Influxdb expects graphite metric name with specific format.

**Comment by spynode** [comment]
But shouldn't there be an option to just use whole metric path as a metric name? As I wrote, when using name-separator = " ", metrics are saved and can be queried with full name like "carbon.relays.idbtest.destinations.10_30_5_76:2003.wallTime_us" or "injector.jvm.threads.new.count". Now the question is, what really is the reason of InfluxDB creating such a huge amount of connections? Could it be related to Graphite compat?

**Comment by lokeshverizon** [comment]
+1
we are also seeing big performance issue in 0.9.0-rc 30, vs 0.8.8.  With 0.9, we are seeing so many TIME_WAIT (56k+) while with 0.8.8 we are not seeing any TIME_WAIT.

**Comment by beckettsean** [comment]
@lokeshverizon Please upgrade to 0.9.0 final. RC30 is not a very relevant build at this point.
