### ISSUE TITLE
unable to fetch data when using group by 

### ISSUE THREAD

**Issue by yowenter** [influxdb/influxdb#2562]
Hi ,there,

Since I have a cadvisor  write data to influxdb (version 0.8) every 20s .
I write a continuous query ,"select * from stats into stats.docker.[container_name]" .

when I query a container's memory usage , I use "select mean(memory_usage) as memory_total  from stats.docker.xxxxmycontainernamexx  group by time(30s)  where time>xxxx s and time <xxx s "

 I can not get points . Is my query wrong ?

**Comment by beckettsean** [comment]
Your measurement name has periods in it. It must be double-quoted. For example:

`select mean(memory_usage) as memory_total from "stats.docker.xxxxmycontainernamexx" group by time(30s) where time>xxxx s and time <xxx s`

Your WHERE clause syntax might also be wrong but without an actual example I cannot be sure.

**Comment by yowenter** [comment]
Thanks for the explanation .
In fact ,I use "select mean(memory_usage) as memory_total from \"stats.docker.{container_name}" group by time(30s) where time>{end_time} s and time <{start_time}s".format(container_name=container_name,end_time=end_time,start_time=start_time)  in my program.
Both end_time and start_time  are int type .
I wonder if the group by interval (here is 30 s) is  small ,or the cadvisor writting to influxdb frequency (20s ) is low ?

**Comment by beckettsean** [comment]
I don't have much experience with CQs on 0.8. If you run the query directly, not as a CQ, do you get the expected results?
