### ISSUE TITLE
Error should be clearer when using illegal tag type

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2565]
Tag keys and values must be strings. The errors returned when violating that are somewhat cryptic. 

When trying to write a tag key that is a number, e.g. 

```
curl -XPOST 'http://localhost:8086/write' -d
{"database":"mydb",
"retentionPolicy":"default",
"points":[
     {
	"name":"myseries",
	"tags": {
		"name":"foo",
		1234:"bar"
	   },
	"timestamp":"2015-05-11T06:20:27.000Z",
	"fields": {
                "value":132.0}
     }
]}
```
the error that is returned is `{"error":"invalid character '1' looking for beginning of object key string"}`. I realize this is contextually driven, but any way we say {"error":"invalid character '1' looking for beginning of tag key string"}

When trying to write a tag value that is a number, e.g. 

```
curl -XPOST 'http://localhost:8086/write' -d
{"database":"mydb",
"retentionPolicy":"default",
"points":[
     {
	"name":"myseries",
	"tags": {
		"name":"foo",
		"numbername":1234.5
	   },
	"timestamp":"2015-05-11T06:20:27.000Z",
	"fields": {
                "value":132.0}
     }
]}
```
the error that is returned is `{"error":"json: cannot unmarshal number into Go value of type string"}`. It would be far more informative to tell the user something like `{"error":"tag value must be a string"}`

**Comment by neonstalwart** [comment]
the first case is invalid json - do you still think something should be done to handle it better?

**Comment by beckettsean** [comment]
@neonstalwart that's a good point and for now it's probably fine to leave it alone. When there are non-JSON ways to write to the db we should make sure those methods return informative errors on non-string tag keys.

**Comment by beckettsean** [comment]
JSON writes deprecated. closing
