### ISSUE TITLE
Question: 0.9 cluster guide

### ISSUE THREAD

**Issue by arunoda** [influxdb/influxdb#2571]
Current 0.9 documentation has done a good introduction to the how 0.9 clustering works. 

I'd like to know about how to setup it. Basically, I want know about how to setup configurations for that (to try out influxdb clustering). Is there any place, I can look more about it?

**Comment by beckettsean** [comment]
Clustering is still under significant development so the docs haven't been published yet. The influxdb/influxdb.org repo is where docs are maintained and would be an excellent place to raise an issue like this.

**Comment by arunoda** [comment]
Okay. Thanks.
