### ISSUE TITLE
ORDER BY seems not work why ?

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2574]
When a use the following query
SELECT * FROM access_log WHERE time >'2015-05-14 14:00:00' ORDER BY time desc limit 100

Results is sent always in asc mode, it seems it did not care about the ORDER BY Why ?

**Comment by ericjmiller** [comment]
InfluxDB is by default ordered in time descending order.

**Comment by dtouzeau** [comment]
Sure but 
SELECT * FROM access_log WHERE time >'2015-05-14 14:00:00' ORDER BY time desc limit 100
SELECT * FROM access_log WHERE time >'2015-05-14 14:00:00' ORDER BY time asc limit 100

give the same results

**Comment by neonstalwart** [comment]
duplicate #2022 - it's simply not implemented yet (assuming you're trying 0.9.0 RCs)

**Comment by toddboom** [comment]
@dtouzeau thanks for the report - @neonstalwart is correct though, it's simply not implemented yet. you can track #2022 for progress.
