### ISSUE TITLE
Should be able to do an aggregate without group by time and where time clause

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2577]
This query should work:

```sql
select sum(value) from redis_keys where time > '2014-12-31' and time < '2015-02-01' group by host
```

**Comment by toddboom** [comment]
It looks like this already works, but seems to produce a strange timestamp as a result. I think we just need to test and confirm behavior.

**Comment by dgnorton** [comment]
This works for me on the current master (8ade485)...
```
> select sum(value) from cpu where time > now() - 1h and time < now() - 30s
name: cpu
---------
time                            sum
2015-05-22T20:33:59.197576Z     68138
```

**Comment by dgnorton** [comment]
To clarify, it works with or without `WHERE` and/or `GROUP BY`.

**Comment by toddboom** [comment]
@pauldix can you clarify how you want the timestamp to behave if this isn't correct?

**Comment by pauldix** [comment]
That looks correct to me, assuming that the time was `1h` prior to when the query was actually executed.

**Comment by toddboom** [comment]
ok, closing this for now, since we've had multiple attempts at producing a problem with no results. we'll wait until there's an actual issue next time. ;)
