### ISSUE TITLE
Influxdb Slow Performance Issue

### ISSUE THREAD

**Issue by gitvegas** [influxdb/influxdb#2588]
Some times you want to query column X based on column Y condition (where Y > 100 or where city in ('NY') etc). So how would i do that if i have each column in a different table/series? Just one column per series? So right now i have 1 series with 10 columns and 15000 rows. Even a basic query select X from table1 WITHOUT ANY CONDITIONS is taking 20sec response time. Using Grafana to view, please suggest

**Comment by toddboom** [comment]
@gitvegas what version of InfluxDB are you running?

**Comment by gitvegas** [comment]
0.8.8, thanks for your reply

**Comment by gitvegas** [comment]
So are you suggesting i wait for 0.9 release?

**Comment by toddboom** [comment]
@gitvegas one of the major changes to v0.9.0 was the support of tags, which will give you much better performance on the exact type of query you're describing. however, I also think that trying to select 15,000 points into your browser is probably creating a lot of rendering overhead, which is likely also causing some of the performance problems you're seeing.

**Comment by gitvegas** [comment]
Thank you, will wait for 0.9.0 until then will try to keep the series limited to few columns, thanks for your reply
