### ISSUE TITLE
Drop series via regex

### ISSUE THREAD

**Issue by anthonywebb** [influxdb/influxdb#2591]
I see we can select or delete from tables matching a regex, but I dont seem to be able to drop a series from table names based on a regex.

My use case is I have a user who may have 10-15 tables tied to them all named something like (user1-table1, user1-table2, user1-table3, user1-table4, etc).  When the user leaves I would like to like to "drop series /user1-*/"

Is anything like this possible?

**Comment by beckettsean** [comment]
@anthonywebb there are no tables in InfluxDB but I think you are using them to refer to collections of series with the same measurement. I also assume you are referring to the 0.9 development versions, not  0.8.x.

The `DROP SERIES` and `DROP MEASUREMENT` commands do not currently accept regular expressions, but you can use `DROP SERIES` to drop multiple series within a measurement, or `DROP MEASUREMENT` to drop the entire set of series sharing that measurement. 

I think your data structure might be getting in the way of what you're trying to do. From what you've written, you might consider storing your data in `table1`, `table2`, etc. with `user=user1` as a tag rather than as part of the measurement name. That way you could trivially remove a user's data with `DROP SERIES FROM table1 WHERE user='user1'`

**Comment by anthonywebb** [comment]
Thanks for the message @beckettsean 

I am a paying customer of your influx cloud service.  Not sure which version you are running for hosted clients?

As for the data structure, I probably should revisit that at some point, however it does seem to be working.  What I have are a series of customers (say customer1 - customer3) and each customer has a series of sensors for which sensor values are stored.

So initially in talking with Todd (last year) he mentioned that having more collections with fewer data points would scale better.  What I did was this,
db-customer1-sensor1 (contains data points for this sensor)
db-customer1-sensor2 (contains data points for this sensor)
db-customer2-sensor1 (contains data points for this sensor)
db-customer3-sensor1 (contains data points for this sensor)
db-customer3-sensor2 (contains data points for this sensor)
db-customer3-sensor3 (contains data points for this sensor)

The only real issue I found was when say customer3 went away, I would like to purge his data from the system so I am not cluttering up the database with needless data.

Is there a more preferred way of structuring things that you would recommend I explore?

**Comment by beckettsean** [comment]
@anthonywebb my advice was for 0.9, the hosted systems are currently running v0.8.8. Therefore my schema advice does not apply, as tags don't exist in 0.8.x.

Have you looked at the docs for 0.8? http://influxdb.com/docs/v0.8/api/query_language.html#deleting-data-or-dropping-series seems to be exactly what you want.

**Comment by anthonywebb** [comment]
@beckettsean yea those are the docs I have been using, which is what prompted the question, customer3 leaves and I want to "drop series db-customer3-*" but I cant do it, so I was hoping for a good way to delete "series" when a customer leaves.  (I assume they are series, they are the collections of data I see when I run "list series", which was sort of analagous to a DB table in my mind)

0.9 looks like a big jump, any idea when it will land to hosted customers?

**Comment by beckettsean** [comment]
@anthonywebb I think that `DROP SERIES` does not allow regular expressions. You should be able to remove all points in all the affected customer series with something like `DELETE FROM /^db-customer3-*/ WHERE time < now()` 

Given your use case, perhaps each customer should be in a separate database? Then you would just drop that database when the customer's data is no longer relevant. Do you ever merge data from multiple customers?

0.9 will arrive for hosted customers in June, we anticipate. It is a significant alteration to the data structure, migration may be challenging depending on your 0.8 data structure.
