### ISSUE TITLE
How can I do a query like " select * from user_action where from='mobile' "?

### ISSUE THREAD

**Issue by weiyoung-zhou** [influxdb/influxdb#2597]
It always raises 
```
ERR: error parsing query: found FROM, expected identifier, string, number, bool at line 1, char 106
```

**Comment by beckettsean** [comment]
`from` is a reserved word in the query language. If you want to use it as an identifier you have to put it in double-quotes:

`select * from user_action where "from"='mobile'`

**Comment by beckettsean** [comment]
In general it's a good idea to avoid using reserved keywords as tag or field names. `select`, `from`, `where`, etc are all special words to the query parser.

**Comment by weiyoung-zhou** [comment]
I will take your advice. 
Thanks for your response. ^_^
