### ISSUE TITLE
InfluxDB 09: Feature Request: JSON time values as epoch numbers instead of date strings

### ISSUE THREAD

**Issue by torkelo** [influxdb/influxdb#2599]
I am not sure this is possible now. But it would be good to have an option to return epochs instead of full JSON Date strings. 

Reduces the response size and parse speed for browsers. 

![image](https://cloud.githubusercontent.com/assets/10999/7680798/669ec3de-fd6a-11e4-989e-aaaa63a46516.png)

In InfluxDB 0.8 it was epochs not sure why this was changed. It is not a big issue for me, but would be a nice to have.

**Comment by pauldix** [comment]
For response size, GZIP should help with that. What are you seeing in terms of the network traffic?

On parse speeds, do you have any numbers of parsing date strings vs. epochs?

This can probably be added at some point without too much work. Just curious what the level of pain is on this feature.

**Comment by torkelo** [comment]
I do not have any benchmarks or stats but can imagine that the deserialization will take longer and take more memory. Also worried about memory in general, grafana slows down during browser GC and so need to conserve memory :)

**Comment by dswarbrick** [comment]
Date string parsing is 46% slower than epoch numbers, on my browser - http://jsperf.com/date-parsing-string-vs-epoch-number

**Comment by pauldix** [comment]
This seems pretty easy to do and I know we have a few cycles while waiting for me to finish some query engine refactoring for the new clustering design. @dgnorton, can you have a look?

I'm thinking this should be done through a single query parameter named `epoch`. For instance `epoch=ms`, which would tell us to return all times as millisecond scale epochs.

Should support `ms`, `us` - micro, `ns` - nano, and `s` - second.

**Comment by torkelo** [comment]
That sounds great.
