### ISSUE TITLE
Panic during "create data node"

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2604]
[server] 2015/05/18 16:59:52 retention policy 'default' auto-created for database 'mydb'
[messaging] 2015/05/18 16:59:53 connected to broker: http://:41974/messaging/messages?index=0&streaming=true&topicID=2
2015/05/18 16:59:53 http: panic serving 127.0.0.1:52141: runtime error: invalid memory address or nil pointer dereference
goroutine 7147 [running]:
net/http.funcÂ·011()
	/usr/local/go/src/net/http/server.go:1130 +0xcc
github.com/influxdb/influxdb/httpd.(*Handler).serveCreateDataNode(0xc208183f40, 0x7f7c0587aea8, 0xc208a1ae80, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:703 +0x634
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveCreateDataNode)Â·fm(0x7f7c0587aea8, 0xc208a1ae80, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:72 +0x53
net/http.HandlerFunc.ServeHTTP(0xc208099880, 0x7f7c0587aea8, 0xc208a1ae80, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/influxdb/influxdb/httpd.funcÂ·005(0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:941 +0x2e0
net/http.HandlerFunc.ServeHTTP(0xc208099a20, 0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/influxdb/influxdb/httpd.funcÂ·006(0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:950 +0xe4
net/http.HandlerFunc.ServeHTTP(0xc208a1aa80, 0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/influxdb/influxdb/httpd.funcÂ·007(0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:983 +0x494
net/http.HandlerFunc.ServeHTTP(0xc208099a60, 0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/influxdb/influxdb/httpd.funcÂ·008(0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:993 +0x1cb
net/http.HandlerFunc.ServeHTTP(0xc208099a90, 0x7f7c0587add0, 0xc208a1ae20, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/influxdb/influxdb/httpd.funcÂ·010(0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:1011 +0x17d
net/http.HandlerFunc.ServeHTTP(0xc208a1aaa0, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1265 +0x4f
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc2084d1098, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/bmizerany/pat/mux.go:109 +0x349
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc208183f40, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/httpd/handler.go:189 +0x6b
github.com/influxdb/influxdb/cmd/influxd.(*Handler).serveData(0xc208145120, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:106 +0x313
github.com/influxdb/influxdb/cmd/influxd.(*Handler).ServeHTTP(0xc208145120, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:65 +0x661
net/http.serverHandler.ServeHTTP(0xc2084b3b60, 0x7f7c05877b00, 0xc2084c7d60, 0xc20840dad0)
	/usr/local/go/src/net/http/server.go:1703 +0x1f7
net/http.(*conn).serve(0xc208059c20)
	/usr/local/go/src/net/http/server.go:1204 +0x1088
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x3cd
2015/05/18 16:59:53 join: failed to connect data node: http://:36621: Post http://:42717/data/data_nodes: EOF
2015/05/18 16:59:53 join: failed to connect data node to any specified server

**Comment by otoolep** [comment]
@benbjohnson @corylanou @jwilder 

Hit this during testing on Circle.

**Comment by otoolep** [comment]
https://circle-artifacts.com/gh/influxdb/influxdb/2528/artifacts/1/tmp/circle-artifacts.E9qRzAR/test_logs_race.txt

**Comment by otoolep** [comment]
The line that blew up is:

` = json.NewEncoder(w).Encode(&dataNodeJSON{ID: node.ID, URL: node.URL.String()})`

**Comment by corylanou** [comment]
It actually isn't that line that blew up, if you look it's really here:

http://golang.org/src/net/http/server.go#L1130

Which likely means it was a closed http connection.  Sounds related to network pressure or dropped connection.  Not something I think we can fix or check for in our code.

**Comment by corylanou** [comment]
Closing this as it's likely a circle environment issue and not our code base.
