### ISSUE TITLE
v0.8: merge series very slow

### ISSUE THREAD

**Issue by jverdeyen** [influxdb/influxdb#2607]
Hi,

I'm using Grafana to graph my InfluxDB query results.

```
select mean(value) from merge(/prod.site.response_time.*.*.timer.upper/) where $timeFilter group by time($interval) order asc
```

Where ` *.* = controller.action`

I'm using this merge to get all the values combined into one value (for Grafana).
I'm showing the lower, mean and upper. For a 6h timespan, it's pretty slow, for a 12h timespan the InfluxDB crashes.

I'm running this on a Digital Ocean Droplet: 2GB RAM, 2 CPU.
Ubuntu 14.04.

```
root@stats:~# influxdb -v
InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
```

Can I work this out in a better way? Should this be better in 0.9?

Thanks!

**Comment by beckettsean** [comment]
How many points are you graphing? How many series match the regex? In order to do the merge all of them have to be loaded into RAM. Are you hitting RAM limits on the box? What are the log lines when it crashes?
