### ISSUE TITLE
_orig_series with merge(/events.*/) type queries returns a single random series

### ISSUE THREAD

**Issue by joerodriguez** [influxdb/influxdb#2611]
Hello,

We are using v0.8.8 on customers.influxdb.com. The merge function seems to return a single series only. We're not sure how it's choosing the series, but it is the same for every record returned.

insert into events.1
insert into events.2

select * from merge(/events\..*/);

The resulting _orig_series values don't differ.

**Comment by beckettsean** [comment]
Can you provide some sample data? The merge function is known to work as expected for most cases and the code has not changed for months. It seems likely to be something specific to your implementation but without sample data it's hard to know what's going wrong.
