### ISSUE TITLE
"error: series not found" should panic the db

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2613]
See #2512 for details, but the error `{"error":"series not found"}` should be unreachable code and thus should panic if raised.

**Comment by otoolep** [comment]
@beckettsean -- RC29 was very different code. I doubt this issue applies any more. I'm closing it, but please re-open if I am mistaken.

**Comment by beckettsean** [comment]
@otoolep Agreed. This was also an issue no one could recreate, including the user who filed the original issue
