### ISSUE TITLE
there is little result from join, version 0.8.8

### ISSUE THREAD

**Issue by wangbin83-gmail-com** [influxdb/influxdb#2616]
There is supposed to have many result. How should I set the time field, can make it work well?

**Comment by beckettsean** [comment]
@wangbin83-gmail-com for general advice with InfluxDB, especially version 0.8.8, please contact the mailing list at influxdb@googlegroups.com.

For specific issues with 0.8.8, please provide example data points, example queries, and relevant log file entries. There is not enough information in your question for us to provide an answer.
