### ISSUE TITLE
Drop database and re-create database with same name retains old data

### ISSUE THREAD

**Issue by deebs031** [influxdb/influxdb#2617]
In testing & learning how to use influxDB I did the following 5+ times:
create database WaitEvents
load data
query
drop the database using the UI under Databases and select "x" to delete.

This was repeated over several days of learning/testing...

Yesterday I re-created the database (same name) and loaded data using an automated cronjob and found a mess when issuing this query this morning:

select * from /.*/ where time < now() - 1h

This morning I see data from two days ago (date -d +@1431976800 = Mon May 18 15:20:00 EDT 2015) which an old series data with old column list and data mapped to my current series column names.

I could be using the system wrong though, so any guidance would be appreciated.

Here is a curl sample I use:

curl -X POST -d '[{"name":"DGW3KML1.YES4.os thread startup","columns":["time","sequence_number","wait_class","total_waits","WC_total_waits","PCT_total_waits"],"points":[[1432133753,1260,"Concurrency","2","3","66.4"]]}]' 'http://192.168.1.121:8086/db/WaitEvents/series?u=root&p=root&time_precision=s'

Dave

**Comment by deebs031** [comment]
When I created a new database with a new database name everything came out as expected.

**Comment by deebs031** [comment]
I saw the same behavior with creating and dropping continuous queries... Will test on 0.9...

**Comment by beckettsean** [comment]
@deebs031 thanks for investigating on 0.9, do report any issues you find. The 0.8.8 branch is not going to have any more code changes.
