### ISSUE TITLE
v0.8.8 - merge fails for certain regex

### ISSUE THREAD

**Issue by skeller047** [influxdb/influxdb#2629]
We are testing influxdb as a "Graphite replacement", using the Graphite input plugin.  I'm having trouble merging the results of collectd input (via the collectd Graphite write plugin) to get an aggregate CPU value.

If I run this query:

`select mean(value) from /^collectd\.myhost_my-company_com\..*\.cpu-idle/  group by time(1m) where time > now() - 1h;`

I get a series for each CPU core in the host in question. 

If I change this to:
`select mean(value) from merge(/^collectd\.myhost_my-company_com\..*\.cpu-idle/)  group by time(1m) where time > now() - 1h;`

This is the same query but merging into a single series, it returns the dreaded "ERROR: cannot find user root" error.

Merge works fine when using a different series:  
`xxxx.gaps.gap_test.data01, data02`, etc. - using the regex `/^xxxx\.gaps\.gap_test\..*/`

This installation is a cluster of 2 machines, our Graphite test cluster, both very beefy (24 cores, 128 GB RAM, 1 TB of attached storage each).  They are running Centos 6.4 64-bit.

I understand this may become "Obsoleted by 0.9.x", but it seems to me this should work.  The regex is correct, and influxdb clearly understands it.  Why should merge not work the same way?

Thanks,
Steve Keller

**Comment by skeller047** [comment]
Once submitted, the above seemed to remove all the "\" characters.  Each dot (".") in the above, except the ones followed by "*" is escaped properly.

**Comment by beckettsean** [comment]
@skeller047 use backticks to delineate code (see the Markdown supported docs for details) and it won't remove the escapes. I've edited your comment to do just that. Please make sure I didn't change any meanings.

**Comment by skeller047** [comment]
That works, thanks Sean!

**Comment by beckettsean** [comment]
Strange as it may seem, our best advice is to downgrade to version 0.8.3 (http://influxdb.com/download/). The `merge` functionality changed between 0.8.3 and 0.8.8 and not to everyone's liking. It is probable that the earlier version will behave as you wish. They are otherwise fairly similar in functionality, as far as I am aware.
