### ISSUE TITLE
Calculate per query statistics

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#263]
More specifically, for a given select query:

1. Time took to run the query (possibly slow queries can make it to a slow log)
1. Memory consumed by a given query (probably just an estimate)
2. Shards hit by a given query
3. Local aggregation flag
4. Number of points read from each shard
5. Number of servers hit
6. Number of points returned from each server

**Comment by Ynguibjoerg** [comment]
+1
Would also be cool if this worked for "list series" commands aswell.

**Comment by beckettsean** [comment]
closing in favor of #2044
