### ISSUE TITLE
Continuous Query fanout causes panic

### ISSUE THREAD

**Issue by annymsMthd** [influxdb/influxdb#2630]
query: 
`CREATE CONTINUOUS QUERY availability_customer2_overall_30m ON statsd BEGIN SELECT sum(available) as available, sum(nonavailable) as nonavailable, customerId INTO "availability.customer.[customerId].30m" FROM "statsd"."default"."availability" group by time(30m), customerId END`

webcall: `http://prd-influx-1:8086/query?database=statsd&q=CREATE CONTINUOUS QUERY availability_customer2_overall_30m ON statsd BEGIN SELECT sum(available) as available, sum(nonavailable) as nonavailable, customerId INTO "availability.customer.[customerId].30m" FROM "statsd"."default"."availability" group by time(30m), customerId END`

```
panic: runtime error: index out of range

goroutine 180863 [running]:
github.com/influxdb/influxdb.(*Server).convertRowToPoints(0xc208076200, 0xc209d815c0, 0x22, 0xc2091d2120, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:4061 +0x7b7
github.com/influxdb/influxdb.(*Server).runContinuousQueryAndWriteResult(0xc208076200, 0xc2099c3880, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:4013 +0x158
github.com/influxdb/influxdb.(*Server).runContinuousQuery(0xc208076200, 0xc2099c3880)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3992 +0x8c1
github.com/influxdb/influxdb.func·050(0xc2099c3880)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3941 +0x34
created by github.com/influxdb/influxdb.(*Server).RunContinuousQueries
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:3942 +0x269

goroutine 1 [chan receive (nil chan), 21 minutes]:
main.(*RunCommand).Run(0xc20803d380, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/run.go:264 +0x806
main.main()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/cmd/influxd/main.go:81 +0x495
```

**Comment by annymsMthd** [comment]
More info: the customerId is a tag

**Comment by annymsMthd** [comment]
Running: `http://prd-influx-1:8086/query?database=statsd&q=select customerId as customerId, sum(available) from "statsd"."default"."availability" group by customerId`

Gives:
`{
	"results": [{
		"series": [{
			"name":"availability",
			"tags":{"customerId":"1"},
			"columns":["time","customerId","sum"],
			"values":[["1970-01-01T00:00:00Z",0]]
		}]
	}]
}`

looks like the tag is not in the columns group where the continuous query is looking for it

**Comment by beckettsean** [comment]
@annymsMthd can you provide a sample statement for writing points to this series? It helps to understand how the data in `availability` is organized.

**Comment by beckettsean** [comment]
Believed fixed by https://github.com/influxdb/influxdb/issues/2499, please try with RC31.
