### ISSUE TITLE
RC31 Cluster Completely Halts

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#2639]
I upgraded our 3 node cluster to RC31 today.  It appears that after a few minutes a node in the cluster completely halts, the process continues to run, however absolutely no log messages are issued indicating reads/writes are attempted against the database.  I completely reinstalled influx on all nodes, wiped the raft an DB directories.  I'm not entirely sure how to provide more information since there is a lack of log messages.
Thanks!

**Comment by beckettsean** [comment]
RC32 has many clustering changes, please try with that once it is released.
