### ISSUE TITLE
Return 401 if authentication is enabled and there are no users

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2653]
The discussion from #2172 brought to my attention that if you have authentication enabled, but no users created, you're always authenticated.

Instead it should only allow the creation of a user, which would be given the root privilege by default.

If the request is to do anything other than create a user, it should return a 401 and specify: `no users exist. create a user first or disable authentication.`

**Comment by corylanou** [comment]
I think the best spot to check this is here:

https://github.com/influxdb/influxdb/blob/master/server.go#L3719

I'm also wondering if this even makes sense then:

https://github.com/influxdb/influxdb/blob/master/httpd/handler.go#L886

If we are going to delegate all authentication to the database, the http endpoint should probably just stay out of it and only pass in the username/password if present, and not do any validation past that.  In effect, allow the server to determine what is allowable, not the http endpoint.

If we do that, then we have to somehow wrap in auth to this endpoint which assumes someone upstream has already done it:

https://github.com/influxdb/influxdb/blob/master/httpd/handler.go#L455
