### ISSUE TITLE
Dropping series causes influxdb to return null when query series with same retention policy

### ISSUE THREAD

**Issue by itachi90** [influxdb/influxdb#2659]
I'm sending Jmeter POST request to influxdb 0.9.0-rc30 with a speed 12K req/s, and doing a count query meanwhile to see how many points have been written to influxdb. The count query result is increasing with a speed of 2K/s. After I stop sending POST requests(count result is still increasing), and drop the series(DROP SERIES WHERE host = 'xxx'), the influxdb will return null on all series using the same retention policy even I restart sending POST requests and influxdb returns 204. If I create a new retention policy, and write points using the new one, there is no issue.

**Comment by beckettsean** [comment]
Can you provide a sample of the actual data and the exact queries you are submitting? That will greatly assist us in reproducing the correct issue.

**Comment by itachi90** [comment]
We are using Jmeter to send POST requests
POST /write
body 
{"database": "mydb","retentionPolicy": "${retention}","points": [{"name": "${metric1}","tags": {"host": "load_influx","region": "symantec"},"fields": {"value": ${__Random(0, 1000)}}}]}

Then drop series as:
drop series where host = 'load_influx'

**Comment by beckettsean** [comment]
believed fixed, please reopen if you can repro with 0.9.4
