### ISSUE TITLE
Issues with "select * from /.*/ limit 1" on newly created databases, fails for those created prior to RC30(?)

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2664]
I recently noticed that the query `select * from /.*/ limit 1` fails on some of my local databases. It has also been independently reported to support@ by another user.

I don't yet have a repro case, but in both cases I did have it appeared that the regex somehow pulled in a tag key, given the error messages:

```
> use mydb
Using database mydb
> select * from /.*/ limit 1
ERR: unknown field or tag name in select clause: boolean
```

For that database the first tag key on the first series (sorted alphabetically) was "boolean". Here's a better example using a different database:

```
> use mon
Using database mon
> select * from /.*/ limit 1
ERR: unknown field or tag name in select clause: alarm_id
> show series
name: alarm_state_history
-------------------------
_id	alarm_id				tenant_id
48895	<snip>	<snip>
```

When I dropped and recreated the `mydb` database with identical data I was unable to reproduce the error. The `select * from /.*/ limit 1` query worked as expected every time. 

I know that the `mon` database was created before I upgraded from RC27 to RC30 and I believe the same was true of the `mydb` database. All databases newly created on RC30 work as expected with that query.

**Comment by toddboom** [comment]
Not sure what happened to cause this, but I'm going to close it out since it's fixed now and nobody else has reported it.
