### ISSUE TITLE
"select * into xx from yy" doesn't work

### ISSUE THREAD

**Issue by jasper-zhang** [influxdb/influxdb#2668]
hi, I execute the statement like "select * from yy", I can get the data, but when use "select * into xx from yy", then I can't get data from xx. It looks like that "into"  can't work?

**Comment by jasper-zhang** [comment]
adding, my version is rc29.

**Comment by toddboom** [comment]
@jasper-zhang thanks for reporting this! i think this is a dupe of #1493, so i'm going to close it out for now, but keep an eye on that issue for progress!
