### ISSUE TITLE
InfluxDB v0.9.0-rc31 on FreeBSD hangs after a while

### ISSUE THREAD

**Issue by syepes** [influxdb/influxdb#2669]
Hello,

I have been testing [InfluxDB on FreeBSD](https://github.com/syepes/FreeBSD-Ports/tree/master/databases/influxdb) and in the last days its been hangs.

Currently I don't know if this is a FreebSD related problem or not, has anyone else seen this kind of isseu?

https://forums.freebsd.org/threads/cleaning-up-an-unkillable-process-influxdb.51783/

**Comment by beckettsean** [comment]
@syepes I haven't seen any other reports of an unkillable `influxd` process. I would guess it's likely specific to FreeBSD, especially since we haven't done any specific testing on FreeBSD or built any official packages for that OS. 

What is in the InfluxDB logs?

**Comment by syepes** [comment]
>What is in the InfluxDB logs?

I have another example that just happened [this week-end](https://forums.freebsd.org/threads/cleaning-up-an-unkillable-process-influxdb.51783/) this time I was running version e5e4b898

[broker] 2015/05/30 20:36:03 executing truncation check for 5 topic(s)
[srvr] 2015/05/30 20:36:04 retention policy enforcement check commencing
[broker] 2015/05/30 20:46:03 executing truncation check for 5 topic(s)
[srvr] 2015/05/30 20:46:04 retention policy enforcement check commencing

The strange thing is that this randomly and sometimes this happens event without inserting data.
