### ISSUE TITLE
[0.9.0-rc31] Unable to write point

### ISSUE THREAD

**Issue by JauntyWard** [influxdb/influxdb#2679]
Using the Go Influx API and Influx 0.9 rc31 I am unable to write points to the database. When using code adapted from the API documentation, the following error occurs on the write:

```
json: cannot unmarshal number into Go value of type struct { Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }
```

What am I doing wrong?

**Comment by toddboom** [comment]
@JauntyWard can you send us an example of the code you're using?

**Comment by JauntyWard** [comment]
@toddboom Sure, below is an example of my code. Thanks.

```go
type bucket struct {
	Name      string            
	Timestamp string            
	Tags      map[string]string 
	Fields map[string]interface{} 
}

func writeInfluxDB(buckets []bucket, influxConnection *client.Client, config influxDBConfig) {
	var (
		points      = make([]client.Point, len(buckets))
		pointsIndex = 0
	)

	for k := range buckets {
		bucket := buckets[k]

		points[pointsIndex] = client.Point{
			Measurement: bucket.Name,
			Tags:        bucket.Tags,
			Fields:      bucket.Fields,
			Time:        time.Now(),
		}
		pointsIndex++
	}

	pointsBatch := client.BatchPoints{
		Points:          points,
		Database:        config.influxDatabase,
		RetentionPolicy: "default",
	}

	_, err := influxConnection.Write(pointsBatch)
	if err != nil {
		fmt.Println(err)
	}
}
```

**Comment by aviau** [comment]
@toddboom 

I don't know if this is related, but I cannot write points on ``0.9.0-rc31``:
I get the following error: ``InfluxDBClientError: 500: {"error":"bucket name required"}``

This is the points i'm sending:

```
[ 
    {
        "measurment": "cpu_load_short",
        "tags": {
            "host": "server01",
            "region": "us-west"
        },
        "time": "2009-11-10T23:00:00Z",
        "fields": {
            "value": 0.64
        }
    }
]
```

**Comment by beckettsean** [comment]
@aviau there's a syntax error in your examples, the correct spelling is measur**e**ment, not measurment. It's wrong in both snippets, but the lack of a measurement name should render a point invalid, as the database has no way of determining to which series the point belongs. I cannot explain why the second JSON block would be accepted as a valid point.

**Comment by JauntyWard** [comment]
For me, both of the examples from @aviau with measurement spelled correctly (or indeed spelled incorrectly) yields a result of  "400: {"error":"json: cannot unmarshal object into Go value of type []client.Point"}"

If, however, I am to use the following JSON:

````
 [
    {
        "measurement": "cpu_load_short",
        "tags": {
            "host": "server01",
            "region": "us-west"
        },
        "timestamp": "2009-11-10T23:00:00Z",
        "fields": {
            "value": 0.64
        }
    }
]
````

The result is "500: {"error":"bucket name required"}". However if I change measurement to name. It writes successfully.

**Comment by aviau** [comment]
@beckettsean 

Wierd.  Using ''name'' works.

**Comment by beckettsean** [comment]
Given the write path changes between RC31 and RC32 I think we can close this issue. Please re-test with the impending RC33.
