### ISSUE TITLE
Should support columns that are arrays of values

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#268]
Should be able to write in for a data point:

```json
{
 "value": 232,
 "tags": ["asdf", "bar"]
}
```

So you can then do queries that group by on those column names. Also do queries that match against points that contain given values in that column. Discussion here: https://groups.google.com/forum/#!topic/influxdb/2dYqF0fCGX4

**Comment by k2xl** [comment]
+1

**Comment by dashesy** [comment]
+1

**Comment by cbenaveen** [comment]
+1

**Comment by beckettsean** [comment]
data format has changed significantly enough in 0.9.0 it is unclear if this is the best solution to the underlying needs

**Comment by llmuculusll** [comment]
+1

**Comment by cblomart** [comment]
+1

**Comment by gylu** [comment]
+1

**Comment by ctaity** [comment]
+1

**Comment by givo** [comment]
+1
