### ISSUE TITLE
Using derivative or difference causes influxdb to stop functioning (0.9 rc30)

### ISSUE THREAD

**Issue by kurtharriger** [influxdb/influxdb#2685]
We were trying to port some dashboard we prototyped in grafana for influx 0.8 to influx 0.9 and grafana 2.

One such dashboard attempted to run the following query:
```
select derivative(value) from /^collectd.interface.*.if_octets.*/ where time > now() - 1h and ... group by time(1m) 
```
This query does return "successfully" stating basically that the function is not implemented:  
{"results":[{"error":"function not found: \"derivative\""}]}

However, after running this query a few times will everything stop working and we start getting gateway timeout errors.  It does seem that some queries do still execute if they can connect, but for the most part influxdb is dead.  

Tailing the logs does not reveal any errors and there are still are some 204s responses from our data ingestion agents, but the frequency is substantially less and it appears clients are unable to connect.  

After restarting influxdb we can run queries again and there do not appear to be any new metrics from the point at which it stopped functioning.

**Comment by beckettsean** [comment]
DERIVATIVE was not wired up in RC30. It's available in RC31, please update to that version and try again.

See the [Changelog](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v090-rc31-2015-05-21) for more details

**Comment by kurtharriger** [comment]
Thats great, but what about difference?

I was more concerned that a user could easily lock up influxdb running simple queries from grafana then the function not yet being implemented.  I assume the issue probably still exists using difference.

**Comment by beckettsean** [comment]
@kurtharriger My apologies I read the examples which were all derivative and missed the note about difference in the issue title. DIFFERENCE is also not yet wired up: https://github.com/influxdb/influxdb/issues/1825. 

Regardless I was unable to lock up my RC31 instance with repeated DERIVATIVE or DIFFERENCE queries. Can you post the relevant log lines from when the database locked up?

**Comment by beckettsean** [comment]
Also, is the database unresponsive to all queries, even those from the CLI or from curl, or is it just grafana giving the gateway timeout errors?

It seems likely #2557 is relevant. Again, please try to recreate with RC31.

**Comment by kurtharriger** [comment]
I am able to reproduce the issue on rc31 with the difference operator using only curl from localhost.
I did need to repeat the command several times before it would hang, but it always does after enough tries.  

I recorded a screencast that demonstrates the issue I'm seeing which you can find here: 
https://youtu.be/zIrmewtTpu8

At first I assumed maybe connection wasn't closed and future clients would fail to connect, but after a bit more testing that does not appear to be the case.  I can still consistently run show measurements, but all other queries appear to fail.  

In the video the is nothing interesting in the logs and it appears that ingestion still continues. However, any metrics received after lock up are do not appear for several minutes after restarting.  Strangely, they do not appear to be lost as when the do fill in the shape of the data looks pretty normal.

I would speculate that this that maybe the data is being logged but not available for query until all the indices and such are updated but this is awaiting some lock which doesn't get released until after the server is restarted and the logged data can be processed.... or maybe not, but that's my theory. 

Are there any metrics that would tell long it took from receiving the data for the data to become queryable?

**Comment by beckettsean** [comment]
@kurtharriger Thank you very much for trying with RC31. I am still unable to repro on my end even with my system under heavy write load. What OS are you running? Can you provide a sample curl statement? Here's what I've been sending:
```
 curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=mydb" --data-urlencode "q=select difference(value) from /^exp.*/ where time > now() - 3w group by time(1m)"
```
That returns the function not found error for difference, but nothing bad seems to happen to the database. 

@pauldix is this perhaps a symptom of the multiple locks issue you discussed this morning at standup? If so, are those locks removed from what will be RC32?

**Comment by pauldix** [comment]
@beckettsean this is probably unrelated to the query being a derivative or difference. Most likely something else. But yes, it sounds like it's related to the locking issue I was talking about at standup. RC32 should resolve this if it's still happening in RC31.

**Comment by beckettsean** [comment]
Thanks, @pauldix. @kurtharriger I think your analysis is correct that this is all due to a locking issue with queries. The data is writing just fine but the querying doesn't catch up after the locking happens. RC32 has fewer lock statements in the code so hopefully will eliminate this issue.

**Comment by beckettsean** [comment]
Can you try with RC33, which will be released imminently?

**Comment by kurtharriger** [comment]
Unfortunately we were unable to keep influxdb running long enough to provide enough value to justify the resoureces.  We decided to reevaluate in another quarter or so.  I should have stopped the instance, but I deleted it. So unfortunately I cant retest without reinstalling.

You can close this issue whenever you feel that it has been fixed.
