### ISSUE TITLE
Influx 0.9rc31 eat all server performance

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2689]
Hi
We have a server that stores 9GB of data and eat memory with a 5.0 of load
![influxeat2](https://cloud.githubusercontent.com/assets/280586/7881774/c6f0b824-0606-11e5-9a36-fc938b86ee81.jpg)
Is it normal ?
How can i help you about fixing this issue ?

**Comment by toddboom** [comment]
@dtouzeau can you tell us a bit more about what's going on with the server while this is happening? what sort of writes and queries are being performed?

both the read and write paths are being modified heavily for RC32. i'd like to see what this looks like once that version is released next week, but answers to the questions above would be very helpful.

**Comment by dtouzeau** [comment]
Yeah! I'm monitoring latest versions each 10mn on your website!
Writes are million proxy requests with strings like IPADDRESSES (string), usernames long string , hits (integer) , size (integer), domain (string) ,subdomain
all are fields

**Comment by beckettsean** [comment]
Try to repro with RC33, especially with the line protocol. The JSON parsing costs are huge for that volume of writes. Reducing that load should help significantly.

**Comment by beckettsean** [comment]
RC31 had only JSON protocol and different datastore structure. Changes in 0.9.0 final and forward should alleviate this load issue.
