### ISSUE TITLE
[0.9.0-rc31] Continuous query causes "index out of range" crash

### ISSUE THREAD

**Issue by toomanyjmikes** [influxdb/influxdb#2692]
Probably a problem with my code or CQ, but unable to see what I could be doing wrong. I have a continuous query (actually every one I've tried) that crashes upon the first attempt to execute with data (without data, I just get a missing measurement error, which makes sense). I have reproduced this with rc30 and rc31. rc28 did not crash (but the CQ didn't work either).

To reproduce, run the reproduction program (caution! it drops and recreates the database "cqtest") and wait until the next CQ run.

Reproduction program: https://gist.github.com/toomanyjmikes/982d804c61c88b52abbc#file-cqcrash-py

Log output: https://gist.github.com/toomanyjmikes/5ddf404cabf6b5d36ef1#file-cqcrash-log

Please let me know if there's anything further I can do to help with this.

**Comment by beckettsean** [comment]
@toomanyjmikes I'm curious what happens if the script partially populates the `ingest` measurement before the CQ is created. I also know there have been major write-path changes between RC31 and RC32 so please try to repro. I would actually hold off for the impending RC33, which should be out today.

**Comment by beckettsean** [comment]
I don't see anything syntactically wrong with the CQ, and I can create that just fine against one of my test databases. I was able to insert data into it as well with no errors or crashes. I'm testing with RC31, as well.

Please try to repro with RC33 as mentioned.
