### ISSUE TITLE
[0.9-RC30] influxd used up all memory and crash on starting up

### ISSUE THREAD

**Issue by nklizhe** [influxdb/influxdb#2708]
Server: Linode 16GB

I couldn't start the influxdb after the Linode power outage (the server reboot) today. The influxd process used up all memory and crash after a few minutes.

Log:
```
[srvr] 2015/05/30 08:45:48 GOMAXPROCS set to 8
[srvr] 2015/05/30 08:45:48 using configuration at: /etc/opt/influxdb/influxdb.conf
[srvr] 2015/05/30 08:45:48 influxdb started, version 0.9.0-rc30, commit acf2dd6ba5429e95ad6a156afe7afbdc6b861979
[srvr] 2015/05/30 08:45:48 Cluster server listening on [::]:8086
[srvr] 2015/05/30 08:45:49 broker opened at /var/opt/influxdb/raft
[raft] 2015/05/30 08:45:49 stopped[1]: log open: created at /var/opt/influxdb/raft/raft, with ID 1, term 1, last applied index of 668897
[raft] 2015/05/30 08:45:49 log open: promoting to leader immediately
[srvr] 2015/05/30 08:45:49 broker already member of cluster.  Using existing state and ignoring join URLs
[srvr] 2015/05/30 08:45:49 Loading metadata index for _influxdb
[srvr] 2015/05/30 08:45:49 Loading metadata index for xvca
```

I suspect this is related to: https://github.com/influxdb/influxdb/issues/2508

**Comment by beckettsean** [comment]
Possibly related to #2508 but it's hard to say. There are breaking changes to the datastore between RC30 and RC33, so there's no way to test with your current setup that it has been fixed. However the metastore changes in RC32+ should mitigate or eliminate this. It sounds like a raft consensus error, and those are more localized now.
