### ISSUE TITLE
Quick access queries in Influx Admin

### ISSUE THREAD

**Issue by baze-** [influxdb/influxdb#2712]
It would be useful if Influx Admin would provide quick access buttons to most common queries.

Illustration below:
![influx_admin_quick_queries](https://cloud.githubusercontent.com/assets/10771136/7898863/78edfc66-0716-11e5-96ea-c2601ddb2aa7.jpg)

Queries without question mark would be executed by clicking. Queries with question mark would copy the query to input field and set the cursor where the question mark is for faster editing.

**Comment by toddboom** [comment]
This is a great idea. I've included part of this with #2746, which should be shipped with v0.9.1. Thanks!
