### ISSUE TITLE
[0.9-rc31] Query containing =~ 'literal' crashes influxdb

### ISSUE THREAD

**Issue by kurtharriger** [influxdb/influxdb#2714]
I was testing some queries in the ui and things stopped working. Checked logs and found  the following stack trace.

The query I was experimenting with looked something like this, but probably unrelated to crash.
select * from "multiHistReport" where time > now() - 1h and eventDescription='component ready' and userAgent=~ /Chrome/ and pageHash= '_iterationstatus'  order by asc

goroutine 78212 [IO wait]:
net.(*pollDesc).Wait(0xc2163bd560, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2163bd560, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2163bd500, 0xc218978000, 0x1000, 0x1000, 0x0, 0x7f9f8efffdb0, 0xc21226fc58)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2149c9bf0, 0xc218978000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc20b486fe8, 0xc218978000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc20e4121c0, 0xc218978000, 0x1000, 0x1000, 0x2, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc214bac480)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc214bac480, 0xc20f5d9b0a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc214bac480, 0x0, 0x0, 0x0, 0xc207ae0300, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc20d1fc570, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc20d1fc570, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc214bac480, 0xc21afdf040, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc20b486fa0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc20b486fa0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

**Comment by kurtharriger** [comment]
Reproduced the issue with another query.  While trying to get regexs to work https://github.com/influxdb/influxdb/issues/2715 I was running a query containing =~ 'literal' instead of = 'literal' or ~= /expression/

The following consistently crashes influxdb:
select * from "descriptionsHistReport" where  eventDescription=~ 'dispatching artifacts_received' order by asc

**Comment by pauldix** [comment]
Can you post the very top lines of the stack track it outputs?

**Comment by dgnorton** [comment]
No need for extra info.  I know how to fix it.

**Comment by pauldix** [comment]
@dgnorton can you do the fix in the `alpha1` branch?

**Comment by dgnorton** [comment]
@pauldix  just in `alpha1` and not in `master`?

**Comment by pauldix** [comment]
Yeah, going to get `alpha1` merged in today or tomorrow. And the next RC will be off that, so no point in doing it off `master`

**Comment by pauldix** [comment]
Fixed in master.
