### ISSUE TITLE
[0.9-rc32] select * from .. should return tag values

### ISSUE THREAD

**Issue by kurtharriger** [influxdb/influxdb#2717]
After moving some columns from fields to tags it became pretty much impossible to determine the context of an event you can filter on them, but they are not included in the result.

The best workaround I have for now is to use group by and then inspect the resulting json. 
The UI does not currently creates a new table for each group, but it does not display the actual values of the group key just repeats the series name.

Another possible workaround is to also send the tags as fields, but then regex queries no longer work correctly.   https://github.com/influxdb/influxdb/issues/2715

**Comment by toddboom** [comment]
@kurtharriger this was already fixed in #1997 and will be included in RC32:
https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v090-rc32-unreleased
