### ISSUE TITLE
Series model for stocks historical data

### ISSUE THREAD

**Issue by FarzinZaker** [influxdb/influxdb#2718]
I am interested in using InfluxDB for storing and retrieving historical stocks data. Suppose that system has about 8k symbols and for each symbol about 100 Indicators should be stored and retrieved for about 20 years. 
First of all, I should know if InfluxDB is suitable for this requirement?
And second question is about series schema. one serie for each indicator? or one serie for each indicatior and each symbol? if I should implement first design model, how can I query for specific indicator values of an specific symbol without tags?

thanks in advance

**Comment by beckettsean** [comment]
This is not an actionable issue with the product and therefore not appropriate for GitHub Issues. Please use the mailing list influxdb@googlegroups.com to request schema advice and ask general product questions.
