### ISSUE TITLE
ORDER BY DESC queries should return an error

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2731]
queries that have any order other than `ORDER BY ASC` should return an error. These will be wired up at a later date, but until that time we should tell the user that it doesn't work (rather than returning incorrect results).

**Comment by otoolep** [comment]
This change will need to be reverted some time soon.

**Comment by dgnorton** [comment]
@otoolep is this issue obsolete now?

**Comment by otoolep** [comment]
Yes, all fixed right now -- thanks @dgnorton
