### ISSUE TITLE
Create a test harness for clusters

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2740]
Create a command line client that can launch a cluster or single server in the cloud and run scalability and performance tests against it.

**Comment by toddboom** [comment]
This will be written in Go.

**Comment by otoolep** [comment]
We've gone most of the way there with the work @mjdesa is doing. Since we're using Pivotal Tracker now for test stories, I don't think this ticket helps.

**Comment by mjdesa** [comment]
Created https://www.pivotaltracker.com/story/show/106875356
