### ISSUE TITLE
Client uses "measurement", httpd uses "name" still.

### ISSUE THREAD

**Issue by GeorgeMac** [influxdb/influxdb#2749]
I keep getting JSON decoding error responses when using the current client with the development version of influx. 

See: https://github.com/influxdb/influxdb/blob/c36cec70f22e1104634523d930df33502014d19f/services/httpd/handler.go#L497

I might be mistaken but shouldn't that now be unmarshalling `measurement` not `name`. I have only just started digging in to influx, so sorry If I am mistaken and doing something stupid! haha

**Comment by GeorgeMac** [comment]
Oh no I see that type isn't used. The client type is. 

The version in brew must still a version before the client changes. Ignore me!

Cheers!

**Comment by beckettsean** [comment]
@GeorgeMac to what specifically are you referring when you say "the current client". Most clients are not keeping pace with master yet. We expect 0.9.0 support to sync up with RC32 or RC33 when those are out.

**Comment by corylanou** [comment]
@GeorgeMac can you give us a more specific example of how/where you are seeing a failure?  I'm assuming you are referring to the client library in the `/client` package.  There was a bug a couple days ago, but I believe master is currently fixed.  Can you confirm that you still get this error using master?

Thanks!

**Comment by GeorgeMac** [comment]
Hey so I have just pulled the codebase and rebuilt everything.
Then from within my application I am sending this payload to influx:
```json
{
    "measurement":"performance",
    "tags": {
        "type":"1"
    },
    "time":"2015-06-04T09:39:51.854533808Z",
    "fields": {
        "value":66
    },
    "precision":"n"
}
```

I get the response:
```json
{
    "error" : "invalid character 'p' looking for beginning of value"
}
```

Sorry I didn't embellish on this sooner.

**Comment by spitfire2** [comment]
I got same error. 

I downloaded rpm from http://influxdb.com/docs/v0.9/introduction/installation.html

The go client is the newest version on github.

**Comment by beckettsean** [comment]
The rpm on the install page is currently RC31, not RC32. There are breaking
changes in between the two versions, so it's not surprising if the latest
client doesn't work with RC31.

On Mon, Jun 8, 2015 at 10:59 PM, Owen Zheng <notifications@github.com>
wrote:

> I got same error.
>
> I downloaded rpm from
> http://influxdb.com/docs/v0.9/introduction/installation.html
>
> The go client is the newest version on github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/2749#issuecomment-110234122>.
>



-- 
Sean Beckett
Director of Support and Professional Services
InfluxDB

**Comment by beckettsean** [comment]
Built-in Go client is now using the line protocol so this is moot.
