### ISSUE TITLE
Cluster size should be limited to 3 servers

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#2750]
For the 0.9.0 release, clusters will be limited in size to 3 servers. We'll start the work to lift this limitation on the 0.9.1 release cycle. But in the meantime, we should forcibly limit the number of servers in a cluster.

If the user starts up a new server and attempts to join a cluster that already has 3 nodes, it should exit with a failure stating that the 0.9.0 release limits clusters to 3 servers.

**Comment by tigerich** [comment]
When will be  0.9.1 out? 3-node cluster is not very useful in my case here. 

thanks,
R

**Comment by beckettsean** [comment]
@tigerich 0.9.2 has been released. See the [blog post](https://influxdb.com/blog/2015/07/23/InfluxDB-0_9_2_released-with-groundwork-for-clustering.html) for more on the state of clustering.

**Comment by tigerich** [comment]
thanks @beckettsean 

The release of 0.9.3 on August 13th will have support for clusters of arbitrary size with replication factors that are less than the number of servers. 

---looking forward to that
