### ISSUE TITLE
cannot give retention policy duration in nanoseconds

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2760]
Since we support retention policies specified in all other InfluxDB units (u, ms, s, m, h, d, w) we might as well support nanos, too.
 
```
> create retention policy foo on mydb duration 3600000000u replication 1
> create retention policy bar on mydb duration 3600000000000n replication 1
ERR: error parsing query: found 3600000000000, expected duration at line 1, char 46

> show retention policies mydb
name	duration	replicaN	default
default	0		1		true
foo	1h0m0s		1		false
```

**Comment by corylanou** [comment]
Supporting a retention policy under microseconds makes no sense.  I'm not sure why we even support anything other than seconds for an retention policy.  I'm assuming that by happy accident the parser can parse this.  I think the real fix is to:

- [ ] Support `n` as a duration and let it parse
- [ ] Error out with some type of `minimum duration` if you try to create a retention policy with a duration less than a minute or something like that.

**Comment by beckettsean** [comment]
@corylanou It does error out if you provide a duration less than 1 hour, thus the 3600000000 microseconds I specified in the example.
