### ISSUE TITLE
show retention policies should be consistent with other queries

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2761]
Right now the syntax is `SHOW RETENTION POLICIES <db-name>`, but `DROP RETENTION POLICY <rp-name> ON <db-name>`. For users it's `GRANT/REVOKE <privilege> ON <db-name>`

I think `SHOW RETENTION POLICIES ON <db-name>` is more congruent with the other statements, and I find myself typing ON every time and then removing it when the parser complains.

**Comment by corylanou** [comment]
We should support either way, but certainly +1 for the consistent manner.

**Comment by EvanDarwin** [comment]
+1

**Comment by dgnorton** [comment]
+10
@corylanou support both for backwards compatibility?

**Comment by corylanou** [comment]
@dgnorton If it's not too hard to support both, that's fine.  Many languages support variant commands.  I don't think that we really have to if we don't want to, so for me, it's a matter of what is easiest.

I support 2 versions of `select count(distinct(foo))` and `select count(distinct foo)` so it isn't like we haven't already broken the `there is only one way` rule :-).

**Comment by dgnorton** [comment]
@corylanou We support 2 versions of count distinct on purpose.  I think leaving `ON` out of `SHOW RETENTION POLICIES` was unintentional.  :)

**Comment by gunnaraasen** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3345
