### ISSUE TITLE
need a way to see user permissions per database

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2764]
I can `GRANT` and `REVOKE` permissions per user per database, but there's no way to list the permissions a user has except cluster admin vs. non-admin.

`SHOW USERS` doesn't give any database level permissions, only cluster permissions.

**Comment by gunnaraasen** [comment]
I think this is covered by #2212 and PR #2650.

**Comment by beckettsean** [comment]
agreed, closing.
