### ISSUE TITLE
`influxd` requires SIGINT to exit

### ISSUE THREAD

**Issue by gunnaraasen** [influxdb/influxdb#2768]
`influxd` will hang indefinitely when running the `config`, `help`, and `version` commands.

It seems to only be a problem with top level commands, `help [command]` works as expected.

**Comment by otoolep** [comment]
Confirmed -- I've seen this. The system should exit when passed `-h`.

**Comment by otoolep** [comment]
This is fixed. I don't know what fixed it, but I no longer see the behaviour I saw before.
