### ISSUE TITLE
[0.9.0-rc31] InfluxDB crashed when enable collectd and scan that port

### ISSUE THREAD

**Issue by ldkingvivi** [influxdb/influxdb#2772]
InfluxDB crashed when enable collectd and scan that port

I have tried version 0.88 and 0.9 rc-31 , both have the same issue, you can enable the collectd plugin, then run the command:

nc -vnzu x.x.x.x 25826

**Comment by beckettsean** [comment]
@ldkingvivi can you provide the log lines surrounding the crash?

**Comment by ldkingvivi** [comment]
the log shows clean, you should be able to repeat it right away

**Comment by ldkingvivi** [comment]
looks like the 0.9 stable just released today, I will give a try later today, see if the same issue still exists

**Comment by beckettsean** [comment]
Assumed fixed in 0.9.0.

**Comment by ldkingvivi** [comment]
please re-open this

you can reproduce this on the latest version right now, which is 0.9

Here's the only conf I made from default conf:

[collectd]
  enabled = true
  bind-address = ":25826"
  # database = ""
   typesdb = "/root/collectd/share/collectd/types.db"


netstat verify it's running on the port:

tcp        0      0 :::8083                     :::*                        LISTEN      28488/influxd
tcp        0      0 :::8086                     :::*                        LISTEN      28488/influxd
tcp        0      0 :::8088                     :::*                        LISTEN      28488/influxd
udp        0      0 :::25826                    :::*                                    28488/influxd

running command to scan the UDP port 25826:

 nc -vnzu 127.0.0.1 25826

then it crashed
