### ISSUE TITLE
Write API - Support sending parameters through POST

### ISSUE THREAD

**Issue by syepes** [influxdb/influxdb#2775]
With the introduction of the new [Line protocol](https://github.com/influxdb/influxdb/pull/2696) its no longer possible to send the parameters like: db,precision,rp... using POST.

It would be nice to have this feature back it makes the URL's cleaner.

**Comment by jwilder** [comment]
Not sure sure I understand, those parameters are required URL parameters still.

**Comment by corylanou** [comment]
Technically one is not harder than the other for a client to support, but it is technically harder for us to parse, so we will be sticking with params.

**Comment by syepes** [comment]
@corylanou  Ok I understand, but in contrary the user and passwd (u/p) would be nice to support basic authentication, this way the dons see them in the URL.

**Comment by corylanou** [comment]
That makes sense.  We should have the ability to authenticate the writes if authentication is turned on.

**Comment by jwilder** [comment]
Basic authentication should already work for this endpoint.
