### ISSUE TITLE
Please consider versioning the client package.

### ISSUE THREAD

**Issue by chakrit** [influxdb/influxdb#2781]
At the current state of things, the `client` package uses the new 0.9 protocol (posting to `/write` endpoint) which means:

* All calls would return 404 if run against influxdb 0.8 (the current production version) because `/write` endpoint doesn't yet exist.
* No way to manually `import "github.com/influxdb/influxdb"` and get v0.8-compat client. We are forced to use the master by go (which currently sends everything in v0.9-style)

So please consider making available version-specific client import path, either using gopkg.in if possible or just an exported folder like `github.com/influxdb/influxdb/client/v0.8` or whatever scheme you think is best.

Of course  forking the repo and resetting the master works, but that's just ugly and all updates are now manual instead of automatic.

**Comment by marcosnils** [comment]
@chakrit 0.8 is not getting updates or fixes at this moment as the guys from Influx are focusing entirely on 0.9. I'd say it's pretty safe to fork the repo as it's not likely to have any updates. 

If you check you'll see that the last commit in the v0.8.8 branch has been several months ago.

**Comment by gunnaraasen** [comment]
As @marcosnils mentioned, there is no more development on 0.8 so updates should not be a concern. Checking out the `v0.8.8` branch is the only way to use the 0.8 client package.

[gopkg.in](http://labix.org/gopkg.in) is not a viable option for importing v0.8.8. It only allows imports on major version numbers. While gopkg.in/influxdb/influxdb.v0 currently imports the v0.8.8 branch, it will automatically start importing v0.9.0 as soon as it is released.

**Comment by politician** [comment]
I'm surprised by this situation *and* answer - InfluxDB lacks a stable client for it's most recent stable server, but you can get one if you fork the repo and update your sources?

I was just casually browsing this repo this morning, but have realized that I've got v0.8.8 code that I can't rebuild now because it's pointing to the master client!

**Comment by jwilder** [comment]
You shouldn't need to fork the repo and update your source.  You can manage your client dependencies to ensure you build against the appropriate commit or tag using tools such as [godep](https://github.com/tools/godep), [glock](https://github.com/tools/godep) or vendoring the client libs.   godep and glock will manage the versions checked out under your `GOPATH` for you so you can just declare that your project depends on a specific version of the influxdb client and you won't be affected by changes to master.

**Comment by politician** [comment]
@jwilder That's the better answer - the inability of `go get` to facilitate reproducible builds aren't InfluxDB's problem.
