### ISSUE TITLE
Request RC32 on the download page

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#2782]
We have issues on performance, all our servers be loaded caused the Influxdb eat I/0 CPU 
![05-06-201510-02-06](https://cloud.githubusercontent.com/assets/280586/8002038/c976ae2c-0b6b-11e5-9a4d-5135de6288e1.png)

It seems that there are a lot of improvements on the RC32, is it possible to get it compiled in the deb package ?

**Comment by gunnaraasen** [comment]
@dtouzeau [rc32](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v090-rc32-unreleased) will likely be cut sometime today. Please test this again once rc32 is out and open a new bug report if you continue to run into performance problems.
