### ISSUE TITLE
Create default retention policy

### ISSUE THREAD

**Issue by gunnaraasen** [influxdb/influxdb#2791]
The `default` retention policy is no longer automatically created.

**Comment by otoolep** [comment]
For now I have updated the README so it reflects this:

https://github.com/influxdb/influxdb/pull/2797

Re-enabling auto-create of retention policies is not straightforward in the newer design. Not difficult, but not trivial. We may not elect to do it.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/2802

**Comment by otoolep** [comment]
All fixed.
