### ISSUE TITLE
[master] missing call of syncWaitGroup.done

### ISSUE THREAD

**Issue by liyichao** [influxdb/influxdb#2806]
In https://github.com/influxdb/influxdb/blob/master/meta/store.go#L428 , there is `s.wg.Add(1)`, but in the goroutine `handleExecConn`, there is not any call of `s.wg.Done()`, it may be a bug.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/2824

Thanks @liyichao
