### ISSUE TITLE
Race condition in TestCluster_Open

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#2810]
This just popped up, and went green on the retry:

```
--- FAIL: TestCluster_Open (0.79s)
panic: store: i=2, addr=127.0.0.1:40119, err=create local node: create node: exec failed: apply: node is not the leader [recovered]
	panic: store: i=2, addr=127.0.0.1:40119, err=create local node: create node: exec failed: apply: node is not the leader

goroutine 122 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x249
github.com/influxdb/influxdb/meta_test.MustOpenCluster(0x3, 0x0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store_test.go:699 +0x562
github.com/influxdb/influxdb/meta_test.TestCluster_Open(0xc2080e93b0)
	/home/ubuntu/influxdb-build/src/github.com/influxdb/influxdb/meta/store_test.go:554 +0x43
testing.tRunner(0xc2080e93b0, 0xe6d588)
	/usr/local/go/src/testing/testing.go:447 +0x134
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:555 +0xd4e
```

The details of the test run are here:
https://circleci.com/gh/influxdb/influxdb/3112

**Comment by otoolep** [comment]
I'll try to take a look at this.

**Comment by benbjohnson** [comment]
@otoolep It looks like the third node in the cluster `(i=2)` thinks it knows the leader but by the time it forwards on the remote exec the leader has been demoted. I would bet that increasing the election timeout in the tests would fix it.

**Comment by otoolep** [comment]
The hypothesis is that testing takes place under limited resources, which can caused leader elections to take place. The test code, however, assumes that no elections take place, and panic. These panics do not occur in production code, so simply making the timeouts longer for tests should address this issue.
