### ISSUE TITLE
[0.9.0rc32] Config file in rpm is not valid

### ISSUE THREAD

**Issue by dennisjac** [influxdb/influxdb#2813]
I just installed the rpm and it seems the provided config file is no longer valid:
"using configuration at: /etc/opt/influxdb/influxdb.conf
run: Meta.Dir must be specified. To generate a valid configuration file run `influxd config > influxdb.generated.conf`."

"influxd config" looks different indeed but also seems to be missing information (e.g. no graphite entries) so what would a correct config file look like?

**Comment by toddboom** [comment]
@dennisjac good catch - we'll get that fixed in the next release.

**Comment by toddboom** [comment]
This is fixed with #2833. It will be available in RC33 later today.
