### ISSUE TITLE
Queries on latest build causes panic

### ISSUE THREAD

**Issue by srini-raju** [influxdb/influxdb#2815]
When i run a query like 'show series' or 'show measurements' it works fine but when i try to run a query like 'select * from cpu', database panics. Writes are working fine.

**Comment by pauldix** [comment]
we need more detail. Can you output the top of the stack trace? From the first goroutine? Is this on RC32?

**Comment by pauldix** [comment]
Without further context and information about the writes going in, I'm guessing this is fixed by #2820
