### ISSUE TITLE
[0.8] The first getting started example can not work.

### ISSUE THREAD

**Issue by abcfy2** [influxdb/influxdb#2821]
I'm new to influxdb, and I followed the official doc. The first example about writing some test data failed.

The document screenshot:

![](http://influxdb.com/images/docs/log_lines.jpg)

But I received 400 error, Unable to write points without fields:
![ubuntu14 04-2015-06-09-00-00-16](https://cloud.githubusercontent.com/assets/5327677/8039180/946c8158-0e3a-11e5-92b4-139d10db9ddc.png)

I'm confused. What's wrong?

**Comment by beckettsean** [comment]
@abcfy2 that example works fine for me on a brand new 0.8 database and the code hasn't changed in months. 

In your screenshot there is nothing in the "Values" section. Both the Time Series Name and the Values must have properly formatted information. 

Can you please show exactly what you are submitting as well as the error received? I'm unable to reproduce and cannot diagnose without more information.

**Comment by abcfy2** [comment]
Oh sorry, I misunderstand the doc. Because the ``Values`` input box is gray, so I think this is read only, but it's not. I fill in the box with the json string in the doc, it works.

Thanks.
