### ISSUE TITLE
Should drop measurement data before removing from index

### ISSUE THREAD

**Issue by liyichao** [influxdb/influxdb#2841]
In https://github.com/influxdb/influxdb/blob/master/tsdb/query_executor.go#L431 , `drop measurement` first removes index, this may be problematic because if influxdb is shutdown between `db.DropMeasurement(m.Name)` and later statement, the measurement data is not deleted, and when we execute it again, influxdb will complain `ErrMeasurementNotFound`, namely, it is not idempotent.

**Comment by beckettsean** [comment]
We consider it preferable for the failure scenario to lead to a correct index (measurement deleted) and possibly dead data on disk. The alternate, deleting the data and then the index, can lead to a situation where the data is partially or totally gone but the index still exists. That seems less desirable and harder to repair.
