### ISSUE TITLE
[0.9.0rc32] Query on empty database say database not found

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2851]
From https://groups.google.com/d/msgid/influxdb/87cd208a-3edb-4df0-8590-b9f13bfb05a5%40googlegroups.com

----------

The message returned when querying an empty database is not relevant. It say the database is not found.

Create an new database.

`curl -G 'http://localhost:8086/query' --data-urlencode "q=create database test"`

Show it has been created.

```
curl -G 'http://localhost:8086/query' --data-urlencode "q=show databases"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["test"]]}]}]}
```

Do a query.

```
curl -G 'http://localhost:8086/query' --data-urlencode "db=test" --data-urlencode "q=select * from /.*/"
{"results":[{"error":"database not found: test"}]}
```

It's not an error from my point of view. Is there a reason to return an error message instead of an empty set ?

**Comment by beckettsean** [comment]
Possible duplication of #2258

**Comment by otoolep** [comment]
This error is coming from `expandSources` in the `QueryExecutor` type.

**Comment by otoolep** [comment]
So the issue with this is that the in-RAM index associated with each shard does not have a `DatabaseIndex` object inserted until the first point for that database is written into the shard.

**Comment by otoolep** [comment]
Fixed in RC34.
