### ISSUE TITLE
update homebrew for RC33

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2861]
Need to release the latest as a --devel package.

**Comment by toddboom** [comment]
@gunnaraasen i'll let you know as soon as rc33 is out and you can cut it!

**Comment by srikara** [comment]
@gunnaraasen @toddboom 
+1 for this.
I thought I could update the formula and send out a pull request but it looks like there are a bunch of additional dependencies that were added in rc33 (faith/pool, raft-boltdb etc.) and I wasn't sure which versions of the dependencies to use. 
I could be doing something silly as well :-)

**Comment by gunnaraasen** [comment]
@srikara yup, deps need to be updated. I'm working on it right now.

**Comment by gunnaraasen** [comment]
PR submitted Homebrew/homebrew#40564

**Comment by srikara** [comment]
@gunnaraasen : Looks like the pull request has been merged and is ready for consumption. Thank You.
