### ISSUE TITLE
The rc32 will be panic when select a measurement with dot in its name

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#2863]
When run select like `select * from "net.tcp.timewait"` in influxdb cli, the influxdb will be panic with below error.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x8 pc=0x566d96]

    goroutine 67 [running]:
    github.com/influxdb/influxdb/tsdb.(*FieldCodec).FieldIDByName(0x0, 0xc208152ab5, 0x5, 0x1, 0x0, 0x0)

Is anyone has ideas about this? Thanks in advance.

**Comment by ziyel** [comment]
The issue also found when using http api `http://host:port/query`.

**Comment by ziyel** [comment]
More details of the error message.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x8 pc=0x566d96]
    
    goroutine 21 [running]:
    github.com/influxdb/influxdb/tsdb.(*FieldCodec).FieldIDByName(0x0, 0xc2080f9035, 0x5, 0x1, 0x0, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/shard.go:588 +0x46
    github.com/influxdb/influxdb/tsdb.(*LocalMapper).Begin(0xc2082d8580, 0x0, 0x0, 0x2710, 0x0, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/tx.go:315 +0x2c4
    github.com/influxdb/influxdb/influxql.(*MapReduceJob).processRawQuery(0xc208011c00, 0xc208161200, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:218 +0xd6
    github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208011c00, 0xc208161200, 0x0)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:81 +0x11ec
    github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2082fd8c0, 0xc208161200)
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:926 +0xba
    created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
            /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:905 +0x5a

**Comment by ziyel** [comment]
There also has issue when using dot in the value of tag.

**Comment by ziyel** [comment]
We also met issue while insert a point using line protocol. If there has `.` in the tag value, the influxdb will panic while select the measurement.

**Comment by dgnorton** [comment]
@ziyel can you try rc33 or `master`?  I think this was fixed by #2808.

**Comment by ziyel** [comment]
Yes. The issue has been fixed. Cool!
