### ISSUE TITLE
fill(0) is not working.

### ISSUE THREAD

**Issue by ghmlee** [influxdb/influxdb#2866]
This is my example query. It worked before 0.9.0-rc31 but it is not working with 0.9.0-rc31 with this error.
```
SELECT max(value) FROM cpu WHERE host = 'A' AND time > now() - 3h group by host, time(10m), value fill(0)
```
```
{"error":"can not use field in group by clause: value"}
```

**Comment by beckettsean** [comment]
@ghmlee I'm unclear why you mention `fill(0)` in the title but your example query uses `max` and has no `fill(0)` clause at all. Can you please clarify?

In your schema, is `host` a tag or a field?

**Comment by ghmlee** [comment]
@beckettsean Sorry for that. I missed my query. Here is the query.

```
SELECT max(value) FROM cpu WHERE host = 'A' AND time > now() - 3h group by host, time(10m), value fill(0)
```

**Comment by beckettsean** [comment]
Thanks for the full query. The proper syntax omits the word "value" from before the `fill(0)`.

```
SELECT max(value) FROM cpu WHERE host = 'A' AND time > now() - 3h group by host, time(10m) fill(0)
```

If you were trying to group by `host` and `value`, that is not possible. GROUP BY does not accept fields, only tags. Therefore `value` is not valid in the GROUP BY clause. See #2618.

**Comment by ghmlee** [comment]
@beckettsean Thanks. :+1:
