### ISSUE TITLE
systemd service file missing from RPM spec file

### ISSUE THREAD

**Issue by Ormod** [influxdb/influxdb#2867]
The service file added in ec4d2ecc9223845e9db3138ef3fc67182e9ceff2 to scripts/influxdb.service should be added to the RPM spec file so it would go into /usr/lib/systemd/system/.

Now the script file is missing completely from the RPM package.

**Comment by otoolep** [comment]
@Ormod -- sounds like you are saying it should only go in the RPM package, not the deb?

**Comment by Ormod** [comment]
Well I personally care about the rpm package, but now that both the latest Debian and Ubuntu support systemd as well, it really ought to go into the .deb package as well.

**Comment by Ormod** [comment]
One thing to consider BTW would be just adding the .spec file and debian/* files into the main repo so this sort of fixes could just come in as pull requests.

**Comment by otoolep** [comment]
I believe systemd has been handled correctly for 0.9.4.
