### ISSUE TITLE
[0.9.0rc33] Continuous queries causes errors in logs and doesn't work

### ISSUE THREAD

**Issue by quhar** [influxdb/influxdb#2868]
I've tried to test continuous queries with RC33 and after creating one I errors in the logs constantly:
```
[continuous_querier] 2015/06/10 13:32:24 error executing query: SELECT mean(in_bps), mean(out_bps) INTO "observer"."yearly".traffic FROM "observer"."daily".traffic GROUP BY time(1d): err = aggregate functions with GROUP BY time require a WHERE time clause
```

Sample point inserted by line protocol:
```
curl -v -XPOST 'http://127.0.0.1:8086/write?db=observer&rp=daily&precision=s' -d 'traffic,if_id=3315579,router=3345 in_bps=2914678440,out_bps=7283185960 1433935438'
```

Continuous query:
```
CREATE CONTINUOUS QUERY traffic_yearly ON observer BEGIN SELECT mean(in_bps), mean(out_bps) INTO "observer"."yearly".traffic FROM "observer"."daily".traffic GROUP BY time(1d), * END
```

**Comment by dgnorton** [comment]
@quhar  The error message says...
```
err = aggregate functions with GROUP BY time require a WHERE time clause
```
Can you try adding a `WHERE time > now() - 1w` or something similar?

**Comment by quhar** [comment]
Now I'm getting timeouts, but this may be related to big load I'm seeing on the server.
```
[continuous_querier] 2015/06/10 15:21:00 error executing query: SELECT mean(in_bps), mean(out_bps) INTO "observer"."yearly".traffic FROM "observer"."daily".traffic WHERE time > now() - 1w GROUP BY time(1d), *: err = timeout
```

**Comment by dgnorton** [comment]
@quhar I haven't been able to reproduce a timeout so far but it would take a while to build up a test db with that many points.  At 100K points / 5 min, that's about 200M points / week.  With the query you're running, the interval is `1d`.  200M points / 7d = about 29M points per day (interval).  If you're running the default config, `RecomputePreviousN` is set to `2`, so each run of the query would compute the `mean` of 29M points 3 times (the current day + the previous 2 days).  If you know that you never write data into previous days, try setting this and restarting `influxd`:
```
[continuous_queries]
  recompute-previous-n = 0
```

Also, maybe try dropping the CQ and adding a new one with a smaller window of time: `WHERE time > now() - 3d`

**Comment by quhar** [comment]
After setting `recompute-previous-n` and `WHERE time > now() - 2d` I'm not seeing timeouts anymore. Thanks
