### ISSUE TITLE
Granting all privileges to a users doesn't work.

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2872]
The following commands:
```sql
CREATE USER jdoe WITH PASSWORD '1337'
grant all priviledges to jdoe
SHOW USERS
```

Should result in:

```json
{"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",true]]}]}]}
```

But results in:

```json
{"results":[{"series":[{"columns":["user","admin"],"values":[["jdoe",false]]}]}]}
```

Please see the skipped test in `/cmd/influxed/run/server_test.go` named `TestServer_UserCommands`, table test: `show users, existing user as admin`

**Comment by beckettsean** [comment]
This is a regression from RC31, when I tested the GRANT ALL function for the docs. It worked as expected then.
