### ISSUE TITLE
Default rp syntax not working

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2873]
The following query:

```sql
SELECT * FROM db0..cpu
```

Verified that the default RP does exist with:

```
show retention policies db0
```

results:

```
{"results":[{"series":[{"columns":["name","duration","replicaN","default"],"values":[["default","0",1,false],["rp0","1h0m0s",1,true]]}]}]}
```

No longer works.   Results in the following error:

```json
{"results":[{"error":"retention policy not found"}]}
```

There is a test for this that is skipped under `cmd/influxd/run/server_test.go`.  Test name: `TsetServer_Query_DefaultDBAndRP`

And also test `TestServer_Query_Regex` table test `specified db and default rp`

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/commit/be792b926a86bad31b8e3c9e0d997a6ede31dc70
https://github.com/influxdb/influxdb/commit/5b39b96b9db87e27e8a75ee090fc50259931fd74

tests re-enabled and now pass after recent changes.
