### ISSUE TITLE
Select not returning empty result set

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2874]
When querying the database, if you have no results, you should get an empty result set like:

```json
{"results":[{}]}
```

However, this query isn't behaving properly:

```sql
SELECT * FROM db0.rp0.cpu where time > now()
```

Results:

```json
{"results":[{"series":[{"name":"cpu","tags":{"host":"server01"},"columns":["time","value"]}]}]}
```

There is currently a test under `cmd/influxd/run/server_test.go` called `TestServer_Query_Now` that is skipped and can reproduce this.

**Comment by beckettsean** [comment]
@pauldix, @toddboom wonders if the implicit `GROUP BY *` issue would address this?

**Comment by otoolep** [comment]
Master code now seems fine, this test now passes.

**Comment by otoolep** [comment]
All fixed.
