### ISSUE TITLE
[RC33] InfluxDB Graphite service won't start unless protocol and consistency-level are specified in config file

### ISSUE THREAD

**Issue by labrown** [influxdb/influxdb#2876]
RC33 won't start when Graphite service is enabled unless you also specify protocol and consistency-level in the configuration file, a la:

    [[graphite]]
      enabled = true
      consistency-level = "one"
      protocol = "tcp"

Anything less than this results in influxdb not running.

Leave out consistency-level and this happens:

    /opt/influxdb/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/generated.conf
    
     8888888           .d888 888                   8888888b.  888888b.
       888            d88P"  888                   888  "Y88b 888  "88b
       888            888    888                   888    888 888  .88P
       888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
       888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
       888   888  888 888    888 888  888   X88K   888    888 888    888
       888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
     8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
    
    GOMAXPROCS set to 2
    using configuration at: /etc/opt/influxdb/generated.conf
    run: create server: invalid consistency level

Leave out procol and you get:

    $ /opt/influxdb/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/generated.conf
    
     8888888           .d888 888                   8888888b.  888888b.
       888            d88P"  888                   888  "Y88b 888  "88b
       888            888    888                   888    888 888  .88P
       888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
       888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
       888   888  888 888    888 888  888   X88K   888    888 888    888
       888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
     8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
    
    GOMAXPROCS set to 2
    using configuration at: /etc/opt/influxdb/generated.conf
    2015/06/10 12:06:12 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
    2015/06/10 12:06:12 read local node id: 1
    [httpd] 2015/06/10 12:06:12 listening on HTTP: [::]:8086
    [tcp] 2015/06/10 12:06:12 cluster service accept error: network connection closed
    [retention] 2015/06/10 12:06:12 retention policy enforcement terminating
    [retention] 2015/06/10 12:06:12 retention policy enforcement terminating
    run: open server: open service: unrecognized Graphite input protocol

**Comment by otoolep** [comment]
This is a bug, since it should default to `One` -- thanks for the report @labrown. I will fix this.

**Comment by labrown** [comment]
I see that protocol has a default for 'tcp' but that doesn't appear to get picked up either.  More bug?

**Comment by otoolep** [comment]
Should be fixed by PR 2895

**Comment by otoolep** [comment]
Thanks for the report @labrown
