### ISSUE TITLE
Dividing integer aggregate function results come back null

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2879]
When issuing aggregate functions against an `int` data type, and then dividing the results, you get a null back instead of the actual calculation expected.

Assuming some data already in the system, this query:

```sql
SELECT sum(value), mean(value), sum(value) / mean(value) as div FROM intoverlap GROUP BY region
```

Should result in:

```json
{"results":[{"series":[{"name":"intoverlap","tags":{"region":"us-east"},"columns":["time","sum","mean","div"],"values":[["1970-01-01T00:00:00Z",50,25,2]]},{"name":"intoverlap","tags":{"region":"us-west"},"columns":["time","div"],"values":[["1970-01-01T00:00:00Z",100,100,1]]}]}]}
```

but results in

```json
{"results":[{"series":[{"name":"intoverlap","tags":{"region":"us-east"},"columns":["time","sum","mean","div"],"values":[["1970-01-01T00:00:00Z",50,25,null]]},{"name":"intoverlap","tags":{"region":"us-west"},"columns":["time","sum","mean","div"],"values":[["1970-01-01T00:00:00Z",100,100,null]]}]}]}
```

There is a test that reproduces this condition in `cmd/influxd/run/server_test.go` name: `TestServer_Query_Aggregates` table name: `multiple aggregations with division - int`

**Comment by beckettsean** [comment]
possibly related to #3000. Looks like arithmetic functions involving integer values are not working as expected, aggregation or no.
