### ISSUE TITLE
Missing _influxdb monitoring database

### ISSUE THREAD

**Issue by Comradin** [influxdb/influxdb#2888]
I have the following block activated:
[monitoring]
  enabled = true
  write-interval = "1m0s"

But with rc33 there is no _influxdb database. With rc31 the database was created and populated with metrics.

    > use _influxdb
    Using database _influxdb
    > show series
    ERR: database not found: _influxdb

**Comment by otoolep** [comment]
Thanks @Comradin -- due to the recent cluster redesign and implementation, monitoring was removed. This will be added back in very soon.

**Comment by otoolep** [comment]
All done. New database is called _internal.
