### ISSUE TITLE
How to create continuous queries for horizontal aggregatio

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb#2890]
Hi, I have a huge amount of timeseries data  from every node  which is part of a RACK which is in turn part of a datacenter. this hierarchy can grow depending on the setup.

the below query which is intended to get the total capacity of all the site combined (horizontal aggregation) for every time interval. which is damn slow as there are many time series it has to look through for the calculation.( have played around to distribute amount multiple shards in a clustered environment)

select sum(CAPACITY.Allocated_tb) from merge(/.*SITE_(China|Australia|UnitedStates)_.*Allocated_tb/) 

so I am trying to run a continous query which will do the job in the backend 

select sum(CAPACITY.Allocated_tb) from merge(/.*SITE_(China|Australia|UnitedStates)_.*Allocated_tb/) into SITE_Allocated_tb 
 
the above query complains, is merge() allowed in the continuous query?? is there any better way to do this??

appreciate  any help with this .

**Comment by beckettsean** [comment]
@prashleo This looks like an issue with 0.8, not 0.9. Since there is no further development on 0.8 we can better handle this at support@influxdb.com. Can you re-send your issue there?
