### ISSUE TITLE
[0.9.0rc33] field type conflict with line protocol, no conflict with JSON

### ISSUE THREAD

**Issue by quhar** [influxdb/influxdb#2892]
When I'm writing points with different value types (and tagsets) with line protocol I get 500 with 
```
[write] 2015/06/10 23:54:32 write failed for shard 1 on node 1: field type conflict
```
Data:
```
res,router=1,routing_engine=666,type=cpu value=30 1433883891
res,router=1,routing_engine=666,type=load value=0.28 1433883891
```

When I'm writing same points with JSON write is successful
Data:
```
{
    "database": "observer",
    "retentionPolicy": "daily",
    "points": [
        {
            "measurement": "res",
            "tags": {
                "router": "1",
                "routing_engine": "666",
                "type": "load"
            },
            "time": "2015-06-09T21:04:52Z",
            "fields": {
                "value": 0.64
            }
        },
        {
            "measurement": "res",
            "tags": {
                "router": "1",
                "routing_engine": "666",
                "type": "cpu"
            },
            "time": "2015-06-09T21:04:52Z",
            "fields": {
                "value": 80
            }
        }
    ]
}
```
After inserting points with JSON they are visible in db.
```
> select * from res
name: res
tags: router=1, routing_engine=666, type=cpu
time                    value
----                    -----
2015-06-09T21:04:52Z    80


name: res
tags: router=1, routing_engine=666, type=load
time                    value
----                    -----
2015-06-09T21:04:52Z    0.64
```
Both queries are written to clean database.

**Comment by jwilder** [comment]
This was fixed today with #2882 .  It will return a 400 now with better error message.  The issue is that your first write is writing the data as an integer, `30`, and your second write is writing it as a float, `0.28`.  If you are writing float data, you must write all the values with a decimal like `30.0` so that the field type is set correctly.

**Comment by quhar** [comment]
But why these writes are accepted when written using JSON? Also two points have different tagset `router=1,routing_engine=666,type=cpu` vs `res,router=1,routing_engine=666,type=load` so they are part of different series

**Comment by beckettsean** [comment]
@quhar Fields and tags belong to measurements, not series. Series are the unique combination of measurement and tag set, but the fields themselves are attached to the measurement. For example, you can have up to 255 distinct fields per measurement, not per series within that measurement. Any given series can have from 1-255 of those fields present, but if it has field `foo`, that data type must match across all series.

As for why the JSON write worked, I would guess that it's an order of parsing thing. The first point in your JSON example is a float. The first point in the line protocol is an integer. I can easily write `80` as a float when the `0.64` value already defined it as such, but I cannot write `0.28` as an integer after `30` defined it as such. 

I suspect this JSON write will fail (assuming fields aren't already defined as floats): 

```
{
    "database": "observer",
    "retentionPolicy": "daily",
    "points": [
        {
            "measurement": "res",
            "tags": {
                "router": "1",
                "routing_engine": "666",
                "type": "cpu"
            },
            "time": "2015-06-09T21:04:52Z",
            "fields": {
                "value": 80
            }
        },
       {
            "measurement": "res",
            "tags": {
                "router": "1",
                "routing_engine": "666",
                "type": "load"
            },
            "time": "2015-06-09T21:04:52Z",
            "fields": {
                "value": 0.64
            }
        }
     ]
}
```

**Comment by jwilder** [comment]
I believe the JSON worked because the go json parser converts numbers to float64 so you could not write ints previously.

See http://golang.org/pkg/encoding/json/#Unmarshal

**Comment by otoolep** [comment]
+1 on that reasoning.

**Comment by quhar** [comment]
Thanks for explanation. I thought that field is actually attached to series not measurement. Also reason why JSON worked is reasonable. Thanks.
