### ISSUE TITLE
IO Storm suddenly 

### ISSUE THREAD

**Issue by yonger1516** [influxdb/influxdb#2899]
iostat -x 2 screenshot:
Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
scd0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sda             389.00    40.00   65.00  469.00  3652.00  4100.00    14.52   142.06  284.73   1.87 100.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.50    0.00    1.26   72.04    0.00   26.20

Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
scd0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sda            1529.50    19.50  350.50  413.50 14984.00  3464.00    24.15   105.77  134.89   1.31  99.95

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.51    0.00    1.52   59.64    0.00   38.32

Device:         rrqm/s   wrqm/s     r/s     w/s   rsec/s   wsec/s avgrq-sz avgqu-sz   await  svctm  %util
scd0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00   0.00   0.00
sda            1455.50   269.00  395.00  365.00 14832.00  5052.00    26.16   105.60  133.40   1.32 100.00

it's the io utilization of influxdb host, and I can detect the influxdb process consume almost IO resources by iotop:

Total DISK READ: 1628.98 K/s | Total DISK WRITE: 2.13 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                             
   39 be/4 root        0.00 B/s    0.00 B/s  0.00 % 99.34 % [kswapd0]
12415 be/4 root       30.95 K/s    0.00 B/s  0.00 %  0.00 % java -Djava.util.logging.config.file=/usr/l~org.apache.catalina.startup.Bootstrap start
 7053 be/4 influxdb  564.92 K/s    0.00 B/s 99.72 %  0.00 % influxdb -pidfile /opt/influxdb/shared/infl~id -config /opt/influxdb/shared/config.toml
 1230 be/4 influxdb  584.26 K/s    ....

**Comment by toddboom** [comment]
@yonger1516 would you be able to try this with v0.9.1?

**Comment by yonger1516** [comment]
Hi Todd,
No. Only for 0.8.8.
I moved to another machine which has enough memory, and the issue doesn’t  happen to me.

Thank you.
