### ISSUE TITLE
Couldn't delete the database with `.` in its name in influxdb admin web page

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#2909]
It came up below error message.

    Failed to remove database: {"error":"error parsing query: found ., expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 22"}

**Comment by ziyel** [comment]
As I found the admin has not add the `"` in the request to influxdb.
`http://host:port/query?u=root&p=root&q=DROP%20DATABASE%20database.name.with.dot`

**Comment by beckettsean** [comment]
@ziyel what version?

**Comment by ziyel** [comment]
rc33.

**Comment by toddboom** [comment]
Once #2746 is merged, queries will be exposed more directly to the user, so this should no longer be an issue.
