### ISSUE TITLE
Unable to insert negatif floats

### ISSUE THREAD

**Issue by BigEpsilon** [influxdb/influxdb#2919]
Hi, 

With the rc33, I'm getting a parse error whatever I try to insert a negatif float value into my db.

Here's a reproduction of the bug:

    curl -XPOST 'http://localhost:8086/write' -d '
    {
        "database": "mydb",
        "retentionPolicy": "default",
        "points": [
            {
                "measurement": "cpu_load_short",
                "tags": {
                    "host": "server01",
                    "region": "us-west"
                },
                "time": "2009-11-10T23:00:00Z",
                "fields": {
                    "value": -0.64
                }
            }
        ]
    }
    '

and I get : 

    unable to parse number value '-0.64.0': strconv.ParseFloat: parsing "-0.64.0": invalid syntax
    unable to parse number value '-0.64.0': strconv.ParseFloat: parsing "-0.64.0": invalid syntax

**Comment by pachenbach** [comment]
I have the same issue:

```
panic: unable to parse number value '-107.5.0': strconv.ParseFloat: parsing "-107.5.0": invalid syntax
```

InfluxDB crashes then.
