### ISSUE TITLE
influxdb_latest_amd64.deb not accessible

### ISSUE THREAD

**Issue by bjfelton** [influxdb/influxdb#2923]
http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb is not currently accessible.

```
wget http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
--2015-06-11 10:45:21--  http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.10.240
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.10.240|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-06-11 10:45:21 ERROR 403: Forbidden.
```

The equivalent 0.9.0 am64.deb package can be downloaded just fine.  I have not tested others.

**Comment by beckettsean** [comment]
Permissions issue on the S3 bucket. Resolved

**Comment by lusitania** [comment]
```
--2016-04-05 11:52:16--  http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.83.18
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.83.18|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-05 11:52:16 ERROR 404: Not Found.
```

What's the proper way to get the current version? I wont check the download page for every installation to see which version is the latest.

**Comment by rossmcdonald** [comment]
@lusitania The recommended way would be to use the InfluxData package repository, with instructions [here](https://docs.influxdata.com/influxdb/latest/introduction/installation/#installation).
