### ISSUE TITLE
GROUP BY time not always returning values

### ISSUE THREAD

**Issue by manuel-huez** [influxdb/influxdb#2929]
Running on 64-bit Ubuntu 14.04 with InfluxDB 0.9, installed with the package provided in the documentation.

```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY myrp ON mydb DURATION 365d REPLICATION 1 DEFAULT"

curl -d '{"database" : "mydb", "retentionPolicy" : "myrp", "points": [{"name":"cpu","tags":{"region":"useast","host":"server_1","service":"redis"},"fields":{"value":61}}]}' -H "Content-Type: application/json" http://localhost:8086/write

curl -G http://localhost:8086/query  --data-urlencode 'db=mydb' --data-urlencode 'SELECT * from cpu WHERE time > now() - 2w AND time < now() - 1w GROUP BY time(1d)'
```

Returns no result as no measurement has been made in this timeframe/satisfy the where clauses.

It would be more consistent to always return an array filled with null or filled values.

**Comment by beckettsean** [comment]
We do intend to return an empty results array when no points match the WHERE conditions. There should be a response of some kind, in any event.

**Comment by manuel-huez** [comment]
Yeah, it does make sense to return an empty results array when it's not
grouping by time. However, for consistency sake, I believe it would make
more sense to return an array filled with null/predefined values. Even
though there is no value, we are specifically asking to group by time. The
fact that there is no value in the time frame shouldn't be taken into
account.

This behavior could also be enabled when using fill(), but disabled by
default, giving more choice.

**Comment by manuel-huez** [comment]
Just realised this issue had been closed, but is still not working.

When no point matches the WHERE close, an empty set is returned instead of an empty results array, even if fill is being used.

**Comment by beckettsean** [comment]
@manuel-huez what you are describing is a change in functionality, so it's a feature request. Can you open a new issue describing the behavior you would like to see when using `GROUP BY` in conjunction with `fill()` when there are no matching points?
