### ISSUE TITLE
SUM of string value should return error, not zero

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2930]
Inspired by #2907.

The SUM of a field that isn't a float or int shouldn't be returned as zero, the query should return an error.

**Comment by beckettsean** [comment]
It is possible for the same field key to have string values on one shard and numeric on another. In that instance, would it be better to return the valid SUM of the numbers or an error for the whole query?

**Comment by dashesy** [comment]
could it return `nan` for example? meaning that it is missing. I think InfluxDB needs the notion of missing values in general.

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/influxdb/issues/3818
