### ISSUE TITLE
Missing WHERE time clause error on continuous queries

### ISSUE THREAD

**Issue by toomanyjmikes** [influxdb/influxdb#2944]
I'm creating this continuous query (stolen from your documentation): 

CREATE CONTINUOUS QUERY c1h ON cqtest BEGIN SELECT COUNT(name) INTO clicksCount_1h FROM clicks GROUP BY time(1h) END

and am getting a error message (repeated once per second) like:

[continuous_querier] 2015/06/11 13:40:24 error executing query: SELECT count(name) INTO "cqtest"."default".clicksCount_1h FROM "cqtest"."default".clicks GROUP BY time(1h): err = aggregate functions with GROUP BY time require a WHERE time clause

I've reproduced this using 0.9.0rc33 on OS X and 0.9.0-1 final on Centos.

Program that creates db, cq and populates with a little data at https://gist.github.com/toomanyjmikes/a92a1521d1a95ee9c7e3#file-cq_where_time_error-py

**Comment by mahuika88** [comment]
I'm seeing this too. this is the I'm using query on 0.9.0:
create continuous query agg_cpu on collectd begin select sum(value) into "cpu" from "cpu_value" where type_instance =~ /(system|user|nice|wait|interrupt|softirq|steal)/  group by time(10s) end

Seeing this error:
[continuous_querier] 2015/06/12 17:10:40 error executing query: SELECT sum(value) INTO "collectd"."default".cpu FROM "collectd"."default".cpu_value WHERE type_instance =~ /(system|user|nice|wait|interrupt|softirq|steal)/ GROUP BY time(10s): err = aggregate functions with GROUP BY time require a WHERE time clause

**Comment by beckettsean** [comment]
Thanks, @toomanyjmikes @mahuika88 this is a definite change from the prior behavior and is easy to reproduce. We'll get with the core devs and find out if this was an accidental or intentional change to the CQ syntax and then update the docs appropriately.
