### ISSUE TITLE
[0.9] Authentication Documentation section unclear

### ISSUE THREAD

**Issue by defreng** [influxdb/influxdb#2953]
Hi

although I added an [authentication] section to /etc/opt/influxdb/influxdb.conf (I had to add it, it wasn't in there by default), this seems to be ignored by the server, since I still can make any request without specifying a user or password through the admin interface.

I installed influxdb on Ubuntu 15.04 Server.

Please let me know if you need further details to debug this problem.

**Comment by leelasharma** [comment]
Can you post a snippet of the configuration file

**Comment by defreng** [comment]
Of course! Here it is:
http://pastebin.com/g4D12DYp

**Comment by leelasharma** [comment]
In the http section, the  auth-enabled flag seems to be set as false.

**Comment by defreng** [comment]
Thx, this seems to solve it! Also the authentication section does not seem to be needed in this case.

The documentation on this topic seems to be a bit unclear, so I'll update the title.

**Comment by beckettsean** [comment]
@defreng Did you install with the .deb package or build from source? 

Did you generate a configuration file after installation, e.g. `influxd config > influxdb.generated.conf`? I think the generic influxdb.conf that ships with the product is a template, not a full config.

**Comment by defreng** [comment]
@beckettsean I installed the .deb package. But also the output of influxd config revealed the same template...

**Comment by beckettsean** [comment]
@defreng I see that the generated file is the same as the template. I'll make an issue on the docs repo to revisit the authentication setup

**Comment by beckettsean** [comment]
Docs updated.
