### ISSUE TITLE
Metrics from collectd's write_graphite plugin being rejected

### ISSUE THREAD

**Issue by deric** [influxdb/influxdb#2954]
When sending data from collectd's `write_graphite` plugin, data are rejected. Maybe problem with underscore??
```
[graphite] 2015/06/12 10:02:01 unable to parse data: received "example.com.processes-process-all.ps_pagefaults.majflt" which doesn't conform to format of key.value.key.value.name or name
```
Influx version: `0.9.0-rc30`

**Comment by deric** [comment]
Probably duplicate of #2102

**Comment by otoolep** [comment]
Yes, once #2102 is addressed, Graphite processing will be customizable.
