### ISSUE TITLE
Cannot write points through admin interface

### ISSUE THREAD

**Issue by palkan** [influxdb/influxdb#2968]
OS: Ubuntu 14.04
InfluxDB: 0.9.0 (from deb package)

I'm trying to write points through admin interface ("Explore data"), but server responds with `{ "error": "database is required" }` and status code 400.

The query: `POST http://localhost:8086/write?u=root&p=root&db=test` and data: 

```json
{
 "name": "cpu_load",
 "tags": {
   "host": "server01",
   "core": "0"
 },
"fields": {
  "value": 0.45
 }
}
```

Or using curl:

```shell
curl -i -XPOST 'http://localhost:8086/write?db=test' -d '{"name":"cpu_load_short","tags":{"host":"server02"},"fields":{"value":0.74}}'

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 2a4e242e-112d-11e5-800c-000000000000
X-Influxdb-Version: FIXME
Date: Fri, 12 Jun 2015 18:02:18 GMT
Content-Length: 33

{"error":"database is required"}
```

I tried the following form too (example from [this page](http://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html)):

```shell
curl -i -XPOST 'http://localhost:8086/write?db=test' -d '{"database":"test", "points":[{"name":"cpu_load_short","tags":{"host":"server02"},"fields":{"value":0.74}}]}'

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 9ce1e7c4-112d-11e5-800f-000000000000
X-Influxdb-Version: FIXME
Date: Fri, 12 Jun 2015 18:05:30 GMT
Content-Length: 32

{"error":"missing measurement"}
```

But... another kind of error.

P.S. Line protocol works correctly using the same endpoint.

**Comment by FoxxMD** [comment]
I'm seeing the same problem
```
{
   "name":"api",
   "tags":{
      "merchant":50001
   },
   "fields":{
      "value":"Merchant_GET"
   }
}
```

Gives me a bad request in the admin interface and also trying to send as a POST request.

**Comment by tima** [comment]
@FoxxMD The JSON you are pushing isn't valid. The API was modified a fair bit in the last few RCs before release and the docs haven't caught up. For instance name is now measurement.

**Comment by tima** [comment]
@palkan Looks like you have similar issues as @FoxxMD. API breaks not reflected in the docs. For instance this works fine for me:

```curl -i -XPOST 'http://localhost:8086/write?u=root&p=root' -d '{"database":"demo" ,"measurement":"cpu_load_short","tags":{"host":"server02"},"fields":{"value":0.74}}'```

**Comment by FoxxMD** [comment]
Thanks @tima . Where can I find a reference for the latest api schema?

**Comment by beckettsean** [comment]
@palkan where did you see those examples in the docs? Can you provide the URL?

**Comment by tima** [comment]
@FoxxMD  I figured it out from the discussions here and some trial and error. There is no reference yet. Like I said the docs haven't caught up.

**Comment by palkan** [comment]
Thanks @tima!
Closed.
