### ISSUE TITLE
Potential memory usage issues with collectd

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2972]
Reports from field that collectd memory usage looks too high, and increases as time passes, with 0.9.0.

**Comment by otoolep** [comment]
cc @pauldix @dgnorton

**Comment by otoolep** [comment]
`GODEBUG=gctrace=1 ./influxdb` gather GC details.

https://github.com/collectd/go-collectd is a potential source for load-generation code.

**Comment by otoolep** [comment]
Specific discussion related to collectd performance, that may or may not be related to this:

https://groups.google.com/forum/#!msg/influxdb/KyP7XrZ6qG4/u1mjLhRfyWsJ

**Comment by otoolep** [comment]
From mailing list post:

"And it's fairly obvious that something is either leaking memory, or the GC isn't working as intended, because after a few hours, influxd is using ~16 GB RAM and ~4 GB swap - and growing."

**Comment by otoolep** [comment]
This change adds a basic collectd load generator to the system.

https://github.com/influxdb/influxdb/pull/2976

**Comment by otoolep** [comment]
I have started a collectd load test on a single node. It's injecting 3,000 points/second, 10 measurements, each with a single tag. The tag itself has a variance of 10, which means a total of 100 series.

Actual writing to BoltDB has been disabled (data is dropped just before the write takes place), as there is ongoing investigation of its usage, which may also blow up memory. This way I have taken that out of the equation.

Test run started at 3:37 PDT, June 12.  Initial `top` usage:

`18994 philip    20   0  470336  13408   5836 S  10.0  0.1   0:24.40 influxd`

**Comment by otoolep** [comment]
Second run: ` 8383 root      20   0  289892   8672   5248 S   0.3  0.1   0:00.07 influxd                                                                                                                 `, started at 4:30pm PDT, June 12th.

**Comment by otoolep** [comment]
After 72 hours with 3,000 points/sec, but dropping just before writing to the shard, memory usage is stable. There is no leak in the collectd (or deeper) path, when skipping writes to BoltDB.

**Comment by neonstalwart** [comment]
@otoolep so, have you confirmed if there *is* a leak when you include writing?  

i'm curious because i don't use collectd but i suspect something is leaking but i haven't been able to confirm the leak yet in order to start determining the cause.

**Comment by otoolep** [comment]
@neonstalwart -- no, there is not necessarily a leak when writing. But reports of excessive memory usage and IO load requires that actual writing is taking place. What this ticket's testing shows is that simply shipping incoming data through the system to the correct shards (but not actually writing the data) is not leaking memory.

**Comment by pauldix** [comment]
@neonstalwart we're working on optimizing our use of BoltDB so that it's more efficient. Basically, no memory leak, but there is an issue with how we're structuring things that causes IOPS to be unreasonably high.
