### ISSUE TITLE
Line protocol: tag string values quotation

### ISSUE THREAD

**Issue by palkan** [influxdb/influxdb#2980]
When writing using line protocol the same string value quoted and unquoted resolves to two different tags:

```shell
 curl -i -XPOST 'http://localhost:8086/write?db=test' -d 'test,role=server value=0.74'

 curl -i -XPOST 'http://localhost:8086/write?db=test' -d 'test,role="server" value=0.74'

 curl -G http://localhost:8086/query --data-urlencode "db=test" --data-urlencode "q=select * from test limit 10"

{"results":
  [
     {"series":
        [
          {
            "name": "test",
            "tags": {"role": "server"}
             ...
           },
           {
              "name": "test",
              "tags": {"role": "\"server\""}
               ...
           } 
  ]
}
```

Why do we need to distinguish between these values?
It's really strange to write queries like: `select ... from .... where server='"server"'`.
If I need quotes within value it's better to just escape them.

So, the question is: what do you think about this problem? If you don't mind, I would like to make a PR.

**Comment by jwilder** [comment]
Tag values should not be quoted.  Just use the value directly without quoting it.  If the value has spaces or commas, then those need to be escaped with `\ ` and `\, ` respectively.  

Quotes _are_ required for field values that are strings.  The only thing that needs to be escaped within string field values is `"` with `\"`.

**Comment by palkan** [comment]
Thanks! Got it. It was not clear from docs.

**Comment by fromYukki** [comment]
@jwilder Thank you for clarification.
Maybe it is better to create separated page for line protocol? Because as for now it is very hard to find detailed information. In one place it is written that tags values are string. In another page I can see that it is possible to use any type. What is the correct answer - I dont know.

[Reading and Writing Data](https://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html)
> You can add columns to existing series without penalty, and integers, floats, strings, booleans, and raw bytes are all supported as types. 

> Both keys and values must be strings.

[Schema Design](https://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html)
> Note that tag values are always interpreted as strings.

**Comment by corylanou** [comment]
I know this isn't a great answer but at least until the docs get updated (and they are working on it) you can refer to the tests for all possible scenarios: https://github.com/influxdb/influxdb/blob/master/tsdb/points_test.go

**Comment by beckettsean** [comment]
@fromYukki thanks for pointing out the confusing statements in the docs. I've updated the "Reading and Writing Data" page:

> You can add columns to existing series without penalty. Tag keys, tag values, and field keys are always strings, but field values may be integers, floats, strings, booleans, or raw bytes. 

The changes will go live on the next push.

**Comment by jwilder** [comment]
@fromYukki You can also find more details about the line protocol here: https://github.com/influxdb/influxdb/blob/master/tsdb/README.md
