### ISSUE TITLE
Reduce Log Output?

### ISSUE THREAD

**Issue by mrjgreen** [influxdb/influxdb#2989]
I was wondering if there is an option to limit the amount of logging output from the server, especially when using the UDP collection handler.

I'm getting thousands of rows of output that look like this:

~~~
[udp] 2015/06/15 16:07:28 Wrote a batch of 10 points to test
[udp] 2015/06/15 16:07:28 Wrote a batch of 10 points to test
[udp] 2015/06/15 16:07:28 Wrote a batch of 10 points to test
[udp] 2015/06/15 16:07:28 Wrote a batch of 10 points to test
~~~

I tried adding a `log-enabled = false` directive to the [udp] section but this didn't work either. This seems odd, I would have expected some consistency between the different handlers.

I notice in earlier versions there were options in the config file for setting the log level. These no longer seem to have any effect... The ability to log only messages above a configured level seems like it would be useful? Has there been a conscious decision to remove this in v0.9 or has it just not yet been implemented?

~~~
[logging]
# logging level can be one of "debug", "info", "warn" or "error"
level  = "info"
file   = "influxdb.log"         # stdout to log to standard out
~~~

Sorry if I'm asking questions that have already been answered elsewhere... I had a look through the closed issues but couldn't find anything.

If there is a requirement here for a new feature I'd be happy to try and work towards a PR

Cheers

**Comment by otoolep** [comment]
Thanks @mrjgreen -- this is excessive we should not be logging each batch.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/2993

**Comment by otoolep** [comment]
All fixed.

**Comment by mrjgreen** [comment]
Thats great! And thanks for such quick resolution!
