### ISSUE TITLE
Retention policy creation not enforcing minimum retention duration

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#2991]
You can currently create a RP with a duration of 1s. We used to have a minimum but I can't remember what it is.  It should be more than 1s though I would think.

There is a test in `cmd/influxd/run/server_test.go`, testname: `TestServer_RetentionPolicyCommands`, table test: `Ensure retention policy with unacceptable retention cannot be created` that is currently skipped that is able to replicate the issue.

**Comment by otoolep** [comment]
@corylanou - this minimum used to be 1 hour.

**Comment by beckettsean** [comment]
@corylanou confirming the minimum RP duration was 1 hour: #2760.

Is max still correct? #2762

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3027

**Comment by otoolep** [comment]
All fixed for 0.9.1
