### ISSUE TITLE
Create build machine for nightly builds

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#2998]
https://groups.google.com/forum/#!msg/influxdb/Od6ykEGzTCM/hLyITFttwXEJ

@toddboom @gunnaraasen

**Comment by dahankzter** [comment]
It would be great to have channel for builds with bugfixes. So basically "latest-nightly" or something with fixes that are somewhat safe but no other experimental features if possible.

**Comment by itxx00** [comment]
+1

**Comment by marcosnils** [comment]
With the help of Circleci [Parametrized builds](https://circleci.com/docs/parameterized-builds) a [nightly build](https://circleci.com/docs/nightly-builds) configuration seems pretty straightforward. I believe it's nice to have it in Travis as nightly build becomes transparent for everyone

My two cents.

**Comment by itxx00** [comment]
+1 again

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/issues/3074
