### ISSUE TITLE
Make error reported by empty tags array a little bit more sensible

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb#2999]
When you are trying to write the following json:

```json
{
   "measurement":"volume",
   "tags":{
   },
   "timestamp":"2015-06-12T23:59:59+02:00",
   "fields":{
       "value":0.083333
    }
}
```

You get the following error:

'{"error":"json: cannot unmarshal array into Go value of type map[string]string"}

I think the error should be more in the line of 'tags cannot be empty' or simply be ignored.

**Comment by randywallace** [comment]
My understanding is that the JSON format for writing metrics is to be deprecated.  (Note: I am not a maintainer of InfluxDB, just a user)  Even though I believe it should work with 0.9, the documentation now describes the line protocol format, which is supposed to be significantly faster: http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html.  I personally like it much better, and for your question, it supports inserting metrics without any tags.

**Comment by beckettsean** [comment]
The JSON protocol in 0.9 also allows for writing points without tags, but not for an empty `tags` section in the payload.

However, as @randywallace pointed out, the JSON protocol is deprecated so I'm closing this issue.
