### ISSUE TITLE
Problem with simple arithmetic expressions on integers

### ISSUE THREAD

**Issue by bblodfon** [influxdb/influxdb#3000]
Hi,

In influxdb 0.9.0, I have inserted many cpu data data like this:
curl -i -XPOST 'http://localhost:8086/write?db=stats&precision=u' -d 'cpu_user value=32.9 1434383413397157'
and many memory data (value is in bytes) like this:
curl -i -XPOST 'http://localhost:8086/write?db=stats&precision=u' -d 'available_memory value=38744784896 1434383413397213'

Inside the CLI, when I query:
select value, 2*value from cpu_user
I get the results:
2015-06-16T07:55:33.199964Z	18       36
2015-06-16T07:56:34.524977Z	19.1    38.2
... (all OK)

but when I query the other measurement, the arithmetic expression (2*value) becomes null:
select value, value/2 from available_memory
2015-06-16T07:51:27.876727Z	44327944192
2015-06-16T07:52:29.205774Z	44333027328

Is this a limitation of the current version?

**Comment by beckettsean** [comment]
@bblodfon any errors returned in the CLI or in the logs? My guess is that is has to do with the `cpu_user` metrics being `float64` while the `available_memory` metrics are `int64`. 

My own testing shows that I get expected results for `2*value` or `value*2` when `value` is a float64, but if `value` is an `int64` I get no results for the arithmetic operation. 

There are no errors in the logs.

**Comment by bblodfon** [comment]
Hi @beckettsean, no errors in the CLI or logs: the values are just nullified only that I can see...the thing is why influxdb puts a number like 34 as int64 and not one like 326723166323 - which has 12 digits and I believe it is inside the range of int64! I mean as you saw from above, I insert no floats at all!

**Comment by beckettsean** [comment]
@bblodfon there are only four data types in InfluxDB: `int64`, `float64`, `boolean`, and `string`.

Data types for fields are determined by the first value written to that field, so all of your `cpu_user` fields are `float64` and all of your `available_memory` fields are `int64`. The math operators are failing on integer values.

**Comment by beckettsean** [comment]
@bblodfon updating following your comment edit:

Yes, if you want a field value to store as a `float64` you must include a decimal point, e.g. 32.0 vs 32

**Comment by otoolep** [comment]
Fixed for all integer values up to 2^53 by https://github.com/influxdb/influxdb/pull/3613

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/issues/3614 tracks implementing true integer math, which will support values up to 2^63
