### ISSUE TITLE
0.9.0 instabilities during app testing

### ISSUE THREAD

**Issue by neonstalwart** [influxdb/influxdb#3004]
the script at https://gist.github.com/neonstalwart/4029ce4af721b371234d closely simulates what happens as part of my app testing.  

i'm sorry i couldn't reduce the script any further and it isn't always failing with this shell script but it does seem to fail often enough that if you try a few times (5 - 10) you'll probably see one of these errors.  in my app testing it fails every time.

EDIT: between each run i stop `influxd`, `rm -rf ~/.influxdb`, and then restart `influxd` to make sure i start with a clean install.

some of what might be relevant characteristics of the script are:

* create database, insert data, drop measurements, insert data again - it never seems to fail until after i've dropped measurements
* multiple simultaneous http requests being made to the database - i was never able to see the problems without running the curl commands in the background
* each point inserted via its own http request - i.e. no batching

if there is some part of this which is outside the intended usage of influxdb, let me know and i can possibly change the way i approach my app to adjust some of those characteristics but it wouldn't be trivial and i think there really is probably some issue beyond just heavy usage.

the errors are not reproducible every time but some of the ones i've seen are:

* `write failed for shard 2 on node 1: database not open` (some extra lines shown for context in case it's useful) - this one is the most common
```
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] GET /query?q=drop%20measurement%20volunteer&db=mydb HTTP/1.1 200 43 - curl/7.37.1 67a1504b-146f-11e5-86eb-000000000000 80.199µs
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] GET /query?q=drop%20measurement%20completeNeed&db=mydb HTTP/1.1 200 42 - curl/7.37.1 67a1586b-146f-11e5-86ed-000000000000 883.519µs
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] GET /query?q=drop%20measurement%20like&db=mydb HTTP/1.1 200 42 - curl/7.37.1 67a15824-146f-11e5-86ec-000000000000 944.33µs
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] GET /query?q=drop%20measurement%20pageview&db=mydb HTTP/1.1 200 42 - curl/7.37.1 67a1b296-146f-11e5-86ee-000000000000 653.484µs
[write] 2015/06/16 16:34:01 write failed for shard 2 on node 1: database not open
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] POST /write?db=mydb HTTP/1.1 500 32 - curl/7.37.1 67a6537c-146f-11e5-86ef-000000000000 219.617µs
[write] 2015/06/16 16:34:01 write failed for shard 2 on node 1: database not open
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] POST /write?db=mydb HTTP/1.1 500 32 - curl/7.37.1 67a67605-146f-11e5-86f0-000000000000 163.553µs
[write] 2015/06/16 16:34:01 write failed for shard 2 on node 1: database not open
[http] 2015/06/16 16:34:01 127.0.0.1 - - [16/Jun/2015:16:34:01 -0500] POST /write?db=mydb HTTP/1.1 500 32 - curl/7.37.1 67a73bb1-146f-11e5-86f1-000000000000 212.896µs
```

* `invalid memory address or nil pointer dereference`
```
[http] 2015/06/16 16:41:00 127.0.0.1 - - [16/Jun/2015:16:41:00 -0500] GET /query?q=select%20count%28value%29%20from%20like&db=mydb HTTP/1.1 200 108 - curl/7.37.1 61275731-1470-11e5-86d7-000000000000 644.349µs
[http] 2015/06/16 16:41:00 127.0.0.1 - - [16/Jun/2015:16:41:00 -0500] GET /query?q=select%20count%28value%29%20from%20completeNeed&db=mydb HTTP/1.1 200 118 - curl/7.37.1 61279583-1470-11e5-86da-000000000000 425.896µs
[http] 2015/06/16 16:41:00 127.0.0.1 - - [16/Jun/2015:16:41:00 -0500] GET /query?q=select%20count%28value%29%20from%20follow&db=mydb HTTP/1.1 200 110 - curl/7.37.1 6127a0e1-1470-11e5-86db-000000000000 385.574µs
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x306e51]

goroutine 5262 [running]:
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/tx.go:208 +0x31
github.com/influxdb/influxdb/tsdb.(*LocalMapper).Close(0xc20843c6e0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/tx.go:267 +0x2c
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Close(0xc208767b90)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:60 +0x8d
github.com/influxdb/influxdb/influxql.(*Executor).close(0xc2084ed940)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:912 +0x6a
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/tx.go:208 +0x31
github.com/influxdb/influxdb/tsdb.(*LocalMapper).Close(0xc20843c6e0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/tx.go:267 +0x2c
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Close(0xc208767b90)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:60 +0x8d
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Open(0xc208767b90, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:51 +0xdb
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208767b90, 0xc2087b7080, 0xc208157f00)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:72 +0x36
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2084ed940, 0xc2087b7080)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:926 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:905 +0x5a
```

**Comment by neonstalwart** [comment]
fyi - failures still exist as of 38b4f07 (which includes #3002) in case anyone is wondering if #3002 fixes this.

**Comment by beckettsean** [comment]
@neonstalwart thanks for the great testing and the write-up. I do think that dropping measurements is assumed to be an infrequent activity for InfluxDB. Of course things should work and be stable, so there's a bug here to be found, but repeatedly creating and dropping the same measurements is not part of the typical use case. Occasionally dropping a measurement that is never re-created is much more typical.

**Comment by neonstalwart** [comment]
yeah. I just drop each measurement once.

**Comment by otoolep** [comment]
@neonstalwart -- are you writing data into the past? If so, how far? Specifically more than 12-hours old? 12hours appears to be your retention period.

**Comment by neonstalwart** [comment]
my retention period is 120d https://gist.github.com/neonstalwart/4029ce4af721b371234d#file-test-sh-L18. 

I do intentionally add a dummy point for each measurement at the epoch as a way to ensure my measurement exists - this is a kludge to avoid errors for things like dropping non-existent measurements and it also sort of defines my "schema". 

apart from that, my other times are randomly generated to fall within the 120 day window (I think - I can dig further if that's important but the script includes times that were the ones I actually used this afternoon).

**Comment by otoolep** [comment]
Please disable retention enforcement and see if the instability is still there. I want to see if writing to shards which are being deleted could be an issue.

Add the following to your config:

```
[retention]
enabled = false
```

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/services/retention/config.go

**Comment by otoolep** [comment]
Ack on your retention being 120d -- I misread that.

**Comment by neonstalwart** [comment]
2nd run with default config + retention turned off :crying_cat_face: 

```
[http] 2015/06/16 20:29:29 127.0.0.1 - - [16/Jun/2015:20:29:29 -0500] GET /query?q=show%20measurements&db=mydb HTTP/1.1 200 163 - curl/7.37.1 4c325fa6-1490-11e5-86a2-000000000000 145.015µs
[http] 2015/06/16 20:29:29 127.0.0.1 - - [16/Jun/2015:20:29:29 -0500] GET /query?q=drop%20measurement%20follow&db=mydb HTTP/1.1 200 42 - curl/7.37.1 4c32c8d2-1490-11e5-86a3-000000000000 626.144µs
[http] 2015/06/16 20:29:29 127.0.0.1 - - [16/Jun/2015:20:29:29 -0500] GET /query?q=select%20count%28value%29%20from%20completeNeed&db=mydb HTTP/1.1 200 118 - curl/7.37.1 4c335467-1490-11e5-86a4-000000000000 419.
128µs
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x306e51]

goroutine 5119 [running]:
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/tx.go:208 +0x31
github.com/influxdb/influxdb/tsdb.(*LocalMapper).Close(0xc208b1d8c0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/tx.go:267 +0x2c
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Close(0xc208395e30)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:60 +0x8d
github.com/influxdb/influxdb/influxql.(*Executor).close(0xc20897ef00)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:912 +0x6a
github.com/boltdb/bolt.(*Tx).Rollback(0x0, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/boltdb/bolt/tx.go:208 +0x31
github.com/influxdb/influxdb/tsdb.(*LocalMapper).Close(0xc208b1d8c0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/tsdb/tx.go:267 +0x2c
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Close(0xc208395e30)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:60 +0x8d
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Open(0xc208395e30, 0x0, 0x0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:51 +0xdb
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208395e30, 0xc2089817a0, 0xc208389700)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:72 +0x36
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc20897ef00, 0xc2089817a0)
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:926 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /Users/neonstalwart/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/influxql/engine.go:905 +0x5a
```

**Comment by otoolep** [comment]
OK, great, thanks @neonstalwart -- that rules out that simple cause.

**Comment by otoolep** [comment]
I am currently reworking the query engine code, as part of the work to re-implement distributed query support. One way or another I will be fixing this issue.

**Comment by neonstalwart** [comment]
i've been looking at this some more and here's something i've found (sorry for all the links)...

when the store deletes a measurement from a shard, if [`sh.deleteMeasurement()`](https://github.com/influxdb/influxdb/blob/4933736d51d4c163d9a2e64264916e19649015d2/tsdb/store.go#L167) fails (after adding logging, i've seen `bucket not found` and `database not open` errors for this when running my script), the [shard will be closed](https://github.com/influxdb/influxdb/blob/4933736d51d4c163d9a2e64264916e19649015d2/tsdb/shard.go#L292-L295) but it still remains in `s.shards` and when a subsequent attempt is made to [write to that shard](https://github.com/influxdb/influxdb/blob/4933736d51d4c163d9a2e64264916e19649015d2/tsdb/store.go#L255-L260) the database is not open and [`s.db.Update()`](https://github.com/influxdb/influxdb/blob/4933736d51d4c163d9a2e64264916e19649015d2/tsdb/shard.go#L154-L193) fails.

i'm hoping that someone a little more familiar with the code here can take this and figure out what the issue is.  it looks to me that in general if `sh.XXX()` fails, the db will be closed so the shard should probably be removed from `s.shards` anytime `sh.XXX()` fails.  e.g. in [`s.deleteMeasurement`](https://github.com/influxdb/influxdb/blob/4933736d51d4c163d9a2e64264916e19649015d2/tsdb/store.go#L167-L169) maybe it should be:

```go
for shardID, sh := range s.shards {
	if err := sh.deleteMeasurement(name, seriesKeys); err != nil {
		// remove the closed shard
		delete(s.shards, shardID)
		return err
	}
}
```

and similarly for `deleteSeries` and maybe others too.

i really hope that helps.

**Comment by neonstalwart** [comment]
so, the question still remains why i'm seeing `bucket not found` errors that trigger all of this but hopefully someone more familiar with the code could come up with some possible reasons.  let me know if there's anything i could try or any more information i could provide.

**Comment by beckettsean** [comment]
I've sen the `bucket not found` error when trying to drop a measurement for the first time. 

```
> show measurements
name: measurements
------------------
name
boolean
meas
test-show-tags
time

> drop measurement meas
ERR: bucket not found

#note I was already operating in the `use mydb` context, I merely repeated it here to see if there was some unrelated CLI issue with persisting that.
> use mydb
Using database mydb
> drop measurement meas
ERR: measurement not found: meas
> show measurements
name: measurements
------------------
name
boolean
test-show-tags
time
```

**Comment by ccutrer** [comment]
this is likely related, `drop series from energy where circuit='solaredge'` is also giving me `ERR: bucket not found` on 0.9.0. a subsequent `select * from energy where circuit='solaredge'` (to confirm the drop worked) crashes influx.

**Comment by beckettsean** [comment]
@benbjohnson, @otoolep says you likely fixed this as a side effect of some WAL work?

**Comment by beckettsean** [comment]
Should be ameliorated by WAL and metastore changes in 0.9.2 and later. I haven't seen a `bucket not found` error in quite some time.
