### ISSUE TITLE
Influx 0.9.0 not binding on all IP addresses - IPv6 & localhost only

### ISSUE THREAD

**Issue by ckmaresca** [influxdb/influxdb#3005]
All,

Tried a number of ways of telling Influx to bind on all IP addresses or at least all IPv4 addresses, but it only wants to bind to either all IPv6 addresses + localhost or the IPv4 address you specify + localhost.

Tried using `0.0.0.0` and `*` + `port` but none of these work.

**Comment by otoolep** [comment]
To bind to all interfaces, using port 8086, you should just be able to set the relevant bind address to ":8086".

**Comment by ckmaresca** [comment]
Tried that - it's the default setup, doesn't work - eg. connection refused.  I wouldn't actually file a bug without trying every possible incantation - this is not a PEBAK.  Stuff like this is part of the reason why Influx is moving down our list of DBs to trust.

**Comment by beckettsean** [comment]
@ckmaresca I'd say InfluxDB is still in a trust-but-verify state. There's been a lot of good change but that change has led to edge case instability. I think we're quickly addressing the edge case issues, and every bug report helps.

**Comment by otoolep** [comment]
I will presume you are on a Linux platform.

@ckmaresca - can you please start InfluxDB and show me the output of 'ss
-ant' or netcat.

**Comment by ckmaresca** [comment]
Yes, but I'm not sure I'll have time to do that.  We just soft-launched our product and I'm leaving for vacation on Monday....

**Comment by noroute** [comment]
@otoolep We noticed the same problem (CentOS 6.4).

```
ss -ant

State       Recv-Q Send-Q                          Local Address:Port                            Peer Address:Port
LISTEN      0      128                                        :::2003                                      :::*
LISTEN      0      128                                        :::8083                                      :::*
LISTEN      0      128                                        :::8086                                      :::*
LISTEN      0      128                                        :::22                                        :::*
LISTEN      0      128                                         *:22                                         *:*
LISTEN      0      128                                        :::8088                                      :::*
```
We just disabled ipv6 support for all interfaces (using sysctl), now interfaces only have ipv4 addresses, problem persists.

**Comment by otoolep** [comment]
I cannot reproduce this.

```
$ ss -ant | grep 8086
LISTEN     0      128                      :::8086                    :::*     
~ $ telnet 192.168.128.53 8086
Trying 192.168.128.53...
Connected to 192.168.128.53.
Escape character is '^]'.
^]
telnet> Connection closed.
~ $ telnet 127.0.0.1 8086
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^]
telnet> Connection closed.
```

With `:8086` as the bind address in the config, I can connect using multiple IPv4 addresses.

**Comment by artkrz** [comment]
Same issue for me, listing only on tcp6. Fresh install of 0.9 package on Debian 8.2.

**Comment by otoolep** [comment]
So I can repo @artkrz -- can you show me how you know it's not binding on all interface?

**Comment by PavloDemyanchuk** [comment]
Guys,
I have same issue.

I installed influxdb_0.9.4.2 on Ubuntu and I can only connect to localhost:8083,8086.
I run command  lsof -i:8086,  lsof -i:8083 I get flowing:
sudo lsof -i:8086
COMMAND  PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
influxd 9383 influxdb   10u  IPv6 1075928      0t0  TCP *:8086 (LISTEN)
sudo lsof -i:8083
COMMAND  PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
influxd 9383 influxdb    9u  IPv6 1075927      0t0  TCP *:8083 (LISTEN)

What should i do to make influx listen on ipv4?

Thanks,
Pavlo

**Comment by rossmcdonald** [comment]
@PavloDemyanchuk Are you sure InfluxDB is not listening on IPv4? Linux supports dual-stack sockets, so (assuming there's not an error) InfluxDB should be able to be reached over IPv4 and IPv6 over the same port (even though `netstat` and `lsof` display it just as IPv6).

**Comment by ckmaresca** [comment]
@PavloDemyanchuk Have you tried actually connecting to Influx over ipv4?  I'm saying this because one thing I noticed is that Linux tools lie about what is active.  I was researching this when I first reported this issue, and there were some notes that tools looking for listening services (netstat et. al.) would lie about what was active.

For example - if I `netstat -antp` this is what is says for Influx:
```
tcp6       0      0 :::8083                 :::*                    LISTEN      29447/influxd   
tcp6       0      0 :::8086                 :::*                    LISTEN      29447/influxd   
tcp6       0      0 10.10.2.222:8086        10.10.2.222:59666       ESTABLISHED 29447/influxd   
tcp6       0      0 10.10.2.222:8086        10.10.2.222:59669       ESTABLISHED 29447/influxd   
```

Clearly wrong and that doesn't show up until after a connection has been established.  There is zero indication that it is binding to any ipv4 addresses beforehand....

This is `0.9.5-nightly-bc569e8` with default options.  AFAIK, I haven't specified an IP for it to bind to....

**Comment by PavloDemyanchuk** [comment]
@ckmaresca  Yes, and i can reach server by ipv4. 
Looks like issue was in my firewall settings.

Thank you for help!
Pavlo.

**Comment by karinator** [comment]
My concern is that influx listens to all ports, instead of just localhost. My ping tests: 

root@hoover:~# **curl -sl -I localhost:8086/ping**
HTTP/1.1 204 No Content
Request-Id: 85366cf7-c5d4-11e5-8004-000000000000
X-Influxdb-Version: 0.9.6.1
Date: Thu, 28 Jan 2016 15:33:46 GMT

root@hoover:~# **curl -sl -I 10.61.68.41:8086/ping**
HTTP/1.1 204 No Content
Request-Id: 86b1ba74-c5d4-11e5-8006-000000000000
X-Influxdb-Version: 0.9.6.1
Date: Thu, 28 Jan 2016 15:33:48 GMT

I really need to restrict my influxdb to something like 

tcp6       0      0 :::8083                 :::*                    LISTEN      29447/influxd   
tcp6       0      0 :::8086                 :::*                    LISTEN      29447/influxd   

There is no problem to restricting it to localhost for ipv4 

tcp        0      0 127.0.0.1:8083          0.0.0.0:*               LISTEN      12292/influxd   
tcp        0      0 127.0.0.1:8086          0.0.0.0:*               LISTEN      12292/influxd   
tcp        0      0 127.0.0.1:8088          0.0.0.0:*               LISTEN      12292/influxd 

but this is not what i am going for. 


Thank you!
Karina

**Comment by karinator** [comment]
In logs it says 
run: open server: split bind address: too many colons in address ::1:8088

**Comment by tripledes** [comment]
@karinator Can you try "[::1]:8086" ? That's the syntax Go's `net.Listen` accepts.

**Comment by chengweiv5** [comment]
+1, I meet this issue on CentOS 7.2 with 0.13.0-1, and `[::1]:8086` doesn't help.

But listen to specific IP:port can work around, like below

```
[root@ IP ~]# netstat -tlnp | grep influxd
tcp        0      0 IP:8086      0.0.0.0:*               LISTEN      10143/influxd       
tcp6       0      0 :::8083                 :::*                    LISTEN      10143/influxd       
tcp6       0      0 :::8088                 :::*                    LISTEN      10143/influxd  
```
