### ISSUE TITLE
Support distributed queries

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3009]
This issue captures design notes and discussions about implementing support for distributed queries -- queries where all shard data is not necessarily local to the node received the query.

## Initial refactoring
- `engine.go` and `functions.go` to be moved to `tsdb` package with as little change as possible, as first step in refactoring. Looks possible at a high-level.

## High-level Query sequence
- co-ord node receives query over HTTP.
- JSON encoding of request and response body will be used.
- co-ord node parses query to ensure it's sane. Return error if statement doesn't parse.
- co-ord node ensures database and retention policy exist. It uses the Raft metastore to do this. If they don't exist, return an error.
- co-ord node performs any required auth.
- co-ord node gets shard groups (SGs) for the policy, taking database, retention policy, and time into account.
- SGs determine the list of target shards.
- co-ord node determines list of host nodes for each shard. In some case those nodes may include the co-ord node.
- co-ord node will hit endpoint (more later) for remote nodes, or perform call to local store if target node is co-ord node. Question here about how much, and what layer, this should be abstracted from the co-ord node. By comparison there is no abstraction for writing -- the write code on a co-ord node makes an explicit choice between the `TSDBStore` and `ShardWriter` interfaces when writing:

https://github.com/influxdb/influxdb/blob/master/cluster/points_writer.go#L240

## Questions about generating queries to shards (remote or local)
- What level of parallelism makes sense? At a minimum all the shards of the earliest SG within the retention policy should be queried in parallel, since they would (potentially) contain data for the same times. Only when those queries complete should the next SGs be queried.

- How many SGs must be queried depends on any GROUP BY time factor. If the GROUP BY time factor is larger than the duration of SGs for that retention policy, then multiple contiguous SGs will need to be accessed before the GROUP BY results can be calculated. If GROUP BY time factor is less than the duration of SGs, then only 1 SG's set of shards need to be accessed.

## Proposal about network support

- HTTP endpoint will be added to each node, `/remote_query`. This endpoint will accept a shard ID and query, and possibly user information.
- The response to the co-ord node will be `influxql.Row` objects (or something similar). The tag sets contained within these rows can be derived from examining the rows. Or does it make more sense for the remote node (or TSDBStore in the case of local) to explicitly include tagsets of sent rows, coupled to `influxql.Row` objects?
- Auth may also be enforced on this endpoint.
- Endpoint shouldn't need to be much more than wrapping a call to the local store. Similar to `LocalMapper` and `RemoteMapper` code that existed before (though this is going to be more complex than simple Mapper-type code).

## How shards will handle a query
- parse query.
- determine tagsets using parsed query and shard metadata.
- For each tagset in parallel, query the relevant series data using Bolt cursors (to be abstracted away as needed to account for any on-disk datastore format changes) in an iterative manner.
- obey any specified time range.
- execute local mapping functions e.g. sum.
- enforce LIMIT and requested chunking.
- Meta-queries -- such as `SHOW MEASUREMENTS` also need to operate in a distributed fashion.

## How the co-ord node will handle response from endpoint or local shard
- for a given time range (or time buckets for aggregates) create the set of tagsets it receives.
- gather data from various responses and merge by tagset.
- perform any final mapping e.g. sum by tagset.
- return result to client.

**Comment by otoolep** [comment]
@pauldix

**Comment by otoolep** [comment]
A short design doc is now available here:

https://docs.google.com/document/d/1yILep780dCmNqiwPdbWx15Asr6F50iArrf9xODGOOpg

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3231/files

**Comment by daviesalex** [comment]
The design doc appears locked from public viewing. Is this intentional?

**Comment by otoolep** [comment]
Not really, but we needed the permissions it has now for team-editing purposes. 

The design in the doc is obsolete now anyway, so you're not missing much. The actual commit will be accompanied by a README, which will explain the design.

**Comment by otoolep** [comment]
![mapperstagsets](https://cloud.githubusercontent.com/assets/536312/8554075/9b76dee4-24b5-11e5-933e-e402682ee811.jpg)

Outline of Mappers and TagSets.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3299

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3376

**Comment by otoolep** [comment]
Remaining work captured by:

https://github.com/influxdb/influxdb/issues/2755
https://github.com/influxdb/influxdb/issues/3295
https://github.com/influxdb/influxdb/issues/3296
https://github.com/influxdb/influxdb/issues/3377
