### ISSUE TITLE
[0.9.0] Cluster configuration

### ISSUE THREAD

**Issue by Kuaaaly** [influxdb/influxdb#3011]
With RC33, I was able to set up a cluster using the "join-urls" parameter (in conf file) but this doesn't seem to work with the new release 0.9.0. I can not find any documentation (on the official website) or any forum/github post that can help me to set up a 2/3 nodes cluster on InfluxDB 0.9.0.
Did I misunderstood something in the 0.9.0, or is the clustering functionality just not working ?

Thank you in advance for your help

PS : I am a newbie in InfluxDB, I use it to handle tones of events.

**Comment by otoolep** [comment]
`join-urls` is not yet functional. To create a cluster set the `peers` in the `meta` section of the config file. For example:

```
[meta]
   peers = ["127.0.0.1:8088", "127.0.0.2:8088", "127.0.0.3:8088"]
```

Each node should have the same line.
