### ISSUE TITLE
[0.9.0] Can't set Database Users as Database Admins using Web Interface

### ISSUE THREAD

**Issue by levkov** [influxdb/influxdb#3012]
Ubuntu 14.04, clean install from pre-build package.
Tested in Chrome and Firefox.
[0.9.0] Can't set Database Users as Database Admins using Web Interface

It's not possible to set user as Admiin when creating New Database User.
It's not possible to set existing user as Admin.

**Comment by maxcanada** [comment]
Same issue here.
Also, when trying via a Python client "grant_admin_privileges", it doesn't work. When trying via CLI either (GRANT ALL PRIVILEGES TO user)

**Comment by levkov** [comment]
Additionally,
I can't delete Database Users. When I click on [x] on the right from username, there is dialog asking "Are you sure you want to delete this user?" . Clicking "OK" does nothing, user is is still in the list. 

(Tested in Chrome and Firefox).

**Comment by Kuaaaly** [comment]
Same issue here too...
Similar problem for deleting database with the web interface, dialog box appear but clicking "OK" does nothing. "Successfully removed database : test" appear but the database is not deleted.

It seems that [0.9.0] Web interface is really bugged :(

(Chrome)

**Comment by beckettsean** [comment]
@maxcanada can you open a different issue for the `GRANT ALL` in the CLI? That is a different problem from the one reported initially here.

**Comment by beckettsean** [comment]
New admin UI coming in 0.9.1.

**Comment by toddboom** [comment]
The new admin interface in #2746 will expose queries more directly, so this should no longer be a blocker.
