### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb#3017]
**Action**: Execute a malformed query

http://influxdb-test.testhost.com:8086/query?q=select%20*%20from%20test_metric

**Result**: panic: runtime error: invalid memory address or nil pointer dereference

**Log**: http://tca0.nl/Q4l

**Comment by dahankzter** [comment]
Seems serious. We have hit it quite a bit especially with newer users that constantly makes mistakes. We have to restart the server and loose data.

**Comment by neonstalwart** [comment]
duplicate of #2932

**Comment by otoolep** [comment]
You must include a database when SELECTing data. The fix will be available in 0.9.1.
