### ISSUE TITLE
brew install influxdb

### ISSUE THREAD

**Issue by hy05190134** [influxdb/influxdb#3018]
I install influxdb 0.8.8, and I found no influx in any path, how can I use after I install through "brew install influxdb"

**Comment by Kuaaaly** [comment]
What you're looking for was written during the influxdb installation by brew, and here is the answer : 
/usr/local/Cellar/influxdb/0.8.8/bin/influxdb -config /usr/local/etc/influxdb.conf

**Comment by hy05190134** [comment]
but I can't use command in terminal, and I find no "127.0.0.1:8083/query " when I modify the config

**Comment by Kuaaaly** [comment]
Are you looking for the web UI ?

**Comment by hy05190134** [comment]
I want to check whether 0.8.8 can't be used for command?

**Comment by hy05190134** [comment]
I just use 127.0.0.1:8083 to create db and more

**Comment by beckettsean** [comment]
@hy05190134 there is no further development on the 0.8.x line of InfluxDB. For assistance with that version please contact the mailing list at influxdb@googlegroups.com or reach out to InfluxDB support at support@influxdb.com.
