### ISSUE TITLE
Intermittent invalid aggregate query results 

### ISSUE THREAD

**Issue by ryancurrah** [influxdb/influxdb#3023]
I am seeing an issue with influx 0.8.8 returning inconsistent results when running the following query:

Query:
```
SELECT FIRST(qlimit.value - qusage.value) FROM instances.tenant.dev.openstack.quota.limit AS qlimit INNER JOIN instances.tenant.dev.openstack.quota.usage AS qusage
``` 

Result:
```
time	first
0	    21
```

This is not the correct value, the correct value is -103 = -1 - 102. Based on querying the individual fields. But after a few minutes and I query again the right result will be returned. 

Limit Query:
```
SELECT FIRST(value) FROM instances.tenant.dev.openstack.quota.limit
```

Limit Result (correct result):
```
time	first
0	    -1
```

Usage Query:
```
SELECT FIRST(value) FROM instances.tenant.dev.openstack.quota.usage
```

Usage Result:
```
time	first
0	    102
```

**Comment by beckettsean** [comment]
@ryancurrah I don't know the 0.8 syntax very well, but shouldn't your first query be 

`SELECT FIRST(qlimit.value) - FIRST(qusage.value) FROM instances.tenant.dev.openstack.quota.limit AS qlimit INNER JOIN instances.tenant.dev.openstack.quota.usage AS qusage`

Does that give the expected result?

**Comment by ryancurrah** [comment]
No that didn't work I got...

Error message:
```
Execute QueryERROR: Value cannot be evaluated for type &{FIRST 10 [0xc20871e7d0] <nil> false}
```

I tried putting some extra brackets around SELECT same errors.

```
SELECT (FIRST(qlimit.value) - FIRST(qusage.value)) FROM instances.tenant.dev.openstack.quota.limit AS qlimit INNER JOIN instances.tenant.dev.openstack.quota.usage AS qusage
```

**Comment by beckettsean** [comment]
In 0.9 the syntax would be like what I suggested, where you take the `FIRST` of each field and do arithmetic on those. There is a current bug (#3000) where arithmetic operators only function on `float`s and not `int`s. 

There's an open issue describing exactly what you want to do: #761. I would recommend putting a `+1` on that issue.

When you upgrade to 0.9 be aware pretty much everything is different, not least of which are the schema and the query syntax.
