### ISSUE TITLE
404's on the web-based admin interface

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb#3025]
I understand that this may be related to changes in 0.9.0, but how do we get the web-based admin interface to work again. Had influxdb-0.8.8 installed, and removed it with `rpm -e influxdb-0.8.8-1.x86_64`

**Comment by beckettsean** [comment]
In 0.9.0 the admin UI is available at http://localhost:8083.

**Comment by skynet** [comment]
yes, that's where I proxy requests using Nginx. I can see the UI but all queries returns 404. 
![capture](https://cloud.githubusercontent.com/assets/139233/8215650/5c1cd28c-14ff-11e5-9581-6ce61a624157.PNG)

**Comment by neonstalwart** [comment]
@skynet sounds like it might be a problem with how you're using nginx.  does it work without nginx?

**Comment by skynet** [comment]
I wish it was a problem with Nginx since that's something I can easily fix. But no, it isn't. All requests are transparently proxied through Nginx. And running it like this still fails:
`> curl 'http://127.0.0.1:8083/query?u=root&p=root&q=SHOW%20DATABASES'
404 page not found
`

**Comment by toddboom** [comment]
@skynet it looks you're trying to send queries to the admin port (8083). they should be getting sent to API port (8086).

**Comment by skynet** [comment]
@toddboom - you were right. I just realized that in order to run this in a Web browser remotely I also need to proxy localhost:8086 through Nginx. Thanks, everyone!
