### ISSUE TITLE
[0.9.0] BatchPoint time isn't setting the default time for points

### ISSUE THREAD

**Issue by epelc** [influxdb/influxdb#3026]
The influxdb go client `BatchPoint` doesn't behave as it's docs suggest. The docs state that the time field will be used as the default for all points if they don't set their own time field. But it uses the current time instead of what you give it for points with no time set.

**Comment by neonstalwart** [comment]
@epelc see #2513 which is a PR for a test case demonstrating how the code fails to do what the docs say.  i'm fairly sure that it would require significant architectural changes to change the code to work the way the docs advertise and since the line protocol is going to eventually be the only way to write points i expect that this issue won't be fixed.

**Comment by neonstalwart** [comment]
> since the line protocol is going to eventually be the only way to write points

actually, if i recall, you're using the go client and my comment is related to using JSON and HTTP.  regardless, to make `BatchPoint` work as advertised seems unlikely to me.

**Comment by epelc** [comment]
@neonstalwart Is the goal to define the time once in the `BatchPoint` json instead of in each `Point`'s json? If you don't mind redefining it in each points json this could probably work.

As for @2513 I think you might be able to fix it by using an anonymous struct in place of `Point` in `BatchPoint.UnmarshalJson`. It would be essentially the same as `Point` but because it's anonymous you could control everything in `BatchPoint.UnmarshalJson`.

Also if it can't be fixed is there any other reason to keep the `Time` field in `BatchPoint`? I think it'd be much less confusing/irritating for people using the client if it can't be fixed.

**Comment by neonstalwart** [comment]
@epelc now that i look again, my problem was with precision not time - but i think there are some similar issues.  if you know a way to fix it then i'm sure a PR would be merged.

**Comment by vladlopes** [comment]
@epelc I got bitten by this too.

As stated in f7d90cf, when the client was changed to use the line protocol, we kind of lost the ability to use default values (eg: tags, time, precision) for all points in the `Batchpoints`. This is hooked on the server side that does a "normalization" (https://github.com/influxdb/influxdb/blob/master/services/httpd/handler.go#L368) of the points when json data is received.

The line protocol needs information per point and, problably, will never have the same idea as the json.

So, it still works if you can send the json payload directly to the server, something that is no longer possible with the go client.

I think we could do the same "normalization" of the points on the client side to, at least, have the behavior stated on the `Batchpoints` documentation.

**Comment by beckettsean** [comment]
Your assumption is correct, @vladlopes, there are no plans to add batch parameters to the line protocol. 

The JSON protocol is soon to be retired and this code along with it. @epelc is there a specific place in the documentation that led to your confusion? I'd love to update that to make it less likely to lead people astray while the JSON protocol is still active.

**Comment by vladlopes** [comment]
@beckettsean The documentation we are refering is both on the client [Readme](https://github.com/influxdb/influxdb/blob/master/client/README.md), that has a Note that you can set the values for all points, and on the [source](https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L452) code for the client.

**Comment by epelc** [comment]
Yes it'd be nice if the docs were updated to reflect the current behavior.

**Comment by beckettsean** [comment]
Thanks, @epelc and @vladlopes. I made #3056 to address the README issue, please let me know if that seems reasonable.

I've opened #3057 to update the godocs as fixing it is beyond my expertise. Please give suggestions on that as to how we can better document the client functions.
