### ISSUE TITLE
Perform further system test of shard precreation

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3029]
I had test data write some data to the past, and saw the output below from shard precreation. I need to confirm if it is correct. The logging also needs more details, such as start and end times for the created shard groups and shards.

```
2015/06/17 11:49:08 pre-creating successive shard group for group 1, database db, policy rp
2015/06/17 11:49:09 new shard group 3 successfully created
2015/06/17 11:49:09 pre-creating successive shard group for group 2, database db, policy rp
2015/06/17 11:49:10 new shard group 4 successfully created
2015/06/17 11:59:10 pre-creating successive shard group for group 1, database db, policy rp
2015/06/17 11:59:10 new shard group 3 successfully created
2015/06/17 11:59:10 pre-creating successive shard group for group 2, database db, policy rp
2015/06/17 11:59:10 new shard group 4 successfully created
2015/06/17 11:59:10 pre-creating successive shard group for group 3, database db, policy rp
2015/06/17 11:59:10 new shard group 2 successfully created
```

**Comment by otoolep** [comment]
I suspect much of the output is from `CreateShardGroupsIfNotExist` which doesn't actually create the groups if they already exist. The log message may need to be updated to reflect this reality.

**Comment by neonstalwart** [comment]
yes please, some more insight here would be helpful

**Comment by otoolep** [comment]
Confirmed, logging gives the impressions that shard groups are constantly being created, which is not the case.

**Comment by otoolep** [comment]
Shard creation logging is now sensible.
