### ISSUE TITLE
0.9.0 Cluster Information

### ISSUE THREAD

**Issue by ClanStyles** [influxdb/influxdb#3031]
I don't see any docs on how to setup the clusters or provision new ones? Am I over looking something?

**Comment by otoolep** [comment]
We are in the process of creating documentation, but you check out this post to the mailing list:

https://groups.google.com/forum/#!topic/influxdb/b_f2I7-zV-A

**Comment by ClanStyles** [comment]
You should be able to do this via command line (at least show nodes)... that way once you deploy, you can use SkyDNS to generate the string on the fly and scale faster / easier. Otherwise we have to run confd and regenerate the config, reboot nodes and that could cause downtime.
