### ISSUE TITLE
how can I read the continuous query data using command or curl request

### ISSUE THREAD

**Issue by hy05190134** [influxdb/influxdb#3034]
I have create continous query using specific command, and I can see the results when I do "show counties query", but how can I get the data ?
![screen shot 2015-06-18 at 6 47 48 pm](https://cloud.githubusercontent.com/assets/7495796/8229537/91226f1e-15ea-11e5-8de4-1451be573349.JPEG)

**Comment by beckettsean** [comment]
Your SELECT statement is operating on the original raw data series. The data is not downsampled in place. The data is written to the series specified in the INTO clause. 

`select * from waf..count_by_1h` should show you the downsampled data.

**Comment by hy05190134** [comment]
select * from waf..count_by_1h  can not return down sampled data and tell me "ERR: measurement not found: "waf"."default".every_1h_count", can you add some explanation to docs after we create continuous queries.

**Comment by hy05190134** [comment]
@beckettsean

**Comment by hy05190134** [comment]
is it create the data after the influxd' s retention check interval ? after that time, I found the data exist and updated.

**Comment by beckettsean** [comment]
Continuous queries run at the boundaries of the GROUP BY interval. In your CQ the GROUP BY is `1h`, so the CQ will run once an hour to downsample the prior hour's datapoints. If there are no source points with a timestamp in the prior hour there will be nothing written to the series created by the CQ.

Note that the timestamp is what matters, not the time when the point was written. If a point was written to the database 5 minutes ago but has a timestamp from two weeks ago, that point will not be part of the CQ's selection when it runs.
