### ISSUE TITLE
show users returns data in an inconsistent manner

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb#3048]
Query:

```sql
SHOW USERS
```

Output:

```json
{  
   "results":[  
      {  
         "series":[  
            {  
               "columns":[  
                  "user",
                  "admin"
               ]
            }
         ]
      }
   ]
}
```

Why are the user names being shown in the columns section instead of the values section? It seems inconsistent with the other queries such as SHOW DATABASES and SHOW SERIES

**Comment by otoolep** [comment]
@thecodeassassin -- this is the output when there are no users in your system. `user` and `admin` are column names, corresponding to the user's name and his or here admin flag. The fact that there are no values means there are no users.

**Comment by otoolep** [comment]
Please consult the docs if you have any more questions:

https://influxdb.com/docs/v0.9/query_language/database_administration.html

specifically the section titled "User Management".
