### ISSUE TITLE
data files and series exist after drop database

### ISSUE THREAD

**Issue by jasper-zhang** [influxdb/influxdb#3049]
My version is 0.9.0, and I created a cluster of 3 servers. After I create a db and insert some data to it, I drop the db. I find the db files in the server which I curl the drop command are deleted, but data files in  other two servers exist still. Otherwise, I find the result of "show series" is still seen !!

**Comment by jasper-zhang** [comment]
The result of "SHOW MEASUREMENTS"  exists also.

**Comment by maxcanada** [comment]
Same issue here

**Comment by otoolep** [comment]
Since clustering is in alpha-state, not all operations are support on clusters. `DROP MEASUREMENT` is one such operation. It only works correctly on a single node.

Please follow https://github.com/influxdb/influxdb/issues/3009 -- when this issue is closed, `DROP MEASUREMENT` will work on a cluster.

**Comment by maxcanada** [comment]
Actually we have this issue on a single node
Thanks

**Comment by otoolep** [comment]
Can you please show me an entire sequence of `curl` commands demonstrating the issue on your single node, as described here? 

https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#bug-reports

**Comment by maxcanada** [comment]
Hi, 

Here is the list of commands I've done : 

curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
Result : {"results":[{}]}

curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY myrp ON mydb DURATION 365d REPLICATION 1 DEFAULT"
Result : {"results":[{}]}

curl -d '{"database" : "mydb, retentionPolicy" : "myrp", "points": [{"measurement":"cpu","tags":{"region":"useast","host":"server_1","service":"redis"},"fields":{"value":61}}]}' -H "Content-Type: application/json" http://localhost:8086/write

curl -G http://localhost:8086/query --data-urlencode "q=DROP DATABASE mydb"

curl -G http://localhost:8086/query  --data-urlencode 'db=mydb' --data-urlencode 'q=SELECT * from cpu'
{"results":[{"error":"database not found: mydb"}]}

curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY myrp ON mydb DURATION 365d REPLICATION 1 DEFAULT"
Result : {"results":[{}]}

Here is the problem : 

curl -G http://localhost:8086/query  --data-urlencode 'db=mydb' --data-urlencode 'q=SHOW MEASUREMENTS'
{"results":[{"series":[{"name":"measurements","columns":["name"],"values":[["cpu"]]}]}]}

No data in there though : 
curl -G http://localhost:8086/query  --data-urlencode 'db=mydb' --data-urlencode 'q=SELECT * from cpu'
{"results":[{}]}

Thanks a lot,

**Comment by otoolep** [comment]
@maxcanada -- the JSON in your supplied "write" is not valid. `retentionPolicy` needs to be quited.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3090

**Comment by otoolep** [comment]
Thanks @maxcanada for the bug report.

**Comment by jasper-zhang** [comment]
@otoolep --DROP MEASUREMENT will not work when my MEASUREMENT contains dot, result show:
{
    "error": "error parsing query: found ., expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 21"
}

**Comment by beckettsean** [comment]
@jasper-zhang you must double-quote measurement names that contain a period.

**Comment by otoolep** [comment]
The original issue has been addressed and 0.9.1 will have the fix.
