### ISSUE TITLE
MS Windows Installer

### ISSUE THREAD

**Issue by sirinath** [influxdb/influxdb#3051]
Can you provide a MS windows installer?

**Comment by beckettsean** [comment]
It's on the roadmap but not for a few months.

**Comment by otoolep** [comment]
@corylanou took care of this, and it's available here:

https://influxdb.com/download/index.html

**Comment by binary132** [comment]
@otoolep there are no MSI builds at the download link.  Has Windows support been scrapped?

**Comment by rossmcdonald** [comment]
@binary132 We don't officially support windows and the TSM engine currently is not working on windows (although community members have been contributing fixes to get it working). We're evaluating windows support and soliciting feedback in #5359.
