### ISSUE TITLE
Top N support?

### ISSUE THREAD

**Issue by 9mm** [influxdb/influxdb#3055]
Hello,

I'm curious if top() and bottom() are still supported in 0.9? If I use top() in the query, it says I'm using the wrong number of arguments (implying it exists). If I put the correct number of arguments, it says the function doesn't exist.

I need to show a shorted list of items, grouped by a tag (referrers), so like:

    google.com - 500
    yahoo.com - 300
    stackoverflow.com - 20

Cardinality on the referrer tag shouldnt be too bad, in the low single/double digit thousands.

Thanks!

**Comment by beckettsean** [comment]
Issue #1821 is still open, therefore TOP has not been wired back up in 0.9.0. Any behavior for that function is currently undefined. It's currently scheduled to be wired back up in 0.9.2.

Closing in favor of #1821
