### ISSUE TITLE
syntactically invalid SELECT causes panic

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3062]
From https://github.com/influxdb/influxdb/issues/2883#issuecomment-113638315

```
> create database db123
> use db123
Using database db123
> select * from db123
ERR: Get http://localhost:8086/query?db=db123&q=select+%2A+from+db123: EOF
```

logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x26b76f]

goroutine 70 [running]:
github.com/influxdb/influxdb/influxql.(*SelectStatement).RewriteDistinct(0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/influxql/ast.go:780 +0x37f
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).rewriteSelectStatement(0xc208037780, 0x0, 0xc2080ee888, 0x0, 0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/query_executor.go:271 +0x18a
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc208037780, 0x0, 0xc2080cc180, 0xc2080e668e, 0x5, 0xc2081502a0, 0x2710, 0x0, 0x0)
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/query_executor.go:219 +0x58
github.com/influxdb/influxdb/tsdb.func·004()
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/query_executor.go:157 +0x727
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /private/tmp/influxdb20150611-31144-myuhfv/influxdb-0.9.0/src/github.com/influxdb/influxdb/tsdb/query_executor.go:211 +0x22b
```

**Comment by msiebuhr** [comment]
It might be worth noting that the following *doesn't* crash the database:

    > create database db123
    > use db123
    Using database db123
    > insert foo,bar=baz val=42
    > select * from db123
    ERR: measurement not found: "db123"."default".db123

That is: inserting data first, makes it cough up an error.

**Comment by beckettsean** [comment]
Thanks, @msiebuhr, that should narrow down the possible code paths to investigate.

**Comment by otoolep** [comment]
This is fixed in 0.9.1.

**Comment by msiebuhr** [comment]
Pardon my ignorance, but I can't quite find any 0.9.1 release/rc's in git (or anywhere else, for that matter). What should I check out to have a look?

**Comment by otoolep** [comment]
0.9.1 will be released July 2nd. In the meantime, you can build from source if you like. Full instructions are https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#installing-go

**Comment by gunnaraasen** [comment]
Alternatively, if you're running OS X and use Homebrew, the `influxdb` formula now has an option to install from head, e.g. `brew install influxdb --HEAD`.
