### ISSUE TITLE
line protocol doc advocates "sorting tag keys" but doesn't give sort

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3069]
https://github.com/influxdb/influxdb/blob/master/tsdb/README.md, line 16, says: 

"Tags should always be sorted by key before being sent for best performance."

What sort? ASCII? Alphabetical?

**Comment by otoolep** [comment]
A simple alphabetical sort is what is meant by this.

**Comment by beckettsean** [comment]
So then `A` and `a` both sort before `B` or `b`. Where do `1`, `_`, `#`, `-`, or ` ` sort, for example?

**Comment by beckettsean** [comment]
Is there a standard sorting library we can use as a reference? Given the issues with multi-language, unicode, etc. I would really prefer to have a definitive, determinative answer for what sort order means.

**Comment by beckettsean** [comment]
For instance, what's the sort order for `ø`, `ö`, `o`, `Ö`, and `ó`?

**Comment by otoolep** [comment]
Fair question. Sorting happens here:

https://github.com/influxdb/influxdb/blob/master/tsdb/points.go#L254

I believe it comes to down to this sort:

http://golang.org/pkg/bytes/#Compare

@jwilder can confirm.

**Comment by jwilder** [comment]
Yes, @otoolep is correct.  Comes down to `bytes.Compare`.

**Comment by otoolep** [comment]
@beckettsean -- I'll close this. Please re-open if you need more technical detail.
