### ISSUE TITLE
line protocol does not allow for some edge cases with backslash and escaping

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3070]
There's currently no way to insert a tag key or value like `123\,456` using the line protocol. 

```
> insert slash_test,taggy=123,456 value=1
ERR: missing value
> insert slash_test,taggy=123\,456 value=1
> insert slash_test,taggy=123\\,456 value=1
ERR: missing value
> insert slash_test,taggy=123\\\,456 value=1
> show tag values with key = "taggy"
name: taggyTagValues
--------------------
taggy
123,456
123\\,456
```

This is certainly the most trivial of edge cases, but I did expect a triple escaping `123\\\,456` to result in a tag value of `123\,456`.

**Comment by consense** [comment]
+1

**Comment by otoolep** [comment]
The code that performs all this parsing is at https://github.com/influxdb/influxdb/blob/master/models/points.go. There are also many tests, ensuring that existing functionality does not break.

So the resources are there to fix this issue, for someone that is up for it.

**Comment by otoolep** [comment]
To run the existing test suite, do this:
```
cd models
go test -v ./...
```
assuming your build environment is configured correctly. See https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md for information on that.

**Comment by e-dard** [comment]
I'm currently working on this.
