### ISSUE TITLE
saving string that has time issue

### ISSUE THREAD

**Issue by sonneym** [influxdb/influxdb#3071]
In new 0.9.0 stable saving a point that has string with time text as in 2015-06-20T00:17:50.219485173Z  throws error:
unable to parse asdf="[[{"timeuid":"2015-06-20T00:17:51.225520825Z","key":"val"...  bad timestamp

(this used to work in 0.9.0rc31)

**Comment by beckettsean** [comment]
@sonneym can you please give the full write statement you are trying to insert? The error without the originating command is not sufficient to investigate.

**Comment by sonneym** [comment]
The actual issue is with double quotes:  Just marshal some object in golang and save it using influxdb go client, it will have double quotes and throw the issue.
try string for example: qote: "[[{"timeuid":"2015-06-20T00:17:51.225520825Z","key":"val"}]]" :endquote
I can live with it by replacing double quotes.

More pressing issue for me: DROP SERIES FROM measurement WHERE tag filters
Doesn't work anymore. How do I drop certain series now?

**Comment by beckettsean** [comment]
@sonneym see #3087 for details on the DROP SERIES issue.

**Comment by beckettsean** [comment]
@sonneym do you have some sample Go code that shows the "marshal some object in golang and save it using influxdb go client, it will have double quotes and throw the issue" behavior?
