### ISSUE TITLE
Create nightly builds

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3074]
The following steps are required:

- make `package.sh` support a non-interactive mode. @gunnaraasen 
- spin up DO box for kicking the nightly build. @otoolep
- Use parameterized builds with CircleCI. @otoolep
- Creation of IAM AWS credits for pushing to S3 bucket. @otoolep

**Comment by otoolep** [comment]
@gunnaraasen -- starting with you since we need the package script changes.

**Comment by otoolep** [comment]
@toddboom

**Comment by otoolep** [comment]
@kfitzpatrick

**Comment by neonstalwart** [comment]
i suppose this issue replaces #2998?

**Comment by otoolep** [comment]
https://circleci.com/docs/parameterized-builds

**Comment by otoolep** [comment]
This task has been completed. Notification about nightly builds will be shared soon.

**Comment by otoolep** [comment]
https://influxdb.com/download/index.html
