### ISSUE TITLE
Remove _key from SHOW SERIES output

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3076]
Started with https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/YplsIe1BwLs/cPCa6n6NIYYJ

It's debatable whether `SHOW SERIES` output should include `_key`.

**Comment by beckettsean** [comment]
Consensus is remove it from the output.

**Comment by otoolep** [comment]
Decided to leave this in after all.
