### ISSUE TITLE
Null field causes database panic

### ISSUE THREAD

**Issue by robashton** [influxdb/influxdb#3077]
The following request will completely crash influx  (I did a search through the issues for "panic" and "nil" and as I'd expect for a Go project got a lot of hits - but not this one)

curl -i -XPOST 'http://localhost:8086/write?db=foo' -d 'cpu_load_short,host=server01,region=us-west,value=343.0,value2= 1434055562000000000'

**Comment by toddboom** [comment]
@robashton I verified that it does cause a panic (though my current branch is a little bit behind master) - we should definitely make sure that gets handled, however it looks like the point you're writing is malformed. There should be a space separating the tags and fields and an actual value assigned to `value2`. Fixing those makes the write succeed as expected.

**Comment by robashton** [comment]
I know my input is malformed but as you've acknowledged - malformed input shouldn't crash an entire database ;-) (Obligatory "this wouldn't happen in Erlang")

I got to this because another project I use was submitting *this* JSON

     '{"points":[{"measurement":"katja_vmstats.error_logger_message_queue","time":"2015-06-21T21:45:22.000Z","tags":{},"fields":{"value":0,"state":null,"description":null}}],"database":"riemann"}'

I have submitted another PR to that project to fix that.

The above was just a minimised test case because I wanted to rule out other things.

On that note by the way - I can't see if JSON is supposed to be supported in the future or not, should I be sending a pull request to this third party project and making it submit the plain comma delimited input?

**Comment by beckettsean** [comment]
@robashton The JSON protocol is deprecated and will not persist long-term. All libraries should move to the line protocol when possible.

**Comment by otoolep** [comment]
There have been fixes made by @jwilder that mean the write shown in the opening will no longer panic the system. Instead an error is returned.

```
$ curl -i -XPOST 'http://localhost:8086/write?db=foo' -d 'cpu_load_short,host=server01,region=us-west,value=343.0,value2= 1434055562000000000'
HTTP/1.1 400 Bad Request
Request-Id: 9383305b-19fe-11e5-800e-000000000000
X-Influxdb-Version: 0.9
Date: Tue, 23 Jun 2015 23:21:29 GMT
Content-Length: 124
Content-Type: text/plain; charset=utf-8

unable to parse 'cpu_load_short,host=server01,region=us-west,value=343.0,value2= 1434055562000000000': invalid field format
```

**Comment by otoolep** [comment]
Since the JSON API is deprecated, I'll close this.

**Comment by robashton** [comment]
Aight - another pull request pending to another project to make them stop using json then... our work is never done. 

Cheers!
