### ISSUE TITLE
Writing multiple points not working

### ISSUE THREAD

**Issue by arunjana** [influxdb/influxdb#3085]
I just pasted example insert statements in influxdb tutorial for "writing multiple points" with/without timestamps and it is giving 400-bad request. I am able to write single points. 

When I tried to write using jerset-client, I can insert single points. But, when tried to write multiple points, I  can see the last point in the batch statement and not the others. 

This is the post payload that is being sent
String input = "cpu_load_short,host=server01,region=us-west value=0.800894 "+ System.getProperty("line.separator") + "cpu_load_short,host=server01,region=us-west value=0.80894 " + System.getProperty("line.separator") + "cpu_load_short,host=server01,region=us-west value=0.400894";

**Comment by beckettsean** [comment]
@arunjana for the line protocol, points must be separated by `\n`. What is `"line.separator"` in your code?

**Comment by thecodeassassin** [comment]
We are separating points with \n. It's still not working (only inserts one record).

Payload (the line ending is a \n):

```bash
curl -i -XPOST 'http://10.11.104.24:8086/write?db=influx_test_db' -d 'test_metric,host=server01,region=us-west cpucount=10,value=0.64
test_metric,host=server01,region=us-west cpucount=10,value=0.84' 
```

Query:

```sql
SELECT count(value) FROM test_metric

```
outputs:

```php
array(1) {
  [0] =>
  array(2) {
    'time' =>
    string(20) "1970-01-01T00:00:00Z"
    'count' =>
    int(1)
  }
}

```

As you can see; only one point has been written. This is also the case for the example you provide on the website. We are writing the data

**Comment by jwilder** [comment]
@thecodeassassin Use `--data-binary` instead of `-d`.

**Comment by thecodeassassin** [comment]
@jwilder still only one record is added to the database

**Comment by jwilder** [comment]
It looks like your points don't have timestamps so they will all get the same timestamp for the batch.  Since your writing two points with the same key (`test_metric,host=server01,region=us-west`), its writing duplicate points so only the last one would get written.  Try adding timestamps.

**Comment by thecodeassassin** [comment]
@jwilder yup this solved it thanks
