### ISSUE TITLE
admin UI should show tags on "select * from"

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3089]
Inspired by https://groups.google.com/d/msgid/influxdb/d82a2a89-d8f5-4c46-924d-6fe472266e4c%40googlegroups.com.

When using the admin UI, users have a reasonable expectation that `select * from measurement` will return the tags on that measurement as well as the fields. Currently only the fields are displayed on return.l

**Comment by toddboom** [comment]
This is fixed on the new admin interface as of mere moments ago.
