### ISSUE TITLE
[0.9.0] spaces in line protocol in tags

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#3092]
tried to add this line 
```
webfilter,uid='',category='suspicious',rulename='default',public_ip='52.28.100.45',blocktype='blocked domain',why='blocked domain',hostname='',website='c.byvue.com',client='alexandre-amd' TIME=1435003513,RQS=1
```
Generate a Error:bad timestamp
Because there are space in tag value
adding any quotes did not change the error...

**Comment by beckettsean** [comment]
In the line protocol, tag keys and values  and field keys should not be quoted, spaces and commas must always be escaped by a backslash `\`

For field values, strings should be single-quoted and spaces or commas need not be escaped.

See https://github.com/influxdb/influxdb/blob/master/tsdb/README.md for more.

**Comment by jwilder** [comment]
@beckettsean Small correction to what said.  Field values should use double-quotesif they are string values.  Not single quotes.

**Comment by dtouzeau** [comment]
Thanks!!!
