### ISSUE TITLE
[0.9.0] Improve documentation regarding naming convention

### ISSUE THREAD

**Issue by vptheron** [influxdb/influxdb#3093]
It is still very obscure what is the proper way to name measurements, tags, fields, etc.  Which characters are allowed? Which one should be escaped? How to escape? With a backslash, with double quotes, with simple quotes?

This information is spread everywhere in the doc and sometimes contradictory.  Please add a clear naming convention document.

**Comment by beckettsean** [comment]
Moved this issue to the documentation repo: https://github.com/influxdb/influxdb.com/issues/51

**Comment by beckettsean** [comment]
@vptheron the https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html and https://influxdb.com/docs/v0.9/guides/troubleshooting.html pages should the info or links to the info needed.
