### ISSUE TITLE
query 'select * from user' returns error even if there is a 'user' series

### ISSUE THREAD

**Issue by imlk** [influxdb/influxdb#3094]
Version : 0.9.0
Source: https://s3.amazonaws.com/influxdb/influxdb_0.9.0_amd64.deb
OS: Ubuntu

Steps : 
**#Create new db**
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"

**#Create and write to a series name 'user'**
curl -i -XPOST 'http://localhost:8086/write?db=mydb' -d 'user name="john"'

**#Create and write to a series name 'tenant'**
curl -i -XPOST 'http://localhost:8086/write?db=mydb' -d 'tenant name="mike"'

**#Query the series 'tenant', returns data**
curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM tenant"
<pre>
{
  "results": [
    {
      "series": [
        {
          "name": "tenant",
          "columns": [
            "time",
            "name"
          ],
          "values": [
            [
              "2015-06-22T22:33:17.003586465Z",
              "mike"
            ]
          ]
        }
      ]
    }
  ]
}
</pre>

**#Query the series 'user', returns error:**
curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM user"
<pre>"error parsing query: found USER, expected identifier at line 1, char 15" </pre>

I know that "USER" is kind of a keyword in InfluxDB 0.9, is that the reason why the SELECT query fails ? If so, are there any other ways we can operate a series named "user" ?

**Comment by beckettsean** [comment]
@imlk you need to surround the measurement name in double-quotes so that the parser knows it's an identifier and not the reserved word, `USER`. 

`SELECT * FROM "user"`

**Comment by imlk** [comment]
@beckettsean Thanks
