### ISSUE TITLE
running `influx -dump=true -database=mydb` causes wierd bash output issue

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3096]
When I run `influx -dump=true -database=mydb` my shell output gets a little weird. If I type anything after running the command, I get no output.

The following is an example of running `influx -dump=true -database=mydb` then typing 'hello' and then hitting enter:
![screen shot 2015-06-22 at 5 31 31 pm](https://cloud.githubusercontent.com/assets/1477539/8296394/d2429664-1904-11e5-8a51-7465f1638d54.png)

Similar closed issue [1833](https://github.com/influxdb/influxdb/issues/1833)

**Comment by mjdesa** [comment]
Another similar issue [2768](https://github.com/influxdb/influxdb/issues/2768)

**Comment by beckettsean** [comment]
closing in favor of #3235
