### ISSUE TITLE
get panic when use Write func in client

### ISSUE THREAD

**Issue by jasper-zhang** [influxdb/influxdb#3098]
When I use the client to write data to influxdb, I get the error message below:

```
# github.com/influxdb/influxdb/tsdb
..\..\..\influxdb\influxdb\tsdb\snapshot_writer.go:100: cannot use boltTxCloser literal (type *boltTxCloser) as type snapshot.FileWriter in assignment:
        *boltTxCloser does not implement snapshot.FileWriter (missing WriteTo method)
```

I just run the test case TestClient_Write in influxdb_test.go, I get the same message

**Comment by cheffo** [comment]
you are not using latest version of https://github.com/boltdb/bolt  - update bolt and the message will disappear.

**Comment by jasper-zhang** [comment]
Thanks!

**Comment by otoolep** [comment]
Let us know if you have any other issues. 

Thanks for resolving @cheffo
