### ISSUE TITLE
Writing data to 0.9 a mystery?

### ISSUE THREAD

**Issue by haf** [influxdb/influxdb#3100]
How do I write data? Using the sample schema doesn't seem to work: https://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html

Details here: https://github.com/mozilla-services/heka/issues/1581

**Comment by torkelo** [comment]
They changed the write json api, (without changing the docs)

```json 
"points": [
         {
            "measurement": "cpu_load",
            "tags": {
                "host": "server01",
                "core": "0"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.45
            }
        },
```

They changed "name" -> "measurement" in the point json object

**Comment by haf** [comment]
@torkelo tackar! I'm keeping the issue open as a documentation issue then.

**Comment by haf** [comment]
Someone should push their changes https://github.com/influxdb/influxdb.com/commit/be4a843ea5847121cc783bd84597389401cc853e /cc @jhorwit2

**Comment by beckettsean** [comment]
Closed in favor of https://github.com/influxdb/influxdb.com/issues/61
