### ISSUE TITLE
Newline at the end of multiline write results in error

### ISSUE THREAD

**Issue by romikk** [influxdb/influxdb#3106]
Single entry write works irrespective of extra newline at the end

_no extra newline:_
```
$> cat > ./txt
test3 value=1 1435072169453^C
$> curl -i -XPOST 'http://localhost:8086/write?db=metrics&precision=ms' -d @txt
HTTP/1.1 204 No Content
Request-Id: f1965c69-19bf-11e5-80c5-000000000000
X-Influxdb-Version: FIXME
Date: Tue, 23 Jun 2015 15:53:08 GMT
```
_newline at the end:_
```
$> cat > ./txt
test3 value=1 1435072169453
^C
$> curl -i -XPOST 'http://localhost:8086/write?db=metrics&precision=ms' -d @txt
HTTP/1.1 204 No Content
Request-Id: f70d2204-19bf-11e5-80c6-000000000000
X-Influxdb-Version: FIXME
Date: Tue, 23 Jun 2015 15:53:17 GMT
```

However multiple entry write fails if there is a newline after last entry.
_no extra newline:_
```
$> cat > ./txt
test3 value=1 1435072169453
test3 value=1 1435072169454^C
$> curl -i -XPOST 'http://localhost:8086/write?db=metrics&precision=ms' -d @txt
HTTP/1.1 204 No Content
Request-Id: 00de8ed1-19c0-11e5-80c7-000000000000
X-Influxdb-Version: FIXME
Date: Tue, 23 Jun 2015 15:53:34 GMT
```
_newline at the end:_
```
$> cat > ./txt
test3 value=1 1435072169453
test3 value=1 1435072169454
^C
$> curl -i -XPOST 'http://localhost:8086/write?db=metrics&precision=ms' -d @txt
HTTP/1.1 400 Bad Request
Request-Id: 05b20280-19c0-11e5-80c8-000000000000
X-Influxdb-Version: FIXME
Date: Tue, 23 Jun 2015 15:53:42 GMT
Content-Length: 13
Content-Type: text/plain; charset=utf-8

bad timestamp
```

I would expect it to work in all of above cases.

**Comment by jwilder** [comment]
Use `curl -i -XPOST 'http://localhost:8086/write?db=metrics&precision=ms' --data-binary @txt`

`-d` sets the `Content-Type` to `application/x-www-form-urlencoded` which causes problems with the newlines separators.

**Comment by beckettsean** [comment]
@romikk It sounds like @jwilder has identified the issue. Please reply and we will re-open if that fix doesn't address your problem.

**Comment by romikk** [comment]
@beckettsean this works for me, but i guess the docs need to be updated:
https://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html
examples there use 'curl -d'

**Comment by beckettsean** [comment]
Thanks, @romikk, the docs still have the `curl` syntax from the JSON protocol, it appears. I was aware of the `--data-binary` flag but I wasn't aware it was required. 

Created https://github.com/influxdb/influxdb.com/issues/65 to fix this in the docs.
