### ISSUE TITLE
Log that authentication cannot be enabled if there is no admin account created

### ISSUE THREAD

**Issue by ryanwalder** [influxdb/influxdb#3107]
If you enable auth in the config without creating a new admin user then restart the service there is no mention of this in the logs.

I know this is kind of expected behaviour, having it logged on startup would be good though something like:

[WARN] Unable to enable Authentication, no Admin users exist.

**Comment by beckettsean** [comment]
Related to #2193 and #2278

**Comment by gunnaraasen** [comment]
For 0.9.2, when authentication is turned on and no users exist, only the `CREATE USER [user] WITH PASSWORD [user] WITH ALL PRIVILEGES` command can be executed (see PR https://github.com/influxdb/influxdb/pull/3244). If one or more users exist, authorization is enforced as usual.

Once PR https://github.com/influxdb/influxdb/pull/3427 is merged, the logs will note whether authentication is enabled or disabled.
