### ISSUE TITLE
Arithmetic operators not working on Count() results in a join

### ISSUE THREAD

**Issue by Baddja** [influxdb/influxdb#3111]
```
select count(Listing.id) / count(Message.id) from Listing inner join Message
```

results in `Value cannot be evaluated for type &{count 10 [0xc208323270] <nil> false}`

What I want is the ratio of listings to messages over a given time. I am using grafana in raw query mode.
This is the full query:
```
select count(Listing.id) / count(Message.id) from Listing inner join Message where $timeFilter group by time($interval) order asc
```

**Comment by beckettsean** [comment]
`JOIN` is not supported in 0.9.0. What version of the database are you using?

**Comment by chrischang7312** [comment]
We are using v0.8 of influxdb. How do you join series and use arithmetic operators with the aggregate function `count()`?

**Comment by beckettsean** [comment]
@chrischang7312 I don't know the 0.8.x query syntax very well, but this page should have the details: https://influxdb.com/docs/v0.8/api/query_language.html, particularly the "Joining Series" section at the bottom.
