### ISSUE TITLE
[0.9.0] Unable to create a database with the name of a query paramater

### ISSUE THREAD

**Issue by ryanwalder** [influxdb/influxdb#3119]
Trying to create a database called `servers` returns an error:

`{"error":"error parsing query: found SERVERS, expected identifier at line 1, char 15"}`

You can focre it by creating it with double quotes `CREATE DATABASE "servers"` (single quotes throw the same error) but then you get into funky broken territory where it can't write/query it to it unless it's double quoted in the query.

I've run a few tests and get the same behaviour when trying to name a database a name that would be part of a query string (drop, show, database, where, etc...).

**Comment by otoolep** [comment]
Could you please show this issue in action via `curl` or the CLI?

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#bug-reports explains more.

**Comment by ryanwalder** [comment]
Apologies, I should have provided steps to replicate!

So, I want a database called `test`:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=CREATE DATABASE test"
{"results":[{}]}
```

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["test"]]}]}]}
```

No worries, works as expected.

Now I want one called `servers`:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=CREATE DATABASE servers"
{"error":"error parsing query: found SERVERS, expected identifier at line 1, char 17"}
```

OK, lets try single quotes:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=CREATE DATABASE 'servers'"
{"error":"error parsing query: found servers, expected identifier at line 1, char 16"}
```

Nope, lets try doubles:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=CREATE DATABASE \"servers\""
{"results":[{}]}
```

Cool, it created it:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["servers"]]}]}]}
```

Now if you check on the webinterface, you can't drop it:

`Failed to remove database: {"error":"error parsing query: found SERVERS, expected identifier at line 1, char 15"}`

Ok, let's drop it manually:

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=DROP DATABASE servers"
{"error":"error parsing query: found SERVERS, expected identifier at line 1, char 15"}
```

Nope


```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=DROP DATABASE 'servers'"
{"error":"error parsing query: found servers, expected identifier at line 1, char 14"}
```


I should have expected this

```
curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=DROP DATABASE \"servers\""
{"results":[{}]}
```

Cool, done.

So any query to a database creates this way must include the doublequotes when referencing a database that has a conflict with a query argument. This is also seen when using the following database names (that I've tested): `drop`, `select`, `where`, `database`, `user`, `show`, `grant`.

eg:

```
vagrant@coretest-dev:~$ curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=CREATE DATABASE \"grant\""
{"results":[{}]}
vagrant@coretest-dev:~$ curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=DROP DATABASE grant"
{"error":"error parsing query: found GRANT, expected identifier at line 1, char 15"}
vagrant@coretest-dev:~$ curl -GSs -w "\n" http://localhost:8086/query --data-urlencode "q=DROP DATABASE \"grant\""
{"results":[{}]}
```

Granted these are very likely going to be edge cases for database names.

**Comment by beckettsean** [comment]
When using a reserved word as an identifier, it's mandatory that the identifier be double-quoted so that the parser knows this particular occurrence of `SELECT` or `time` is referring to a database object and not a query language token.

I'm not sure why `servers` is a reserved word, though. @dgnorton, any ideas?

**Comment by beckettsean** [comment]
related to https://github.com/influxdb/influxdb/issues/3010, which refers to field keys, but measurements, tag keys, field keys, database names, and retention policy names all must be double-quoted if they are the same as a reserved word in InfluxQL.

We don't yet have a list of all reserved words, I'll make a docs issue for that.

**Comment by ryanwalder** [comment]
I guessed that may have been the case (much like the time I tried to grant Grant some permissions in PGSQL). Would it be worth potentially closing this ticket and raising a simpler one for adding double quotes by default to WebUI which is the main place this will affect the actual codebase?

**Comment by beckettsean** [comment]
@ryanwalder I think implicitly adding double-quotes to the web UI for all requests is a bit too magic. If folks insist on using reserved words as identifiers they incur a higher syntax load.
