### ISSUE TITLE
panic creating an enormous slice in hh/queue.go

### ISSUE THREAD

**Issue by daviesalex** [influxdb/influxdb#3120]
We are on 0.9.0 on RHEL7. Box has 128G RAM and 16 cores. Cluster of 3, r=3, n=3. 

Under high loads (2k nodes sending 20 odd metrics every 10 seconds), we get a panic that looks like this:
```
    Jun 23 15:32:31 hostname influxd: panic: runtime error: makeslice: len out of range
    Jun 23 15:32:31 hostname influxd: goroutine 1 [running]:
    Jun 23 15:32:31 hostname influxd: github.com/influxdb/influxdb/services/hh.(*segment).current(0xc208037180, 0x0, 0x0, 0x0, 0x0, 0x0)
    Jun 23 15:32:31 hostname influxd: /home/username/xxxx-packages/influxdb/gopath/src/github.com/influxdb/influxdb/services/hh/queue.go:499 +0x200
    Jun 23 15:32:31 hostname influxd: github.com/influxdb/influxdb/services/hh.(*queue).Open(0xc20804c660, 0x0, 0x0)
    Jun 23 15:32:31 hostname influxd: /home/username/xxxx-packages/influxdb/gopath/src/github.com/influxdb/influxdb/services/hh/queue.go:113 +0x246
    Jun 23 15:32:31 hostname influxd: github.com/influxdb/influxdb/services/hh.(*Processor).addQueue(0xc20804c5a0, 0x3, 0x0, 0x0, 0x0)
    Jun 23 15:32:31 hostname influxd: /home/username/xxxx-packages/influxdb/gopath/src/github.com/influxdb/influxdb/services/hh/processor.go:99 +0x37e
    Jun 23 15:32:31 hostname influxd: github.com/influxdb/influxdb/services/hh.(*Processor).loadQueues(0xc20804c5a0, 0x0, 0x0)
    Jun 23 15:32:31 hostname influxd: /home/username/xxxx-packages/influxdb/gopath/src/github.com/influxdb/influxdb/services/hh/processor.go:79 +0x1b5
    Jun 23 15:32:31 hostname influxd: github.com/influxdb/influxdb/services/hh.NewProcessor(0xc2080da2a0, 0x11, 0x7ffff7fc0d68, 0xc2080dbd20, 0x40000000, 0x0, 0x40eafe, 0x0, 0x0)
    Jun 23 15:32:31 hostname influxd: /home/username/xxxx-packages/influxdb/gopath/src/github.com/influxdb/influxdb/services/hh/processor.go:49 +0x3e4
```
From services/hh/queue.go (the panic is line 499):
```
    492         // read the record size
    493         sz, err := l.readUint64()
    494         if err != nil {
    495                 return nil, err
    496         }
    497         l.currentSize = int64(sz)
    498 
    499         b := make([]byte, sz)
    500         if err := l.readBytes(b); err != nil {
    501                 return nil, err
    502         }
```

From https://golang.org/src/runtime/slice.go, it looks like there is a max value on len (sz in this case) of uintptr(len) > maxmem/uintptr(t.elem.size) and we are hitting it. 

Its worth noting that we had about 2 million goroutines at this point (according to the panic), so while this is far outside something i'm expert at I wonder if that check can be done before calling make, and return an error back before this value rather than relying on a runtime panic.

**Comment by jwilder** [comment]
@daviesalex Can you provide a sample of the data being written?

Also, could you log a different issues regarding the 2 million goroutines and include the full stack trace in a gist? That should be investigated.

**Comment by daviesalex** [comment]
We were running tcollector on the client nodes, so its hitting the openTSDB endpoint and as it happens I have a tcpdump from about this time. There was about 40Mbit of this traffic on all 3 nodes:

```
put proc.interrupts 1434661386 0 type=ERR cpu=0 host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put proc.interrupts 1434661386 0 type=MIS cpu=0 host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.zoneallocs 1434661386 227931 node=0 type=hit host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.zoneallocs 1434661386 0 node=0 type=miss host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.foreign_allocs 1434661386 0 node=0 host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.allocation 1434661386 227893 node=0 type=local host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.allocation 1434661386 38 node=0 type=remote host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
put sys.numa.interleave 1434661386 19780 node=0 type=hit host=host--capture07 firm_bu=infrastructure firm_dc=chl firm_ev=xx
```

I will see if we can replicate the 2 million goroutine situation; I suspect we can under high loads. Sadly, we did not at this point have decent logging due to systemd's inability to play nicely with the stderr method of logging; we are going to work around this by having systemd call a shell script which calls influx.

**Comment by beckettsean** [comment]
@daviesalex Can you try with 0.9.1? Clustering in 0.9.0 was pre-alpha (meaning no one tested anything)

**Comment by daviesalex** [comment]
Sure - feel free to close this. Our internal conclusion was that the OpenTSDB endpoint does not work with clustering at all (we find this with 0.9.2 after upgrading; the data simply does not get replicated between nodes). We moved to using the native protocol for other reasons, which appears to work.

We have yet to really stress test the native protocol endpoint, but it appears to work much better!

**Comment by beckettsean** [comment]
@daviesalex glad the native endpoint is working well!
