### ISSUE TITLE
last(), first() commands print wrong date

### ISSUE THREAD

**Issue by biskit** [influxdb/influxdb#3121]
from cli, they all seem to print epoch value.
centos 6.6 - latest download

time    |                last
--------|------------------
1970-01-01T00:00:00Z   | 6.887297e+06

time    |                first
--------|---------------------
1970-01-01T00:00:00Z   |  0

**Comment by beckettsean** [comment]
This is documented behavior: https://influxdb.com/docs/v0.9/query_language/aggregate_functions.html

The issue to address this is https://github.com/influxdb/influxdb/issues/1577.

**Comment by biskit** [comment]
i see similarity with #3079 but still quite can't make connection with documented behavior. 

can someone post a query to get latest value and time of it from a series?
(that's because last() cannot be used with a 'group by')

**Comment by beckettsean** [comment]
@biskit what you're asking for is in #1577, not yet implemented. There is no query (yet) that will return the actual timestamp of a point if there is a function in the SELECT clause.
