### ISSUE TITLE
cmd buffer on cli

### ISSUE THREAD

**Issue by biskit** [influxdb/influxdb#3122]
does it use readline library?
1. does not seem to support vi or Emacs edit modes
2. behaves inconsistently in recall and history limits
centos 6.6 latest 0.9.0 download

**Comment by beckettsean** [comment]
@corylanou what are the details of the CLI history buffer?

This is not an actionable issue or bug, closing issue. 

@biskit support@influxdb.com (private convo) or influxdb@googlegroups.com (public list) are more appropriate channels to ask open-ended questions. GitHub is for bug reports and feature requests.

**Comment by biskit** [comment]
to rephrase:
documentation says .influx_history holds upto 10000 commands
1. scrolling up or down does not move up or down history all the time (hangs scrolling)
2. editing works with emacs mode sometimes and does not sometime

typically happens after moving back and forth the history a few times.
