### ISSUE TITLE
Trying to insert a number larger than the largest signed 64-bit number kills influxd

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3127]
On OSX with influx version 0.9 built from source

Running the command

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' -d 'test value=9223372036854775808'
```

kills influxd

**Comment by beckettsean** [comment]
@mjdesa what's the actual panic message in the logs?

Seems like the database should issue an error on the write that some values are out of bounds. @dgnorton @otoolep do we not have boundary checks on writes?

**Comment by mjdesa** [comment]
@beckettsean 

```
panic: unable to parse number value '9223372036854775808': strconv.ParseInt: parsing "9223372036854775808": value out of range
```
