### ISSUE TITLE
Can't seem to use arithmetic on values anymore 

### ISSUE THREAD

**Issue by timgriffiths** [influxdb/influxdb#3134]
Queries like this

SELECT (value * -1) FROM "measurement" WHERE tag1='value2' 

no longer work in version 0.9

**Comment by mjdesa** [comment]
@timgriffiths are the values you're storing integers?

**Comment by timgriffiths** [comment]
Yes i believe so, is there a query i can perform to validate this?

**Comment by mjdesa** [comment]
At the moment, there's not a way to validate. And currently arithmetic on integer values is unsupported.

**Comment by beckettsean** [comment]
closing in favor of #3000
