### ISSUE TITLE
influxdb configuration brittle

### ISSUE THREAD

**Issue by baboune** [influxdb/influxdb#3137]
Hi,

The current influxdb configuration crashes without any logs being generated anywhere.  To crash influxdb using the deb http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb, in the /etc/opt/influxdb/influxdb.conf, simply change:
auth-enabled = false
to
auth-enabled = "false"

Then 
$ /etc/init.d/influxdb start

And influxdb will produce a single log before crashing:
GOMAXPROCS set to 1

In general, the configuration file options should be better handled and not crash the DB without any warnings.

**Comment by miguelcnf** [comment]
This #3136 should make it so that the init script fails to start with proper return codes.

Also this is failing silently because the init script defaults all stdout logging to `/dev/null` and an error loading the config gets sent to stdout as far as I can see.

As a workaround you can set `STDOUT=/var/log/influxdb/influxd.log` in the `/etc/default/influxdb` configuration file - this will allow you to see the error messages.

**Comment by baboune** [comment]
Yes, making sure STDOUT is set to /var/log/influxdb.log fixes this issue.

**Comment by baboune** [comment]
Additionally, there is simply no documentation about the configuration options in 0.9.

The often referred:
$ influxd config > generated.conf
Just launches the influxd shell.

**Comment by beckettsean** [comment]
@baboune `influx` launches the shell, `influxd config > ` generates a conf file. Note the influx vs influx**d**

Agreed we need better documentation on the config file. That will be part of the 0.9.2 docs push if not 0.9.1 next week. https://github.com/influxdb/influxdb.com/issues/74

**Comment by baboune** [comment]
Hi,
Yes you are correct. I was using the other command "influx" instead of "influxd".
"influxd" works. 


     On Friday, June 26, 2015 9:40 PM, Sean Beckett <notifications@github.com> wrote:
   

 @baboune influx launches the shell, influxd config > generates a conf file. Note the influx vs influxdAgreed we need better documentation on the config file. That will be part of the 0.9.2 docs push if not 0.9.1 next week. influxdb/influxdb.com#74—
