### ISSUE TITLE
[0.9.0] duration of retention policy not enforced?

### ISSUE THREAD

**Issue by robinroestenburg** [influxdb/influxdb#3138]
I have a question about the duration of retention policies.

The following policies are defined:

```
> show retention policies itrp_stats
name		duration	replicaN	default
6_hours		6h0m0s		1		true
7_days		168h0m0s	1		false
6_months	4368h0m0s	1		false
2_years		17472h0m0s	1		false
```

I would expect all data older than 6 hours to be deleted from the `6_hours` policy. That does not seem to be the case, as I can still query for points older than 6 hours. For example, querying for points 2 days ago:

```
> select value from "6_hours"."rack.requests.response_time" where \
     environment='production' and time > now() - 2d limit 1;
name: rack.requests.response_time
---------------------------------
time			value
2015-06-23T14:39:39Z	295
```

Is my expectation correct? If not, how should I configure my policies to achieve the desired behavior (delete data older than 6 hours) in this case?

**Comment by otoolep** [comment]
There was a significant bug in 0.9.0 around shard management. Do you see the same behaviour with the nightly builds?

https://influxdb.com/download/index.html

**Comment by robinroestenburg** [comment]
Trying out the nightly build today, I will let you know the results.

**Comment by robinroestenburg** [comment]
That fixed it @otoolep.

I now see log messages that shard groups are being deleted:

```
2015-06-26 17:00:00.973131500  [retention] 2015/06/26 17:00:00 retention policy enforcement check commencing
2015-06-26 17:00:00.973318500  [retention] 2015/06/26 17:00:00 retention policy shard deletion check commencing
2015-06-26 17:00:00.976569500  [retention] 2015/06/26 17:00:00 deleted shard group 3 from database itrp_stats, retention policy 6_hours
```

Data outside of the retention policy is no longer stored and cannot be queried anymore.

Thanks!

**Comment by otoolep** [comment]
Great! Thanks @robinroestenburg

**Comment by otoolep** [comment]
And thanks again to @vladlopes who fixed the issue.
