### ISSUE TITLE
Using Line protocol to write points and then using derivative functions crashes the database

### ISSUE THREAD

**Issue by anandmani-lab49** [influxdb/influxdb#3139]
This does not happen when using json to write data. Here are the steps to reproduce: 
-- Create Database
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE testDerivative"
-- Insert some data
curl -XPOST 'http://localhost:8086/write?db=testDerivative&precision=ms' -d 'cpu,host=server01,region=uswest value=123 1435256752991'
curl -XPOST 'http://localhost:8086/write?db=testDerivative&precision=ms' -d 'cpu,host=server01,region=uswest value=234 1435256760819'
-- Query using derivative
curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=testDerivative" --data-urlencode "q=SELECT derivative(value) FROM cpu WHERE host='server01'"

Boom database is down. Please advise.

**Comment by jwilder** [comment]
You are writing points as integers which was not possible before with the JSON API.  There is bug in 0.9.0 with a pending fix #2956 that has not been merged yet. 

As a workaround, you can write your points as floats by adding a `.0` to each one.

**Comment by gunnaraasen** [comment]
Closing in favor of #2956. Thanks for the report!
