### ISSUE TITLE
[0.9.0] Where `database` appears when writing to the HTTP API is wrong in the documentation

### ISSUE THREAD

**Issue by contentfree** [influxdb/influxdb#3145]
The [docs for reading and writing](https://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html) state that "**database** must be specified in the request body and must already exist." However, the example clearly shows that it's not in the request body but in the request query string. (And also it's called `db` and not `database`)

**Comment by gunnaraasen** [comment]
Thanks @contentfree. I've moved this issue to the [influxdb.com website repo](https://github.com/influxdb/influxdb.com).
