### ISSUE TITLE
Inserting multiple mesurements/points in the same post throws error

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb#3147]
I have an issue inserting multiple measurements, its failing with "bad time stamp"
but the same time stamp works perfect when inserting just one measurement/points

is it the write syntax( I got this syntax from Influxdb document)
```
lab@influxdb0:~$ curl -i -XPOST 'http://10.91.38.210:8086/write?db=testdb&rp=test&precision=s' -d 'cpu_load_short,host=server01,region=us-west value=0.64 cpu_load_short,host=server02,region=us-west value=0.55 1435281408 cpu_load_short1,direction=in,host=server01,region=us-west value=23422.0 1435281408'

HTTP/1.1 400 Bad Request

Request-Id: 6d76f70b-1ba1-11e5-8013-000000000000

X-Influxdb-Version: FIXME

Date: Fri, 26 Jun 2015 01:19:44 GMT

Content-Length: 13

Content-Type: text/plain; charset=utf-8



bad timestamplab@influxdb0:~$ 
```

**Comment by otoolep** [comment]
@jwilder -- perhaps the answer is immediately obvious to you?

**Comment by jwilder** [comment]
With curl, use --data-binary instead of -d

**Comment by prashleo** [comment]
Same issue :(

$ curl -i -XPOST 'http://10.91.38.210:8086/write?db=testdb&rp=test&precision=s'  --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1435281408 cpu_load_short1,host=server02,region=us-west value=0.55 1435281408'
HTTP/1.1 400 Bad Request
Request-Id: 82c5680d-1baa-11e5-8016-000000000000
X-Influxdb-Version: FIXME
Date: Fri, 26 Jun 2015 02:24:45 GMT
Content-Length: 13
Content-Type: text/plain; charset=utf-8

bad timestamp

**Comment by jwilder** [comment]
I think there is a problem with newlines and your command-line.  If you are using bash.  You could try [ansi C quoting](http://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) the string like:

```
curl -i -XPOST 'http://127.0.0.1:8086/write?db=testdb&rp=test&precision=s' --data-binary $'cpu_load_short,host=server01,region=us-west value=0.64 1435281408\ncpu_load_short1,host=server02,region=us-west value=0.55 1435281408'
```

Alternatively, you could put each line in a file and then use:

```
curl -i -XPOST 'http://127.0.0.1:8086/write?db=testdb&rp=test&precision=s' --data-binary @/path/to/points
```

**Comment by prashleo** [comment]
Thanks Jwilder, ansi C quoting did the trick.

**Comment by rajeshpp** [comment]
> I think there is a problem with newlines and your command-line. If you are using bash. You could try [ansi C quoting](http://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) the string like:
> 
> ```
> curl -i -XPOST 'http://127.0.0.1:8086/write?db=testdb&rp=test&precision=s' --data-binary $'cpu_load_short,host=server01,region=us-west value=0.64 1435281408\ncpu_load_short1,host=server02,region=us-west value=0.55 1435281408'
> ```
> 
> Alternatively, you could put each line in a file and then use:
> 
> ```
> curl -i -XPOST 'http://127.0.0.1:8086/write?db=testdb&rp=test&precision=s' --data-binary @/path/to/points
> ```

How to use it, if there are variables to be passed as below:
curl -i -XPOST 'http://127.0.0.1:8086/write?db=test' --data-binary $"inspec_reporting,profile=$profile success_control=$success_control,failure_control=$failure_control,skip_control=$skip_control,success_summary=$success_summary,failure_summary=$failure_summary,skip_summary=$skip_summary"

The above one is not working.
