### ISSUE TITLE
Add binary tgz generation to build packaging script

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3149]
A simple tgz file should be produced as part of the packaging process.

**Comment by otoolep** [comment]
@pauldix -- the packaging script now generates a compressed tarball, and uploads it to S3. We should update the Downloads page.

**Comment by beckettsean** [comment]
@otoolep Can you make an issue or PR on the docs repo?

**Comment by otoolep** [comment]
I think you just did @beckettsean ?

**Comment by beckettsean** [comment]
@otoolep yeah I did, since I write that note I ended up needing to add some more things to the downloads page.
