### ISSUE TITLE
Documentation for v0.9

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb#3153]
Please write more documentation for v0.9. Starting to lose patience with so many things that do not work. Can't just guess or try all options in the world until we get to a working solution, especially with queries. Moreover there's a mix of documentation for v7, v8 and v9 which makes it even more important for you to continue documenting v9 and stabilizing your query language. Thank you!

**Comment by marcosnils** [comment]
@skynet I now it might not be like a definitive solution, but have you tried using the .MD files located in this repo?. I find them really updated in comparison to what's on the website.

**Comment by skynet** [comment]
That's a great tip, thank you.

**Comment by beckettsean** [comment]
@skynet we're trying to catch up, but it takes as long to write good docs as it does to write good code, so we're always a bit behind on the support team. If there are specific issues you want addressed in the docs, open an issue on the docs repo: https://github.com/influxdb/influxdb.com/issues/new

**Comment by deebs031** [comment]
+1 
Need good documentation. Should be checked in in-sync with code feature changes IMO... No doc no merge, maybe...

**Comment by beckettsean** [comment]
@deebs031 with the new RC pace that is the plan. Pre 0.9.0 release things were changing much more quickly. It was impossible to keep up with 4 RCs a week when fundamental things like the JSON and line protocol were changing with each new version (they weren't really RCs, jsut got stuck in an unfortunate naming convention until 0.9.0 final.) We need another two weeks or so to dig out of our documentation debt, and then post 0.9.2 there should be docs queued up for each release.
