### ISSUE TITLE
Query isses when a tag is named group

### ISSUE THREAD

**Issue by yee379** [influxdb/influxdb#3162]
i have the following series:

```
show series from "network.kpi"

_key	group	prefix	prefix_len
network.kpi,group=subnet,prefix=172.21.58.0,prefix_len=24	subnet	172.21.58.0	24
```
so queries like the following work fine:

```
select mean(count) from "network.kpi" where prefix='172.21.58.0'
```

however, this does not work:

```
select mean(count) from "network.kpi" where prefix='172.21.58.0' and group='subnet'
QueryERROR: {"error":"error parsing query: found GROUP, expected identifier, string, number, bool at line 1, char 70"}
```

i'm on v0.9.0.

**Comment by beckettsean** [comment]
`GROUP` is a reserved word in the query language. If you are using it in a context where you don't mean to start a `GROUP BY` clause, you must double-quote it so the parser knows it is an identifier and not a keyword. E.g.

`select mean(count) from "network.kpi" where prefix='172.21.58.0' and "group"='subnet'
