### ISSUE TITLE
Logging enhancement

### ISSUE THREAD

**Issue by Comradin** [influxdb/influxdb#3164]
The current logging capabilities of influxdb suffer from the poor basic golang log package. There are no different log levels like info, warning and error being written into different logfiles.

Due to the current state of influxdb it would be great to have separate logs to look into when searching for errors.

Please consider using packages like:

github.com/golang/glog (Google logging library)
github.com/op/go-logging

Regards,
Marcus

**Comment by otoolep** [comment]
Thanks for the references @Comradin -- we'll take a look.

**Comment by pauldix** [comment]
We won't be doing log levels because they end up being too noisey. Instead, we're opting for being able to turn on trace logging at different areas of the system. For example, turning on write trace logging, or raft trace logging, or BoltDB, or trace logging around distributed queries, etc.

Is there some specific area you're trying to get more debug output for?

**Comment by Comradin** [comment]
Hello Paul, excellent question.

As the software is kind of unstable in the current state I would like to see different log files for different kinds of logs. Separating the info loglevel from the errors and even the panic logs would help (me) to find the necessary bits of information to dig into the possible problem my cluster may have just experienced. Having a single log file for all of these different kind of informations seems unfortunate to me.

I know its not the best move to propose a different log handling after the 0.9 release. Should have done this already when you guys started rewriting the software from ground up, but I have not done any serious tests with influxdb in the times of 0.8 and before and so its just now that Im feeling unhappy with the current log solution imposed by the default (*simple?*) golang log package.

**Comment by deric** [comment]
Is it possible to log rejected metrics (incorrect format, too many attributes, etc.) in 0.9? I'm sending metrics over UDP collectd protocol and some of them are not written to influxdb.

**Comment by zeroXten** [comment]
I am currently getting parse errors for the graphite input:

    [graphite] 2015/07/03 09:42:25 unable to parse data: received "" which doesn't have three fields

Why I'm getting that is another question. There isn't any other context, and the system generating the graphite data hasn't changed. Tcpdump shows legit looking graphite data coming in on port 2003.

Strace it is I guess o_O

**Comment by iNikem** [comment]
Is there any documentation at all about different logging events? https://influxdb.com/docs/v0.9/administration/logs.html does not say anything about it. Our problem right now is the huge amount of logs being generated (like a couple of megabytes per minute) and we would like to decrease it.

**Comment by beckettsean** [comment]
@iNikem you can disable logging of continuous queries in the config file. I don't believe anything else is configurable yet. It seems odd that your logs are growing that quickly, what are most of the log lines?

**Comment by iNikem** [comment]
Hell lot of
```
[http] 2015/08/05 18:52:00 10.0.0.116 - plumbr [05/Aug/2015:18:52:00 +0000] GET /query?db=plumbr&epoch=ms&p=%5BREDACTED%5D&q=select+%2A+from+%22lockWaitDuration%22+where+jvmId%3D%278HCn_a6wh5tgAXIvUlR9qaE5s8-uUJLcwQsACoLDHSI%23%27+and+time+%3E%3D+1438800718230ms&u=plumbr HTTP/1.1 200 40 - okhttp/2.4.0 0dd636db-3ba3-11e5-8aa9-000000000000 686.344µs
```

Like 2.5M+ lines during last 7 hours

**Comment by beckettsean** [comment]
Currently all queries are logged. It looks like you've got some client or a collection of clients that's making 100 queries per second or so. Do you have lots of grafana users with dashboards refreshed every second?

**Comment by pauldix** [comment]
We should probably add an option to disable query logging

**Comment by iNikem** [comment]
@beckettsean It is our own application, that queries data from Influx. And yes, current rate is about 100 queries per second. And we expect this to grow. So disabling query logging would be GREAT.

**Comment by beckettsean** [comment]
Created #3566 to address disabling query logging.

**Comment by tmonk42** [comment]
I'm injecting metrics via HTTP, and I keep filling my logs up with those messages as well :-P

**Comment by corylanou** [comment]
This should be trivial once the config option is added.  That service already has a dedicated logger and we silence it in our testing.

**Comment by jwilder** [comment]
I believe this will disable HTTP logging.

```
[http]
  log-enabled = false
```

**Comment by otoolep** [comment]
Yeah, what @jwilder points out should be what you need.

**Comment by otoolep** [comment]
I don't believe there is anything more to do here.
