### ISSUE TITLE
[0.9.1-rc1] Database not found error not in json

### ISSUE THREAD

**Issue by cburki** [influxdb/influxdb#3170]
When writing into a non existing database, the error message is not in a JSON structure like other error messages.

curl -X POST 'http://192.168.1.1:8086/write?db=notexist' --data-binary @TEST_VALUES
database not found: "notexist"

curl -X POST 'http://192.168.1.1:8086/write?db=test&u=notexist&p=password' --data-binary @TEST_VALUES
{"error":"user not found"}

I think it is better to embedded all error messages in a JSON structure.

**Comment by benfb** [comment]
This seems to be related to [these lines](https://github.com/influxdb/influxdb/blob/master/services/httpd/handler.go#L350-L356) or the way errors are handled. A search reveals that "user not found" is never returned directly, but rather as an error which may be relevant.

**Comment by otoolep** [comment]
This should not be too difficult. Simply trace through the code to learn where errors are created, and use Go's built-in JSON encoding to spit out a JSON error.

**Comment by jademcgough** [comment]
Grabbing this.

**Comment by aneshas** [comment]
Hey @jademcgough still working on this issue?

**Comment by jademcgough** [comment]
@aneshas will try to have a PR ready this weekend, I'm still ramping up my golang so I spent a few hours just familiarizing myself with the codebase :)

**Comment by aneshas** [comment]
@jademcgough Oh, ok no problem, just let us know if you decide to pass it on :)
