### ISSUE TITLE
"as" only works for some functions + inconsistent column naming

### ISSUE THREAD

**Issue by fxkr** [influxdb/influxdb#3173]
influxdb 0.9.1-rc1

"as" works for sum / min - the column in the result is called "foo":

<pre>
> select <b>sum(rx_bytes) as foo</b> from port_rx_bytes where time > now() - 1h group by time(10m) limit 1
name: port_rx_bytes
-------------------
time			<b>foo</b>
2015-06-29T08:20:00Z	798336
</pre>

"as" doesn't work for derivative / non_negative_derivative - the column in the result isn't called "foo":

<pre>
> select <b>derivative(rx_bytes) as foo</b> from port_rx_bytes where time > now() - 1h group by time(10m) limit 1
name: port_rx_bytes
-------------------
time				<b>rx_bytes</b>
2015-06-29T08:16:32.916135011Z	0
</pre>

Additionally, even when no "as" is used, the column names are determined differently:

<pre>
> select <b>derivative(rx_bytes)</b> from port_rx_bytes where time > now() - 1h group by time(10m) limit 1
name: port_rx_bytes
-------------------
time				<b>rx_bytes</b>
2015-06-29T08:18:37.928172484Z	0

> select <b>sum(rx_bytes)</b> from port_rx_bytes where time > now() - 1h group by time(10m) limit 1
name: port_rx_bytes
-------------------
time			<b>sum</b>
2015-06-29T08:10:00Z	290304
</pre>

**Comment by chrishiestand** [comment]
In 0.9.2 the derivative column is always named `value` instead of what it should be.

**Comment by corylanou** [comment]
This is fixed in this PR: https://github.com/influxdb/influxdb/pull/3564

Column name should always be the aggregate function name, so in this case, it would be `derivative` unless you alias it (which now works again).

**Comment by chrishiestand** [comment]
Thank you @corylanou
