### ISSUE TITLE
0.9.1 cluster consistency

### ISSUE THREAD

**Issue by ecables** [influxdb/influxdb#3182]
Just upgraded to the latest 0.9.1 RC, and I'm seeing temporarily inconsistent data on one of the nodes in a 3-node cluster -- "db2," which eventually becomes consistent.

The data looks something like this:
```
db1 == 46371089468 (2015-06-29T19:43:00Z)
db2 == 83275287536 (2015-06-29T19:43:00Z)
db3 == 46371089468 (2015-06-29T19:43:00Z)
```

db2 eventually becomes consistent after about 10 minutes, and some messages like the following in the db2 influxd.log:
```
[retention] 2015/06/29 12:53:09 retention policy shard deletion check commencing
[shard] 2015/06/29 12:53:49 flush 76979 points in 3.049s
[shard] 2015/06/29 12:53:56 flush 78022 points in 6.707s
[shard] 2015/06/29 12:54:03 flush 77341 points in 6.800s
[shard] 2015/06/29 12:54:09 flush 72951 points in 6.630s
[shard] 2015/06/29 12:54:17 flush 76089 points in 7.099s
[shard] 2015/06/29 12:54:24 flush 73939 points in 7.423s
[shard] 2015/06/29 12:54:31 flush 76947 points in 6.527s
[shard] 2015/06/29 12:54:38 flush 76889 points in 7.417s
```

Then the data is consistent again:
```
db1 == 46371089468 (2015-06-29T19:43:00Z)
db2 == 46371089468 (2015-06-29T19:43:00Z)
db3 == 46371089468 (2015-06-29T19:43:00Z)
```

I'm seeing this pretty frequently on db2 (inconsistent data point once every 10-15 mins) -- any ideas?

**Comment by otoolep** [comment]
The 0.9 release has a "hinted handoff" service, which writes points to nodes that were unavailable when the write originally arrived at the cluster. Is your cluster suffering from partition issues?

The other cycle in the system at about this period is the WAL flush, which defaults to 10 minutes:

https://github.com/influxdb/influxdb/blob/master/tsdb/config.go#L28

There may be something going on there, but if it is the WAL, it should not produce these results.

cc @jwilder @benbjohnson

**Comment by ecables** [comment]
There are no known partitioning issues that I am aware of, and I haven't seen anything in the influxd.log file on db1 or db3 to indicate that db2's health is degraded at any time. If there were issues with the system, such that it was becoming partitioned from raft's perspective, what kind of error messages should I expect to see in the log file?

The WAL flush seems to resolve the inconsistency, and brings the data point into consistency with the other nodes in the cluster, so the initial write seems to be the problem. Unfortunately, the WAL flush seems to correlate to the timing of these inconsistent data points -- could this be related to system resource consumption and/or a race condition?

```
[shard] 2015/06/29 16:55:15 flush 63489 points in 2.656s
[shard] 2015/06/29 16:55:25 flush 64754 points in 10.099s
[shard] 2015/06/29 16:55:38 flush 66312 points in 12.506s
[shard] 2015/06/29 16:55:53 flush 65574 points in 14.869s
[shard] 2015/06/29 16:56:09 flush 66511 points in 16.269s
[shard] 2015/06/29 16:56:26 flush 60921 points in 17.289s
[shard] 2015/06/29 16:56:42 flush 64931 points in 15.362s

db1 == 33721051239 (2015-06-29T23:56:00Z)
db2 == 40650822353 (2015-06-29T23:56:00Z)
db3 == 33721051239 (2015-06-29T23:56:00Z)
```

```
[shard] 2015/06/29 17:07:04 flush 60151 points in 3.464s
[shard] 2015/06/29 17:07:14 flush 59713 points in 10.356s
[shard] 2015/06/29 17:07:28 flush 64074 points in 13.943s
[shard] 2015/06/29 17:07:43 flush 63592 points in 14.900s
[shard] 2015/06/29 17:08:00 flush 65347 points in 16.953s
[shard] 2015/06/29 17:08:17 flush 62000 points in 16.926s
[shard] 2015/06/29 17:08:37 flush 66270 points in 20.127s
[shard] 2015/06/29 17:08:52 flush 65267 points in 14.535s

db1 == 35944812258 (2015-06-30T00:08:00Z)
db2 == 37647503058 (2015-06-30T00:08:00Z)
db3 == 35944812258 (2015-06-30T00:08:00Z)
```

**Comment by ecables** [comment]
I'll add that I ran some continuous ping tests, with a timeout value of 0.25s from both db1 and db3, towards db2, and the results were not indicative of any kind of network partition. During said test, I continued to see inconsistent data points being written during WAL flush events, but only during these flush events.

**Comment by otoolep** [comment]
To be clear -- the WAL is meant to be fully accessible during queries. After the data is written to the system, are you seeing different after the WAL flush, than before the WAL flush?

**Comment by ecables** [comment]
After the WAL flush all previous inconsistent data points are corrected, but during the WAL flush a new inconsistent data point is written. Does that make sense?

Strangely, the WAL flush seems to be taking significantly longer on db2 than db1 or db3 nodes.
db1:
```
[shard] 2015/06/29 17:35:47 flush 52042 points in 1.061s
[shard] 2015/06/29 17:35:48 flush 51714 points in 1.080s
[shard] 2015/06/29 17:35:49 flush 51842 points in 1.094s
[shard] 2015/06/29 17:35:50 flush 51673 points in 0.878s
[shard] 2015/06/29 17:35:51 flush 52223 points in 1.205s
[shard] 2015/06/29 17:35:53 flush 52056 points in 1.627s
[shard] 2015/06/29 17:35:55 flush 52910 points in 1.557s
[shard] 2015/06/29 17:35:57 flush 52710 points in 1.831s
```

db2:
```
[shard] 2015/06/29 17:31:31 flush 61543 points in 17.682s
[shard] 2015/06/29 17:31:45 flush 62280 points in 13.991s
[shard] 2015/06/29 17:32:04 flush 62326 points in 18.551s
[shard] 2015/06/29 17:32:22 flush 63016 points in 18.182s
[shard] 2015/06/29 17:32:43 flush 63671 points in 20.215s
```

db3:
```
[shard] 2015/06/29 17:35:29 flush 52086 points in 0.983s
[shard] 2015/06/29 17:35:31 flush 51667 points in 1.185s
[shard] 2015/06/29 17:35:32 flush 51823 points in 1.265s
[shard] 2015/06/29 17:35:34 flush 51627 points in 1.531s
[shard] 2015/06/29 17:35:36 flush 52230 points in 1.914s
[shard] 2015/06/29 17:35:38 flush 52113 points in 1.942s
[shard] 2015/06/29 17:35:40 flush 52878 points in 2.033s
[shard] 2015/06/29 17:35:42 flush 52746 points in 2.044s
```

Any ideas on why db2 would be so much slower, and also be the node experiencing these inconsistent data points during the flush process? These nodes all have identical hardware.

**Comment by benbjohnson** [comment]
@ecables The WAL flush currently blocks reads while it's occurring. We're going to fix that in the future but for now it could be that your queries are executing against the snapshot of `db2` when it first began flushing vs the queries that are executing against the snapshot of `db1` and `db3` when they first started executing. Essentially, `db2` data could be 20s+ old.

How long do your `db2` queries take to execute?

**Comment by pauldix** [comment]
@benbjohnson this begs the question, should we lower the size of the WAL so that flushes complete faster?

**Comment by benbjohnson** [comment]
@pauldix Lowering the size of the WAL can help but it also has limits since if the WAL is too small then it won't allows us to batch multiple points together per series. It sounds like the really long wait times are a hardware issue here.

A better approach is to change the flushes so that they're non-blocking but that's more involved. We'll  need to do a copy-on-write cache which has GC implications but at least it'll make flushes less of an issue.

**Comment by ecables** [comment]
Just to be clear, the hardware between nodes in the cluster differs, but is not malfunctioning. db1 and db3 are SSD backed, while db2 is not. The resulting difference in WAL flush times (1-2s for db1/db3 vs. 17-20s for db2), appears to be triggering this data inconsistency.

**Comment by beckettsean** [comment]
Major clustering and WAL changes in 0.9.3, please test with that and let us know if you can reproduce.
