### ISSUE TITLE
server will not start (after 0.8.8 -> 0.9.0 -> 0.8.8 ... maybe)

### ISSUE THREAD

**Issue by rca** [influxdb/influxdb#3187]
I've been running influxdb 0.8.8 on CoreOS using the [tutum docker image](https://registry.hub.docker.com/u/tutum/influxdb/) on docker.com.  Earlier today the server running this container rebooted and subsequently pulled down the 0.9.0 image, started up and nothing was working.  Realizing this, I pinned the version down to 0.8.8 and the server started serving data again.  Things seemed to be working fine for a few hours and then the server stopped responding to requests.  I assume something happened to the data directory when version 0.9 touched it but am not sure.

When the server is running correctly, I see the following in the logs:

```
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] Starting admin interface on port 8083
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] Graphite input plugins is disabled
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] Collectd input plugins is disabled
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] UDP server is disabled
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] Starting Http Api server on port 8086
Jun 29 22:22:17 ip-172-30-0-12.ec2.internal docker[3429]: [06/29/15 22:22:17] [INFO] Reporting stats: &client.Series{Name:"reports", Columns:[]string{"os", "arch", "id", "version"}, Points:[][]interface {}{[]interface {}{"linux", "amd64", "bb7377f141157ddd", "0.8.8"}}}
```

Now, when the server starts up the lines `Starting admin interface on port 8083` and `Starting Http Api server on port 8086` don't appear.  Placing the server in debug mode doesn't show anything very useful either.

While recovering the existing data isn't critical, I'd like to understand how to recover from this.

For now, I've archived the corrupted data directory and am starting from scratch using 0.9.

Thanks.

**Comment by beckettsean** [comment]
@rca there is no currently supported upgrade path from 0.8.x to 0.9.x, although one is in development. The behavior is undefined right now, but certainly won't work in any meaningful way. I don't know if there's a way to recover. 

How did 0.9.0 get launched? What config file did it use, and can you include that and your 0.8.8 config here? 

The migration work is happening in https://github.com/influxdb/influxdb/issues/2378, perhaps @corylanou has learned some useful things while working on the migration tool.

**Comment by rca** [comment]
Thanks for the response, @beckettsean.

Here is the service section of the CoreOS unit file:

```
[Service]
TimeoutStartSec=300
Restart=always
EnvironmentFile=/etc/environment
ExecStartPre=-/usr/bin/docker kill influxdb
ExecStartPre=-/usr/bin/docker rm influxdb
ExecStartPre=/usr/bin/docker pull tutum/influxdb:0.8.8
ExecStart=/usr/bin/docker run --memory 6g --name influxdb -p 8083:8083 -p 8086:8086 --expose 8090 --expose 8099 --volume /srv/influxdb:/data tutum/influxdb:0.8.8
ExecStop=/usr/bin/docker stop influxdb
```

Prior to today, the `docker pull` and `docker run` commands were simply referencing `tutum/influxdb` rather than pinning down version 0.8.8.  When the machine rebooted and re-launched influxdb, it grabbed the latest version which was 0.9.  In order to get things working again, unfortunately with no historical data, I pinned the version down as seen above.

After posting this, I read about 0.9 and the API is quite different, so I'm sticking to 0.8.8 for the time being.  

The config file is the vanilla one provided by the tutum image at https://github.com/tutumcloud/influxdb/blob/master/0.8.8/config.toml

Again, data recovery isn't super critical, but would be nice.  Thanks!

**Comment by smedefind** [comment]
We just ran into this problem after an accidental upgrade via Chef.

After leaving InfluxDB running for a few hours it finally came back up and was accessible again.

Strace showed it scanning all the data files while we were waiting for it to come up. So my guess it was doing some sort of repair to damage caused by the unexpected 0.9.0 upgrade.

**Comment by rca** [comment]
@smedefind Thanks for mentioning this.  I will launch an instance with the old data volume and report back.  It would be great to have a message in the logs saying it's scanning the filesystem.  Ideally with some sort of indicator that it's still working.  Even in debug mode, nothing was mentioned and raft logs overtake all other messages.  Thanks again!
