### ISSUE TITLE
0.9.1-rc1 group by does not work

### ISSUE THREAD

**Issue by cailiang9** [influxdb/influxdb#3190]
SELECT mean(value) FROM heartrate WHERE device_id='6' and time < now() GROUP BY time(1m)

{"results":[{"series":[{"name":"heartrate","columns":["time","mean"],"values":[["1970-01-01T00:00:00Z",null]]}]}]}

There are still a lot of other functions that does not work. What is wrong?

**Comment by jhorwit2** [comment]
This also doesn't work with other aggregators like count. :(

**Comment by mjdesa** [comment]
@cailiang9 if no lower bound on `time` is set influx assumes that you want to go back to epoch.

Try something like this:

```sql
SELECT mean(value) FROM heartrate WHERE device_id='6' and time > now() - 1h GROUP BY time(1m)
```

**Comment by jhorwit2** [comment]
@mjdesa That still doesn't make sense then. Is the `where time` query have some upper bound limit on how far back it can go?

**Comment by mjdesa** [comment]
@jhorwit2 There's not a limit on how far back it can go, but `group by` can only return a maximum of 100,000 buckets.

See [2702](https://github.com/influxdb/influxdb/issues/2702)

**Comment by cailiang9** [comment]
That's my original query. The output is:

Execute QueryERROR: {"error":"error parsing query: found GROUP, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 76"}

Is influxdb 0.9 in stable release ? I think such operation is very basic.

**Comment by mjdesa** [comment]
@cailiang9 What's your original query?

**Comment by cailiang9** [comment]
SELECT mean(value) FROM heartrate WHERE device_id='6' and time > now()-1d GROUP BY time(1m)

**Comment by cailiang9** [comment]
Is it because there is no data in some time buckets?

**Comment by cailiang9** [comment]
I know the reason: If there is no blank around '-', it return: error parsing query: found GROUP, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 78

**Comment by beckettsean** [comment]
This is documented in "Whitespace Requirements" on https://influxdb.com/docs/v0.9/query_language/query_syntax.html

**Comment by cailiang9** [comment]
That's weird and important, there should be a notice in getting start page.
