### ISSUE TITLE
No error code for bad query

### ISSUE THREAD

**Issue by kwando** [influxdb/influxdb#3191]
This query
```
SELECT count(*) FROM datapoints WHERE time > now() - 1h GROUP BY time(10m)
```
results in the following error, which is returned with a 2xx HTTP status code:
```
{"results"=>[{"error"=>"expected field argument in count()"}]}
```
I'm expecting a 4xx HTTP status code in this case.

Possibly related to #3181

**Comment by mjdesa** [comment]
@kwando this behavior is expected.

A 4XX is returned if the request could not be understood. 2XX is returned if Influx could understand the request, but processing cannot be completed. In this case a JSON response is included in the body of the response with additional error information.

To achieve the result that I think you're looking for try specifying a field key in place of `*` in your query.

For example:

```
SELECT count(value) FROM datapoints WHERE time > now() - 1h GROUP BY time(10m)
```
