### ISSUE TITLE
Query on not existing time series causes database panic

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3192]
I'm on 0.9.0. I noticed that my database kept crashing when i performed a certain query. I then realized it was because the timeseries did not exist in the database. The query was done through the UI. 

The query I executed through the UI was - `select * from lo`, which resulted in "Error" being shown as a message. I didn't see anything in the response as far as messages are concerned. When i looked in the logs I saw this: http://pastebin.com/iZzyJLyH

**Comment by otoolep** [comment]
This has been fixed in master and 0.9.1-rc1.

https://influxdb.com/download/index.html

**Comment by jhorwit2** [comment]
Awesome, thanks.
