### ISSUE TITLE
[0.9.1-rc1] Unable to login in the web admin interface

### ISSUE THREAD

**Issue by cburki** [influxdb/influxdb#3195]
Could not login into the web admin interface. So I could not execute any query. I fill the connection settings form but the "save" button send a "SHOW DATABASES" query (show the network section of the chrome developer tools when clicking on the save button).

**Comment by jhofeditz** [comment]
I have this same problem in influxdb_0.9.1-rc1. Authentication is not passed along with the query in requests from the admin web UI. PR #3184 looks like it will fix this issue.

Also, I'm a new influxdb user and the default localhost in the connection settings is confusing. I incorrectly assumed that the admin console was making a server side query. Maybe the hostname or fqdn would be a better default?

**Comment by toddboom** [comment]
Fixed with #3184.
