### ISSUE TITLE
LIMIT 1 returns first point, should return last point

### ISSUE THREAD

**Issue by MarekRychlik** [influxdb/influxdb#3197]
Found in: InfluxDB 0.9.0

Issue: Query such as "SELECT * FROM cpu LIMIT 1" returns the first point in each series for measurement cpu.  It should return the last point, as documented in https://influxdb.com/docs/v0.9/query_language/querying_data.html

Please fix.  Being able to get the latest point data for multiple series is fundamental.

**Comment by mjdesa** [comment]
@MarekRychlik Sorry about the confusion  in the documentation, it could certainly be more clear. The "last" point in the series is first point that was ever written. Currently there is no way to get the latest point that was written.

See [2022](https://github.com/influxdb/influxdb/issues/2022) for more information.

**Comment by zhulinhong** [comment]
Why don't support this ?  I think it is very useful in my case.
How can we get the newest point?

**Comment by zhulinhong** [comment]
Why don't support this ? I think it is very useful in my case.
How can we get the newest point?  @mjdesa

**Comment by beckettsean** [comment]
@zhulinhong please follow issue #2022 for details. We also consider this important but not as important as other work already happening. It's not a matter of "we will not support this" but just "we have not yet built this but we will."
