### ISSUE TITLE
Continue query exception when fill(null) used

### ISSUE THREAD

**Issue by evgygor** [influxdb/influxdb#3202]
Hi,

This continue query:

`select mean(elapsed) as average, percentile(elapsed,95) as percentile_95, max(elapsed) as maximum from /^Jmeter.*/ group by time(1s) fill(null) into 1sec.timing.:series_name backfill(false) `

cause to error 
`[2015/07/01 08:05:38 IDT] [EROR] (github.com/influxdb/influxdb/coordinator.(*Coordinator).InterpolateValuesAndCommit:486) Couldn't write data for continuous query: %!(EXTRA *errors.errorStr
ing=proto: Marshal called with nil)`

and doesnt works.

Without fill(null) the CQ works fine, but i need to fill the intervals in series.

Is some workaround exists?

**Comment by mjdesa** [comment]
hey @evgygor I'm having a hard time reproducing the error. Have you tried something like `fill(0)` or `fill(1.0)`

**Comment by evgygor** [comment]
Hi,
I'm using the influxdb 0.8.8.
I cannot use fill(0) cause it's fill data with wrong values, 0 is one of possible values, so I need fill the "missed" associated datapoints with null.

I think the issue comes from golang's working with JSON...

**Comment by mjdesa** [comment]
Currently InfluxDB doesn't support writing points with null values.

I'm trying to think if there's a work around. Could you increase the `group by` to `time(2s)` and then run a select with a `group by time(1s)`?

**Comment by evgygor** [comment]
Thanks, I'll try.
