### ISSUE TITLE
[0.9.0] LIMIT 1 return first value instead of last value

### ISSUE THREAD

**Issue by vmire** [influxdb/influxdb#3206]
> select I from node11
name: node11
------------
time			I
2015-06-24T09:54:48Z	1567
2015-06-24T09:58:05Z	1567
2015-06-24T10:02:26Z	1567
2015-06-24T10:06:48Z	1567
2015-06-24T10:08:59Z	1567
2015-06-24T10:11:59Z	1568
2015-06-24T10:15:15Z	1568
...
2015-07-01T17:17:55Z	2404
2015-07-01T17:19:01Z	2404

> select I from node11 limit 1
name: node11
------------
time			I
2015-06-24T09:54:48Z	1567

**Comment by otoolep** [comment]
@vmire -- this is the way software currently works since results are returned by time-ascending order. We will support time-descending order in the near future.

**Comment by vmire** [comment]
online documentation says the opposite :
(https://influxdb.com/docs/v0.9/query_language/querying_data.html)

> SELECT * FROM /.*/ limit 1;
> Return the last point from every time series in the database.

**Comment by otoolep** [comment]
Documentation is currently being reworked for the 0.9 series, and we hope to have it 100% correct very soon.

**Comment by vmire** [comment]
Workaround :
select LAST(I) from node11 where time > now() - 1d GROUP BY time(2d)
