### ISSUE TITLE
When querying large amount of data, points returned in more than one series

### ISSUE THREAD

**Issue by rohilbh** [influxdb/influxdb#3208]
I'm using Grafana to create a dashboard using influxdb. I have around 300 events per second stored in my influx database and if i use a query in Grafana that includes more than a couple minutes of data from one series, I get the data returned but in multiple series with the same name. This causes Grafana to create multiple lines with the same names and completely throws off the graph. This is the query that causes the issue:

q=SELECT+counter1+FROM+%22clickLogger_clickMetric2%22++where+time+%3E+now()+-+3m+

The response that Grafana is getting is

```javascript
{
	results: [
		{
			series: [
				{
					name: "clickLogger_clickMetric2",
					columns: [
						"time",
						"counter1"
					],
					values: [...]
				},
				{
					name: "clickLogger_clickMetric2",
					columns: [
						"time",
						"counter1"
					],
					values: [...]
				}
			]
		}
	]
}
```

If I change the query to 
q=SELECT+counter1+FROM+%22clickLogger_clickMetric2%22++where++time+%3E+now()+-+3m+and+time+%3C+now()+-+2m

only one series is returned and everything works fine. It seems like if there are too many points returned in the query, the influx response is splitting them into multiple series - not ideal behavior.

**Comment by beckettsean** [comment]
closing in favor of #3242
