### ISSUE TITLE
Support DELETE FROM with value-based WHERE clauses

### ISSUE THREAD

**Issue by seibert** [influxdb/influxdb#3210]
I have a sensor that was occasionally returning an impossible value.  I would like to remove all these bad data points using a query like:
```sql
DELETE FROM temp WHERE value > 95
```
but that returns an `ERR: invalid query`.

(The documentation does make it clear that DELETE currently only supports time ranges, but other kinds of WHERE clauses would be very useful.)

**Comment by seibert** [comment]
Oops, it looks like I was reading the pre-0.9.0 docs.  There doesn't seem to be any DELETE functionality documented in version 0.9.0.  Nevertheless, I would still like to be able to delete points using a query like that listed above.  :)

**Comment by mjdesa** [comment]
@seibert Deleting points is something InfluxDB highly recommends against. As an alternative we recommend updating the point that you'd like to delete with a default value. Are you using 0.8.X or 0.9.X?

**Comment by seibert** [comment]
0.9.X.  How would I replace the value of a point?

**Comment by mjdesa** [comment]
In 0.9.X you can replace the value of the point by simply rewriting the point with that timestamp.

So if my point was `cpu,host=serverA value=1029 1434055562000000000`

I could update it by doing

```
INSERT cpu,host=serverA value=0 1434055562000000000
```

**Comment by seibert** [comment]
Thanks!  Is there an easy way to get SELECT to return the timestamps in integer form?  I would rather not have to convert the ISO format timestamps manually if I can avoid it.

**Comment by beckettsean** [comment]
@seibert https://github.com/influxdb/influxdb/pull/2673 added this, but it's undocumented and I didn't even know about it until I went looking. I think the syntax would be `&epoch=s` for seconds, `&epoch=ms` for milliseconds, etc.

@mjdesa can you try to verify what the URL param should be?

**Comment by beckettsean** [comment]
Added https://github.com/influxdb/influxdb.com/issues/90 to document

**Comment by mjdesa** [comment]
@beckettsean the url params you thought are correct:

```
curl -G 'http://localhost:8086/query?epoch=s' --data-urlencode 'q=select * from "telegraf"..cpu_user limit 1'
```

**Comment by mingzhou** [comment]
I would like to use influxdb as a time-series db for storing tick position infomation. For example, I insert the following record yesterday:

|time | tick | volume|
|---| --- | --- |
| 123456 | "GOOG" | 100 |
| 123456 | "MSFT" | 200 |
| 123456 | "AAPL" | 300 |

Today, I find that I made a big mistake, I should change the record into:

|time | tick | volume|
|---| --- | --- |
| 123456 | "GOOG" | 100 |
| 123456 | "AAPL" | 200 |

Since there's no delete clause in v0.9.6. How could I  `DELETE` the old record and insert the new correct record?
Thanks.

**Comment by dandv** [comment]
StackOverflow question: [Delete points with unwanted field values from InfluxDB measurement](http://stackoverflow.com/questions/39685114/delete-points-with-unwanted-field-values-from-influxdb-measurement)

**Comment by desa** [comment]
@dandv This advice no longer applies to new versions (10+) of InfluxDB.

Previously we used to store rows in the database so writing , now we store columns.

**Comment by dandv** [comment]
Is there a workaround, such as `SELECT`ing `INTO`, but which also [preserves the points in which the field doesn't have a value](https://github.com/influxdata/docs.influxdata.com/issues/717#issuecomment-249663947)? The SELECT below will exclude points that don't have a `temperature` field (but have other sensor data):

    SELECT * INTO temp_clean FROM temp WHERE temperature <= 95

**Comment by beckettsean** [comment]
@dandv since there's no way to select a point that _doesn't_ have a particular field, I don't think there's a way to accomplish what you desire using INTO queries. Points without the referenced field will always be ignored.

The best fix would likely be to dump the data to raw line protocol using `influx_inspect export` and then massaging the output before replaying it. Run `influx_inspect export -h` for help on the command.

**Comment by akhan4u** [comment]
Hi all ,

How can i delete a host entry from a database in the Influxdb? ... Please help me out with the command. i have accidentally configured a hostname that was not supposed to be present!

**Comment by dandv** [comment]
I [no longer](https://stackoverflow.com/questions/39685114/delete-points-with-unwanted-field-values-from-influxdb-measurement) even get a message that it's not possible to DELETE FROM measurement WHERE field=value:

![image](https://user-images.githubusercontent.com/33569/34904543-ca9b463e-f7fc-11e7-8b59-39c5386b928c.png)

The command fails (or succeeds?) silently.

**Comment by MrBoggi** [comment]
It is a bit strange that delete is not allowed and that replacing the value is recomended. Why replace a wrong value with something else that is wrong (Yes it is wrong because you do not know what the value actually was). It can be updated with the same value as the point before or after or a mean between the two but it is still a wrong value inserted. I would also like to see delete with value-based where command being supported in InfluxDB.

**Comment by uski** [comment]
Hi, is there a reason why this has been closed ? I still doesn't work in the latest stable version and it seems multiple users are supporting this feature request. Thanks

**Comment by jeroenst** [comment]
I also experienced this issue today in influx 1.6.4, when I read about where is not supported in a delete statement I thought it was a joke :-(

> delete from "pond.temperature" where value > 10
ERR: shard 212: fields not supported in WHERE clause during deletion

**Comment by anordvall** [comment]
Hi all! I got sick and tired of not being able to "delete where value" so I created a C# app that will delete values not within the range set by the user. See attached TXT file showing how it works. Let me know if you want to try it out..

**Comment by mvintila** [comment]
Why is this issue closed? This still doesn't work.

**Comment by n0valis** [comment]
I don't know where to find the "how can I do this otherwise" thread, wiki article that would explain why this issue was closed.
It is not possible to clean a measure from 'dirty' values, is it?
PLease do something but not ignore this issue. Or just tell us how to do it.

**Comment by anderml1955** [comment]
> Hi all! I got sick and tired of not being able to "delete where value" so I created a C# app that will delete values not within the range set by the user. See attached TXT file showing how it works. Let me know if you want to try it out.. [influx_clean.txt](https://github.com/influxdata/influxdb/files/6018514/influx_clean.txt)

Could you share your app please?

**Comment by OverWorldD** [comment]
Just joining the choir here... Not being able to remove erroneous values is very annoying. Also I'd like to be able to remove erroneous fields. I haven't figured out how to do that either. So my database has all these fields that are unused because they are wrong/contain wrong values i cannot delete so i had to make new ones. It gets real messy.

**Comment by dandv** [comment]
Perhaps time to consider alternatives to InfluxDB for new projects at least.

https://github.com/timescale/timescaledb
https://github.com/VictoriaMetrics/VictoriaMetrics

**Comment by anordvall** [comment]
> > Hi all! I got sick and tired of not being able to "delete where value" so I created a C# app that will delete values not within the range set by the user. See attached TXT file showing how it works. Let me know if you want to try it out.. [influx_clean.txt](https://github.com/influxdata/influxdb/files/6018514/influx_clean.txt)
> 
> Could you share your app please?
[influx_cleanup.zip](https://github.com/influxdata/influxdb/files/7920384/influx_cleanup.zip)

Not sure if this will work, but I've tried attaching a ZIP here. You will need to run the program on the same machine (Windows) where influxd is running. Let me know if it works or not. If it doesn't I'll try to fix it. And of course, make a backup of your DB first just to be on the safe side.

**Comment by OverWorldD** [comment]
> Not sure if this will work, but I've tried attaching a ZIP here. 

Hi, Thank you so much I will test it and report!

**Comment by OverWorldD** [comment]
First dry run test, I realize it doesn't work for me as I use the database a bit differently. I need to be able to select a certain field in a measurement and query only that field for values to delete.

My database is "influxtest", it has the measurement "modbus" and then inside I have my fields for the values that come from modbus. For example sumPower which is accumulated power consumption from my house. In this field(sumPower) I have bad values I want to remove. So if I understood it correctly your code will not work, or am I missing something?

![image](https://user-images.githubusercontent.com/12225528/150968287-9f90cabc-33a8-4c15-80fb-e9f4759aaa56.png)

**Comment by GoumJer** [comment]
My soluton for this is first find the timestamps which should be deleted, and then delete based on that (which works :-))

> select * from day where value = 0;
name: day
time                value
----                -----
1630623600000000000 0
1630710000000000000 0
1630796400000000000 0

Use these timestamps to create a delete script in your favourite editor:
> delete from day where time = 1630623600000000000;
> delete from day where time = 1630710000000000000;
> delete from day where time = 1630796400000000000;

Et presto, zero- value records are gone:
> select * from day where value = 0;
>

Regards,

Jeroen

**Comment by randianb** [comment]
> > k and tired of not being able to "delete where value" so I created a C# app that will delete values not within the range set by the user. See attached TXT file showing how it works. Let me know if you want to try it out..
> 
> what tool are you using in these screenshots?

grafana
