### ISSUE TITLE
[0.9.0]  how to setup  timezone  in influxdb,  the time from  influxdb  is not my  timezone 

### ISSUE THREAD

**Issue by waydeechen** [influxdb/influxdb#3211]
query result:
cpu_load_short3   
time	                                 value
2015-07-02T02:06:14Z	10.64

actually  the time is  2015-07-02T10:06:14Z,  my  timezone is  Asia/Shanghai 

how to resolve  this ?

**Comment by beckettsean** [comment]
All timestamps in InfluxDB are returned in UTC. There is no support yet for alternate timezones. See https://github.com/influxdb/influxdb/issues/2071 and https://github.com/influxdb/influxdb/issues/2074 to follow the discussions.

**Comment by thetcc** [comment]
I eagerly awaited this feature.
Without this feature,I can not use group by time(1d) .
I am very very need this feature.

**Comment by beckettsean** [comment]
closing in favor of the two previously mentioned issues.
