### ISSUE TITLE
[0.9.0] influxdb curl insert data  is very slow,   why ?

### ISSUE THREAD

**Issue by waydeechen** [influxdb/influxdb#3212]
time curl -i -XPOST 'http://192.168.90.23:8086/write?db=zabbix&rp=zabbixpolicy&precision=s' -d 'cpu_load_short3,host=server01,region=us-west value=10.64 1435802774'
HTTP/1.1 204 No Content
Request-Id: a32b9e15-206a-11e5-b0e9-000000000000
X-Influxdb-Version: FIXME
Date: Thu, 02 Jul 2015 03:30:09 GMT

real    0m1.114s
user    0m0.001s
sys     0m0.004s

**Comment by beckettsean** [comment]
@waydeechen the first point ever written to a series takes a bit longer. If you write more points to that series they will write more quickly. Also, InfluxDB is designed to accept points in batches up to ~10,000 points each. Batching will significantly increase write throughput.
