### ISSUE TITLE
Database crash when continously loading data

### ISSUE THREAD

**Issue by koppor** [influxdb/influxdb#3214]
I use influxdb 0.9.1-rc2 and try to test its limits. Therefore, I created following python script:

```
import requests
import random
import time

basets = int(time.time())

#1 day: 86400 seconds
#each 3 seconds a measurement: 28800
for i in range(0, 28800):
        print i
        payload = ""
        for haushalt_id in range(0, 10000):
                for meter_id in range(0, 5):
                        payload += "verbrauch,haushalt_id=%d,meter_id=%d value=%f %d\n" % (haushalt_id, meter_id, random.random(), basets)
        basets += 3
        r = requests.post("http://localhost:8086/write?db=example&precision=s", data=payload)
```

After creating the database `example` and letting the script run, the script starts to output numbers. On a system with 2 GB RAM and virtual 6 GHz, it stops after number 1397, meaning more than 70.000.000 values have been filled in. Stopping means that an `requests.exceptions.ConnectionError` is output. The influx process is not there any more. The last lines of the log (`/var/log/influxdb/influxd.log`) read as follows:

```
[retention] 2015/07/02 05:31:16 retention policy shard deletion check commencing
[retention] 2015/07/02 05:31:16 retention policy enforcement check commencing
[http] 2015/07/02 05:31:37 ::1 - - [02/Jul/2015:01:25:20 +0200] POST /write?db=example&precision=s HTTP/1.1 500 32 - python-requests/2.2.1 CPython/2.7.6 Linux/3.16.0-38-generic 70ccd2c2-2048-11e5-857d-000000000000 4h6m16.58276707s
```

With influx 0.9.0 the script stopped at about 590.

Wish: influx should not silently terminate, but output something if it encounters an error

**Comment by otoolep** [comment]
Thanks for the report, I'm looking into it.

**Comment by otoolep** [comment]
@koppor -- all crash (panic) output should be in the same log. If you do not see a panic in there, it did not happen. Perhaps something else stopped the InfluxDB process.

**Comment by otoolep** [comment]
Thanks for the script. I am running it on my own box to see if I can bring out the issue you reported.

**Comment by beckettsean** [comment]
@otoolep did you ever repro?

@koppor can you try with 0.9.1 final?

**Comment by otoolep** [comment]
I remember running this, and I think we fixed the issue, but I can't recall for sure.

**Comment by koppor** [comment]
With 32 GB of RAM and the nightly retrieved at 2015-07-16, it works. With 0.9.1 and 2 GB of RAM, the script stops at 1348.

The log file of the crashed instance has entries such as

```
goroutine 18732 [semacquire, 535 minutes]:
sync.(*RWMutex).RLock(0xc20812e0f0)
        /usr/local/go/src/sync/rwmutex.go:36 +0x5f
github.com/influxdb/influxdb/tsdb.(*Shard).validateSeriesAndFields(0xc20812e0b0, 0xc2cf8ca000, 0xc350, 0xec00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:638 +0x143
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc20812e0b0, 0xc2cf8ca000, 0xc350, 0xec00, 0x0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:220 +0x75
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc208046480, 0x1, 0xc2cf8ca000, 0xc350, 0xec00, 0x0, 0x0)
        /home/philip/build/src/github.com/influxdb/influxdb/tsdb/store.go:281 +0xf7
github.com/influxdb/influxdb/cluster.func·002(0x1, 0x1, 0xc2cf8ca000, 0xc350, 0xec00)
        /home/philip/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:241 +0xfc
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /home/philip/build/src/github.com/influxdb/influxdb/cluster/points_writer.go:271 +0x30b
```

**Comment by pauldix** [comment]
@koppor how many series are the points spread across?

**Comment by beckettsean** [comment]
For 60000 series, 2 GB of RAM may not be enough. The 0.9.3 release coming on Friday has significant improvements to the performance of writes, please test with that as this should be fixed. We will be publishing recommended configuration numbers in the coming weeks.
