### ISSUE TITLE
Getting a spurious EnableSingleNode error

### ISSUE THREAD

**Issue by jan-grant** [influxdb/influxdb#3216]
We're generating a config automatically. In a simple single-node case, influxdb is failing to start, complaining that EnableSingleNode must be enabled in order to proceed.

It transpires the problem was that the precomputed set of influxdb nodes was being inserted into the config file (it's an ansible template we're using) and triggering this condition to be false (from store.go):

    config.EnableSingleNode = (len(s.peers) == 0)

Although we've fixed the template, the condition could, perhaps, be revised to:

    config.EnableSingleNode = (len(s.peers) <= 1)

(... or have I misuderstood the use of the peers setting - should the current node be excluded from the configuration?)

Cheers

**Comment by otoolep** [comment]
@jan-grant -- what version is this report about? It doesn't look like 0.9.
