### ISSUE TITLE
v0.9.1 RC1 - default graphite template cannot have extra tags

### ISSUE THREAD

**Issue by Inisfair** [influxdb/influxdb#3223]
You cannot add tags to the default graphite template without triggering the following startup error:
>GOMAXPROCS set to 2
>using configuration at: ./influxdb.conf
>run: invalid graphite config: no measurement in template `template=default`. To generate a valid configuration file run `influxd config > influxdb.generated.conf`.

The templates config section:
```
    templates = [
      "translog.* .app.function.measurement template=translog",
      "server.measurement template=default"
    ]
```
This error was not logged into the influx.log file, I was only able to obtain it by interactively launching influxd from the command line.

I'm trying to tag the template chosen to parse a line because I am having issues with templates crossing/interfering with each other when the filter patterns should preclude that and discovered this while troubleshooting that.

Update: As a workaround I set a filter of ```*.*``` on what would be the default template.

**Comment by Inisfair** [comment]
Ok, so here is my actual issue.

I have multiple data sources that send data to InfluxDB via the graphite service.  In converting over from v0.9.0 I modified the metric names and set up multiple templates to parse those metrics.  most of the templates work as expected however I have one that will not work in any variation that I have tried.
```
  templates = [
    "dial.* source.app.role.logical_host.datacenter.environment.mw_layer.api_name.mw_source.mw_provider.status.measurement",
    "volume.* .app.role.datacenter.environment.hostname.mw_layer.api_name.mw_source.mw_provider.status.measurement source=transdb",
    "logwatcher.* source.app.role.datacenter.environment.hostname.measurement",
    "app.role.datacenter.environment.hostname.source.measurement",
  ]
```
Note that originally the 'volume' template was original filtered using 'transdb' but 'transdb' is also an application that we monitor so I observed some issues with the default template picking up records that should have gone to the 'volume' template so I simply changed the starting string to avoid that issue, otherwise it would follow the same pattern of picking up the source value from the metric name directly.

The issue I am having is with the logwatcher template.  No matter what prefix I use for those records and or which order I place that template within the configuration it seems all of the records fall through to the default template (explicit or implicit).  The only time it works as expected is when it is the only template in the configuration file.

Here are some example graphite metrics that should match each of the defined templates
```
app1.function1.seattle.prod.host001.hppm.cpu_queue 1 1435902600
app1.function1.seattle.prod.host001.hppm.cpu_queue 0 1435902300
app1.function2.detroit.prod.host002.hppm.cpu_queue 0 1435902600
app1.function2.detroit.prod.host002.hppm.cpu_queue 0 1435902300
app1.function1.seattle.prod.host001.hppm.mem_util 40.27 1435902600
app1.function1.seattle.prod.host001.hppm.mem_util 40.28 1435902300
app1.function2.detroit.prod.host002.hppm.mem_util 48.81 1435902600
app1.function2.detroit.prod.host002.hppm.mem_util 48.81 1435902300
app1.function1.seattle.prod.host001.hppm.cpu_util 17.34 1435902600
app1.function1.seattle.prod.host001.hppm.cpu_util 17.33 1435902300
app1.function2.detroit.prod.host002.hppm.cpu_util 4 1435902600
app1.function2.detroit.prod.host002.hppm.cpu_util 4.47 1435902300
logwatcher.app1.function1.seattle.prod.host001.transaction_elapsed_time 1.6445 1435879200
logwatcher.app1.function2.detroit.prod.host002.transaction_elapsed_time 2.0005 1435879200
dial.app1.function1.lh1.seattle.prod.inbound.createOrder.dealer.cms.success.transaction_elapsed_time 6.891 1435903920
dial.app1.function2.lh1.detroit.prod.inbound.createOrder.dealer.cms.success.transaction_elapsed_time 7.391 1435903920
dial.app1.function2.lh1.detroit.prod.inbound.validAddress.selfservice.web.failure.transaction_elapsed_time 30.001 1435903920
mwvolume.app1.function1.seattle.prod.host001.inbound.getProfile.cms.db.success.transaction_elapsed_time 0.552 1435904340
mwvolume.app1.function2.detroit.prod.host002.inbound.getProfile.cms.db.success.transaction_elapsed_time 0.776 1435904340
mwvolume.app1.function2.detroid.prod.host002.inbound.getProfile4_0.ivr.db.failure.transaction_elapsed_time 0.142 1435904340
mwvolume.app1.function1.seattle.prod.host001.inbound.requestSpecialPricing.crm.exec.success.transaction_count 2 1435904040
mwvolume.app1.function2.detroit.prod.host002.inbound.requestSpecialPricing.crm.exec.success.transaction_count 1 1435904040
```

**Comment by otoolep** [comment]
@jwilder

**Comment by olivierHa** [comment]
Hello, 

I think I got a similar issue. It seems that only one filter/template is applied , all others filter/template are unused, and data go to the default template.

Regards
