### ISSUE TITLE
Need more detail doc for udp config

### ISSUE THREAD

**Issue by linkdesu** [influxdb/influxdb#3224]
Hi ! I want to say THX first , influxdb + grafana is really a nice combination !

I am new to influxdb , and I have tried use statsd as frontend but they do not support tags yet .

So I want to use udp to send data to influxdb directly , but I can not found doc from chapter writing data .

This is my questions:

1. How can I debug if my data send to influxdb udp port ?
1. Can I make multiple database support udp ?
1. What is  batch-size and batch-timeout exactly means ?

**Comment by beckettsean** [comment]
These are support questions, not bug reports or feature requests. As such they are not appropriate for GitHub Issues. Please contact us at support@influxdb.com and we'll help with your questions. If you have suggestions for better documentation, please raise an issue on the documentation repo: https://github.com/influxdb/influxdb.com/issues/new
