### ISSUE TITLE
heavy load causes stepdowns

### ISSUE THREAD

**Issue by nstott** [influxdb/influxdb#3228]
I understand that work on clustering is ongoing, just submitting this in case there's value

on a three node cluster, with each node on an amazon r3.large
(GOMAXPROCS gets detected as 1, which is odd)

both the heartbeat timeout and the election timeout are set to 3 seconds

after startup the cluster converges, and I start sending traffic, (probably about 2-3k data points a second, batched in groups of 1000)  

shortly after startup the leader steps down, 
```
Jul  3 15:18:17 metrics-2 influxdb5: influxdb | 2015/07/03 15:18:17 [WARN] raft: Failed to contact 10.0.21.194:8088 in 1.3362231s

Jul  3 15:18:17 metrics-2 influxdb5: influxdb | 2015/07/03 15:18:17 [WARN] raft: Failed to contact 10.0.21.195:8088 in 1.327155039s

Jul  3 15:18:17 metrics-2 influxdb5: influxdb | 2015/07/03 15:18:17 [WARN] raft: Failed to contact quorum of nodes, stepping down

Jul  3 15:18:17 metrics-2 influxdb5: influxdb | 2015/07/03 15:18:17 [INFO] raft: Node at 10.0.21.196:8088 [Follower] entering Follower state
```

The network is fine here during these incidents, the system is writing heavily to disk, and my theory is that the heavy IO load effects the scheduler, so that the raft listener hits timeouts

**Comment by beckettsean** [comment]
Significant clustering improvements and WAL tuning changes. Should be alleviated in 0.9.3
