### ISSUE TITLE
[0.9.1]: Unable to dump database

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#3235]
the command

```
/opt/influxdb/influx -host 127.0.0.1 -port 8086 -database 'proxydb' -dump >/home/dbdump.dmp
```
Produce 
```
Dump failed. HTTP Protocol error 404
```

**Comment by beckettsean** [comment]
Reproduced with a simpler string:

```
$ influx -database 'mydb' -dump
Dump failed. HTTP Protocol error 404
```

The return also confuses Terminal on my Mac. It no longer prints out typed characters, and neither `reset` or `clear` restore functionality.

**Comment by beckettsean** [comment]
`dump` needs to be wired back up.

**Comment by beckettsean** [comment]
@corylanou can you please remove the `dump` flag from the CLI? It's not wired up right now and it's confusing that it still shows in `help`
