### ISSUE TITLE
Error using graphite plugin with multiple filters

### ISSUE THREAD

**Issue by olivierHa** [influxdb/influxdb#3245]
Hello, 

Using influxdb 0.9.1, I got strange data when using multiples filters with graphite plugin : 

With configuration : 

```
templates = [ 
    "prod.app1.* env.app.measurement*", 
    ".measurement*", 
]
```

`echo "prod.app1.errors.count 42 `date +%s`" | nc -q0  localhost 2003`

will give : 

``` 
> show series
name: errors.count
------------------
_key				app	env
errors.count,app=app1,env=prod	app1	prod

```

Which is what I think is fine.

But when using 
```
templates = [
    "prod.app1.* env.app.measurement*",
    "prod.app2.* env.app.site.measurement*",
    ".measurement*",
]
```

the same query `echo "prod.app1.errors.count 42 `date +%s`" | nc -q0  localhost 2003`

will give this output .

```
> show series
name: app1.errors.count
-----------------------
_key
app1.errors.count
```

Which I think isn't fine.

Any clues ?

PS : not sure it is the same issue than #3223

**Comment by giganteous** [comment]
Hi @jwilder ,

Could this be not closed, but pending on release, or "known bugs in 0.9.1"? Its hard (for users) to search a bug in 0.9.1 that is open in 0.9.1.

Great it has been fixed!

I wrote a small tool to help test your graphite stuff while debugging this.

**Comment by jwilder** [comment]
It'll be in 0.9.2. Should be in current nightly build too.
