### ISSUE TITLE
0.9.1  cannot start the http write and read port

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#3249]
We have run a  cluster with 3 machine with 0.9.0 version influxdb.  After we upgrade to version 0.9.1, the httpd service cannot be started up. Please find below log while I start the influxdb. There is no line indicate the httpd service has been started. Please help about  this. Actually, we have met the same issue when running on 0.9.0. We have 200GB+ data on each node.

    2015/07/07 12:48:46 [INFO] raft: Node at 10.242.163.101:8088 [Follower] entering Follower state
    2015/07/07 12:48:46 read local node id: 3
    2015/07/07 12:48:48 [DEBUG] raft-net: 10.242.163.101:8088 accepted connection from: 10.242.162.131:44480
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.163.101:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.163.101:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.163.101:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.163.101:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.122:8088 10.242.163.101:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.163.101:8088 10.242.162.131:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.122:8088 10.242.163.101:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.163.101:8088 10.242.162.122:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.122:8088 10.242.163.101:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.162.122:8088 10.242.163.101:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.162.122:8088 10.242.163.101:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.122:8088 10.242.163.101:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.163.101:8088 10.242.162.122:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.163.101:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.163.101:8088 10.242.162.131:8088 10.242.162.122:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.122:8088 10.242.163.101:8088 10.242.162.131:8088]
    2015/07/07 12:48:48 [DEBUG] raft: Node 10.242.163.101:8088 updated peer set (2): [10.242.162.131:8088 10.242.162.122:8088 10.242.163.101:8088]

**Comment by nicksellen** [comment]
I observed a similar issue. I only had a bit of test data in and I resolved it by starting clean again. I'm restarting influxdb periodically now to see how it handles it.

Each time I restart it it will log an additional "updated peer set" line. This doesn't seem right.

My startup log, up to starting http server currently looks like:
```
GOMAXPROCS set to 8
2015/07/07 23:52:56 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
2015/07/07 23:52:56 read local node id: 1
[shard] 2015/07/07 23:52:56 flush 5374 points in 0.044s
2015/07/07 23:52:58 [WARN] raft: Heartbeat timeout reached, starting election
2015/07/07 23:52:58 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
2015/07/07 23:52:58 [DEBUG] raft: Votes needed: 1
2015/07/07 23:52:58 [DEBUG] raft: Vote granted. Tally: 1
2015/07/07 23:52:58 [INFO] raft: Election won. Tally: 1
2015/07/07 23:52:58 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
2015/07/07 23:52:58 [INFO] raft: Disabling EnableSingleNode (bootstrap)
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/07/07 23:52:58 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[shard] 2015/07/07 23:52:58 flush 5061 points in 0.063s
[shard] 2015/07/07 23:53:00 flush 5041 points in 0.058s
[shard] 2015/07/07 23:53:03 flush 5350 points in 0.055s
[shard] 2015/07/07 23:53:05 flush 4726 points in 0.052s
[shard] 2015/07/07 23:53:07 flush 5267 points in 0.068s
[shard] 2015/07/07 23:53:09 flush 5412 points in 0.063s
[shard] 2015/07/07 23:53:11 flush 4830 points in 0.040s
[shard] 2015/07/07 23:53:13 flush 18417 points in 0.159s
[shard] 2015/07/07 23:53:15 flush 17982 points in 0.179s
[shard] 2015/07/07 23:53:17 flush 18100 points in 0.191s
[shard] 2015/07/07 23:53:20 flush 16835 points in 0.157s
[shard] 2015/07/07 23:53:22 flush 16869 points in 0.160s
[shard] 2015/07/07 23:53:24 flush 19118 points in 0.207s
[shard] 2015/07/07 23:53:26 flush 17774 points in 0.167s
[shard] 2015/07/07 23:53:28 flush 17206 points in 0.169s
[httpd] 2015/07/07 23:53:30 listening on HTTP: [::]:8086
```

The shard flush lines are also odd, as it outputs one every two seconds during startup (corresponding to data/WALPartitionFlushDelay config), but the http server is  waiting the whole time, seemingly needlessly delaying startup, and I'm losing data from failed writes in this time.

**Comment by beckettsean** [comment]
@otoolep have your recent changes touched on code that might help with this?

**Comment by otoolep** [comment]
This has been improved significantly in master. There are no longer any 2-second delays at start up. The WAL must still be flushed before the system can be used, but this should take much less time.

**Comment by otoolep** [comment]
To be clear, the WAL is flushed in 1 straight shot at start-up.
