### ISSUE TITLE
Replicating data in cluster

### ISSUE THREAD

**Issue by definea** [influxdb/influxdb#3252]
I create cluster with 3 node (node0 - master, node1, node2).
Node1/2 - seed-server node0.
On all node peers [node0/1/2].
How to sync data on all node?

Node0:
root@node0:~# curl -G 'http://localhost:8086/query?u=admin&p=qwe' --data-urlencode "q=CREATE DATABASE issuez"
> {"results":[{}]}
root@node0:~# curl -i -XPOST 'http://localhost:8086/write?db=issuez&u=admin&p=qew' --data-binary 'log,host=server01,region=us-west value=0.64 1434055562000000000'

root@node0:~# curl -G 'http://localhost:8086/query?u=admin&p=q3urwlYEyWqHEITxyGSFW' --data-urlencode "db=issuez" --data-urlencode "q=SELECT * FROM log"
> {"results":[{"series":[{"name":"log","tags":{"host":"server01","region":"us-west"},"columns":["time","value"],"values":[["2015-06-11T20:46:02Z",0.64]]}]}]}

Read data from Node2:
root@node2:~# curl -G 'http://localhost:8086/query?u=admin&p=qwe' --data-urlencode "q=show databases"
> {"results":[{"series":[{"name":"databases","columns":["name"],"values":[["statistics"],["test"],["test2"],["issuez"]]}]}]}root@cl2-vm:~#

root@node2:~# curl -G 'http://localhost:8086/query?u=admin&p=qwe' --data-urlencode "db=issuez" --data-urlencode "q=SELECT * FROM log"
> {"results":[{"error":"measurement not found: \"issuez\"..log"}]}

**Comment by otoolep** [comment]
@definea - if you create a 3-node cluster, you must explicitly create a retention policy with a replication factor of 3, and write data to that retention policy. This requirement should be lifted in the next release. Check the link below to learn how to create retention policies.

https://influxdb.com/docs/v0.9/administration/administration.html
