### ISSUE TITLE
Influxdb stops writing data after a while

### ISSUE THREAD

**Issue by zeroXten** [influxdb/influxdb#3253]
Data is coming in through the graphite plugin. Managed to get 7 hours of data before it stopped writing last night. 

When I was debugging it yesterday I had put in some fmt.Printf statements in the graphite parser function. I was tcpdumping port 2003 and watching the printfs. At first they were in sync, then slowly over time the delay between the incoming packet and the printf grew and grew. I could see the influxdb processing blocking on IO, so I rebuilt the box with more processing power, more memory and more IOps. I thought this fixed it but found influxdb to have stopped writing data at 3am.

Yesterday, restarting influxdb seem to help temporarily, but that doesn't seem to be the case anymore.

The mod time on the data file is increasing and a dirty diff on a couple of hexdumps shows quite a few changes over a 5 minute period:

    /var/opt/influxdb/db/graphite_db/default# cp 1 $(date +%s) && sleep 300 && cp 1 $(date +%s)
    /var/opt/influxdb/db/graphite_db/default# diff --suppress-common-lines -y <(hexdump -C 1436261903) <(hexdump -C 1436262213) | wc -l
610095

I guess I'll try to install the boltdb cli tool to see if I can dig into the data.

**Comment by otoolep** [comment]
@zeroXten -- please tell us the version you are running.

**Comment by zeroXten** [comment]
0.9.0 from http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb

**Comment by otoolep** [comment]
There have been significant improvements in the 0.9.1 release, I strongly suggest you upgrade and try again. Please let us know if it does not address the issue.

https://influxdb.com/download/index.html

(Those "latest" links are deprecated)
