### ISSUE TITLE
Logging config doesn't make a difference

### ISSUE THREAD

**Issue by zeroXten** [influxdb/influxdb#3254]
Changes to the [logging] parameters in the influxdb.conf file don't seem to make any difference.

I have set write-trace to true and http-access to false, restarted and yet I still see http and no writes.

**Comment by otoolep** [comment]
@zeroXten -- what version are you running?

**Comment by zeroXten** [comment]
0.9.0 from http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb

**Comment by otoolep** [comment]
There have been significant improvements in the 0.9.1 release, I strongly suggest you upgrade and try again. Please let us know if it does not address the issue.

https://influxdb.com/download/index.html

(Those "latest" links are deprecated)
