### ISSUE TITLE
0.9.1 crash on query

### ISSUE THREAD

**Issue by nlalevee** [influxdb/influxdb#3261]
I have setup a collectd to push data into influxdb. Tried a query and it crashed.

The query:
```
SELECT mean(value) FROM "cpu_value" WHERE time > '2015-07-07T18:30:00Z' GROUP BY time(10s) ORDER BY asc
```

In the logs:
```
[httpd] 2015/07/07 18:39:17 listening on HTTP: [::]:8086
[collectd] 2015/07/07 18:39:17 collectd UDP started
[http] 2015/07/07 18:39:28 10.242.2.6 - - [07/Jul/2015:18:39:28 +0200] GET /query?q=SHOW+DATABASES&db= HTTP/1.1 200 95 http://10.10.0.42:8083/? Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36 bc7d118b-24c6-11e5-8001-000000000000 940.459µs
panic: runtime error: makeslice: len out of range

goroutine 68 [running]:
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208476690, 0xc208bb2120, 0xc208145700)
        /home/philip/build/src/github.com/influxdb/influxdb/influxql/engine.go:136 +0x641
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2083a2080, 0xc208bb2120)
        /home/philip/build/src/github.com/influxdb/influxdb/influxql/engine.go:928 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
        /home/philip/build/src/github.com/influxdb/influxdb/influxql/engine.go:907 +0x5a
```

**Comment by jwilder** [comment]
* How much RAM do you have on this host?
* What does `SELECT count(value) FROM "cpu_value" WHERE time > '2015-07-07T18:30:00Z'` return?

**Comment by nlalevee** [comment]
* top reports 32816088KB of memory
* the count returns `null`. Here the raw response:
```
{"results":[{"series":[{"name":"cpu_value","columns":["time","count"],"values":[["2015-07-07T13:38:38.968762306Z",null]]}]}]}
```
But I wouldn't have expected a high number. I get one machine to collect metric once per second, and I got it running for few minutes.

**Comment by benbjohnson** [comment]
@nlalevee I'm looking into this issue again. Can you retry with the latest nightly build to see if you still get a panic? The code has been refactored since you posted the issue and I want to nail down the errant line of code if the problem still exists.

**Comment by ymettier** [comment]
Hello,

Please have a look on issue #3687.
Maybe related to this one. Maybe not.

Regards
Yves

**Comment by beckettsean** [comment]
no repro case, no response from reporter, assuming fixed.
