### ISSUE TITLE
Update 0.9 docs for new derivative behavior

### ISSUE THREAD

**Issue by nathanielc** [influxdb/influxdb#3262]
The derivative docs online for 0.9 still say the same thing as 0.8. Since now there is a second argument to the function and it changes the behavior we should update the docs. I'll take a stab at it but this comment https://github.com/influxdb/influxdb/issues/2699#issuecomment-110527407 is my only source of information on how it really works so my explanation may not be adequate.

**Comment by nathanielc** [comment]
Create issue in correct project.... https://github.com/influxdb/influxdb.com/issues/103

**Comment by beckettsean** [comment]
@nathanielc thanks very much for https://github.com/influxdb/influxdb.com/pull/104! I'm closing this issue in favor of that PR. I opened a companion issue on the doc repo (https://github.com/influxdb/influxdb.com/issues/110)
