### ISSUE TITLE
GUI not updating with newly created DB without refreshing the page.

### ISSUE THREAD

**Issue by sarvesh-ranjan** [influxdb/influxdb#3263]
Newly created DB is not showing in Databases dropdown but works correctly is I run "SHOW DATABASE" on the search tab. Works fine if I refresh the page.
In the snapshot look for DB PROBLEM.

<img width="1224" alt="screen shot 2015-07-07 at 11 17 19 am" src="https://cloud.githubusercontent.com/assets/8452090/8553661/cb53a370-2499-11e5-8582-62d2ac4f39fc.png">

**Comment by beckettsean** [comment]
Working as intended. The Admin UI is not a polling system, it only knows of databases that existed when it loaded.
