### ISSUE TITLE
influxdb write performance problem

### ISSUE THREAD

**Issue by jasper-zhang** [influxdb/influxdb#3265]
v0.9.1, single node,
10 metrics 1000/s  ok
100 metrics 1000/s ok
1000 metrics 1000/s  problem, respone "timeout"

so, If the number of metrics is limited?

**Comment by beckettsean** [comment]
@jasper-zhang there is no hard limit on the number of metrics, but 1 million points per second is well beyond the performance capabilities of a single node. 100k points per second is at the edge of the current performance, depending on your batching and data.
