### ISSUE TITLE
[0.9.1] Logging config doesn't make a difference (reopen of #3254)

### ISSUE THREAD

**Issue by zeroXten** [influxdb/influxdb#3266]
Changes to the [logging] parameters in the influxdb.conf file don't seem to make any difference.

I have set write-trace to true and http-access to false, restarted and yet I still see http and no write traces.

Although this time around I may be seeing "[shard] ... flush xx points" messages at the start.

Version 0.9.1.

**Comment by otoolep** [comment]
I believe our logging is now OK. Please let us know if not.
