### ISSUE TITLE
[0.9.1] Influxdb stops writing data after a while (reopen of #3253), graphite plugin

### ISSUE THREAD

**Issue by zeroXten** [influxdb/influxdb#3267]
From previous ticket:

Data is coming in through the graphite plugin. Managed to get 7 hours of data before it stopped writing last night.

When I was debugging it yesterday I had put in some fmt.Printf statements in the graphite parser function. I was tcpdumping port 2003 and watching the printfs. At first they were in sync, then slowly over time the delay between the incoming packet and the printf grew and grew. I could see the influxdb processing blocking on IO, so I rebuilt the box with more processing power, more memory and more IOps. I thought this fixed it but found influxdb to have stopped writing data at 3am.

Yesterday, restarting influxdb seem to help temporarily, but that doesn't seem to be the case anymore.

The mod time on the data file is increasing and a dirty diff on a couple of hexdumps shows quite a few changes over a 5 minute period:

/var/opt/influxdb/db/graphite_db/default# cp 1 $(date +%s) && sleep 300 && cp 1 $(date +%s)
/var/opt/influxdb/db/graphite_db/default# diff --suppress-common-lines -y <(hexdump -C 1436261903) <(hexdump -C 1436262213) | wc -l
610095

I guess I'll try to install the boltdb cli tool to see if I can dig into the data.

----

That was on version 0.9.0. We have been running on 0.9.1 since yesterday afternoon and this time it managed to go about 20 hours before no longer writing.

I have no idea what the influxdb process is doing as it doesn't seem to log anything useful and SHOW STATS doesn't seem to be implemented yet.

**Comment by zeroXten** [comment]
Interestingly, restarting the process (after trying to make a logging change) seems to have cured things for now.

**Comment by beckettsean** [comment]
@zeroXten glad it seems to be resolved for now. There are a lot of issues around writing via the graphite plugin, so although I'm closing this we will make sure to test graphite writing under load.
