### ISSUE TITLE
Not listening on any ports, other than 8088 and "tcp.Mux: handler not registered: 80" in the logs

### ISSUE THREAD

**Issue by mrmrwat** [influxdb/influxdb#3268]
I am running Influx 0.9.1 on 64-bit Ubuntu 14.04 (Linux 3.13.0-57-generic) installed from the following package: https://s3.amazonaws.com/influxdb/influxdb_0.9.1_amd64.deb

I tested it in a standalone configuration and it worked ok.

After creating two more machines and configuring them into a cluster, as per the docs on influxdb.com, everything was working fine, until I rebooted the machines. Now one of the machines has all three ports (8083, 8086 and 8088) up and listening, but the other two machines (with exactly the same versions of software and equivalent configs) only have the raft/meta port 8088 listening. No matter what I do (reboot, restart the service, alter the configs and restart, reinstall, remove all data files and reinstall, etc.) I can't get those other two hosts to listen on all ports.

There is nothing in the logs to indicate why the ports are failing to listen.

In addition, on all three machines I am getting `tcp.Mux: handler not registered: 80` constantly written to `/var/log/influxdb/influxd.log`; not sure if that is related, but I can't find anyone else with that particular log line.

**Comment by otoolep** [comment]
We haven't seen this issue in ages, and can also be triggered by misconfigured clusters (I've done it myself). I don't believe we have an issue any longer.
