### ISSUE TITLE
Admin Web UI 401 Unauthorized when Basic Auth is enabled

### ISSUE THREAD

**Issue by elisiariocouto** [influxdb/influxdb#3270]
Hello,

I've just installed 0.9.1 and enabled Basic Auth. Created an admin user and a database using the influx CLI tool and opened the Web UI. All the info in the connection settings box is correct but I keep getting a 401. It seems that requests made by the Web UI don't use the Basic Auth settings. If I turn off the Basic Auth in `influxdb.conf`, it works.

**Comment by toddboom** [comment]
I think this was fixed in #3184, so this should be corrected in `v0.9.2`.
