### ISSUE TITLE
Allow password to be sent via HTTP header

### ISSUE THREAD

**Issue by btashton** [influxdb/influxdb#3271]
Since the HTTP request is being stored in the logs it would be really nice if the password could be optionally passed as and HTTP header instead.

**Comment by gunnaraasen** [comment]
User credentials can be included in the HTTP request as either URL query parameters or a HTTP [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication) header. Credentials sent using Basic Auth have never been logged by InfluxDB.
