### ISSUE TITLE
[0.9.1ish-master] failed to write batch: timeout, graphite protocol

### ISSUE THREAD

**Issue by shish** [influxdb/influxdb#3275]
A seemingly different issue to #3199 

After a while of writing graphite metrics and not doing any queries (so I can't see how this would be triggered by an invalid query), influxdb stops accepting data, maxes out my server's IO (the other ticket said server IO was around 10%) and writes to the log ~50x per second:

[graphite] 2015/07/08 15:54:16 failed to write point batch to database "graphite": timeout

Install is from current master ( 37de817f035d1a2f916e8c023bd796335aa0b4b8 ), using the 0.9.1 config file, only modified to enable graphite input.

Looks like even before it gets to the point of timing out 50x per second, timeouts still happen fairly frequently and the server's io-wait is around 80%

I'm only accepting a few KB/s of stats, with a total database size of 70MB after a day of use - it seems very strange that this manages to completely max out my hard drive :S  0.8 seemed to have practically zero io-wait from what I can remember (my 0.8 install recently decided to become corrupt, and since influxdb was where I kept a log of my server's io-wait readings, I can't check...)

**Comment by spynode** [comment]
Same issue with 0.9.1 stable and 0.9.2 nightly. Tried tweaking [cluster] write-timeout , shard-writer-timeout and [[graphite]] batch-size,  batch-timeout to no avail.

**Comment by shish** [comment]
after deleting raft.db which was full of copies of localhost, I now appear to have /no/ peers...

```
[graphite] 2015/07/20 21:47:13 failed to write point batch to database "graphite": at least one node required
[graphite] 2015/07/20 21:47:13 failed to write point batch to database "graphite": at least one node required
[graphite] 2015/07/20 21:47:13 failed to write point batch to database "graphite": at least one node required
[graphite] 2015/07/20 21:47:13 failed to write point batch to database "graphite": at least one node required
```

**Comment by otoolep** [comment]
There haven been very significant changes to the storage engine since this ticket was filed, much of which was to help address timeouts. I'm closing this, please re-open if you still see issues.
