### ISSUE TITLE
Multiple series should not be merged when selecting a field

### ISSUE THREAD

**Issue by samhatchett** [influxdb/influxdb#3281]
v0.9.1, Brew, non-clustered.

Not sure if it's a bug or a feature. `SELECT * FROM ...` returns each separate series with its tags and field values listed, which is as expected. However, `SELECT 'field-name' FROM ...` returns a merged version as a single series with no tags. This is counterintuitive. Given behavior of the former, I would expect the latter to produce a subset of those results (e.g., only the columns specified plus timestamp), but still show each individual series with its tags. This more intuitive behavior can be forced by specifying a `group-by` clause, as long as the series don't share the same value for the grouped key.

To illustrate:

````
# create database and 2 different series
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE tag_list_bug"
curl -i -XPOST 'http://localhost:8086/write?db=tag_list_bug' --data-binary 'cpu_temp,region=us-west,server=serv-1,login=joe degrees=0.64 1434055562000000000'
curl -i -XPOST 'http://localhost:8086/write?db=tag_list_bug' --data-binary 'cpu_temp,region=us-east,server=serv-2,login=joe degrees=1.2 1434055562000000000'

# query for (*) -> result: Two different series are returned, with tags listed. great.
curl -G http://localhost:8086/query  --data-urlencode 'db=tag_list_bug' --data-urlencode 'q=select * from cpu_temp'

# query for (value) -> result: A single series is returned with both data points in it, and no tags :(
curl -G http://localhost:8086/query  --data-urlencode 'db=tag_list_bug' --data-urlencode 'q=select degrees from cpu_temp'

# same query with field specified, but with group-by also specified -> result: Two different series are returned, with tags listed. :)
curl -G http://localhost:8086/query  --data-urlencode 'db=tag_list_bug' --data-urlencode 'q=select degrees from cpu_temp group by region'
````

**Comment by prakashsurya** [comment]
@samhatchett I was hitting this and was really confused until I stumbled on this issue. I also think it's unintuitive to have the series' automatically merged; at the very least I'd expect behavior to be consistent when selecting by `*` and when selecting by a `field-name`. Thanks for posting a work around too, I think using `group-by` will suffice for now.

**Comment by beckettsean** [comment]
Created https://github.com/influxdb/influxdb.com/issues/119 to clarify this in the docs, but it is behaving as expected.
