### ISSUE TITLE
[0.9.1] batch write performance

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3282]
I was trying to figure out earlier an optimal batch write size so influxdb wouldn't consistently timeout under the load. My POST request to influx in using line protocol and is only 10kb in size. Even at this rate the write speeds consistently rise until the 5 second timeout is reached. This is pretty bad :(. Is this being addressed in the next point release? 

If I try batches of 1k I hit a timeout in about ~20 requests and it consistently times out at 5 seconds and returns a 500 status code. Any batches higher than 1k result in even quicker timeout reached.

**Comment by jhorwit2** [comment]
As a follow up, I'm on a quad core machine with 16gb of ram and a SSD. I notice consistently 100% utilization of a CPU Core. Memory usage is low and write speeds seem fine. There are no queries being run on this database, only writes.

**Comment by beckettsean** [comment]
@jhorwit2 can you share a sample of the exact line protocol data you are writing? It sounds like perhaps you're writing timestamps in descending order or there's some other syntax that's causing excessive load.

**Comment by jhorwit2** [comment]
```300lo0.040423238762562264 random="0.8410009609311295",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436482083336
300lo0.7842570628792662 random="0.002777329283267682",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436482083343
300lo0.9390205470656039 random="0.32942420450859655",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436482083343
300lo0.8924706889250253 random="0.18143448897929904",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436482083343
300lo0.7007264472584372 random="0.01736308519125951",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436482083343```

This is output from my log.

**Comment by jhorwit2** [comment]
It appears the time stamps are in descending order. Should they be sorted otherwise? That is not something I have heard of in performance talk.

**Comment by jhorwit2** [comment]
@beckettsean I added a sorting algorithm when I build my line protocol to sort in ascending order. Sending 1 request per second with a batch size of 100 seems to slowly still be inching towards timeout. It's taking longer, but it's definitely the trending line.

**Comment by jhorwit2** [comment]
@beckettsean 
```
300lo random="0.3466630607195913",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866036
300lo random="0.1299868789901808",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866045
300lo random="0.0943490885215662",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866050
300lo random="0.8365214823014128",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866059
300lo random="0.12585407469405385",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866067
300lo random="0.06486548753563104",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866071
300lo random="0.30836706708598804",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866077
300lo random="0.404782951588023",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866082
300lo random="0.2294015090802085",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866091
300lo random="0.2553346671114026",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866096
300lo random="0.403958717823826",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866100
300lo random="0.14037045796062653",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866104
300lo random="0.6456390856725701",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866108
300lo random="0.038118015690291496",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866116
300lo random="0.8483937346610219",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866119
300lo random="0.661435514637977",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866122
300lo random="0.631423846265378",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866125
300lo random="0.1205694246969814",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866134
300lo random="0.20385281556403811",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866138
300lo random="0.8736204352625752",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866144
300lo random="0.31544280338365493",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866145
300lo random="0.08016003496082602",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866153
300lo random="0.44765750481560285",foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866155
```

This is a subset of some data points I have been trying in my most recent test. Current I'm sending 1 request every second with a batch size of 100. The content length is `10224`. The requests start with a low response time, which is awesome; however, each request slowly gets longer and longer until it times out. I added your sorting suggestion, but that didn't solve it either. I'd really expect influx to be able to handle batches of 100 at a 1req/s rate :(


So, very interestingly as I was typing this, I noticed something curious in the logs. 

```
[http] 2015/07/09 22:43:46 192.168.1.4 - - [09/Jul/2015:22:43:45 -0400] POST /write?db=watchtower&precision=ms HTTP/1.1 204 0 - Apache-HttpClient/4.4.1 (Java/1.8.0_25) 7bf84ecc-26ad-11e5-8157-000000000000 807.498721ms
[http] 2015/07/09 22:43:48 192.168.1.4 - - [09/Jul/2015:22:43:47 -0400] POST /write?db=watchtower&precision=ms HTTP/1.1 204 0 - Apache-HttpClient/4.4.1 (Java/1.8.0_25) 7d267864-26ad-11e5-8158-000000000000 832.464947ms
[shard] 2015/07/09 22:43:48 flush 34400 points in 0.083s
[http] 2015/07/09 22:43:49 192.168.1.4 - - [09/Jul/2015:22:43:49 -0400] POST /write?db=watchtower&precision=ms HTTP/1.1 204 0 - Apache-HttpClient/4.4.1 (Java/1.8.0_25) 7e42ffab-26ad-11e5-8159-000000000000 20.612978ms
```

You can see that my times were up to 832ms for a write, but then a flush happened at that time dropped down significantly only to start building up again. Is there a way to increase the flush frequency?

**Comment by jhorwit2** [comment]
So, I dug through the code a little and noticed the [flush timer](https://github.com/influxdb/influxdb/blob/8b67872d6bd1013d455e3b12af3e79b24d78bf0d/tsdb/shard.go#L144) is based on a configuration, so I decided to set it to something small; however.... it's still not getting triggered.

config:
```
[data]
  dir = "/var/opt/influxdb/data"
  MaxWALSize = 5000 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  WALFlushInterval = "15s" # Maximum time data can sit in WAL before a flush.
  WALPartitionFlushDelay = "2s" # The delay time between each WAL partition being flushed.
```

run command: `./opt/influx/influxd -config /opt/etc/influxdb/influxdb.conf`

**Comment by zeroXten** [comment]
This sounds a little bit like my problem in #3267 but rather it being a batch of data such, I've got streams over graphite data coming in every minute. Initially performance is fine, then things just slowly get worse over time until nothing shows up in the queries.

**Comment by jhorwit2** [comment]
Yea, I think it's a general write performance issue.

**Comment by otoolep** [comment]
@zeroXten  @jhorwit2  - what do the logs show regarding WAL flushes? You should see messages in there.

**Comment by jhorwit2** [comment]
@otoolep When a flush happens my response time drops like crazy, as you can see above a couple comments where i pasted a log output. I tried to adjust the flush time to be quicker to see if that would help; however, it didn't seem to make it any quicker as I didn't see the frequency of flushes getting logged. You can see the settings I tried a few comments above

**Comment by jhorwit2** [comment]
Well, after diving into the code, I realized that the flush parameters in the configuration are not valid anymore.

These
```
  MaxWALSize
  WALFlushInterval
  WALPartitionFlushDelay
```

should be 

```
max-wal-size
max-flush-interval
max-partition-flush-delay
```

If I decrease my max wall size  & flush interval I can easily sustain way more points / second in batches. I'm able to sustain over 800 points / second (so 1 http request w/ 800 points per second) when I flush way more often at a sub 200ms response time. Is there anything bad about this approach?

**Comment by jhorwit2** [comment]
Actually, it appears that simply making the configuration change in #3298 drastically speeds up performance, even keeping defaults. (no idea why... as it appears the code sets the same defaults??) I'm sending about 2-2.4k metrics per second with no creep in response times. I tested this on two separate machines (both different OS and hardware and both timed out in load testing) and they both repeated this increase in performance.

**Comment by beckettsean** [comment]
@jhorwit2 sounds like you've solved the issue with WAL tuning, that's great!

We notice that you are writing the `random` values as strings rather than floats. If you ever want to do functions on those it's better to write them as a floating point value. E.g.

`300lo random=0.3466630607195913,foo="bar",foo1="bar",foo2="bar",foo3="bar",foo4="bar" 1436495866036`

**Comment by jhorwit2** [comment]
@beckettsean Yea, I was just using random values for the load test. A question I have though is should the WAL parameters be lowered by default? It seems the default settings are geared towards points that are bigger in size (where you would fill up the 100mb drain size quickly)

I haven't had time to dive deep into the core code, but my hypothesis is that as more points are added to the queue, it takes longer and longer to sort & filter (or w/e it does) the values, which causes write performance to take a huge hit. Over time this causes times outs and makes the system unrecoverable.
