### ISSUE TITLE
change the influx.conf

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb#3285]
i use influxd config > influx.conf get the config file, how can i do to change the file, and make i work. i change the file and mv the file to /opt/influxdb/, but it is not work.

**Comment by jhorwit2** [comment]
if you run `./opt/influxdb/influxd -config /opt/influxdb/influx.conf` it should start with the confi file at the given path.

**Comment by mjdesa** [comment]
@kcrosswind what @jhorwit2 said is spot on.
