### ISSUE TITLE
I am unable to drop measurements.

### ISSUE THREAD

**Issue by shilpisharma** [influxdb/influxdb#3286]
I inserted records using curl.

curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=42.64 1422823500000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=42.94 1422824400000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.27 1422825300000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=42.86 1422826200000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.02 1422827100000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=44.5 1422828000000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.49 1422828900000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.08 1422829800000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.86 1422830700000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=44.02 1422831600000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.78 1422832500000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.53 1422833400000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=43.08 1422834300000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=42.83 1422835200000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=42.25 1422836100000'
curl -i -XPOST 'http://localhost:8086/write?db=influxtest&precision=ms' -d 'tempF value=41.63 1422837000000'

When I try to drop the measurement from CLI it give me an error as shown below:

> drop measurement temperature
ERR: bucket not found
> select * from measurement
ERR: error parsing query: found MEASUREMENT, expected identifier at line 1, char 15
> select * from temperature
ERR: measurement not found: "influxtest"."default".temperature
> exit

now if I stop db and restart it using 
sudo /etc/init.d/influxdb stop
sudo /etc/init.d/influxdb start

If I check again in DB, the measurement is still there:
> select count(value) from temperature
name: temperature
-----------------
time                    count
1970-01-01T00:00:00Z    45785

administrator@administrator-IdeaCentre-Q190:~$ sudo /etc/init.d/influxdb stop
influxd process was stopped [ OK ]
administrator@administrator-IdeaCentre-Q190:~$ sudo /etc/init.d/influxdb start
Starting the process influxd [ OK ]
influxd process was started [ OK ]
administrator@administrator-IdeaCentre-Q190:~$ influx
Failed to connect to http://localhost:8086
InfluxDB shell 0.9.0
> use influxtest
Using database influxtest
> select count(value) from temperature
name: temperature
-----------------
time                    count
1970-01-01T00:00:00Z    45785

> 

I have tried dropping from HTTP, lots of things. Nothing seems t o work. Please help.

**Comment by otoolep** [comment]
Can you please upgrade to 0.9.1 and try again?

https://influxdb.com/download/index.html

**Comment by shilpisharma** [comment]
Updating the version worked. Thanks.

**Comment by beckettsean** [comment]
Great, thanks for the update, @shilpisharma
