### ISSUE TITLE
Website says 0.9.2 nightly but it is a 0.9.1

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#3287]
The web site say you can download the nightly 0.9.2 but we download a 0.9.1 rc version as this version is already released.

**Comment by otoolep** [comment]
0.9.2 has not been officially tagged yet, so the version format is that generated by `git describe --tags`, means that it shows the number commits on the master branch, since the last tag (which is v0.9.1).

**Comment by otoolep** [comment]
To be clear you are running code that will become the 0.9.2 release.

**Comment by dtouzeau** [comment]
thanks
