### ISSUE TITLE
[0.9.2ish-nightly] influxdb panic on launch on Windows, built from source

### ISSUE THREAD

**Issue by TheSecondMile** [influxdb/influxdb#3294]
I got influx working on windows 7 about a month ago but I need to upgrade in order to use continuous queries (they don't work in the version that I had but I think that bug has since been fixed). The problem is that, when I try to execute influxd.exe, it completes execution and so doesn't stay connected to localhost:8086. In the previous version I was using, I just ran influxd.exe and it didn't exit unless I closed it so I could query on localhost:8086 from my browser. 

There is no error message, it just executes and connects for a second and then disconnects. The influx version I'm trying to use is 0.9.2-pre.

For installation, I am using the guide here : https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md

```
mkdir -p $GOPATH/src/github.com/influxdb
cd $GOPATH/src/github.com/influxdb
git clone https://github.com/influxdb/influxdb.git
cd $GOPATH/src/github.com/influxdb/influxdb
cp .hooks/pre-commit .git/hooks/
cd $GOPATH/src/github.com/influxdb
go get -u -f -t ./...
go build ./...
go install ./...
```

For execution I go to my Go\projects\bin folder and execute influxd.exe:
```
cd Go\projects\bin
influxd
```

My GOPATH is set to `C:\Go\Projects` and my GOROOT is set to `C:\Go\`

**Comment by beckettsean** [comment]
@TheSecondMile thanks for the report. We have done only the barest minimum testing on Windows and the nightly builds are not tested at all on Windows. I don't see anything obviously wrong.

What is in the InfluxDB logs? If the process is exiting early perhaps there's a panic or another warning.

**Comment by TheSecondMile** [comment]
There is a panic that I didn't see when I posted this issue. It says "panic: interface conversion: interface is nil, not *internal.CreateNodeCommand.

**Comment by beckettsean** [comment]
@TheSecondMile try deleting your data files and restarting the system. That particular panic is a raft protocol error and is unrecoverable in our experience.
