### ISSUE TITLE
Convert SHOW MEASUREMENTS to distributed query

### ISSUE THREAD

**Issue by dgnorton** [influxdb/influxdb#3296]

**Comment by li-ang** [comment]
Is the issue fixed?

**Comment by dgnorton** [comment]
@li-ang yes

**Comment by JulienChampseix** [comment]
@dgorton the warning on influxdb clustering documentation (https://influxdb.com/docs/v0.9/guides/clustering.html) can be removed for this issue ?

**Comment by dgnorton** [comment]
@JulienChampseix  for this particular issue (`SHOW MEASUREMENTS`), yes.

**Comment by beckettsean** [comment]
Thanks for the reminder, @JulienChampseix: https://github.com/influxdb/influxdb.com/issues/451
