### ISSUE TITLE
[0.9.1] Field type conflict

### ISSUE THREAD

**Issue by dennisbauer** [influxdb/influxdb#3305]
I'm using influxdb-java to connect to influxdb from my Java project. In my application I'm collecting sensor data with a field (named value, collected als float numbers) and a different set of tags. As described in influxdb/influxdb-java#55 I'm getting the following error from time to time. This is happening while
a) sending sensor data directly to influxdb (not described in the referenced issue)
b) after storing them as json while no connection is available and send them when connection is established again

```java
07-07 07:24:06.418   9821-11560 E/DatabaseInfluxDB﹕ write failed: field type conflict: input field "value" is type int64, already exists as type %!s(influxql.DataType=1)
    java.lang.RuntimeException: write failed: field type conflict: input field "value" is type int64, already exists as type %!s(influxql.DataType=1)
            at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
            at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
            at java.lang.reflect.Proxy.invoke(Proxy.java:397)
            at org.influxdb.impl.$Proxy0.writePoints(Unknown Source)
            at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:156)
            at de.fhg.ipa.wearatwork.DatabaseInfluxDB$1.run(DatabaseInfluxDB.java:63)
            at java.lang.Thread.run(Thread.java:818)
```

What I already tried is chaning the field's numbers to BigDecimal and Double. It's happening less in the following order then, but it's not completely solved:
Float > BigDecimal > Double

It seems to me like influxdb is storing e.g. 10.0 as an Integer and let's say the next value is 10.5 and then I am getting an error. Any ideas how to solve this? Probabyle a possibility to add variable's type to line protocol?

Thanks,
Dennis

**Comment by jwilder** [comment]
If the values are floats, they must always have a decimal when sending them via the line protocol.  e.g. `1` must be sent as `1.0`, `0` as `0.0`.  The first value sent determines the type stored for the field.  From the error message, It looks like you sent an integer but it was stored as a float.

**Comment by beckettsean** [comment]
@dennisbauer This does indeed sound like a case where float values are occasionally being sent without a decimal. This is something that must be handled client-side before submission to the line protocol write endpoint. 

It sounds like the influxdb-java library needs some way of turning integers into floats when appropriate. That repo is not maintained directly by InfluxDB team members, so I encourage you to open an issue there to try and address this in the library itself.
