### ISSUE TITLE
java write data

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb#3322]
because my project use jdk 1.6，i can not use the java-api. so i do the http post myself. where can i find the struct for the data to write.

url = "http://localhost:8086/write"
HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        con.setDoOutput(true);
OutputStream wr = con.getOutputStream();
 wr.write(stringBuilder.getBytes(UTF_8));
 wr.flush();
stringBuilder={"database":"write_test","point":[{"table":"cpu","fields":{"value":5}}]}
it is not work.

**Comment by kcrosswind** [comment]
i want to know if the http://localhost:8083 is work, i use data explore to write data, but the json body is always wrong.

**Comment by beckettsean** [comment]
@kcrosswind what version of InfluxDB are you running. If you can write data through the admin interface at localhost:8083 you are most likely not on the latest version. Please upgrade to 0.9.1 if possible.

The documentation for writing data is here: https://influxdb.com/docs/v0.9/guides/writing_data.html

**Comment by kcrosswind** [comment]
@beckettsean 
thank you for help
