### ISSUE TITLE
[0.9.1] (regression) simple regex query fails with cryptic error

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3326]
`SELECT * FROM /.*/ LIMIT 1`, which appears in our 0.9 docs three times, now fails with an error about fields in a GROUP BY.

```
> SELECT * FROM /.*/ LIMIT 1
ERR: can not use field in group by clause: host
```

This worked in 0.9.0, doesn't work in 0.9.1.

**Comment by jacekgrzybowski** [comment]
@beckettsean what if I need to get grouped results from all series alltogether? Example:

    SELECT MAX(value) AS max FROM /^response_times.service_1.*/ WHERE time > now() - 1d GROUP BY time(6h)

Result:

    response_times.service_1.pl.warsaw.dc1
    time  max
    2015-07-19T00:00:00Z  942
    2015-07-20T00:00:00Z  949
    2015-07-21T00:00:00Z  888
    response_times.service_1.us.new-york.dc3
    time  max
    2015-07-19T00:00:00Z  993
    2015-07-20T00:00:00Z  873
    2015-07-21T00:00:00Z  917

And I would like to get results grouped just as a single serie.

**Comment by mjdesa** [comment]
Similar issue

```
> insert thing,"query"=yay value=1
> select * from thing
ERR: can not use field in GROUP BY clause: query
```
