### ISSUE TITLE
[0.9.1] Drop database deletes data/ directory

### ISSUE THREAD

**Issue by PierreF** [influxdb/influxdb#3330]
On master (56d3add), when I issue a "DROP DATABASE name", the folder ~/.influxdb/data is removed, meaning all data files are removed. So after a restart (because influxdb keep some file opened) I've lost all data from all databases.

Version 0.9.1 is also affected.

Step to reproduce:

* clean ~/.influxdb to start from fresh setup (`rm -fr ~/.influxdb`)
* Start influxdb
* With UI, issue `CREATE DATABASE db1` and `CREATE DATABASE db2`
* With UI, write into both database (I'm writting `cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000`, from the doc)
* Check with `SHOW MEASUREMENTS` that writes succeed.
* Also check that two folder "db1" and "db2" exists under `~/.influxdb/data`
* With UI Issue `DROP DATABASE db1`
* Folder `~/.influxdb/data` no longer exists ! (so db2's file are deleted from disk)
* Restart influxdb, db2 still exists but is empty (`SHOW MEASUREMENTS` return nothing)

**Comment by mjdesa** [comment]
@pauldix @otoolep any ideas?

**Comment by otoolep** [comment]
One for @dgnorton, @jwilder and @benbjohnson too.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3335

**Comment by otoolep** [comment]
@mjdesa -- we don't usually close issues until a PR is merged.

**Comment by otoolep** [comment]
Merged to master.

Thanks the reports @mjdesa and @PierreF
