### ISSUE TITLE
Support for Decreasing Resolution of Data

### ISSUE THREAD

**Issue by icebourg** [influxdb/influxdb#3333]
Looking through the docs and the Github Issues, I haven't seen this discussed. (please feel free to point me to any previous discussion on this if I've missed it)

We currently run telegraf in production posting to InfluxDB every 10 seconds. As far as I can tell, that means we will store 10-secondly level of data forever. In contrast, in Graphite we have a retention policy set up that we'll have 10-second resolution for something like a day, then minutely resolution for a month, then 5-minutely resolution for a year.

This is different from the InfluxDB [retention policies](https://influxdb.com/docs/v0.9/administration/administration.html) which seem to be pretty binary. (keep all data we are supposed to retain -- drop all the rest)

Any idea if this will be implemented or how we can go about achieving similar results?

Thanks.

AJ

**Comment by otoolep** [comment]
Continuous Queries are the canonical way to do this in InfluxDB. You set up a CQ to query one retention policy, perform an aggregate, and write that at aggregated data into a different retention policy.

https://influxdb.com/docs/v0.9/query_language/continuous_queries.html

**Comment by dgipps** [comment]
@otoolep The linked docs page doesn't say anything about a continuous query that goes from one retention policy (not one specific measurement) to another retention policy. Lets say I have a retention policy "metrics" and I want to downsample data to "metrics_hourly". I see how I could do this individually for each measurement I have in metrics, but given that I have a lot measurements and will likely add more in the future, a single continuous query would be a lot better.

Based on what you said above it sounds like that should exist, but could you point me to documentation on the format for that continuous query?

**Comment by beckettsean** [comment]
@dgipps we're working on improved CQ documentation (https://github.com/influxdb/influxdb.com/issues/159) 

As for a single CQ that consumes multiple measurements, that is not yet possible, but this issue (https://github.com/influxdb/influxdb/issues/2555) is the request for a backreference for regex that would make it possible. It's slated for the 0.9.3 release but will likely slip into 0.9.4.
