### ISSUE TITLE
Group by nothing

### ISSUE THREAD

**Issue by ntfournier** [influxdb/influxdb#3336]
When I do a SELECT * FROM measurements I get multiples series.

It is possible to group the results by one/several tags using ``GROUP BY [tagname]``. 

Now, can I group all results?

Is it possible to make a GROUP BY "nothing" to have all series merged together?

**Comment by beckettsean** [comment]
This is current design but not the long-term desired behavior. Unfortunately, with `SELECT *` there is currently a hack/workaround that implicitly does a `GROUP BY *` to return the tags. As such, `SELECT *` cannot currently be executed without at least an implicit hidden `GROUP BY`.

`SELECT fieldval1, fieldval2, etc.` with no `GROUP BY` will automatically merge all series together, but you will need to explicitly name the fields you wish to query.

**Comment by beckettsean** [comment]
Related to https://github.com/influxdb/influxdb/issues/3326, regarding the internal `GROUP BY *`

**Comment by jacekgrzybowski** [comment]
@beckettsean what if I need to get grouped results from all series alltogether? Example:

    SELECT MAX(value) AS max FROM /^response_times.service_1.*/ WHERE time > now() - 1d GROUP BY time(6h)

Result:

    response_times.service_1.pl.warsaw.dc1
    time  max
    2015-07-19T00:00:00Z  942
    2015-07-20T00:00:00Z  949
    2015-07-21T00:00:00Z  888
    response_times.service_1.us.new-york.dc3
    time  max
    2015-07-19T00:00:00Z  993
    2015-07-20T00:00:00Z  873
    2015-07-21T00:00:00Z  917

And I would like to get results grouped just as a single serie.
