### ISSUE TITLE
InfluxDB 500 timeout errors when ingesting data into InfluxDB

### ISSUE THREAD

**Issue by samidalouche** [influxdb/influxdb#3349]
How to reproduce

Download and extract https://drive.google.com/file/d/0B5ighvmMo-dYbHBrUE9rTjl3V1U/view?usp=sharing

Start with a fresh influxdb 0.9.1 on Mac OS X
```bash
curl -G http://influxdb:8086/query --data-urlencode "q=CREATE DATABASE mydb"
for i in dest/** ; do curl -i -XPOST 'http://influxdb:8086/write?db=mydb&precision=ms' --data-binary "@$i" ; done
```

After a while, curl will output errors such as

HTTP/1.1 500 Internal Server Error
Request-Id: bbe9d518-2be7-11e5-80e9-000000000000
X-Influxdb-Version: 0.9.1
Date: Thu, 16 Jul 2015 18:23:25 GMT
Content-Length: 8
Content-Type: text/plain; charset=utf-8

timeout
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
Request-Id: bf83e187-2be7-11e5-80ea-000000000000
X-Influxdb-Version: 0.9.1
Date: Thu, 16 Jul 2015 18:23:30 GMT
Content-Length: 8
Content-Type: text/plain; charset=utf-8

timeout
HTTP/1.1 100 Continue

-----

On the InfluxDB side, the kind of logs we have is

[http] 2015/07/16 14:23:25 ::1 - kpi [16/Jul/2015:14:23:19 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 bbe9d518-2be7-11e5-80e9-000000000000 6.031924575s
[http] 2015/07/16 14:23:30 ::1 - kpi [16/Jul/2015:14:23:25 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 bf83e187-2be7-11e5-80ea-000000000000 5.024233432s
[http] 2015/07/16 14:23:35 ::1 - kpi [16/Jul/2015:14:23:30 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 c2846812-2be7-11e5-80eb-000000000000 5.024393663s
[http] 2015/07/16 14:23:40 ::1 - kpi [16/Jul/2015:14:23:35 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 c584e0f5-2be7-11e5-80ec-000000000000 5.022836486s
[http] 2015/07/16 14:23:45 ::1 - kpi [16/Jul/2015:14:23:40 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 c88514b7-2be7-11e5-80ed-000000000000 5.024503321s
[http] 2015/07/16 14:23:50 ::1 - kpi [16/Jul/2015:14:23:45 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 cb856a0c-2be7-11e5-80ee-000000000000 5.023451153s
[retention] 2015/07/16 14:24:40 retention policy enforcement check commencing
[retention] 2015/07/16 14:24:40 retention policy shard deletion check commencing
2015/07/16 14:24:46 new shard group 32 successfully created for database mydb, retention policy default
2015/07/16 14:24:48 new shard group 33 successfully created for database mydb, retention policy default
[shard] 2015/07/16 14:25:49 flush 1 points in 0.001s
[shard] 2015/07/16 14:25:49 flush 1996 points in 0.015s
[shard] 2015/07/16 14:25:51 flush 2 points in 0.000s
[shard] 2015/07/16 14:25:51 flush 1996 points in 0.004s
[shard] 2015/07/16 14:25:53 flush 1 points in 0.001s
[shard] 2015/07/16 14:25:53 flush 998 points in 0.003s
[shard] 2015/07/16 14:25:53 flush 2132 points in 0.005s
[shard] 2015/07/16 14:25:55 flush 1 points in 0.001s

**Comment by otoolep** [comment]
Thanks for the report @samidalouche . Have you tried reducing the size of your WAL? Perhaps by 50%?

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L39

I'd like to know if this helps.

**Comment by samidalouche** [comment]
No, I have not, I will try and reply with the results

**Comment by samidalouche** [comment]
Same thing. Ends up timing out 

http] 2015/07/16 15:37:59 ::1 - - [16/Jul/2015:15:37:54 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 277a796b-2bf2-11e5-8028-000000000000 5.029369274s
[http] 2015/07/16 15:38:04 ::1 - - [16/Jul/2015:15:37:59 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 2a7bc52f-2bf2-11e5-8029-000000000000 5.026220061s
[http] 2015/07/16 15:38:10 ::1 - - [16/Jul/2015:15:38:04 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 2d7c7291-2bf2-11e5-802a-000000000000 5.02902371s

**Comment by samidalouche** [comment]
I also tried increasing the timeouts to 15s, and I still see the requests failing after 5s

[cluster]
  shard-writer-timeout = "15s"
  write-timeout = "15s"

[http] 2015/07/16 15:41:10 ::1 - - [16/Jul/2015:15:41:05 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 9923ba86-2bf2-11e5-8021-000000000000 5.021813866s
[http] 2015/07/16 15:41:15 ::1 - - [16/Jul/2015:15:41:10 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 9c23bb6c-2bf2-11e5-8022-000000000000 5.034980458s
[http] 2015/07/16 15:41:20 ::1 - - [16/Jul/2015:15:41:15 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 9f25a120-2bf2-11e5-8023-000000000000 5.022640187s
[http] 2015/07/16 15:41:25 ::1 - - [16/Jul/2015:15:41:20 -0400] POST /write?db=mydb&precision=ms HTTP/1.1 500 8 - curl/7.37.1 a225c753-2bf2-11e5-8024-000000000000 5.02453319s

**Comment by samidalouche** [comment]
I even tried a much lower WAL size 
 max-wal-size = 26214400

**Comment by gunnaraasen** [comment]
@samidalouche It looks like that file contains 305 files with 10000 points in each file. The InfluxDB will crash if you try to pump 3.05 million points into it at the same time.

A single node can sustain between 5000 and 10000 points per second.

**Comment by samidalouche** [comment]
@gunnaraasen I tried a variant of the script that sleeps 15 seconds between each curl (thus largely reducing the ingestion rate below 5000 points per second):

for i in dest/** ; do curl -i -XPOST 'http://influxdb:8086/write?db=mydb&precision=ms' --data-binary "@$i" ; sleep 15 ; done

And I still get the same issue.

**Comment by otoolep** [comment]
Let's re-open this, there are some ingestion issues being reported and we need to look into this.

**Comment by jwilder** [comment]
@sakamotomsh Thanks for the test script.  I was able to reproduce this w/ 0.9.1 branch but not with master.  The profile showed that there was too much time spent sorting the WAL which is the same issue as #3159.

The fix should be in the latest nightly builds and will also be in 0.9.2.
