### ISSUE TITLE
[0.9.3 nightly] derivative() on bools returns 0, should return parser error

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3353]
Issuing the select statement

```
select derivative(value) from bool
```

causes

```
panic: expected either int64 or float64, got false
```

**Comment by rnubel** [comment]
This appears to be a regression; #2548 originally added support for this, but after major refactorings, that code is now orphaned in the unused function [Shard#ValidateAggregateFieldsInStatement](https://github.com/influxdb/influxdb/blob/ee614054a107a907c98a9cbddd7b44f6868ed571/tsdb/shard.go#L498). @pauldix might have an idea of where it should be called from, or if it needs to be updated.

**Comment by otoolep** [comment]
Thanks @rnubel -- it should be easy to port this change to the new code.

**Comment by beckettsean** [comment]
No longer panics the db in 0.9.3 nightly

```
> insert bool value=T
> insert bool value=F
> insert bool value=T
> insert bool value=F
> select * from bool
name: bool
----------
time				value
2015-08-18T23:05:22.03751526Z	true
2015-08-18T23:05:25.057646886Z	false
2015-08-18T23:05:26.905708926Z	true
2015-08-18T23:05:28.441897777Z	false

> select derivative(value) from bool
name: bool
----------
time				derivative
2015-08-18T23:05:22.03751526Z	0

```

Probably should return a query parser error rather than 0, but that's minor.

**Comment by pauldix** [comment]
We can't validate this at the parser level. And there's no guarantee that a field is a bool in all shards. Going to close this for now as won't fix. As long as the server doesn't crash.
