### ISSUE TITLE
[0.9.1] Failed to start hinted handoff processor after ansible install

### ISSUE THREAD

**Issue by logston** [influxdb/influxdb#3354]
I'm getting the following error when I try and restart the influxdb process:

```
ubuntu@ip-10-0-0-249:/var/log/influxdb$ sudo /etc/init.d/influxdb restart
influxd process is not running [ OK ]
Starting the process influxd [ OK ]
influxd process failed to start [ FAILED ]
ubuntu@ip-10-0-0-249:/var/log/influxdb$
```

`/var/log/influxdb/influxdb.log` shows the following:

```
GOMAXPROCS set to 1
2015/07/16 21:38:37 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
GOMAXPROCS set to 1
[handoff] 2015/07/16 21:46:16 Failed to start hinted handoff processor: mkdir all: mkdir /home/ubuntu/.influxdb: permission denied
```

So I added the directory `/home/ubuntu/.influxdb` and now I get the following in the log file:

```
GOMAXPROCS set to 1
[handoff] 2015/07/16 21:50:20 Failed to start hinted handoff processor: mkdir all: mkdir /home/ubuntu/.influxdb/hh: permission denied
```

I don't want to have to create all the necessary hidden directories. I'm sure there's something I'm missing that's causing influx to loose permissions to create directories. 

I can't run the `/etc/init.d/influxdb restart` as ubuntu because that user does not have sufficient permissions. For example:

```
ubuntu@ip-10-0-0-249:/var/log/influxdb$ /etc/init.d/influxdb restart
influxd process is not running [ OK ]
/etc/init.d/influxdb: line 151: ulimit: open files: cannot modify limit: Operation not permitted
set open file limit to 65536 [ FAILED ]
```

Funny enough, I already have my open file limit set to 65536 on this machine. 

The only customization I have in my `influxdb.conf` file is the following:

```
[http]
 ... 
auth-enabled = true
 ...
```

**Comment by beckettsean** [comment]
@otoolep something wonky with restart and HH

**Comment by logston** [comment]
Forgive me, but what is "HH"

**Comment by logston** [comment]
Can I safely turn off hinted-handoff if I'm not using more than the vanilla installation of influxdb? 

```
[hinted-handoff]
  enabled = false
  ...
```

Vanilla installation being this:
```
wget http://influxdb.s3.amazonaws.com/influxdb_0.9.1_amd64.deb
sudo dpkg -i influxdb_0.9.1_amd64.deb
```

**Comment by logston** [comment]
Found a fix.

I noticed that I had an `influxdb` user on my remote machine but that user had no home directory. I created the home dir for this user, `chmod`ed control over the dir to the `influxdb` user, and updated the `/etc/opt/influxdb/influxdb.conf` to read `/home/influxdb/` where it was `/home/ubuntu/` before. 

Thus, it looks like installation of influx via Ansible maybe problematic. I used the following script to install influxdb on my remote machine. 

```yml
- name: Get Influxdb package
  get_url: url=http://influxdb.s3.amazonaws.com/influxdb_0.9.1_amd64.deb
           dest=/tmp/influxdb_0.9.1_amd64.deb
           force=yes

- name: Install Influxdb
  apt: deb="/tmp/influxdb_0.9.1_amd64.deb"
```

Might not install this package correctly.

**Comment by beckettsean** [comment]
@logston Hinted handoff only has relevance for a cluster, it's effectively meaningless in a single node environment.

**Comment by logston** [comment]
Thanks @beckettsean

**Comment by otoolep** [comment]
HH has been refactored recently, I don't think we have an issue any longer.
