### ISSUE TITLE
[0.9.1+ from source] derivative function responds with error

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3355]
Just upgraded to the latest version.

Issuing the command

```
select derivative(value) from cpu_user
```

returns 

```
ERR: expected function argument to derivative
```

**Comment by mjdesa** [comment]
@jwilder any idea why this is happening?

**Comment by otoolep** [comment]
You mean you built from master?

**Comment by otoolep** [comment]
I change the query-engine code. Is this a regression?

**Comment by otoolep** [comment]
Can you show us:

`service influxd version`

**Comment by connor4312** [comment]
I also get this, just having pulled from master (hash 64020798088d15ed2a8d83932b3f3fe46159b373)

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3361

**Comment by otoolep** [comment]
Thanks for the report @mjdesa @connor4312
