### ISSUE TITLE
aggregate query returns no data

### ISSUE THREAD

**Issue by gucki** [influxdb/influxdb#3366]
Using a fesrh install of 0.9.1:
 
    > CREATE DATABASE "netskin"
    > USE netskin
    Using database netskin

    > INSERT net.tx,host=r-ch100,interface=switch value=0
    > INSERT net.tx,host=r-ch101,interface=switch value=30

    > SELECT * FROM "netskin"."default"."net.tx"
    name: net.tx
    tags: host=r-ch100, interface=switch
    time        value
    ----        -----
    2015-07-17T18:54:15.864057189Z  0

    name: net.tx
    tags: host=r-ch101, interface=switch
    time        value
    ----        -----
    2015-07-17T18:54:17.235394579Z  30

    > SELECT MAX(value) FROM "netskin"."default"."net.tx" WHERE time > 0 GROUP BY time(5m)
    name: net.tx
    ------------
    time      max
    1970-01-01T00:00:00Z

Expected out is something like:

    name: net.tx
    tags: host=r-ch100, interface=switch
    time        value
    ----        -----
    2015-07-17T18:50:0Z  0

    name: net.tx
    tags: host=r-ch101, interface=switch
    time        value
    ----        -----
    2015-07-17T18:50:0Z  30

**Comment by otoolep** [comment]
Can you please check again with a nightly build? https://influxdb.com/download/index.html

There have been some changes in the query enegin, that may address this issue.

**Comment by gunnaraasen** [comment]
The `WHERE time > 0` means the query is requesting 5m groups from 1970 to present and is attempting to return 4,790,412 points. It fails because the `GROUP BY` clause will only return a maximum of 100k points in a single query. See https://github.com/influxdb/influxdb/issues/2702.
