### ISSUE TITLE
[0.9.2-rc1] : ORDER BY asc giving error: "only ORDER BY ASC supported at this time"

### ISSUE THREAD

**Issue by olivierHa** [influxdb/influxdb#3380]
Hello, 

Using 0.9.2-rc1, I got an issue with Grafana : 

Looking at the query sent, I can reproduice it with influxdb cli : 

> SELECT sum(value) FROM "count" WHERE provider = 'xxx' AND time > now() - 6h GROUP BY time(60s), api ORDER BY asc;
ERR: only ORDER BY ASC supported at this time

> SELECT sum(value) FROM "count" WHERE provider = 'xxx' AND time > now() - 6h GROUP BY time(60s), api ORDER BY ASC;
ERR: only ORDER BY ASC supported at this time

> SELECT mean(value) FROM "count" WHERE time > now() - 6h GROUP BY time(60s) ORDER BY ASC; 
ERR: only ORDER BY ASC supported at this time

Regards

Olivier

**Comment by olivierHa** [comment]
Steps to reproduice : 


```
/opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.2-rc1
InfluxDB shell 0.9.2-rc1
> create database test;
> use test
Using database test

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000' 
HTTP/1.1 204 No Content
Request-Id: c302d1f3-2ed9-11e5-8006-000000000000
X-Influxdb-Version: 0.9.2-rc1
Date: Mon, 20 Jul 2015 12:20:52 GMT

/opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.2-rc1
InfluxDB shell 0.9.2-rc1
> use test
Using database test
> select * from cpu_load_short order by time asc;
ERR: error parsing query: only ORDER BY ASC supported at this time
```

**Comment by beckettsean** [comment]
Possible regression in 0.9.2. For me, the following query runs without issue in 0.9.1:

`> select sum(value) from cpu_idle where time > now() - 10m group by time(1m),cpu  order by asc`

**Comment by beckettsean** [comment]
@olivierHa if you leave the `ORDER BY` clause off the queries, they should perform as expected. Does that address your issue?

**Comment by olivierHa** [comment]
Indeed it was working using 0.9.1, so I think it is a regression.
And yes, removing the "order by asc" is a working fine. Thanks for the
workaround.



2015-07-20 22:46 GMT+02:00 Sean Beckett <notifications@github.com>:

**Comment by otoolep** [comment]
Yeah, this is a regression. Something up with the parsing perhaps.
