### ISSUE TITLE
what is the meaning of the time in web client displayed

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb#3388]
http://localhost:8083
query:select * from temperature
displayed:time    value
but the time is not my written. is it the local time? maybe it will different in different timezone. where can i to change it. i am in china. Display is not correct.

**Comment by beckettsean** [comment]
Please ask questions on the mailing list influxdb@googlegroups.com or email support@influxdb.com. GitHub Issues are for feature requests or actionable bug reports.

All times in InfluxDB are stored and reported in UTC. There is no ability to change that yet.

**Comment by kcrosswind** [comment]
@beckettsean 
how can i join the gmail list? i send mail, but no reply.
thank you

**Comment by beckettsean** [comment]
I replied a little less than an hour ago to your "the longest column name" email. Response times to the mailing list are 1-5 days, generally speaking.

**Comment by kcrosswind** [comment]
it is solved. Thank you for your help
