### ISSUE TITLE
HTTP write : bad timestamp

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdb/influxdb#3397]
Hi,
I'm using curl to send a data file that was generated on a windows machine, and i'm getting an error : 

> unable to parse 'frequency,frequency=0,ma=45,pola': bad timestamp49824.00000 1436277850000

When I convert the line endings of this file to `\n` instead of `\r\n`, the lines are correctly written into the database.

Is this a normal behaviour?

**Comment by beckettsean** [comment]
The line protocol requires newline separators (`\n`), and carriage returns cause parsing issues. This is expected behavior.
