### ISSUE TITLE
How to write efficiently a large amount of data for a single timestamp

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdb/influxdb#3398]
Hi,
I have a system that generates 96 * 2 frequencies spectrum each minute (the first tag has 96 values, and each value has 2 values for the second tag). Each spectrum physically represents one point in time. However, each spectrum is composed of 512 values.

I tried to tell InfluxDB to have 512 fields, but it seems to be limited to 255 (if I remember the code I read, that is MAX(uint8) - 1

I also tried having 512 values for a tag, but the read and write performance were awful (about 30s to write if I remember well, and 10s to read, only for a single minute).

What I end up to do is splitting by 512 values into 4 batches of 128 values, each having a "batch" tag from 0 to 3.

Is there a better way to do this? Is there any chance to have this field number limit incremented/configurable in the future?

**Comment by beckettsean** [comment]
There are no current plans to increase the number of fields per measurement.

You didn't mention what version you were testing, but write performance is significantly improved from 0.9.0 to 0.9.2. It could be that simply upgrading or waiting for another point release will resolve your performance issues. It sounds from your experience that your writes and queries were about as non-performant as possible, as even 0.9.0 InfluxDB can handle writing 10k points per second if reasonably well tuned. 

Did you batch up your writes? Sending single points is much more expensive than sending batches of 100-5000 points each.

Did you send your writes in order of increasing timestamp? InfluxDB assumes that points come in roughly in temporal order, so if you send lots of old points before new points, that can cause performance issues.

**Comment by jeremyVignelles** [comment]
Using 0.9.1, I am trying to send 192 files of 512 points each.
For a fresh database (I'm using Docker), with this configuration file:
```
bind-address = "0.0.0.0"
port = 8086
reporting-disabled = false

[meta]
  dir = "/var/opt/influxdb/meta"
  commit-timeout = "1s"

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083
  assets = "/opt/influxdb/current/admin"

[api]
  bind-address = "0.0.0.0"
  port = 8086

[collectd]
  enabled = false

[opentsdb]
  enabled = false

[udp]
  enabled = false

[broker]
  dir = "/data/broker"
  enabled = true
  election-timeout = "0"

[data]
  dir = "/data/db"
  enabled = true
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "10s" # The delay time between each WAL partition being flushed.

[snapshot]
  enabled = false

[logging]
  write-tracing = false
  raft-tracing = false
  level  = "info"
  file   = "/opt/influxdb/shared/log.txt"

[monitoring]
  enabled = false

[debugging]
  pprof-enabled = false

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"
  disabled = false

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"


[cluster]
  shard-writer-timeout = "5s" # The time within which a shard must respond to write.
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.
```

Trying to send in sequence my 192 files of 512 points each:
Total time : 155883ms
The following chart shows the integration time over file number
![Integration times over file number](https://cloud.githubusercontent.com/assets/3399355/8795280/fd33d12e-2f8b-11e5-8e8d-850149a89943.png)


When trying to batch these files into one big file, the result is "timeout".
Supposing I'm able to write those data in a reasonable way, the query
```sql
SELECT value FROM frequency GROUP BY ma, polar, frequency ORDER BY asc LIMIT 1
```
takes 6.6s to get the data.

To answer your last question, the 96*2*512 points have all the exact same timestamp because they are retrieved at the same time. This is why it makes sense for us to have 512 fields.

Thanks for your answer :smiley:

**Comment by gunnaraasen** [comment]
@jeremeyVignelles can you provide some example points?

Might be worth reexamining why you were getting such bad results with tags. It sounds like at least some of the fields should be moved into tags. 

Also, try bumping up the batch size to 1000-5000 points per batch and testing on 0.9.2-rc1.

**Comment by jeremyVignelles** [comment]
Hi,
Just made a configurable testing script using node.js : https://gist.github.com/jeremyVignelles/3ebd42f66f9d078e0c41
You must have async installed in the folder with `npm i async`

Here is what I got on my machine : 

* `cargoSize = 512;` : 23651ms to upload
* `cargoSize = 512*2*96;` : timeout after 5s the first time. The second time is ok
* `cargoSize = 5000;` : 9072ms
I also tried on 0.9.2-rc1 with the same results.

The query `SELECT value FROM test GROUP BY i,j,k LIMIT 1` is still slow (~5s on 0.9.1) but is much slower on 0.9.2-rc1 : 33s!

Could you try on your computer?

**Comment by beckettsean** [comment]
@mjdesa here's a possible perf test case

**Comment by mjdesa** [comment]
@jeremyVignelles just ran the test script you gave and I'm getting the following as a result

```
generateData: 269ms
STATUS: 204
upload: 4571ms
total: 4578ms
```

**Comment by gunnaraasen** [comment]
The query engine was completely rewritten behind the scenes for 0.9.2-rc1 and unfortunately a fairly serious performance bug was introduced. The fix will be in 0.9.2-rc2.

With that many tags, the first request will be significantly slower than subsequent requests due to the overhead incurred when new series are created. As you note, subsequent writes are much faster. Also, something seems off on your test results for smaller batch sizes. @mjdesa What are your results for 512, 2000, 5000, and 10000 point batches?

For queries like `SELECT value FROM test GROUP BY i, j, k LIMIT 1`, moving data into fields will indeed give much better query times. In my crude testing, inserting a batch of 512 points each with 192 fields writes at 241ms (1.3s first write) and `SELECT * FROM test GROUP BY i LIMIT 1` on that data returns in 227ms using the latest master.

@jeremyVignelles Can you try your benchmark with the field heavy approach using the latest master?

**Comment by jeremyVignelles** [comment]
Updated gist to have more configuration: 
https://gist.github.com/jeremyVignelles/3ebd42f66f9d078e0c41

With this new script, here are the results I have:

version|iCount|jCount|pointsCount|fieldsCount|write1|write2|read
-------|------|------|-----------|-----------|------|------|----
0.9.1|96|2|4|128|2231|667|442
0.9.1|96|2|512|1|timeout|4145|5872
0.9.1|96|2|1|255|1723|405|193
0.9.2-rc1|96|2|4|128|2237|667|693
0.9.2-rc1|96|2|512|1|timeout|4068|32757
0.9.2-rc1|96|2|1|255|2746|384|311
nightly(2015-07-23 08:13 UTC)|96|2|4|128|2298|658|721
nightly(2015-07-23 08:13 UTC)|96|2|512|1|timeout|4314|33370
nightly(2015-07-23 08:13 UTC)|96|2|1|255|1784|409|305

Looking at the results, it would be a huge benefit for us to have 512 fields rather than 512 tags. Moreover, the 512 values have the same time and are not meant to be used separately. Being able to configure the max number of columns (something like being able to tell the database to use 2-bytes indexes) would be a good point for influxDB integration in our project. 
Is it hard to implement? Would it make the database slower? heavier?

**Comment by mjdesa** [comment]
Here's what I get for writes

| Batch Size | Round 1 | Round 2 |
|----------------|-------------|--------------|
| 512    |    3230ms  |   1117ms |
| 2000  | 2933ms | 890ms |
| 5000  |  2931ms | 914ms |
| 10000 | 2863ms | 889ms |
| 512*2*96 | 4516ms | 954ms |

**Comment by gunnaraasen** [comment]
@jeremyVignelles Can you open new issue with a feature request for making the max number of fields configurable? I'm not sure how hard that would be to implement or the performance impact.

The other option to increasing the max number of fields would be to encoding all the values into a single string value. Of course, that would require some additional client side processing and limit the usefulness of some InfluxDB features like aggregate functions.

Going to close this issue since it seems like the performance (on the latest master) is in line with expectations.
