### ISSUE TITLE
[0.9.1] After Restart of one Node cant access data

### ISSUE THREAD

**Issue by diiidiii** [influxdb/influxdb#3410]
I've got the following problem: i have 3 nodes with clustering. When i stop or restart 1 node, everything goes right because i can access the data on the other two nodes and look at grafana. 
Now the big problem: When the node starts again i get always the debug info "Failed to contact x.x.x.x" and "Rejecting vote from x.x.x.x since we have a leader: x.x.x.x"
Now i restarted all nodes again and it works like it should: 

GOMAXPROCS set to 24
2015/07/21 10:06:47 [INFO] raft: Node at x.x.x.x [Follower] entering Follower state
2015/07/21 10:06:47 read local node id: 1
2015/07/21 10:06:49 [DEBUG] raft-net: x.x.x.x accepted connection from: x.x.x.x
2015/07/21 10:06:49 [DEBUG] raft: Node x.x.x.x updated peer set (2): [x.x.x.x     x.x.x.x       x.x.x.x]
2015/07/21 10:06:50 [DEBUG] raft-net: x.x.x.x accepted connection from: x.x.x.x

But when i look at the disk space there are a few differences. Leader got ~ 170gb, the other two ~ 150gb. Access via Grafana or in shell doesnt work...

Failed to connect to http://hostname:port
InfluxDB shell 0.9.1

Is it normal that i have to delete all my data?

**Comment by spicykaiju** [comment]
Has anyone else experienced this problem? We would like to migrate to 0.9.x from 0.8.8 and we currently have a 2 node cluster that experiences data corruption.

**Comment by gunnaraasen** [comment]
@diiidiii clustering is in alpha for 0.9.1 and failure scenarios are not fully defined. The raft consensus should be reestablished when the downed node comes back up. Is there anything in the logs when you try to query the restored cluster? Also, does the IP/bind address for the downed node change or remain the same?

Do the disk usage numbers include log files or is that number only the size of the InfluxDB `/data` directory?

@spicykaiju 0.9.1 restricts clusters to three nodes. Also, a 2 node cluster for 0.8 will have trouble establishing raft consensus. The recommended minimum cluster size is 3 nodes.

**Comment by diiidiii** [comment]
@gunnaraasen In the log of leader i can see the following when i start the cluster:

2015/07/24 08:30:04 [ERR] raft: Failed to AppendEntries to 4.128.2.141:8088: dial tcp 4.128.2.141:8088: connection refused
2015/07/24 08:30:04 [WARN] raft: AppendEntries to 4.128.2.139:8088 rejected, sending older logs (next: 245)
2015/07/24 08:30:04 [ERR] raft: Failed to AppendEntries to 4.128.2.141:8088: dial tcp 4.128.2.141:8088: connection refused
2015/07/24 08:30:04 [INFO] raft: pipelining replication to peer 4.128.2.139:8088
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.140:8088 4.128.2.139:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.141:8088 4.128.2.139:8088 4.128.2.140:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.141:8088 4.128.2.139:8088 4.128.2.140:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088]
2015/07/24 08:30:04 [INFO] raft: Removed peer 4.128.2.141:8088, stopping replication (Index: 240)
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [INFO] raft: Added peer 4.128.2.141:8088, starting replication
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.139:8088 4.128.2.140:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.140:8088 4.128.2.139:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [DEBUG] raft: Node 4.128.2.140:8088 updated peer set (2): [4.128.2.140:8088 4.128.2.139:8088 4.128.2.141:8088]
2015/07/24 08:30:04 [ERR] raft: Failed to AppendEntries to 4.128.2.141:8088: dial tcp 4.128.2.141:8088: connection refused
2015/07/24 08:30:04 [ERR] raft: Failed to AppendEntries to 4.128.2.141:8088: dial tcp 4.128.2.141:8088: connection refused
2015/07/24 08:30:04 [ERR] raft: Failed to AppendEntries to 4.128.2.141:8088: dial tcp 4.128.2.141:8088: connection refused
2015/07/24 08:30:04 [WARN] raft: AppendEntries to 4.128.2.141:8088 rejected, sending older logs (next: 246)
2015/07/24 08:30:05 [INFO] raft: pipelining replication to peer 4.128.2.141:8088
2015/07/24 08:33:24 [INFO] raft: aborting pipeline replication to peer 4.128.2.139:8088
2015/07/24 08:33:24 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: EOF
2015/07/24 08:33:24 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:24 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [WARN] raft: Failed to contact 4.128.2.139:8088 in 500.206257ms
2015/07/24 08:33:25 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [WARN] raft: Failed to contact 4.128.2.139:8088 in 980.813355ms
2015/07/24 08:33:25 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:25 [WARN] raft: Failed to contact 4.128.2.139:8088 in 1.472383519s
2015/07/24 08:33:26 [ERR] raft: Failed to heartbeat to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:26 [DEBUG] raft: Failed to contact 4.128.2.139:8088 in 1.915859666s
2015/07/24 08:33:26 [ERR] raft: Failed to AppendEntries to 4.128.2.139:8088: dial tcp 4.128.2.139:8088: connection refused
2015/07/24 08:33:26 [DEBUG] raft: Failed to contact 4.128.2.139:8088 in 2.384023158s
2015/07/24 08:33:27 [INFO] raft: pipelining replication to peer 4.128.2.139:8088

The IP/Bind Adress doesnt change... The disk usage is with logs etc. When i try to open influxdb shell it says: Failed to open ...

**Comment by diiidiii** [comment]
Now it works... i think it needs some time to sync.
