### ISSUE TITLE
500 timeout on write

### ISSUE THREAD

**Issue by xkrt** [influxdb/influxdb#3411]
Hi,

If I write following line (generated by QuickCheck-like tool, actually):
```
>curl -XPOST "http://localhost:8086/write?db=mydb" -d "cpu \a=1"
timeout
```
I got 500 with `timeout` in body. The problem occurs probably because of field key `\a`.

After that, any other writes with "normal" field keys returns same 500 timeout:
```
>curl -XPOST "http://localhost:8086/write?db=mydb" -d "cpu v=1"
timeout
```

InflixDB 0.9.1

**Comment by Xyaren** [comment]
I seem to have a similar issue but am not able to identify the breaking POST..

Any idea how to identify it ? 

The post comes most likely from Telegraf.
