### ISSUE TITLE
Grouped results merged for multiple series

### ISSUE THREAD

**Issue by jacekgrzybowski** [influxdb/influxdb#3412]
What I need to do is to get results from multiple series with group option merged into a single serie:

    SELECT MAX(value) AS max FROM /^response_times.service_1.*/ WHERE time > now() - 1d GROUP BY time(6h)

Result:

    response_times.service_1.pl.warsaw.dc1
    time  max
    2015-07-19T00:00:00Z  942
    2015-07-20T00:00:00Z  949
    2015-07-21T00:00:00Z  888
    response_times.service_1.us.new-york.dc3
    time  max
    2015-07-19T00:00:00Z  993
    2015-07-20T00:00:00Z  873
    2015-07-21T00:00:00Z  917

Desired feature result:

    /^response_times.service_1.*/
    time  max
    2015-07-19T00:00:00Z  1935
    2015-07-20T00:00:00Z  1822
    2015-07-21T00:00:00Z  1805

**Comment by gunnaraasen** [comment]
The data schema provided is not canonical for InfluxDB. The measurement should be `response_times` and descriptors like `service` and `dc` should be included as tags. Then the query would be

```
SELECT MAX(value) AS max FROM response_times WHERE service = 1 AND time > now() - 1d GROUP BY time(6h)
```

Also, check out the [Graphite plugin](https://github.com/influxdb/influxdb/tree/master/services/graphite).

**Comment by jacekgrzybowski** [comment]
Thanks a lot, I need to migrate my data to 0.9 supported schema then.
