### ISSUE TITLE
Handoff fails to parse data with missing tag values.

### ISSUE THREAD

**Issue by nathanielc** [influxdb/influxdb#3417]
I am using the OpenTSDB pluing to write data to InfluxDB. Sometimes the data that comes in is missing a tag value. I don't see any error on ingestion, but when the handoff tries to replicate the metric it gets and error like

`[handoff] 2015/07/21 03:59:56 retried write failed: unable to parse 'disk,type=disk_time,type_instance= value=3.0 1437436501000000000': missing tag value`

Seems like what ever sends the data to the handoff process should omit the empty tag or the handoff should tolerate the missing tag value.

Running version InfluxDB v0.9.1-rc1-201-g5206c0e (git: 5206c0e4b950b94f6a8ec384594caa304c603247)

**Comment by beckettsean** [comment]
closed by #3420
