### ISSUE TITLE
Next() on TagSet Cursor is linear with cursor count

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3418]
Stress testing shows that the following code is causing long query times when the series cursor count is 42K:

```
   7.26s      7.26s    572:func (mc *seriesCursor) Peek() (key int64, value []byte) {
    25.20s     25.20s    573:    if mc.keyBuffer == -1 {
         .       60ms    574:        k, v := mc.cursor.Next()
         .          .    575:        if k == nil {
         .          .    576:            mc.keyBuffer = 0
         .          .    577:        } else {
         .          .    578:            mc.keyBuffer = int64(btou64(k))
         .          .    579:            mc.valueBuffer = v
         .          .    580:        }
         .          .    581:    }
         .          .    582:
    11.10s     11.10s    583:    key, value = mc.keyBuffer, mc.valueBuffer
     2.15s      2.15s    584:    return
         .          .    585:}
```

**Comment by otoolep** [comment]
The implementation of `Peek()` simply put a wrapper around value-buffer code that has been in the query-engine for a quite a while. `Peek()` may be called a lot, but most of the time it will be returning stuff from memory. So the search is linear with the number of cursors.

Basically, all this peeking is a re-write of this: 

https://github.com/influxdb/influxdb/blob/8ade485b5865e642b128a7cc6eb20c9da73d1b48/tx.go#L510

**Comment by otoolep** [comment]
@benbjohnson : yeah, it was a problem before too. it's a linear search on every Next() call.

**Comment by otoolep** [comment]
@dgnorton @jwilder

**Comment by otoolep** [comment]
From a user's point of view this can actually cause write timeouts since it can cause queries to hold locks for too long.

**Comment by otoolep** [comment]
![peek](https://cloud.githubusercontent.com/assets/536312/8811565/9d7a74fc-2fab-11e5-871c-b859e4fb9c58.jpg)

**Comment by otoolep** [comment]
Perhaps we can use this to build a priority queue of cursors:

http://golang.org/pkg/container/heap/

where the highest-priority cursor is the one with the lowest timestamp.

**Comment by beckettsean** [comment]
@dgnorton did your heap changes fix this?

**Comment by dgnorton** [comment]
@beckettsean  yes

**Comment by beckettsean** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/3520
