### ISSUE TITLE
Add PointsBatcher to OpenTSDB service

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3423]
Also include the commented config options in the opentsdb section of the sample config.

**Comment by otoolep** [comment]
@DanielMorsing -- want to look at this? The batcher used by Graphite needs to be integrated with openTSDB.

**Comment by DanielMorsing** [comment]
#3780

**Comment by otoolep** [comment]
All done for 0.9.4

https://github.com/influxdb/influxdb/pull/4043
