### ISSUE TITLE
Influx - Port binding

### ISSUE THREAD

**Issue by shilpisharma** [influxdb/influxdb#3433]
Hi,

At times when I start influxDB process, the process get started but the port 8086 is not binded.
Understandably I am unable to do any insertions using HTTP API. However, an hour later without changing anything on the environment, the port suddenly binds. This behavior is a little strange.

Any clue why this is and how we can avoid this?

Shilpi

**Comment by beckettsean** [comment]
@shilpisharma can you provide the log statements from startup and then from later when the port is bound?

What version are you running? I think with 0.9.1 the http listener didn't start until after the WAL flushes completed. If you somehow have a huge number of points in the WAL, that might keep the http service from starting (shouldn't take an hour, but maybe a few minutes)

**Comment by shilpisharma** [comment]
Please find below the logs:

2015/07/22 17:09:45 new shard group 25158 successfully created for database influxtest, retention policy default
GOMAXPROCS set to 2
2015/07/22 17:14:45 [INFO] raft: Restored from snapshot 51-24625-1437596327070
2015/07/22 17:14:45 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
2015/07/22 17:14:45 read local node id: 1
2015/07/22 17:14:47 [WARN] raft: Heartbeat timeout reached, starting election
2015/07/22 17:14:47 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
2015/07/22 17:14:47 [DEBUG] raft: Votes needed: 1
2015/07/22 17:14:47 [DEBUG] raft: Vote granted. Tally: 1
2015/07/22 17:14:47 [INFO] raft: Election won. Tally: 1
2015/07/22 17:14:47 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
2015/07/22 17:14:47 [INFO] raft: Disabling EnableSingleNode (bootstrap)
2015/07/22 17:14:54 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[httpd] 2015/07/22 17:29:04 listening on HTTP: [::]:8086
2015/07/22 17:29:04 Sending anonymous usage statistics to m.influxdb.com
[http] 2015/07/22 17:31:18 127.0.0.1 - - [22/Jul/2015:17:31:18 -0400] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.9.1 fd322917-30b8-11e5-8001-000000000000 109.736µs

It started listening to the port in 16 minutes.

**Comment by beckettsean** [comment]
@shilpisharma what version of InfluxDB?

**Comment by beckettsean** [comment]
The service used to wait before bringing up the HTTP listener, it should be up as soon as the service is alive, now. Things like WAL flushes and loading the index into RAM no longer block the listener.

Please re-open if you still see this behavior with 0.9.3 nightly builds, or with the 0.9.3 final coming later this week.
