### ISSUE TITLE
Seeing 'tcp.Mux: handler not registered' messages in 0.9.2rc1

### ISSUE THREAD

**Issue by ecables** [influxdb/influxdb#3441]
Running influx-0.9.2rc1 in a 3-node cluster, and seeing these messages on one of the nodes:
```
...
2015/07/22 18:53:26 tcp.Mux: handler not registered: 71
2015/07/22 18:53:26 tcp.Mux: handler not registered: 71
2015/07/22 18:53:26 tcp.Mux: handler not registered: 71
2015/07/22 18:53:26 tcp.Mux: handler not registered: 71
2015/07/22 18:53:26 tcp.Mux: handler not registered: 71
...
```

I've restarted influx, but the messages persist. Can someone explain what might be going on?

**Comment by jwilder** [comment]
Are you connecting to the correct ports for writing/querying?  That message can be logged if you try to query or write to the cluster port (default `8088`) and not the API port (default `8086`).

**Comment by ecables** [comment]
I just re-built the cluster; will monitor to see if this recurs.

**Comment by jwilder** [comment]
Please re-open if you see it again.
