### ISSUE TITLE
[0.9.2] should Retention Policy Replication factor allow values other than 3?

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#3442]
I recently upgraded to the 0.9.2 RC.  Since distributed queries are now working is it still necessary to have the retention policy equal the cluster size?  I started with a fresh database, I am still no longer allowed to create a retention policy with a replication factor less than 3.

**Comment by beckettsean** [comment]
@otoolep did we intentionally leave in the replication factor = 3 requirement?

**Comment by NickPadilla** [comment]
Hello, I'd like to see if this is the case. I added a influx.conf file and it has the auto creation of the retention policy but i keep getting a 'retention policy not found' when trying to query for values.  I do see the 'default' one there but I also tried creating one with a 'replication' at 1.  It still isn't working, do I have to have a cluster to make the new version work? Is it possible that adding a configuration, b/c i wanted to have authentication enabled, is causing the problems? i am on 0.9.1.

**Comment by beckettsean** [comment]
@NickPadilla for 0.9.1 you can have a cluster of 1 or a cluster of 3, and the replication factor must equal the number of nodes. That's a hardcoded requirement in 0.9.0 and 0.9.1. 

0.9.2 may or may not relax that requirement.

@pauldix can you chime in on replication factor in 0.9.2 since @otoolep is otherwise occupied?

**Comment by pauldix** [comment]
0.9.2 won't have support for different cluster sizes. Although in this release we've laid all the groundwork to lift that limitation in 0.9.3. That release will be on August 13th, but the ability to spin up larger clusters should be in a nightly build sometime next week.

**Comment by beckettsean** [comment]
Thanks for the answer, Paul. Closing this issue as the behavior is intended for 0.9.2

**Comment by otoolep** [comment]
Yes, until clustering support and distributed query rewrite are in place.

@jwilder @dgnorton

**Comment by otoolep** [comment]
Oh, I see @pauldix provided the full explanation earlier.
