### ISSUE TITLE
Go client has too many dependencies

### ISSUE THREAD

**Issue by mikedanese** [influxdb/influxdb#3447]
In upgrading `"github.com/influxdb/influxdb/client"` from 32846 (v0.8.0-rc.3-9-g328466) to 8b3219 (v0.9.1) I have to add dependencies:

```
golang.org/x/crypto/bcrypt
golang.org/x/crypto/blowfish
github.com/influxdb/influxdb/tsdb
github.com/influxdb/influxdb/toml
github.com/influxdb/influxdb/snapshot
github.com/influxdb/influxdb/meta
github.com/influxdb/influxdb/influxql
github.com/hashicorp/raft-boltdb
github.com/hashicorp/raft
github.com/hashicorp/go-msgpack/codec
github.com/golang/glog
github.com/gogo/protobuf/proto
github.com/boltdb/bolt
github.com/armon/go-metrics
```

These are not dependencies of the v0.8.0-rc.3-9-g328466 client. Why do I have to depend on a database, a raft implementation, a configuration language (among other things) to use the client? 

`"github.com/influxdb/influxdb/influxql"` and`"github.com/influxdb/influxdb/tsdb"` are the only two packages directly imported into the client. Is it possible to break up those packages so client doesn't have such a huge dependency graph?

**Comment by mark-rushakoff** [comment]
I looked into this a little bit, and saw that the [influxql package seems to only depend on standard libraries](https://godoc.org/github.com/influxdb/influxdb/influxql?imports), while the [tsdb package requires several of the mentioned dependencies](https://godoc.org/github.com/influxdb/influxdb/tsdb?imports). 

Walking through Sourcegraph a little, it looks like the client package only depends on the tsdb package to  [create a tsdb.Point and call its .String method](https://sourcegraph.com/github.com/influxdb/influxdb@a09c00653c9fb6bfe8e4a28075ea5bbaa6362568/.tree/client/influxdb.go#selected=708), so in theory, this should be straightforward to extract to a separate package.

**Comment by ameske** [comment]
Is there any plan regarding this? At the day job we have to vendor any 3rd party code we use, and this will require us to have to vendor every single one of these dependencies, which is extremely less than ideal just to use the client library. Is this something I can provide assistance with in order to make it happen? (unsure if the "category/internal" label means it's not something for outside contributors to help with)

**Comment by beckettsean** [comment]
@ameske no plan yet, no. The label shouldn't discourage any pull request you might consider, it just a catch-all.

**Comment by pauldix** [comment]
@corylanou I think we should have no external dependencies for the client, which means we're probably going to have to do some copy/paste of code. Better than this though. Thoughts?

**Comment by corylanou** [comment]
@pauldix agreed.  I think if we truly want no external dependancies, we should make the client it's own top level repo then to ensure we don't cross boundaries, and make it easier to keep an eye on updates as needed.  It will also make it easier for contributions as it should be a pretty small/simple code base as well.

**Comment by abh** [comment]
+1 for moving it back to its own repository.

**Comment by juliusv** [comment]
I don't think there need to be zero dependencies for a client library (for example, depending on something like https://godoc.org/golang.org/x/net/context to allow users to control cancellation etc. is quite reasonable). But right now it's of course way too many, and they are not even really used (like the statically compiled assets in https://github.com/influxdb/influxdb/blob/master/statik/statik.go (900kB)) that are pulled in transitively when using the InfluxDB Go client library.
