### ISSUE TITLE
Hot snapshot fails

### ISSUE THREAD

**Issue by aaronjwood** [influxdb/influxdb#3449]
I'm trying to do a backup of a running InfluxDB database (0.9.0-rc30 commit acf2dd6ba5429e95ad6a156afe7afbdc6b861979) but it fails with the message `[srvr] 2015/07/22 19:20:13 backup: download: snapshot error: status=404`

I have nothing in my configuration for disabling snapshots so I would think it should work since the docs state that it's enabled by default. Why is it giving a status of 404?

**Comment by gunnaraasen** [comment]
@aaronjwood snapshots were either not implemented or extremely buggy in version 0.9.0-rc30.

**Comment by beckettsean** [comment]
@aaronjwood please update to 0.9.1 or wait a few hours and grab 0.9.2 later today. 0.9.0-RC30 has significant known issues.

**Comment by gunnaraasen** [comment]
Keep in mind there have been breaking changes since 0.9.0-rc30 so an upgrade to 0.9.1 or 0.9.2 will not play well with an existing 0.9.0-rc30 database.

**Comment by aaronjwood** [comment]
Thanks, that's good to know. We'll be upgrading ASAP.
