### ISSUE TITLE
[0.9.2] Retention Policy Endpoint Failure

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#3450]
I upgraded to 0.9.2 from 0.9.1 recently.  It appears that whenever I try to write to a specific retention policy other than default, the tags and measurement names are populated however no points are written into the DB.  Recreation is about as follows:
```create database test```

```create retention policy short on test duration 2h replication 3```

```curl -X POST 'http://localhost:8086/write?db=test&rp=short' --data-binary 'disk_free,hostname=server01 value=442221834240 1435362189575692182'```

```select value from disk_free```

The above command results in no points being returned at all.

**Comment by beckettsean** [comment]
`select value from disk_free` is shorthand for `select value from <default>.disk_free`, where `<default>` is the default retention policy for the database. I can see from your RP creation query that you did not set `short` as the default retention policy for the `test` database.

Your query should be `select value from short.disk_free`
