### ISSUE TITLE
Influx does not force authentication with auth-enabled = true

### ISSUE THREAD

**Issue by robinjha** [influxdb/influxdb#3452]
Currently running influxdb-0.9.1
Steps to reproduce:
1.Installed Influx using brew : brew install influxdb 
2. CREATE USER admin WITH PASSWORD 'admin' WITH ALL PRIVILEGES
3. show users
    > show users
       user	admin
      admin true
4. Updated conf files: 
     vi /usr/local/etc/influxdb.conf
     vi /usr/local/etc/influxdb.conf.default 
5. Set the auth-enabled option to true in #4 and restarted influxd.
6. Executed curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE authorization". This created the database although I didn't provide a username and password.

**Comment by gunnaraasen** [comment]
This is a known issue fixed by https://github.com/influxdb/influxdb/pull/3244. Version 0.9.2, to be released later today, includes the fix.

**Comment by robinjha** [comment]
Thanks! Much appreciated.
