### ISSUE TITLE
queryDB provided in influxdb/client/README.md does not return correct error codes

### ISSUE THREAD

**Issue by stefanKnott** [influxdb/influxdb#3454]
So I realized that the queryDB function provided in client/README.md does not make proper use of Golang's return by named result parameter feature and returns successfully when it should not.

In queryDB() res and err are the named result parameters, however in the if-statement we create a local (to the if-statement) copy of err different from the result err which has already been initialized and set to 0 as the Golang named result parameter documentation states.

This causes no error to ever be returned when you query the DB as the err that returns from con.Query(q) is a local variable in the if-statement and the data within this variable is not transferred to the err result variable.  Simply pulling "response, err := con.Query(q)" out of the if-statement clause fixes this issue as the correct Query() error code is then mapped to the result err variable which the function initialized locally (and not the err variable which only the if-statement has scope over...)

func queryDB(con *client.Client, cmd string) (res []client.Result, err error) {
	q := client.Query{
		Command:  cmd,
		Database: MyDB,
	}
	if  response, err := con.Query(q); err == nil {
		if response.Error() != nil {
			return res, response.Error()
		}
		res = response.Results
	}
	return
}

This is very bad as every call to con.Query() is believed to have been successful!

**Comment by beckettsean** [comment]
@stefanKnott your recent note to support@ mentioned you were running v0.8.8. Is this issue filed against 0.8 or 0.9?

**Comment by stefanKnott** [comment]
Ah it only acts like this in 0.8 and not 0.9 as I now see through testing.

Apologies, I will close the issue.
