### ISSUE TITLE
[0.9.2-rc1] Cant select quoted field key

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#3464]
I can insert a quoted field key

```
> insert fail value=1,"break"=1
```

But when I go to query for the data I get this error

```
> select * from fail
ERR: unknown field or tag name in select clause: break
```

**Comment by jwilder** [comment]
Might be fixed by: https://github.com/influxdb/influxdb/commit/0945db75aa76b3ad87f357244fe49f51323a6d38

**Comment by mjdesa** [comment]
@jwilder yup it did
