### ISSUE TITLE
Admin Basic Auth Still Broken in 0.9.2

### ISSUE THREAD

**Issue by andyl** [influxdb/influxdb#3466]
Basic Auth was reported broken in Issue #3222 and #3300, and closed as fixed.

I just downloaded 0.9.2 and am still getting the same error.

**Comment by scharissis** [comment]
+1

With a fresh install I, I get the following error in the console:
`No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by beckettsean** [comment]
@mjdesa can you repro?

**Comment by gunnaraasen** [comment]
It looks like `influxd` only has an `OPTIONS` request handler on the `/write` endpoint and won't respond to `OPTIONS` requests on the `/query` endpoint. PR #3474 should fix the error.
