### ISSUE TITLE
[0.9.2] (regression) Error reading from measurement named "Measurement"

### ISSUE THREAD

**Issue by phagunbaya** [influxdb/influxdb#3467]
Created series with name "Measurement", and after reading from the series, I see an error.

Query : `select * from "Measurement"`
Error   : `Server returned error: found MEASUREMENT, expected identifier at line 1, char 98`

It was working fine with 0.9.0 and as well as 0.9.1

**Comment by beckettsean** [comment]
Can you please include the actual CLI or curl commands you are running? The error stonly implies you have at least 98 characters in your actual query, yet your example is only 27 characters long.

**Comment by beckettsean** [comment]
I can repro with 0.9.2:

```
Connected to http://localhost:8086 version 0.9.2
InfluxDB shell 0.9.2
> use mydb
Using database mydb
> insert Measurement value=1
> select * from Measurement
ERR: error parsing query: found MEASUREMENT, expected identifier at line 1, char 15
> select * from "Measurement"
ERR: found MEASUREMENT, expected identifier at line 1, char 36
> select * from 'Measurement'
ERR: error parsing query: found Measurement, expected identifier at line 1, char 14
> show measurements
name: measurements
------------------
name
Measurement
...
```

as long as the exact name isn't `measurement` it seems to parse fine.

```
> insert Measurement1 value=1
> select * from "Measurement1"
name: Measurement1
------------------
time				value
2015-07-27T04:29:09.991429754Z	1

```

**Comment by mjdesa** [comment]
Similar issue from `stats` 

```
> insert stats value=10
> select * from stats
ERR: error parsing query: found STATS, expected identifier at line 1, char 15
```

**Comment by beckettsean** [comment]
I'm curious why the error from the correctly double-quoted measurement gives a character number that is nonsense. The original submitter had "expected identifier at line 1, char 98", mine, with identical syntax, is on "char 36", and Michael's, which is a shorter line than mine, errors on "char 45". None of the statements are long enough to have that many characters. 

@dgnorton is the parser walking off the end of the statement somehow?

**Comment by mjdesa** [comment]
Similar issue

```
> insert thing,"query"=yay value=1
> select * from thing
ERR: can not use field in GROUP BY clause: query
```

**Comment by gunnaraasen** [comment]
Does the same error occur on queries which do not use `*`? It looks like the error is occurring after the `*` is expanded and the query statement is re-parsed, which would explain the nonsensical error locations on the line.

**Comment by mjdesa** [comment]
Without the `*` I get 

```
> select value from "stats"
ERR: found STATS, expected identifier at line 1, char 36
```

**Comment by DanielMorsing** [comment]
Tested this on master. Looks like #3560 fixed it.

**Comment by consolacion** [comment]
I am afraid #3560 didnt quite fix it. I have exactly the same problem
![influx](https://user-images.githubusercontent.com/8614925/36607459-fe4effda-18c6-11e8-9be9-d7485980881f.png)

**Comment by desa** [comment]
@consolacion the users password needs to be single quoted. See https://docs.influxdata.com/influxdb/v1.4/query_language/spec/#create-user

**Comment by consolacion** [comment]
Thank you and please beat me over the head with an old diskdrive for overlooking this
