### ISSUE TITLE
influxd backup /tmp/mysnapshot   gives an EMPTY backup

### ISSUE THREAD

**Issue by ibobak** [influxdb/influxdb#3470]
I launched influxd backup /tmp/mysnapshot  following help manual
https://influxdb.com/docs/v0.9/administration/backup_and_restore.html

on the last version (which I got by running
wget http://influxdb.s3.amazonaws.com/influxdb-0.9.2-1.x86_64.rpm
sudo rpm -ivh influxdb-0.9.2-1.x86_64.rpm

Result:  the file /tmp/mysnapshot is simpy EMPTY.

**Comment by mjdesa** [comment]
@ibobak by default snapshotting is disabled. If you'd like to enable snapshotting add

```
[snapshot]
enabled = true
```

to you influxdb config file.

**Comment by ibobak** [comment]
then why not to output a message  "snapshots are disabled"  when I am doing "influxd backup" ?

**Comment by mjdesa** [comment]
@ibobak yeah thats probably a good idea. Open up an issue for it.
