### ISSUE TITLE
Question: Upper limit for tags

### ISSUE THREAD

**Issue by shilpisharma** [influxdb/influxdb#3471]
I have a small question. Is there an upper limit to how many tags we can add in InfluxDB?

**Comment by mjdesa** [comment]
From the [docs](https://influxdb.com/docs/v0.9/concepts/schema_and_data_layout.html)

>As a rule of thumb, keep tag cardinality below 100,000. The limit will vary depending on the resources available to InfluxDB, but it is best to keep tag cardinality as low as possible. If you have a value in your data with high cardinality, it should probably be a field, not a tag.

**Comment by beckettsean** [comment]
The 100k number is very rough. If you stay below that you should be fine. With tag cardinality in the millions schema and query design become more important, as it becomes easier to create poor performance situations.

We will document this more extensively as performance testing matures.

**Comment by kotwal13aditya** [comment]
An extension to the question: is there a limit to the length of a tag?

**Comment by beckettsean** [comment]
Not really. There used to be a 64k limit but that was removed with the TSM engine. I suspect 4GB would be the limit now, but anything above a few thousand KB seems like a bad idea, just for throughput concerns.

Remember, the full uncompressed tag set lives in memory as the index. No better way to chew up RAM than with 10KB tag names and values.

**Comment by kotwal13aditya** [comment]
Thanks @beckettsean

**Comment by elvarb** [comment]
Sorry to add to this issue, but by tag cardinality does that include both tag keys and tag values or just one or the other?

**Comment by desa** [comment]
@elvarb usually we mean a single tag key with many tag values as the the cardinality of a tag. As mentioned above this is very much just a rule of thumb and is increasingly not relevant.

At the moment we're working on https://github.com/influxdata/influxdb/issues/7151 which will remove these types of restrictions.

**Comment by elvarb** [comment]
@desa thanks for the info, I have been testing using influxdb to track logs and using tags for the log metadata. Extremely promising and glad to hear that this possible problem will be removed in the future.

**Comment by ivanpricewaycom** [comment]
eek. we just ran into this. given that retention policies can't go less than an hour we are eating all available ram (16g) within the hour with (fairly) unique tag sets of source / destination IP/port plus volume counters (cisco netflow logging). aggregating doesn't help coz just the initial data is killing us, let alone our desire to archive aggregated data. we've got a stress-test python script that simulates our load in case it's interesting.

-i

**Comment by lrtanner** [comment]
Data newb here. This has been a useful issue to read, but can someone explain cardinality in terms of InfluxDB tags?

**Comment by ivanpricewaycom** [comment]
the latest versions of influx address this with disk-based indexing..

https://www.influxdata.com/blog/path-1-billion-time-series-influxdb-high-cardinality-indexing-ready-testing/

https://docs.influxdata.com/influxdb/v1.5/concepts/tsi-details/

**Comment by priori** [comment]
Would be a good idea to use influxdb to try to count accesses with a lot of information in tags? To get something close to Google Analytics and Matomo... With some big quantity of tags in a "request" measurement like: requestId, appName, appExecutionId, userId, userSessionId, apiRoute, url and apiRouteMainParam, userAgent, browser, ip? Could be a good idea replace my matomo for a "request" measurement in influxdb?
