### ISSUE TITLE
[0.9.1] Including integer literal in continuous query causes panic

### ISSUE THREAD

**Issue by njurgens** [influxdb/influxdb#3476]
I've create a continuous query that downsamples data into 10 second bins.  As part of this query I create a new field `length` and set it to `10`.  This causes the database to immediately crash.

    CREATE CONTINUOUS QUERY "downsample" ON mydb BEGIN
        SELECT sum(value), 10 AS length INTO "1h".data FROM "default".data GROUP BY time(10s)
    END

I've created a gist that reproduces the crash and includes the crash log: https://gist.github.com/njurgens/9a459ccdc3b8c3a7255b.

**Comment by beckettsean** [comment]
It is no longer possible to create a CQ that mixes aggregates and single values:

```
> create continuous query foo on foo begin 
     select sum(value), 10 as bar into newfoo from thing group by time(1m) 
   end
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported
```
