### ISSUE TITLE
Influxdb crashes when on invalid input via UDP

### ISSUE THREAD

**Issue by juddgaddie** [influxdb/influxdb#3485]
Reproducibility: 100%
Influx version: 0.9.1
Enable UDP in influxdb.conf

nc -u 127.0.0.1 $influx_udp_port
cpu\,01,host=serverA,region=us-west

panic: runtime error: slice bounds out of range

goroutine 26 [running]:
github.com/influxdb/influxdb/tsdb.scanKey(0xc208142000, 0x23, 0x10000, 0x23, 0xc20811b4b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/points.go:296 +0x682
github.com/influxdb/influxdb/tsdb.parsePoint(0xc208142000, 0x23, 0x10000, 0xecd498bd4, 0x382bcde2, 0xe9e4c0, 0xad1050, 0x1, 0x0, 0x0, ...)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/points.go:141 +0x86
github.com/influxdb/influxdb/tsdb.ParsePointsWithPrecision(0xc208142000, 0x24, 0x10000, 0xecd498bd4, 0x382bcde2, 0xe9e4c0, 0xad1050, 0x1, 0x0, 0x0, ...)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/points.go:124 +0x22a
github.com/influxdb/influxdb/tsdb.ParsePoints(0xc208142000, 0x24, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/points.go:102 +0xe8
github.com/influxdb/influxdb/services/udp.(*Service).serve(0xc20809c120)
	/home/philip/build/src/github.com/influxdb/influxdb/services/udp/service.go:121 +0x28a
created by github.com/influxdb/influxdb/services/udp.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/udp/service.go:72 +0x6e6

goroutine 1 [chan receive (nil chan), 11 minutes]:
main.(*Main).Run(0xc20801bf60, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:75 +0x450
main.main()
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:35 +0x1d3

goroutine 6 [syscall, 11 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 8 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.func·004()
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:461 +0xed
created by github.com/influxdb/influxdb/cmd/influxd/run.startProfile
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:464 +0x4d4

goroutine 17 [syscall, 11 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [IO wait, 11 minutes]:
net.(*pollDesc).Wait(0xc208010450, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010450, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080103f0, 0x0, 0x7f84b98e2cc8, 0xc2080ec020)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803ad10, 0xaf2770, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803ad10, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080bbc50, 0x7f84b98e9298, 0xc20803ad10, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:290 +0x7a8

goroutine 10 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803ad18, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080bbc80, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/meta/store.go:1803 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080104d0)
	/home/philip/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/home/philip/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080b81c0)
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080b81c0)
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080b81c0)
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/home/philip/build/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/build/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080b81c0)
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/home/philip/build/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/build/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 13 [select, 2 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080b81c0)
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/home/philip/build/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/home/philip/build/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/build/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 15 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803ad20, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208072280)
	/home/philip/build/src/github.com/influxdb/influxdb/meta/store.go:467 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/home/philip/build/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2

goroutine 16 [select, 11 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080340d0, 0xc2080404e0)
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:412 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:296 +0x919

goroutine 18 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc20804d360)
	/home/philip/build/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef

goroutine 19 [select, 11 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc20804d360)
	/home/philip/build/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109

goroutine 20 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803ad28, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc2080102a0)
	/home/philip/build/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67

goroutine 21 [select]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc20800ad70)
	/home/philip/build/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb

goroutine 22 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803ad30, 0x0, 0x0, 0x0, 0x0)
	/home/philip/build/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc20800ae60)
	/home/philip/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62

goroutine 23 [IO wait, 11 minutes]:
net.(*pollDesc).Wait(0xc208010a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080109a0, 0x0, 0x7f84b98e2cc8, 0xc2080ec160)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803ade8, 0xc208066380, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803ade8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc2080e0120, 0x7f84b98e9298, 0xc20803ade8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f84b98e9298, 0xc20803ade8, 0x7f84b98eaae0, 0xc2080ec150, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc2080bba70)
	/home/philip/build/src/github.com/influxdb/influxdb/services/admin/service.go:71 +0x147
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/admin/service.go:39 +0xd9

goroutine 24 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc208010310)
	/home/philip/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:151 +0x301
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed

goroutine 25 [IO wait]:
net.(*pollDesc).Wait(0xc208010a70, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010a70, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010a10, 0x0, 0x7f84b98e2cc8, 0xc20809e410)
	/usr/local/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803adf0, 0xc2080f3dc8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803adf0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208041860, 0x7f84b98e9298, 0xc20803adf0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f84b98e9298, 0xc20803adf0, 0x7f84b98eaa90, 0xc208010380, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20807b840)
	/home/philip/build/src/github.com/influxdb/influxdb/services/httpd/service.go:83 +0x79
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/httpd/service.go:51 +0x283

goroutine 27 [select, 6 minutes]:
github.com/influxdb/influxdb/services/udp.(*Service).writePoints(0xc20809c120)
	/home/philip/build/src/github.com/influxdb/influxdb/services/udp/service.go:82 +0x41e
created by github.com/influxdb/influxdb/services/udp.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/udp/service.go:73 +0x703

goroutine 28 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc208040b40)
	/home/philip/build/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67

goroutine 29 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208040b40)
	/home/philip/build/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/home/philip/build/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81

goroutine 30 [chan receive, 11 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc2080340d0)
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:363 +0x18e
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:319 +0xdbb

goroutine 31 [select, 11 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc2080403c0)
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:118 +0x2da
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	/home/philip/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:102 +0xa2e

goroutine 32 [select, 6 minutes]:
github.com/influxdb/influxdb/tsdb.func·002()
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/batcher.go:69 +0x512
created by github.com/influxdb/influxdb/tsdb.(*PointBatcher).Start
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/batcher.go:102 +0x29a

goroutine 89 [IO wait]:
net.(*pollDesc).Wait(0xc208010990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010930, 0xc20819e000, 0x1000, 0x1000, 0x0, 0x7f84b98e2cc8, 0xc20809e568)
	/usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20815e110, 0xc20819e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:121 +0xdc
net/http.(*liveSwitchReader).Read(0xc208176188, 0xc20819e000, 0x1000, 0x1000, 0x2800000000000000, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:214 +0xab
io.(*LimitedReader).Read(0xc208130e60, 0xc20819e000, 0x1000, 0x1000, 0xc2085e3940, 0x0, 0x0)
	/usr/local/go/src/io/io.go:408 +0xce
bufio.(*Reader).fill(0xc208134900)
	/usr/local/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).ReadSlice(0xc208134900, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:295 +0x257
bufio.(*Reader).ReadLine(0xc208134900, 0x0, 0x0, 0x0, 0xc207ff0100, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:324 +0x62
net/textproto.(*Reader).readLineSlice(0xc2080fe000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:55 +0x9e
net/textproto.(*Reader).ReadLine(0xc2080fe000, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/textproto/reader.go:36 +0x4f
net/http.ReadRequest(0xc208134900, 0xc2081140d0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:598 +0xcb
net/http.(*conn).readRequest(0xc208176140, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:586 +0x26f
net/http.(*conn).serve(0xc208176140)
	/usr/local/go/src/net/http/server.go:1162 +0x69e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x35e

goroutine 51 [select, 11 minutes]:
net/http.(*persistConn).readLoop(0xc208064420)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 52 [select, 11 minutes]:
net/http.(*persistConn).writeLoop(0xc208064420)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc

goroutine 41 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc2080644d0, 0xc20816f140)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:453 +0x385
created by github.com/influxdb/influxdb/tsdb.func·008
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 46 [select, 6 minutes]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc208064580, 0xc208134720)
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:453 +0x385
created by github.com/influxdb/influxdb/tsdb.func·008
	/home/philip/build/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

**Comment by jwilder** [comment]
This is fixed in `0.9.2`.
