### ISSUE TITLE
Cant read data points.

### ISSUE THREAD

**Issue by mbejda** [influxdb/influxdb#3486]
Tested On : 
Influxdb Shell Version : InfluxDB shell 0.9.1
Influxdb Shell Version : InfluxDB shell 0.9.2

Go Version : go version go1.4.2

I connect to my Influxdb database that is hosted on influxdb.com.

Execute the following command : 
<code>Show databases; </code>
And get : 
<pre>
{ Results []client.Result "json:\"results,omitempty\""; Err string "json:\"error,omitempty\"" }
</pre>

**Comment by mjdesa** [comment]
@mbejda how did you execute the `show databases` command? You mentioned client version that you're using is 0.9.x, but which version of Influxdb are you using? Can you recreate the issue locally?

**Comment by mbejda** [comment]
Ok Im closing this issue. There is a influxdb 0.8.x to influxdb 0.9.x shell incompatibility. The hosted service still uses influxdb 0.8.x database and locally Im using 0.9.2. So you cant use influxdb 0.9.x shell to communicate in influxdb 0.8.x database.  You need to use influxdb 0.8.x shell to communciat with influxdb 0.8.x database. I wish this was written somewhere in the docs. XD. :tangerine:

**Comment by mjdesa** [comment]
@mbejda I'll open an issue in the `influxdb.com` repo for this.
