### ISSUE TITLE
[0.9.1] LIMIT in some queries may use too much RAM

### ISSUE THREAD

**Issue by esecules** [influxdb/influxdb#3492]
In both the command line client as well as through the web API, a "limit" in the query has no effect. This is potentially harmful since paging through mounds of data is now impossible because 
```
SELECT * FROM huge_table LIMIT 10 OFFSET 0
 ```
will give me not the first 10 items but all of them which has run my host out of memory (8GB)

**Comment by beckettsean** [comment]
@esecules there must be something else going on. `LIMIT` worked as intended in 0.9.1 and also in 0.9.2. Perhaps you are confusing `SLIMIT` and `LIMIT`?  

`LIMIT 10` will return the 10 oldest points *per series* from the `huge_table` measurement. If you have a number of tag sets in the `huge_table` measurement that might still return hundreds or thousands of points. 

`SLIMIT 10` will return the 10 oldest points and only 10 points from `huge_table`

I created https://github.com/influxdb/influxdb.com/pull/169 to update the docs.

It doesn't seem like either should explode the RAM usage that much, though. How did you submit the query, and what was the exact syntax?

**Comment by esecules** [comment]
Limiting sometimes works like it does with this query:
```SELECT "value" FROM large_series WHERE tag='1234' LIMIT 1```
but when selecting * it is ignored.
```SELECT * FROM large_series WHERE tag='1234' LIMIT 1```
the series ```large_series``` has data from older versions of influx and probably makes up the majority of my database of about 4.5GB but Im not sure of an efficient way to check. 

However when I created a new test database to make sure this is a bug I did a couple of inserts and limiting works in both of the above cases.

**Comment by beckettsean** [comment]
"has data from older versions of influx"

Do you mean older 0.9.x versions, or did you manually migrate from 0.8?

Can you provide sample output of the `SELECT * FROM large_series WHERE tag='1234' LIMIT 1` query? I have no issue with that query whatsoever.

```
> select * from cpu_idle where cpu='cpu7' limit 1
name: cpu_idle
tags: cpu=cpu7, host=catalyst
time				value
----				-----
2015-07-15T17:43:58.500619733Z	30130.7734375

> 
```

**Comment by esecules** [comment]
I mean it has 0.9.0 as well as 0.9.1

**Comment by esecules** [comment]
```
> SELECT count(value) FROM large_series WHERE tag='1234'
name: large_series
------------
time			count
1970-01-01T00:00:00Z	159
```
```
SELECT * FROM large_series WHERE tag='1234' LIMIT 1
name: large_series
tags: <38 tags, not all assigned>
time			           value
----			        	-----
2015-07-29T00:27:52Z		0

<the above times 159 with unique timestamps> 
```

**Comment by beckettsean** [comment]
That's not necessarily the wrong behavior. Again the query is slightly obfuscated so I can't tell exactly what's happening, but the query will return 1 point for each unique tag set where `tag=1234`. Given that there are 37 other tags, each with an unknown number of possible values, maybe there is a unique series for each of the 159 returned points.

Is that the case? If not, would you be willing to share the actual un-edited query results? Otherwise there's not much more to go on, except perhaps this is related to legacy data, but I believe we would have seen other reports of that by now.

Does SLIMIT behave as expected?

**Comment by esecules** [comment]
I do have a unique ID as part of the tags so that explains the symptoms I've been seeing, and SLIMIT N does return a N rows in this case. However to my knowledge there is still no data independent way of ensuring that the output of a query is bounded. I will work around it by paging over time intervals rather than a fixed number of rows.

**Comment by beckettsean** [comment]
Yes, if you are writing a unique value to a tag, then you have a series for every value of that tag, and every series has a unique index ID stored in RAM. That's a huge index, and may explain the very long startup time, as the shards have to build an in-RAM structure for the index on boot.

If a tag has a unique value it really should be a field. Querying using fields in the WHERE clause is slower, but the database will scale properly. Unique tag values will not scale.

**Comment by esecules** [comment]
The schema change is going to get locked in soon and hopefully I will see improvements as the retention policies clean out the old data.
