### ISSUE TITLE
Influx 0.9.2 Panics

### ISSUE THREAD

**Issue by mnietz** [influxdb/influxdb#3499]
Influx 0.9.2 has stopped working with the above error. I'm not able to restart it.

Prior of the crash i created a obviously wrong cq for testing:

create continuous query "justatest" on analytics begin select mean(value) as value, sid, uid into "test" from view where name = 'account' group by time(5m), * end

How can fix the situation, this instance of influx is used in production to gather statistics

panic: runtime error: index out of range

goroutine 28 [running]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).convertRowToPoints(0xc2080102a0, 0xc208144a3c, 0x4, 0xc20814aea0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:350 +0x6ec
github.com/influxdb/influxdb/services/continuous_querier.(*Service).runContinuousQueryAndWriteResult(0xc2080102a0, 0xc2080f5100, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:288 +0x2f4
github.com/influxdb/influxdb/services/continuous_querier.(*Service).ExecuteContinuousQuery(0xc2080102a0, 0xc20816e550, 0xc2080fd6a0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:238 +0x69f
github.com/influxdb/influxdb/services/continuous_querier.(*Service).runContinuousQueries(0xc2080102a0)
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:179 +0x32a
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc2080102a0)
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:161 +0x2e2
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed

goroutine 1 [chan receive]:
main.(*Main).Run(0xc20808fa80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x73b
main.main()
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc208010370, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010370, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010310, 0x0, 0x7f09b9353cc8, 0xc2080f8000)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803aa08, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803aa08, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080b9950, 0x7f09b9356388, 0xc20803aa08, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:298 +0x7a8

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803aa10, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080b9980, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/meta/store.go:1855 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc2080103f0)
        /root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
        /root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080b61c0)
        /root/go/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080b61c0)
        /root/go/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080b61c0)
        /root/go/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
        /root/go/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
        /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080b61c0)
        /root/go/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
        /root/go/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
        /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080b61c0)
        /root/go/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
        /root/go/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
        /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
        /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 14 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803aa18, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc20800c140)
        /root/go/src/github.com/influxdb/influxdb/meta/store.go:470 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /root/go/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2

goroutine 15 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080aa0e0, 0xc208046420)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:421 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:304 +0x919

goroutine 16 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc2080320b0, 0xc208047a40)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 18 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc208032000, 0xc208046de0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 19 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc208032210, 0xc2080474a0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 20 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc208032160, 0xc208047b60)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 21 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc2080322c0, 0xc208047ec0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 22 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc208032420, 0xc20814a1e0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 23 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc20804d220)
        /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef

goroutine 24 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc20804d220)
        /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109

goroutine 25 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803aa20, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc208010230)
        /root/go/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
created by github.com/influxdb/influxdb/cluster.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67

goroutine 26 [select]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc20800adc0)
        /root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb

goroutine 27 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803aa28, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc20800aeb0)
        /root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62

goroutine 29 [IO wait]:
net.(*pollDesc).Wait(0xc208011090, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011090, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011030, 0x0, 0x7f09b9353cc8, 0xc2080d0000)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803a1f8, 0xc208021c00, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803a1f8, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208160240, 0x7f09b9356388, 0xc20803a1f8, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f09b9356388, 0xc20803a1f8, 0x7f09b9359dd0, 0xc2080aca00, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20800aff0)
        /root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:107 +0x79
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:75 +0x590

goroutine 30 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc208046900)
        /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67

goroutine 31 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208046900)
        /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81

goroutine 32 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc2080aa0e0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x18e
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:327 +0xdbe

goroutine 33 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc208011b90)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:125 +0x2da
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:107 +0xbb4

goroutine 34 [select]:
net/http.(*Transport).getConn(0xc20809a000, 0xc2081a9a00, 0x0, 0xbe53d0, 0x4, 0xbe53d7, 0x13, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:525 +0x608
net/http.(*Transport).RoundTrip(0xc20809a000, 0xc2081a9a00, 0xc20819b1d0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:228 +0x4d4
net/http.send(0xc2081a9a00, 0x7f09b9354100, 0xc20809a000, 0x44, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:219 +0x4fc
net/http.(*Client).send(0xc20817ee40, 0xc2081a9a00, 0x44, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:142 +0x15b
net/http.(*Client).doFollowingRedirects(0xc20817ee40, 0xc2081a9a00, 0xc30db0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:367 +0xb25
net/http.(*Client).Post(0xc20817ee40, 0xbe53d0, 0x44, 0xb3c150, 0x10, 0x7f09b93576a0, 0xc208153420, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/client.go:441 +0x10d
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).reportServer
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:415 +0x95d

goroutine 35 [IO wait]:
net.(*pollDesc).Wait(0xc2081535d0, 0x77, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitWrite(0xc2081535d0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:93 +0x43
net.(*netFD).connect(0xc208153570, 0x0, 0x0, 0x7f09b935b298, 0xc208164720, 0xecd4ac87f, 0x309116b, 0xec5400, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:114 +0x24b
net.(*netFD).dial(0xc208153570, 0x7f09b93563c0, 0x0, 0x7f09b93563c0, 0xc20817ef60, 0xecd4ac87f, 0x309116b, 0xec5400, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/sock_posix.go:139 +0x37a
net.socket(0xaf0870, 0x3, 0x2, 0x1, 0x0, 0xc20817ef00, 0x7f09b93563c0, 0x0, 0x7f09b93563c0, 0xc20817ef60, ...)
        /root/.gvm/gos/go1.4.2/src/net/sock_posix.go:91 +0x422
net.internetSocket(0xaf0870, 0x3, 0x7f09b93563c0, 0x0, 0x7f09b93563c0, 0xc20817ef60, 0xecd4ac87f, 0x309116b, 0xec5400, 0x1, ...)
        /root/.gvm/gos/go1.4.2/src/net/ipsock_posix.go:137 +0x148
net.dialTCP(0xaf0870, 0x3, 0x0, 0xc20817ef60, 0xecd4ac87f, 0x309116b, 0xec5400, 0xc2080f1770, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:156 +0x125
net.dialSingle(0xaf0870, 0x3, 0xbe53d7, 0x13, 0x0, 0x0, 0x7f09b9356358, 0xc20817ef60, 0xecd4ac87f, 0x60309116b, ...)
        /root/.gvm/gos/go1.4.2/src/net/dial.go:235 +0x3f5
net.func·016(0xecd4ac87f, 0xe0309116b, 0xec5400, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/dial.go:163 +0x12c
net.dial(0xaf0870, 0x3, 0x7f09b9356358, 0xc20817ef60, 0xc2080a1b08, 0xecd4ac87f, 0xe0309116b, 0xec5400, 0x0, 0x0, ...)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:40 +0x6f
net.(*Dialer).Dial(0xc20808e140, 0xaf0870, 0x3, 0xbe53d7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/dial.go:170 +0x4be
net.*Dialer.Dial·fm(0xaf0870, 0x3, 0xbe53d7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:38 +0x79
net/http.(*Transport).dial(0xc20809a000, 0xaf0870, 0x3, 0xbe53d7, 0x13, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:479 +0x84
net/http.(*Transport).dialConn(0xc20809a000, 0x0, 0xbe53d0, 0x4, 0xbe53d7, 0x13, 0xc20817ee40, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:564 +0x1678
net/http.func·019()
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:520 +0x42
created by net/http.(*Transport).getConn
        /root/.gvm/gos/go1.4.2/src/net/http/transport.go:522 +0x335

**Comment by mnietz** [comment]
Solved this by restarting influx with continuous queries disabled, deleted the cq, enabled cq's again and restarted once again

**Comment by beckettsean** [comment]
@mnietz that is the correct resolution. CQs calculate on startup, so if there's a broken one you must first disable them, then restart the server to delete the CQ, then re-enable them and bounce the service once more.

**Comment by beckettsean** [comment]
probable dupe of https://github.com/influxdb/influxdb/issues/3284 or https://github.com/influxdb/influxdb/issues/3459
