### ISSUE TITLE
InfluxDB 0.9.2 Query Template syntax error

### ISSUE THREAD

**Issue by srfraser** [influxdb/influxdb#3500]
Using the dropdown 'Query Templates':

Selecting "Show Retention Policies", the template provided misses out the word "ON", filling in "SHOW RETENTION POLICIES db_name" instead of "SHOW RETENTION POLICIES ON db_name"

Selecting "Drop Retention Policy", the template provided misses "ON db_name" from the end:
"error parsing query: found EOF, expected ON at line 1, char 31"

**Comment by beckettsean** [comment]
Thanks for the report, @srfraser. Looks like we missed one spot affected by https://github.com/influxdb/influxdb/pull/3345

**Comment by gunnaraasen** [comment]
This was actually fixed by https://github.com/influxdb/influxdb/pull/3438, but the admin UI assets were not precompiled for statik. PR https://github.com/influxdb/influxdb/pull/3587 compiles this fix into statik.
