### ISSUE TITLE
[0.9.3 nightly] Graphite plugin: "assignment to entry in nil map" on shutdown

### ISSUE THREAD

**Issue by glarizza** [influxdb/influxdb#3506]
Server Setup:

```
[root@ip-10-12-111-57 influxdb]# /opt/puppet/bin/facter os
{"name"=>"RedHat", "family"=>"RedHat", "release"=>{"major"=>"6", "minor"=>"6", "full"=>"6.6"}}

[root@ip-10-12-111-57 influxdb]# /opt/influxdb/influx -version
InfluxDB shell 0.9.1-rc1-326-g2a02605
```

I've got about 6 Puppet compilation masters running Puppetserver which have a metrics service sending out graphite data every 5 minutes.  There are quite a few measurements per-server (as measurements get created on a per-resource basis), and so a lot of data getting streamed to the InfluxDB server.  I'm using the graphite plugin for InfluxDB and was originally using 0.9.2 before I switched to nightly to see if anything recent helped with this issue.  

The reproducible use-case is to first load up the config in this gist --> https://gist.github.com/glarizza/a244124079110bf8ec6b

I've tuned WAL for performance according to a couple of the previous bugs.  I can start the service and get an initial query to work fine (I get a single dataset for all measurements), but nothing after.  In the logs, I can see the queries and can see data flushing, but nothing can be queried.  When I restart the service, I get the panic in the gist that sites "assignment to entry in nil map".  I have a feeling it's possibly something in the data that Puppetserver is sending.

When I restart the service, it hangs and doesn't initially start the admin/http/graphite services (but they do get started after some indeterminate period of time).  ONce they start, I get a datapoint and that's it.  If I kill the meta and data directories, all services start, but I get the same thing (initial datapoint, then that's it).

Where can I start to debug this?

**Comment by glarizza** [comment]
After more digging and restricting the number of hosts sending to InfluxDB, I found some errors arising:

```
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-catalog-/*/-percentage NaN 143820236
4'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-facts-/*/-percentage NaN 1438202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-facts_search-/*/-percentage NaN 1438
202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-file_bucket_file-/*/-percentage NaN
1438202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-file_content-/*/-percentage NaN 1438
202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-file_metadata-/*/-percentage NaN 143
8202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-file_metadatas-/*/-percentage NaN 14
38202364'
[graphite] 2015/07/29 20:39:24 dropping unsupported value: 'puppetlabs.ip-10-12-111-62.http.:environment-node-/*/-percentage NaN 1438202364'
```

Looks like there are points being sent that influx does not like.  I started to use the filters/templates to the Graphite plugin, is there a way to have Influx ignore points that match a certain regex?  I know there's way to define tags and measurements from a single point being sent, but can you wholesale filter certain datapoints?

**Comment by glarizza** [comment]
Seems to be the load - if I turn off metrics to all but a single server, Influx is able to keep up.  I'll play with it some more to find out where it starts having problems (and tune the timeouts and WAL a bit).  Are there any other performance suggestions that could be made?

**Comment by beckettsean** [comment]
@glarizza If you've tuned the WAL that's a great first step. Did you experiment the `batch-size` and `batch-timeout` settings on the graphite endpoint? If you didn't generate a new config when upgrading that's probably the first thing to try. Batching will help with performance for sure.

Also see the comments on this issue: https://github.com/influxdb/influxdb/issues/3230. They specifically address `NaN` errors with the graphite endpoint. Sounds like the issue was resolved in a PR that was in 0.9.2. 

Your CLI output strongly implies that you are running an older version, 0.9.1-RC1. Can you upgrade to 0.9.2 and see if it fixes things?

**Comment by glarizza** [comment]
Hey Sean - This is the nightly from last night, it was installed completely fresh this morning.  When I start up InfluxDB, the git commit lines up with the merge from last night, but the version string is still giving 0.9.1-RC1, which is weird but happens.

I've got `batch-size` at `250` and `batch-timeout` at `20ms`, but I'm unsure if increasing the size and timeout will work around the errors and be better for the system, or ultimately just conceal a problem?  What's the direct effect of those settings?

The `NaN` error in the long was the first time I've seen that - and it only happened when I stopped shipping datapoints from 5 of the 6 nodes.  I suspect the structure of some of the measurements might causing fits (specifically when I'm seeing values like '`'puppetlabs.ip-10-12-111-62.http.:environment-node-/*/-percentage NaN 1438202364'`' popping up).  I would suspect the incredibly large amounts of measurements coming from every server is probably choking InfluxDB, and I'm trying to decide if it's easier to break into Puppetserver and see if I can restrict WHAT'S sent or if I can template through the graphite section to try and filter out a majority that I don't care about.

At any rate, this is definitely reproducible, but it's because I have about 1500 nodes hitting a pool of 6 Puppet masters at a rate of twice an hour, and there are datapoints being sent every five SECONDS (not minutes, as I said above) from each master.  

With a single master, the service stays up, and I can restart it without a panic, BUT it takes several minutes before InfluxDB starts the http/admin/graphite services and listens on the appropriate ports.  I don't know what it's doing during that time, but CPU utilization increases for the process.  This shows up in other issues, however, and I suspect I'm seeing what they're seeing.

**Comment by beckettsean** [comment]
@glarizza thanks for the note about the version string. I've opened an issue to look at our nightly build script. I'm guessing we've got a hard-coded value somewhere in there. https://github.com/influxdb/influxdb/issues/3512

**Comment by toddboom** [comment]
@glarizza can you give it a try again? i think the nightly build may have been slightly out of date. :crying_cat_face:

i just pushed a new build from master a bit ago.

**Comment by glarizza** [comment]
Sadly, I had to pull the server because of I/O issues.  This is for a customer I'm working with, but I've captured the data so I can replicate.  As of right now I'm not going to be able to replicate it for awhile, so feel free to close this issue for now (unless someone else wants to comment).

**Comment by beckettsean** [comment]
No new comments so I'll close this for now. Thanks for the report, @glarizza and do let us know if it shows up with any of the newer builds.
