### ISSUE TITLE
[0.9.3-nightly] Logfile is growing too big

### ISSUE THREAD

**Issue by markusr** [influxdb/influxdb#3510]
With the recent change of logging every write in a continuous query, I get a lot of entries like this: 
```
[continuous_querier] 2015/07/29 12:20:15 wrote 1 point(s) to archive.policy_forever.15min_averages
```
So every 15 mins I have thousands of entries.

In the last 3 days the log file got as big as 350 MByte. For now I just deleted the file.

```
version 0.9.1-rc1-310-gf994a97
```

**Comment by beckettsean** [comment]
See https://github.com/influxdb/influxdb/issues/1943 for how to install a reasonable logrotate config for InfluxDB.

Closing in favor of that issue.

**Comment by beckettsean** [comment]
Note also that you can disable CQ logging in the config file:

```
[continuous_queries]
 log-enabled = false
...
```
