### ISSUE TITLE
Move WAL out of BoltDB

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3514]
Having the WAL in BoltDB is causing the entire database to lock during WAL flushes, which is causing write timeouts. Move the WAL outside of Bolt and ensure that flushes of the WAL do not cause the database to lock for writes.

WAL should be able to flush incrementally. It should gradually put on back pressure if the index is unable to keep up with the pace of WAL flushing. Ideally this should occur over time rather than as a large timeout.

**Comment by jmcook** [comment]
This would be wonderful.

**Comment by maxboiko** [comment]
Seems that the same issue is very important in my case, hope fix will be provided soon.

**Comment by syepes** [comment]
Waiting for this one also ;-)

**Comment by kenzodeluxe** [comment]
While you guys are waiting for this, I am *urgently* waiting for it :)

**Comment by srikara** [comment]
+1

**Comment by redHL** [comment]
+1

**Comment by redHL** [comment]
+1

**Comment by indrekj** [comment]
+1

**Comment by pauldix** [comment]
Done in #3569 and on 0.9.3-rc1, which I'm cutting right now. Testing and performance results are greatly appreciated!
