### ISSUE TITLE
Should we remove UUID from the project?

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3515]
I see we're using UUID to set a request id, but that doesn't seem to get used anywhere. Wondering if we should remove this as it seems like extra cruft.

**Comment by corylanou** [comment]
Do you have an alternative ID you would like to use?  This request ID will be important once we wire it up to go through our entire system.

The theory is that whenever we initiate a request, this ID follows it through all system calls, and would log out with any errors/warnings.  Then, you can consolidate your logs across the distributed system and see how that request was actually processed.

We don't have that functionality today, but likely need it at some point for troubleshooting/debugging of the distributed system.  Unless we have plans to do it some other way.

**Comment by otoolep** [comment]
I agree with @corylanou, what he suggests could be very useful.

**Comment by beckettsean** [comment]
@pauldix I'm gonna close this since you've been outvoted :smile:
