### ISSUE TITLE
Retention policy not being enforced

### ISSUE THREAD

**Issue by btobolaski** [influxdb/influxdb#3518]
OS: Ubuntu 14.04
Influxdb Version: 0.9.3 nightly build, the deb version is 0.9.1-rc1-326-g2a02605

```
InfluxDB shell 0.9.1-rc1-326-g2a02605
> SHOW RETENTION POLICIES ON metrics
name			duration	replicaN	default
default			24h0m0s		1		true
one_minute_rollup	744h0m0s	1		false
five_minute_rollup	2232h0m0s	1		false
fifteen_minute_rollup	8760h0m0s	1		false
thirty_minute_rollup	26280h0m0s	1		false
sixty_minute_rollup	0		1		false
```

But if I query the default retention policy, I see data from much longer ago than that

```
> SELECT mean(value) FROM "metrics"."default"."cpu" WHERE time > NOW() - 168h GROUP BY time(24h)
name: cpu
---------
time			mean
2015-07-23T00:00:00Z
2015-07-24T00:00:00Z
2015-07-25T00:00:00Z
2015-07-26T00:00:00Z
2015-07-27T00:00:00Z	0.029077113837690904
2015-07-28T00:00:00Z	0.03637480649205551
2015-07-29T00:00:00Z	0.03695373716541052
2015-07-30T00:00:00Z	0.03440392710221358
```

This is a relatively new server, I only started writing data to it 4 days ago which is why the first 4 entries are blank. I do see entries like:

```
[retention] 2015/07/30 14:21:01 retention policy enforcement check commencing
[retention] 2015/07/30 14:21:01 retention policy shard deletion check commencing
```

But they never result in dropping a shard. Could this be happening because I modified the default retention policy from infinite retention? Is there something that I can do to make the retention policy be enforced? Perhaps dropping it and recreating it?

**Comment by beckettsean** [comment]
@btobolaski we recently discovered that our nightly builds weren't successfully building form the latest master. That version string in your first comment is not a mistake, unfortunately, you were actually testing with an 0.9.1 rc1 build. 

Can you try upgrading to the latest 0.9.3 nightly build and see if the issue persists?

**Comment by btobolaski** [comment]
Indeed upgrading fixed it.
