### ISSUE TITLE
Database file grew too fast

### ISSUE THREAD

**Issue by caoli5288** [influxdb/influxdb#3527]
Hey guys, I am a new for influxdb. 
I used RRD to record collectd's data beforce and now use influxdb-0.9.2 instead of.
But a found something that I got a 1G database file in a day. 
When using RRD the database file is tiny.
So I will get a 365G file in a year? I don't have so many hard drives for collectd and I think it's not normal for this growth data.

**Comment by mjdesa** [comment]
@caoli5288 about how many points did you write for that day?

**Comment by caoli5288** [comment]
@mjdesa "select count()" statement is not supported, So how can I query the number of points?

**Comment by mjdesa** [comment]
@caoli5288 the query `select count(value) from /.*/` doesn't work?

**Comment by caoli5288** [comment]
@mjdesa It seem works, but it lag (still now, I cant get result) :-(
collectd read host's hardware information every 10s.

**Comment by caoli5288** [comment]
@mjdesa Result show count for each tags, I don't know the total's.

**Comment by mjdesa** [comment]
@caoli5288 any idea approximately?

**Comment by caoli5288** [comment]
@mjdesa The number looks exceptions, but why did I never pay attention to the size of the database when it was used to store data in RRD? I'm sorry I don't know enough about RRD and your project.

**Comment by mjdesa** [comment]
Not totally sure.

**Comment by beckettsean** [comment]
@caoli5288 we are working on data compression as part of the 0.9.3 release. To date we have focused on write speed over size on disk, so I would expect that InfluxDB 0.9.2 is much less efficient than RRD. 25 million points isn't very many, but at 1 GB for 25 million points that's 40-45 bytes per point. 

What values are you storing? Strings, floats, how many?

**Comment by caoli5288** [comment]
@beckettsean pure int value. store by collectd-plugin which build-in influxdb.

**Comment by caoli5288** [comment]
@beckettsean I try to gzip database file and get a 1/10 size file. look forward to 0.9.3 :)
