### ISSUE TITLE
[0.9.3-rc1] memory use and lack of responsiveness

### ISSUE THREAD

**Issue by srfraser** [influxdb/influxdb#3528]
Overview: 

1. Each time I restart, I have to remove the data directory or InfluxDB doesn't open the ports 8083 and 8086
2. There is a fast growth in resident memory usage. 

Using 0.9.2, installed from influxdb_0.9.2_amd64.deb on Ubuntu 12.04, kernel 3.2.0-35-generic
The server has 128Gb memory and 40 cores, and about 70Tb spinning disk.

I've experimented with 0.9.2 for a little while with low volumes. Yesterday  I started from scratch to test telegraf. I started with a clean database area, and I installed telegraf on one of our clusters of 321 nodes.

Overnight, influxdb was killed by oom-killer. When restarting it wasn't opening ports 8083 or 8086, just port 8088. I had to clear out the data/ directory to get it to restart. Set up the database and user again, and data starts coming in. 

That was four hours ago, and InfluxDB is now using 38Gb resident memory and growing rapidly.  iostat/iotop report trivial amounts of disk usage. The admin interface on port 8083 was loading but not responding to any queries. The command line tool could be used to run queries without any noticeable delay.

Telegraf is submitting at the default 10s interval, except for 'disk', which has given interval="5m". From /var/log/influxdb/influxdb.log it looks like 20-42 POSTS are coming in each second. 

I've just set up telegraf on that node to point to a different influxdb instance, so I should be able to get graphs of this behaviour relatively soon.

Cardinality for each measurement seems low enough, according to the documentation:
   9832 cpu_guest
   9832 cpu_guestNice
   9832 cpu_idle
   9832 cpu_iowait
   9832 cpu_irq
   9832 cpu_nice
   9832 cpu_softirq
   9832 cpu_steal
   9832 cpu_stolen
   9832 cpu_system
   9832 cpu_user
  17319 disk_free
  17319 disk_inodes_free
  17319 disk_inodes_total
  17319 disk_inodes_used
  17319 disk_total
  17319 disk_used
   2301 io_io_time
   2301 io_read_bytes
   2301 io_read_time
   2301 io_reads
   2301 io_write_bytes
   2301 io_write_time
   2301 io_writes
    322 mem_active
    322 mem_available
    322 mem_buffers
    322 mem_cached
    322 mem_free
    322 mem_inactive
    322 mem_shared
    322 mem_total
    322 mem_used
    322 mem_used_prec
    322 mem_wired
    391 net_bytes_recv
    391 net_bytes_sent
    391 net_drop_in
    391 net_drop_out
    391 net_err_in
    391 net_err_out
    391 net_packets_recv
    391 net_packets_sent
    322 swap_free
    322 swap_in
    322 swap_out
    322 swap_total
    322 swap_used
    322 swap_used_perc
    322 system_load1
    322 system_load15
    322 system_load5

I think that the issue with it failing to restart is related to the log entries when it shuts down: 
https://gist.github.com/srfraser/01d479bfd7890bb05435

Any advice available, gratefully received.

**Comment by pauldix** [comment]
Are there queries also hitting the box or just Telegraf? What sampling interval do you have on your telegraf config?

It sounds from this like you have telegraf installed on all 321 nodes? That means you have 321 different writers (which should be fine), just want to verify if there are any more.

**Comment by srfraser** [comment]
The only queries are from one grafana dashboard, it's not a live service yet so no one else is looking at it.

The sampling interval is the default 10s, and telegraf is installed on all the 321 nodes 

Thanks!

**Comment by DanielMorsing** [comment]
Some profiles out of the system would be really helpful in tracking this down. To get a cpu profile and a memory profile run
```
go tool pprof -proto -output /tmp/memprofile http://serverhostname:8086/debug/pprof/heap
go tool pprof -proto -output /tmp/cpuprofile http://serverhostname:8086/debug/pprof/profile
```
If you send me the `/tmp/cpuprofile` and `/tmp/memprofile` files, I'll have a look

**Comment by srfraser** [comment]
Will do, am out for the evening will post results in a few hours

**Comment by srfraser** [comment]
Sent the binary files, but the text versions for the issue record are:

33820.65MB of 34187.70MB total (98.93%)
Dropped 252 nodes (cum <= 170.94MB)
      flat  flat%   sum%        cum   cum%
15427.88MB 45.13% 45.13% 15427.88MB 45.13%  github.com/influxdb/influxdb/tsdb.parsePoint
 9411.92MB 27.53% 72.66%  9411.92MB 27.53%  bytes.makeSlice
 4693.31MB 13.73% 86.39%  4693.31MB 13.73%  github.com/influxdb/influxdb/tsdb.func·012
 2366.99MB  6.92% 93.31%  2366.99MB  6.92%  github.com/influxdb/influxdb/cluster.(*ShardMapping).MapPoint
 1300.52MB  3.80% 97.11%  1300.52MB  3.80%  github.com/influxdb/influxdb/tsdb.(*FieldCodec).EncodeFields
  613.01MB  1.79% 98.91%   613.01MB  1.79%  github.com/influxdb/influxdb/tsdb.newFieldsFromBinary
    5.50MB 0.016% 98.92%  2372.50MB  6.94%  github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints
    1.51MB 0.0044% 98.93% 15429.39MB 45.13%  github.com/influxdb/influxdb/tsdb.ParsePointsWithPrecision
         0     0% 98.93%  9411.92MB 27.53%  bytes.(*Buffer).ReadFrom
         0     0% 98.93% 27213.81MB 79.60%  github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP
         0     0% 98.93%  2366.99MB  6.92%  github.com/influxdb/influxdb/cluster.(*PointsWriter).MapShards
         0     0% 98.93%  6780.55MB 19.83%  github.com/influxdb/influxdb/cluster.func·002
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.(*Handler).serveWrite
         0     0% 98.93% 17801.89MB 52.07%  github.com/influxdb/influxdb/services/httpd.(*Handler).serveWriteLine
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveWrite)·fm
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·001
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·002
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·003
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·004
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·005
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·006
         0     0% 98.93% 27213.81MB 79.60%  github.com/influxdb/influxdb/services/httpd.func·007
         0     0% 98.93%  6780.55MB 19.83%  github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints
         0     0% 98.93%  6780.55MB 19.83%  github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard
         0     0% 98.93%   613.01MB  1.79%  github.com/influxdb/influxdb/tsdb.(*point).Fields
         0     0% 98.93%   613.01MB  1.79%  github.com/influxdb/influxdb/tsdb.(*point).unmarshalBinary
         0     0% 98.93%  9411.92MB 27.53%  io/ioutil.ReadAll
         0     0% 98.93%  9411.92MB 27.53%  io/ioutil.readAll
         0     0% 98.93% 27231.81MB 79.65%  net/http.(*conn).serve
         0     0% 98.93% 27213.81MB 79.60%  net/http.HandlerFunc.ServeHTTP
         0     0% 98.93% 27213.81MB 79.60%  net/http.serverHandler.ServeHTTP
         0     0% 98.93% 34080.89MB 99.69%  runtime.goexit

35.41s of 37.67s total (94.00%)
Dropped 163 nodes (cum <= 0.19s)
      flat  flat%   sum%        cum   cum%
    15.95s 42.34% 42.34%     15.95s 42.34%  runtime.cmpbody
     8.77s 23.28% 65.62%     26.43s 70.16%  github.com/influxdb/influxdb/tsdb.byteSlices.Less
     3.60s  9.56% 75.18%     30.03s 79.72%  github.com/influxdb/influxdb/tsdb.(*byteSlices).Less
     1.58s  4.19% 79.37%     30.55s 81.10%  sort.doPivot
     1.41s  3.74% 83.12%     17.36s 46.08%  runtime.cmpbytes
     0.70s  1.86% 84.97%      1.13s  3.00%  github.com/influxdb/influxdb/tsdb.(*byteSlices).Swap
     0.50s  1.33% 86.30%      0.55s  1.46%  runtime.mallocgc
     0.49s  1.30% 87.60%      0.49s  1.30%  runtime.writebarrierslice
     0.47s  1.25% 88.85%      0.47s  1.25%  bytes.Compare
     0.32s  0.85% 89.70%      0.32s  0.85%  syscall.Syscall
     0.27s  0.72% 90.42%      0.60s  1.59%  runtime.growslice
     0.23s  0.61% 91.03%      2.74s  7.27%  sort.insertionSort
     0.21s  0.56% 91.58%     33.50s 88.93%  sort.quickSort
     0.19s   0.5% 92.09%      3.35s  8.89%  sort.medianOfThree
     0.13s  0.35% 92.43%      0.20s  0.53%  runtime.mapiternext
     0.10s  0.27% 92.70%      0.47s  1.25%  sort.swapRange
     0.09s  0.24% 92.94%      0.20s  0.53%  github.com/boltdb/bolt.func·006
     0.09s  0.24% 93.18%      0.19s   0.5%  runtime.mapassign1
     0.06s  0.16% 93.34%      0.33s  0.88%  sort.Search
     0.05s  0.13% 93.47%      0.59s  1.57%  bytes.Replace
     0.05s  0.13% 93.60%     33.83s 89.81%  github.com/influxdb/influxdb/tsdb.func·012
     0.04s  0.11% 93.71%      0.30s   0.8%  runtime.newarray
     0.03s  0.08% 93.79%      0.52s  1.38%  github.com/boltdb/bolt.(*Cursor).search
     0.02s 0.053% 93.84%      0.77s  2.04%  github.com/influxdb/influxdb/tsdb.unescape
     0.01s 0.027% 93.87%      0.70s  1.86%  github.com/boltdb/bolt.(*Bucket).Put
     0.01s 0.027% 93.89%      0.53s  1.41%  github.com/boltdb/bolt.(*Cursor).seek
     0.01s 0.027% 93.92%      0.85s  2.26%  github.com/influxdb/influxdb/tsdb.(*Shard).validateSeriesAndFields
     0.01s 0.027% 93.95%      0.44s  1.17%  github.com/influxdb/influxdb/tsdb.(*point).Name
     0.01s 0.027% 93.97%      0.65s  1.73%  github.com/influxdb/influxdb/tsdb.newFieldsFromBinary
     0.01s 0.027% 94.00%     33.51s 88.96%  sort.Sort
         0     0% 94.00%      0.52s  1.38%  System
         0     0% 94.00%      0.21s  0.56%  github.com/boltdb/bolt.(*Bucket).spill
         0     0% 94.00%      0.45s  1.19%  github.com/boltdb/bolt.(*Cursor).searchNode
         0     0% 94.00%      1.81s  4.80%  github.com/boltdb/bolt.(*DB).Update
         0     0% 94.00%      0.78s  2.07%  github.com/boltdb/bolt.(*Tx).Commit
         0     0% 94.00%      0.49s  1.30%  github.com/boltdb/bolt.(*Tx).write
         0     0% 94.00%      0.20s  0.53%  github.com/boltdb/bolt.(*node).spill
         0     0% 94.00%      0.32s  0.85%  github.com/boltdb/bolt.fdatasync
         0     0% 94.00%        37s 98.22%  github.com/influxdb/influxdb/cluster.func·002
         0     0% 94.00%        37s 98.22%  github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints
         0     0% 94.00%        37s 98.22%  github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard
         0     0% 94.00%      0.65s  1.73%  github.com/influxdb/influxdb/tsdb.(*point).Fields
         0     0% 94.00%      0.65s  1.73%  github.com/influxdb/influxdb/tsdb.(*point).unmarshalBinary
         0     0% 94.00%      1.02s  2.71%  github.com/influxdb/influxdb/tsdb.func·011
         0     0% 94.00%     37.15s 98.62%  runtime.goexit
         0     0% 94.00%      0.32s  0.85%  syscall.Fdatasync

**Comment by srfraser** [comment]
Not sure if this is useful, but it covers the life of the previous instance of the process: 

![influxdbmemorystats](https://cloud.githubusercontent.com/assets/5933384/9024254/d6f78d5e-38bc-11e5-8d3a-183c05baa05c.png)

**Comment by srfraser** [comment]
There appears to be a correlation between the size of the BoltDB file and the amount of process memory used:

![influxdb_process_vs_dbsize](https://cloud.githubusercontent.com/assets/5933384/9025932/f7be9438-3911-11e5-9e8f-1d954bf2e922.png)

It may be that a workaround is to group nodes running telegraf into different logical groups with their own databases so they get different files, although that would be an admin overhead that's not desirable longer-term.

It seems like a lot of disk space for the amount of data, too - is that expected?

**Comment by pauldix** [comment]
We're working on compression for the next release. Also working on changing up how the WAL works to reduce IOPS and make it so that flushing the WAL doesn't lock the DB up.

**Comment by srfraser** [comment]
Thanks @pauldix - is that what's happening here? The database is being locked up while flushing the WAL? 

If the process's memory usage closely matches the size of the database on disk, what sort of changes can be made to ensure a reasonable memory usage? I don't really want a retention period of a few hours

**Comment by DanielMorsing** [comment]
I had a look at the profiles. They match up with the file system not being accessible. Work queues up waiting for the file system and eventually, the memory limit is hit and the process runs into the OOM-killer. How is the file system mounted? NFS?

As for memory use, `influxd` uses a file store that uses mmap. Files mapped into process memory gets marked as in-use by the linux kernel even though they are reclaimable. The `MemAvailable` field in `/proc/meminfo` should still show a substantial amount of memory available.

How are you measuring per-process memory use? If it's via virtual memory size, then the mmaped pages from the database would show up in those numbers as well. If it's resident set size, that indicates that there's a bug somewhere.

**Comment by srfraser** [comment]
The disks are internal, RAID6 through a hardware raid controller and presented as /dev/sdb and /dev/sdc, which are both used in an LVM volume. It's mounted locally. There's nothing in the system logs about unavailable storage.

The memory use in the graph above is from /proc/<influxpid>/status, the line VmRSS, so the resident set size, not virtual. 

If the file being mmap'd gets bigger and bigger, won't that affect the resident memory? Or is the file meant to be rotated? I admit I don't know a lot about how mmap works.

**Comment by srfraser** [comment]
I'm trying to see if the same issue occurs with 0.9.3 nightly builds, and so far struggling. I'm using telegraf built from nightly to cover the integer format changes, rather than 0.1.4.

After a short while influxd stops logging 204 responses and starts logging 500s. Memory usage appears to follow the same pattern as before - endlessly growing.

**Comment by pauldix** [comment]
@srfraser wait for #3569 to get merged in and you should see a difference.

**Comment by srfraser** [comment]
Trying 0.9.3-rc1 and telegraf 0.1.5 now. I initially thought things were a lot better, as influxdb successfully survived overnight with a good memory profile. I realised that a new config option to telegraf meant I wasn't collection memory usage stats, so I added that and now the same symptoms are appearing: upswing in resident memory use, and now influxdb.log is reporting that posts are taking slightly over 5 seconds (where before they were 10-20ms, they now appear to be 5s + 10-20ms)

I'm not sure if it's the volume of points, or something specific to do with the cpu usage stats. Tempted to try collecting only those, and see if the symptoms persist.

**Comment by srfraser** [comment]
I'm not sure it's entirely a performance issue, looking at the label, since the process doesn't survive over 13 hours, and I have to erase the database before it'll restart.

**Comment by pauldix** [comment]
Did you start with a fresh database? If not, then you're still using the
same engine as before.

**Comment by srfraser** [comment]
I removed everything under /var/opt/influxdb/data/, was that enough?

**Comment by pauldix** [comment]
@srfraser if that's the data directory that's being used. What do the startup logs say? If you start Influx from the command line without specifying a config to use, it'll use `~/.influxdb` by default for all directories. Is it possible for you to rerun the test and get us another profile?

Thanks again for helping us work through this.

**Comment by srfraser** [comment]
/var/opt/influxdb/data is the default location provided by the .deb, I've not changed it.

I reset everything again to start with jhorwit2's load tester, so it's not currently reporting any 500s or other problems (the test has only been going for ten minutes). I'll start up telegraf again and run the profiles once it's having issues.

**Comment by srfraser** [comment]
gzipped files available, @pauldix 
http://www.flummox.org/memprofile
http://www.flummox.org/cpuprofile

**Comment by srfraser** [comment]
Looks like the memory use is now more stable, however this may be because most of the requests are getting a 500:

![influxdb_memory](https://cloud.githubusercontent.com/assets/5933384/9406268/dafd2172-47f6-11e5-8166-69b206c3f20c.png)

**Comment by srfraser** [comment]
Memory use after the weekend.  Am going to try turning off per-cpu metrics in telegraf to see what the characteristics are, there, since they account for 2/3 of the points coming in. 

![influxdb_memory2](https://cloud.githubusercontent.com/assets/5933384/9436163/388df032-4a45-11e5-921b-4156b806509b.png)

**Comment by srfraser** [comment]
I've turned off per-cpu metrics in telegraf, cutting the number of points coming in by about two-thirds (from 300k to 100k). It appears to be showing the same pattern in memory use increase, just over a much longer period of time. The shape of the graph is the same, so far, although it hasn't started giving 500s yet.

![influxdb_memory3](https://cloud.githubusercontent.com/assets/5933384/9489167/f18f3734-4bd6-11e5-8717-e5c954268d94.png)

**Comment by pauldix** [comment]
Is it possible that you're just seeing the memory reported by the mmap'd file? We use BoltDB under the hood, see: https://github.com/boltdb/bolt#caveats--limitations for more about the memory thing.

**Comment by srfraser** [comment]
It's running the server out of memory and getting killed by oom-killer. It's entirely possible that if I left the current setup for a while it wouldn't do that, but the initial behaviour is still occurring. I think I will dig into the code.

**Comment by marcogallotta** [comment]
We are also experiencing very similar symptoms on 0.9.3, with the addition that we are also maxing out CPU. Is there any extra data we can provide to help diagnose this?

**Comment by pauldix** [comment]
We're still investigating this. We have some more debugging stuff going into the nightlies now that might provide more detail. Specifically more logging and the `show stats` query.

**Comment by srfraser** [comment]
Thank you for the update, I'll happily try out any new build

**Comment by pauldix** [comment]
This seems to be related to the overall storage engine issues we're having. I'm closing this out to consolidate all these in one place. We're working on a new storage engine that should fix this. Track #4086 to see when it gets done and to read a full writeup when it's available in a nightly build.
