### ISSUE TITLE
A problem related to some data loss.

### ISSUE THREAD

**Issue by mbarragan** [influxdb/influxdb#3538]
Hi,

I've just started to use Influxdb and I have a problem related to the loss of some data.

I send POSTs with some points every 1 minute to different measurements of the same database. 

My problem is the bellow:

After a POST has been done, I've done the bellow select:

SELECT count(hit) FROM measurement1 WHERE time >= '2015-08-03 08:00:00.000' 

And I've obtained:

time                                   count
2015-08-03T08:00:00Z    1456104

But after 10 minutes, the bellow message has appeared in the influxdb log:

[shard] 2015/08/03 08:11:17 flush 197 points in 0.005s
[shard] 2015/08/03 08:11:19 flush 2058 points in 0.010s
[shard] 2015/08/03 08:11:20 flush 4080 points in 0.033s
[shard] 2015/08/03 08:11:21 flush 372 points in 0.005s
[shard] 2015/08/03 08:11:22 flush 4022 points in 0.048s
[shard] 2015/08/03 08:11:23 flush 255 points in 0.005s
[shard] 2015/08/03 08:11:24 flush 3779 points in 0.031s
[shard] 2015/08/03 08:11:25 flush 290 points in 0.006s
[shard] 2015/08/03 08:11:26 flush 3857 points in 0.053s
[shard] 2015/08/03 08:11:27 flush 1578 points in 0.007s
[shard] 2015/08/03 08:11:28 flush 3347 points in 0.032s
[shard] 2015/08/03 08:11:29 flush 411 points in 0.004s
[shard] 2015/08/03 08:11:30 flush 4154 points in 0.053s
[shard] 2015/08/03 08:11:31 flush 237 points in 0.004s
[shard] 2015/08/03 08:11:32 flush 3357 points in 0.035s
[shard] 2015/08/03 08:11:34 flush 4052 points in 0.052s

Then I've done the same select again and I've received less data than the first one.

Why are there less data?

I have the same problem for all of the POSTs I I'm losing a lot of data.

**Comment by beckettsean** [comment]
Data is not being lost, it's being double-counted in your COUNT statement until the WAL is flushed. https://github.com/influxdb/influxdb/pull/3482 is an attempt to fix this but the first pass didn't work.

Essentially, when you write the points in there's an initial duplication. Once the points are flushed the duplication goes away.
