### ISSUE TITLE
Web UI downgrade to 0.88 in 0.92 CLI

### ISSUE THREAD

**Issue by serenabi** [influxdb/influxdb#3540]
[Urgent] I have 0.88 installed, then I rpm -e it. and install .92. But the Web UI is still connect to v0.88 version 

[root@sijr12mxdb2-iot influxdb]# ./influx
Connected to http://localhost:8086 version InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
InfluxDB shell 0.9.2
> 

How can I get the 8086 to 0.92??

**Comment by serenabi** [comment]
Can any one help me?

**Comment by juddgaddie** [comment]
Try restart influx

**Comment by beckettsean** [comment]
It appears that you still have InfluxDB 0.8.8 running on the box. Shut down the process and make sure that you are explicitly launching the new 0.9.2 binary. The CLI just connects to whatever answers at port 8086, so somehow you've still got the old binary running.
