### ISSUE TITLE
Where should I put the config file for centos/rhel ?

### ISSUE THREAD

**Issue by ericjmiller** [influxdb/influxdb#3543]
I've searched around and it seems there is no straightforward answer to this.  I can't use the default version of the software and need to change many config options.  How can I do this?

I tried the solution found in #3285, but that didn't work for me.

I should add: when I run the -config command found in #3285, I get the following message: 
[handoff] 2015/08/03 19:41;80 Failed to start hinted handoff processor: mkdir all: mkdir /root/.influxdb: permission denied

**Comment by beckettsean** [comment]
@ericjmiller please verify my understanding of the problem:

- You downloaded InfluxDB 0.9.2 and installed the RPM.
- You generated a new config file with `influxd config > filename`
- You launched InfluxDB with `influxd -config /path/to/filename` and you immediately get the permissions error for `/root/.influxdb`?

Is that all correct?

**Comment by ericjmiller** [comment]
Well, there was a lot of running the influxd config > filename in different directories, then restarting the server to see if the config file would work.  But yea, more or less that's what happened.

I'm just going to delete my ec2 instance and start over.

**Comment by ericjmiller** [comment]
I figured it out after reading you steps and reinstalling. 

For those that have the same problem in the future:

run this command in the directory you want to contain your config file:
influx config > filename 

then enter the path to THAT file in the following command:
influxd -config path/to/file

By the way - I didn't see this info in the official docs.
