### ISSUE TITLE
Influxdb goclient API does not work when a field has a newline character in it 

### ISSUE THREAD

**Issue by lokeshverizon** [influxdb/influxdb#3545]
for  b := uint64(0); b < *batch; b++ {
                        pts[b] = influx.Point{
                                Measurement: MEASUREMENT_STR,
                                Fields: map[string]interface{}{
                                        MESSAGE_LABEL_STR : "this has newline\n",
                                },
                                Time:      time.Now(),
                                Precision: PRECISION_STR,
                                Tags: map[string] string {
                                        APP_NAME_K: APP_NAME_V,
                                },
                        }
                }

                bps := influx.BatchPoints{
                        Points:          pts,
                        Database:        DATABASE_NAME,
                        RetentionPolicy: RETENTION_POLICY,
                }

Failed to write the message unable to parse 'app_logs,appname=app msg="node-38eaa7157a74|10.1.20.1|TORRANCE|1|INFO|13|app|app|app|consumer.go:150|2015/07/31 18:03:48.993878379|Commited offset 7499': unbalanced quotes

**Comment by lokeshverizon** [comment]
what is the update on this?

**Comment by beckettsean** [comment]
@lokeshverizon no comments on the issue means no updates yet.
