### ISSUE TITLE
Write became asynchronous?

### ISSUE THREAD

**Issue by xkrt** [influxdb/influxdb#3546]
Hi, I have a [test](https://github.com/influxdb/influxdb-fsharp/blob/master/src/InfluxDB.FSharp.IntegrationTests/Tests.fs#L127) that write a single point and query it back. Starting from some version InfluxDB start responding to query with empty results.

Screenshot of Fiddler dump:
![influxdb_fiddler](https://cloud.githubusercontent.com/assets/428187/9055811/de1586b4-3a96-11e5-879f-6092ead8d38c.png)

As you can see right after `/write` InfluxDB return empty query response (markerd as red, response content len = 16), but after a few seconds same request return data (marked as green, response content len = 179).

version: 0.9.3-nightly-d810682

**Comment by beckettsean** [comment]
This is known and expected behavior. It can take a few seconds for points to become available for querying. Please see Paul's blog post about the CP vs AP split for metadata and data: https://influxdb.com/blog/2015/06/03/InfluxDB_clustering_design.html
