### ISSUE TITLE
[0.9.1] [0.9.2] [nightly] Unable to query fields starting with keywords ("user", "in", ...)

### ISSUE THREAD

**Issue by Dagrut** [influxdb/influxdb#3547]
In 0.9.1, 0.9.2 and the current nightly build, values with names starting with sql keywords cannot be queried. Try inserting this : 
```
network,server=someserver,interface=eth0 in-bytes=1765,in-packets=16,in-errors=0,out-bytes=9719,out-packets=9,out-errors=0 1438675084696
```
And then query it with : 
```
select * from network;
```
It throws a "Server returned error: found IN, expected identifier, string, number, bool at line 1, char 8"
It was not happening in 0.9.1 with "user", but it does with 0.9.2 and later. I only tested it with "user" and "in".
Edit: I read the guidelines too late...
OS: Debian 7.8
Installed from the pre-built .deb.
Test case : 
```
HOST=localhost
curl -G "http://$HOST:8086/query" --data-urlencode 'q=create database mydb'
curl -X POST "http://$HOST:8086/write?db=mydb" --data-binary 'network,server=someserver,interface=eth0 in-bytes=1765,in-packets=16,in-errors=0,out-bytes=9719,out-packets=9,out-errors=0 1438675084697'
curl -G "http://$HOST:8086/query" --data-urlencode 'q=select * from network' --data-urlencode 'db=mydb'
```

Edit 2: It does not need to start with the keyword. An other example :
```
HOST=localhost
DB=test001
curl -G "http://$HOST:8086/query" --data-urlencode 'q=create database '"$DB"
curl -X POST "http://$HOST:8086/write?db=$DB" --data-binary 'network,server=someserver,interface=eth0 net-in-bw=42 1438675084697'
curl -G "http://$HOST:8086/query" --data-urlencode 'q=select * from network' --data-urlencode "db=$DB"
```

Edit 3: It seems that it is releated to the dash character `-`. With spaces (escaped at insertion step), it works. Also having a backslash in a value name may create an error too : "found \\, expected FROM", which may be releated to this issue.

**Comment by DanielMorsing** [comment]
It looks like the in-bytes field gets expanded to `select in-bytes` when `select *` is used and because it contains a keyword and is a valid expression, the select clause doesn't know what to do. A workaround for now would be to insert the measurement as `network,server=someserver,interface=eth0 "net-in-bw"=42 1438675084697`, with ""s around the value name. That would make you able to query the measurement again.

**Comment by Dagrut** [comment]
Thank you, the insertion and query works! :-) . However, the field name now contains the double quotes, so to query it, I have to write `select "\"net-in-bw\""`, and the response also contains the double quotes.
I'll use camelcase for now :stuck_out_tongue: .
