### ISSUE TITLE
SELECT * behavior should be changed

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3549]
Currently, if you do a `SELECT *` query it will do two things.

1. rewrite the `*` to have all field names from the measurement
2. insert a `GROUP BY *` at then end of the query, which will expand out to all tag keys

This is causing a bunch of confusion and bugs. Instead, `SELECT *` should select all field values AND it should insert the tag keys and values in the result set.

For example if you have the following data:

```
cpu,host=A,region=uswest value=23.2 123450
cpu,host=B,region=useast value=65.2 123450
cpu,host=A,region=uswest value=22.3 123460
```

And you do this query: `SELECT * FROM cpu` you should get in the result set a single series. The important bit in the response is this:

```json
{
  "columns": ["time", "host", "region", "value"],
  "values": [
    [123450, "A", "uswest", 23.2],
    [123450, "B", "useast", 65.2],
    [123460, "A", "uswest", 22.3]
  ]
}
```

Note that `time` is always the first column and the other columns are sorted lexicographically.

The insertion of the tags into the result set will need to happen at the Mapper level since the reducer may or may not know about these.

Ideally, this work will also make it possible to do queries like this:

```
SELECT value, host from cpu
SELECT min(value), host from cpu
```

**Comment by jacekgrzybowski** [comment]
A little offtopic, but is it currently possible to return time as integer - like in your example?

**Comment by pauldix** [comment]
It is, when you make the request add the query parameter `epoch=true`

**Comment by jacekgrzybowski** [comment]
Great news, thanks!

**Comment by corylanou** [comment]
Additional notes:

 `SELECT value, host from foo group by host, region`
then `host` should be included in the columns
any tag keys they have in the `GROUP BY` statement, shouldn’t be written into the columns in the case of the `SELECT *`


`select * from foo group by *`
No tags in the columns, only group by tags
