### ISSUE TITLE
tcp.Mux: handler not registered: 71

### ISSUE THREAD

**Issue by dopey** [influxdb/influxdb#3553]
Running influxdb 0.9.2 in a 3 node cluster using only the default ports. The cluster is able to reach consensus and elect a leader, but when it attempts to read data from one node to the next it  uses `:8088` instead of `:8086`. like so: 

```
Connected to http://localhost:8086 version 0.9.2
InfluxDB shell 0.9.2
> use collectd
Using database collectd
> select * from "tail_value" where "host"='myHost'
ERR: Get http://myIp:8088/shard_mapping?chunksize=10000&q=SELECT+value+FROM+%22collectd%22.%22default%22.tail_value+WHERE+host+%3D+%27myHost%27+GROUP+BY+host%2C+instance%2C+type%2C+type_instance&shard=%09: read tcp myIP:8088: connection reset by peer
```

These requests, as well as requests from grafana, result in the log line `tcp.Mux: handler not registered: 71` on the servers to which the request is being made.

**Comment by jwilder** [comment]
Can you post the out of `show servers`?

**Comment by dopey** [comment]
yawp

```
Connected to http://localhost:8086 version 0.9.2
InfluxDB shell 0.9.2
> show servers
id	url
1	http://127.0.0.1:8088
2	http://myIp1:8088
3	http://myIp2:8088
```

Also, I am on ubuntu, running trusty.

**Comment by xinyisu79** [comment]
I have encountered the same problem when I deploy 0.9.2 in 3 nodes. Any update about this issue?

**Comment by jwilder** [comment]
Can you test with `0.9.3`?

**Comment by jwilder** [comment]
The only way I've seen an error like this is when querying against a measurement that is not fully replicated across the cluster (replication factor < # nodes), the coordinating node does not own the shard (remote mapping required) and one of the owning nodes is down.  In that case, I get a `connection refused` error which is not exactly the same but similar.  The original error messages show a `connection reset by peer` which might have been a query bug that killed the server or connection abruptly.

#3377 may fix this if it retries the query when a node fails.

**Comment by otoolep** [comment]
I have not seen this issue for weeks, and only when one connects to the wrong port of an InfluxDB system with the CLI. I don't think this is an issue any longer.
