### ISSUE TITLE
VERSION 0.9.2 not support json format post? 

### ISSUE THREAD

**Issue by SiriusHu** [influxdb/influxdb#3556]
I found that json post is supported in early version, why not now?

**Comment by joshuawarner32** [comment]
The following has been working fine for me on 0.9.2:

```
$ curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary '{"database":"mydb","retentionPolicy":"default","points":[{"measurement":"cpu_load_short","tags":{"host":"server01","region":"us-west"},"timestamp":"2009-11-10T23:00:00Z","fields":{"value":0.64}}]}'
HTTP/1.1 204 No Content
Request-Id: 598c9852-3b7c-11e5-8749-000000000000
X-Influxdb-Version: 0.9.2
Date: Wed, 05 Aug 2015 14:14:57 GMT
```

**Comment by jwilder** [comment]
@SiriusHu The JSON write format has been deprecated in favor of the line protocol.  We did this because of performance reason related to JSON.  The JSON writes still currently work but will be removed in a future release.  

See #2696 for more background.

**Comment by SiriusHu** [comment]
thanks, I got it from 2696
Though I still think JSON is a more convenient way, PERFORMANCE is more I'm concerned with.

**Comment by CumpsD** [comment]
Should they still work in 0.11? Do I have to pass in some allow deprecated flag? (I am trying to move data from a database to anotehr server, from 0.9.3 to 0.11.0)

**Comment by rossmcdonald** [comment]
@CumpsD Please see https://github.com/influxdata/influxdb/pull/5512 for how to re-enable the deprecated JSON write path in v0.11. It will be entirely removed with v0.12.

**Comment by CumpsD** [comment]
Thanks.

Is there a supported way to migrate data from one influxdb database to another (already existing server)?
