### ISSUE TITLE
InfluxDB package for armhf architecture

### ISSUE THREAD

**Issue by cobyism** [influxdb/influxdb#3557]
An issue (https://github.com/influxdb/influxdb/issues/786) was opened about adding an `armhf` build of InfluxDB to the official builds, however it was raised specifically in the context of version 0.8, and closed as redundant with the release of 0.9. I’d like to ask about the possibility of adding an `armhf` build of InfluxDB going forward, *regardless* of version.

There’s already an `armel` build (go [here](https://s3.amazonaws.com/influxdb/) and do an in-page search for `arm`—I can’t seem to find an official link to it anywhere on the site), which is great, however devices like the Raspberry Pi (my specific use case) are `armhf`, which I don’t believe are able to use `armel` binaries.

Related online discussions about getting InfluxDB running on `armhf`:
- https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=81824
- https://groups.google.com/forum/#!msg/influxdb/I-cqsDcZhbQ/MgO4jqIJxy8J
- https://groups.google.com/forum/#!topic/influxdb/FrFyqpXePHg
- https://groups.google.com/forum/#!topic/influxdb/MnJ9a5DFozg
- http://www.pihomeserver.fr/en/2014/11/29/raspberry-pi-home-server-installer-influxdb/
- http://comments.gmane.org/gmane.comp.db.influxdb/353
- http://influxdb.narkive.com/nyFscRlv/building-influxdb-0-9-0-for-armhf

Some people have obviously been able to figure out how to get this to run, however it’d be a great deal easier if there was an official build.

What would need to happen in order for this to be added?

/cc https://github.com/influxdb/influxdb/issues/684

**Comment by beckettsean** [comment]
We're hoping to spend part of the 0.9.4 release cycle on packaging concerns.

**Comment by fg2it** [comment]
@cobyism v0.8 was much harder to build than v0.9.
```bash
#building on raspbian
#1 install gvm
sudo apt-get install bison
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source ~/.gvm/scripts/gvm
#2/ follow https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#installing-go
gvm install go1.4
gvm use go1.4 --default
#3/ install fpm
sudo apt-get install ruby-dev rpm
sudo gem install fpm
#4/ follow the first code snippet of https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#project-structure
export GOPATH=$HOME/gocodez
mkdir -p $GOPATH/src/github.com/influxdb
cd $GOPATH/src/github.com/influxdb
git clone git@github.com:influxdb/influxdb
#5/ 
cd influxdb
NIGHTLY_BUILD=false ./package.sh 0.9.4
#package.sh execution will end by an error but you don't care, you will have your package
```
Way less painfull than before but admittedly, I would love to see an official build for raspberry.

**Comment by beckettsean** [comment]
Addressed in https://github.com/influxdb/influxdb/issues/3755
