### ISSUE TITLE
Should be able to show shards

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3562]
For users to see what shards they have and where they're located, we need a command to show that information. I propose:

```
SHOW SHARDS
```

The result set should include the columns: `id, start_time, end_time, server_ids` Where `server_ids` is a string of comma separated server ids that have a copy of the shard.

Results should be ordered by shard ID.

**Comment by beckettsean** [comment]
Any possibility we could show more information, like when the shard will expire according to the retention policy, the measurements/series in the shard, the size on disk, the compaction percentage, etc.?

**Comment by pauldix** [comment]
@beckettsean The expiration part should be easy. The other ones will be harder. Although they'd be very useful so we should probably create a separate issue for that. Don't think it's something we can get to in 0.9.4, but soon after.

**Comment by otoolep** [comment]
Previously shard data was available through `SHOW DIAGNOSTICS`, and having shard data as part of that command (when re-implemented) was my plan. A dedicated command is fine too, I do not have a strong opinion either way.
