### ISSUE TITLE
[0.9.3-HEAD] Duplicates in query results after restarting and updating a point

### ISSUE THREAD

**Issue by elliots** [influxdb/influxdb#3571]
Running head (using brew install influxdb --HEAD) on osx 10.10.2
At revision 4098de881b

Steps to reproduce

``create database testcase``

- Insert value:

```bash
curl -i -XPOST 'http://localhost:8086/write?db=testcase&precision=s' --data-binary 'temperature value=100 1434059627'
```

```bash
HTTP/1.1 204 No Content
Request-Id: 7c813dd5-3bd8-11e5-8014-000000000000
X-Influxdb-Version: 0.9.3-HEAD
Date: Thu, 06 Aug 2015 01:14:29 GMT
```

- Query results are correct
![image](https://cloud.githubusercontent.com/assets/622455/9101623/8a0a49e6-3c2c-11e5-9b07-6280db585363.png)

- Restart InfluxDB

- Update value
```bash
$ curl -i -XPOST 'http://localhost:8086/write?db=testcase&precision=s' --data-binary 'temperature value=200 1434059627'
```
```bash
HTTP/1.1 204 No Content
Request-Id: d42ecc4b-3bd8-11e5-8018-000000000000
X-Influxdb-Version: 0.9.3-HEAD
Date: Thu, 06 Aug 2015 01:16:56 GMT
```

- Both old and new values are returned from query
![image](https://cloud.githubusercontent.com/assets/622455/9101677/220522e8-3c2d-11e5-997a-1f45d9628d09.png)

- Restart InfluxDB again

- Query results are correct again
![image](https://cloud.githubusercontent.com/assets/622455/9101686/47f4c6a2-3c2d-11e5-8419-4b78cc0784fb.png)

**Comment by beckettsean** [comment]
@otoolep @benbjohnson I thought this was patched with Ben's latest WAL changes?

**Comment by otoolep** [comment]
I too thought all duplicate points issues had been addressed.

**Comment by benbjohnson** [comment]
Fixed with https://github.com/influxdb/influxdb/pull/3626.
