### ISSUE TITLE
[0.9.3-HEAD] Updating a point only works if the value is higher, until you restart

### ISSUE THREAD

**Issue by elliots** [influxdb/influxdb#3572]
Running head (using brew install influxdb --HEAD) on osx 10.10.2
At revision 4098de881b

Steps to reproduce

``create database testcase``

- Insert value:

```bash
curl -i -XPOST 'http://localhost:8086/write?db=testcase&precision=s' --data-binary 'temperature value=100 1434059627'
```

- Query results are correct
![image](https://cloud.githubusercontent.com/assets/622455/9101623/8a0a49e6-3c2c-11e5-9b07-6280db585363.png)

- Update value higher:

```bash
curl -i -XPOST 'http://localhost:8086/write?db=testcase&precision=s' --data-binary 'temperature value=200 1434059627'
```

- Query results are correct
![image](https://cloud.githubusercontent.com/assets/622455/9101865/7e99e3d4-3c2f-11e5-8649-e859c6216e28.png)

- Update value lower:

```bash
curl -i -XPOST 'http://localhost:8086/write?db=testcase&precision=s' --data-binary 'temperature value=50 1434059627'
```

- Query results are incorrect

![image](https://cloud.githubusercontent.com/assets/622455/9101879/aa54a428-3c2f-11e5-9717-a8edf62db886.png)

- Restart influxdb

- Query results are correct

![image](https://cloud.githubusercontent.com/assets/622455/9101885/be3fb978-3c2f-11e5-8731-1dd9006dc502.png)

**Comment by mjdesa** [comment]
@elliots thanks for the report. I'm getting the same results.

**Comment by mjdesa** [comment]
Actually, when I restart my request just hangs.

**Comment by beckettsean** [comment]
I cannot repro on 0.9.3-rc2: (the timestamps are different from the source example because I wasn't supplying `s` for the precision, but the test remains valid as all points have the same timestamp.)

```
Connected to http://localhost:8086 version 0.9.3-rc2
InfluxDB shell 0.9.3-rc2
> create database testcase
> use testcase
Using database testcase
> insert temperature value=100 1434059627
> select * from temperature
name: temperature
-----------------
time				value
1970-01-01T00:00:01.434059627Z	100

> insert temperature value=200 1434059627
> select * from temperature
name: temperature
-----------------
time				value
1970-01-01T00:00:01.434059627Z	200

> insert temperature value=50 1434059627
> select * from temperature
name: temperature
-----------------
time				value
1970-01-01T00:00:01.434059627Z	50

> 
```
