### ISSUE TITLE
SELECT field_name from /.*/ error if field does not exist in all measurements

### ISSUE THREAD

**Issue by jbillhei** [influxdb/influxdb#3573]
In 0.9.2, Ubuntu 14.04 64 bit.

If you do a ```select field_name from /.*/```, you will get ```unknown field or tag name in select clause: field_name``` unless field_name exists in all measurements.  It does not seem to matter that field_name may exist in some of the measurements.

I remember this worked in 0.8.x, it would just return results for measurements that have the requested field.

**Comment by beckettsean** [comment]
closing in favor of #3326

**Comment by jbillhei** [comment]
Missed that issue when searching for similars!  Thanks!
