### ISSUE TITLE
Extremely difficult to find a list of supported datatypes

### ISSUE THREAD

**Issue by nii236** [influxdb/influxdb#3588]
I'm in the process of setting up an InfluxDB instance using an external Unix time stamp. Due to the Unix time 2038 problem I want to be absolutely sure that the datatypes of that field will be int64. 

I can not find any information on the supported datatypes in InfluxDB. The only useful information so far is the fact that once you enter your first value into a field, the datatype is locked and can not be changed in the future.

**Comment by mjdesa** [comment]
@nii236 in the **Fields** section of the [line protocol](https://influxdb.com/docs/v0.9/write_protocols/line.html) docs.

**Comment by xanderdunn** [comment]
Updated [link](https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#data-types)
