### ISSUE TITLE
[0.9.3-nightly-bd51276] After update: Field Type Conflict

### ISSUE THREAD

**Issue by diiidiii** [influxdb/influxdb#3589]
Hi,

i updated my 0.9.3 nightly to bd51276 and now i get a field type conflict when getting data from telegraf and collectd... 

mem_total,host=iqtsdb03 value=164853372000
mem_total,host=itngt02 value=3916788000
[write] 2015/08/07 13:53:37 write failed for shard 45 on node 1: error code 1: write shard 45: field type conflict: input field "value" on measurement "mem_total" is type float64, already exists as type integer

I deleted influxdb, installed new version and configured the influxdb.. accessing data works but writing doesnt... Have you some solutions for my problem?

**Comment by mjdesa** [comment]
@diiidiii recently there was an update to the line protocol. Writing integers now require a trailing `i` and no trailing `i` is specified, influxdb will try to write the value as a float. See issue https://github.com/influxdb/influxdb/pull/3526

**Comment by beckettsean** [comment]
@diiidiii until there is a new release of telegraf, a telegraf database created on 0.9.2 or prior versions will be incompatible when upgraded to InfluxDB 0.9.3. It's a one-time incompatibility, and will be resolved with a new release of telegraf next Thursday.

Closing in favor of https://github.com/influxdb/telegraf/issues/99
