### ISSUE TITLE
Write delays

### ISSUE THREAD

**Issue by jpillora** [influxdb/influxdb#3595]
For testing purposes, I'm writing 1000 points in batches of 7 and the insertion times change from sub-millisecond to just over a second.
```
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e7709bc-3e89-11e5-804c-000000000000 589.857µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e772c90-3e89-11e5-804d-000000000000 562.425µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e774f3c-3e89-11e5-804e-000000000000 543.72µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e77712f-3e89-11e5-804f-000000000000 537.505µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e7790dc-3e89-11e5-8050-000000000000 557.11µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e77b142-3e89-11e5-8051-000000000000 535.125µs
[http] 2015/08/09 21:27:02 127.0.0.1 - - ... 8e77d01d-3e89-11e5-8052-000000000000 438.041µs
[http] 2015/08/09 21:27:03 127.0.0.1 - - ... 8e77ec17-3e89-11e5-8053-000000000000 1.003966261s
[http] 2015/08/09 21:27:04 127.0.0.1 - - ... 8f1132bb-3e89-11e5-8054-000000000000 1.003531407s
[http] 2015/08/09 21:27:05 127.0.0.1 - - ... 8faa668e-3e89-11e5-8055-000000000000 1.006600539s
[http] 2015/08/09 21:27:06 127.0.0.1 - - ... 90440f32-3e89-11e5-8056-000000000000 1.004519916s
[http] 2015/08/09 21:27:07 127.0.0.1 - - ... 90dd666b-3e89-11e5-8057-000000000000 1.00810159s
[http] 2015/08/09 21:27:08 127.0.0.1 - - ... 91774ccd-3e89-11e5-8058-000000000000 1.003943542s
```

Each data point looks like:

``` go
tags := Tags{"a":"a"} //OR Tags{"b":"b"} OR Tags{"c":"c"}
Point{
		Measurement: "bazz",
		Fields:      Fields{"zip": fmt.Sprintf("entry %d", i)},
		Tags:        tags,
		Time:        t0.Add(time.Duration(i) * 24 * time.Hour),
}
```

Restarting `influxd` seemed to help, then I increased the total number of points to 5000 and it started happening again after about 2000 points.

Am I getting rate limited? Or is this an internal blocking issue? Any idea what's happening?

Edit: `InfluxDB, version 0.9.2, commit 6c0a91f775f9fc0e625d17ffa04a3fe86945ba09` on OSX 10.10

Edit 2: Changing the batch size to 500 points for a total of 10 inserts still blocks, only for longer now:

```
[http] 2015/08/09 21:58:53 127.0.0.1 - - ... 0125f707-3e8e-11e5-8022-000000000000 12.420728ms
[http] 2015/08/09 21:58:53 127.0.0.1 - - ... 01289a5e-3e8e-11e5-8023-000000000000 15.476115ms
[http] 2015/08/09 21:58:53 127.0.0.1 - - ... 012c3d7a-3e8e-11e5-8024-000000000000 16.280127ms
[http] 2015/08/09 21:58:53 127.0.0.1 - - ... 012f86a9-3e8e-11e5-8025-000000000000 10.710813ms
[http] 2015/08/09 21:59:22 127.0.0.1 - - ... 0131e111-3e8e-11e5-8026-000000000000 29.172071989s
```

**Comment by otoolep** [comment]
What version are you running? This may be related to WAL flushing, which is being addressed in https://github.com/influxdb/influxdb/issues/3514

**Comment by jpillora** [comment]
`InfluxDB, version 0.9.2, commit 6c0a91f775f9fc0e625d17ffa04a3fe86945ba09` (bottom of the text)

**Comment by jwilder** [comment]
It looks like you are writing points into the future and you are probably hitting shard group boundaries which require new shard groups to be created in the meta store.  Creating new shard groups goes through raft consensus and there was a 1s delay in place in `0.9.2` (and prior) to allow the raft changes to propagate throughout the cluster.  That has been removed in `0.9.3` by commit e904416.  There will still be a small delay when a new shard group is created but it should not consistently be 1s.

I'd suggest testing with the current nightly to see if this has improved.

**Comment by jpillora** [comment]
Okay great thanks @jwilder will get back to you

**Comment by jpillora** [comment]
Seems as if writing points into the future was the issue - changing the timestamp on each point to `t0.Add(time.Duration(i) * time.Minute),` solved the problem.

**Comment by arvindsam96** [comment]
We have an django rest framework running with Influxdb as DB. 
Sometimes, when request is posted to the server, InfluxDB is taking more than 10 secs to insert records in one of my measurement (Records are received at the same time, but got inserted after 13 secs as seen in below log lines).

**2022-02-10 09:11:34,268** : INFO: Record [{'measurement': 'agentChangeInfo', 'fields':{'timestamp': '2022-02-10 09:11:34', 'authorized': False, 'enabled': True}, 'tags': {'agentName': 'RAV11300'}}] inserted successfully to default.agentChangeInfo!!

**2022-02-10 09:11:47,900** : INFO: Record [{'measurement': 'agentChangeInfo', 'fields':{'timestamp': '2022-02-10 09:11:34', 'authorized': True, 'enabled': True, 'splitState': False, 'stateChange': 'active'}
