### ISSUE TITLE
Multiple UDP configuration not supported in 0.9.2

### ISSUE THREAD

**Issue by tpitale** [influxdb/influxdb#3596]
Version 0.7.1 added support for multiple UDP configuration. I just updated to 0.9.2 and this feature appears to be gone.

https://github.com/influxdb/influxdb/blob/0c4c5b20cb8f5d9db97544027e87010619002c54/CHANGELOG.md#v071-2014-05-29

* Was this an intentional decision, or was the feature simply lost over time?
* Is there another way to configure this now?
* If I were to add support again, is that something desirable?

**Comment by tpitale** [comment]
Maybe the intention is to start multiple instances of influxdb each with its own distinct config?

**Comment by tpitale** [comment]
Nope, running multiple processes does not appear to work (or at least easily). The configuration settings needed might be wrong.

**Comment by beckettsean** [comment]
Duplication of https://github.com/influxdb/influxdb/issues/2785
