### ISSUE TITLE
influxd db 9.2 takes too long to start 

### ISSUE THREAD

**Issue by FarzinZaker** [influxdb/influxdb#3597]
when starting influxdb service, it **starts filling memory to reach upper than 12GB very slowly**. during startup time, cpu usage is 100%. then starts responding on port 8086! before reaching this amount of memory usage no one is listening on port 8086.

There is no way to limit memory usage of influxdb currenty. some times influxdb stops responding to write post messages for about 1hour, so I need to restart influxdb service periodically which takes about 2 hours!!!

what is the problem?

Thanks in advance

This is my **data folder size**:
11441272        data/

I have installed influxdb 9.2 on **Red Hat Enterprise Linux Server release 6.4 (Santiago)** using instructions provided in https://influxdb.com/docs/v0.9/introduction/installation.html 

this is my **influxdb.config** content

```
### Welcome to the InfluxDB configuration file.

# Once every 24 hours InfluxDB will report anonymous data to m.influxdb.com
# The data includes raft id (random 8 bytes), os, arch, version, and metadata.
# We don't track ip addresses of servers reporting. This is only used
# to track the number of instances running and the versions, which
# is very helpful for us.
# Change this option to true to disable reporting.
reporting-disabled = false

###
### [meta]
###
### Controls the parameters for the Raft consensus group that stores metadata
### about the InfluxDB cluster.
###

[meta]
  dir = "/var/opt/influxdb/meta"
  hostname = "localhost"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"

###
### [data]
###
### Controls where the actual shard data for InfluxDB lives and how it is
### flushed from the WAL. "dir" may need to be changed to a suitable place
### for your system, but the WAL settings are an advanced configuration. The
### defaults should work for most systems.
###

[data]
  dir = "/var/opt/influxdb/data"
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

###
### [cluster]
###
### Controls non-Raft cluster behavior, which generally includes how data is
### shared across shards.
###

[cluster]
  shard-writer-timeout = "5s" # The time within which a shard must respond to write.
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.

###
### [retention]
###
### Controls the enforcement of retention policies for evicting old data.
###

[retention]
  enabled = true
  check-interval = "10m"

###
### [admin]
###
### Controls the availability of the built-in, web-based admin interface. If HTTPS is
### enabled for the admin interface, HTTPS must also be enabled on the [http] service.
###

[admin]
  enabled = true
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

###
### [http]
###
### Controls how the HTTP endpoints are configured. These are the primary
### mechanism for getting data into and out of InfluxDB.
###

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

###
### [[graphite]]
###
### Controls one or many listeners for Graphite data.
###

[[graphite]]
  enabled = false
  # bind-address = ":2003"
  # protocol = "tcp"
  # consistency-level = "one"
  # name-separator = "."

  ## "name-schema" configures tag names for parsing the metric name from graphite protocol;
  ## separated by `name-separator`.
  ## The "measurement" tag is special and the corresponding field will become
  ## the name of the metric.
  ## e.g. "type.host.measurement.device" will parse "server.localhost.cpu.cpu0" as
  ## {
  ##     measurement: "cpu",
  ##     tags: {
  ##         "type": "server",
  ##         "host": "localhost,
  ##         "device": "cpu0"
  ##     }
  ## }
  # name-schema = "type.host.measurement.device"

  ## If set to true, when the input metric name has more fields than `name-schema` specified,
  ## the extra fields will be ignored.
  ## Otherwise an error will be logged and the metric rejected.
  # ignore-unnamed = true

###
### [collectd]
###
### Controls the listener for collectd data.
###

[collectd]
  enabled = false
  # bind-address = ""
  # database = ""
  # typesdb = ""

###
### [opentsdb]
###
### Controls the listener for OpenTSDB data.
###

[opentsdb]
  enabled = false
  # bind-address = ""
  # database = ""
  # retention-policy = ""

###
### [udp]
###
### Controls the listener for InfluxDB line protocol data via UDP.
###

[udp]
  enabled = false
  # bind-address = ""
  # database = ""
  # batch-size = 0
  # batch-timeout = "0"

###
### [monitoring]
###

[monitoring]
  enabled = true
  write-interval = "24h"

###
### [continuous_queries]
###
### Controls how continuous queries are run within InfluxDB.
###

[continuous_queries]
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m"

###
### [hinted-handoff]
###
### Controls the hinted handoff feature, which allows nodes to temporarily
### store queued data when one node of a cluster is down for a short period
### of time.
###

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"
  max-size = 1073741824
  max-age = "168h"
  retry-rate-limit = 0
  retry-interval = "1s"
```

**Comment by FarzinZaker** [comment]
today it stopped responding to select queries too. select queries takes too long without response or timeout. 

please tell me how can I debug influxdb queries to find out problem.

**Comment by FarzinZaker** [comment]
in startup influxdb uses only one core to bring data too ram. is there any solution for using multiple cores? it may help speeding up startup process

**Comment by FarzinZaker** [comment]
no idea?

**Comment by beckettsean** [comment]
@FarzinZaker the challenge is that we have no other similar reports, so it's tough to guess what might be happening. You've only got 11 MB of data, so there's no reason RAM should grow significantly beyond that. 

Can you share some examples of your write statements?

Can you include your logs from startup?

**Comment by FarzinZaker** [comment]
As you see, data files size is 11GB not 11MB. I have about 161K measurements. each measurement may include 100 to 10000 data points.

Is it normal for influxdb to bring all data to ram at startup?

according to influxdb website:
On disk and in memory. It shouldn’t require a cluster of machines keeping everything in memory since most analytics data is cold most of the time.

so why it is bringing all data to ram?

I should mention that I have upgraded influxdb from 8.6 to 9.0 and 9.1 and 9.2 using rpm -Uvh. but data base is created after upgrading to 9.2.

**Comment by otoolep** [comment]
It is not bringing all the data into RAM, it does load metadata however, which is an index of what series are in the shards.

**Comment by FarzinZaker** [comment]
so why it is consuming 12GB of ram on startup?

**Comment by FarzinZaker** [comment]
would disabling new shard creation on every 10 minutes help?

**Comment by otoolep** [comment]
@FarzinZaker -- how do you know shards are being created every 10 minutes?

**Comment by FarzinZaker** [comment]
@otoolep I saw in previous issues for influxdb 8.x and in log file of 8.x version.

<img width="601" alt="screen shot 2015-08-14 at 1 27 28 am" src="https://cloud.githubusercontent.com/assets/3818476/9261536/c5f5e332-4223-11e5-9f65-be80a4378938.png">
<img width="591" alt="screen shot 2015-08-14 at 1 27 49 am" src="https://cloud.githubusercontent.com/assets/3818476/9261542/cf7be230-4223-11e5-94fc-4d58fb2954e7.png">

as you see, influxdb is consuming about 20GB one day after restart

**Comment by FarzinZaker** [comment]
if you think remote access to server helps detecting problem, give me your email address plz.

**Comment by otoolep** [comment]
@DanielMorsing

**Comment by DanielMorsing** [comment]
Some profiles out of the system would be really helpful in tracking this down. To get a cpu profile and a memory profile run
```
go tool pprof -proto -output /tmp/memprofile http://serverhostname:8086/debug/pprof/heap
go tool pprof -proto -output /tmp/cpuprofile http://serverhostname:8086/debug/pprof/profile
```
If you send me the /tmp/cpuprofile and /tmp/memprofile files, I'll have a look

**Comment by FarzinZaker** [comment]
@DanielMorsing

[memprofile](https://drive.google.com/file/d/0B9I7x2AXZPB9ZUZzQ3VLcmlkQTQ/view?usp=sharing)
[cpuprofile](https://drive.google.com/file/d/0B9I7x2AXZPB9NlBsVWIyWm9iVDg/view?usp=sharing)

thanks in advance

**Comment by DanielMorsing** [comment]
Looking at the profiles, there seem to be a lot of fields being created. What is the data that you're inserting?

**Comment by FarzinZaker** [comment]
I am using InfluxDB for historical data of stocks market. closing, min, max, low and high price plus stocks market related indicators like sma, ema, rsi and ...

I am not using fields or tags. I have created a measure for each property of each stocks item.

for example name of a measure is like dailyTrade_{itemID}_closingPrice or indicator_{itemId}_sma_7

so each measurement only keeps a value and date but I have about 161K measurements in this way

**Comment by beckettsean** [comment]
@FarzinZaker that is a less-than-optimal schema. I would strongly recommend writing to a few measurements and using tags to identify metadata.

Measurement: dailyTrade
Tags: ItemID, closingPrice
Field: value=<closing price>

Also, a minor note, you are using fields, as it is not possible to write a point without at least one field. In InfluxDB, a field is the actual value stored with a metric. See https://influxdb.com/docs/v0.9/concepts/glossary.html for more context.

**Comment by FarzinZaker** [comment]
@beckettsean This type of design is because of limitations in version 0.8
sure, I will change it as you said

but you mean, stability problem, long start time and huge memory consumption is because of my wrong design?

**Comment by beckettsean** [comment]
0.9 has a brand new schema design, I highly recommend researching that and updating your code to reflect it. InfluxDB 0.9 is built with the assumption that there will be perhaps 100s of measurements in a given database, more likely a dozen or two. 

I cannot blame any particular issue on the schema, but when there are problems and also a known bad practice at work, it's generally best to fix the bad practice first, rather than go down the rabbit hole of trying to tune something that's possibly fundamentally broken.

Practical effects are that your in-RAM series index is an incredibly broad, shallow index, rather than a deep branching index. What impact that has is hard to say *a priori* but it could easily have an impact on total RAM usage. 

Another effect is that the database tracks field types per measurement. On startup, the system has to go and load the data types for each field for each measurement. That code is not at all tuned because there should be perhaps 50 field buckets to check. In your case there are 161000 buckets to check, and it's entirely possible that's a huge resource hog. It doesn't matter for those using a more congruent schema because a slow process that only happens a few dozen times is unnoticeable.

There are no doubt many more places where that number of measurements will lead to less than ideal behavior, simply because no one has gone poking around in those places yet from lack of need.

**Comment by FarzinZaker** [comment]
after migrating to new model, the problem solved and influxdb startup time is about 5 seconds now. thanks for your help. 

the only remaining problem is that after about 2 or 3 days, write actions slow down from about 1ms for each point to 10ms. so influxdb should be restarted every 2 days.

**Comment by beckettsean** [comment]
Thanks for the update, @FarzinZaker. Future releases of 0.9 should eliminate any need to reboot to maintain performance.
