### ISSUE TITLE
Writing data - tags don't seem to be optional when using the lines format

### ISSUE THREAD

**Issue by jamhall** [influxdb/influxdb#3600]
Importing data with a tag succeeds:

```
curl -i -XPOST 'http://localhost:8086/write?db=timevalue&precision=s' --data-binary 'datapoints,dataset=test temperature=1.220,windspeed=2.301,humidity=92.900 1351724461' 
```

However, If I try to import some data points without a tag, it fails:

```
curl -i -XPOST 'http://localhost:8086/write?db=timevalue&precision=s' --data-binary 'datapoints, temperature=1.220,windspeed=2.301,humidity=92.900 1351724461' 
```

This returns: 
```
unable to parse 'datapoints, temperature=1.220,windspeed=2.301,humidity=92.900 1351724461': missing tag key
```

Or If I remove the space between the series name and the fields:

```
curl -i -XPOST 'http://localhost:8086/write?db=timevalue&precision=s' --data-binary 'datapoints,temperature=1.220,windspeed=2.301,humidity=92.900 1351724461' 
```

This returns:

```
unable to parse 'datapoints,temperature=1.220,windspeed=2.301,humidity=92.900 1351724461': invalid field format
```

Aren't tags supposed to be optional?

Thanks in advance

**Comment by jwilder** [comment]
Don't add a comma if you do not want tags. Just use a space and list your fields.

**Comment by gunnaraasen** [comment]
Tags are optional. Both of those data points are not valid line protocol points.

For the first point, the comma after temperature needs to be removed (or backslash escaped if the comma is part of the measurement name).

For the second point, there needs to be a space between the measurement name and the field values.

**Comment by jamhall** [comment]
@jwilder and @gunnaraasen  - Thank you very much for the information.  Much appreciated!

**Comment by jsrimr** [comment]
> Don't add a comma if you do not want tags. Just use a space and list your fields.

For those want abbreviation : 
```insert datapoints temperature=1.220,windspeed=2.301,humidity=92.900```

**Comment by rwb196884** [comment]
I have
```
commands = ["python -c \"import sys; sys.path.append('/usr/local/lib/python2.7'); import sun; print sun.getSEA(52.001, -2.001, 0)\" | awk '{ print \"sea sea=\" $0 }'"]
```
which outputs
```
sea sea=-40.1217819452
```
but
```
[inputs.exec] Error in plugin: metric parse error: expected tag at 1:15: "-40.1217819452"
```
