### ISSUE TITLE
Why on a real machine, concurrency 1s less than 30? cpu utilization rate has remained unchanged

### ISSUE THREAD

**Issue by zengzhihai110** [influxdb/influxdb#3604]
Why on a real machine, concurrency 1s less than 30? cpu utilization rate has remained unchanged

But I linux in a virtual machine but 1s concurrent high above, cpu utilization is high, the environment and versions are the same, what is the reason

**Comment by beckettsean** [comment]
@zengzhihai110 this is not a bug report or a feature request. Perhaps the mailing list would be a better place for your question: influxdb@googlegroups.com. If you are seeing substantially different behavior from InfluxDB on two different systems that you think is a bug, please provide more details of each system.
