### ISSUE TITLE
[0.9.2] very slow to write multiple points

### ISSUE THREAD

**Issue by korora** [influxdb/influxdb#3620]
Hi,
I'm trying to insert a huge records, but it seems to be very slow when I throw request by curl.
It takes about 2.5 minutes for 1000 points. I installed 0.9.2 on Mac book pro late 2011 with core i7, 16GB RAM and SSD, so I think it is no problem with hardware spec. I didn't change anything on config file.
Here is the command:

curl -i -XPOST 'http://127.0.0.1:8086/write?db=mydb' --data-binary @filename

and the content of file is like that:
flow3_13,station_name=anystation,river_name=anyriver,place=L value=614.0 863913600000000000

Is there any way to solve the problem, or is it a bug?
Thanks,
/Muneo

**Comment by zengzhihai110** [comment]
me too

**Comment by zengzhihai110** [comment]
We have the same problem

**Comment by mjdesa** [comment]
@korora are the points you're writing in ordered where time is increasing? Writing points in non increasing order causes huge decreases in write performance.

**Comment by korora** [comment]
Thanks for the replies!
I didn't know about that specification, but time is increasing in my file.
Here's the example. This is a historical data so timestamps are very young.

flow3_13,station_name=SIKFORS_KRV,place=L value=51.0 86400000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=50.0 172800000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=50.0 259200000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=50.0 345600000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=48.0 432000000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=47.0 518400000000000
flow3_13,station_name=SIKFORS_KRV,place=L value=45.0 604800000000000

**Comment by kwilcox** [comment]
I've also seen large slowdowns in some cases but haven't tracked down the issue yet.

Here is an example:
https://gist.github.com/kwilcox/1a2529d674aaad14b59c

* 13**s** - 2000 records with a constant depth=N tag
* 13**s** - 2000 records with no tags
* 70**ms** - 2000 records with increasing time and depth tag

**Comment by mjdesa** [comment]
@kwilcox any chance you can send me the a gist with the points you're trying to write so i can try to repro?

**Comment by kwilcox** [comment]
@mjdesa Here you go, let me know if you need any other combinations of tags, etc. with the same data.

https://gist.github.com/kwilcox/3fceb9a7dc8b3f25f858

**Comment by mjdesa** [comment]
@kwilcox I'm getting really similar write times for both of those. On average about 75ms. Are you getting something different?

```
[http] 2015/08/12 14:03:59 ::1 - - [12/Aug/2015:14:03:59 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.37.1 a6bf501f-4135-11e5-8002-000000000000 88.559845ms
[http] 2015/08/12 14:06:21 ::1 - - [12/Aug/2015:14:06:21 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.37.1 fbcaff42-4135-11e5-8003-000000000000 71.331064ms
```

**Comment by kwilcox** [comment]
@mjdesa oyyyyy I should have tried `curl` with the line protocol messages directly.  I am too getting similar results for both sets.  It is the `influxdb-python` library causing the slowdown. I'll investigate there, thanks!

**Comment by mjdesa** [comment]
@kwilcox anytime. Let me know if you figure out whats causing the issue in the python lib. I'm interested in knowing what is causing the slow down.

**Comment by mjdesa** [comment]
@korora do you have data I can try to repro the issue with?

**Comment by korora** [comment]
@mjdesa 
Sure!
here is the data:
https://gist.githubusercontent.com/korora/8a43d76bbbeb8360dfb6/raw/9c58399e2ac954742415794f4aa69e3d7f0cad35/h13influx9.txt

**Comment by mjdesa** [comment]
@korora 

When I run `curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary '@h13influx9.txt'`

I get 

```
[http] 2015/08/13 11:24:36 ::1 - - [13/Aug/2015:11:24:32 -0700] POST /write?db=mydb HTTP/1.1 204 0 - curl/7.37.1 8adb468a-41e8-11e5-8004-000000000000 3.959147152s
```

**Comment by mjdesa** [comment]
@korora I'm closing this issue.

**Comment by korora** [comment]
@mjdesa sorry, I was away yesterday. In my case it returns http 100 and did not proceed to 204. then l reduced the lines to 1000 and tried again, and after 2.5min it returned 204.

**Comment by mjdesa** [comment]
@korora have you tried using 0.9.3?

**Comment by korora** [comment]
not yet. is it 0.9.3 that you tried?

**Comment by mjdesa** [comment]
yeah, if you're still having performance issues with 0.9.3 I'll reopen the issue

**Comment by korora** [comment]
@mjdesa 
Thanks for tips.

I installed 0.9.3 nightly and inserted the file. It took only several seconds so the performance problem seems to be solved.
But after I got HTTP 204, influxdb process died and after I restarted this I tried following query:
select count(value) from flow3_13;  

...and the server does not respond:(
use mydb; and show measurements; worked  though.

But maybe it is another problem?

**Comment by mjdesa** [comment]
Sounds like its another issue. Can you give me the steps to try to repro?

**Comment by korora** [comment]
Okay, I'll make sure the steps.  
I think I can report it by tonight or tomorrow.

**Comment by korora** [comment]
I couldn't connect to localhost:8086 any more so I deleted the current installation(including config file) and re-installed 0.9.3-nightly-c2dbf16, but now this build does not seem to have any config file and could not start at all. I think I should wait more stable nightly build.

**Comment by otoolep** [comment]
@korora -- I just installed the nightly build to which you refer and it works fine for me. The config file is there, and it started up without any trouble.

Please be aware that there are breaking changes in the 0.9.3 nightly relative to 0.9.2 and any older config file will need to be changed with regards to the `udp` input. Specifically:

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L171

**Comment by zengzhihai110** [comment]
why very slow to  write data use udp ???


use InfluxDB\Point;

// directly get the database object
$database = InfluxDB\Client::fromDSN(sprintf('influxdb://user:pass@%s:%s/%s', '127.0.0.1', 8086, 'test_db'));

    // get the client to retrieve other databases
$client = $database->getClient();   

// set the UDP driver in the client
$client->setDriver(new \InfluxDB\Driver\UDP($client->getHost(), 4444));

for($i=0;$i<1000000;$i++){
	$points = [
	    new Point(
	        'test_metric',
	        0.84,
	        ['host' => 'server01', 'region' => 'us-west'],
	        ['cpucount' => 10],
	        exec('date +%s%N') // this will produce a nanosecond timestamp in Linux operating systems
	    )
	];

	$result = $database->writePoints($points);
}



sdk ：  https://github.com/influxdb/influxdb-php

**Comment by beckettsean** [comment]
@zengzhihai110 from the testing @korora did it appears the slowdown is primarily in the PHP library. Perhaps the library isn't batching points, perhaps it's writing them in an inefficient manner, I'm not sure. The library is maintained by the community, not by InfluxDB. Please open an issue on that repo for assistance: https://github.com/influxdb/influxdb-php/issues/new
