### ISSUE TITLE
[0.9.2]Can not access the db by admin UI after set http auth-enabled = true at 0.9.2  Centos.

### ISSUE THREAD

**Issue by mail2fish** [influxdb/influxdb#3621]
A correct user name and password has set in Connection Settings.

But it always got "Couldn't fetch database list from InfluxDB (http://192.168.0.69:8086). Try updating your connection settings and make sure the server is running."

The http status code was 405 Method Not Allowed.

Version: 0.9.2
OS: Centos 7

**Comment by aheusingfeld** [comment]
@mail2fish I have influxdb 0.9.2.1 running with this working like a charm. You might want to try the tutum docker image that I updated recently https://github.com/tutumcloud/influxdb/pull/47 -> https://registry.hub.docker.com/u/tutum/influxdb/

**Comment by gunnaraasen** [comment]
@mail2fish as @aheusingfeld mentioned, this error was fixed in a special release of 0.9.2.1. The RPM package can be downloaded here: `https://s3.amazonaws.com/influxdb/influxdb-0.9.2.1-1.x86_64.rpm`.
