### ISSUE TITLE
Can not access Admin UI for influxdb from browser

### ISSUE THREAD

**Issue by Chaithra83** [influxdb/influxdb#3627]
The admin UI for influx can not be accessed it throws the below error. We are using influx 0.9.2
But Grafana is able to get data from same influxdb.

Couldn't fetch database list from InfluxDB (http://10.3.4.:8086). Try updating your connection settings and make sure the server is running.

Please provide your inputs on this

**Comment by gunnaraasen** [comment]
@Chaithra83 `10.3.4.` does not look like a valid IP address. Can you double check your connection settings? Also, if auth is turned on you may be running into this issue, https://github.com/influxdb/influxdb/issues/3222.

**Comment by beckettsean** [comment]
@Chaithra83 any updates?

**Comment by san310787** [comment]
I have installed influxdb (influxdb-0.9.2.1-1.x86_64.rpm) in a redhat linux enterprise server and started the server. 

After starting the influxdb process, to work using influx cli, executed /opt/influxdb/influx file. gives the message as below.

Connected to http://localhost:8086 version 0.9.2
InfluxDB shell 0.9.2.1

I tried to access the influxdb ui from my windows machine using the url 

http://linuxmachineip:8086/

I get 404 page not found.

If I access using 8083 port http://linuxmachineip:8083/, I get a GUI as below. But, database list is not fetched.

![image](https://cloud.githubusercontent.com/assets/13868788/9355456/13ccf7a4-4697-11e5-99e3-1f020b09e7fd.png)


Please throw your ideas on this?

**Comment by gunnaraasen** [comment]
@san310787 Accessing `http://linuxmachineip:8086/` will not return results to the browser. The admin UI is only accessible on port 8083.

Does a database exist? Have you made sure the connection settings are valid (includes credentials if you're using auth).

**Comment by rohilbh** [comment]
I'm seeing the same issue and am getting the same error message as above. If I try to execute a query like show databases, I get "Couldn't connect to host(<host>): error". I am sure a database exists and my credentials are correct because I can query the database using the CLI and write to it and Grafana is querying it successfully. Only the browser UI is having issues.

**Comment by gunnaraasen** [comment]
@rohilbh What version are you running? What are your connection settings? "Couldn't connect to host(): error" indicates the admin UI is not making contact with InfluxDB.

**Comment by rohilbh** [comment]
@gunnaraasen  I'm running version 0.9.2. I've confirmed my host and port (8086) are correct and I was using auth in the beginning so I had a username and password. On the clean installation on the new machine, I am not using auth and it is working so far.

**Comment by gunnaraasen** [comment]
Not sure why the auth would not be working. I also recommend trying out 0.9.3-rc1, which has better admin UI error messages.

@san310787 @Chaithra83 please try 0.9.3-rc1.

**Comment by rohilbh** [comment]
will do, but can confirm it has to do with auth. Tried without auth on both machines and the admin UI worked fine.

**Comment by san310787** [comment]
@gunnaraasen: Yes. I was wrong. Admin UI was accessible on port 8083. I tried that too. But, it was not fetching the database list. That's the point where I decided to check here.

The arbitrary username/password which I set here in Connection Settings section was not correct I think. I gave as root/password initially. Later, I tried with influxdb/influxdb. It worked. It fetched the database list and I can execute the queries.

BTW, I'm using 0.9.2.1. I'll try what you recommended too.

**Comment by richipal** [comment]
I changed the influxdb.conf with following property in [admin] section
enabled = true
It works now.

**Comment by vit1251** [comment]
Could you add please [admin] section in default influxdb.conf in /etc directory.

**Comment by michaeldongvrviu** [comment]
@vit1251 
![image](https://user-images.githubusercontent.com/29565083/34765183-cd4a15fe-f62b-11e7-900a-77e6ef8908db.png)
https://docs.influxdata.com/influxdb/v1.4/tools/web_admin/

**Comment by vit1251** [comment]
@michaeldongvrviu, thanks.
