### ISSUE TITLE
meta store problem after upgrade -> localhost:8088 not in [127.0.0.1:8088]

### ISSUE THREAD

**Issue by timgriffiths** [influxdb/influxdb#3632]
So updated from 0.9.2 to the nightly build tonight (to see if #3603 is resolved) and hit this problem
```
[metastore] 2015/08/12 23:59:04 localhost:8088 is not in the list of raft peers. Please update /data/meta/peers.json on all raft nodes to have the same contents.
run: open server: open meta store: raft: peers out of sync: localhost:8088 not in [127.0.0.1:8088]
```
Easy work around is to just edit this file and change the ip address to the name, but sort of blocks an easy clean upgrade for no real reason as far as i can see.

**Comment by beckettsean** [comment]
@timgriffiths are you running a cluster or was this a single node upgrade?

**Comment by mjdesa** [comment]
@timgriffiths have you tried setting your `/data/meta/peers.json` file to be `["localhost:8088"]`?

**Comment by jwilder** [comment]
You can also start your server with `-hostname 127.0.0.1`.  #3641 will resolve this for single-node.

**Comment by timgriffiths** [comment]
Single node setup, and yes setting the ip to localhost in /data/meta/peers.json has resolved the problem, 

Using the hostname flag i assume would also solve the problem as well but i have not tested
