### ISSUE TITLE
[Question] Regarding influxdb cluster

### ISSUE THREAD

**Issue by phagunbaya** [influxdb/influxdb#3642]
1. [0.9.3] Will it still be a case to always connect with master ?
2. [0.9.2] I was encountering issue with cluster in term of availability. I added ~10 datapoint and immediate fetch did not retrieve anything. It took few seconds to make the data available. Any thoughts ?
3. [0.9.3] If any of the node is down, will influx service be still available ?
4. [0.9.3] If any of the node is down, then I have to programmatically handle retry with other node ?
5. [0.9.3] Will there be write timeout exception, if payload is ~50mb ?

**Comment by mjdesa** [comment]
@phagunbaya 

1. I'm not sure I understand what you are asking.
2. As I understand it, data isn't available for querying until its been fully replicated in 0.9.2, but I could be wrong.
3. If a node goes down influx will be available. It just won't be possible to issue queries or writes to that node.
4. Yes.
5. Write timeouts are configurable.

**Comment by otoolep** [comment]
Q2: may or may not be queryable before it has been fully replicated. It depends if the node servicing the query has received the data yet.

**Comment by phagunbaya** [comment]
@mjdesa : 
- With Q1 I meant, with 0.9.3 will I be able to connect with any of the node in the cluster even if it's not the master ? 
- Q3 : Will data get replicated automatically if node comes back ?
- Q5 :  Using this `write-timeout=20s` right ?

@otoolep : What I encountered was, when writing and reading back from same node in the cluster required me to put some time delay.

Also till what version it will be the case to have cluster of 3 nodes always ?

**Comment by mjdesa** [comment]
@phagunbaya 

- Q1. In 0. 9.3 you can connect to any node in the cluster. Currently there's a bug, noted in https://github.com/influxdb/influxdb/issues/3574 which prevents queries to non-raft nodes in the cluster.
- Q3. To my knowledge, no, old data will not get replicated, but new data will be.
- Q5. Yes.

**Comment by mjdesa** [comment]
0.9.3 allows for arbitrarily sized cluster. The first 3 nodes to join a cluster are the raft *peers* the rest are data nodes.

**Comment by beckettsean** [comment]
@phagunbaya please address questions to the mailing list, as GitHub Issues should be for feature requests and bug reports. If you read the [blog](https://influxdb.com/blog.html) and follow the [CHANGELOG updates](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md) you will have a reasonable idea what's happening with new releases.
