### ISSUE TITLE
Bulk load crashes influxDB

### ISSUE THREAD

**Issue by ianflint** [influxdb/influxdb#3644]
NOTE: My understanding is that the 500 issue is a known issue in 0.9.2, but I'm not sure if the crashing issue is, so I'm putting this in the system just to make sure it's known.

I was doing a bulk load into influxDB at Yahoo, and it crashed.

Here are the specifics:
Running on an openstack VM with
two CPU allocated,
4GB RAM,
107GB Virtual Disk,
RHEL 6.6 (64 Bit) - 2.6.32-431.23.3

I notice a few bad behaviors:

First, the server would return 500 responses until it flushed points, and then it would go back to 204 responses. Here's an example:

```
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:50 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5852fa0c-41a7-11e5-b49e-000000000000 1.095539723s
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 58ff03d8-41a7-11e5-b49f-000000000000 108.762595ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5914ac73-41a7-11e5-b4a0-000000000000 137.166907ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 592ea571-41a7-11e5-b4a1-000000000000 145.381486ms
[http] 2015/08/13 10:37:51 ::1 - - [13/Aug/2015:10:37:51 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 5949ad8a-41a7-11e5-b4a2-000000000000 191.109206ms
[http] 2015/08/13 10:37:52 ::1 - - [13/Aug/2015:10:37:52 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 596ebc38-41a7-11e5-b4a3-000000000000 139.672744ms
[http] 2015/08/13 10:37:57 ::1 - - [13/Aug/2015:10:37:52 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5989f415-41a7-11e5-b4a4-000000000000 5.004170123s
[http] 2015/08/13 10:38:02 ::1 - - [13/Aug/2015:10:37:57 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5c8d211f-41a7-11e5-b4a5-000000000000 5.277618526s
[http] 2015/08/13 10:38:07 ::1 - - [13/Aug/2015:10:38:02 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 5fd4adc4-41a7-11e5-b4a6-000000000000 5.203838367s
[http] 2015/08/13 10:38:13 ::1 - - [13/Aug/2015:10:38:08 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 63030dc4-41a7-11e5-b4a7-000000000000 5.168254414s
[http] 2015/08/13 10:38:18 ::1 - - [13/Aug/2015:10:38:13 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 66290c96-41a7-11e5-b4a8-000000000000 5.026161599s
[http] 2015/08/13 10:38:23 ::1 - - [13/Aug/2015:10:38:18 +0000] POST /write?db=net_test HTTP/1.1 500 8 - - 69305036-41a7-11e5-b4a9-000000000000 5.04217651s
[shard] 2015/08/13 10:38:25 flush 88700 points in 33.253s
[http] 2015/08/13 10:38:26 ::1 - - [13/Aug/2015:10:38:23 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6c39e2e6-41a7-11e5-b4aa-000000000000 2.666516615s
[http] 2015/08/13 10:38:26 ::1 - - [13/Aug/2015:10:38:26 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6dd758d9-41a7-11e5-b4ab-000000000000 682.503952ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e44efc0-41a7-11e5-b4ac-000000000000 87.540081ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e5ab120-41a7-11e5-b4ad-000000000000 125.655127ms
[http] 2015/08/13 10:38:27 ::1 - - [13/Aug/2015:10:38:27 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 6e75935d-41a7-11e5-b4ae-000000000000 101.985689ms
```

Second, at some point the server mysteriously died.

I've ruled out the disk being full - it still has plenty of space, and the size of the database is currently 4.9 GB.

I was feeding it approximately 100M datapoints just as fast as it could consume them. I was feeding them via the HTTP interface, in batches of 1000-1100 datapoints per post.

The test started at 7:08 GMT and ended at 10:39 GMT, and in that time there were 56898 posts, of which 56607 were successful, 40 returned status code 400, and 251 returned status code 500. It's also interesting to note that the first status code 500 occurred at 08:24 GMT, over an hour into the test. If it helps, here's the list of times for 500 responses. They definitely seemed to be more frequent further into the test.

\<snip\> (they are available in https://github.com/influxdb/influxdb.com/issues/222 if needed)

Please let me know if there's any other information you need to help troubleshoot this. I'll leave everything as it was the moment it crashed in case you need me to do any diagnostics.

**Comment by beckettsean** [comment]
@ianflint Were you running any queries when the db crashed? Is there a panic in the logs? Please include the log statements from right before the process died.

What happens when you relaunch the process?

**Comment by ianflint** [comment]
I was not running any queries (I was thankfully asleep since it was 3 AM :))
I didn't see any kind of panic in /var/log/influxdb/influxd.log - everything just stopped.
Here's the last 10 lines of the log:

[http] 2015/08/13 10:39:10 ::1 - - [13/Aug/2015:10:39:10 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 8835a5a3-41a7-11e5-b538-000000000000 89.86584ms
[http] 2015/08/13 10:39:10 ::1 - - [13/Aug/2015:10:39:10 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 88488175-41a7-11e5-b539-000000000000 154.530764ms
[http] 2015/08/13 10:39:11 ::1 - - [13/Aug/2015:10:39:10 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 886a030c-41a7-11e5-b53a-000000000000 133.933748ms
[http] 2015/08/13 10:39:11 ::1 - - [13/Aug/2015:10:39:11 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 88846fd5-41a7-11e5-b53b-000000000000 320.085825ms
[http] 2015/08/13 10:39:11 ::1 - - [13/Aug/2015:10:39:11 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 88d185f9-41a7-11e5-b53c-000000000000 400.950888ms
[http] 2015/08/13 10:39:12 ::1 - - [13/Aug/2015:10:39:12 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 892352d4-41a7-11e5-b53d-000000000000 241.298776ms
[http] 2015/08/13 10:39:13 ::1 - - [13/Aug/2015:10:39:12 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 896385e8-41a7-11e5-b53e-000000000000 478.499674ms
[http] 2015/08/13 10:39:13 ::1 - - [13/Aug/2015:10:39:13 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 89db30f8-41a7-11e5-b53f-000000000000 579.933269ms
[http] 2015/08/13 10:39:14 ::1 - - [13/Aug/2015:10:39:14 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 8a5ecfa4-41a7-11e5-b540-000000000000 620.99765ms
[http] 2015/08/13 10:39:16 ::1 - - [13/Aug/2015:10:39:15 +0000] POST /write?db=net_test HTTP/1.1 204 0 - - 8b070088-41a7-11e5-b541-000000000000 837.673585ms

I looked at the last 100 lines, and there were some flushes.  Here are the last 20 flushes.  I'm not sure if it's interesting that the flushes are of such different sizes.
[shard] 2015/08/13 10:31:39 flush 8810 points in 1.248s
[shard] 2015/08/13 10:31:42 flush 6416 points in 0.941s
[shard] 2015/08/13 10:31:45 flush 7313 points in 0.843s
[shard] 2015/08/13 10:31:47 flush 8993 points in 0.617s
[shard] 2015/08/13 10:34:47 flush 90116 points in 29.124s
[shard] 2015/08/13 10:35:27 flush 87611 points in 38.036s
[shard] 2015/08/13 10:35:57 flush 88769 points in 27.858s
[shard] 2015/08/13 10:36:31 flush 86382 points in 31.309s
[shard] 2015/08/13 10:36:53 flush 84889 points in 20.167s
[shard] 2015/08/13 10:37:22 flush 85194 points in 26.988s
[shard] 2015/08/13 10:37:50 flush 89898 points in 25.217s
[shard] 2015/08/13 10:38:25 flush 88700 points in 33.253s
[shard] 2015/08/13 10:38:29 flush 10006 points in 1.926s
[shard] 2015/08/13 10:38:33 flush 11658 points in 1.455s
[shard] 2015/08/13 10:38:36 flush 9093 points in 0.958s
[shard] 2015/08/13 10:38:39 flush 9642 points in 1.279s
[shard] 2015/08/13 10:38:42 flush 10013 points in 1.027s
[shard] 2015/08/13 10:38:46 flush 8639 points in 1.789s
[shard] 2015/08/13 10:38:49 flush 9469 points in 0.935s
[shard] 2015/08/13 10:38:51 flush 9366 points in 0.548s

Also, FWIW the data cardinality for the data I was trying to insert is 1.7M.  Since it got a little more than halfway through, I suspect the actual key cardinality in the database is around 1M.

Now the test - to restart the server.  And ...

Starting the process influxd [ OK ]
influxd process failed to start [ FAILED ]

Here's what showed up in influxd.log:

[metastore] 2015/08/13 19:14:35 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/13 19:14:35 read local node id: 1
[metastore] 2015/08/13 19:14:36 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/13 19:14:36 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/13 19:14:36 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/13 19:14:36 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/13 19:14:36 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/13 19:14:36 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/13 19:14:37 [INFO] raft: Disabling EnableSingleNode (bootstrap)
[metastore] 2015/08/13 19:14:37 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/13 19:14:37 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]

**Comment by ianflint** [comment]
It looks like influx started, but got wedged - I couldn't connect to it with /opt/influxdb/influx.  I increased the heartbeat timeout to 10s and bounced it, but it still came up wedged.  Any other ideas?

**Comment by ianflint** [comment]
Tried 100s heartbeat timeout.  Still nojoy.

**Comment by beckettsean** [comment]
Looks like there might be a raft consensus issue, even though it's a cluster of one node. That's beyond my ability to debug. @otoolep or @benbjohnson any thoughts on why this server won't stay up?

**Comment by jwilder** [comment]
Does not look like a raft issue from the log snippet.  The node became the leader which is what it should do.  What is you data size on disk?  It may be taking a long time to initialize the shards so the HTTP listener will not come up until that completes.

**Comment by ianflint** [comment]
Data size on disk is 4.9GB
On the second go-round, the process died as soon as it was launched.  I'll try again.

**Comment by ianflint** [comment]
It's running now, but I still can't connect.  I'll give it a few minutes to get its feet under it and try again.

**Comment by ianflint** [comment]
It's now up and accepting connections.

So the question is why it crashed in the first place.  Any ideas?  Is there anything you'd like me to look at?

**Comment by jwilder** [comment]
If the process crashed or paniced, there should be something in the influxdb log.  If the OS killed the process (perhaps linux OOM killer), there should be something in syslog `/var/log/syslog` that might provide some hints to the problem.

**Comment by ianflint** [comment]
There it is!

Aug 13 10:39:19 raisedamazed kernel: Out of memory: Kill process 2339 (influxd) score 940 or sacrifice child
Aug 13 10:39:19 raisedamazed kernel: Killed process 2339, UID 498, (influxd) total-vm:9412756kB, anon-rss:3796636kB, file-rss:156kB

So is there a way to limit the memory footprint of the process?  Or do I just need a box with more memory?

**Comment by jwilder** [comment]
There is no way to limit how much memory influxd uses right now.  You will need a box with more RAM.

**Comment by pauldix** [comment]
This might be due to the in memory cache of the write ahead log. The next release (0.9.3) next week will give you some controls to limit how much memory it uses.

**Comment by pauldix** [comment]
Do you know how many unique series you have? A unique series is the measurement + tag set. If it's > 1m you'll definitely need more memory since we keep an in memory inverted index of the measurements and tags

**Comment by ianflint** [comment]
My hope was to push about 100x this much data into influx, so what would be the memory footprint for a database of 500GB?

**Comment by ianflint** [comment]
To answer your other question, cardinality will be about 5 million.

**Comment by beckettsean** [comment]
@ianflint the memory footprint is a function of the number of unique series, not the number or size of points stored. 

You say the eventual cardinality will be about 5 million, what is it now?

**Comment by ianflint** [comment]
About 1M (based on when it crashed)
- Ian
 


     On Thursday, August 13, 2015 3:24 PM, Sean Beckett <notifications@github.com> wrote:
   

 @ianflint the memory footprint is a function of the number of unique series, not the number or size of points stored. You say the eventual cardinality will be about 5 million, what is it now?—

**Comment by ianflint** [comment]
The reason it's so high compared to the data volume is that I was only loading the first hour out of 24.
- Ian

**Comment by beckettsean** [comment]
With 1 MM unique series, 4GB is insufficient RAM. I can't say for sure what would be required, but try bumping to 8GB or better 16GB, if you plan to push in 5 MM unique series. We should be publishing recommended server configurations with the 0.9.4 release.
