### ISSUE TITLE
Performance implications of different tag-set/series per entries?

### ISSUE THREAD

**Issue by eliperelman** [influxdb/influxdb#3645]
As I found out in https://github.com/influxdb/influxdb.com/issues/220 (sorry for posting to the wrong repo!) I cannot key records together using `time` as inserting many records with the same `time` will cause updates instead of creates. The reason I had records with shared `time` fields was so that my test metrics would always aggregate together in the Grafana UI, which groups by time.

So instead, I'll be inserting a new field/tag which I can use key test run metrics together, but from what I understand, this would need to be a tag in order to be used in `group by`. If every 30 rows produced a separate tag-set/series, would I eventually run into performance problems with all the series? I would put this key into the fields, but I am unsure about using fields in `group by`.

**Comment by eliperelman** [comment]
Closing as this idea does not resolve the problem.

**Comment by eliperelman** [comment]
For anyone running across this in the future, I forced creates to happen by utilizing the `time` field to encode 2 values: the epoch time of the record as I normally would, and then using the remaining digits as a unique identifier for the record. This can happen because I write the records using the nanosecond precision.

Example:

```js
var padId = function(id) {
  return ('000000' + id).substr(id.toString().length);
};

var time = Date.now() + padId(25) // 1439562982972000025: epoch: 1439562982972, id: 000025
```

This forces creates to be written in InfluxDB, while still allow records to easily aggregate together in Grafana as the record are all within 1ms of each other.

**Comment by otoolep** [comment]
@eliperelman -- this is an effective way to do what you want, and should continue to work with all future releases of InfluxDB. The nanosecond-precision timestamps help.
