### ISSUE TITLE
Import should have an argument to limit insertion rate

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3648]
Since people are often going to be importing into an 0.9 instance that is actually hot for writes, they should be able to limit their insertion rate. Should be some number of points/sec.

**Comment by beckettsean** [comment]
@corylanou did this make it into 0.9.3?

**Comment by corylanou** [comment]
yes: https://github.com/influxdb/influxdb/blob/master/importer/README.md#throttiling-the-import
