### ISSUE TITLE
Continuous queries should be able to output to foreign databases

### ISSUE THREAD

**Issue by comcomservices** [influxdb/influxdb#3649]
It would be nice to keep one copy of sensor data with a 1 month retention policy and another down sampled copy with INF retention.

Since retention policies are attached to databases, it makes sense that the output of a continuous query should be able to feed into another database with another retention policy

**Comment by beckettsean** [comment]
This is already possible. In the INTO clause, simply provide the full "[db.rp.measurement](https://influxdb.com/docs/v0.9/query_language/data_exploration.html#selecting-the-database-and-retention-period)" syntax. For example, to write from database `mydb` into database `foo` and retention policy `bar`, the CQ statement would be

```
CREATE CONTINUOUS QUERY events_10m ON mydb BEGIN
  SELECT COUNT(type) INTO foo.bar.event_count_10m FROM events GROUP BY time(10m)
END
```

**Comment by comcomservices** [comment]
Thanks! What was confusing is that it would not work with the "default" retention policy name.. Had to create another one otherwise I got this error

error parsing query: found DEFAULT, expected identifier at line 1, char 89

**Comment by beckettsean** [comment]
Ahh, gotcha. So

`SELECT COUNT(type) INTO foo.default.event_count_10m FROM ...` was failing with that warning? That's a parser error, but there is a workaround. You can omit the RP name if using default. For example:

`SELECT COUNT(type) INTO foo..event_count_10m FROM ...` will write to database `foo` in the default retention policy, regardless of the identifier for that default policy.

**Comment by comcomservices** [comment]
yeah, that's correct.. Thanks for the workaround @beckettsean
