### ISSUE TITLE
continuous query scalability on v 0.8.8

### ISSUE THREAD

**Issue by sidcisco** [influxdb/influxdb#3657]
Are there any scalability numbers available for the number of continuous queries that can be run every minute ? For my use case I am having to run continuous queries once every minute. With that frequency I am able to do about 200 continuous queries every minute. If I go higher than 200, its taking more than a minute to complete each round of continuous queries. I have a VM with 4 core and 8G of RAM. It dint look like there was a CPU churn as CPU was still idle on few cores, reaching about 100% in only one or two cores. Also there was no I/O wait cycles as well. Does 200 continuous queries per minute sound about right ? Can I expect a better performance in v 0.9 and if so by what magnitude ?

**Comment by beckettsean** [comment]
@sidcisco this is a more appropriate question for the [Google Group](mailto:influxdb@googlegroups.com), especially as it pertains to 0.8, which is no longer under development.

For 0.9, the feasible number of CQs depends entirely on your data and the specifics of the queries. There are no built-in limits of which I'm aware.
