### ISSUE TITLE
MAX MEAN SUM MIN return incorrect value

### ISSUE THREAD

**Issue by chenchaogao** [influxdb/influxdb#3658]
my measurement value blow 1 but not equal 0, the max and sum min will return 0. Maybe it's not right!

```
> select value from loadavg where category='load_1' and time > now() - 3m
name: loadavg
-------------
time                    value
2015-08-14T08:39:49Z    0.00
2015-08-14T08:40:49Z    0.04
2015-08-14T08:41:49Z    0.01

> select mean(value) from loadavg where category='load_1' and time > now() - 3m
name: loadavg
-------------
time                            mean
2015-08-14T08:39:28.239614148Z  0

```

**Comment by mjdesa** [comment]
@chenchaogao what version of Influx are you running?

**Comment by mjdesa** [comment]
Why I try the same queries in 0.9.3 I get the following

```
> insert loadavg value=0.00
> insert loadavg value=0.04
> insert loadavg value=0.01
> select mean(value) from loadavg
name: loadavg
-------------
time			mean
1970-01-01T00:00:00Z	0.016666666666666666

> select max(value) from loadavg
name: loadavg
-------------
time			max
1970-01-01T00:00:00Z	0.04

> select min(value) from loadavg
name: loadavg
-------------
time			min
1970-01-01T00:00:00Z	0
```

**Comment by beckettsean** [comment]
@chenchaogao can you share an example of the points you write? It's most likely that you've written the values as strings, not numbers. If you are using the line protocol you must not double-quote numeric values in fields.

**Comment by gaochenchao** [comment]
Thanks, I wrote the points values as string. when i change the data type to float, it's work.
I think it's better give a warning when people use mean on a value of string. Thanks again.
