### ISSUE TITLE
[0.9.2] Panic: slice bounds out of range (tsdb/shard.go:959)

### ISSUE THREAD

**Issue by consense** [influxdb/influxdb#3659]
Seeing the following panic in influx 0.9.2

    [http] 2015/08/14 08:48:27 127.0.0.1 - user_username [14/Aug/2015:08:48:27 +0200] POST /write?db=databasename HTTP/1.1 204 0 - - 7785f1fc-4250-11e5-8904-000000000000 1.501138ms
    panic: runtime error: slice bounds out of range
    
    goroutine 59817 [running]:
    github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFields(0xc208f7f5b0, 0x7f646aea12b6, 0x3b, 0x7fffffff, 0x7fffffff, 0x0, 0x0)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:959 +0x78b
    github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeFieldsWithNames(0xc208f7f5b0, 0x7f646aea12b6, 0x3b, 0x7fffffff, 0x7fffffff, 0x0, 0x0)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:974 +0x72
    github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc20a62cbd0, 0x11bb3e19d77c0000, 0x11bb8cae68bbbdc0, 0xc2099d4420, 0x6, 0x6, 0xc208d85990, 0x1, 0x1, 0x11bb55052c886000, ...)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:570 +0x1a1
    github.com/influxdb/influxdb/tsdb.(*RawMapper).NextChunk(0xc2095fc0b0, 0x0, 0x0, 0x0, 0x0)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:169 +0x139
    github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc20925ccc0, 0x0, 0x0, 0x0)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:54 +0x5c
    github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc208b95770, 0xc2099d43c0)
    	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:125 +0x1012
    created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
    	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:93 +0x5a

full stacktrace here: https://gist.github.com/consense/693af492ef9cf9faa68a

This occurs during our automated integration tests (resulting in ~500 writes, 200 selects into influx). Not reproducable on each run of the test suite (happens roughly every 10th run) and not always occuring at the same point during the test run.

Gladly suggest a way to make this more reproducable for you, but currently I wouldnt be able to provide a simple curl example resulting in the above panic.

**Comment by beckettsean** [comment]
@consense Do your tests operate on the same databases and measurements every time? Are you running them repeatedly against the same running InfluxDB cluster without restarts in between? We've seen some other issues where the churn from dropping a database, recreating it, writing to it, and then repeating the cycle soon and often can eventually lead to issues. It's perfectly reasonable integration test behavior, but it's somewhat pathological for the actual use case of InfluxDB. We're still tracking down all the related issues, but many have been mitigated in 0.9.3, which will be out next week.

**Comment by consense** [comment]
Thanks @beckettsean

Yes, situation is basically as you already guess: we scaffold/teardown in rapid succession (only difference being that we are using DROP MEASUREMENT, not DROP DATABASE in between tests. DELETE FROM SERIES was even more unstable to use in v0.8 at least so we switched to DROP MEASUREMENT).

In that case closing the issue and will reopen if the problem persists in 0.9.3

**Comment by ymettier** [comment]
Hello,

Me too.
0.9.2 from rpm.
Similar context.

Regards,
Yves
