### ISSUE TITLE
Influx 0.9.2 is not capable of handling fields like 0_foo

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdb/influxdb#3660]
During tests, I created a measurement with fields named like 0_foo, 1_foo...
While the data are correctly saved, doing a 
```
SELECT * FROM bar
```
fails with `found _foo, expected FROM at line 1, char 10`.

Doing foo_0 does not crash.

The interpreter should either accept the form 0_foo, or reject the user input at write time, claiming that fields must start with a non-digit character, like some programming languages do.

**Comment by jeremyVignelles** [comment]
Afterwards, the application crashed when trying to make a query, but I don't know if this is related.
Here are the logs: 
http://pastebin.com/KjB9MhyJ

This is the full log since influxdb was set up this morning with default config. All operations are related to this measurement.

before [14/Aug/2015:14:10:07 +0000] : trying to send data with 0_foo,0_bar,1_foo,1_bar... (number ranges from 0 to 18). After this point, field names were flipped.

**Comment by DanielMorsing** [comment]
The problem with queries failing on `select *` should be fixed on the nightly build. Could you try out that version and see if it works?

**Comment by mjdesa** [comment]
@jeremyVignelles Closing issue as it seems to be resolved in 0.9.3

``> insert bar 0_foo=1,1_foo=1
> select * from bar
name: bar
---------
time				0_foo	1_foo
2015-08-19T23:49:39.521320959Z	1	1
```

**Comment by jeremyVignelles** [comment]
Thanks for your replies. Tested in 0.9.3-rc1 and it worked.
