### ISSUE TITLE
Compilation failed on current master

### ISSUE THREAD

**Issue by papylhomme** [influxdb/influxdb#3684]
When I try to install influxdb the compilation fails with

    cmd/influxd/run/command.go:78: constant 10000000000 overflows int

I'm trying this on a RaspberryPI (arm)

**Comment by mvadu** [comment]
Same here.. I was about to create a new issue. On Pi 2

    Linux raspberrypi 4.0.7-v7+ #801 SMP PREEMPT Tue Jun 30 18:38:23 BST 2015 armv7l GNU/Linux

**Comment by otoolep** [comment]
@DanielMorsing

**Comment by papylhomme** [comment]
Commit ac8bf75f01d5727b7c08a0fabc38119d82fb87cf seems to fix this, but given the message log it looks more like a side effect than an intended fix ;)

**Comment by beckettsean** [comment]
closed by #3694

**Comment by mvadu** [comment]
Awesome, that was a very quick turnaround time. I can confirm its working in my Pi-2.
