### ISSUE TITLE
Query Template for SHOW RETENTION POLICES broken in 0.9.2

### ISSUE THREAD

**Issue by timgriffiths** [influxdb/influxdb#3685]
Looks like #2761 has added "ON" into the query, web admin template querys just needs to be updated. to reflect this change

![image](https://cloud.githubusercontent.com/assets/4284863/9295768/1f346bc6-44bd-11e5-9a5c-8c2bd8b23a76.png)

**Comment by gunnaraasen** [comment]
This has already been fixed by https://github.com/influxdb/influxdb/pull/3438 and will be in 0.9.3.
