### ISSUE TITLE
SSL Changes

### ISSUE THREAD

**Issue by DaveBlooman** [influxdb/influxdb#3688]
The UI changes in 0.9.2 mean that you can't select the SSL option as previously.

We currently use EC2 with a ELB, we terminate SSL on the instance and proxy traffic to localhost:8083 and 8086 for front end and API.  With the old way of working, the request for API calls would be made from an HTTPS address, but now the request to InfluxDB API is made to HTTP, so mixed content violations occur.  

Is there an option in the UI to allow a forced connection over SSL in the UI, or at least a feature to add it back in?

**Comment by DaveBlooman** [comment]
So I now see that there is a panel for SSL like the older UI, but oddly with the same options I get a method not allowed

![screenshot-2015-08-17-20 36 00](https://cloud.githubusercontent.com/assets/1492067/9314308/03c73d56-4520-11e5-893b-d6e78bd557f6.jpg)

**Comment by gunnaraasen** [comment]
This method not allowed error was fixed by a minor-minor 0.9.2.1 release. See issue https://github.com/influxdb/influxdb/issues/3222 for more info. It will also be fixed in 0.9.3 when it is released later this week.

Happy to reopen this issue if that does not resolve the issue.

**Comment by DaveBlooman** [comment]
Thanks
