### ISSUE TITLE
Field type conflict when indicating retention policy in query

### ISSUE THREAD

**Issue by simcap** [influxdb/influxdb#3690]
I created successfully a new DB with a retention policy by doing:

`CREATE DATABASE serverload`
`CREATE RETENTION POLICY fivedays ON serverload DURATION 5d REPLICATION 1 DEFAULT`

When doing the following curl:

`curl -i -XPOST 'http://mymachine:8086/write?consistency=&db=serverload&rp=default' --data-binary "load,env=production value=0.04"`

I get a 400 Bad Request with error message `write failed: field type conflict: input field "value" on measurement "load" is type float64, already exists as type string`

When removing from the query string the element (and only this one) `rp=default` to get the following curl:

`curl -i -XPOST 'http://mymachine:8086/write?consistency=&db=serverload' --data-binary "load,env=production value=0.04"`

... it works and goes through responding with a HTTP/1.1 204 No Content. I can then see it was persisted doing in my browser the request `http://mymachine:8086/query?q=select+value+from+load&db=serverload`. I get the response: 
```json
{"results":[{"series":[{"name":"load","columns":["time","value"],"values":[["2015-08-17T13:51:19.94391978Z",0.04]]}]}]}
```

I am only using curl to debug as I had this issue with the official Go client

**Comment by beckettsean** [comment]
@simcap this `curl` statement: `curl -i -XPOST 'http://mymachine:8086/write?consistency=&db=serverload&rp=default'...` says "please write this point to the `default` retention policy", meaning the original RP created with the database that is named `default`. 

To write to the `fivedays` RP, your query string should be: `curl -i -XPOST 'http://mymachine:8086/write?consistency=&db=serverload&rp=fivedays'...`

**Comment by beckettsean** [comment]
When you remove the explicit RP declaration from they query string, it writes to the retention policy that is set to be the default, which is `fivedays`.

**Comment by simcap** [comment]
Ok. Thanks a lot for the explanation. 

But why would it fails if for the `default` retention policy? It is actually set in the request - by the official Go influxDB client - when no retention is given. Shouldn't the write work with any retention policy?

**Comment by simcap** [comment]
Sorry @beckettsean, I misunderstood what you meant. It is all clear now. Thanks.
