### ISSUE TITLE
When is 0.9.3 version of influxdb going to be released?

### ISSUE THREAD

**Issue by chaithrar** [influxdb/influxdb#3692]
Hi,

Would like to when would be next release for 0.9.3.

Thanks and Regards

**Comment by mjdesa** [comment]
@chaithrar 0.9.3 should be released this friday.

**Comment by beckettsean** [comment]
@chaithrar This is neither a feature request nor a bug. Please ask questions like this on the [mailing list](mailto:influxdb@googlegroups.com) rather than opening a GitHub Issue.
