### ISSUE TITLE
[0.9.2] group by value crashes database

### ISSUE THREAD

**Issue by sphadley** [influxdb/influxdb#3695]
The query **select from "series_name" group by value**

 consistently crashes the influxdb 0.9.2 database on CentOS 6.6. The output of the log file looks like this for the last operation:

goroutine 604 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc208093800, 0x0, 0xc20820a0c0, 0xc2081080c0, 0x2710, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:282 +0x149
github.com/influxdb/influxdb/tsdb.func·006()
        /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:146 +0x6bd
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:196 +0x1f5

![influx_error](https://cloud.githubusercontent.com/assets/7024807/9311411/8f877b34-44db-11e5-85d9-a8afbfcd501a.png)

This is on a single server without a cluster.
Thanks,
Steven

**Comment by otoolep** [comment]
@sphadley -- it should not panic, but please be aware that GROUP BY a field is not valid.

**Comment by sphadley** [comment]
@otoolep Thank you for your quick response,

We assumed it was not valid after seeing the results. We are considering opening up our influxdb instance to a much wider audience soon, and we are concerned that new users learning the query language will bring down our database.  Any help making panics harder to induce is much appreciated. 

Thanks,
Steven

**Comment by otoolep** [comment]
@sphadley - can paste the entire panic trace? Gist is fine.

**Comment by sphadley** [comment]
What Log file would that be in?

**Comment by otoolep** [comment]
https://influxdb.com/docs/v0.9/administration/logs.html

**Comment by otoolep** [comment]
It would be directed to wherever STDERR is going.

**Comment by sphadley** [comment]
panic: interface conversion: interface is int64, not map[string]interface {}
8030
8031 goroutine 53 [running]:
8032 github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc208030aa0, 0xc20822e000, 0x1, 0x2710, 0x0)
8033         /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:758 +0xc63
8034 github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc208030aa0)
8035         /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:693 +0xba
8036 github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc208138a80, 0xc208194240)
8037         /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:160 +0xfdc
8038 created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
8039         /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:93 +0x5a
8040
8041 goroutine 1 [chan receive, 175 minutes]:
8042 main.(*Main).Run(0xc20808fa80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
8043         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x73b
8044 main.main()
8045         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc
8046
8047 goroutine 6 [syscall, 175 minutes]:
8048 os/signal.loop()
8049         /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
8050 created by os/signal.init·1
8051         /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35
8052
8053 goroutine 17 [syscall, 175 minutes, locked to thread]:
8054 runtime.goexit()
8055         /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1
8056
8057 goroutine 8 [IO wait, 175 minutes]:
8058 net.(*pollDesc).Wait(0xc20809c290, 0x72, 0x0, 0x0)
8059         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
8060 net.(*pollDesc).WaitRead(0xc20809c290, 0x0, 0x0)
8061         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
8062 net.(*netFD).accept(0xc20809c230, 0x0, 0x7f70f77b8cc8, 0xc2080f8000)
8063         /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
8064 net.(*TCPListener).AcceptTCP(0xc208038dd0, 0x0, 0x0, 0x0)
8065         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
8066 net.(*TCPListener).Accept(0xc208038dd0, 0x0, 0x0, 0x0, 0x0)
8067         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
8068 github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080c1cb0, 0x7f70f77bb208, 0xc208038dd0, 0x0, 0x0)
8069         /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
8070 created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
8071         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:298 +0x7a8
8072
8073 goroutine 9 [chan receive, 175 minutes]:
8074 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038dd8, 0x0, 0x0, 0x0, 0x0)
8075         /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
8076 github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080c1ce0, 0x0, 0x0, 0x0, 0x0)
8077         /root/go/src/github.com/influxdb/influxdb/meta/store.go:1855 +0x64
8078 github.com/hashicorp/raft.(*NetworkTransport).listen(0xc20809c310)
8079         /root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
8080 created by github.com/hashicorp/raft.NewNetworkTransport
8081         /root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4
8082
8083 goroutine 10 [select]:
8084 github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080be1c0)
8085         /root/go/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
8086 github.com/hashicorp/raft.(*Raft).runLeader(0xc2080be1c0)
8087         /root/go/src/github.com/hashicorp/raft/raft.go:779 +0x74e
8088 github.com/hashicorp/raft.(*Raft).run(0xc2080be1c0)
8089         /root/go/src/github.com/hashicorp/raft/raft.go:576 +0xc9
8090 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
8091         /root/go/src/github.com/hashicorp/raft/raft.go:241 +0x27
8092 github.com/hashicorp/raft.func·011()
8093         /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
8094 created by github.com/hashicorp/raft.(*raftState).goFunc
8095         /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
8096
8097 goroutine 11 [select, 3 minutes]:
8098 github.com/hashicorp/raft.(*Raft).runFSM(0xc2080be1c0)
8099         /root/go/src/github.com/hashicorp/raft/raft.go:490 +0xf74
8100 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
8101         /root/go/src/github.com/hashicorp/raft/raft.go:242 +0x27
8102 github.com/hashicorp/raft.func·011()
8103         /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
8104 created by github.com/hashicorp/raft.(*raftState).goFunc
8105         /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
8106
8107 goroutine 12 [select, 1 minutes]:
8108 github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080be1c0)
8109         /root/go/src/github.com/hashicorp/raft/raft.go:1594 +0x466
8110 github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
8111         /root/go/src/github.com/hashicorp/raft/raft.go:243 +0x27
8112 github.com/hashicorp/raft.func·011()
8113         /root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
8114 created by github.com/hashicorp/raft.(*raftState).goFunc
8115         /root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3
8116
8117 goroutine 14 [chan receive, 175 minutes]:
8118 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038de0, 0x0, 0x0, 0x0, 0x0)
8119         /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
8120 github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208070140)
8121         /root/go/src/github.com/influxdb/influxdb/meta/store.go:470 +0x8f
8122 created by github.com/influxdb/influxdb/meta.(*Store).Open
8123         /root/go/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2
8124
8125 goroutine 15 [select, 175 minutes]:
8126 github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080aa0e0, 0xc208044540)
8127         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:421 +0x14a
8128 created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
8129         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:304 +0x919
8130
8131 goroutine 16 [select, 1 minutes]:
8132 github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc20802e0b0, 0xc2080455c0)
8133         /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
8134 created by github.com/influxdb/influxdb/tsdb.func·010
8135         /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611
8136
8137 goroutine 18 [select, 3 minutes]:
8138 github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc20802e160, 0xc20811c1e0)
8139         /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
8140 created by github.com/influxdb/influxdb/tsdb.func·010
8141         /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611
8142
8143 goroutine 19 [select]:
8144 github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc208031220)
8145         /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
8146 created by github.com/influxdb/influxdb/services/hh.(*Service).Open
8147         /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef
8148
8149 goroutine 20 [select, 55 minutes]:
8150 github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc208031220)
8151         /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
8152 created by github.com/influxdb/influxdb/services/hh.(*Service).Open
8153         /root/go/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109
8154
8155 goroutine 21 [chan receive, 175 minutes]:
8156 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038de8, 0x0, 0x0, 0x0, 0x0)
8157         /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
8158 github.com/influxdb/influxdb/cluster.(*Service).serve(0xc20809c150)
8159         /root/go/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
8160 created by github.com/influxdb/influxdb/cluster.(*Service).Open
8161         /root/go/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67
8162
8163 goroutine 22 [select, 3 minutes]:
8164 github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc20800adc0)
8165         /root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
8166 created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
8167         /root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb
8168
8169 goroutine 23 [chan receive, 175 minutes]:
8170 github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038df0, 0x0, 0x0, 0x0, 0x0)
8171         /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
8172 github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc20800aeb0)
8173         /root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
8174 created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
8175         /root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62
8176
8177 goroutine 24 [IO wait, 175 minutes]:
8178 net.(*pollDesc).Wait(0xc20809c3e0, 0x72, 0x0, 0x0)
8179         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
8180 net.(*pollDesc).WaitRead(0xc20809c3e0, 0x0, 0x0)
8181         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
8182 net.(*netFD).accept(0xc20809c380, 0x0, 0x7f70f77b8cc8, 0xc2080dc190)
8183         /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
8184 net.(*TCPListener).AcceptTCP(0xc208038048, 0xc208120380, 0x0, 0x0)
8185         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
8186 net.(*TCPListener).Accept(0xc208038048, 0x0, 0x0, 0x0, 0x0)
8187         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
8188 net/http.(*Server).Serve(0xc208102060, 0x7f70f77bb208, 0xc208038048, 0x0, 0x0)
8189         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
8190 net/http.Serve(0x7f70f77bb208, 0xc208038048, 0x7f70f77bfae0, 0xc2080dc180, 0x0, 0x0)
8191         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
8192 github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc20800af50)
8193         /root/go/src/github.com/influxdb/influxdb/services/admin/service.go:105 +0x147
8194 created by github.com/influxdb/influxdb/services/admin.(*Service).Open
8195         /root/go/src/github.com/influxdb/influxdb/services/admin/service.go:68 +0x431
8196
8197 goroutine 25 [select]:
8198 github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc20809c1c0)
8199         /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:151 +0x301
8200 created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
1         /root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed
8202
8203 goroutine 26 [IO wait]:
8204 net.(*pollDesc).Wait(0xc20809c610, 0x72, 0x0, 0x0)
8205         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
8206 net.(*pollDesc).WaitRead(0xc20809c610, 0x0, 0x0)
8207         /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
8208 net.(*netFD).accept(0xc20809c5b0, 0x0, 0x7f70f77b8cc8, 0xc208028a10)
8209         /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
8210 net.(*TCPListener).AcceptTCP(0xc208038098, 0xc208143dc8, 0x0, 0x0)
8211         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
8212 net.(*TCPListener).Accept(0xc208038098, 0x0, 0x0, 0x0, 0x0)
8213         /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
8214 net/http.(*Server).Serve(0xc208044180, 0x7f70f77bb208, 0xc208038098, 0x0, 0x0)
8215         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
8216 net/http.Serve(0x7f70f77bb208, 0xc208038098, 0x7f70f77bfa90, 0xc2080acb80, 0x0, 0x0)
8217         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
8218 github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc20800b090)
8219         /root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:107 +0x79
8220 created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
8221         /root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:75 +0x590
8222
8223 goroutine 27 [select, 5 minutes]:
8224 github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc208044960)
8225         /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
8226 created by github.com/influxdb/influxdb/services/retention.(*Service).Open
8227         /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67
8228
8229 goroutine 28 [select, 5 minutes]:
8230 github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208044960)
8231         /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
8232 created by github.com/influxdb/influxdb/services/retention.(*Service).Open
8233         /root/go/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81
8234
8235 goroutine 29 [chan receive, 175 minutes]:
8236 github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc2080aa0e0)
8237         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x18e
8238 created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
8239         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:327 +0xdbe
8240
8241 goroutine 30 [select, 175 minutes]:
8242 github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc20800fc00)
8243         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:125 +0x2da
8244 created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
8245         /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:107 +0xbb4
8246
8247 goroutine 51 [chan receive]:
8248 github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc2080acb80, 0x7f70f77cf508, 0xc20811ec40, 0xc208168000, 0x0)
8249         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:268 +0xa44
8250 github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveQuery)·fm(0x7f70f77cf508, 0xc20811ec40, 0xc208168000, 0x0)
8251         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:95 +0x4f
8252 github.com/influxdb/influxdb/services/httpd.func·001(0x7f70f77cf508, 0xc20811ec40, 0xc208168000)
8253         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:696 +0x78
8254 net/http.HandlerFunc.ServeHTTP(0xc2080e01c0, 0x7f70f77cf508, 0xc20811ec40, 0xc208168000)
8255         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8256 github.com/influxdb/influxdb/services/httpd.func·002(0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8257         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:754 +0x288
8258 net/http.HandlerFunc.ServeHTTP(0xc2080dc920, 0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8259         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8260 github.com/influxdb/influxdb/services/httpd.func·003(0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8261         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:763 +0xba
8262 net/http.HandlerFunc.ServeHTTP(0xc2080e01e0, 0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8263         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8264 github.com/influxdb/influxdb/services/httpd.func·004(0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8265         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:796 +0x31a
8266 net/http.HandlerFunc.ServeHTTP(0xc2080dc950, 0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8267         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8268 github.com/influxdb/influxdb/services/httpd.func·005(0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8269         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:806 +0x179
8270 net/http.HandlerFunc.ServeHTTP(0xc2080dc970, 0x7f70f77cf430, 0xc20811eba0, 0xc208168000)
8271         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8272 github.com/influxdb/influxdb/services/httpd.func·006(0x7f70f77cf430, 0xc20811eb80, 0xc208168000)
8273         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:814 +0x123
8274 net/http.HandlerFunc.ServeHTTP(0xc2080e0200, 0x7f70f77cf430, 0xc20811eb80, 0xc208168000)
8275         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8276 github.com/influxdb/influxdb/services/httpd.func·007(0x7f70f77cf3f8, 0xc2080301e0, 0xc208168000)
8277         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:824 +0x12c
8278 net/http.HandlerFunc.ServeHTTP(0xc2080e0220, 0x7f70f77cf3f8, 0xc2080301e0, 0xc208168000)
8279         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
8280 github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038cd8, 0x7f70f77cf3f8, 0xc2080301e0, 0xc208168000)
8281         /root/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
8282 github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc2080acb80, 0x7f70f77cf3f8, 0xc2080301e0, 0xc208168000)
8283         /root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:175 +0x256
8284 net/http.serverHandler.ServeHTTP(0xc208044180, 0x7f70f77cf3f8, 0xc2080301e0, 0xc208168000)
8285         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
8286 net/http.(*conn).serve(0xc2080300a0)
8287         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
8288 created by net/http.(*Server).Serve
8289         /root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e
8290
8291 goroutine 52 [chan receive]:
8292 github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc20808f800, 0x0, 0xc20818c0c0, 0xc208074780, 0x2710, 0x0, 0x0)
8293         /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:282 +0x149
8294 github.com/influxdb/influxdb/tsdb.func·006()
8295         /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:146 +0x6bd
8296 created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
8297         /root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:196 +0x1f5

**Comment by sphadley** [comment]
@otoolep  is that better?

**Comment by otoolep** [comment]
Great, thanks @sphadley

**Comment by otoolep** [comment]
Can you provide example data that you write that causes this when queried? Really the system should respond with:

```
{
    "results": [
        {
            "error": "can not use field in GROUP BY clause: value"
        }
    ]
}
```

**Comment by sphadley** [comment]
Starting with the following dummy example dataset
![influx_error2](https://cloud.githubusercontent.com/assets/7024807/9318551/18379d28-450a-11e5-8dd0-23b5892ed26c.png)
We use the following query
![influx_error](https://cloud.githubusercontent.com/assets/7024807/9318554/21590ad6-450a-11e5-8d9d-409ef1afb8dc.png)
And boom it panics.

Please let me know if there is anything I can do to help you reproduce or any other log info, that I am missing.

Thanks,
Steven

**Comment by otoolep** [comment]
Can you show me the data being inserted please?

**Comment by beckettsean** [comment]
Confirming that in 0.9.2 that is an instant panic:

```
> use test
Using database test
> insert height value=6
> select * from height group by value
ERR: Get http://localhost:8086/query?db=test&q=select+%2A+from+height+group+by+value: EOF
```

Stack trace is the same

```
panic: interface conversion: interface is int64, not map[string]interface {}

goroutine 4287 [running]:
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc2080740a0, 0xc208492000, 0x1, 0x2710, 0x0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:758 +0xc63
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc2080740a0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:693 +0xba
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc208681e60, 0xc2082e0de0)
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:149 +0x2d7
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
        /private/tmp/influxdb20150724-51807-r65xyy/influxdb-0.9.2/src/github.com/influxdb/influxdb/tsdb/engine.go:93 +0x5a
```

**Comment by otoolep** [comment]
Master code:
```
> use test
Using database test
> insert height value=6
> select * from height group by value
ERR: can not use field in GROUP BY clause: value
> 
```

**Comment by otoolep** [comment]
@jwilder made some changes recently to address these issues. I believe he fixed them.

**Comment by otoolep** [comment]
@sphadley -- can you please download a nightly build and try again.

https://influxdb.com/download/index.html

**Comment by beckettsean** [comment]
Confirmed fixed in the nightly:

```
Connected to http://localhost:8086 version 0.9.3-nightly-1548f62
InfluxDB shell 0.9.3-nightly-1548f62
> use foo
Using database foo
> insert height value=6
> select * from height group by value
ERR: can not use field in GROUP BY clause: value
```

Database is still up and responsive.

**Comment by sphadley** [comment]
I can confirm also, this issue is not present in the nightly. Thank you!
