### ISSUE TITLE
Layout issues on Edge browser

### ISSUE THREAD

**Issue by mvadu** [influxdb/influxdb#3696]
Using Windwos 10 Edge browser, admin page layout is incorrect.
![image](https://cloud.githubusercontent.com/assets/8618235/9311621/f4fd69fc-4534-11e5-8ff9-08ef9f7c7b18.png)
This way you can not get to Databases page or create a new database.

**Comment by mjdesa** [comment]
@mvadu I dont think this is an error. To create a new database you issue a 

```
create database <name of database>
```

command in the query box.

**Comment by mvadu** [comment]
Oh.. okay, at work I created my first DB using Curl, and then visited the admin page. At home I visited the admin page first, and got confused. Thanks for that.

**Comment by mjdesa** [comment]
Anytime. Glad to hear things are working.
