### ISSUE TITLE
Tests failing on i386 and armhf

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb#3701]
Hello,

The tests are failing on i386 and armhf. For the same reason.

```
=== RUN TestConfig_Parse
--- PASS: TestConfig_Parse (0.00s)
[collectd] 2015/08/11 16:32:32 collectd UDP started
[collectd] 2015/08/11 16:32:32 collectd UDP closed
--- PASS: TestService_CreatesDatabase (0.01s)
[collectd] 2015/08/11 16:32:32 collectd UDP started
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x99284]

goroutine 17 [running]:
sync/atomic.addUint64(0x10764524, 0x1, 0x0, 0x1, 0x0)
	/usr/lib/go/src/sync/atomic/64bit_arm.go:31 +0x70
github.com/influxdb/influxdb/tsdb.func·002()
	/«BUILDDIR»/influxdb-0.9.2+dfsg1/obj-arm-linux-gnueabihf/src/github.com/influxdb/influxdb/tsdb/batcher.go:77 +0x1ec
created by github.com/influxdb/influxdb/tsdb.(*PointBatcher).Start
	/«BUILDDIR»/influxdb-0.9.2+dfsg1/obj-arm-linux-gnueabihf/src/github.com/influxdb/influxdb/tsdb/batcher.go:104 +0x2b8
```

Full logs are available here: https://buildd.debian.org/status/logs.php?pkg=influxdb&ver=0.9.2%2Bdfsg1-2
Related Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795640

Could that be related to https://github.com/influxdb/influxdb/issues/3213 ?

I'm happy to help however possible.

When this is fixed, we should enable those architectures on CircleCI. Those kind of issues are easier to fix when they are noticed early!

**Comment by otoolep** [comment]
The change for #3213 has gone in. Are you telling me you are still seeing issues, even with that change in place?

**Comment by aviau** [comment]
@otoolep yes,  this is with InfluxDB 9.2.1.

**Comment by otoolep** [comment]
OK, thanks @aviau -- right now we have no leads as to why this is failing. We had hoped it was an alignment issue, but it does not appear to if you are running with the latest code.

Copy @DanielMorsing who worked on this with me.

**Comment by aviau** [comment]
Wait.  Was this included in the 0.9.2 release?

**Comment by otoolep** [comment]
@aviau -- I asked if you were seeing the problem with the fix in place. I saw you responded "yes" and stopped there. :-)

The change is no in 0.9.2, but will be in 0.9.3.

**Comment by aviau** [comment]
@otoolep It works... almost!

I have one failing test:
```
# github.com/influxdb/influxdb/toml_test
src/github.com/influxdb/influxdb/toml/toml_test.go:29: constant 10737418240 overflows toml.Size
```

It looks like the skip code isn't working:
```toml/toml_test.go```:
```
func TestSize_UnmarshalText_GB(t *testing.T) {
        if typ := reflect.TypeOf(0); typ.Size() != 8 {
                t.Skip("large gigabyte parsing on 64-bit arch only")
        }
```

**Comment by aviau** [comment]
Looks like 
```
if strconv.IntSize != 64 {
```

Would work.

**Comment by otoolep** [comment]
Wouldn't a check of GOARCH be better?

https://golang.org/pkg/runtime

**Comment by aviau** [comment]
Actually, the build fails. So there is nothing to do at runtime hehe.

**Comment by otoolep** [comment]
Hmmm, right, @aviau

**Comment by aviau** [comment]
What about this?
```
From f81ba1c821d032772a0a6a31b0afd6d8f859ba29 Mon Sep 17 00:00:00 2001
From: Alexandre Viau <alexandre@alexandreviau.net>
Date: Mon, 17 Aug 2015 23:15:38 +0000
Subject: [PATCH] Disable 64bit tests properly

---
 toml/toml_test.go                       | 16 ----------------
 toml/toml_unmarshal_linux_amd64_test.go | 16 ++++++++++++++++
 2 files changed, 16 insertions(+), 16 deletions(-)
 create mode 100644 toml/toml_unmarshal_linux_amd64_test.go

diff --git a/toml/toml_test.go b/toml/toml_test.go
index 2890aa3..f3a4379 100644
--- a/toml/toml_test.go
+++ b/toml/toml_test.go
@@ -1,9 +1,7 @@
 package toml_test
 
 import (
-	"reflect"
 	"testing"
-
 	"github.com/influxdb/influxdb/toml"
 )
 
@@ -17,20 +15,6 @@ func TestSize_UnmarshalText_MB(t *testing.T) {
 	}
 }
 
-// Ensure that gigabyte sizes can be parsed.
-func TestSize_UnmarshalText_GB(t *testing.T) {
-	if typ := reflect.TypeOf(0); typ.Size() != 8 {
-		t.Skip("large gigabyte parsing on 64-bit arch only")
-	}
-
-	var s toml.Size
-	if err := s.UnmarshalText([]byte("10g")); err != nil {
-		t.Fatalf("unexpected error: %s", err)
-	} else if s != 10*(1<<30) {
-		t.Fatalf("unexpected size: %d", s)
-	}
-}
-
 /*
 func TestConfig_Encode(t *testing.T) {
 	var c influxdb.Config
diff --git a/toml/toml_unmarshal_linux_amd64_test.go b/toml/toml_unmarshal_linux_amd64_test.go
new file mode 100644
index 0000000..f81a104
--- /dev/null
+++ b/toml/toml_unmarshal_linux_amd64_test.go
@@ -0,0 +1,16 @@
+package toml_test
+
+import (
+        "testing"
+        "github.com/influxdb/influxdb/toml"
+)
+
+// Ensure that gigabyte sizes can be parsed.
+func TestSize_UnmarshalText_GB(t *testing.T) {
+        s := toml.Size
+        if err := s.UnmarshalText([]byte("10g")); err != nil {
+                t.Fatalf("unexpected error: %s", err)
+        } else if s != 10*(1<<30) {
+                t.Fatalf("unexpected size: %d", s)
+        }
+}
-- 
1.9.1
```

**Comment by otoolep** [comment]
How does this work? Filename-based?

**Comment by aviau** [comment]
Yeah.

See ``File Suffixes``: http://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

**Comment by otoolep** [comment]
Sweet, sounds like a great solution. Wanna generate a PR?

**Comment by aviau** [comment]
> Wanna generate a PR?

Yep. Right after I'm done testing

**Comment by otoolep** [comment]
Same as https://github.com/influxdb/influxdb/issues/3732

**Comment by aviau** [comment]
@otoolep 

I have just uploaded 0.9.2.1+dfsg1-1 to Debian.

Thanks to your help, we have [fixed](https://buildd.debian.org/status/package.php?p=influxdb) the InfluxDB build on i386 and armhf! InfluxDB will be available for these architectures on Debian in a couple hours. On Ubuntu, tomorrow.
