### ISSUE TITLE
[master] Retention policy not enforced ?

### ISSUE THREAD

**Issue by papylhomme** [influxdb/influxdb#3702]
Hello, I'm experiencing issues with retention not being enforced as I intented (maybe some misconfiguration ?)

Running on current master (deabf8d2a8e60e701c32302b569a1006ba378ee5)

I can see values older than the retention policy:

```
InfluxDB shell 0.9
> show retention policies on collectd
name    duration        replicaN        default
default 1h0m0s          1               true

> select value from cpu_value where host='danska' and time > now() - 48h limit 1
name: cpu_value
---------------
time                            value
2015-08-17T00:00:00.39513Z      0

> select value from cpu_value where host='danska' and time > now() - 1h limit 1
name: cpu_value
---------------
time                            value
2015-08-17T18:54:40.395196Z     0
```

But the policy is enforced somehow, it shows up in the logs:

```
[metastore] 2015/08/17 01:32:03 new shard group 2 successfully created for database collectd, retention policy default
[retention] 2015/08/17 01:32:04 retention policy shard deletion check commencing
[retention] 2015/08/17 01:32:04 retention policy enforcement check commencing
...
(multiple times between 01:32:04 and 03:02:04)
[retention] 2015/08/17 01:42:04 retention policy shard deletion check commencing
[retention] 2015/08/17 01:42:04 retention policy enforcement check commencing
...
[retention] 2015/08/17 03:02:04 retention policy shard deletion check commencing
[retention] 2015/08/17 03:02:04 retention policy enforcement check commencing
[retention] 2015/08/17 03:02:04 deleted shard group 1 from database collectd, retention policy default
...
[retention] 2015/08/17 03:12:04 retention policy shard deletion check commencing
[retention] 2015/08/17 03:12:04 retention policy enforcement check commencing
[retention] 2015/08/17 03:12:04 shard ID 1 deleted
...
```

I don't know if it bears any significance, but the records kept by the retention are all timestamped to *2015-08-17T00:00:00*

**Comment by otoolep** [comment]
How long are you waiting after writing the points before expecting retention enforcement to delete the data?

**Comment by papylhomme** [comment]
I was expecting the old data to be deleted at each pass of *retention policy enforcement check commencing*, so between 1h and 1h + retention.check-interval. Currently the oldest point is 24h old.

**Comment by otoolep** [comment]
The system performs retention checks every 10 minutes. If you have written data with a timestamp older than 1 hour ago, into a retention policy with a period of 1 hour, waited at least 10 minutes, and still see the data, I would say that there may be a bug.

Can you show us a sequence of commands (or curl commands ideally) that shows creation of the database and retention policy, writes a point (showing the timestamp), wait for the policy check to run, and show a SELECT query returning that point?

**Comment by papylhomme** [comment]
The suggested scenario is working:
```
[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE test_retention"
{"results":[{}]}

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "q=SHOW RETENTION POLICIES ON test_retention"
{"results":[{"series":[{"columns":["name","duration","replicaN","default"],"values":[["default","0",1,true]]}]}]}

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "q=ALTER RETENTION POLICY default ON test_retention DURATION 1h"
{"results":[{}]}[

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "q=SHOW RETENTION POLICIES ON test_retention"
{"results":[{"series":[{"columns":["name","duration","replicaN","default"],"values":[["default","1h0m0s",1,true]]}]}]}

[root@danska ~]# curl -i -X POST 'http://localhost:8086/write?db=test_retention' --data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'
HTTP/1.1 204 No Content
Request-Id: 9553d00d-459c-11e5-8231-000000000000
X-Influxdb-Version: 0.9
Date: Tue, 18 Aug 2015 11:30:52 GMT

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "db=test_retention" --data-urlencode "q=SELECT * FROM cpu_load_short"
{"results":[{"series":[{"name":"cpu_load_short","columns":["time","host","region","value"],"values":[["2015-06-11T20:46:02Z","server01","us-west",0.64]]}]}]}

[root@danska ~]# date
mar. août 18 13:32:38 CEST 2015

[root@danska ~]# curl -i -X POST 'http://localhost:8086/write?db=test_retention' --data-binary 'cpu_load_short,host=server01,region=us-west value=2'
HTTP/1.1 204 No Content
Request-Id: f55ec375-459c-11e5-8235-000000000000
X-Influxdb-Version: 0.9
Date: Tue, 18 Aug 2015 11:33:33 GMT

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "db=test_retention" --data-urlencode "q=SELECT * FROM cpu_load_short"
{"results":[{"series":[{"name":"cpu_load_short","columns":["time","host","region","value"],"values":[["2015-06-11T20:46:02Z","server01","us-west",0.64],["2015-08-18T11:33:33.851544066Z","server01","us-west",2]]}]}]}

[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "db=test_retention" --data-urlencode "q=SELECT * FROM cpu_load_short"
{"results":[{"series":[{"name":"cpu_load_short","columns":["time","host","region","value"],"values":[["2015-08-18T11:33:33.851544066Z","server01","us-west",2]]}]}]}
```

Associated logs:
```
[metastore] 2015/08/18 13:35:49 new shard group 5 successfully created for database test_retention, retention policy default
[retention] 2015/08/18 13:35:50 retention policy shard deletion check commencing
[retention] 2015/08/18 13:35:50 retention policy enforcement check commencing
[retention] 2015/08/18 13:35:50 deleted shard group 3 from database test_retention, retention policy default
[retention] 2015/08/18 13:35:50 deleted shard group 5 from database test_retention, retention policy default
```


Regarding my main database, I can see a difference with the test scenario: my points are being created with the current time (using collectd), not with a timestamp which is already old. In this case I have records 36 hours old.

I'll check in 1 hour if the second message inserted in the test_retention database has been removed or not.

**Comment by papylhomme** [comment]
The record inserted earlier in the test_retention db is still there, with an age > 80m:

```
[root@danska ~]# curl -G 'http://localhost:8086/query' --data-urlencode "db=test_retention" --data-urlencode "q=SELECT * FROM cpu_load_short where time < now() - 80m"
{"results":[{"series":[{"name":"cpu_load_short","columns":["time","host","region","value"],"values":[["2015-08-18T11:33:33.851544066Z","server01","us-west",2]]}]}]}
```

**Comment by beckettsean** [comment]
@papylhomme Are you running a single node or multi-node cluster?

**Comment by papylhomme** [comment]
It's a single node. I'm trying the test case on another platform just in case. 

From the look of it, I'm not sure it's a problem a policy enforcement: when there is multiple shard/shard group, records are being deleted, but somehow all my records seems to be in one shard/shard group and there is no new one created. I'm basing this assumption on the fact that there is only a single file in */var/lib/influxdb/data/collectd/default*, and also there is no log *new shard group x successfully created for database collectd, retention policy default*
 
Can you give me some hint to add some log in the source files ? I'm starting to look into it but I'm at lost regarding the relation between point insertion and shard creation.

**Comment by papylhomme** [comment]
It seems shard group duration is not updated when altering the retention policy, with a default of 1 week (604800000000000 nanoseconds).

Added log:

```
diff --git a/cluster/points_writer.go b/cluster/points_writer.go
index b5a7863..4816821 100644
--- a/cluster/points_writer.go
+++ b/cluster/points_writer.go
@@ -158,16 +158,21 @@ func (w *PointsWriter) MapShards(wp *WritePointsRequest) (*ShardMapping, error)
                return nil, err
        }
 
+  w.Logger.Printf("ShardGroupDuration is %d", rp.ShardGroupDuration)
+
        for _, p := range wp.Points {
                timeRanges[p.Time().Truncate(rp.ShardGroupDuration)] = nil
+    w.Logger.Printf("Truncating time to %s", p.Time().Truncate(rp.ShardGroupDuration).String())
        }
 
        // holds all the shard groups and shards that are required for writes
        for t := range timeRanges {
+    w.Logger.Printf("Requesting shard group for %s", t.String())
                sg, err := w.MetaStore.CreateShardGroupIfNotExists(wp.Database, wp.RetentionPolicy, t)
                if err != nil {
                        return nil, err
                }
+    w.Logger.Printf("Received shard group %d with start time %s end time %s", sg.ID, sg.StartTime.String(), sg.EndTime.String())
                timeRanges[t] = sg
        }
```

Scenario:
- create a database
- insert a point to display shard group duration on the logs
- alter the retention policy
- insert a new point to display shard group duration on the logs

Result:
```
[http] 2015/08/19 13:23:55 ::1 - - [19/Aug/2015:13:23:55 +0200] GET /query?q=CREATE%20DATABASE%20test_retention HTTP/1.1 200 16 - curl/7.43.0 c70f5451-4664-11e5-8001-000000000000 103.426514ms
[write] 2015/08/19 13:23:59 ShardGroupDuration is 604800000000000
[write] 2015/08/19 13:23:59 Truncating time to 2015-08-17 00:00:00 +0000 UTC
[write] 2015/08/19 13:23:59 Requesting shard group for 2015-08-17 00:00:00 +0000 UTC
[write] 2015/08/19 13:23:59 Received shard group 1 with start time 2015-08-17 00:00:00 +0000 UTC end time 2015-08-24 00:00:00 +0000 UTC
[http] 2015/08/19 13:23:59 ::1 - - [19/Aug/2015:13:23:59 +0200] POST /write?db=test_retention HTTP/1.1 204 0 - curl/7.43.0 c953906e-4664-11e5-8002-000000000000 256.519948ms
[http] 2015/08/19 13:24:09 ::1 - - [19/Aug/2015:13:24:09 +0200] GET /query?q=ALTER%20RETENTION%20POLICY%20default%20ON%20test_retention%20DURATION%201h HTTP/1.1 200 16 - curl/7.43.0 cf71664b-4664-11e5-8003-000000000000 53.118622ms
[write] 2015/08/19 13:24:15 ShardGroupDuration is 604800000000000
[write] 2015/08/19 13:24:15 Truncating time to 2015-06-08 02:00:00 +0200 CEST
[write] 2015/08/19 13:24:15 Requesting shard group for 2015-06-08 02:00:00 +0200 CEST
[write] 2015/08/19 13:24:15 Received shard group 2 with start time 2015-06-08 00:00:00 +0000 UTC end time 2015-06-15 00:00:00 +0000 UTC
[http] 2015/08/19 13:24:15 ::1 - - [19/Aug/2015:13:24:15 +0200] POST /write?db=test_retention HTTP/1.1 204 0 - curl/7.43.0 d2ea493b-4664-11e5-8004-000000000000 256.208142ms
```

**Comment by papylhomme** [comment]
OK, so I have a fix for my case, updating the **rpi.ShardGroupDuration** when updating the retention policy duration (see patch below). However this asks for other questions:

- what about existing shards ? On my use case, what I would do is loop over **rpi.ShardGroups** and update their **EndTime** (possibly to **time.Now()** if the new duration is already exceeded)
- shards (and by the way retention policies) don't look to be designed to enforce a strict time interval to retain values (bullets below). Is this an intended choice for the project or will/can it change in the future ? I'm not looking for pinpoint accuracy, but I'm dealing with low and fixed space constraint (coming from the land of RRD, the fixed and foreseeable size of the DB is a **major** feature :-D)
    - Shards are expired when **EndTime + rpi.Duration** is passed, not just **EndTime**
    - func **shardGroupDuration** result is "loosely" based on rpi.Duration


```
diff --git a/meta/data.go b/meta/data.go
index 33c829b..ac5a240 100644
--- a/meta/data.go
+++ b/meta/data.go
@@ -212,6 +212,7 @@ func (data *Data) UpdateRetentionPolicy(database, name string, rpu *RetentionPol
        }
        if rpu.Duration != nil {
                rpi.Duration = *rpu.Duration
+               rpi.ShardGroupDuration = shardGroupDuration(*rpu.Duration)
        }
        if rpu.ReplicaN != nil {
                rpi.ReplicaN = *rpu.ReplicaN
```

**Comment by otoolep** [comment]
Thanks for your detailed analysis @papylhomme -- there does indeed seem to be an issue here. I'll look into it shortly.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3736 will fix the issue in the code.

Existing shard groups are not changed when the retention policy changes. Right now retention policy changes only apply to shard groups moving forward. It does not affect data that has already been written. That may be something we may need to change, and I will open a ticket.

**Comment by papylhomme** [comment]
Thanks, I'm trying this on a new DB with collectd, I'll close this issue tomorrow once I can monitor what happened this night.

**Comment by papylhomme** [comment]
Problem fixed for retention enforcment, records are deleted after approx. 2h (as expected with shard expiration = shardGroup.EndTime + rpi.Duration)

However I'm experiencing a strange behaviour when querying the data:
- simple query _select * from users_value where time > now() - 6h_ return first result at 16h00 (expected), and point every 10 seconds till 18:30:00
- query _select mean(value) from users_value where time > now() - 6h group by time(10s)_ return 1 value at  16:00:00 and nothing for 16:XX:XX, 1 value for 17:00:00 and nothing for 17:XX:XX, and a value for each 10 seconds in 18:XX:XX

Does the aggregate functions (_mean_ and others) work over multiple shard groups ? If so, I'm not sure if this is related to the latest fix or another commit interfering, so do I close this issue and open a new one ?

I will try to apply the fix on the version I was running previously (I know it was displaying more than the last hour of value), but it will have to wait till the end of the week.

**Comment by otoolep** [comment]
Thanks @papylhomme.

It would be most helpful if you could open a new issue if you have suspicions about query behaviour. Please include all the details above.

**Comment by papylhomme** [comment]
OK I'll do that, primary problem is fixed

**Comment by beckettsean** [comment]
Closing this issue as the retention policy behavior is not a bug.

@papylhomme can you open a [new issue](https://github.com/influxdb/influxdb/issues/new) for the query issue you are seeing? Please include the actual output from the query.

**Comment by mslee89** [comment]
how did you solve the problem?
