### ISSUE TITLE
[0.9.0] Wrong tag values parsed while writing data

### ISSUE THREAD

**Issue by phagunbaya** [influxdb/influxdb#3711]
I'm encountering following behaviour if my tags have spaces

This creates tag with value "hello\" as suppose to be "hello world"
```
insert test1,tag1=hello\ world,group=greeting value=123 1439882982374
```

whereas this creates correct tag values
```
insert test5,tag1=hello\ world,group=greeting,tag2=magic\ world value=123 1439882982374
```

<img width="674" alt="screen shot 2015-08-18 at 1 15 56 pm" src="https://cloud.githubusercontent.com/assets/1146297/9324829/6828e62e-45ab-11e5-8f8e-593af51ff615.png">

**Comment by jwilder** [comment]
This is fixed in the latest nightlies and will be fixed for 0.9.3.  This is not fixed in 0.9.2 however so you will need to upgrade to 0.9.3 when it's released.

```
Connected to http://localhost:8086 version 0.9
InfluxDB shell 0.9
> create database test
> use test
Using database test
> insert test1,tag1=hello\ world,group=greeting value=123 1439882982374
> select * from test1
name: test1
-----------
time				group		tag1		value
1970-01-01T00:23:59.882982374Z	greeting	hello world	123

> insert test5,tag1=hello\ world,group=greeting,tag2=magic\ world value=123 1439882982374
> select * from test5
name: test5
-----------
time				group		tag1		tag2		value
1970-01-01T00:23:59.882982374Z	greeting	hello world	magic world	123

>
```

**Comment by phagunbaya** [comment]
@jwilder When 0.9.3 is going to be released ?

**Comment by gunnaraasen** [comment]
0.9.3 should be released this Friday.
