### ISSUE TITLE
Unable to Drop Series

### ISSUE THREAD

**Issue by JauntyWard** [influxdb/influxdb#3712]
I am unable to drop a series from a database. When attempting to do so, the error: "Server returned error: database not open" is returned. 

The query I am using takes the form of:

DROP SERIES FROM cpu WHERE host='server01'

This is on InfluxDB 0.9.2, running on Docker.

**Comment by mjdesa** [comment]
@JauntyWard this should no longer be an issue in 0.9.3.  Please upgrade.
