### ISSUE TITLE
graphite templates - matching

### ISSUE THREAD

**Issue by testuser7** [influxdb/influxdb#3713]
Hi,

Is it possible to configure graphite templates to apply only first matching template?
Example:
```
    "jmeter.test.* .jmeter.measurement",
    "jmeter.* .measurement.response.metric"
```

**Comment by jwilder** [comment]
It will match the most specific filter first. `"jmeter.test.* .jmeter.measurement"` is more specific so it will attempt to match that first and then the `"jmeter.* .measurement.response.metric"`.  The order that they are listed in the config file is not used.  You read more about how the graphite plugins works in the [README](https://github.com/influxdb/influxdb/tree/master/services/graphite)
