### ISSUE TITLE
Building Influx, how to get service mode?

### ISSUE THREAD

**Issue by mvadu** [influxdb/influxdb#3715]
This is more of a question than a real issue. The front page says 

>Starting InfluxDB• service influxdb start  if you have installed InfluxDB using an official Debian or RPM package.
>• $GOPATH/bin/influxd  if you have built InfluxDB from source.

I am building my own on a Raspberry Pi, but would like to run it as a service (so it can run even after I close the SSH connection). 

How do I get the service option on my Raspberry with a custom build from scratch?

**Comment by mjdesa** [comment]
@chaithrar This is neither a feature request nor a bug. Please ask questions like this on the [mailing list](mailto:influxdb@googlegroups.com) rather than opening a GitHub Issue.

**Comment by mvadu** [comment]
You need to build a package using package.sh, then run dpkg -i <package name>, sudo service influxdb start
