### ISSUE TITLE
Sorting and the latest data

### ISSUE THREAD

**Issue by zhang8h** [influxdb/influxdb#3726]
Hello, may I ask how to sort Series, how to query the latest data Series, thank you

**Comment by zhang8h** [comment]
I realized that, I don't know what's the problem?
select coutn(load) from cpu;
select * from cpu limit 1 offset count(load)-1;

**Comment by beckettsean** [comment]
The mailing list, influxdb@googlegroups.com, is a more appropriate place to ask usage questions. GitHub Issues are primarily for feature requests and bug reports.

In your note, please mention the version of the database you are running.

`select * from cpu limit 1 offset count-1;` You cannot reference `count` as a value in the query. Functions do not generate stored or cached values and the results cannot be referenced in subsequent queries or in clauses other than the SELECT clause.
