### ISSUE TITLE
Incorrect measurement specification in the Graphite README.md in ADDING TAGS section

### ISSUE THREAD

**Issue by omer653** [influxdb/influxdb#3727]
The measurement should be loadavg.10. 

servers.localhost.cpu.loadavg.10

Template: .host.resource.measurement* region=us-west,zone=1a
Output: measurement = loading.10 tags = host=localhost resource=cpu region=us-west zone=1a
--> 
Output: measurement = loadavg.10 tags = host=localhost resource=cpu region=us-west zone=1a

**Comment by gunnaraasen** [comment]
Thanks @omer653

**Comment by beckettsean** [comment]
Semi-dupe of #3462, looks like that only caught the first one.
