### ISSUE TITLE
Upgrade from 0.92 to 0.93

### ISSUE THREAD

**Issue by abolinhas** [influxdb/influxdb#3729]
Hi,
If I upgrade from 0.92 to 0.93 I will lose all my data?
If so, any way to recover it on new version
Best regards

**Comment by gunnaraasen** [comment]
The upgrade from 0.9.2 to 0.9.3 should not delete any data. Existing shards created by 0.9.2 will continue to use the old b1 storage engine. All new shards created by 0.9.3 will utilize the bz1 storage engine, which includes the new WAL implementation and compression. The query engine should return data from shards using either engine.

**Comment by abolinhas** [comment]
Hi,
Thanks for your quick reply.
There is any tool to migrate old data from shard (b1 storage) to the new storage engine (bz1)?
Best regards

**Comment by gunnaraasen** [comment]
There is no way to convert existing shards to the new engine. The only way do that is by rewriting the old data into a new database.
