### ISSUE TITLE
Add Metadata Associated to a Series

### ISSUE THREAD

**Issue by samuraraujo** [influxdb/influxdb#373]
Proposal: It would be nice if we could store metadata about the series itself, so it could be used for presentation, graphing, etc. 

Here is a scenario:

Suppose we have series representing pageviews:

company.uri1.pageview
company.uri2.pageview
company.uri3.pageview
....

The series contain two columns value and timestamp

Ex.
bloghouse.b7cb47c1a9a4642b9882b0cb4393a71fc4dbff44.pageview  

value timestamp
1         32874982893
32         32874982895
42         32874982897
....

bloghouse.b7cb47c5454656459882b0cb4393a71fc4dbff44.pageview  

value timestamp
1         32874982893
52         32874982895
76         32874982897
....

Now I need to visualize these series in a graph. However, I want to have a nice name to  my series,i.e, the title of the page ("Post About Furnish")  instead of "bloghouse.b7cb47c1a9a4642b9882b0cb4393a71fc4dbff44.pageview" .

It would be nice if we could store metadata about the series itself, so it could be used for presentation, graphing, etc. 

Once stored, the metadata could be obtained by querying as well.

:)

**Comment by BartVB** [comment]
:+1:

My main use case would be storing the unit of the data. IMO it's insane that we need to manually add this to graphs in the frontend when we know the unit and kind of data on the collector side.

Metadata for series would also make it possible to ask for 'all networking related stats for cluster A' or 'all postgres stats for server X'. Series metadata is much better suited for this than tags.

**Comment by pauldix** [comment]
You can actually do this using tags. Particularly since there's no limit to the number of tags you can have on a series. The current tag functionality lets you do things like that kind of discovery.

There's a few examples in this post: http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html

**Comment by KrishnaPG** [comment]
@pauldix This is a valid concept and cannot be achieved with tags alone. I have put some additional info on the challenges with the tags approach in this issue: https://github.com/influxdb/influxdb/issues/3445
