### ISSUE TITLE
Move to Go 1.5

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3731]
Go 1.5 has been released.

http://blog.golang.org/go1.5

At some point (line up with a specific release) we need to move to this version of Go. This would require:

- ensure all code compiles with Go 1.5.
- remove explicitly setting GOMAXPROCS, since it is now automatically set to number of cores.
- update linker flags (commit, vesion, branch) to use new form.
- ensure all tests pass with Go 1.5.
- update CONTRIBUTING.md.
- moving CircleCI testing to 1.5.
- build scripts used to create debian and RPM packages to 1.5.
- all developers change their tool chains.
- message to mailing list.

**Comment by otoolep** [comment]
@DanielMorsing believes moving to 1.5 for the 0.9.4 release is OK. That works for me too.

**Comment by otoolep** [comment]
@dgnorton @toddboom

**Comment by benbjohnson** [comment]
:+1: for 1.5 in 0.9.4.

**Comment by corylanou** [comment]
:ship: 1.5 in 0.9.4!

**Comment by dgnorton** [comment]
:+1: for 1.5 in 0.9.4

**Comment by scharissis** [comment]
The new GOMAXPROCS default will be (likely) better for a lot of applications, but not necessarily. Perhaps benchmarking (as part of the test suite) should determine InfluxDB's optimal setting whilst still exposing it to end users who may choose to fine-tune their deployment?

Original proposal: https://docs.google.com/document/d/1At2Ls5_fhJQ59kDK2DFVhFu3g5mATSXqqV5QrxinasI/edit

**Comment by otoolep** [comment]
Sure, I have no problem exposing GOMAXPROCS control to users, in principle. By default it will be set to the number of CPUs, which is what is does today.
