### ISSUE TITLE
go test fails github.com/influxdb/influxdb/toml_test 

### ISSUE THREAD

**Issue by BGraco** [influxdb/influxdb#3732]
Built 0.9.3-rc1 on a beaglebone black running debian 7.8. 
"go test -v ./... "returns all PASS except for the result below

```
# github.com/influxdb/influxdb/toml_test 
influxdb/toml/toml_test.go:29: constant 10737418240 overflows toml.Size 
FAIL	github.com/influxdb/influxdb/toml [build failed]
```

Is this cause for concern?

**Comment by beckettsean** [comment]
@otoolep @DanielMorsing any thoughts on this test failure?

**Comment by DanielMorsing** [comment]
The type is something that is supposed to represent a size on disk (i think?), so it should probably be turned into a int64.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/3734 should fix this. The case is to test parsing of multi-gigabyte files. Let's just assume a 2GB file.

**Comment by otoolep** [comment]
Should be fixed now, though I have not actually tried 32-bit compilation. Please let us know if this doesn't address the issue.

**Comment by BGraco** [comment]
Just tested and issue is resolved!
