### ISSUE TITLE
Alter ShardGroup end times when retention policy changes

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#3738]
Started with https://github.com/influxdb/influxdb/issues/3702, and related https://github.com/influxdb/influxdb/pull/3736

If a retention policy's (RP) period is reduced from, say, 1 week to 1 hour, any shard groups that were created while the period was 1 week do not have the associated end-times changed. This means that data written into the RP while the period was 1 week stay around much longer than might be expected.

It seems to be most sensible to modify the end-times such that data older than the new RP period is deleted at the next enforcement cycle.

@beckettsean and @pauldix for a policy call.

**Comment by pauldix** [comment]
End times shouldn't be modified. And the only time this would make a difference is for shards that are hot for writes, which would be problematic to update while they're going.

I would say that we just document that if you reduce the retention period, the currently hot shards will have to finish up before that gets applied.

In your example, any shards that are cold for writes, should get removed on the next sweep, assuming their end time is older than an hour ago.

**Comment by papylhomme** [comment]
If I may, the proposal for just documenting what happens when reducting the retention period is fine for a running system, but then we might need an option to configure the retention duration for the default DB at installation.

**Comment by beckettsean** [comment]
@papylhomme there's an open issue for that very feature: https://github.com/influxdb/influxdb/issues/2676, currently slated for the 0.9.4 release.

**Comment by beckettsean** [comment]
I see what @pauldix is saying, especially thinking about an inadvertent retention policy change. If I have INF and change to 1h, realize my mistake, and switch back, I might lose all my data, and the shards might have two very quick updates to their end times. Not good and quite risky.

Can we have a return message for all `ALTER RETENTION POLICY` statements with a DURATION setting, something along the lines of "changes to duration do not affect data already on disk. that data will expire using the prior settings"

For an INF duration that changes to 1h duration, the shards go cold after a week and then would be purged?

**Comment by otoolep** [comment]
What will happen with top-of-master code is this (by default).

- say a retention policy with infinite period exists.
- shard groups are created for that policy with period of 7 days.
- 30 minutes before anyone of these shard groups expires, a succeeding one will be precreated with an end-time 7 days and 30 minutes in the future. Call this shard group X.
- user then sets retention period to 1 hour.
- data written to shard group X will not be removed from the system for another 7 days even though the retention policy period is now 1hour.

Is this acceptable behaviour?

**Comment by otoolep** [comment]
To be clear, it sounds exactly what @pauldix requests, but I want to be sure.

**Comment by otoolep** [comment]
Sounds like we're done here, since master has been modified.
