### ISSUE TITLE
package not follow linux FHS

### ISSUE THREAD

**Issue by SteamedFish** [influxdb/influxdb#3753]
From [Debian FHS manual](https://www.debian.org/doc/packaging-manuals/fhs/fhs-2.3.txt) :

1. if not use the `/opt/` directory
    1. the binary file `influx` and `influxd` should be placed under `/usr/bin/` 
    2. the documentation should be placed under `/usr/share/doc/influxdb/`
    3. init script should be placed at `/etc/init.d/influxd` and use `update-rc.d` to install the script
    4. configuration files should go under `/etc/influxdb/`
    5. there should be a `/etc/default/influxdb` configuration file provided by default
    6. data directory should go under `/var/lib/influxdb`
    7. influxdb user should set `/var/lib/influxdb` or `/nonexistant` as home directory and use `/bin/false` as login shell
    8. there should be a `/lib/systemd/system/influxdb.service` configuration file for systemd 
2. if use the `/opt/` directory
    1. the binary file `influx` and `influxd` should be placed under `/opt/influxdb/bin/`
    2. the documentation should be placed under `/opt/influxdb/usr/share/doc/influxdb/`
    3. configuration files should go under `/etc/opt/influxdb/`
    4. data directory should go under `/var/opt/influxdb/`
    5. I have no idea where the init script should be located. I will read more manuals about it.
    6. influxdb user should set `/var/opt/influxdb` or `/nonexistant` as home directory and use `/bin/false` as login shell

**Comment by SteamedFish** [comment]
This is an example system configuration file from ArchLinux. 

https://aur.archlinux.org/cgit/aur.git/tree/influxdb.service?h=influxdb

**Comment by gerrickw** [comment]
I also agree this would be a nice addition.  You could also look at how Grafana set their packaging as they are also a go project.

https://github.com/grafana/grafana/tree/master/packaging
https://github.com/grafana/grafana/issues/1758

**Comment by rossmcdonald** [comment]
Closing in favor of #4479. Any further comments should be made on the PR.
