### ISSUE TITLE
Package.sh Architecture detection in Raspbian fails

### ISSUE THREAD

**Issue by mvadu** [influxdb/influxdb#3755]
Current version on Package.sh, has `ARCH=``uname -i`` to detect current architecture. This is later used to branch out build logic. 

On Raspbian (running on Raspberry Pi 2, derivation of debian) `uname -i` returns `unknown`. This results in incorrect package creation. Raspbain returns

    pi@raspberrypi ~ $ uname -a
    Linux raspberrypi 4.1.5-v7+ #809 SMP PREEMPT Thu Aug 13 00:50:56 BST 2015 armv7l GNU/Linux
    pi@raspberrypi ~ $ uname -m
    armv7l

Package.sh needs to have additional logic to detect this as proper arm architecture.

**Comment by mvadu** [comment]
I am not an expert in shell scripts. I wanted to try 
    
    if [ $ARCH = "unknown" ]; then
	    if uname -a | grep -q "arm";then ARCH="arm";fi
    fi

But I am getting 

    GOPATH (/home/pi/.gvm/pkgsets/go1.4.2/global) looks sane, using /home/pi/.gvm/pkgsets/go1.4.2/global for installation.
    The source tree is not clean -- aborting.

So I can't verify the fix.

**Comment by otoolep** [comment]
@mvadu -- if the script you can comment out the check at https://github.com/influxdb/influxdb/blob/master/package.sh#L266

**Comment by mvadu** [comment]
Tried it today. But it failed to package as rpmbuild is

    ./package.sh v.0.91

    Post-install script created successfully at /tmp/tmp.cd2Q5XG2Ry
    Commence creation of arm packages, version v.0.91? [Y/n] y
    no value for epoch is set, defaulting to nil {:level=>:warn}
    no value for epoch is set, defaulting to nil {:level=>:warn}
    Need executable 'rpmbuild' to convert dir to rpm {:level=>:error}

And I can't find a package for rpmbuild, but I did install librpmbuild3 (which is the only package I can get). But at least my fix is working and is going into arm branch. Need help in figuring out rpmbuild part.

**Comment by mvadu** [comment]
I think the issue with Raspbian is just lack of rpmbuild. Even though the script defaults to `debian_package=influxdb_${VERSION}_amd64.deb` when the ARCH is not matched, FPM automatically changes to `influxdb_${VERSION}_armhf.deb`. So the platform detection works in FPM. 

That being said, since package.sh tries to create rpm package first and it fails (100% of the time) makes things difficult in Raspberry Pi. If the order of package creation can be changed to create deb->tar->rpm then the script will work and we will get .deb and .tar packages, and then script fails. At that stage only thing left is tagging and aws upload, so I think it will be a good balance.

    COMMON_FPM_ARGS="-C $TMP_WORK_DIR --vendor $VENDOR --url $URL --license $LICENSE --maintainer $MAINTAINER --after-install $POST_INSTALL_PATH --name influxdb --version $VERSION --config-files $CONFIG_ROOT_DIR ."
    
    $FPM -s dir -t deb $deb_args --description "$DESCRIPTION" $COMMON_FPM_ARGS
    if [ $? -ne 0 ]; then
        echo "Failed to create Debian package -- aborting."
        cleanup_exit 1
    fi
    echo "Debian package created successfully."
    
    $FPM -s dir -t tar --prefix influxdb_${VERSION}_${ARCH} -p influxdb_${VERSION}_${ARCH}.tar.gz --description "$DESCRIPTION" $COMMON_FPM_ARGS
    if [ $? -ne 0 ]; then
        echo "Failed to create Tar package -- aborting."
        cleanup_exit 1
    fi
    echo "Tar package created successfully."
    
    $rpm_args $FPM -s dir -t rpm --description "$DESCRIPTION" $COMMON_FPM_ARGS
    if [ $? -ne 0 ]; then
        echo "Failed to create RPM package -- aborting."
        cleanup_exit 1
    fi
    echo "RPM package created successfully."

**Comment by mvadu** [comment]
@otoolep  Could you please check in the above modification (i.e. Changing order of package creation rpm->deb-tar to deb->tar->rpm) to support Raspbian?

**Comment by otoolep** [comment]
Done in https://github.com/influxdb/influxdb/commit/3f525ff8c1699ed79f93a4669824aae1464ac8fb @mvadu

**Comment by mvadu** [comment]
Thank @otoolep for a very quick turnover. I think long term we should have arguments to skip one or more type of packages skipped, and to pass arch as a command line argument.

**Comment by otoolep** [comment]
Yes, exactly @mvadu -- we do need something more sophisticated in time.

**Comment by fg2it** [comment]
@otoolep the fact that this script is just for your own use is a bit sad : there are not .deb for armhf so this is a very convinient way to build our own. Influxdb is a really nice tool for a lot of application that fit nicely on raspberry 2. It would be nice to have .deb or cleaner script. Anyway it is already a lot easier to build that v0.8.
@mvadu personnaly, I installed rpm and use
NIGHTLY_BUILD=false ./package.sh 0.9.4
it avoid messing with clean_check_tree() call. The little price for that is the failure when package.sh try to publish the package.

**Comment by mvadu** [comment]
@fg2it WIth my suggestion already checked-in you don't need to skip the `clean_check_tree()`, I just do `git pull` and run the ./package.sh. All we did change is to generate debian package first before it tries to invoke rpm build.

**Comment by fg2it** [comment]
@mvadu I understood this, my point was just that this was not necessary. A bit nicer (and cleaner) change would have been to allow options from the command line to choose a single target distribution (and why not the publishing too).

**Comment by otoolep** [comment]
PRs welcome gentlemen. :-)

**Comment by fg2it** [comment]
@otoolep @mvadu 
Here is what I have in mind for these package.sh options : 
```
package.sh [-h] [-p|-w] [-t <dist>] <version>
    -p just build packages
    -w build packages for current working directory
       imply -p
    -t <dist>
       build package for <dist>
       <dist> can be rpm, tar or deb
       can have multiple -t
```
- It preserves current semantics, so this works as before
```
./package.sh 0.9.4
NIGHTLY_BUILD=true ./package.sh 0.9.4
```
- `-t` allows to build only listed package formats
```
#only deb
./package.sh -t deb 0.9.4
#only deb and tar
./package.sh -t deb -t tar 0.9.4
```
and address the original issue raised by mvadu by the mean of switch.
- `-p` is meant do address simple builds without any tagging, or publishing. Use case is typically someone wanting to build influxdb when no official package is provided (e.g. me with raspberry ...)
- `-w` goes a bit further, it allows packaging current, uncommitted, working directory. Here, use case could be someone wanting to build influxdb but needing to customize build (e.g. changing sthg in package.sh).

**Comment by mvadu** [comment]
@fg2it I agree that your suggestion makes mist sense as it makes life easier for everyone building on platforms not supported by core team. But I think the team needs us to contribute by coding and submitting a pull request. Do you have time/expertise to do that? I am currently in middle east, far away from home. I can can try implementing it once I am back at home.

**Comment by fg2it** [comment]
@mvadu Just wanting to get input before submitting PR. I already have a branch implementing these suggestions.

**Comment by otoolep** [comment]
@fg2it -- those kind of switches would be great, and exactly the kind of thing I'd propose myself. If you put something together, we'd be interested. I'm pretty sure we'd merge.

**Comment by mvadu** [comment]
@fg2it Please update master/CONTRIBUTING.md as well. Currently package.sh is not documented at all. But with your changes it can be part of official documentation (not on main web, but on github). My be just adding what you wrote yesterday is good enough.

@otoolep please confirm.

**Comment by otoolep** [comment]
Sure, I'm OK with mentioning `package.sh` in `CONTRIBUTING.md`. A one-line statement telling the user about the script, and to check the help output of the script for more details should be sufficient and the most maintainable.

**Comment by otoolep** [comment]
There is no more work planned here, as we only officially support the platforms in the packaging script.

**Comment by mvadu** [comment]
As I mentioned earlier, with package only option (thanks to @fg2it), we don't need separate platform detection, fpm takes care of it.
