### ISSUE TITLE
0.9.2 InfluxDB UI not able to connect to 8086 port

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#3758]
Influx 0.9.2 UI is not able to connect to 8086 port,

![influxdb_ui](https://cloud.githubusercontent.com/assets/8173290/9383047/713849e4-4763-11e5-8f01-d782c42afe86.jpg)

Where as I am getting response if I copy paste URL on my browser http://localhost:8086/query?q=SHOW+DATABASES&db=

![show_query](https://cloud.githubusercontent.com/assets/8173290/9383086/d392b1d8-4763-11e5-89fa-c6aad4d75303.jpg)

**Comment by gunnaraasen** [comment]
The error message indicates this is the 0.9.3-rc1 admin UI and the version string in the UI needs to be updated.

@buro1983 are there any errors being reported in the browser console when you click 'save'?

**Comment by buro1983** [comment]
No,
One point to be noted, I tired with 0.9.3-rc1 UI also and it worked fine but I have observed that version string was 0.9.2

**Comment by beckettsean** [comment]
Thanks @buro1983 the version string has been fixed by https://github.com/influxdb/influxdb/pull/3764. Since the admin UI is working in 0.9.3 RC1 I'm closing the issue.

**Comment by buro1983** [comment]
I am not able to switch  to 0.9.3 till https://github.com/influxdb/influxdb/issues/3757 is fixed
