### ISSUE TITLE
Timestamp set to random value

### ISSUE THREAD

**Issue by karma243** [influxdb/influxdb#3769]
When timestamp is being provided externally, it is being set to some random value. I am using influxDB 0.9.2
![influxerror](https://cloud.githubusercontent.com/assets/8341456/9389851/f20f631e-478a-11e5-8b08-b14e7a9de17d.jpg)

**Comment by otoolep** [comment]
Thanks @karma243 -- could you simply copy 'n' paste text from the terminal to the bug report, as opposed to a screen shot?

**Comment by DanielMorsing** [comment]
The line protocol uses nanoseconds from the epoch as the timestamp format. It looks like you are writing to the database with seconds from the epoch instead.

**Comment by otoolep** [comment]
Good catch @DanielMorsing -- this explains the 1970 timestamp.

Closing as a non-issue. @karma243 -- if you don't agree, please let us know.

**Comment by beckettsean** [comment]
@karma243 to clarify the response, you write in a timestamp of 1440089182, but you did not specify a precision. InfluxDB assumes all timestamps are in epoch nanoseconds unless otherwise specified.

`1440089182` in nanoseconds is 1.4 seconds after midnight, 1970-01-01, just as your screenshot shows.
