### ISSUE TITLE
[0.9.3] (regression) cannot use tag in GROUP BY if there is also a field of the same name

### ISSUE THREAD

**Issue by sudabon** [influxdb/influxdb#3783]
When execute the query there is tagKey in GROUP BY clause, error occurs below.

ERR: can not use field in GROUP BY clause: tagKey

The following is the output of command line.

```
# /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.3-rc1
InfluxDB shell 0.9.3-rc1
> use xdata_db
Using database xdata_db
> show tag keys from xdata_influxdb_action_001248
name: xdata_influxdb_action_001248
----------------------------------
tagKey
action
session_id

> select count(url) from xdata_influxdb_action_001248 where time > now() - 120s;
name: xdata_influxdb_action_001248
----------------------------------
time				count
2015-08-21T04:17:23.394514985Z	383

> select count(url) from xdata_influxdb_action_001248 where time > now() - 120s group by action;
ERR: can not use field in GROUP BY clause: action
```

I hope this is fixed in 0.9.3 GA.

Thanks

**Comment by beckettsean** [comment]
@sudabon can you also give the output of `show field keys from xdata_influxdb_action_001248`? I want to make sure there's not a field key also named `action`.

@corylanou @pauldix To me this is almost certainly related to the GROUP BY * PR, any insights?

**Comment by corylanou** [comment]
@beckettsean I'm fairly certain there has to be a field named `action`.  However, we should handle this regardless and default to the tag for group by, the same way we default to the field for a select statement.  For sure a bug regardless.

**Comment by sudabon** [comment]
@beckettsean I attach the output of required query below.

```
> show field keys from xdata_influxdb_action_001248
name: xdata_influxdb_action_001248
----------------------------------
fieldKey
access_date
action
browser
customer_id
device_maker
device_name
device_type
domain_group
domain_name
engine_name
ip
keyword
landing_type
mode
os
query_aq
query_attributes_id
query_b
query_brand_id
query_ctg_name
query_ctgid
query_ei
query_event
query_fr
query_from_link
query_id
query_ktr_ev
query_ktr_evct
query_label
query_order_cd
query_p_img_url
query_p_name
query_p_num
query_p_price
query_pid
query_price
query_pstart
query_sale_id
query_top_category
query_utm_campaign
query_utm_content
query_utm_medium
query_utm_source
query_value
referrer_domain
repeat_flag
session_id
site_id
unique_id
url
```

I add 'action' in not only tag key but field key in order to be flexible for future requirement from application.
For example, select count(action) from ... group by OTHER_TAG_KEY.

If I remove 'action' from field key, does it work well?
I will try it out.

**Comment by sudabon** [comment]
@beckettsean When I remove 'action' from field key, it works well like below.
As @corylanou says I hope that it works well even if there is also 'action' in field key 

```
> select count(url) from xdata_influxdb_action_001248 where time > now() - 600s group by action;
name: xdata_influxdb_action_001248
tags: action=cartin
time				count
----				-----
2015-08-22T07:08:09.668491729Z	37


name: xdata_influxdb_action_001248
tags: action=cartout
time				count
----				-----
2015-08-22T07:08:09.668491729Z	27


name: xdata_influxdb_action_001248
tags: action=login
time				count
----				-----
2015-08-22T07:08:09.668491729Z	266


name: xdata_influxdb_action_001248
tags: action=member_regist
time				count
----				-----
2015-08-22T07:08:09.668491729Z	7


name: xdata_influxdb_action_001248
tags: action=order
time				count
----				-----
2015-08-22T07:08:09.668491729Z	8


name: xdata_influxdb_action_001248
tags: action=view
time				count
----				-----
2015-08-22T07:08:09.668491729Z	1459


name: xdata_influxdb_action_001248
tags: action=waiting_list
time				count
----				-----
2015-08-22T07:08:09.668491729Z	2
```

**Comment by rstets** [comment]
same problem here.
getting "ERR: can not use field in GROUP BY clause: shopId"
and yes there is a shopId field and a shopId tag. was working fine in 0.9.2, stopped after upgrading to 0.9.3 ("stable")

**Comment by beckettsean** [comment]
Hopefully we can fix the parser to check for the existence of the tag before the field, so that the error never fires.

**Comment by sudabon** [comment]
glad to hear that.

**Comment by beckettsean** [comment]
@corylanou short term, just assume they are grouping by tag if there's an identifier that matches both.

**Comment by corylanou** [comment]
After looking at this in more detail, and talking to several of the other core team members, supporting a tag and a field with the same name is outside of the current design architecture.  It's equivalent in other databases as having 2 columns with the same name.  I would welcome a compelling use case, but I suspect there isn't one.  

The reason you CAN do it is because when we write to shards, we only know about that shards meta data.  Therefore enforcing that you can't have a duplicate tag/field name is very difficult.  We have several safeguards in the code that prevent issues when querying back, but it's still an undesired outcome.

The real problem is with `select * from measurement group by *`.  Trying to make that work properly with a field/tag with the same name is very difficult.

**Comment by pauldix** [comment]
@corylanou I think their ultimate goal here is they want to have a field and be able to group by that field. Where if they have a numeric value and they write it as both a field and a tag they can group by it and then they can also do math against it.

Although I agree, it's an antipattern to have a field and a tag with the same name. It's not really something people should be doing.

**Comment by corylanou** [comment]
Agreed. I think a work around for now would be to have a field called `action` and a tag called`tagaction` or something like that, and then log the same value to them.  Now, if they are indeed different data, then the same column name then we certainly would recommend against that design pattern.
