### ISSUE TITLE
graphite section in influxdb-0.9.2.1 version doesn't have name-schema property.

### ISSUE THREAD

**Issue by san310787** [influxdb/influxdb#3786]
I'm using collectl for pushing system data to influxdb. I can see in  config files of < 0.9 versions of influxdb, under graphite section, we do have a property named 'name-schema' for separating the measurement, tags and values using the separator.

In 0.9.2.1v influxdb, I don't see in the generated config file. Even, If i'm introducing such property, the influxdb process is not getting started. B'coz of which the entire metric is assigned as measurement name. Further, I can't use WHERE clause to filter out the data.

Graphite section in newly generated config file:

[[graphite]]
  bind-address = ":2003"
  database = "graphite"
  enabled = true
  protocol = "tcp"
  batch-size = 0
  batch-timeout = "0"
  consistency-level = "one"
  separator = "."

Hope, you understand the issue from the image below.

![image](https://cloud.githubusercontent.com/assets/13868788/9410101/f8bb372c-483b-11e5-964d-6cc42963c4f3.png)

**Comment by beckettsean** [comment]
Please review the [Graphite README](https://github.com/influxdb/influxdb/blob/master/services/graphite/README.md) for details on how filtering/naming works in InfluxDB 0.9

**Comment by beckettsean** [comment]
If you lose the link, it's also in the documentation: https://influxdb.com/docs/v0.9/write_protocols/graphite.html
