### ISSUE TITLE
resort flag for wal cache can be inadvertently cleared

### ISSUE THREAD

**Issue by DanielMorsing** [influxdb/influxdb#3792]
https://github.com/influxdb/influxdb/blob/master/tsdb/engine/wal/wal.go#L1302

A worked example: If the cache contains timestamps [1,2,5], then you insert 4, followed by 6, you can end up clearing the resort flag for that cache entry. This will cause the cache cursor to return non-sorted values when iterated over.

@pauldix

**Comment by otoolep** [comment]
Added 0.9.3 milestone, so this isn't missed.
