### ISSUE TITLE
[0.9.3-rc1] WAL Flush Logging

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#3796]
Prior to the WAL being moved out of BoltDB there was a flush message indicating the amount of points being flushed, and the duration of the flush operation.  This is a desired log message to verify BoltDB and Disk performance.  Ideally it should be re-implemented for WAL flushes.

**Comment by otoolep** [comment]
Are these the messages you mean? They are in the 0.9.3 code.

```
[wal] 2015/08/21 13:42:04 Flush due to threshold. Compacting 1 series from partition 5
[wal] 2015/08/21 13:42:04 compaction of partition 5 took 267.701191ms
[wal] 2015/08/21 13:42:06 Flush due to threshold. Compacting 1 series from partition 5
[wal] 2015/08/21 13:42:06 compaction of partition 5 took 367.034513ms
[wal] 2015/08/21 13:42:07 Flush due to threshold. Compacting 1 series from partition 5
```

**Comment by otoolep** [comment]
Please let me know if I am mistaken but the code in the 0.9.3 branch and master logs each flush of the WAL.

**Comment by pauldix** [comment]
I updated the logging a bit. #3807 should improve the output
