### ISSUE TITLE
[0.9.2] Service fails to start on Ubuntu 14.04

### ISSUE THREAD

**Issue by llevar** [influxdb/influxdb#3799]
Installed Influxdb via Debian package
Ran  `/opt/influxdb/influxd config > /etc/opt/influxdb/influxdb.conf`
Running `service influxdb restart` I get:

```
influxd process is not running [ OK ]
Starting the process influxd [ OK ]
influxd process failed to start [ FAILED ]
```

In /var/log/influxdb/influxd.log:
`[handoff] 2015/08/21 22:37:41 Failed to start hinted handoff processor: mkdir all: mkdir /root/.influxdb: permission denied`

If I run `/opt/influxdb//influxd -config /etc/opt/influxdb/influxdb.conf`  instead I get normal startup:

```
using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/08/21 22:41:47 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/21 22:41:47 read local node id: 1
[admin] 2015/08/21 22:41:47 listening on HTTP: [::]:8083
[httpd] 2015/08/21 22:41:47 authentication enabled: false
[httpd] 2015/08/21 22:41:47 listening on HTTP: [::]:8086
2015/08/21 22:41:47 InfluxDB starting, version 0.9.2, commit 6c0a91f775f9fc0e625d17ffa04a3fe86945ba09
2015/08/21 22:41:47 GOMAXPROCS set to 1
[run] 2015/08/21 22:41:47 listening for signals
[metastore] 2015/08/21 22:41:48 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/21 22:41:48 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/21 22:41:48 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/21 22:41:48 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/21 22:41:48 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/21 22:41:48 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/21 22:41:48 [INFO] raft: Disabling EnableSingleNode (bootstrap)
[metastore] 2015/08/21 22:41:48 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/21 22:41:48 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/08/21 22:41:48 Sending anonymous usage statistics to m.influxdb.com
```

The directories under `/root/.influxdb` appear to be created ok

After that if I run the service restart again it still fails with the same error.

**Comment by llevar** [comment]
Now that I stared at it some more I realize that the problem is because the script at /etc/init.d/influxb is using the influxdb user to run

USER=influxdb
GROUP=influxdb

but the default config file is listing /root/.influxdb as the directory for a bunch of files and the influxdb user doesn't have perms to write there.

I can make the service start now by changing the USER and GROUP to root inside the shell script, but why doesn't this work out of the box?

**Comment by otoolep** [comment]
@llevar -- it actually does work out of the box. The step:

```
 Ran /opt/influxdb/influxd config > /etc/opt/influxdb/influxdb.conf
```

is completely unnecessary, and changed the directory paths of the config file to paths inaccesible by the `influxdb` user. If you had skipped that step everything would have worked perfectly. Please let me know if you have any more questions.

**Comment by llevar** [comment]
Thanks for responding @otoolep.
In my understanding the step is necessary to customize configuration. Which I need to do. I indicated the step in its current form just to simplify the test case and rule out my customizations messing normal operation.

The reason I put the config into /etc/opt/influxdb/influxdb.conf is because that was the path that was specified in the service script at /etc/init.d/influxdb. I assume that's the path set up by the installer as I hadn't configured it at any point prior.

```
/etc/opt/influxdb/influxdb.conf 
107 # Configuration file
108 config=/etc/opt/influxdb/influxdb.conf
```

Is this how config file path specification for the service script supposed to work, or have I gotten confused?

Thanks for your help.

**Comment by otoolep** [comment]
@llevar -- yes, but the easiest way to customize the configuration script is to copy what is put there by the installation script as a backup, and then edit in place the original file in `/etc/opt/influxdb/influxdb.conf`. If you break it you can just put the copy back and start again. Make sense?

**Comment by beckettsean** [comment]
I opened https://github.com/influxdb/influxdb.com/issues/247 to make this all more clear in the docs.

**Comment by llevar** [comment]
So is it the case that the default config-file file permissions need to be preserved, and I messed things up by overwriting the file instead of editing it in place? How does that relate to the error message that indicates the program trying to write to /root/.influxdb and failing? Which location, that the influxdb user has access to, are those files supposed to go into?

**Comment by otoolep** [comment]
When you overwrote the default config file, it replaced the directories used for storage by InfluxDB with your home directories. Since you are root on this box, the home directories are in root.

**Comment by llevar** [comment]
So what's the way out? I need to deploy this out to a cluster periodically with customized config. Do I need to replicate the permissions of the original config script in order for it to not mess with the wrong directories? My plan was to deploy this via a config management tool rather than editing a file in place.

**Comment by beckettsean** [comment]
The config script does not have permissions, it references directories. When you run `/opt/influxdb/influxd config > /etc/opt/influxdb/influxdb.conf` the outputted config file puts all the directories under `~`. When you are root, `~` translates to `/root`.

If you don't want to use `/root` as your InfluxDB data directory there are a few options.

1. Run `/opt/influxdb/influxd config > /etc/opt/influxdb/influxdb.conf` as the user you want to run `influxd`. Then the config file will use that user's home directory as the install location.
1. Explicitly edit ` /etc/opt/influxdb/influxdb.conf` to reference the directories you want to use.

**Comment by llevar** [comment]
Ok that clears it up, thanks. But the installation guide here - https://influxdb.com/docs/v0.9/introduction/installation.html#ubuntu-debian

doesn't really mention needing to run as the influxdb user. In fact the top of the guide states that the configuration needs to be run by someone who has root. Clarifying this would probably help the next chap trying to go through this guide. 

Thanks again.

**Comment by unlikelyzero** [comment]
Ran into this again in 12.1

**Comment by beckettsean** [comment]
@unlikelyzero this is a very old issue about a version that is out of date. Please open a new issue if you feel there are improvements needed to the Ubuntu package.

**Comment by claytondukes** [comment]
Seems this is a problem again at least on Ubuntu 16 installing influxdb v1.0.2. The problem is that `/lib/systemd/system/influxdb.service` has:
```User=influxdb
Group=influxdb
```

But `/etc/influxdb/influxdb.conf` has several options set to root:
```
dir = "/root/.influxdb/meta"
dir = "/root/.influxdb/data"
wal-dir = "/root/.influxdb/wal"
```

What I don't know is if this happened during apt install or me messing around trying to get it to work by generating a config as the root user using `influxd config > influxdb.generated.conf`
