### ISSUE TITLE
[0.9.3-rc2] InfluxDB start as root if start-stop-daemon is not present

### ISSUE THREAD

**Issue by KoeSystems** [influxdb/influxdb#3803]
This bug is related with PR 3115 merged and closed for 0.9.3.

If start-stop-daemon is not present, this happens in CentOS, Fedora and RedHat (maybe more), then influxdb is started as root.

```
[koe@localhost init.d]$ sudo service influxdb start
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]

[koe@localhost init.d]$ ps -ef| grep influxdb
root      1245     1  0 00:53 pts/0    00:00:00 /opt/influxdb/influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/influxdb.conf
```

**Comment by beckettsean** [comment]
@KoeSystems do you have a PR or suggestion how to fix this? We're not packaging experts for CentOS

**Comment by KoeSystems** [comment]
@beckettsean This has been solved in https://github.com/influxdb/influxdb/pull/3804

**Comment by otoolep** [comment]
Oh yeah, I should have closed this. Thanks @KoeSystems
