### ISSUE TITLE
Can I count and group into 24h?

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#3810]
I can use group by time(1h) to see datas across every hour, but what if I want to see the data group by each hour in 24 hours so I can see on which hour users are most active?

**Comment by jhorwit2** [comment]
`select count(user_id_column) from measurement where time > now() - 24h and group by time(1h)`

**Comment by beckettsean** [comment]
I think this is a duplicate request to https://github.com/influxdb/influxdb/issues/2241. Closing in favor of that. @airyland please add more detail to that issue if you like.
