### ISSUE TITLE
[0.9.2] RPM is missing a dependency (coreutils)

### ISSUE THREAD

**Issue by johncagle** [influxdb/influxdb#3816]
When trying to incorporate influxdb into an appliance ISO, installs may fail because the post-install script of influxdb's RPM uses rm, ln, chown, chmod, etc. which are binaries from the coreutils RPM. Please add coreutils as a dependency of influxdb.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/commit/55d9c9bfaa1836ac251e4f175d3a5bef7dc0164f
