### ISSUE TITLE
Installation instructions missing 'influxd' instruction for OSX users

### ISSUE THREAD

**Issue by yoniholmes** [influxdb/influxdb#3826]
Can someone please add either of the below (which ever is correct) to the OS X installation instructions?
```
$ influxd
``` 
or 
```
$ sudo /etc/init.d/influxdb start
``` 

It's there for the linux distro instructions, but missing for the OS X instructions. I actually uninstalled influxdb while evaluating it because the current instructions lead to the below error, arising because I hadn't actually started the daemon:

```bash
$ influx
Failed to connect to http://localhost:8086
InfluxDB shell 0.9.2
```

whereas this worked:

```bash
$ influxd

#  then in a separate shell:

$ influx
Connected to http://localhost:8086 version 0.9.2
InfluxDB shell 0.9.2
```

This might save other people evaluating your tool a bit of time and frustration. 

Hope it helps, 

Jonathan

**Comment by beckettsean** [comment]
@yoniholmes are you talking about the post-install instructions in the package or the instructions on the installation docs page?

**Comment by yoniholmes** [comment]
Hi Sean, 

Thanks for your response. I'm specifically talking about the [Installation page](https://influxdb.com/docs/v0.9/introduction/installation.html) on the web docs. If you take a look, both 'Ubuntu & Debian' and 'RedHat & CentOS' have the step 'Then start the daemon by running:'.  OS X doesn't. Because I was ignoring the first two and only focusing on OSX, I didn't realise that I need to start the daemon. 

Subsequently, on the [Getting started](https://influxdb.com/docs/v0.9/introduction/getting_started.html) page there's no mention of needing to have the daemon started. Under 'Logging in and creating your first database' it should also probably read: 

> If you’ve installed InfluxDB locally, the `influx` command should be available via the command line. ***Once you have started the InfluxDB daemon (see [Installation](https://influxdb.com/docs/v0.9/introduction/installation.html) instructions)***, executing `influx` will start the CLI and automatically connect to the local InfluxDB instance. If `influx` is not on your path, try `/opt/influxdb/influx`. The output should look like this:

Thanks,

Jonathan

**Comment by beckettsean** [comment]
Thanks, @yoniholmes. I'm closing in favor of new issue on docs repo: https://github.com/influxdb/influxdb.com/issues/251

**Comment by yoniholmes** [comment]
thanks

**Comment by eostermueller** [comment]
+1
