### ISSUE TITLE
Delay in InfluxDB data read with 0.9.3-rc2

### ISSUE THREAD

**Issue by chaithrar** [influxdb/influxdb#3844]
Hi,

We are using the influx (0.9.3-rc2) , though influxdb logs says write successful, the same data can be read only after 4/5 minutes

Influx db container logs

Aug 25 22:17:35 host sh[36179]: [http] 2015/08/25 22:17:35 10.6.30.1 - - [25/Aug/2015:22:17:35 +0000] POST /write?consistency=&db=indb&precision=&rp=custom_rp HTTP/1.1 204 0 - InfluxDBClient 16658a6a-4b77-11e5-9d36-000000000000 35.512µs 

select * from test where time > now() - 1m limit 10

This query returns no data. But if we wait for more 4/5 minutes data written at "22:17:35" can be retrieved.

The data is written in UTC and read in UTC time zones.

**Comment by pauldix** [comment]
Are you sure you're not writing data with future time stamps? What if you make your query:

```sql
select * from test where time > now() - 1m and time < now() + 200h limit 10
```

**Comment by pauldix** [comment]
Or, can you provide a script or way to reproduce this?

**Comment by pauldix** [comment]
Another question, is this a totally fresh database or an upgrade from 0.9.2?

**Comment by chaithrar** [comment]
select * from test where time > now() - 1m and time < now() + 200h limit 10

This query returned 0 records

We created fresh new database to test new version of influx

**Comment by pauldix** [comment]
Can you show exactly what data you're writing in? Can you give us exact steps to reproduce? What do we set up, how do we write data? We have no way to reproduce this and a failure this basic should show up in about 50 different tests in our suite.

**Comment by pauldix** [comment]
Can you try again with RC3 released last night? There was one query bug in there that might have thrown things off. See #3829. Closing for now, please re-open if you see this again.

**Comment by beckettsean** [comment]
@pauldix I did notice that in both this issue and https://github.com/influxdb/influxdb/issues/3825 the writes are going to a retention policy other than the auto-generated `default`. I tried to repro in 0.9.3-rc2 with a newly created default RP and it worked as expected. However my test database was brand new and has no load.

**Comment by eliperelman** [comment]
I am able to reproduce this, or something like it locally using a brand new database. Some tables seem to be available instantly while others take several minutes. I've noticed that if I tried writing data several times that it starts to resolve.

**Comment by beckettsean** [comment]
@eliperelman can you paste in your repro steps, ideally in CLI format?

**Comment by eliperelman** [comment]
@beckettsean hopefully this will suffice :)

Steps:

1. `drop database raptor; create database raptor`
2. `show measurements` to make sure nothing is there
3. write the data [1] using HTTP
4. `select * from annotation`: there is a single record
5. `select * from measure limit 5`: nothing

[1]

```
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-html-load,phase=restartb2g,test=restart-b2g value=4978 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-settings-loadstart,phase=restartb2g,test=restart-b2g value=4990 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-loadstart,phase=restartb2g,test=restart-b2g value=5435 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-jsm-loaded,phase=restartb2g,test=restart-b2g value=546.455 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-bootstrap,phase=restartb2g,test=restart-b2g value=9250 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-start,phase=restartb2g,test=restart-b2g value=9255 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-system-frame-set,phase=restartb2g,test=restart-b2g value=9483 1441319788996000001
measure,branch=master,context=b2g,device=flame-kk,memory=319,metric=gecko-shell-notify-content-start,phase=restartb2g,test=restart-b2g value=9937 1441319788996000001
measure,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=loadEnd,phase=restartb2g,test=restart-b2g value=10840 1441319788996000001
measure,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=ftuSkip,phase=restartb2g,test=restart-b2g value=16123 1441319788996000001
measure,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=homescreenStart,phase=restartb2g,test=restart-b2g value=16637 1441319788996000001
measure,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=navigationLoaded,phase=restartb2g,test=restart-b2g value=16916 1441319788996000001
measure,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=navigationInteractive,phase=restartb2g,test=restart-b2g value=16922 1441319788996000001
measure,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=visuallyLoaded,phase=restartb2g,test=restart-b2g value=17767 1441319788996000001
measure,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=visuallyLoaded,phase=restartb2g,test=restart-b2g value=21140 1441319788996000001
measure,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=contentInteractive,phase=restartb2g,test=restart-b2g value=21145 1441319788996000001
measure,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=osLogoEnd,phase=restartb2g,test=restart-b2g value=21596 1441319788996000001
measure,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=fullyLoaded,phase=restartb2g,test=restart-b2g value=21847 1441319788996000001
memory,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=pss,phase=restartb2g,test=restart-b2g value=25188892.672 1441319788996000001
memory,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=rss,phase=restartb2g,test=restart-b2g value=37535875.072 1441319788996000001
memory,branch=master,context=verticalhome.gaiamobile.org,device=flame-kk,memory=319,metric=uss,phase=restartb2g,test=restart-b2g value=19067305.984 1441319788996000001
memory,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=uss,phase=restartb2g,test=restart-b2g value=67239936 1441319788996000001
memory,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=rss,phase=restartb2g,test=restart-b2g value=88256544.768 1441319788996000001
memory,branch=master,context=system.gaiamobile.org,device=flame-kk,memory=319,metric=pss,phase=restartb2g,test=restart-b2g value=74822189.056 1441319788996000001
annotation text="Gaia: ea8866ae99d5e298,<br/>Gecko: 1f20d26a0b2bfc11" 1441319788996
```

![2](https://cldup.com/aKfCLRSbL1-3000x3000.png)

**Comment by eliperelman** [comment]
It took about 4-5 minutes for the data to show up in the query:

![1](https://cldup.com/cqKrJjUzSR-2000x2000.png)

**Comment by beckettsean** [comment]
@eliperelman those repro steps don't work for me:

```
> create database raptor
> use raptor
Using database raptor
> show measurements
```

Then `curl -i -XPOST 'http://localhost:8086/write?db=raptor' --data-binary @points.txt` where `points.txt` contains the lines you provided above.

```
> show measurements
name: measurements
------------------
name
annotation
measure
memory

> select * from memory
name: memory
------------
time				branch	context				device		memory	metric	phase		test		value
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	pss	restartb2g	restart-b2g	2.5188892672e+07
2015-09-03T22:36:28.996000001Z	master	system.gaiamobile.org		flame-kk	319	pss	restartb2g	restart-b2g	7.4822189056e+07
2015-09-03T22:36:28.996000001Z	master	system.gaiamobile.org		flame-kk	319	rss	restartb2g	restart-b2g	8.8256544768e+07
2015-09-03T22:36:28.996000001Z	master	system.gaiamobile.org		flame-kk	319	uss	restartb2g	restart-b2g	6.7239936e+07
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	uss	restartb2g	restart-b2g	1.9067305984e+07
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	rss	restartb2g	restart-b2g	3.7535875072e+07

> select * from memory limit 5
name: memory
------------
time				branch	context				device		memory	metric	phase		test		value
2015-09-03T22:36:28.996000001Z	master	system.gaiamobile.org		flame-kk	319	uss	restartb2g	restart-b2g	6.7239936e+07
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	uss	restartb2g	restart-b2g	1.9067305984e+07
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	rss	restartb2g	restart-b2g	3.7535875072e+07
2015-09-03T22:36:28.996000001Z	master	verticalhome.gaiamobile.org	flame-kk	319	pss	restartb2g	restart-b2g	2.5188892672e+07
2015-09-03T22:36:28.996000001Z	master	system.gaiamobile.org		flame-kk	319	pss	restartb2g	restart-b2g	7.4822189056e+07
```

When you inserted the points, were the timestamps slightly in the future? By default, the time range for `SELECT * FROM foo` runs from `epoch 0` to `now()`. If the points are more in the future than `now()` they will not be returned unless you include `WHERE time < now() + 15m` or whatever makes an appropriate upper bound.

**Comment by beckettsean** [comment]
That would also explain why the `annotation` point shows up. It's got a timestamp that's actually in milliseconds, but was written at nanosecond precision. The actual timestamp is thus a few minutes after epoch 0 and would always be in the default time range for a `SELECT *` statement.

**Comment by eliperelman** [comment]
Ugh.

@beckettsean great find, and you are totally correct. My InfluxDB instance lives in a docker container, which for some reason has a clock that is about 5 minutes behind my system time. Thanks for the effort, I appreciate it.

![picard](http://picardfacepalm.com/picard-facepalm.jpg)

**Comment by beckettsean** [comment]
No worries, @chaithrar I'm glad we got to the bottom of that.
