### ISSUE TITLE
[0.9.3-rc3] influxdb large io write

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#3847]
influxdb 0.9.3rc3
centos 7.1 xfs file system
raid 1 disk
http input
using influxdb-ruby client to submit 6000 metric per post and 3 thread
iotop show actual disk write is high,but the influxdb data dir not big
```
[root@influxdb influxdb]# du -sk *
520224	data
0	hh
40	meta
72428	wal

Total DISK READ :       0.00 B/s | Total DISK WRITE :       9.04 M/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:      98.98 M/s
  PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
47210 be/4 root        0.00 B/s    2.45 M/s  0.00 %  0.12 % influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/influxdb.conf
```

**Comment by pauldix** [comment]
Not sure what you're reporting here. What's the problem exactly? How many total data points did you write?

**Comment by huhongbo** [comment]
the problem is the actual disk write is 98.98M/s , influxdb write do so many iops and actual disk write, my actual datapoint is about 10000 points/s

**Comment by pauldix** [comment]
Is this with a fresh database? Can you try the 0.9.3 release?

**Comment by huhongbo** [comment]
yes ,it's a fresh database 
I've test the 0.9.3 and has the same result,I want to know it's normal to get the high actual disk write?

Total DISK READ :       0.00 B/s | Total DISK WRITE :       5.78 M/s
Actual DISK READ:       0.00 B/s | Actual DISK WRITE:     298.49 M/s
  PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
11616 be/4 root        0.00 B/s    5.72 M/s  0.00 %  0.27 % influxd -pidfile /var/run/influxdb/influxd.pid -config /etc/opt/influxdb/influxdb.conf

**Comment by pauldix** [comment]
After a bunch of testing, we've determined that the underlying index just can't keep up with the insertion load that the WAL makes possible. To prevent the system from going OOM and dying we're going to put back pressure on the write clients and start failing writes when memory gets too high. See #4066.

We're also working on a massive storage engine upgrade that will fix this. Should be available in the nightlies within a week or two. It will have much better compression and be able to keep up with the write load of the WAL.

More soon...

**Comment by huhongbo** [comment]
good news

**Comment by pauldix** [comment]
Closing this out to consolidate. Track #4086 for when this is done.
