### ISSUE TITLE
Failed to connect to http://localhost:8086

### ISSUE THREAD

**Issue by hellofishy** [influxdb/influxdb#3854]
Hi,

I am new to influxdb and just downloaded it via homebrew.  When I try to run $:influx I get
Failed to connect to http://localhost:8086.  I was wondering if anyone else had this problem and how to get around it?

**Comment by otoolep** [comment]
Can you explain what you expected to happen? You are running the command-line tool, not the database. The database binary is `influxd`, which you also need to run.

**Comment by hellofishy** [comment]
awesome! thanks, didn't realize I had to do that

**Comment by zhanglingzhi1988** [comment]
you can try 

influx -host   111.222.333.444   

or (if you has pass)
influx -host   111.222.333.444   -username userExample -password  passExample


and  replace the 111.222.333.4444 to  your Private Net IP
