### ISSUE TITLE
[0.9.3] Slowness on SELECT queries

### ISSUE THREAD

**Issue by dstreppa** [influxdb/influxdb#3865]
I have problems with InfluxDB (my first experience with TSDB), regarding slowness of SELECT queries. Here is my configuration:

**Server:**
CPUs: 2 x Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
RAM: 4 Gb
OS: CentOS 6.7

**InfluxDB:**
Version: 0.9.1
DB size: 66 Gb
Datapoints: ~800 millions
Measurements: 15
Tags: 2 (item and signal the keys)
Fields: 3 (value, value_raw and flag (not used))
Data resolution: 10 seconds

The problem is that some queries are very slow. For example if I want to show with Grafana 2.x the last 30d values of 15 different signals ( ~3.9 milions of datapoints) I have to wait a lot, the last test yesterday more than 6 minutes!
Obviously less are the requested data faster are the queries.

I don't think is a Grafana problem, because the same happens if we extract data via curl.

Here a query that gives you and idea on how my measurements are structured:

```
> select value from gridsense_HH04_techroom WHERE signal='V_avg' and item='Boiler' AND time > '2015-08-23 23:00:00' AND time < '2015-08-23 23:01:00'
name: gridsense_HH04_techroom
-----------------------------
time			value
2015-08-23T23:00:10Z	410.3
2015-08-23T23:00:20Z	409.9
2015-08-23T23:00:30Z	410.3
2015-08-23T23:00:40Z	409.6
2015-08-23T23:00:50Z	409.2
```

Here is the InfluxDB log during the last test (30d values of 15 different couples item/signal on 5 measurements, my Grafana requests started at ~09:21:30), maybe it can help:

```
[dstrepparava@ununpentio~]$ tail -f /var/log/influxdb/influxd.log
[shard] 2015/08/26 09:23:05 flush 70181 points in 34.258s
[http] 2015/08/26 09:23:28 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22trevano_HH00_roofhouse%22+WHERE+item%3D%27PV%27+AND+signal%3D%27V_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 12973 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 12b384d4-4bc3-11e5-9868-000000000000 1m57.163390697s
[http] 2015/08/26 09:23:30 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH01_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27I_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 11173 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 12b38aee-4bc3-11e5-9869-000000000000 1m59.821391517s
[shard] 2015/08/26 09:23:41 flush 77527 points in 34.700s
[http] 2015/08/26 09:23:52 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH04_techroom%22+WHERE+item%3D%27PV%27+AND+signal%3D%27I_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 11147 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 12b0ba02-4bc3-11e5-9867-000000000000 2m21.332284949s
[http] 2015/08/26 09:23:56 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22trevano_HH00_roofhouse%22+WHERE+item%3D%27PV%27+AND+signal%3D%27I_a%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 14140 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 1286b3a2-4bc3-11e5-9865-000000000000 2m26.103929988s
[http] 2015/08/26 09:24:02 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH02_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27I_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 11354 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 1286a1da-4bc3-11e5-9864-000000000000 2m31.790005849s
[http] 2015/08/26 09:24:03 127.0.0.1 - - [26/Aug/2015:09:21:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH03_techroom1%22+WHERE+item%3D%27PV%27+AND+signal%3D%27I_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 11144 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 12aae93d-4bc3-11e5-9866-000000000000 2m32.405311113s
[shard] 2015/08/26 09:24:11 flush 72054 points in 28.040s
[retention] 2015/08/26 09:24:38 retention policy enforcement check commencing
[retention] 2015/08/26 09:24:38 retention policy shard deletion check commencing
[shard] 2015/08/26 09:25:02 flush 73792 points in 48.114s
[http] 2015/08/26 09:25:18 127.0.0.1 - - [26/Aug/2015:09:23:28 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH01_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27V_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 10374 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 588d55e0-4bc3-11e5-986d-000000000000 1m50.891000904s
[http] 2015/08/26 09:25:33 127.0.0.1 - - [26/Aug/2015:09:23:30 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH02_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27V_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 10318 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 5a298299-4bc3-11e5-986e-000000000000 2m2.836297031s
[shard] 2015/08/26 09:25:42 flush 69551 points in 38.081s
[http] 2015/08/26 09:26:11 127.0.0.1 - - [26/Aug/2015:09:24:03 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH01_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27kW_tot%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 9659 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 6d876a49-4bc3-11e5-9874-000000000000 2m8.144684598s
[shard] 2015/08/26 09:26:24 flush 64878 points in 40.091s
[http] 2015/08/26 09:26:49 127.0.0.1 - - [26/Aug/2015:09:23:52 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH03_techroom1%22+WHERE+item%3D%27PV%27+AND+signal%3D%27V_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 10222 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 66eee258-4bc3-11e5-9870-000000000000 2m56.853959139s
[http] 2015/08/26 09:26:55 127.0.0.1 - - [26/Aug/2015:09:24:02 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22trevano_HH00_roofhouse%22+WHERE+item%3D%27PV%27+AND+signal%3D%27kW_tot%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 14494 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 6d025685-4bc3-11e5-9873-000000000000 2m53.198368897s
[http] 2015/08/26 09:27:04 127.0.0.1 - - [26/Aug/2015:09:23:56 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH04_techroom%22+WHERE+item%3D%27PV%27+AND+signal%3D%27V_avg%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 10378 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 69a8985e-4bc3-11e5-9871-000000000000 3m7.312434092s
[shard] 2015/08/26 09:27:06 flush 75210 points in 40.392s
[http] 2015/08/26 09:27:42 127.0.0.1 - - [26/Aug/2015:09:25:19 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH02_garage%22+WHERE+item%3D%27PV%27+AND+signal%3D%27kW_tot%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 9993 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 9ab5cfc0-4bc3-11e5-9879-000000000000 2m23.438978789s
[http] 2015/08/26 09:27:42 127.0.0.1 - - [26/Aug/2015:09:25:33 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH03_techroom1%22+WHERE+item%3D%27PV%27+AND+signal%3D%27kW_tot%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 9806 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 a36bbd1a-4bc3-11e5-987a-000000000000 2m9.215933054s
[http] 2015/08/26 09:27:52 127.0.0.1 - - [26/Aug/2015:09:26:11 +0200] GET /query?db=ebm&p=xxx&q=SELECT+mean%28value%29+FROM+%22gridsense_HH04_techroom%22+WHERE+item%3D%27PV%27+AND+signal%3D%27kW_tot%27+AND+time+%3E+now%28%29+-+30d+GROUP+BY+time%2830m%29+ORDER+BY+asc&u=ebm HTTP/1.1 200 10971 http://gridsense.supsi.ch:3000/dashboard/db/pv-plants Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0 b9f30c06-4bc3-11e5-987e-000000000000 1m40.801375318s﻿
```

**Comment by dstreppa** [comment]
@beckettsean Regarding your questions on G+:
* Tag *item* can assume 10 possible values
* Tag *signal* can assume 74 possible values
* Memory usage: below there is the output of *top -b -d2 | grep influxd* during 30d querying just done.

`16446 influxdb  20   0 79.0g 924m 817m S  0.0 24.1  34:37.85 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 924m 817m S  0.5 24.1  34:37.86 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 928m 817m S 11.9 24.2  34:38.10 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 931m 819m S 14.4 24.3  34:38.39 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 933m 820m S 10.0 24.4  34:38.59 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 936m 822m S  3.5 24.4  34:38.66 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 938m 825m S  3.5 24.5  34:38.73 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 941m 827m S  2.5 24.6  34:38.78 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 943m 830m S  6.0 24.6  34:38.90 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 946m 832m S  8.0 24.7  34:39.06 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 949m 834m S  6.5 24.8  34:39.19 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 951m 837m S  4.5 24.8  34:39.28 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 953m 839m S 13.4 24.9  34:39.55 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 955m 841m S  5.0 24.9  34:39.65 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 957m 843m S  6.0 25.0  34:39.77 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 963m 848m S 12.4 25.2  34:40.02 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 967m 850m S 10.0 25.3  34:40.22 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 970m 853m S  4.0 25.3  34:40.30 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 972m 855m S  4.0 25.4  34:40.38 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 974m 857m S  4.0 25.4  34:40.46 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 976m 859m S  3.5 25.5  34:40.53 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 978m 861m S  5.5 25.5  34:40.64 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 980m 863m S  4.5 25.6  34:40.73 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 982m 865m S  6.0 25.6  34:40.85 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 983m 866m S  9.0 25.7  34:41.03 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 984m 867m S  7.5 25.7  34:41.18 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 986m 869m S  9.5 25.7  34:41.37 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 987m 870m S  5.5 25.8  34:41.48 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 987m 870m S  0.5 25.8  34:41.49 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 987m 870m S  0.0 25.8  34:41.49 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 987m 870m S  0.0 25.8  34:41.49 influxd`                                                                                                                      
`16446 influxdb  20   0 79.0g 987m 870m S  0.5 25.8  34:41.50 influxd`

**Comment by otoolep** [comment]
You should upgrade to 0.9.3. We have made significant improvements to query
performance since 0.9.1.

**Comment by dstreppa** [comment]
OK, I already planned the upgrade for Monday

**Comment by beckettsean** [comment]
@dstreppa thanks for the additional info on your tags. 

Your cardinality is fine and the number of points is also reasonable. I notice in your log statements that the WAL flushes are taking 30-40 seconds. 0.9.3 should significantly reduce that. That combined with the very long query times (1-2 minutes) strongly suggests that the box is just overwhelmed. 

Are you continually writing points to the database? If so, how?

**Comment by dstreppa** [comment]
Exactly, what is the meaning of WAL?

Anyways, I decided to double the ram of the box in the next days. It was planned for the end of the year, but now it is useless to wait.

@beckettsean I insert new data hourly using a Python script that calls curl command. I use LINE protocol, the data files are of 5000 rows. I never noted problems about inserting.

**Comment by beckettsean** [comment]
WAL is the write-ahead log. It quickly persists points to disk and batches them into efficient sized blocks for writing into the BoltDB files that form the permanent storage engine for InfluxDB. Flushes should take seconds, but not 30-40. 

Let us know how the new RAM changes performance.

**Comment by dstreppa** [comment]
OK, so it seems to me that WAL regards inserting not querying...am I right?

Here an extract of my data file in LINE protocol:

`gridsense_HH03_techroom,item=PV,signal=V_avg value=238.2,value_raw=238.2 1437868750`
`gridsense_HH03_techroom,item=PV,signal=V_avg value=238.2,value_raw=238.2 1437868760`
`gridsense_HH03_techroom,item=PV,signal=V_avg value=238.3,value_raw=238.3 1437868790`
`gridsense_HH03_techroom,item=PV,signal=I_avg value=0.12,value_raw=0.12 1437696000`
`gridsense_HH03_techroom,item=PV,signal=I_avg value=0.119,value_raw=0.119 1437696010`

**Comment by beckettsean** [comment]
@dstreppa Points in the WAL are available to queries. There's an in-RAM copy that handles queries. Does that answer your question?

Have you upgraded to 0.9.3?

**Comment by dstreppa** [comment]
Thank you very much for the response Sean. 
I upgraded to 0.9.3. The big queries described above are still too long, instead the WAL flushes are much faster (max. 10 seconds, usually not more than 4).
Anyway, the memory will be doubled this week.

**Comment by beckettsean** [comment]
@dstreppa pulling one of your queries out of the logs it looks like this:

`SELECT mean(value) FROM "trevano_HH00_roofhouse" WHERE item='PV' AND signal='I_a' AND time > now() - 30d GROUP BY time(30m) ORDER BY asc`

That's a 30 day historical query, which pulls all 3.9 million data points off disk. It's a very expensive one to run over and over. Instead, just run it once with a continuous query and then grab that data:

```
CREATE CONTINUOUS QUERY foo ON mydb BEGIN
  SELECT mean(value) FROM "trevano_HH00_roofhouse" INTO new_measurement GROUP BY time(30m), *
END
```

That CQ will automatically put the 30 minute MEAN into a new measurement, which you can quickly query with `SELECT value FROM new_measurement WHERE item='PV' AND signal='I_a' AND time > now() - 30d`.

The queries aren't necessarily slow considering they are sampling nearly 4 million points. Are you using SSDs or spinning disks?

**Comment by dstreppa** [comment]
@beckettsean I see the problem. I am already trying CQ solution, and it works fine. Unfortunately there are two negative aspects:
* I have ~4 months of data without CQ and it seems to me it is not possible to recalculate CQ on data already in DB  (#211 and https://influxdb.com/docs/v0.9/query_language/continuous_queries.html). My fault, due to my limited experience outside SQL-world :)
* The minimal resolution that I reach with CQ is 1h, if I go under with GROUP BY time(30m, 10m,..., 1m) the CQ do not work. I must insert data once an hour all together (at hour x+1 I insert data of hour x) and I can't change this procedure. I think this is the cause.

**Comment by beckettsean** [comment]
> it is not possible to recalculate CQ on data already in DB 

That is correct. We will be implementing backfill for CQs soon, possibly in the 0.9.5 release.

> The minimal resolution that I reach with CQ is 1h, if I go under with GROUP BY time(30m, 10m,..., 1m) the CQ do not work.

That is not expected behavior. I've successfully run CQs with `GROUP BY time(1s)`, so I know it does function. Are your timestamps out of date when being written? If your timestamps are 30 minutes old by the time they hit the database then CQs grouping by less than 30 minutes would never see any matching points.

**Comment by dstreppa** [comment]
@beckettsean I also think the problem is due to out-of-date timestamps. When inserted in DB, the data can have timestamps 60 minutes old. As said before, unfortunately I can't change the acquisition procedure.

**Comment by beckettsean** [comment]
@dstreppa That's a known limitation, but one that will be mitigated by https://github.com/influxdb/influxdb/issues/211. Hopefully that issue will be addressed in a month or so.
