### ISSUE TITLE
A modulo (%) Operator...

### ISSUE THREAD

**Issue by chromos33** [influxdb/influxdb#3871]
would be nice especially for the Where Clauses to only select Values form series every full hour.(Without using group by).

**Comment by pauldix** [comment]
Not sure I know what this means. Can you elaborate?

**Comment by beckettsean** [comment]
@chromos33 can you give an example of a query that would show the usefulness?

**Comment by chromos33** [comment]
sry opened this thread prematurely wanted to only show hour values while maintaining a group by with time(5m) since in our original query structure of trying to encompasse all variables , the results were not what they should have been. Am now doing multiple queries of the same series with different class of Tags and sum them up in php, since the other way around did not result in expected or rather wanted results.
