### ISSUE TITLE
RC versions are recognized as higher than release versions by yum

### ISSUE THREAD

**Issue by cannium** [influxdb/influxdb#3879]
For example, `influxdb-0.9.3_rc2-1.x86_64` is higher than `influxdb-0.9.3-1.x86_64`

Some reference: http://fedoraproject.org/wiki/Packaging%3aNamingGuidelines#NonNumericRelease

**Comment by otoolep** [comment]
OK, thanks, we'll look into it.

**Comment by beckettsean** [comment]
@otoolep any thoughts on tackling this before 0.9.4_rc1? @pauldix would love to fix this before that RC.

**Comment by otoolep** [comment]
I can take a look, might be easy.

**Comment by otoolep** [comment]
@cannium -- it looks like if we rename our pre-release packages something like:

influxdb-0.9.3rc2-1.x86_64

that might do it? I'm looking at the Mozilla source example. 

The document is dense, if you know the right form, just let me know. :-)

**Comment by otoolep** [comment]
Or maybe `influxdb-0.9.3-0.1.rc2.x86_64` following  "Upgrade Path Example (alsa-lib)"

**Comment by cannium** [comment]
I Believe `influxdb-0.9.3-0.1.rc2.x86_64` is the correct version:
```
# rpmdev-vercmp 0.9.3-0.1.rc2 0.9.3-1
0:0.9.3-1 is newer
# rpmdev-vercmp 0.9.3rc2-1 0.9.3-1
0:0.9.3rc2-1 is newer
# rpmdev-vercmp 0.9.3_rc2-1 0.9.3-1
0:0.9.3_rc2-1 is newer
```

**Comment by otoolep** [comment]
@cannium -- what if you do: 0.9.3-1.rc2  vs 0.9.3-1 ?

Otherwise our packaging script is going to be painful.

**Comment by cannium** [comment]
```
# rpmdev-vercmp 0.9.3-1.rc2  0.9.3-1
0:0.9.3-1.rc2 is newer
```
You could install the tool by `yum install rpmdevtools` and compare them yourself.

**Comment by otoolep** [comment]
Thanks for that.

I am running Ubuntu, and it's a pain getting those tools, short of spinning
up a Fedora VM. I will though, need to run some more checks.

**Comment by matwey** [comment]
> For example, influxdb-0.9.3_rc2-1.x86_64 is higher than influxdb-0.9.3-1.x86_64

It is probably should be influxdb-0.9.3~rc2, AFAIR ~ has special meaning in RPM version lexicographical comparison. It is always less even than end of the string.

**Comment by otoolep** [comment]
I will get this done for 0.9.5.

**Comment by otoolep** [comment]
PR to change the script up at https://github.com/influxdb/influxdb/pull/4115

**Comment by otoolep** [comment]
Fixed by latest changes to packaging script.
