### ISSUE TITLE
Aggregation by time interval should support timezones

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#388]
This is related to #387, since we have to respect the natural boundaries of a day, week, etc. InfluxDB has to accept a timezone argument for each query which will be used to convert the stored timestamps, instead of assuming UTC all the time.

**Comment by k2xl** [comment]
+1

**Comment by 8igO** [comment]
+1

**Comment by jnutzmann** [comment]
+1

Any thoughts of getting this into the 0.9 release?

**Comment by Glavin001** [comment]
+1 would be great to have this in 0.9.0 release, however please do not hold that release up. This is a must for the future, although we should get 0.9.0 out ASAP. Thanks!

**Comment by kayhman** [comment]
+1

**Comment by toddboom** [comment]
This definitely needs to happen, but I'm moving this to #2074 to clean things up.
