### ISSUE TITLE
hard to manage data without delete or put support

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#3882]
If I import some bad points, I can do nothing but to drop the measurement. I cannot delete some unused data to reduce database size.

**Comment by mjdesa** [comment]
@airyland you can rewrite data a point by writing a to the same data point. e.g.

### Write a point
`curl -XPOST "http://localhost:8086/write?db=mydb" --data-binary "example value=10 148903244903284"`

#### Query it
`curl -G "http://localhost:8086/query?db=mydb" --data-urlencode "q=select * from example"`

yields

```json
{
    "results": [
        {
            "series": [
                {
                    "columns": [
                        "time",
                        "value"
                    ],
                    "name": "example",
                    "values": [
                        [
                            "1970-01-02T17:21:43.244903284Z",
                            10
                        ]
                    ]
                }
            ]
        }
    ]
}
```

### Re-write the point

`curl -XPOST "http://localhost:8086/write?db=mydb" --data-binary "example value=100 148903244903284"`

#### Query it

`curl -G "http://localhost:8086/query?db=mydb" --data-urlencode "q=select * from example"`

yields

```json
{
    "results": [
        {
            "series": [
                {
                    "columns": [
                        "time",
                        "value"
                    ],
                    "name": "example",
                    "values": [
                        [
                            "1970-01-02T17:21:43.244903284Z",
                            100
                        ]
                    ]
                }
            ]
        }
    ]
}
```

If I want to nullify the point I can re-write the point with a different field key like so:

`curl -XPOST "http://localhost:8086/write?db=mydb" --data-binary "example null=true 148903244903284"`

then when I query for it

`curl -G "http://localhost:8086/query?db=mydb" --data-urlencode "q=select * from example"`
 
the value is gone

```json
{
    "results": [
        {
            "series": [
                {
                    "columns": [
                        "time",
                        "null",
                        "value"
                    ],
                    "name": "example",
                    "values": [
                        [
                            "1970-01-02T17:21:43.244903284Z",
                            true,
                            null
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by beckettsean** [comment]
Also, there are open issues for improving [DELETE SERIES](https://github.com/influxdb/influxdb/issues/1647) and [DELETE](https://github.com/influxdb/influxdb/issues/2755) statements, so this is a duplicate of both.

**Comment by airyland** [comment]
Thx. But I couldn't find the related document?

**Comment by diiidiii** [comment]
I used the null=true statement of @mjdesa and got now the following structure:
> name: annotation
tags: host=iqtsdb01, measurement=system_load1
time                    null    value
----                    ----    -----
2015-09-09T17:01:40Z    true
2015-09-09T19:01:40Z    true
2015-09-09T20:21:00Z    true
2015-09-09T22:21:00Z    true


name: annotation
tags: host=, measurement=
time                    null    value
----                    ----    -----
2015-09-09T19:00:00Z            "Test"

Override the points which uses both tags (host and measurements) works excellent but now i want to rewrite the point with value "Test"... How can i do that?
I tried a lot of things:
> curl -i -XPOST 'http://iqtsdb01:8086/write?precision=s&db=telegraf' -d 'annotation,host=,measurement= null=true 1441863583'

Doesnt work: missing tag value

> curl -i -XPOST 'http://iqtsdb01:8086/write?precision=s&db=telegraf' -d 'annotation,host="",measurement="" null=true 1441863583'

Doesnt work: Creates new tags with content ""

> curl -i -XPOST 'http://iqtsdb01:8086/write?precision=s&db=telegraf' -d "annotation,host='',measurement='' null=true 1441863583"

Doesnt work: add a new series with host="" and measurement="" 

How can i re-write this point?

**Comment by mjdesa** [comment]
@diiidiii I'm having a hard time following what you're trying to do.

**Comment by beckettsean** [comment]
@diiidiii a point is uniquely defined by it's measurement name, the full tag set, and the timestamp. If you change the tags, it's not the same point. What @mjdesa suggested was setting the *fields* to something irrelevant like `null=true`. When you write a point with the same measurement name, same timestamp, but different *tag keys* OR *tag values*, you are writing a new point, not overwriting a previous point.

In your output:

```
name: annotation
tags: host=, measurement=
```

is telling you that the `host` and `measurement` tags have no value set. So, if you want to rewrite that point, you want to use the same *tag set*, which is an empty set, meaning no tags at all, not tag keys with no associated values. `curl -i -XPOST 'http://iqtsdb01:8086/write?precision=s&db=telegraf' -d 'annotation null=true 1441863583'` will overwrite the point with `null="Test"` as a field.

**Comment by diiidiii** [comment]
Ahh now i understand... Thank you for your help :)
