### ISSUE TITLE
Graphite plugin slow writes on version 0.9.2

### ISSUE THREAD

**Issue by tlopo** [influxdb/influxdb#3887]
I am trying to import data from influxdb-0.8.8 to influxdb-0.9.2, writes are very slow **10Kpbs**, importing the data from v.0.8.8 to another v.0.8.8 writing speed is **3.5Mbps** both running in the same box(ec2 c1.medium), but not simultaneously.

The script I used to import data: can be found [here](https://gist.github.com/tlopo/76cb4c20442cdb910f21). It does the following:
* Gets series list
* Creates a connection to graphite plugin
* For each serie run query `select * from <serie>`
* Creates an array with chunks of 1K datapoints in graphite format `<metric_name> <epoch> <value>`
* Send chunk by chunk
* Close connection

A snippet from the log generated by the script: 

```
==> 0.8.log <==
}

2015-08-28T20:21:52.418Z - info: Progress : 100%
{
 "seriesTotal": 10,
 "serieCount": 10,
 "chunksTotal": 165,
 "chunkCount": 165,
 "dataPointsSent": 1133497,
 "chunksSent": 1140,
 "bytesSent": 74801643,
 "chunksPerSec": 56,
 "bytesPerSec": 3707089
}

2015-08-28T20:21:52.418Z - info: Closing client

real	0m20.733s
user	0m3.012s
sys	0m0.808s

==> 0.9.log <==
}

2015-08-28T20:12:20.740Z - info: Progress : 100%
{
 "seriesTotal": 10,
 "serieCount": 10,
 "chunksTotal": 165,
 "chunkCount": 165,
 "dataPointsSent": 1132988,
 "chunksSent": 1138,
 "bytesSent": 74768150,
 "chunksPerSec": 0,
 "bytesPerSec": 10458
}

2015-08-28T20:12:20.741Z - info: Closing client

real	119m9.231s
user	0m3.536s
sys	0m0.916s
```

Any help will be appreciated.

**Comment by otoolep** [comment]
Couple of suggestions @tlopo.

If you are creating a brand new 0.9 system, I suggest you use 0.9.3. There are a large number of bug fixes and improvements in 0.9.3 vs 0.9.2.

In addition, ensure your Graphite batching is set to something sensible like 1000 points, and 1 second timeout.

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L138

I am going to assume these changes will address the issues, since others have had the same and batching fixed it.

**Comment by tlopo** [comment]
@otoolep  0.9.3 was released only two days ago, I missed that sorry. It did improved the writing speed a lot! it's still slower than 0.8.8 but I guess it's acceptable ~ 2Mbps. Thank you very much!

**Comment by otoolep** [comment]
We are continuing to improve throughput, and you may wish to try the nightly builds if you want bleeding edge.

https://influxdb.com/download/index.html

**Comment by otoolep** [comment]
You could also try increasing your batch size and timeout. Try 5K and 5 seconds.
