### ISSUE TITLE
create DEPENDENCY_LICENSES.md in the root of the repo

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3888]
list out the dependencies, their license, and link to their license files.

**Comment by beckettsean** [comment]
@toddboom @pauldix please chime in if you have any additional requirements. I made https://github.com/influxdb/telegraf/issues/154 on the telegraf repo.

**Comment by mjdesa** [comment]
https://github.com/influxdb/influxdb/pull/3891

**Comment by gunnaraasen** [comment]
Purely semantic request, can the file start with "license" so it will be listed next to the `LICENSE` file when viewing files in the repo root? E.g. `LICENSE_DEPENDENCIES` or `LICENSE_THIRD_PARTY`.

**Comment by otoolep** [comment]
This is done right, @gunnaraasen @beckettsean 

https://github.com/influxdb/influxdb/blob/master/LICENSE_OF_DEPENDENCIES.md

**Comment by beckettsean** [comment]
Yes, this is done. I closed the docs issue about it, didn't see this one.
