### ISSUE TITLE
improve error message in CLI when database not available

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#3894]
Alternate fix for https://github.com/influxdb/influxdb/issues/3855.

Launching `influx` before `influxd` is a fairly common source of confusion for new users. The current error message from `influx` does not make it clear that the database process is not available. 

```
$ influx
Connected to http://localhost:8086 version 
InfluxDB shell 0.9.3
> show databases
ERR: Get http://localhost:8086/query?db=&q=show+databases: dial tcp 127.0.0.1:8086: getsockopt: connection refused
> 
```

@otoolep found that MySQL's error is more clear:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

Can we get some more informative error that makes users more likely to realize they need to launch the daemon?

**Comment by otoolep** [comment]
We actually fixed this by correctly checking if the database is running. This is no longer an issue since the error message above should only be displayed in true error cases.
