### ISSUE TITLE
go1.5 and internal import policy prevents build on fork

### ISSUE THREAD

**Issue by fg2it** [influxdb/influxdb#3896]
Trying to submit PR to add options to package.sh, I forked and try to build influxdb from that fork. I was welcomed with : 
```
#go get failure; same for go install
package github.com/influxdb/influxdb/cluster
        imports github.com/influxdb/influxdb/cluster/internal: use of internal package not allowed
package github.com/influxdb/influxdb/meta
        imports github.com/influxdb/influxdb/meta/internal: use of internal package not allowed
package github.com/influxdb/influxdb/tsdb
        imports github.com/influxdb/influxdb/tsdb/internal: use of internal package not allowed
```
It seems this is related to go1.5 new policy with internal : it is not allowed to import internal from an external repo (see https://golang.org/doc/go1.5 and https://golang.org/s/go14internal).

By the way, I manage to build by changing internal import path in
```
cluster/rpc.go
meta/store.go
meta/data.go
meta/rpc.go
tsdb/meta.go
tsdb/shard.go
```
to point to my repo.

**Comment by beckettsean** [comment]
@otoolep thoughts on this Go 1.5 issue?

**Comment by otoolep** [comment]
Yeah, this looks annoying. Let me look into it.

**Comment by otoolep** [comment]
Easily reproducible, looking into it.

**Comment by fg2it** [comment]
thx for this. I am new to git and go and was unsure I wasn't missing something.

**Comment by otoolep** [comment]
Turns out our documentation re cloning forks needed updating. I have updated it here:

https://github.com/influxdb/influxdb/pull/3910

Please follow the instructions there to learn how to work with forks.
