### ISSUE TITLE
[0.9.3] high cpu usage while querying from influxdb

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#3900]
We have set up a cluster with 3 nodes. And we write to all of 3 nodes at about 600 qps and read from one of the nodes at about 100 qps.

As we found, the new version 0.9.3 influxdb will occupy much more cpu then version 0.9.2 while querying. And if we shut down the read application, the cpu usage will descend. There are 24 cores in our servers served influxd.

Below is the output while I run `perf top -p [pid]`

    13.6% scanblock                             
    12.3% compress/flate.(*compressor).findMatch
    11.1% sync/atomic.AddUint32                 
     6.2% runtime.mallocgc                      
     5.1% encoding/json.compact                 
     4.8% compress/flate.(*compressor).deflate  
     4.4% encoding/json.typeEncoder             
     4.0% runtime.MSpan_Sweep                   
     1.4% runtime.writebarrierptr               
     1.3% encoding/json.stateInString           

The low cpu idle will also impact the write performance of influxdb.

**Comment by ziyel** [comment]
Most of our query is like `select * from mt where time > 1441002714s`. And if I add `group by *` at the end of query, the use usage will descend. Is there any ideas about this?

**Comment by beckettsean** [comment]
@ziyel We need to take a look at your data to properly investigate this. Can you make a gzipped tarball of your `/data`, `/wal`, `/hh`, and `/meta` directories and share it with us? Please email support@influxdb.com if you prefer to share that data in private.

**Comment by otoolep** [comment]
The nightly builds have lots of improvements around query performance, queries should be rechecked.
