### ISSUE TITLE
SELECT on fake measurement without warning

### ISSUE THREAD

**Issue by dstreppa** [influxdb/influxdb#3903]
In the Influx client (server version: 0.9.3), a SELECT on a fake measurement has the same result of a SELECT on an existing measurement with an empty result (show the last two queries).

`> SELECT * FROM monitor WHERE host='Lamone' and process='mysqld' and time>'2015-08-31 12:36:00'`
`name: monitor`
`-------------`
`time			cpu_perc	host	mem_perc	process`
`2015-08-31T12:36:02Z	0		Lamone	0.79		mysqld`
`2015-08-31T12:36:03Z	0		Lamone	0.79		mysqld`
`2015-08-31T12:36:04Z	0		Lamone	0.79		mysqld`
`2015-08-31T12:36:06Z	0		Lamone	0.79		mysqld`

`> SELECT * FROM monitor WHERE host='Lamone' and process='mysqld' and time>'2015-08-31 12:40:00'`
`> SELECT * FROM goofy`

I think a warning like "measurement goofy does not exist" should be useful.

**Comment by beckettsean** [comment]
@dstreppa it's a reasonable request but not possible due to the internal architecture of the system. There is no central record of all measurements that exist.
