### ISSUE TITLE
Insert too long integer: 'invalid integer'

### ISSUE THREAD

**Issue by Nurza** [influxdb/influxdb#3905]
Hello, I am using InfluxDB 0.9.2 and I need to insert big integers in my DB, but I have this problem:

When I insert points with tiny int, it works:
```bash
curl -i -XPOST 'http://localhost:8086/write?db=dgs' \
--data-binary '--data-binary 'mystats,id=15 netbandwithtx=1000 1441028274'
```

But when I insert a big int (like int64), it fails:
```bash
curl -i -XPOST 'http://localhost:8086/write?db=dgs' \
--data-binary '--data-binary 'mystats,id=15 netbandwithtx=10000000000000000000 1441028274'

> unable to parse 'mystats,id=15 netbandwithtx=10000000000000000000 1441028274': invalid integer
```

But when I insert the same number in scientific notation it works:
```bash
curl -i -XPOST 'http://localhost:8086/write?db=dgs' \
--data-binary '--data-binary 'mystats,id=15 netbandwithtx=1e19 1441028274'
```

Is it a bug or it's normal to be not allowed to insert a big number like this?

**Comment by Nurza** [comment]
My bad, 1e19 is a float

**Comment by beckettsean** [comment]
@Nurza 1e+19 as an integer exceeds the maximum `int64` value of 9023372036854775807, which is roughly 9e+18. See https://influxdb.com/docs/v0.9/guides/troubleshooting.html#architectural-limits for the limits of the various data types.

**Comment by Nurza** [comment]
I understand my mistake. Thank you for this useful link.
