### ISSUE TITLE
[0.9.3] full WAL at startup can lead to tsdb new engine timeouts

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#3917]
0.9.3
[store] 2015/09/01 12:46:36 Using data dir: /var/opt/influxdb/data
[metastore] 2015/09/01 12:46:36 Node at test:8088 [Follower]
[retention] 2015/09/01 12:46:37 retention policy enforcement terminating
run: open server: open tsdb store: failed to open shard 1: new engine: timeout

and restart several times will startup successfully

**Comment by beckettsean** [comment]
@huhongbo is this a new installation or did you upgrade from a prior version?

Once the service is started are there any similar issues with opening shards?

**Comment by beckettsean** [comment]
What OS and filesystem are you using?

**Comment by beckettsean** [comment]
@huhongbo how big is your WAL directory on restarts? Can you run `du -h` in the parent directory of `/data` and `/wal`?

**Comment by huhongbo** [comment]
@beckettsean this is a new installation and once the service is started ,everything is fine
centos 7.1 with xfs
9.8G	data/metrics/default
9.8G	data/metrics
9.8G	data
0	hh
0	meta/snapshots
40K	meta
70M	wal/metrics/default/1
70M	wal/metrics/default
70M	wal/metrics
70M	wal

**Comment by beckettsean** [comment]
Most likely the load times from the WAL occasionally exceed the timeouts for starting the engine. You can try lowering the absolute size of the WAL to prevent the errors

**Comment by beckettsean** [comment]
@huhongbo did lowering the WAL size help?

**Comment by huhongbo** [comment]
yes lowering the wall size works for me 
and the timeout for the engine is configurable?

**Comment by beckettsean** [comment]
@huhongbo the engine timeout is not configurable. I'm glad to hear lowering the WAL size helped with the issue.

**Comment by pauldix** [comment]
Closing this out as it should be fixed with #4066 and all the other stuff. For the issue of overall throughput and improving that, please track #4086
