### ISSUE TITLE
Write fails for multiple points when tag starts with quote

### ISSUE THREAD

**Issue by jamesholcomb** [influxdb/influxdb#3928]
2015/09/01 11:28:41 InfluxDB starting, version 0.9.3, branch unknown, commit 2094f3fec17e7f675e5cacc8e984d98b1aec662d
````
11:25 AM $ cat points_2
baz,mytag="a x=1 1441103862125
baz,mytag=a z=1 1441103862126
11:25 AM $ curl -i -XPOST 'http://localhost:8086/write?db=foo' --data-binary @points_2
HTTP/1.1 400 Bad Request
Request-Id: 1fafe215-50c6-11e5-819c-000000000000
X-Influxdb-Version: 0.9.3
Date: Tue, 01 Sep 2015 16:25:57 GMT
Content-Length: 94
Content-Type: text/plain; charset=utf-8

unable to parse 'baz,mytag="a x=1 1441103862125
baz,mytag=a z=1 1441103862126': bad timestamp
````

**Comment by otoolep** [comment]
@jamesholcomb -- what would you expect to happen? The tag value has no matching quote.

**Comment by otoolep** [comment]
Do you expect the good ones to go through, and the bad ones to be dropped?

**Comment by jwilder** [comment]
@otoolep Quotes are not special in tags.  This is a valid bug.  Fix coming.

**Comment by otoolep** [comment]
OK, thanks @jwilder -- I thought we supported quoting tag values.

**Comment by jwilder** [comment]
No.  Field values use quotes to designate strings.  Tags values are used as is.  In general, tags should not be sent with quotes.

**Comment by jamesholcomb** [comment]
@otoolep - Good ones and bad ones?  Not sure I understand what you mean.

**Comment by otoolep** [comment]
@jamesholcomb -- not to worry, I was mistaken and this is a real issue. The premise of my question was incorrect.
