### ISSUE TITLE
[0.9.3] field and tag with same name cause issues

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3936]
I have a tag & field with the same name (already made them different). I'm wondering if it even should be allowed as it breaks querying and doesn't make too much sense.

```
SELECT count(family) FROM varys WHERE action = 'eventReceived' and time > now() - 4w GROUP BY time(1d), family
```

produces

```
Server returned error: can not use field in GROUP BY clause: family
```

when family is a tag and field.

**Comment by beckettsean** [comment]
duplicate of #3783
