### ISSUE TITLE
[0.9.2] Duplicate points displayed with same timestamp and same tags for minutes

### ISSUE THREAD

**Issue by yuan0122** [influxdb/influxdb#3962]
I met this issue when I tried to overwrite an existing point. I use InfluxDBClient (http://influxdb-python.readthedocs.org/en/latest/include-readme.html) to write to InfluxDB. Following are the python command lines: 

>>> from influxdb import InfluxDBClient
>>> json_body1 = [{'fields': {'status': '1', 'execution_time': 14.545258043962536}, 'tags': {'task': 'abcd'}, 'time': '2015-09-01 14:09:26', 'measurement': 'xxxxx'}]
>>> client = InfluxDBClient('xxxxxxxxx.compute-1.amazonaws.com', 8086, username='ubuntu', database='aaaaa')
>>> client.write_points(json_body1)
True
>>> json_body2 = [{'fields': {'status': '1', 'execution_time': 15.545258043962536}, 'tags': {'task': 'abcd'}, 'time': '2015-09-01 14:09:26', 'measurement': 'xxxxx'}]
>>> client = InfluxDBClient('xxxxxxxxx.compute-1.amazonaws.com', 8086, username='ubuntu', database='aaaaa')
>>> client.write_points(json_body2)
True

You can see that json_body1 and json_body2 have totally the same timestamp and same tags, then when I checked with InfluxDB, I got the following:

> select * from xxxxx
name: xxxxx
tags: task=abcd
time			execution_time	status
----			--------------	------
2015-09-01T14:09:26Z	15.545258044	1
2015-09-01T14:09:26Z	14.545258044	1
2015-09-01T15:18:15Z	15.3297729492	1

Both two points show up at the same time instead of overwriting until a few minutes later when I checked back, and it's like following:

time			execution_time	status
----			--------------	------
2015-09-01T14:09:26Z	15.545258044	1
2015-09-01T15:18:15Z	15.3297729492	1

Now we can see that the older point is overwritten by the newer one. It seems that it takes time to update. Is this normal?

**Comment by beckettsean** [comment]
Thanks for the reproducible steps, @yuan0122. I was unable to repro on my OS X box using the CLI, perhaps it's related to the python client, although I'm not sure that makes any sense.

**Comment by beckettsean** [comment]
@yuan0122 In 0.9.2 recently written points were available for querying but there was no de-duplication happening, so both points were queryable until the write ahead log was flushed to disk, at which time the duplicate point issue was resolved. That issue was fixed with https://github.com/influxdb/influxdb/pull/3626

I'm going to close this for now, please re-open if you can reproduce it with 0.9.3.
