### ISSUE TITLE
[0.9.3-final] value operator returning inconsistent results

### ISSUE THREAD

**Issue by ecables** [influxdb/influxdb#3983]
After seeing inconsistent results in some queries, I started to dig into this a bit more, and I'm hoping someone can provide clarity on the 'value' function.

Here's an example query:
```
SELECT sum(value) from webHits WHERE time > now() - 1h AND value > 100000000 AND server =~ /web.*/ group by time(5m),server fill(null)
```

The above will return results like the following, which clearly matches the above query:
```
2015-09-03T23:15:00Z	1146409233
```

Now, if I increase the "value >" number from 100000000 to 300000000, the above result no longer returns, even though 1146409233 is clearly greater than 300000000.

Is the value function operating on the underlying points, rather than the returned value of 'sum(value)' in the above query? Is that intended? If so, is there another way to approach this particular query?

**Comment by beckettsean** [comment]
`value` is not a function. `value` is an identifier, more specifically it is a field key. Field keys can be any string but typically `value` is used as it is what most graphing tools expect.

The `WHERE value > 100000000` clause means only `SUM` points whose `value` exceeds 100000000. It has no relation whatsoever to the return value of the `SUM` function, except as the additional restriction removes points from the valid range for the `SUM` function.

There is no way to return anything from the `SUM` function other than the actual sum. You will have to apply the conditional client side if you wish to display something different depending on the result of the `SUM` aggregation.

**Comment by ecables** [comment]
The goal of my query is to only show resulting sum values that exceed a threshold that is intuitive.

If I'm understanding your explanation correctly, one needs to understand how often a point is being inserted to properly infer the correct threshold for the `value` identifier, based on the data set being analyzed -- is that correct?

So if I insert a point into influx every 1 second the `value` threshold will need to be 1/60th of a similar point inserted every 60 seconds?

Can you offer up an alternative, more intuitive, way to achieve the desired goal? The only alternative I can think of is to build a CQ without the `value` identifier, and then run another query against the CQ with the `value` identifier to slice the returned query -- would this work? Can there be another feature that operates on the returned sum(value) for limiting the returned data points that only exceed a specified threshold? Say `threshold`?

**Comment by beckettsean** [comment]
@ecables `value
