### ISSUE TITLE
TSDBServer: malformed tag data : who's that ?

### ISSUE THREAD

**Issue by ymettier** [influxdb/influxdb#3988]
Hello,

I have a lot of lines like this in my log :
```
[opentsdb] 2015/09/04 08:45:22 TSDBServer: malformed tag data nico
```

How can I find who is sending malformed tag data ?

In my specific situation, I could help with this hack : 
```
$ git diff
diff --git a/services/opentsdb/service.go b/services/opentsdb/service.go
index 3179adb..c7ebce9 100644
--- a/services/opentsdb/service.go
+++ b/services/opentsdb/service.go
@@ -241,6 +241,7 @@ func (s *Service) handleTelnetConn(conn net.Conn) {
                        parts := strings.SplitN(tagStrs[t], "=", 2)
                        if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
                                s.Logger.Println("TSDBServer: malformed tag data", tagStrs[t])
+                               s.Logger.Println("TSDBServer: line was : ", line)
                                continue
                        }
                        k := parts[0]
```

When I read the line, and because it was meaningful, I could find the sender. But in most case, it is not enough.

My little patch can be improved : 
* add the IP address of the sender
* have log verbosity levels and print the line only in "warn" or "info" mode, not in "error" mode.

What do you think ?

Regards,
Yves

**Comment by otoolep** [comment]
@ymettier -- I'm fine with that, do you want to generate a PR?

**Comment by otoolep** [comment]
I have added similar code to the openTSDB input. This is no longer an issue.
