### ISSUE TITLE
[0.9.3] Service fails to start on Ubuntu 15.04

### ISSUE THREAD

**Issue by francisdb** [influxdb/influxdb#3989]
Just did a clean install on a new VM with Ubuntu 15.04
Starting the service fails:

```
sudo service influxdb start
Failed to start influxdb.service: Unit influxdb.service failed to load: No such file or directory.
```

Same issue with telegraf 0.1.7

This is probably related to systemd having replaced Upstart as the standard boot and service manager on Ubuntu 15.04

**Comment by beckettsean** [comment]
confirmed I get the same error for both packages on Ubuntu 15.04:

```
root@sean-15:~# sudo service influxdb start
Failed to start influxdb.service: Unit influxdb.service failed to load: No such file or directory.
root@sean-15:~# sudo service telegraf start
Failed to start telegraf.service: Unit telegraf.service failed to load: No such file or directory.
```

@francisdb I was able to start both services just fine with `/etc/init.d/influxdb start` and `/etc/init.d/telegraf start`. I hope that workaround is sufficient for now.

**Comment by francisdb** [comment]
@beckettsean workaround indeed works but of course annoying in case the server goes down...

**Comment by sparrc** [comment]
@francisdb I have a PR up to fix this, but you'll also have to note that Ubuntu 15.04+ uses systemd instead of sysv for daemons, so `service influxdb start` becomes `systemctl start influxdb`

**Comment by francisdb** [comment]
thanks for looking into this and the tip on the use of `systemctl`
