### ISSUE TITLE
[feature request] Extend SHOW MEASUREMENTS to accept a database parameter

### ISSUE THREAD

**Issue by svage** [influxdb/influxdb#3992]
Currently, `show measurements` lists all measurements in a selected database. It would be nice if we had the possibility to specify the database inside the request, just like in `show retention policies on <database>`.

Proposal: `show measurements on <database>.<retention policy>`

Edit: InfluxDB 0.9.3

**Comment by ivanscattergood** [comment]
It would be really handy to see the Retention policies on which a measurement is stored

**Comment by brunohass** [comment]
```
$ influx
Connected to http://localhost:8086 version 0.9.4.1
InfluxDB shell 0.9.4.1
> show retention policies on singular
name            duration        replicaN        default
default         0               1               false
singular        8760h0m0s       1               true
singular_180d   4320h0m0s       1               false
```

**Comment by beckettsean** [comment]
@ivanscattergood see #3318 for the feature request you describe

**Comment by jackzampolin** [comment]
Closing in favor of https://github.com/influxdb/influxdb/issues/3318
