### ISSUE TITLE
Use Case Evaluation, Corporate input please

### ISSUE THREAD

**Issue by dovy** [influxdb/influxdb#4025]
I represent a company that has a device that collects metrics every 2 seconds and uploads to a server every 20 mins. We have 2000 devices which have collected about 290GB of data in the past year. We're ramping up our production release and, over the next year, we're planning to have around 100,000 devices in the wild collecting up to 84 TB of data a year.

Each payload has 16 metrics per reading. What we need is the ability to get a good visualization on this data, and ensure it can scale to our needs, as well as filter it by time. Can you give me honest thoughts about this use case for InfluxDB? If you think you can match our needs, can I interact with someone on the corporate level to see if we can work together to make this happen?

This is our company: http://owletcare.com

Essentially we want to save the lives of infants across the world. If InfluxDB is scalable and ready for a project of this size, you may help us make that happen, and we'll put our trust in you.  ;)

**Comment by beckettsean** [comment]
@dovy I responded to your question on the mailing list and I believe you also submitted a ticket to support@influxdb.com. Both of those are appropriate places for this conversation, GitHub Issues is not (it's a general question, not a bug or feature request.)
