### ISSUE TITLE
Add README.md for udp service

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#4041]
See the graphite README.md for reference.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4379

**Comment by otoolep** [comment]
@beckettsean -- once this closes, the documents can point to the README added as part of #4379

**Comment by otoolep** [comment]
New README available for UDP.

**Comment by beckettsean** [comment]
https://github.com/influxdb/influxdb.com/issues/396 created for linking to the README, thanks, @otoolep!
