### ISSUE TITLE
RPM : /etc/opt/influxdb/influxdb.conf or /etc/opt/influxdb/influxd ? (0.9.4-nightly-8f5f84e)

### ISSUE THREAD

**Issue by ymettier** [influxdb/influxdb#4054]
Hello,

I just installed 0.9.4-nightly-8f5f84e rpm file and noticed something strange with configuration file...
```
$ rpm -ql influxdb-0.9.4_nightly_8f5f84e-1.x86_64
/etc/logrotate.d/influxdb
/etc/opt/influxdb/influxd <--------------------------------
/opt/influxdb/versions/0.9.4-nightly-8f5f84e/influx
/opt/influxdb/versions/0.9.4-nightly-8f5f84e/influxd
/opt/influxdb/versions/0.9.4-nightly-8f5f84e/scripts/init.sh
```

Shouldn't the configuration file be named /etc/opt/influxdb/influxdb.conf ?

```
$ grep '/etc/opt/influxdb/influxd' /opt/influxdb/versions/0.9.4-nightly-8f5f84e/scripts/init.sh
CONFIG=/etc/opt/influxdb/influxdb.conf
```

Yes it should. Of the init.sh script is bugged.
Have I missed something ?

Regards,
Yves

**Comment by otoolep** [comment]
Thanks @ymettier -- this was indeed a bug in our packaging script, that occurred only today. I have corrected it and regenerated the nightly builds. Please try again.

**Comment by ymettier** [comment]
```
$ sudo yum localinstall influxdb-nightly-0.9.4_nightly_a7ba677.x86_64.rpm
Loaded plugins: product-id, rhnplugin, security, subscription-manager
This system is receiving updates from RHN Classic or RHN Satellite.
Setting up Local Package Process
Examining influxdb-nightly-0.9.4_nightly_a7ba677.x86_64.rpm: influxdb-0.9.4_nightly_a7ba677-1.x86_64
influxdb-nightly-0.9.4_nightly_a7ba677.x86_64.rpm: does not update installed package.
Nothing to do
```

Try again...
```
$ sudo rpm -ivh influxdb-nightly-0.9.4_nightly_a7ba677.x86_64.rpm
Preparing...                ########################################### [100%]
        package influxdb-0.9.4_nightly_8f5f84e-1.x86_64 (which is newer than influxdb-0.9.4_nightly_a7ba677-1.x86_64) is already installed
```

Try again...
```
$ sudo rpm -Uvh --force influxdb-nightly-0.9.4_nightly_a7ba677.x86_64.rpm
Preparing...                ########################################### [100%]
   1:influxdb               warning: /etc/opt/influxdb/influxdb.conf created as /etc/opt/influxdb/influxdb.conf.rpmnew
########################################### [100%]
```

OK, it looks fine for me.

BTW, maybe you could do something in the version number of the rpm to prevent this upgrade issue ? Maybe you could add a date+release version before the commit number ?
That could would have been today :
* 0.9.4_nightly_20150909_1_8f5f84e
* 0.9.4_nightly_20150909_2_a7ba677

I'm not opening a new issue because I don't know if this happens only today for the 2 or 3 people who downloaded the 8f5f84e nightly rpm or if it will happen every night to everybody.

Regards,
Yves
