### ISSUE TITLE
[master] [question] keep less and less data after time

### ISSUE THREAD

**Issue by jeremyVignelles** [influxdb/influxdb#4056]
Hi,
I'm writing ~100MB of data in the influxdb per week, and I was wondering if it is possible to keep, let's say 1 data point per day for a year, and clear the other points after a week.

My first thought was to go on a solution with two retention policies, `week` and `year`, and to switch between these policies when writing in the HTTP protocol. However, When I later do the query
```
SELECT * FROM test
```
It only shows the data from my default retention policy (week), and not the other data points, which I have to select using
```
SELECT * FROM year.test
```

I would have expected a query like this to work:
```
SELECT * FROM *.test
```
but...
```
error parsing query: found *, expected identifier at line 1, char 15
```

What is the recommended way of doing so that I keep less and less data in the database?

- Should I duplicate the data in the two retention periods, and SELECT where I want?
- Should I do two queries at a time, on for each retention period, and merge the results?

Thanks in advance.

**Comment by beckettsean** [comment]
@jeremyVignelles as this is more of a question than a bug or feature request, it would be better posted to the mailing list, influxdb@googlegroups.com.

We will be publishing a guide to downsampling later this week which should have the answers you need.

Closed by https://github.com/influxdb/influxdb.com/pull/286 (when it happens)
