### ISSUE TITLE
Wrong date while saving to influx

### ISSUE THREAD

**Issue by codehate** [influxdb/influxdb#4067]
I'm trying to dump data from MySQL to influx. Say i get timestamp and value from mysql in the following format:

```sql
select UNIX_TIMESTAMP(created),value from tmp limit 1;
```
To would return: `1336560057, 2012-05-09 16:10:57`

But when i store the time stamp `1336560057` in influx it's storing time stamp `1970-01-01T00:00:01.336560057Z`.

**Comment by DanielMorsing** [comment]
Influxdb uses nanoseconds from the epoch if nothing else is specified, so it's behaving as intended. If you want to write with second precision you can add the query parameter `precision=s` to the writing HTTP request.

**Comment by codehate** [comment]
Thank you for the response. But while i'm doing this `abc,host=server01,region=europe value=0.64 precision=s 1336560057` a error is thrown `unable to parse 'abc,host=server01,region=europe value=0.64 precision=s 1336560057': bad timestamp`

**Comment by codehate** [comment]
Gotcha. `&precision=s` in URL worked like charm.

**Comment by codehate** [comment]
When I'm doing this: `abc,host=server01,region=us-west value=0.64 1403538329` it's saving as `2014-06-23T10:45:29Z` but it's `2014-06-23T15:45:29Z` in database.

**Comment by DanielMorsing** [comment]
Which timezone is the MySQL server in? InfluxDB returns all times as UTC, so that might be the cause of the offset.

**Comment by codehate** [comment]
Thanks a lot @DanielMorsing that is it.
