### ISSUE TITLE
line protocol parser panics

### ISSUE THREAD

**Issue by dgnorton** [influxdb/influxdb#4076]
While trying to reproduce issue #4069, I wrote a brute force test for the line protocol parser, which found that the following inputs cause `tsdb.ParsePointsString` to panic:

```
'= "\, '= "\ v=1.0
= "'\, = "'\ v=1.0
= '"\, = '"\ v=1.0
=' "\, =' "\ v=1.0
.= "\, .= "\ v=1.0
= ".\, = ".\ v=1.0
= ."\, = ."\ v=1.0
=. "\, =. "\ v=1.0
1= "\, 1= "\ v=1.0
= "1\, = "1\ v=1.0
= 1"\, = 1"\ v=1.0
=1 "\, =1 "\ v=1.0
;= "\, ;= "\ v=1.0
= ";\, = ";\ v=1.0
= ;"\, = ;"\ v=1.0
=; "\, =; "\ v=1.0
= "a\, = "a\ v=1.0
= a"\, = a"\ v=1.0
=a "\, =a "\ v=1.0
a= "\, a= "\ v=1.0
```
However, none reproduce the issue mentioned above.

/cc @jwilder

**Comment by dgnorton** [comment]
Most are probably duplicates.  They all look similar to one of the following:
```
unable to parse number value '1 "\ v=1.0': strconv.ParseFloat: parsing "1 \"\\ v=1.0": invalid syntax
```
```
unable to parse bool value ' "\ v=1.0': strconv.ParseBool: parsing " \"\\ v=1.0": invalid syntax
```

**Comment by beckettsean** [comment]
@dgnorton those points look a lot like like "hello world" in brainfuck.

-- 
Precision thumbed for accuracy

**Comment by jsternberg** [comment]
I can't seem to replicate this using `tsdb.ParsePointsString` (now `models.ParsePointsString`), but a panic definitely happens when you try to write the first value. Here is the stacktrace I got running from master.

```
goroutine 29 [running]:
github.com/influxdb/influxdb/models.newFieldsFromBinary(0xc820596003, 0xf, 0x1fd, 0xc8205e8300)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/models/points.go:1414 +0xa0b
github.com/influxdb/influxdb/models.(*point).unmarshalBinary(0xc82034e120, 0xc8205ec520)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/models/points.go:1287 +0x40
github.com/influxdb/influxdb/models.(*point).Fields(0xc82034e120, 0xc8202fa5d0)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/models/points.go:1200 +0x3a
github.com/influxdb/influxdb/tsdb.(*Shard).validateSeriesAndFields(0xc82022a840, 0xc8205fa260, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/tsdb/shard.go:413 +0x66d
github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints(0xc82022a840, 0xc8205fa260, 0x1, 0x1, 0x0, 0x0)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/tsdb/shard.go:202 +0xa2
github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard(0xc820150000, 0x2, 0xc8205fa260, 0x1, 0x1, 0x0, 0x0)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/tsdb/store.go:417 +0x14e
github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1(0xc820144090, 0xc8205f422f, 0x4, 0xc8201e2750, 0x7, 0xc8204863c0, 0x1, 0x2, 0x1, 0xc8205fa260, ...)
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:315 +0x10b
created by github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard
        /Users/jsternberg/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:347 +0x1c5
```

**Comment by jsternberg** [comment]
After talking with @jwilder, it seems that these inputs shouldn't be getting past the parser to begin with. Quotes in the field key are not supposed to have significance. The input goes through two separate parsers, one for checking validity and one for parsing the values. It seems like the first one thinks this is a valid input, but the second then parses it correctly and panics since it assumed that the input was supposed to already be validated.

I have submitted a PR that will bring the first parser to match the same behavior as the second. It might be worth in the future consolidating these parsers so they don't have to agree since it seems like both of them are doing about the same amount of work anyway.

**Comment by undera** [comment]
Just bumped into this issue in my application . For me it happens with tag values having unmatched quote in it. I'm writing points like this:
t143,label=hey\ "ya a=1i,value=0i t143,label=another a=2i,value=1i 1

And getting:
HTTP Code 400 {"error":"unable to parse 't143,label=hey\\ \"ya a=1i,value=0i\nt143,label=another a=2i,value=1i 1': invalid number"}

My experiments show that to reproduce it you need to have space before quote in tag value. Hope this issue supposes to fix it.

**Comment by jsternberg** [comment]
@undera can you make a separate issue for that? My initial thoughts looking at your description leads me to believe this may be a parser issue, but unrelated to this issue (although some of the symptoms may be in common).

I would like to keep them separate though for now so this issue doesn't get confused.

Thanks!

**Comment by undera** [comment]
np! here you go: #5204
