### ISSUE TITLE
Calculating rate of traffic

### ISSUE THREAD

**Issue by matejzero** [influxdb/influxdb#4081]
I'm pushing counter values (not rate) of network traffic from server to influxdb. I want to show that metrics on the graphs in Grafana. My goal is to always have bytes/s, no matter the timespan I select.

I'm using influxdb version 0.9.3.

My data looks like this:
2015-09-11T11:59:40Z	913298868833
2015-09-11T11:59:50Z	913301354816
2015-09-11T12:00:00Z	913303891905
2015-09-11T12:00:10Z	913307028649
2015-09-11T12:00:20Z	913309906735
2015-09-11T12:00:30Z	913312538597
2015-09-11T12:00:40Z	913315297767
2015-09-11T12:00:50Z	913318159883

Calculating derivative is simple:
SELECT derivative(value) FROM "interface" WHERE "fqdn" = 'graphite' AND time > now() - 1h

But this returns a lot of results if I want to graph last 24h. If I understand correctly, we use GROUP BY to create buckets (example, if we use GROUP BY time(60s) it should calculate average rate per 60s bucket (average bytes/s rate in 60s) and return 60 metrics(given that our timespan is 1h and group by time is set to 60s).

In my case, I get last metric minus first metric for all entries:
SELECT derivative(value) FROM "interface" WHERE "fqdn" = 'graphite' AND time > now() - 1h GROUP BY time(60s)
2015-09-11T12:03:00Z	16909020
2015-09-11T12:03:10Z	16788006
2015-09-11T12:03:20Z	17410074
2015-09-11T12:03:30Z	16606902
2015-09-11T12:03:40Z	16283814
2015-09-11T12:03:50Z	16490946

If I divide this numbers by 60, I get bytes/s. Should it work like this?

As far as I understand, I should get 60s buckets with average transfer rate in bytes/s like so:
2015-09-11T12:03:00Z	281817
2015-09-11T12:04:00Z	279800
2015-09-11T12:05:00Z	290167
2015-09-11T12:06:00Z	276781
2015-09-11T12:07:00Z	271396

How to achieve that? What am I doing wrong?

If I use mean() function instead of derivative(), then I get the right buckets, but calculations are obviously wrong.
2015-09-11T12:15:00Z	913550996036.1666
2015-09-11T12:16:00Z	913566233512.1666
2015-09-11T12:17:00Z	913581996372
2015-09-11T12:18:00Z	913597341944.8333

**Comment by DanielMorsing** [comment]
`derivative` takes an optional second argument that changes which unit the derivative returns. You can use `derivative(value, 1s)` if you want to see the rate per second within the `group by` time

**Comment by matejzero** [comment]
This looks like it returns the right results (bytes per second), but I think group by time is not working correctly.

Query
`SELECT derivative(value,1s) FROM "interface" WHERE "fqdn" = 'graphite' AND time > now() - 1h group by time(60s)`

returns
```
2015-09-11T15:46:10Z	261784.5
2015-09-11T15:46:20Z	247362.8
2015-09-11T15:46:30Z	260923.5
2015-09-11T15:46:40Z	265645.9
2015-09-11T15:46:50Z	258242.9
2015-09-11T15:47:00Z	249119.8
```

Shouldn't it return something like (notice the time buckets):
```
2015-09-11T15:46:00Z	261784.5
2015-09-11T15:47:00Z	247362.8
2015-09-11T15:48:00Z	260923.5
2015-09-11T15:49:00Z	265645.9
2015-09-11T15:50:00Z	258242.9
2015-09-11T15:51:00Z	249119.8
```

**Comment by abh** [comment]
+1 – I had the same confusion. I also wanted to log the raw data to not lose detail right away and have been trying to make CQs to make it easier to graph and down sample the data and have been running into the same issue.

**Comment by matejzero** [comment]
I'm glad I'm not the only one.

**Comment by DanielMorsing** [comment]
hmm, looks like I was confused about how exactly the derivative function works.

Good news is that I think I found a way of executing the query you want. `SELECT derivative(first(value), 1s) from ...`

**Comment by matejzero** [comment]
I don't think this works as expected as well.
Executing `SELECT derivative(first(value), 1s) FROM...` returns only 1 hit with value `0`:
```
interface
time	derivative
2015-09-14T14:05:00Z	0
```

**Comment by jwilder** [comment]
@matejzero Try adding a `fill(0)`

**Comment by matejzero** [comment]
fill(0) looks like it solves the problem. I will try to show metrics on graph and compare to Graphite metrics.

By the way, can you explain to me, what this query and fill(0) actually does, so I can understand better.

**Comment by jwilder** [comment]
If you run something like:
```
SELECT derivative(first(value), 1s) FROM foo WHERE time > now() - 1h GROUP BY time(10s)
```

It first runs:

```
SELECT first(value) FROM foo WHERE time > now() - 1hr GROUP BY time(10s)
```

This returns the first value for each `10s` interval over the last hour.  From these results, it calculates the derivative between each `10s` bucket and converts it to a `1s` rate.  

The `fill(0)` is needed because the first group by query would not return all the data required to calculate a derivative for all the buckets.  The derivative currently exits early if it's missing some data which is why you were only getting one point back w/ `0`.  `derivative` should probably be changed to assume 0 for missing data values though.

**Comment by matejzero** [comment]
Maybe I was too fast with my response.

Using `fill(0)` gives this response:
```
time	derivative
2015-09-14T16:12:00Z	16373950124.4
2015-09-14T16:13:00Z	299882.13333333336
2015-09-14T16:14:00Z	298712.36666666664
2015-09-14T16:15:00Z	286938.35
2015-09-14T16:16:00Z	299208.4
```
If I look at the raw data, I can see why (SELECT first(value) FROM ...):
```
time	first
2015-09-14T16:13:00Z	0
2015-09-14T16:14:00Z	982472923134
2015-09-14T16:15:00Z	982490139435
2015-09-14T16:16:00Z	982508091939
2015-09-14T16:17:00Z	982530697642
```

On the other hand, if I use `fill(none)`, then it leaves out the first response where we don't have enough data, but leaves the rest. Is this the right way to go?

**Comment by matejzero** [comment]
I think this gives me the results I want. I changed first() function with mean() and the result is almost the same as graphite graphs.
