### ISSUE TITLE
[0.9.2] Recovering after disk full

### ISSUE THREAD

**Issue by pawan1987** [influxdb/influxdb#4082]
Hi,

I am using influxdb version 0.9.2.  My influxdb partition is running at 99% disk usage. I deleted few measurements but there is no reflection on disk usage. Now I have setup the retention policy too. But not sure how to enforce it. 

Can you please suggest a way to recover space without dropping database ?

Any help will be appreciated.

**Comment by pawan1987** [comment]
I can't see any of my metrics after dropping few measurements. influxdb stopped with panic. Had to start it. 

---
panic: runtime error: slice bounds out of range

goroutine 8293249 [running]:
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeByID(0xc20df04a50, 0xc20ae4ba09, 0x7f8b6b3f61d4, 0x30, 0x7fffffed, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:1032 +0x82d
github.com/influxdb/influxdb/tsdb.(*FieldCodec).DecodeByName(0xc20df04a50, 0xc209675049, 0x5, 0x7f8b6b3f61c2, 0x42, 0x7fffffff, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:1051 +0x142
github.com/influxdb/influxdb/tsdb.(*tagSetCursor).Next(0xc209b9d1f0, 0x1402ef429776b800, 0x1402ef508fbe1000, 0xc2095dd778, 0x1, 0x1, 0xeceb08, 0x0, 0x0, 0x1402ef4d11ac3a00, ...)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:581 +0x4fd
github.com/influxdb/influxdb/tsdb.func·004(0xc2095dd7f8, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:438 +0x183
github.com/influxdb/influxdb/tsdb.(*aggTagSetCursor).Next(0xc20a639768, 0x8fc9e0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:496 +0x3a
github.com/influxdb/influxdb/influxql.MapMean(0x7fa2a8c8bf08, 0xc20a639768, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/influxql/functions.go:486 +0x14e
github.com/influxdb/influxdb/tsdb.(*AggMapper).NextChunk(0xc20813c1c0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:448 +0x8a6
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc208555fa0, 0xc20ea888d0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:54 +0x5c
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc20cee64e0, 0xc20a7d36e0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:413 +0x20e0
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:337 +0x5a
---

**Comment by beckettsean** [comment]
If your system is 99% disk full, InfluxDB probably can't recover any space until you free up space elsewhere.

> Can you please suggest a way to recover space without dropping database ?

Retention policies are the best way to keep the data size from growing forever, but the system has to be healthy for them to work. Can you delete some logs or tmp files to free up disk space?
