### ISSUE TITLE
create user with admin role

### ISSUE THREAD

**Issue by shilpapadgaonkar** [influxdb/influxdb#4083]
Hello,
How can i create a user with admin role? 
When i tried 
CREATE USER test WITH PASSWORD '*******'
> show users
user    admin
test    false

It sets admin as false. What is the command to set the admin value to true?

Thanks,
Shilpa

**Comment by gunnaraasen** [comment]
The syntax for granting privileges is explained on the [administration page](https://influxdb.com/docs/v0.9/administration/administration.html#privilege-control) in the docs.

To add admin privileges to a newly created user, you need to add `WITH ALL PRIVILEGES` at the end. E.g.

```
CREATE USER test WITH PASSWORD 'password' WITH ALL PRIVILEGES
```

**Comment by jholovacs** [comment]
The above referenced page no longer exists.  Where is the administration page now?

**Comment by gunnaraasen** [comment]
The info is now on [this page](https://docs.influxdata.com/influxdb/v1.7/administration/authentication_and_authorization/#admin-user-management).
