### ISSUE TITLE
[0.9.3] (regression) Continuous Queries results not calculated for every interval

### ISSUE THREAD

**Issue by ericjmiller** [influxdb/influxdb#4087]
I have created a Continuous Query similar to the following:

    CREATE CONTINUOUS QUERY min_best_score ON hadoop_jobs BEGIN
    SELECT MIN(best_score) INTO min_best_score FROM scores GROUP BY time(5s) 
    END

Data from "scores" comes every 0.05 seconds roughly for about 15 minutes.  When the 15 minutes starts, the Continuous Query may show 3-5 results for the entire 15 minutes - definitely not every 5 seconds.  

Am I doing something wrong here?  Is this a known issue?

**Comment by beckettsean** [comment]
I think this is a duplicate of #4068. My CQ that executes every 5 minutes appears to run fine, but I think CQs with durations under 2 minutes might have issues right now.

**Comment by ericjmiller** [comment]
Thanks, Sean.  Are there any fix in the works?  This seems like a very important feature that isn't working.

**Comment by beckettsean** [comment]
@ericjmiller we are working on it but I haven't seen a PR yet, so I can't say how far along the dev team is. Agreed it is an important feature

**Comment by beckettsean** [comment]
dupe of #4068
