### ISSUE TITLE
the document is so confusing on regex query

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#4092]
https://influxdb.com/docs/v0.9/query_language/spec.html

![image](https://cloud.githubusercontent.com/assets/559179/9837401/b840957a-5a6f-11e5-92f3-41c51774ea6c.png)

I tried but failed for many times before I searched the issues and found the correct way:

`=~ /recommend/ `

or did I find the wrong document?

**Comment by beckettsean** [comment]
Please open issues about the documentation on the [docs repo](https://github.com/influxdb/influxdb.com/issues/new)

I've opened an issue for you: https://github.com/influxdb/influxdb.com/issues/313

The document you are looking at is a formal definitions document for the InfluxQL parser. It does not give syntax.
