### ISSUE TITLE
CPU spin on 'delete from ...'

### ISSUE THREAD

**Issue by abh** [influxdb/influxdb#4094]
I realize (since trying it) that it's not supported yet, but spinning 2 CPUs probably isn't the desired behavior:

When I run

`delete from server_queries where time='2015-09-14T04:59:06.059250874Z' and hostname='soft'`

and variations of this the call doesn't return (using the CLI) and the influxd process uses ~2 CPUs at full throttle until I restart the daemon (or at least for several minutes).

 http://localhost:8086/query?db=&q=delete+from+server_queries+where+time%3D%272015-09-14T04%3A59%3A06.059250874Z%27+and+hostname%3D%27sfo2%27

**Comment by rkuchan** [comment]
@abh,

I'm trying to reproduce the issue. What version are you using? 

When I try to run a similar query I receive the following error in the CLI: 

```
> delete from forests where time='1970-01-01T00:01:00Z'
ERR: invalid query
```

Currently the best practice for "deleting" a data point is to overwrite it instead. See https://github.com/influxdb/influxdb/issues/3882. 

Thanks!

**Comment by otoolep** [comment]
We need a repro case for this one, the given query is not valid.
