### ISSUE TITLE
slow insertion latency for future timestamps

### ISSUE THREAD

**Issue by CharlesWong** [influxdb/influxdb#4095]
Hi guys,

Have you noticed that inserting future timestamps has a long latency to show the results from querying?

for example:

        requestFmt := "test value=%d,peopleid=%d %d"

		for i := 0; i < 3600*24*365; i++ {
			request := fmt.Sprintf(requestFmt, i, i*2, time.Now().Add(time.Second*time.Duration(-1*i)).UnixNano())
				req, err := http.NewRequest("POST", url, bytes.NewBuffer([]byte(request)))
				req.Header.Set("Content-Type", "application/octet-stream")
				client := &http.Client{}
				resp, err := client.Do(req)

				if err != nil {
					panic(err)
				}
				defer resp.Body.Close()
				body, _ := ioutil.ReadAll(resp.Body)
		}

in the above example, if  I remove the "-1" in the timestamp generating line, the result of query "select count(value) from test" will increase 3~5 records per second no matter how fast I inserted the records. However, if I keep the "-1" there, the "select count(value) from test" will increase ~500 records per second. Is it by design?

**Comment by SiriusHu** [comment]
same issue, up

**Comment by beckettsean** [comment]
Points in the future are not returned by default. You must explicitly set your upper time boundary or else the system uses `now()`.

https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now
