### ISSUE TITLE
I want to delete some datas within a time, can I use the command such as : delete from cpu where time < '.....'

### ISSUE THREAD

**Issue by guaiguaihw** [influxdb/influxdb#4097]
I want to delete some datas within a time.
Can I use the command such as : 
delete from cpu where time < '2015-08-31 00:00:00' ??
I try this command but it doesn't work.....what should we do to drop the datas within a time ???

**Comment by beckettsean** [comment]
Duplicate of https://github.com/influxdb/influxdb/issues/1647
