### ISSUE TITLE
Uninstall Influxdb

### ISSUE THREAD

**Issue by willemdh** [influxdb/influxdb#4101]
Yesterday I installed InfluxDB 0.9.3 on a CentOS 7.1, but as I decided to use 0.9.4, I decided to uninstall 0.9.3.
I used this command to install:
sudo yum localinstall influxdb-0.9.3-1.x86_64.rpm
And this command to uninstall:
sudo yum remove influxdb

The uninstall was 'successfully' but after uninstalling the web interface was still available and when I try to locate influxdb, I still find files related to the InfluxDB install:
    locate infl
    /etc/opt/influxdb
    /etc/opt/influxdb/influxdb.conf
    /etc/rc.d/init.d/influxdb
    /etc/rc.d/rc0.d/K50influxdb
    /etc/rc.d/rc1.d/K50influxdb
    /etc/rc.d/rc2.d/S50influxdb
    /etc/rc.d/rc3.d/S50influxdb
    /etc/rc.d/rc4.d/S50influxdb
    /etc/rc.d/rc5.d/S50influxdb
    /etc/rc.d/rc6.d/K50influxdb
    /opt/influxdb
    /opt/influxdb/influx
    /opt/influxdb/influxd
    /opt/influxdb/init.sh
    /opt/influxdb/versions
    /opt/influxdb/versions/0.9.3
    /opt/influxdb/versions/0.9.3/influx
    /opt/influxdb/versions/0.9.3/influxd
    /opt/influxdb/versions/0.9.3/scripts
    /opt/influxdb/versions/0.9.3/scripts/init.sh
    /var/log/influxdb
    /var/log/influxdb/influxd.log
    /var/opt/influxdb
    /var/opt/influxdb/data
    /var/opt/influxdb/hh
    /var/opt/influxdb/meta
    /var/opt/influxdb/meta/id
    /var/opt/influxdb/meta/peers.json
    /var/opt/influxdb/meta/raft.db
    /var/opt/influxdb/meta/snapshots

Is this normal behaviour? Are there somewhere upgrade instructions for upgrading from 0.9.x to 0.9.y?

Thanks for any info on this topic.

**Comment by willemdh** [comment]
Hmmm I re-installed the server and InfluxDB 0.9.4 and it seems the web interface is still showing 0.9.3. A locate on the server now does show different files (0.9.4)

locate influxdb
/etc/opt/influxdb
/etc/opt/influxdb/influxdb.conf
/etc/systemd/system/multi-user.target.wants/influxdb.service
/opt/influxdb
/opt/influxdb/influx
/opt/influxdb/influxd
/opt/influxdb/init.sh
/opt/influxdb/versions
/opt/influxdb/versions/0.9.4-rc1
/opt/influxdb/versions/0.9.4-rc1/influx
/opt/influxdb/versions/0.9.4-rc1/influxd
/opt/influxdb/versions/0.9.4-rc1/scripts
/opt/influxdb/versions/0.9.4-rc1/scripts/influxdb.service
/opt/influxdb/versions/0.9.4-rc1/scripts/init.sh
/usr/lib/systemd/system/influxdb.service
/var/log/influxdb
/var/opt/influxdb
/var/opt/influxdb/data
/var/opt/influxdb/hh
/var/opt/influxdb/meta
/var/opt/influxdb/wal
/var/opt/influxdb/data/_internal
/var/opt/influxdb/data/_internal/monitor
/var/opt/influxdb/data/_internal/monitor/1
/var/opt/influxdb/meta/id
/var/opt/influxdb/meta/peers.json
/var/opt/influxdb/meta/raft.db
/var/opt/influxdb/meta/snapshots
/var/opt/influxdb/wal/_internal
/var/opt/influxdb/wal/_internal/monitor
/var/opt/influxdb/wal/_internal/monitor/1
/var/opt/influxdb/wal/_internal/monitor/1/000000.meta

**Comment by rkuchan** [comment]
Hi @willemdh,

Thanks for finding this. It looks like the version number is hardcoded in the admin UI. Working on updating that now.  

All the files were updated correctly - if you open the CLI or ping your server you should see version 0.9.4.

**Comment by willemdh** [comment]
No problem Rkuchan, Thanks for the fast answer. So what about upgrading? I did not found any documentation on how to do this 'officially'. I used this to install 0.9.4 on CentOS 7.
wget https://s3.amazonaws.com/influxdb/influxdb-0.9.4_rc1-1.x86_64.rpm
sudo rpm -ivh influxdb-0.9.4_rc1-1.x86_64.rpm

How would I best update to further versions?

**Comment by beckettsean** [comment]
@willemdh what you describe is the current upgrade path. All 0.9 InfluxDB builds are drop-in replacements for previous builds. Some functionality might be unavailable until the config file is updated but the binary should launch without issue.

>  after uninstalling the web interface was still available 

You also need to stop the service, not just uninstall the files. I do not know if `yum` handles this for you, but it would appear not.

> avoid the issues I had when I tried upgrading from 0.9.3 to 0.9.4?

Other than the version string mismatch I don't see what issues you describe.

**Comment by willemdh** [comment]
Ok, thanks all. Closing this.

**Comment by willemdh** [comment]
@rkuchan @beckettsean 
I update today from 0.9.4 to 0.9.5.1-1 and just noticed that the version in the webGUI is still 0.9.3
When I type 

    influx version
    Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
    Connected to http://localhost:8086 version 0.9.4-rc1
    InfluxDB shell 0.9.5.1

It's kind of confusing and chaotic to see three different version numbers. Is this normal? Or something went wrong during installation?

**Comment by willemdh** [comment]
Sorry must have been cached. I see the correct version now in the gui. Closing.
