### ISSUE TITLE
When using the client, receiving the following error: `undefined: strings.Compare`

### ISSUE THREAD

**Issue by JONBRWN** [influxdb/influxdb#4107]
When trying to build with the following import:

```
import (
	"flag"
	"log"
	"math"
	"os"
	"os/signal"
	"strings"
	"time"
	"fmt"
	"net/url"
	"encoding/json"

	influxdb "github.com/influxdb/influxdb/client"
)
```

I get this error:
```
GOPATH=:`pwd` go get github.com/influxdb/influxdb/client
# github.com/influxdb/influxdb/tsdb
src/github.com/influxdb/influxdb/tsdb/functions.go:1084: undefined: strings.Compare
```

**Comment by otoolep** [comment]
I see no reason why this should happen. Perhaps your tree is not correct?

https://github.com/influxdb/influxdb/blob/master/tsdb/functions.go#L1084

That file is importing `strings`, and CI reports no build problems.

https://circleci.com/gh/influxdb/influxdb/tree/master

**Comment by JONBRWN** [comment]
@otoolep do I need to be importing anything other than `github.com/influxdb/influxdb/client` for it to work? I'm running this on docker so it's pulling the latest code down

**Comment by cyppan** [comment]
I am experiencing the same issue. I run this on Docker too (Alpine Linux).

**Comment by otoolep** [comment]
We now build InfluxDB using Go 1.5, as mentioned in the 0.9.4 CHANGELOG. Are you running an earlier version of Go? Is it feasible for you to upgrade?

**Comment by cyppan** [comment]
Arf that go dependencies management..
Ok upgraded thanks!

**Comment by otoolep** [comment]
This is a Go 1.4 vs. 1.5 issue. Building InfluxDB now requires Go 1.5, as explained by https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md

**Comment by JONBRWN** [comment]
looks like that was the case, thanks @otoolep

**Comment by corylanou** [comment]
With the refactoring I'm doing the client will no longer depend on several other packages, and no longer have the 1.5 go dependency as a result.  That should get merged today hopefully. https://github.com/influxdb/influxdb/pull/4134

**Comment by JONBRWN** [comment]
@corylanou nice, I'll keep my eye out for it
