### ISSUE TITLE
show databases sometimes returns _internal, sometimes not

### ISSUE THREAD

**Issue by aviau** [influxdb/influxdb#4127]
show databases sometimes returns _internal, sometimes not.

This is as of 0.9.4. In 0.9.3, it would never return _internal.

**Comment by otoolep** [comment]
That's because `_internal` is new, and auto-created, in 0.9.4. When running 0.9.4, it should always return `_internal` assuming it has been created.

Can you show us this questionable behaviour?

**Comment by aviau** [comment]
> assuming it has been created.

Is is created after a certain time? this happens in the influxdb-python tests where I create a brand new instance and run a test.

**Comment by otoolep** [comment]
It is created when the system starts up, it shouldn't take more than a few seconds after start up.

https://github.com/influxdb/influxdb/blob/master/monitor/service.go#L304

It can be disabled via this config:

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L100

**Comment by otoolep** [comment]
Do we have an issue here? If not, please close.

**Comment by aviau** [comment]
> it shouldn't take more than a few seconds after start up

That it it then! I run my tests __immediately__ when the instance is ready.

> It can be disabled via this config

Thanks!
