### ISSUE TITLE
[feature request] Add fill() method like Graphite's KeepLastValue

### ISSUE THREAD

**Issue by lexh** [influxdb/influxdb#4137]
Graphite offers a method to deal with missing data called [KeepLastValue](http://graphite.readthedocs.org/en/latest/functions.html?highlight=keeplastvalue#graphite.render.functions.keepLastValue). It "takes one metric [...] and continues the line with the last received value when gaps (‘None’ values) appear in your data..."

Could Influx's `fill()` be extended to offer similar functionality?

**Comment by otoolep** [comment]
Did you read the manual? https://influxdb.com/docs/v0.9/query_language/data_exploration.html

Isn't `fill(previous)` what you want?
