### ISSUE TITLE
Query Logging in 0.9.4.1

### ISSUE THREAD

**Issue by jgerschk** [influxdb/influxdb#4138]
#3566 from what I have read, turn off log-enabled = false within the [http] section should disable the query logging.

What I don't understand is why I am still seeing that in our logs even though we have this disabled.

What I see is something a little new...maybe, but I have not been able to find out what can turn these off...

[query] 2015/09/16 20:55:06 SELECT last(value) .... {cut some due to private details}.

Did I miss some setting that should be disabled?

**Comment by otoolep** [comment]
No @jgerschk -- you did not miss anything. You are only disabling logging at the HTTP level, but logging in the query engine was recently added. This is what is being added.

I can make that configurable too.

**Comment by jgerschk** [comment]
@otoolep Thanks for the reply.  So we should see this in a future release -- to be able to disable this as I understand it....Logging those can create a huge amount of unneeded data at times...

**Comment by otoolep** [comment]
Yes, it will be coming very soon.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4141

**Comment by jgerschk** [comment]
Thank you kindly @otoolep .

**Comment by otoolep** [comment]
Fixed in next nightly build, and in 0.9.5.

**Comment by jgerschk** [comment]
@otoolep, Thanks again, will give the nightly a spin.
