### ISSUE TITLE
[feature request] Specify boltdb pagesize

### ISSUE THREAD

**Issue by kev009** [influxdb/influxdb#4144]
It looks like everything defaults to 4k.  It would be nice to set the pagesize in the config file to match it to different filesystems.

**Comment by rkuchan** [comment]
@benbjohnson

**Comment by beckettsean** [comment]
@kev009 BoltDB is not going to be the storage engine for future releases. We've run into scaling issues with IOPS due to BoltDB. See https://github.com/influxdb/influxdb/issues/4086
