### ISSUE TITLE
[0.9.1] data with same timestamp and tags gets overwritten 

### ISSUE THREAD

**Issue by esecules** [influxdb/influxdb#4150]
Is it a limitation of influx that only one point can exist with the same tags and timestamp? If a collision does occur, does the old one get overwritten?

I can reproduce with this script:
```
from influxdb import InfluxDBClient
import time
from uuid import uuid4
token = str(uuid4())
t = int(time.time())
cli = InfluxDBClient(host="localhost",port="8086",database="test",timeout=30)
cli.create_database("test")
events=[{
        'database': "test",
        "retentionPolicy": "event_data",
        'points': [
            {
                'measurement': 'events',
                'tags': {"location":"Mars", "sector":"12a","token":token},
                'time': t,
                'fields': {"lifeform-count":600}
            }
        ]
    },{
        'database': "test",
        "retentionPolicy": "event_data",
        'points': [
            {
                'measurement': 'events',
                'tags': {"location":"Mars", "sector":"12a","token":token},
                'time': t,
                'fields': {"lifeform-count":700}
            }
        ]
    }]
for e in events:
    cli.write(e)

print cli.query("""SELECT * FROM events WHERE "token"='{0}'""".format(token))
```
Output: It only lists one point even through I wrote two.
```
eric@mothership:~$ python influx_test.py
ResultSet({'(u'events', {u'sector': u'12a', u'token': u'4ed89066-cef1-44d2-a201-f058bdfc8e43', u'location': u'Mars'})': [{u'lifeform-count': 700, u'time': u'2015-09-17T18:17:07Z'}]})

```

**Comment by beckettsean** [comment]
> Is it a limitation of influx that only one point can exist with the same tags and timestamp? 

Yes, this is by design.

> If a collision does occur, does the old one get overwritten?

Yes, it is silently overwritten. 

This is documented but not well. I opened https://github.com/influxdb/influxdb.com/issues/324 to address that.

**Comment by halt-hammerzeit** [comment]
@beckettsean  So, are points always overwritten when repeatedly sending something like `{ data: 123 }`?
Or are they overwritten only when the data being sent has a `time` field set to some constant value which remains the same?

**Comment by beckettsean** [comment]
@halt-hammerzeit: https://docs.influxdata.com/influxdb/v0.13/troubleshooting/frequently_encountered_issues/#writing-duplicate-points

**Comment by yifeikong** [comment]
I'm new to time series database, I got confused by this and wasted one afternoon in finding out why, until I find this post. I'm currently adding an uuid tag to prevent points overwriting each other, is this a good practice?

**Comment by dshen109** [comment]
@yifeikong no, see this schema design guide for why: https://docs.influxdata.com/influxdb/v1.7/concepts/schema_and_data_layout/#don-t-have-too-many-series

**Comment by yifeikong** [comment]
@dshen109 Thanks, I have figured this out. For future readers, there are too options:

1. aggregate points per timestamp by yourself
2. uses a third party tool like telegraf/statsd

**Comment by ljgreen** [comment]
@beckettsean I am a little confused about the overwriting the duplicate data. The overwrite will first check if there is any existing duplicate data (e.g., with the same measure, tag, timestamp), and if it has been found, what will do next ? It will directly modify the existing data in TSM file on disk ? If so, the performance will be affected.  Or, it will do like the deletion operation.

As I know, the deletion operation will add a delete tag to the corresponding data, and when compaction occurs, it will make the garbage collection. 

Can you give me some explanations? 
Thanks.
