### ISSUE TITLE
homebrew version is still 0.9.3

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4152]
Can we get 0.9.4 out there soon or should we update the docs to remove 0.9.4 references for OS X?

**Comment by beckettsean** [comment]
@toddboom

**Comment by toddboom** [comment]
This is just waiting on the Homebrew contributors to merge:

https://github.com/Homebrew/homebrew/pull/43988

If you want to give them a +1, maybe it will help?

**Comment by beckettsean** [comment]
Thanks for kicking them, @toddboom, verified it's available now.
