### ISSUE TITLE
Inserting timestamps from the future doesn't work

### ISSUE THREAD

**Issue by pga23** [influxdb/influxdb#4158]
I'm trying to insert timestamps bigger than now and it doesn't work (at least in 9.3 version)

In the following example only 1st row will be inserted:
example value="2010-01-01" 1262304000000000000
example value="2020-01-01" 1577836800000000000

**Comment by otoolep** [comment]
How do you know it does not work?

**Comment by pga23** [comment]
Just by using "write data" in default InfluxDB web interface

**Comment by toddboom** [comment]
@pga23 it's likely that the points are being written, but the default end time for a query is `now()`. you'll find some assistance here:

https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now

**Comment by toddboom** [comment]
see also #2551
