### ISSUE TITLE
query parser should throw error on improper "now"

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4159]
I think this query should throw a parser error instead of returning the results for all time:
```
> select count(value) from cpu_idle where time > now - 30d group by time(1d)
name: cpu_idle
--------------
time			count
1970-01-01T00:00:00Z	920900
```

The `GROUP BY` clause and the `WHERE time` clause were both ignored just because of the difference between `now` and `now()`. I would expect a parser error that `now` is not a valid comparator for `time`.

**Comment by timraymond** [comment]
@beckettsean This seems to be a dupe of what you mentioned in #4044 .

**Comment by beckettsean** [comment]
dupe of #4044
