### ISSUE TITLE
[0.9.4.1] parser error message isn't aware of the new SHOW commands

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4164]
```
> show statistics
ERR: error parsing query: found statistics, expected CONTINUOUS, DATABASES, FIELD, GRANTS, MEASUREMENTS, RETENTION, SERIES, SERVERS, TAG, USERS at line 1, char 6
```

The command is `SHOW STATS`, but the "expected" strings should include `STATS` and `DIAGNOSTICS` and `SHARDS`, now that the `SHOW STATS`, `SHOW DIAGNOSTICS`, and `SHOW SHARDS` queries are live.

**Comment by otoolep** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4166
