### ISSUE TITLE
[0.9.4.1] non-default Internal Monitoring Database Broken

### ISSUE THREAD

**Issue by Jhors2** [influxdb/influxdb#4167]
Internal monitoring appears to be broken in a cluster.  I created a fresh DB called "internal" I then created a retention policy with a replication of 3 and set it as default.  I started all nodes.  It appears the first node that starts sending metrics into that retention policy and DB stores the metrics, however the metrics aren't replicated to other nodes.

Furthermore, the other nodes are unable to write to that retention policy.  Am I doing something wrong?  In one of the nightlies the retention policy name and replication policy was configurable, it seemed to work well in that state.

**Comment by otoolep** [comment]
How do you know the metrics are not replication to other nodes? Also, is there an error in the logs regarding the failed writes to the retention policy?

To be clear the internal monitoring uses exactly the same write-path as the rest of the system, so I am surprised it is giving you trouble.

**Comment by beckettsean** [comment]
@Jhors2 I believe the correct database for monitoring is `_internal` and it is auto-created. Those settings can be overridden in the config file.

**Comment by otoolep** [comment]
Ah, yes, @beckettsean is correct, it is `_internal` -- resources created by the system itself are prefixed with an underscore.

Do `SHOW DATABASES` to see it.

**Comment by Jhors2** [comment]
I overrode the default database so I could create a fresh one ahead of time on reload.  As an update I noticed the following:
Nodes that are failing to write metrics:
```
name: internal
--------------
id	start_time		end_time		expiry_time		owners
56	2015-09-18T00:00:00Z	2015-09-19T00:00:00Z	2015-10-19T00:00:00Z	3,1,2
name: internal
--------------
id	start_time		end_time		expiry_time		owners
56	2015-09-18T00:00:00Z	2015-09-19T00:00:00Z	2015-10-19T00:00:00Z	3,1,2
```
Node that is successfully writing metrics:
```

name: internal
--------------
id	start_time		end_time		expiry_time		owners
67	2015-09-18T00:00:00Z	2015-09-19T00:00:00Z	2015-10-19T00:00:00Z	3,1,2
```

This is then causing the logs with shard 56 to constantly complain that they cannot accept a write to shard 57.  I didn't touch any files on disk so I'm not sure how it got into this state.  I recreated the DB a second time and it appears to still be the same as above.

**Comment by otoolep** [comment]
Hmmm. Can we see the log messages containing the write error?

Can we rule out the manually-created database? How about just deleting it,
leaving the replication at 3 (in the config) and letting the system
auto-create it? I don't think it should matter, but I am curious.

Philip

**Comment by Jhors2** [comment]
@otoolep What is the config option to add replication factor under the [monitor] section?  I don't see it in the config template anymore.

**Comment by otoolep** [comment]
@Jhors2 -- my apologies, I forgot that we pulled control of that.

However, after the database is created, you can change the replication factor on `_internal`, but the first group of shards will only have a replication factor of 1. We removed control of replication factor from the configuration file, so changes made by administrators would not be overriden on a node-restart.

This may be a sequencing issue. Would this be what has happened?

-- you set a non-default database for monitoring in the config.
-- you started the nodes.
-- the system started and created this database automatically, with a retention policy called `monitor` and a replication factor of 1.
-- you then created the database -- was there any error about it already existing?
-- you changed the replication factor to 3, via the CLI. This will take affect, but only the next time shards are created for the retention policy `monitor`. This could take a day. Right now data is being written with a replication factor of 1, not 3, but that will change soon.

Does this make sense? This may expose some practical issues with configuration management of the monitoring database.

**Comment by Jhors2** [comment]
Order of operations was:
--Nodes Running
--Create non-default database
--Create RP in database called "monitor" with replication of 3 and "default"
--Change config to point at new Database
--Restart each node one at a time

I'll give ALTER on the RP a shot and see how it goes, I'll report back in a day.
Thanks!

**Comment by otoolep** [comment]
OK what you did sounds reasonable and *should* have worked. Since you didn't restart the node until after changing the config, the monitoring system should have written successfully to the non-default database and RP.

What are the write-errors in the logs?

**Comment by otoolep** [comment]
Can I see the `monitor` block of your config file? And the output of `SHOW RETENTION POLICES ON monitor`?

**Comment by Jhors2** [comment]
Write error in the log is:
```
[tcp] 2015/09/18 15:05:36 drop write request: shard=67. shard group does not exist or was deleted
```
This is obviously on the nodes that are failing to write.

Monitor config section:
```
[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "internal" # The destination database for recorded statistics
  store-interval = "10s" # The interval at which to record statistics
```
Retention policies on the non-default DB I created:
```
> show retention policies on "internal"
name	duration	replicaN	default
monitor	720h0m0s	3		true
```

**Comment by otoolep** [comment]
There was some confusing cruft in the monitor sample config, which I have corrected:

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L99

**Comment by otoolep** [comment]
I will need to setup a cluster to replicate this.

@jwilder -- how could the error above happen?

**Comment by jwilder** [comment]
Possibly a race where the coordinating node creates a new shard group and ends up sending it to the remote node before the remote node learned about the new shard group. Are the nodes logging this write error part of the raft group or data nodes?

Another possibility is that there is a bug in the shard lookup func that is preventing it from pinging the leader in a cache miss.

**Comment by Jhors2** [comment]
These nodes are apart of the raft group, all are brokers.  It seems even with letting the first node create the DB then altering the retention policy that other nodes still cannot write to the monitoring DB.

**Comment by otoolep** [comment]
The latest nightly builds includes new stats named `cluster` (available via` `SHOW STATS`). These stats will confirm if the system is remotely accessing shards when it should not otherwise be.

I'd be interested in the output of this command. This is also relevant for issue https://github.com/influxdb/influxdb/issues/4170

**Comment by otoolep** [comment]
@Jhors2 -- since we know that some shards of the `_internal` database are assigned to nodes that are registered by IP, and those node registrations are in a potentially invalid state, these errors may be generated by attempting to access those nodes. The cluster should not be attempting to access those nodes at all.

Once we clear up the invalid nodes, this issue may be addressed as a side-effect.

**Comment by otoolep** [comment]
No more to do here.
