### ISSUE TITLE
[0.9.3] Fails to write points with timestamps in the future

### ISSUE THREAD

**Issue by nmarshall23** [influxdb/influxdb#4169]
Any Insert request that contains points with a timestamp that is in the future causes no field data to be written. However tags get written.

Influx should return an error when it doesn't write points. 

The current behavior is very confusing because SHOW TAG KEYS, and SHOW FIELD KEYS, shows the correct tags and fields. However, selects on that measurement would give me an empty result.

**Comment by otoolep** [comment]
Can you show the query that returns now data?

Unless you explicitly specify an upper time bound, it defaults to now. That would explain why you get no data.

https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now

**Comment by beckettsean** [comment]
@nmarshall23 please see https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#querying-after-now

Works just fine in 0.9.4.1, but as the docs say you must explicitly set the upper bound of the time range to something more in the future than the points you are querying. By default the upper bound is `now()`, so anything in the future does not match the criteria:

```
Connected to http://localhost:8086 version 0.9.4.1
InfluxDB shell 0.9.4.1
> use mydb
Using database mydb
> insert inthefuture,hello=true value=42 1942623186000000000
> select * from inthefuture
> select * from inthefuture where time < now() + 1000w
name: inthefuture
-----------------
time			hello	value
2031-07-24T01:33:06Z	true	42

>
