### ISSUE TITLE
how to use "group by"  in influxdb 

### ISSUE THREAD

**Issue by testzlx** [influxdb/influxdb#4182]
here is the case : I use influxdb to record the accesslog of  nginx ,I want to seek out the frequence of every different ip in a minute .how do I work the "influxdb sql" out ? I will appreciate it if you give me some tips?

**Comment by rkuchan** [comment]
@testzlx, 

Because this isn't a feature request or bug, I'm closing this in favor of you submitting a support ticket. You can do that by emailing support@influxdb.com and we'll be happy to help you out.
