### ISSUE TITLE
[0.9.3] Less than or equal to inequality is not inclusive for time in where clause

### ISSUE THREAD

**Issue by bal2ag** [influxdb/influxdb#4193]
OS: OS X 10.10.4 (although I have seen the same issue on other OSes)
InfluxDB version: 0.9.3
Install: Pre-built package
Test case: Should be able to repro on any database, just format the query as below using <= for time upper bound.

I have the following data in my InfluxDB database (among other data):

```
...
2015-09-09T07:56:00Z		testapp1	testbeacon1	herp	testent1
2015-09-09T07:56:47Z		testapp1	testbeacon1	herp	testent1
2015-09-09T08:22:15Z		testapp1	testbeacon1	herp	testent1
...
```

When I try to query using an inclusive upper and lower bound on time, only the lower bound is actually inclusive - the upper bound is exclusive.

```
> select * from ping where time >= '2015-09-09T07:56:00Z' and time <= '2015-09-09T08:22:15Z'
name: ping
----------
time			application_id	beacon_id	derp	entity_id
2015-09-09T07:56:00Z	testapp1	testbeacon1	herp	testent1
2015-09-09T07:56:47Z	testapp1	testbeacon1	herp	testent1
```

Can anyone shed some light on what might be happening? Is the <= inequality not supported? Is there some sort of clock skew issue?

Thanks very much.

**Comment by rkuchan** [comment]
Thanks, @bal2ag! I was able to repro. This is a bug.
