### ISSUE TITLE
Retention policy

### ISSUE THREAD

**Issue by szop85** [influxdb/influxdb#4214]
Hello guys,

we are using InfluxDB in combination with Graphite to collect measurements and therefor I'd like to ask, if it's possible to setup a retention policy on different levels? Like i.e.:

- each data point represents 30 seconds and we want to keep up to 7 days of data with such frequency
- all historical data for the last 30 days is stored in 5 minute intervals
- all historical data for the last year is stored in 10 minute intervals
- etc.

Does it make sense?

Cheers,
Szop

**Comment by otoolep** [comment]
Why don't you configure the retention policy that Graphite writes into as 7
days, and use Continuous Queries to downsample into the other
retention policies? That is the way to do it.

Note we can't keep every 10th measurement, you will instead need to
aggregate across 10 minute windows.

https://influxdb.com/docs/v0.9/query_language/continuous_queries.html

Philip

**Comment by otoolep** [comment]
I believe CQs are the best way to do this. The mailing list would be the best place for further general knowledge questions.

https://groups.google.com/forum/#!forum/influxdb

**Comment by szop85** [comment]
Grate! Thanks guys!
