### ISSUE TITLE
Timeouts after a few writes to InfluxDB

### ISSUE THREAD

**Issue by willemdh** [influxdb/influxdb#4216]
Hello,

I'm trying to write data ( a bunch of Windows perfmon counters) every 5 seconds to InfluxDB 0.9.4 with this Powershell code

```powershell
$authheader = "Basic " + ([Convert]::ToBase64String([System.Text.encoding]::ASCII.GetBytes("InfluxAdmin:m3MOvzjdaidjaocrGGd2n")))
$uri = "http://$($InfluxDBServer):$($InfluxDBServerPort)/write?db=db_grafana01"
Invoke-RestMethod -Headers @{Authorization=$authheader} -Uri $uri -Method POST -Body $Metrics
```

This works fine when I do this manually one time. But when I make a loop and make it write these counters every 5 seconds, I get this error after the third time my PS script is trying to write data.

```powershell
Error sending metrics to the Graphite Server. Please check your configuration file. 
PSMessageDetails      : 
Exception             : System.Net.WebException: The operation has timed out
                           at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
                           at System.Net.HttpWebRequest.GetRequestStream()
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.SetRequestContent(WebRequest request, String content)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.FillRequestStream(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : System.Net.WebException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at SendMetrics, C:\Nagios\NAF\NAF_Sources\Tools\Grafana\naf_send_metric_to_influxdb.ps1: line 143
                        at Send-BulkInfluxDBMetrics, C:\Nagios\NAF\NAF_Sources\Tools\Grafana\naf_send_metric_to_influxdb.ps1: line 229
                        at Start-StatsToInfluxDB, C:\Nagios\NAF\NAF_Sources\Tools\Grafana\naf_send_metric_to_influxdb.ps1: line 403
                        at <ScriptBlock>, C:\Nagios\NAF\NAF_Sources\Tools\Grafana\naf_send_metric_to_influxdb.ps1: line 424
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

I tried augmenting the commit-timeout in influxdb.conf from 50ms to 500ms and later to 1000ms, but it still times out.
Also tried to augment shard-writer-timeout from 5s to 10s and write-timeout from 5s to 10s, but this also didn't help.

What else can I do to prevent me from getting timeout error? There is only one server sending data to InfluxDB and I'm only sending a few counters. The server is not under heavy load or anything.

This is an example of the data I'm sending each invoke-restmethod:
```powershell
 hdd.e-drive.avg.diskreadqueuelength,host=server1,region=test value=0 
 cpu.usage,host=server1,region=test value=2.30835600969209 
 hdd.total.avg.diskwritequeuelength,host=server1,region=test value=0 
 nic.vmxnet3ethernetadapter.packetsreceivednon-unicast-sec,host=server1,region=test value=7.94371726813738 
 nic.vmxnet3ethernetadapter.packetssentunicast-sec,host=server1,region=test value=10.9226112436889 
 mem.pages-sec,host=server1,region=test value=0 
 mem.pagesinput-sec,host=server1,region=test value=0 
 hdd.c-drive.avg.diskreadqueuelength,host=server1,region=test value=0 
 nic.vmxnet3ethernetadapter.bytesreceived-sec,host=server1,region=test value=1040.626962126 
 hdd.total.avg.diskreadqueuelength,host=server1,region=test value=0 
 mem.availablembytes,host=server1,region=test value=1602 
 hdd.c-drive.avg.diskwritequeuelength,host=server1,region=test value=0 
 nic.vmxnet3ethernetadapter.packetssentnon-unicast-sec,host=server1,region=test value=0 
 nic.vmxnet3ethernetadapter.packetsreceivedunicast-sec,host=server1,region=test value=5.95778795110304 
 nic.vmxnet3ethernetadapter.bytessent-sec,host=server1,region=test value=9820.42047273484 
 system.processorqueuelength,host=server1,region=test value=0 
 hdd.e-drive.avg.diskwritequeuelength,host=server1,region=test value=0 
 system.threads,host=server1,region=test value=910 
```

Any help to get this working properly is welcome.

**Comment by otoolep** [comment]
Please work with the output of `SHOW STATS` and `SHOW DIAGNOSTICS` to see if there are any clues in there.

https://influxdb.com/blog/2015/09/22/monitoring_internal_show_stats.html

**Comment by beckettsean** [comment]
@willemdh what happens if you run the code standalone multiple times? You said it works when run once standalone, and it fails on the third iteration of a loop. What about the third time you run it manually?

What if you run it more often than every 5 seconds? Maybe it's a timeout issue?

**Comment by willemdh** [comment]
@otoolep I can see data when I execute SHOW STATS or SHOW DIAGNOSTICS. I'm able to add the_internals database as datasource to Grafana and successfully test the connection. But when I try to make a graph in Grafana for anything in the _internals db, the graph shows "no datapoints". 
SELECT mean(value) FROM "httpd" WHERE "hostname" = 'grafserver' AND $timeFilter GROUP BY time($interval)
SELECT mean(value) FROM "httpd" WHERE "bind" = ':8086' AND $timeFilter GROUP BY time($interval)
Every query I try is able to find and autocomplete the measurement, and keys, but I seem unable to make a graph of the stats and diagnostics in Grafana for now.

**Comment by otoolep** [comment]
@willemdh -- can you please show us output from the CLI? That we can confirm that no data is being returned by InfluxDB.

**Comment by willemdh** [comment]
@otoolep I've been trying to execute the query in cli, but I seem to have an an issue connecting to the database:
```
influx -username InfluxDbAdmin -password testpassword -database _internal
ERR: unable to parse Basic Auth credentials
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
```

Sorry for the noobish question, but I've tried numerous combinations to try connect to the db and execute a query, but I seem to keep getting "ERR: unable to parse Basic Auth credentials"

**Comment by otoolep** [comment]
Are you using authentication your database? Please avoid the CLI and your code to troubleshoot this issue and try using `curl` directly.

https://influxdb.com/docs/v0.9/guides/writing_data.html

Can you try that?

**Comment by willemdh** [comment]
Yes I can try that. I downloaded curl.exe for Windows and will give that a try asap.

**Comment by willemdh** [comment]
@otoolep My first tests were positive. I did not receive any timeout. curl > invoke-restmethod apparently. It should also work with invoke-restmethod though imho:
https://technet.microsoft.com/en-us/library/hh849971.aspx
Or not?

**Comment by otoolep** [comment]
Unfortunately @willemdh -- I have zero experience with that Microsoft library. If `curl` works fine, it must be something in your client software, so you focus your debug on that. InfluxDB seems to be working fine.

**Comment by willemdh** [comment]
@otoolep @beckettsean 

I have a working Powershell script that can be activated to send all Windows counters specified in an xml to InfluxDB. I'll publish it on GitHub once it's a bit more finished. Thanks. I guess this can be closed.

**Comment by willemdh** [comment]
@otoolep @beckettsean 
Here it is:
https://github.com/willemdh/naf_windows_perfmon_to_influxdb

**Comment by beckettsean** [comment]
Thanks, @willemdh. Is this something you'd like us to list on https://influxdb.com/docs/v0.9/clients/api.html?

**Comment by willemdh** [comment]
@beckettsean Sure. Would be cool. :)

**Comment by benyoungnz** [comment]
@willemdh - bit late for you probably but anyone else having this issue sounds similar to what i was having, firing off multiple calls in a single powershell session, 

Check out the System.Net.ServicePointManager, has a default of 2 connections per endpoint, i pretty much do the following

$ServicePoint = [System.Net.ServicePointManager]::FindServicePoint("http://influxendpoint/write...")
#you could do something like this or manually clear out as required.
$ServicePoint.ConnectionLimit = 10
#start clean
$ServicePoint.CloseConnectionGroup("")

Invoke Webrequests here...

#keep using as needed.
$ServicePoint.CloseConnectionGroup("")

**Comment by willemdh** [comment]
@benyoungnz 

Thanks for sharing, I'll put this on my to do to test this. I'm using curl.exe for Windows atm which seems to work fine for now, but as it it is dependent of an external tool (curl.exe) I think It would be a good idea to make https://github.com/willemdh/naf_windows_perfmon_to_influxdb work natively with invoke-webrequest.

Created https://github.com/willemdh/naf_windows_perfmon_to_influxdb/issues/1 for this.
