### ISSUE TITLE
GROUP BY on tag does not work if there is a value with the same name.

### ISSUE THREAD

**Issue by kwando** [influxdb/influxdb#4217]
I'm not allowed to use group by on a tag it there is value with the same name.

```
$ influxd version
InfluxDB v0.9.4.1 (git: 0.9.4 c4f85f84765e27bfb5e58630d0dea38adeacf543)
```

**Comment by corylanou** [comment]
Writing a tag and a field with the same name is not supported.  Due to the way shards are written, we can't prevent this from happening, but when reading the data there is no way for us to know what you want to retrieve.

**Comment by kwando** [comment]
Hmm, okey. Maybe drivers should throw an exception if that happens then.

**Comment by corylanou** [comment]
For some cases, we could, but for others, we can not. Meta data for fields and tags are not stored at the consensus layer, but at the shard layer.  This is done to support the speed of writes that the database needs to ingest.

So, for instance, if you wrote a single point with both a field and a tag with the same name, I agree, we could easily reject that write.

Effectively I'm agreeing with you, but it's not an easy problem to solve, but hopefully we will keep working towards that.  I think it's fair to say we might need to make this clearer when people are learning about InfluxDB for good design practice.

//cc @beckettsean

**Comment by beckettsean** [comment]
Related issue for preventing duplicate tag and field keys: https://github.com/influxdb/influxdb/issues/2615

@kwando you should get a meaningful error message when attempting it:

```
> insert tagfield,abab=def abab=42
> select * from tagfield group by abab
ERR: can not use field in GROUP BY clause: abab
```

**Comment by kwando** [comment]
I was using the ruby driver and it did not raise an exception:
https://github.com/influxdb/influxdb-ruby

And yeah, highlighting this in the documentation would probably be good. I'm probably not the first and most likely not the last one to hit this error.
