### ISSUE TITLE
Handle out of memory panics at a global level?

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#4220]
Talking with Paul quickly, it sounds like this might be possible. Is there a way we can wrap the server process and catch these so that the server returns a 500 instead of dying?

Example stack trace:
```
[query] 2015/09/24 13:10:50 SELECT * FROM "analytics"."default"./.*/
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58a40, 0x16)
	/home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc853e00000, 0x100000, 0x195d00, 0x10235f8)
	/home/philip/.gvm/gos/go1.5/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x1003980, 0x100000, 0x0)
	/home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0x1003980, 0x8, 0x0)
	/home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x1003980, 0x1, 0x7fa916d1b0a0)
	/home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x1003980, 0x1, 0x7f0000000013, 0x7fa916d1b0a0)
```

**Comment by corylanou** [comment]
You would have to trap the panic at the entry point to the program (effectively main.go for cmd/influxd).  You can't catch a panic in a defer/recover for a process that you didn't spawn.

**Comment by corylanou** [comment]
Or I guess we could wrap our query engine in a defer/recover (or parts of it) and let it return an error when it panics.

**Comment by otoolep** [comment]
@corylanou -- can you trap "fatal" errors? This doesn't look like a panic.

**Comment by corylanou** [comment]
ah, nope, fatal is effectively `panic() + os.Exit()` doh!

**Comment by otoolep** [comment]
OK, then a diaper pattern sounds doable.

http://mike.pirnat.com/2009/05/09/the-diaper-pattern-stinks/

**Comment by otoolep** [comment]
Oh, @corylanou when you said "effectively" you didn't mean "actually is". I misread your comment.

**Comment by corylanou** [comment]
correct, so as far as I know, this can't be done.  See this example: http://play.golang.org/p/_Jf1FL8J6r

**Comment by DanielMorsing** [comment]
log.Fatal goes through a different path than runtime fatal errors.

Runtime fatal errors cannot be caught. The defers will be run, but after a recover, the process exits

**Comment by pkittenis** [comment]
Also hitting this very regularly - similar stack trace as the first post above. 

In our case WAL flushes trigger OOM - similar to OOM during bulk load issues reported else where.

Eg:

```
[wal] 2015/09/25 11:41:21 Flush due to memory. Flushing 118163 series with 617864 points and 10503688 bytes from partition 1
[wal] 2015/09/25 11:41:23 write to index of partition 1 took 4.093154367s
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58a40, 0x16)
        /home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc957460000, 0x100000, 0x2acaf31f7000, 0x10235f8)
        /home/philip/.gvm/gos/go1.5/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x1003980, 0x100000, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:423 +0x160
<snip>
```

**Comment by benbjohnson** [comment]
Even if we could catch OOM errors, there's not much we could do since handling them would probably involve creating at least one object which would, in turn, cause an OOM.

@pkittenis how much RAM are you running with? Also, how long is influx running before the OOM occurs?

**Comment by pkittenis** [comment]
16GB RAM on the server, influxdb using ~8GB resident. DB size is ~34GB at the moment but OOM happens even on a new DB.

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                  
18710 influxdb  20   0 49.4g 7.7g 3.0g S 11.7 49.4  51:26.49 influxd```

Run time is anything from a few minutes to a few hours before it OOM. Seems to be triggered by a spike of incoming metrics that cause a WAL flush due to memory, as above stack trace.

**Comment by pkittenis** [comment]
Latest OOM just now after 3 hours of run time.

```
[wal] 2015/09/25 14:14:23 Flush due to memory. Flushing 120522 series with 618329 points and 10511593 bytes from partition 1
[wal] 2015/09/25 14:14:23 Flush due to idle. Flushing 141 series with 141 points and 4413 bytes from partition 1
[wal] 2015/09/25 14:14:23 write to index of partition 1 took 645.136527ms
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58a40, 0x16)
        /home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc955a10000, 0x100000, 0x195d00, 0x10235f8)
        /home/philip/.gvm/gos/go1.5/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x1003980, 0x100000, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0x1003980, 0x8, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:628 +0x63
```

**Comment by mark-rushakoff** [comment]
> Even if we could catch OOM errors, there's not much we could do since handling them would probably involve creating at least one object which would, in turn, cause an OOM.

It's not unheard of to [set aside a "rainy day fund"](http://stackoverflow.com/a/11788835) at the beginning of a program, and then free it in an OOM scenario to better handle the error. It may not be enough free memory to allow you to fully recover from the OOM, but it could potentially be enough to dump a bit more information about what went wrong.

**Comment by benbjohnson** [comment]
@pkittenis A memory profile would be great! You can run:

```
$ go tool pprof -svg -output heap.svg /path/to/influxd http://localhost:6060/debug/pprof/heap
```

Then just send the `heap.svg` file that's output.

@mark-rushakoff a rainy day fund works for C but it seems difficult to do with a GC language like Go.

**Comment by parisholley** [comment]
@benbjohnson I try to run this to dig into my OOM issues on a new install and get:

```
Fetching profile from http://localhost:8086/debug/pprof/heap
parsing profile: unexpected number of sample values: got 0, want 6
```

**Comment by parisholley** [comment]
@benbjohnson Here is a SVG for my setup, single node (r3.xlarge), 96% memory usage, ~4GB of data with 20M/s being send to server (according to AWS). Currently takes 5 minutes to restart db. One a fresh database everything is fast but eventually OOM about 6 hours in. On restart, it doesn't stay up for long.

http://imgh.us/heap.svg

**Comment by pkittenis** [comment]
Hi,

[Here is heap SVG](https://gist.github.com/pkittenis/3ef48fc062902840d749/raw/eecb6b43fce732df7220dec0e943fc660d700cca/heap.svg) a few seconds before the process OOM.

```
[wal] 2015/09/29 16:09:17 write to index of partition 1 took 7.737877299s
[wal] 2015/09/29 16:09:17 write to index of partition 1 took 7.415779513s
[wal] 2015/09/29 16:09:17 write to index of partition 1 took 713.386871ms
[wal] 2015/09/29 16:09:17 write to index of partition 1 took 7.482164418s
[wal] 2015/09/29 16:09:19 Flush due to memory. Flushing 120432 series with 618795 points and 10519515 bytes from partition 1
[wal] 2015/09/29 16:09:20 Flush due to idle. Flushing 83 series with 84 points and 1428 bytes from partition 1
[wal] 2015/09/29 16:09:20 write to index of partition 1 took 12.886874ms
fatal error: runtime: out of memory
```

**Comment by otoolep** [comment]
We can't handle OOM like this, co closing.
