### ISSUE TITLE
[0.9.4.1] Version number in UI is 0.9.3.

### ISSUE THREAD

**Issue by jordmoz** [influxdb/influxdb#4221]
This is such a minor issue. The influxdb UI shows the version number as 0.9.3.  It's a little confusing.

**Comment by ecables** [comment]
Also present in 0.9.5 nightly.

**Comment by ymettier** [comment]
Hello,

I have noticed it too.
@otoolep : that should be easy to fix. Any idea ?

Regards,
Yves

**Comment by otoolep** [comment]
I think so, but this is one for @toddboom , not me!

**Comment by alexiri** [comment]
I created a pull request (#4125) for this, but it has yet to be merged.

**Comment by gunnaraasen** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4777 and https://github.com/influxdb/influxdb/pull/4131.
