### ISSUE TITLE
listen on both http and https

### ISSUE THREAD

**Issue by yee379** [influxdb/influxdb#4239]
is this possible? 

i have an iframe on a https webserver that has src of my https grafana instance which needs to read from https influx.

however, i would like to keep writing to influx without the overhead of https at the moment (and while we migrate everything over)

**Comment by otoolep** [comment]
No, this is not possible with the current software.

**Comment by yee379** [comment]
:( i wonder whether having this feature would be better than sticking it behind apache/nginx/haproxy... i wonder if the overhead of reverse proxies would be ideal for such high volume traffic. thoughts?

**Comment by otoolep** [comment]
@yee379 -- I don't have any special knowledge in that area, I suggest you just try it out and see how it goes.
