### ISSUE TITLE
[0.9.4.1] timeouts after dropping measurement

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4241]
trying to test new continuous queries, realize I made a mistake and try to drop the query, then the measurement it inserted into causes problems. soon as I issue the drop on the measurement, the logs fill up with:

"failed to write point batch to database"

and the server becomes unresponsive until I restart (and the measurement is never dropped). I can still run commands like "show measurements" but anything that queries data never returns (like it locks the entire db).

behavior is the same in 0.9.5_nightly_b079d20-1

**Comment by beckettsean** [comment]
@parisholley can you provide explicit steps to reproduce, or a copy/paste of your curl or CLI session that leads to the issue?

**Comment by parisholley** [comment]
@beckettsean doesn't seem to be an issue on nightly using the "bz" engine

**Comment by beckettsean** [comment]
@parisholley thanks for the update!
