### ISSUE TITLE
[0.9.3] Crashed when dropping a database

### ISSUE THREAD

**Issue by SamyPesse** [influxdb/influxdb#4243]
I'm currently evaluating influxdb to store ~50 millions entries (visits on websites) to serve stats for specific website.

I tested importing ~10 millions entries in the same serie (I'll now test to use a unique serie for each website). It took the all ram (`influxd` was using ~14gb of RAM and 300% CPU on my mac mini).
After 20min, I restarted it and again it took the all RAM and CPU, and queries were not working (`SELECT COUNT(value) FROM visits`).

So I tried dropping the database using `DROP DATABASE websites`, to start the other test with multiple series, but it crashed the `influxd`. I guess it was not a good idea dropping the database when `influxd` was working, but I wanted to start fresh.

Here is a gist with al the logs: https://gist.github.com/SamyPesse/6588de45481453f31484

How can I cleanup influxdb/database to start fresh ?

**Comment by beckettsean** [comment]
@SamyPesse to start over with a fresh system, simply delete everything in the influxdb directory. On OS X if you installed from homebrew that would be the `~/.influxdb` directory.
