### ISSUE TITLE
[0.9.4.1] udp/hash algorithm not distributing partitions?

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4245]
```
[udp] 2015/09/27 04:06:15 failed to write point batch to database 
```

trying to figure out why I have so many timeouts, notice that every single line from WAL logged refers to "partition 1". I am using UDP to inject events and don't see any activity on the other partitions within the logs.

I suspect this may be why I am seeing my memory usage go through the roof, the udp module isn't able to flush and keeps everything in memory?

**Comment by jhorwit2** [comment]
I'm noticing the same weird partition issues except I'm not using UDP. Seems to be a general WAL writing/flushing issue. #4240

**Comment by otoolep** [comment]
With the default engine in 0.9.4.1 there is only 1 partition.
