### ISSUE TITLE
Missing types.db file for collectd plugin causes server to fail to start

### ISSUE THREAD

**Issue by toddboom** [influxdb/influxdb#4246]
Maybe this is intended behavior, but I wanted to make a note regardless. Should plugin startup failing cause the server to die?

**Comment by otoolep** [comment]
Yes, this has always been the case. I see no reason why the server should carry on if an explicitly configured plugin won't start.

**Comment by otoolep** [comment]
To be clear, it shouldn't panic, but it should error with a clear message in the logs or at `STDERR`.

**Comment by otoolep** [comment]
I don't believe there is any issue here.
