### ISSUE TITLE
[0.9.5-nightly-b079d20] no result when filtering on tag with no data

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4247]
select count(value) from measurement where tag = 'value1';

if there is no series where tag = 'value1', instead of returning count = 0, it returns an empty response

**Comment by beckettsean** [comment]
This is the designed behavior. For any valid query that has no matching data InfluxDB returns an empty response.

**Comment by parisholley** [comment]
@beckettsean are there technical limitations that lead to that design choice? in particular, I believe the lack of a response can cause issues with continuous queries (not an issue for me now, but think I ran into it in the past). If I remember correctly, I thought the user of intervals filled in gaps when data was empty (ie: towards begining of time frame) if there was data at the end of the timeframe. Wouldn't it make sense to make it consistent even if there is no data?

while most of my current use is through grafana (will be making direct API calls soon), i'm sure the client could indeed handle the lack of a response appropriately but I can see it being a PITA (but that is an issue for the grafana project).

Example use case: Dynamic grafana chart where a user can type in the state code. For one chart, I may show two lines where TAG='value1' and TAG='value2' for that item. It is very possibly that for that state, value2 isn't applicable, but for other states it is. Client code could be much cleaner if it could assume that both would return the same intervals (even if one has non existent data) for comparison across each other. Otherwise, you are having to write interval gap logic on client side and risk bugs.

**Comment by parisholley** [comment]
@beckettsean someone recently pointed out the fill(0) functionality to me, however it doesn't seem to apply in this case. perhaps that is a compromise? as it solves how to handle a situation where no data exists?

**Comment by beckettsean** [comment]
`fill(0)` is intended to address this issue and will add zeros to the buckets that otherwise have no value:

```
> select count(value) from cpu_idle where time > now() - 12h group by time(1h)
name: cpu_idle
--------------
time			count
2015-09-28T12:00:00Z	
2015-09-28T13:00:00Z	
2015-09-28T14:00:00Z	
2015-09-28T15:00:00Z	
2015-09-28T16:00:00Z	468
2015-09-28T17:00:00Z	
2015-09-28T18:00:00Z	4599
2015-09-28T19:00:00Z	3564
2015-09-28T20:00:00Z	4635
2015-09-28T21:00:00Z	4626
2015-09-28T22:00:00Z	4320
2015-09-28T23:00:00Z	4626
2015-09-29T00:00:00Z	540


> select count(value) from cpu_idle where time > now() - 12h group by time(1h) fill(0)
name: cpu_idle
--------------
time			count
2015-09-28T12:00:00Z	0
2015-09-28T13:00:00Z	0
2015-09-28T14:00:00Z	0
2015-09-28T15:00:00Z	0
2015-09-28T16:00:00Z	468
2015-09-28T17:00:00Z	0
2015-09-28T18:00:00Z	4599
2015-09-28T19:00:00Z	3564
2015-09-28T20:00:00Z	4635
2015-09-28T21:00:00Z	4626
2015-09-28T22:00:00Z	4320
2015-09-28T23:00:00Z	4626
2015-09-29T00:00:00Z	540
```

However, the initial case was one where there is simply no matching data. When nothing matches the `WHERE` clause `fill(0)` does not function. I don't have a deep enough understanding of the system to describe why the two are different:

```
> select count(value) from cpu_idle where time > now() - 12h AND cpu='cpu1' group by time(1h) fill(0)
name: cpu_idle
--------------
time			count
2015-09-28T12:00:00Z	0
2015-09-28T13:00:00Z	0
2015-09-28T14:00:00Z	0
2015-09-28T15:00:00Z	0
2015-09-28T16:00:00Z	52
2015-09-28T17:00:00Z	0
2015-09-28T18:00:00Z	511
2015-09-28T19:00:00Z	396
2015-09-28T20:00:00Z	515
2015-09-28T21:00:00Z	514
2015-09-28T22:00:00Z	480
2015-09-28T23:00:00Z	514
2015-09-29T00:00:00Z	73

> select count(value) from cpu_idle where time > now() - 12h AND cpu='invalid' group by time(1h) fill(0)
> 
```

**Comment by beckettsean** [comment]
@jwilder why does `fill(0)` work when there is at least one valid point returned for at least one bucket, but if there are no matching points there are no buckets returned at all?

**Comment by jwilder** [comment]
fill will give each bucket a value if it would have been nil. The derivative function then uses that value to calculate the difference between buckets.

**Comment by beckettsean** [comment]
@jwilder I get that behavior, I'm wondering why the `fill` function doesn't do anything if all buckets are `nil`. Instead of getting the buckets returned with whatever `fill` specifies there's just an empty response.

For example, here's the data:

```
> insert fillfunc,a=1 value=1 1443547642000000000
> insert fillfunc,a=1 value=2 1443547643000000000
> insert fillfunc,a=1 value=3 1443547644000000000
> insert fillfunc,a=1 value=4 1443547645000000000
```

And here's the successful query with `fill`:

```
> select count(value) from fillfunc where time > 1443547641000000000 and time < 1443547652000000000 and a='1' group by time(1s) fill(0)
name: fillfunc
--------------
time			count
2015-09-29T17:27:21Z	0
2015-09-29T17:27:22Z	1
2015-09-29T17:27:23Z	1
2015-09-29T17:27:24Z	1
2015-09-29T17:27:25Z	1
2015-09-29T17:27:26Z	0
2015-09-29T17:27:27Z	0
2015-09-29T17:27:28Z	0
2015-09-29T17:27:29Z	0
2015-09-29T17:27:30Z	0
2015-09-29T17:27:31Z	0
```

but if there's no matching point at all, the query just returns an empty response:

```
> select count(value) from fillfunc where time > 1443547641000000000 and time < 1443547652000000000 and a='2' group by time(1s) fill(0)
> 
```

**Comment by jwilder** [comment]
@beckettsean Not sure.   Would need to look into it further.

**Comment by beckettsean** [comment]
I'll open a new issue

**Comment by beckettsean** [comment]
Opened https://github.com/influxdb/influxdb/issues/4273 to investigate this
