### ISSUE TITLE
feature request: treat tags like fields in select?

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4253]
would be great if tag data is saved with field data, and can be accessed via the select statement, even if it is used mainly as an "index". write now, I am having to dual write data to work around it

**Comment by corylanou** [comment]
Can you provide an example of the data you wrote and how you are trying to query it so we can better understand your request?

**Comment by parisholley** [comment]
for instance

```
click,advertiser=1 foo=bar
click,advertiser=2 foo=bar
```

id like to:

```
select count(distinct(advertiser)) 
```
to determine number of unique advertisers (or any other tag point) per period

**Comment by otoolep** [comment]
Isn't `SHOW TAG KEYS` close to what you want? It doesn't have the `count` but it's close. 

https://influxdb.com/docs/v0.9/query_language/schema_exploration.html

**Comment by parisholley** [comment]
@otoolep nope. i'd like to see stats on how diverse certain tag sets are time. considering that strings aren't terribly useful as fields for the most party, there probably isn't a need to treat tag data as a full blown field, but I'd suppose it would make implementation easier.

**Comment by parisholley** [comment]
i suppose this could be solved by just doing a count and group by and handle on client side. just wouldn't be able to use directly in a tool like grafana..

**Comment by beckettsean** [comment]
closing as duplicate of https://github.com/influxdb/influxdb/issues/3880
