### ISSUE TITLE
Import MongoDB profile into Influxdb

### ISSUE THREAD

**Issue by hsalahi** [influxdb/influxdb#4254]
Hi! I'm trying to store MongoDB profile data into InfluxDB. I looked up a bit. One solution is to export the profile in JSON format but I'm not sure then it's possible to import it into InfluxDB! Is there any way to do it?

Thanks.

**Comment by jackzampolin** [comment]
@hsalahi,

Because this isn't a feature request or bug, I'm closing this in favor of you submitting a support ticket. You can do that by emailing support@influxdb.com and we'll be happy to help you out.
