### ISSUE TITLE
Interface conversion panic while running clustered

### ISSUE THREAD

**Issue by CVTJNII** [influxdb/influxdb#4256]
While testing in a cluster one of my nodes fell over with the following panic:

```
[query] 2015/09/25 22:53:40 SELECT mean(value) FROM "riemann"."default"."Test Data" WHERE host = 'Datagen 1' AND time > now() - 15m GROUP BY time(1s)
panic: interface conversion: interface {} is map[string]interface {}, not *influxql.meanMapOutput
```

Full panic is over 500 lines so I have pastebinned it here: http://paste.ubuntu.com/12603851/

As I'm currently testing the cluster was running in Docker.  Unfortunately docker-compose shut the containers down when this happened so I don't know how the cluster would have recovered.  I'm currently working on migrating my tests to Vagrant to avoid any docker issues.

I have not attempted to reproduce as I'm working on moving from Docker to Vagrant for testing.  Please let me know if you need any further information, I will update if this re-occurs outside of Docker.

- Host OS: Ubuntu 14.04 running in Docker
- Install method: .deb from http://influxdb.s3.amazonaws.com/influxdb_0.9.4.1_amd64.deb
- Influx Version: version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543

**Comment by otoolep** [comment]
This has been fixed in the 0.9.5 release. You can run with fix by installing a nightly build.

**Comment by otoolep** [comment]
See https://github.com/influxdb/influxdb/pull/4191

**Comment by CVTJNII** [comment]
Awesome, thanks!
