### ISSUE TITLE
[feature request] choose retention policy for udp

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4259]
currently, it will not work if you put <db>.<policy>, would be great to import into something other than default

**Comment by otoolep** [comment]
Agreed, it would be handy.

**Comment by otoolep** [comment]
Very straightforward change:

https://github.com/influxdb/influxdb/pull/4262

**Comment by otoolep** [comment]
All done @parisholley.

If you want this feature now, you can download a nightly tomorrow.

https://influxdb.com/download/index.html
