### ISSUE TITLE
[feature request] simple query to return health of the node for writes

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4274]
See https://groups.google.com/forum/#!msg/influxdb/O50VLuuNGRs/kYR-NbZ3DwAJ for the use case. Right now there's no way to know a cluster is good for writes except to send a write. However, writes must be POSTed, and many load balancer checks (ELB for example) can only issue GETs.

**Comment by jackzampolin** [comment]
Fixed by https://github.com/influxdb/influxdb/pull/4600/files
