### ISSUE TITLE
[0.9.4.1] DROP SERIES with a field in the WHERE clause always drops all points in the measurement

### ISSUE THREAD

**Issue by simcap** [influxdb/influxdb#4280]
I have got a series with values equal to 0. Since we decided not to push any value that is 0 in our InfluxDB, I want to clean up this serie and remove the existing values equal to 0. Here is what I did:

```
> select count(value) from p2p
name: p2p
---------
time      count
1970-01-01T00:00:00Z  286216

> select count(value) from p2p where value=0
name: p2p
---------
time      count
1970-01-01T00:00:00Z  113630

> drop series from p2p where value=0
> select count(value) from p2p where value=0
> select count(value) from p2p
name: p2p
---------
time      count
1970-01-01T00:00:00Z  3
```
I am surprised that is removed everything (the 3 entries is because the DB get populated at the same time by live clients).

Is the DROP series for a specific value supported?

**Comment by simcap** [comment]
(i have just updated the main description above)

**Comment by beckettsean** [comment]
I believe the `WHERE` clause for DROP SERIES only operates on tags. For it to work on fields (like `value`) it would have to scan every point in the series, as field values are unindexed.

**Comment by simcap** [comment]
Ok thanks for the info.

**Comment by beckettsean** [comment]
@simcap I am closing this in favor of another issue open on `DROP SERIES` (https://github.com/influxdb/influxdb/issues/4276). It appears the `WHERE` clause is not being properly evaluated

**Comment by beckettsean** [comment]
Actually, looking more closely these are two different issues. I'm re-opening this one to focus on the field matching not working. (I don't think it's supposed to work, but it should error or do nothing, not match all points instead.)

**Comment by beckettsean** [comment]
It appears that a `WHERE` clause containing a field key will match every point in the series, regardless:

```
> SELECT * FROM h2o_feet limit 4
name: h2o_feet
--------------
time				location	status!				water_level
1970-01-01T00:00:01.439856Z	santa_monica	below three feet		2.064
1970-01-01T00:00:01.439856Z	coyote_creek	between six and nine feet	8.12
1970-01-01T00:00:01.43985636Z	coyote_creek	between six and nine feet	8.005
1970-01-01T00:00:01.43985636Z	santa_monica	below three feet		2.116

> drop series from h2o_feet where water_level = 'foo'
> SELECT * FROM h2o_feet limit 4
> SELECT * FROM h2o_feet 
> 
```

Note that the `WHERE water_level = 'foo'` cannot ever be true, since `water_level` has floats and `foo` is a string. However, the `DROP SERIES` result suggests that the WHERE clause evaluated to true for every point in the measurement.

**Comment by beckettsean** [comment]
See also https://github.com/influxdb/influxdb/issues/4276

**Comment by beckettsean** [comment]
Might be related somehow to this generic `WHERE field =` bug: https://github.com/influxdb/influxdb/issues/4306
