### ISSUE TITLE
HH Throws error even if disabled

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#4283]
If you disable (or remove) the HH config, the service won't start and gives this error:

```
run: HintedHandoff.Dir must be specified. To generate a valid configuration file run `influxd config > influxdb.generated.conf`.
```

It should not be requiring a directory for a service that is disabled.

**Comment by jwilder** [comment]
https://github.com/influxdb/influxdb/blob/master/cmd/influxd/run/config.go#L107

**Comment by corylanou** [comment]
We probably need to change it to:

```go
 else if c.HintedHandoff.Dir == "" && c.HintedHandoff.Enabled
```

**Comment by otoolep** [comment]
I took a quick look at this code. I agree there doesn't seem to be a better way.

**Comment by otoolep** [comment]
Hmm, but the issue is HH is on by default, so it easy as that.

**Comment by otoolep** [comment]
Anyone familiar with toml processing -- or can just check out the code -- may be able to solve this issue. It's easy to reproduce -- simply pass a config file to `influxd` that does not contain any HH section.

**Comment by ch33hau** [comment]
Hi @otoolep , I have created a pull request for this issue, the way to fix is like @corylanou 's comment.
And one more thing is, since the Dir value is mandatory, so I disable HH by default, hope it make sense.

**Comment by otoolep** [comment]
All done!
