### ISSUE TITLE
[0.9.5-nightly-b079d20] udp memory leak?

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4285]
```
/usr/local/go/bin/go tool pprof -svg -output heap.svg /opt/influxdb/influxd http://localhost:8086/debug/pprof/heap
```
http://imgh.us/heap_1.svg

< 5gb of data (mostly aggregated and last hour or raw ingested data), server eventually crashes. memory usage was after about 24 hours of uptime. doing 4-800 events a second, up to 20 tags + 20 data points at the largest (most active) event

**Comment by parisholley** [comment]
currently testing code changes that creates a single buffer array in udp/service.go and clears it at the end of every batch. suppose it will be trial and error to figure out what in that block is preventing garbage collection. will keep trying different ideas. currently takes about 12 hours before OOM happens.

**Comment by parisholley** [comment]
i setup an hourly cron to do heap dumps, so hopefully it will provide some additional insight as the above svg isn't very helpful on its own

**Comment by parisholley** [comment]
appears the udp service is fine, it is the underlying storage layer. here are a few lines that i've dug through in pprof that show high usage:

```
points_writer.go: w.TSDBStore.WriteToShard(shardID, points)
models/points.go: tags[string(unescapeTag(key))] = string(unescapeTag(value))
shard.go: seriesToCreate, fieldsToCreate, seriesToAddShardTo, err := s.validateSeriesAndFields(points)
share.go: series := NewSeries(string(p.Key()), p.Tags())
store.go: return sh.WritePoints(points)
```
that last line in that list has the highest cumulative usage across the app.

http://www.speedyshare.com/MnYK9/78170f9f/download/heap

**Comment by otoolep** [comment]
@parisholley -- we aware of issues in the current storage engine and currently working on a new one which should be available for early testing very soon. It will replace the current engine. Track this issue to know when it is available: https://github.com/influxdb/influxdb/issues/4086

**Comment by parisholley** [comment]
latest dump shows issues back in udp service

```
27.94GB    27.94GB    132:		buf := make([]byte, UDPBufferSize)
```

after awhile, go isn't GC'ing the buffer? in every other service, the buffer is created once outside the for loop. I tried creating it once then emptying each time, but that didn't work (events didn't write). I'm not sure this may be a storage engine issue (not unless there is some reference in that layer keeping the buffers alive)

http://speedy.sh/awFJb/dump

**Comment by otoolep** [comment]
@parisholley -- I think you might be right, that code could be improved by moving the buffer-creation to outside the loop.

https://github.com/influxdb/influxdb/blob/master/services/udp/service.go#L131

@corylanou -- what do you think?

**Comment by otoolep** [comment]
@parisholley -- can we see the patch you applied, that didn't work for you?

**Comment by parisholley** [comment]
@otoolep @corylanou I just tried that (just moving buf to outside loop), but I get errors like this:

```
panic: unable to parse bool value 'CN': strconv.ParseBool: parsing "CN": invalid syntax


goroutine 94 [running]:
github.com/influxdb/influxdb/models.newFieldsFromBinary(0xc83c05203c, 0x44, 0xffc4, 0xc82d1bc540)
	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/models/points.go:1233 +0xa0b
```

it appears that data is bleeding over when it is not cleared out. i tried something like this earlier in the loop, but then events stopped writing

```
buf = buf[:0]
```

**Comment by parisholley** [comment]
when i print the point before
```
s.batcher.In() <- point
```
everything looks sane. it is almost like it is incorrectly parsing the line thinking that the tags are fields

**Comment by parisholley** [comment]
still digging, but i think my theory is right. when i change the panic message to output the full buffer, I see this:

```
panic: unable to parse country=US,region=CO,firstVisit=FALSE,device=desktop requestType=
```

so it is missing the measurement, and is including the tail of the fields

**Comment by parisholley** [comment]
@otoolep @corylanou think i got it!

so looks the problem came down to the use of slices. when I moved the buffer out of the loop, the modesl/point was making slices of the data when parsing. problem is those slices share the same memory, so when the next batch of UDP events came in, it would overwrite the old data before it was flushed out. 

so my changes included moving the buffer to outside the for loop, then updating models/point to copy the data into a new array (which is isolated), vs. using slices.

```
        keyBuf := make([]byte, len(key))
        fieldsBuf := make([]byte, len(fields))
        tsBuf := make([]byte, len(ts))
        copy(keyBuf[:], key)
        copy(fieldsBuf[:], fields)
        copy(tsBuf[:], ts)

        pt := &point{
                key:    keyBuf,
                fields: fieldsBuf,
                ts:     tsBuf,
        }
```

will need to let this run a bit to see if there is an improvement.

**Comment by parisholley** [comment]
checking after it ran all night, it is still alive! memory levels are about the same as when I launched the instance. what is interesting, is that the points are failing to write now, and that may have been what caused the udp service to build up a ton of memory. all I get is "failed to write point batch to database" for  the udp stream as well as the background monitoring statistics, but that will be a separate issue to track down.

**Comment by parisholley** [comment]
created issues #4301 for the write issues. since running with these code changes (and switching back to bz1 engine), i am now running at < 6GB of memory (huge improvement).

let me know if you would like me to issue a pull.

**Comment by parisholley** [comment]
closing this as i am pretty sure that the leak previously was related to the write timeouts and in memory build up. with the new storage engine, other areas are of more concern when it comes to memory usage.

**Comment by otoolep** [comment]
There is no leak in the UDP code. I applied the simple patch below and sent 1000 packets/sec into the UDP input:
```
diff --git a/services/udp/service.go b/services/udp/service.go
index 6ff536e..57f5568 100644
--- a/services/udp/service.go
+++ b/services/udp/service.go
@@ -104,6 +104,7 @@ func (s *Service) writePoints() {
        for {
                select {
                case batch := <-s.batcher.Out():
+                       continue
                        if err := s.PointsWriter.WritePoints(&cluster.WritePointsRequest{
                                Database:         s.config.Database,
                                RetentionPolicy:  s.config.RetentionPolicy,
```
This means the system performs all UDP processing, except actually writing to the database. InfluxDB's internal metrics shows that Go heap usage remains steady.

```
> SHOW STATS FOR 'udp'
name: udp
tags: bind=:2003
bytes_rx        points_rx
--------        ---------
10050600        428000
```
![udpgc](https://cloud.githubusercontent.com/assets/536312/10377880/9be6d58e-6dba-11e5-9199-294e0b27cdc9.png)

**Comment by parisholley** [comment]
@otoolep it probably isn't going to be easy to reproduce until the GC is put under heavy load. when I dug into the prof tool (I believe i have uploaded the file above so you can analyze manually), it was a clear indicator that the buffer was using a ton of heap.

**Comment by otoolep** [comment]
Sure @parisholley -- I just want to differentiate between inefficient use of memory (which this code may well be guilty of) versus that memory being leaked.

I do think continually re-allocating a 64K buffer (assuming that is what is happening underneath) could probably be avoided.
