### ISSUE TITLE
[0.9.4.2] Problems writing very large values

### ISSUE THREAD

**Issue by paulstuart** [influxdb/influxdb#4295]
A fresh install and it's writing other metrics (using https://github.com/paulstuart/influxsnmp).

I'm seeing the following error repeatedly:

unable to parse 'ifHCInUcastPkts,column=bme0,host=10.101.2.12 value= 1443745777758753664': missing field value

The space after "value=" looks like it's causing the problem (I'm using client.Point to create the data).

**Comment by beckettsean** [comment]
@paulstuart the space is certainly not [proper syntax](https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html). I don't understand what that has to do with the size of the integer, though. 

Without the space the insert works fine:

```
> insert ifHCInUcastPkts,column=bme0,host=10.101.2.12 value=1443745777758753664
> select * from /if/
name: ifHCInUcastPkts
---------------------
time				column	host		value
2015-10-02T17:16:09.746774118Z	bme0	10.101.2.12	1.4437457777587538e+18
```

**Comment by paulstuart** [comment]
I found the problem: the value client.Point was nil. It generates random numbers from that, and also aborts the remainder of the batch write.

I've fixed my code to skip sending nil values, but the client should also deal with them appropriately.

**Comment by beckettsean** [comment]
@paulstuart can you open a new issue regarding the Client handling `nil` more gracefully?

**Comment by paulstuart** [comment]
Done. #4307
