### ISSUE TITLE
[master] points writer not timing out?

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4301]
while understanding the storage engine may change, if boltdb is still used under the hood, this may be useful. I am currently seeing write timeouts and also unable to query the data. When looking at "pprof/goroutine" this stands out:

```
50 @ 0x430e23 0x430ee4 0x440737 0x440386 0x4fceb4 0x7a48e5 0x7a44f4 0x7a4f56 0x82ad69 0x60c2b3 0x619107 0x636c48 0x461ff1
#	0x440386	sync.runtime_Semacquire+0x26							/root/.gvm/gos/go1.5/src/runtime/sema.go:43
#	0x4fceb4	sync.(*Mutex).Lock+0x1c4							/root/.gvm/gos/go1.5/src/sync/mutex.go:82
#	0x7a48e5	github.com/boltdb/bolt.(*DB).beginRWTx+0x85					/root/.gvm/pkgsets/go1.5/global/src/github.com/boltdb/bolt/db.go:464
#	0x7a44f4	github.com/boltdb/bolt.(*DB).Begin+0x34						/root/.gvm/pkgsets/go1.5/global/src/github.com/boltdb/bolt/db.go:413
#	0x7a4f56	github.com/boltdb/bolt.(*DB).Update+0x36					/root/.gvm/pkgsets/go1.5/global/src/github.com/boltdb/bolt/db.go:531
#	0x82ad69	github.com/influxdb/influxdb/tsdb/engine/b1.(*Engine).WritePoints+0xa9		/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/engine/b1/b1.go:212
#	0x60c2b3	github.com/influxdb/influxdb/tsdb.(*Shard).WritePoints+0x633			/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/shard.go:256
#	0x619107	github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard+0xf7			/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/store.go:340
#	0x636c48	github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1+0x108	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/cluster/points_writer.go:274

1834 @ 0x430e23 0x430ee4 0x440737 0x440386 0x4fdd68 0x61904c 0x636c48 0x461ff1
#	0x440386	sync.runtime_Semacquire+0x26							/root/.gvm/gos/go1.5/src/runtime/sema.go:43
#	0x4fdd68	sync.(*RWMutex).RLock+0x58							/root/.gvm/gos/go1.5/src/sync/rwmutex.go:36
#	0x61904c	github.com/influxdb/influxdb/tsdb.(*Store).WriteToShard+0x3c			/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/tsdb/store.go:333
#	0x636c48	github.com/influxdb/influxdb/cluster.(*PointsWriter).writeToShard.func1+0x108	/root/.gvm/pkgsets/go1.5/global/src/github.com/influxdb/influxdb/cluster/points_writer.go:274
```

at some point, it appears that a transaction is causing the shard to lock and then blocks everything moving foward

**Comment by parisholley** [comment]
this happened while running the b1 engine, switched back to bz1 to see what happens with that. stay tuned.

**Comment by otoolep** [comment]
FWIW, the new engine does not use Bolt, so this issue may soon be moot.

Thanks for the report however @parisholley

**Comment by parisholley** [comment]
@otoolep alright. just as an update, bz1 also locks up. it may be important that for new engine, that even if writes/reads are separated, there should be timeouts on the locking mechanism when writing to WAL/database.

**Comment by parisholley** [comment]
if I am reading this block file correctly, excluding the long running goroutines that operate in the background, it appears points_writer is not timing out correctly:

http://mantis-test.s3.amazonaws.com/block.txt

cluster/points_writer.go:313

don't know much about the go syntax/sync logic to come to any conclusion as to what could be happening.

**Comment by parisholley** [comment]
taking a second look, if the write is failing, it looks like it will try to go into the hinted handoff process (which is currently in the top of the block list). going to restart with it disabled and see what happens. I am in a single node setup.

**Comment by parisholley** [comment]
with HH out of the picture, still see hangs. going to try to disable the monitor service now. it appears that the code within that service has no timeout mechanism at all?

**Comment by parisholley** [comment]
after tons more tracing/printf'ing, I think I am much closer to the problem. it appears my problem may be when two flushes happen at the tie same time. in the example below, there is a huge flush that happens first because the memory gets full, then while it takes some time to write, another flush happens because it was idle. it appears the problem is around acquiring a lock in WAL.

adding a bit more logging in the mix to confirm if that is the issue, and if so, may test out adding a mutex in that process to prevent flushes from happening at the same time.

```
[write] 2015/10/03 05:59:55 Maybe Written
[write] 2015/10/03 05:59:55 result
[continuous_querier] 2015/10/03 05:59:55 wrote 1 point(s) to mantis.minutes
[continuous_querier] 2015/10/03 05:59:55 Execute query
[continuous_querier] 2015/10/03 05:59:55 Read query results
[query] 2015/10/03 05:59:55 SELECT mean(rate), max(rate) INTO "mantis"."minutes".agg_cpc_rate FROM "mantis"."default".api_website_winbid WHERE rateType = 'cpc' AND rate > 0.000 AND time >= '2015-10-03T05:58:00Z' AND time < '2015-10-03T05:59:00Z' GROUP BY time(1m)
[wal] 2015/10/03 05:59:55 Flush due to memory. Flushing 14393 series with 100918 points and 21015197 bytes from partition 1
[write] 2015/10/03 05:59:56 start writeToShart
[write] 2015/10/03 05:59:56 async channels
[write] 2015/10/03 05:59:56 pre range
[write] 2015/10/03 05:59:56 loop
[write] 2015/10/03 05:59:56 exec
[write] 2015/10/03 05:59:56 WriteToShard, %!s(int=575)
[store] 2015/10/03 05:59:56 asking for lock
[store] 2015/10/03 05:59:56 git lock
[store] 2015/10/03 05:59:56 writing points
[store] 2015/10/03 05:59:56 locking index
[store] 2015/10/03 05:59:56 got lock
[store] 2015/10/03 05:59:56 unlocked
[store] 2015/10/03 05:59:56 locking index
[store] 2015/10/03 05:59:56 unlocked
[store] 2015/10/03 05:59:56 range loop
[store] 2015/10/03 05:59:56 range loop done
[store] 2015/10/03 05:59:56 sending writes to engine
[wal] 2015/10/03 05:59:56 write series and fields to wal
[wal] 2015/10/03 05:59:56 get WAL logger lock
[wal] 2015/10/03 06:00:00 Flush due to idle. Flushing 2 series with 4 points and 77 bytes from partition 1
[wal] 2015/10/03 06:00:00 write to index of partition 1 took 2.926115ms
[write] 2015/10/03 06:00:01 timeout
[udp] 2015/10/03 06:00:01 failed to write point batch to database "mantis": timeout
[write] 2015/10/03 06:00:01 start writeToShart
[write] 2015/10/03 06:00:01 async channels
[write] 2015/10/03 06:00:01 pre range
[write] 2015/10/03 06:00:01 loop
[write] 2015/10/03 06:00:01 exec
[write] 2015/10/03 06:00:01 WriteToShard, %!s(int=367)
[store] 2015/10/03 06:00:01 asking for lock
[store] 2015/10/03 06:00:01 git lock
[store] 2015/10/03 06:00:01 writing points
[store] 2015/10/03 06:00:01 locking index
[store] 2015/10/03 06:00:01 got lock
[store] 2015/10/03 06:00:01 unlocked
[store] 2015/10/03 06:00:01 locking index
[store] 2015/10/03 06:00:01 unlocked
[store] 2015/10/03 06:00:01 range loop
[store] 2015/10/03 06:00:01 range loop done
[store] 2015/10/03 06:00:01 sending writes to engine
[wal] 2015/10/03 06:00:01 write series and fields to wal
[wal] 2015/10/03 06:00:01 get WAL logger lock
[write] 2015/10/03 06:00:06 timeout
[udp] 2015/10/03 06:00:06 failed to write point batch to database "mantis": timeout
```

**Comment by parisholley** [comment]
as an update, i made some modifications to WAL, in particular i created a mutex just for handling the access to the meta file instead of locking the entire WAL. i also removed some locks that were on the WAL level when calls were just delegating to the partition (which handles its own locks).

also put a lock on the partition around the WriteIndex within flushAndCompact(), as I think once you go into there, it is straight access to Bolt, which may have been causing some issues.

so far, the server has been running for 30 minutes (i've been able to get it to lockup much quicker). *knock on wood*, hopefully these tweaks will be the solution. If the instance remains up for a few hours, I will put all my changes in a pull request.

**Comment by parisholley** [comment]
didn't help too much. while it did open up the ability for multiple retention policies to work (because I locked per partition instead of on the entire WAL), the underlying problem is WriteToIndex at some point just doesn't return. Flushes (due to memory) happened without issue at similar sizes for a period of time, then randomly it just doesn't work (which locks that partition and prevents anything from continuing). I've added some more logging so will continue to look into it.

**I am determined!**

**Comment by parisholley** [comment]
looks like it all boils down to an issue with boltdb. once the call to bz1.WriteIndex is made, it is able to get through iterating all the data points with no issue, the problem then becomes e.db.Update(), it is just waiting forever for the transaction to return. it could be interesting to dig into the boltDb batch API, and try breaking up the flushes, but seems like it would be a waste.

at this point, probably safe to assume that the 0.9x branch will be unusable. my last test will be to just decrease the memory flush size to as small a batch as possible to eliminate the amount of data being written in a single boltdb transaction. that, in combination with the memory fix may be a plausible work around until the new storage engine is ready.

**Comment by cannium** [comment]
@parisholley Could you provide some recent updates? I'm digging a similar problem, but the hanging seems only happen at the creation of a new db file

**Comment by parisholley** [comment]
@cannium i've moved on from influx, but my only solution was to upgrade to the latest storage engine.
