### ISSUE TITLE
[0.9.4.1] query leading to crash

### ISSUE THREAD

**Issue by abolinhas** [influxdb/influxdb#4309]
Hi,
I'm collecting all my users internet activity into my Influx database,I have already stored thousands / millions of points. Now I want query through Web Admin Interface all users activity on specific month, I use this query
SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') but when I execute the query the Influx crash and the server load increases a lot.
My question is, this query is correct? Is there any way to optimize the query in order to reduce the load but returning the same data?

I use influx 0.9.4.1
Server spec: 8 CPU, 8 GB Ram

**Comment by parisholley** [comment]
Would suggest you create a continuous query to down sample the data. Querying raw ingested information is always going to be slow.

**Comment by abolinhas** [comment]
Thanks @parisholley 
Continuous query will not increase the server load and cpu usage?
I read the documentation available on Influx web site, but is not very explicit...
In my case I want to build my own stats application in php, in this app I have a lot of search criteria like by user(s), date(s), website(s), ip(s)... how can I implement  continuous query on my app?
For example to this criteria
SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') 
Best regards

**Comment by parisholley** [comment]
it probably will, but shouldn't be noticeable. i can't help you much with modeling (influx offers developer support if you need it), but you will see good performance if you expect to query adhoc (or have fields with tons of unique values like user ip). recommend grouping by fields with low cardinality in small intervals (ie: 5m) within a continuous  query.

**Comment by dtouzeau** [comment]
Hi paris, has you seen there are some x and y date start and date end that cannot make it Continuous. Understand that some tweaks can improve the query results, but did not understand the "crash"

**Comment by abolinhas** [comment]
Group by don't work on my query....
SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00')  group by time (1h)
ERR: error parsing query. GROUP BY requires at least one aggregate function.

I also try 
SELECT USER, SUM(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') GROUP BY time(1h)
But I get this error
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported

This query work
SELECT sum(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') group by time(1h)
Thin query return  75799 records but the load increase from 0.10 to 4

**Comment by dtouzeau** [comment]
Load from 0.10 to 4 for 75000 records, incredible !!! MySQL do better

**Comment by abolinhas** [comment]
Anyone can help about this issue?

**Comment by beckettsean** [comment]
@abolinhas what is the result of `SELECT COUNT(user) AS count_user, COUNT(size) AS count_size FROM  access_log WHERE time > '2015-08-01 00:00:00' and time < '2015-08-31 23:59:00'`

**Comment by beckettsean** [comment]
> Load from 0.10 to 4 for 75000 records, incredible !!! MySQL do better

@dtouzeau, Your understanding is very inaccurate. InfluxDB returned 75000 values, one for each one hour bucket, but the query still requires every point to be pulled off disk for the SUM statement.

**Comment by abolinhas** [comment]
@beckettsean 
> SELECT COUNT(RQS) AS count_rqs, COUNT(SIZE) AS count_size FROM access_log WHERE time > '2015-08-01 00:00:00' and time < '2015-08-31 23:59:00'
name: access_log
----------------
time                            count_rqs       count_size
2015-08-01T00:00:00.000000001Z  75799           75799

Load stable

**Comment by beckettsean** [comment]
@abolinhas Can you include the output from `SHOW FIELD KEYS FROM access_log`

@dtouzeau my apologies, it does seem that there are only 75k points in this time range. That makes the query performance odd, since that entire set should take very little time. On my machine I can make 1 hour buckets of 375k points over the same time range and it returns in 1.13 seconds with a small spike in usage.

**Comment by beckettsean** [comment]
@abolinhas what was the stack trace when you run `SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00')` and the server crashes?

**Comment by abolinhas** [comment]
@beckettsean 
> SHOW FIELD KEYS FROM access_log
name: access_log
----------------
fieldKey
RQS
SIZE
ZDATE

> SHOW TAG KEYS FROM access_log
name: access_log
----------------
tagKey
CATEGORY
FAMILYSITE
IPADDR
MAC
SITE
USERID
proxyname

Yes the server crash, a good example.
> SELECT COUNT(SIZE) as count_size FROM access_log WHERE (time >'2015-09-01 00:00:00' and time < '2015-10-06 23:59:00')
name: access_log
----------------
time                            count_size
2015-09-01T00:00:00.000000001Z  4.413682e+06


SELECT USERID,SIZE FROM access_log WHERE (time >'2015-09-01 00:00:00' and time < '2015-10-06 23:59:00')
ERR: Get http://10.95.254.99:8086/query?db=proxydb&q=SELECT+USERID%2CSIZE+FROM+access_log+WHERE+%28time+%3E%272015-09-01+00%3A00%3A00%27+and+time+%3C+%272015-10                                                                                                                                                             -06+23%3A59%3A00%27%29: net/http: transport closed before response was received
>
Broadcast message from root@stats-appliance (Tue Oct  6 08:22:36 2015):

The system is going down for reboot NOW!

When I run the query Influx will use about 200% of CPU and 98% of ram (7GB)

**Comment by abolinhas** [comment]
The same issue happens in others servers...

**Comment by beckettsean** [comment]
@abolinhas can you include the log file with about 10 lines before the crash and the full panic stack trace, assuming there is one? It looks like an OOM killer is forcing a reboot, but we need to see what the query logs show. Should be in `var/log/influxdb/influxdb.log`

**Comment by beckettsean** [comment]
@abolinhas looking at the counts, that query set is selecting a tag and a field from about 4.4 million points at the same time. That's a fairly large set. A similar query of 500k values took 3.9 seconds and about 1GB of RAM to return on my machine. Scale that up by a factor of 9 and it does exceed your available RAM.

Why do you need to return all the values for each point in a single query? Can you use CQs to downsample in advance? Can you narrow your time range?

**Comment by abolinhas** [comment]
@beckettsean 
Error after 15 min from query execution (this time the server don't reboot):
> SELECT USERID,SIZE FROM access_log WHERE (time >'2015-09-01 00:00:00' and time < '2015-10-06 23:59:00')
ERR: Get http://10.95.254.99:8086/query?db=proxydb&q=SELECT+USERID%2CSIZE+FROM+access_log+WHERE+%28time+%3E%272015-09-01+00%3A00%3A00%27+and+time+%3C+%272015-10-06+23%3A59%3A00%27%29: EOF
>
Memory usage: 99% gives the fatal error: runtime: out of memory

The log is too long to post here, you can find it in this link
https://docs.google.com/document/d/1mkmPRk71rFtv04q9bQFV2TeqAcVfRw7YnWz7Ej3MBq8/edit?pli=1

**Comment by dtouzeau** [comment]
"Why do you need to return all the values for each point in a single query? Can you use CQs to downsample in advance? Can you narrow your time range?"

Because the GROUP BY is not really supported.. So we need to dump all rows, import them into MySQL in order to use the GROUP BY and other features

**Comment by beckettsean** [comment]
@dtouzeau 

> Because the GROUP BY is not really supported.

Can you elaborate on what more it needs to do? Is this related to GROUP BY fields or something?

> Can you narrow your time range?

If this is just an ETL into MySQL, why grab 4 million points at once? Why not 500k points at a time so the query doesn't OOM?

**Comment by abolinhas** [comment]
@beckettsean 

|Can you elaborate on what more it needs to do? Is this related to GROUP BY fields or something?

Yes group by don't work with tags....

Group by don't work on my query....
SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') group by time (1h)
ERR: error parsing query. GROUP BY requires at least one aggregate function.

I also try
SELECT USER, SUM(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') GROUP BY time(1h)
But I get this error
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported

This query work
SELECT sum(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') group by time(1h)
This query return 75799 records but the load increase from 0.10 to 4

**Comment by beckettsean** [comment]
`SELECT USER,SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') group by time (1h)` 

The error has nothing to do with tags. You're asking for the raw points, but grouped by hour. What does that even mean? Remove the `group by time (1h)` from that query and it will run just fine.

`SELECT USER, SUM(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') GROUP BY time(1h)`

This query is nonsense. You're asking for a 1 hour SUM for the SIZE, but you want to return USER for every point? How does that even work? What output are you expecting?

Maybe this is what you want instead, which is `GROUP BY` on tags, the feature you are describing but not actually using:

SELECT SUM(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') GROUP BY time(1h), USER`

> Also it is possible convert tags to fields?

No. That is fundamentally impossible in InfluxDB

**Comment by beckettsean** [comment]
This issue appears to be a combination of requesting too many points at once for the available RAM, and not understanding the syntax of the query language. Closing

**Comment by abolinhas** [comment]
@beckettsean 
We need to return each user with the sum of download size SUM(SIZE) and group by time 1h, what the best way?
Select userid, sum(size) as size from... 
don't work
and select userid, size from... group by time (1h)
don't work too.

In mysql I can do this opereation, in Influx what is the best way?

**Comment by beckettsean** [comment]
@abolinhas I gave that syntax in my previous comment:

`SELECT SUM(SIZE) as SIZE FROM access_log WHERE (time >'2015-08-01 00:00:00' and time < '2015-08-31 23:59:00') GROUP BY time(1h), USER`

**Comment by abolinhas** [comment]
@beckettsean 
Sorry I don't read your last comment, thanks this query works as expect. Load increase only 1.5 more and ram about 2GB.
One last question, the query return this
name: access_log
tags: USERID=wilson.santos
time                    SIZE
----                    ----
2015-10-01T00:00:00Z
2015-10-01T01:00:00Z
2015-10-01T02:00:00Z
2015-10-01T03:00:00Z
2015-10-01T04:00:00Z
2015-10-01T05:00:00Z
2015-10-01T06:00:00Z
2015-10-01T07:00:00Z
2015-10-01T08:00:00Z
2015-10-01T09:00:00Z
2015-10-01T10:00:00Z
2015-10-01T11:00:00Z
2015-10-01T12:00:00Z
2015-10-01T13:00:00Z
2015-10-01T14:00:00Z    59503
2015-10-01T15:00:00Z    68860
2015-10-01T16:00:00Z
2015-10-01T17:00:00Z    316238
2015-10-01T18:00:00Z
2015-10-01T19:00:00Z    4110
2015-10-01T20:00:00Z    5396
2015-10-01T21:00:00Z    1646
2015-10-01T22:00:00Z
2015-10-01T23:00:00Z

It is possible show only results where SIZE has a value?

**Comment by abolinhas** [comment]
@beckettsean 
I found a way to avoid none values by using the fill() in the query
SELECT SUM(SIZE) as SIZE1 FROM access_log WHERE (time >'2015-09-01 00:00:00' and time < '2015-09-31 23:59:00') GROUP BY time(1h) , USERID fill(none)
