### ISSUE TITLE
[0.8.8] Not able to create retention policy on db using command line interface

### ISSUE THREAD

**Issue by shaileshswapnil** [influxdb/influxdb#4322]
Hi All,

I have been trying long to create db with retention policy from the command line using CURL command interface. But instead it is creating just the db. And when I am trying to see the config file, the db created is not showing up.

Is there any possible way or option available to create db with retention policy, when using with CURL interface?

InfluxDB: 0.8.8
OS: Centos 6.6

**Comment by beckettsean** [comment]
0.8 requires many administrative actions happen in the Admin UI, including database creation. See  https://influxdb.com/docs/v0.8/introduction/getting_started.html for more.
