### ISSUE TITLE
Feature Request: "CREATE DATABASE metrics IF NOT EXISTS"

### ISSUE THREAD

**Issue by leehambley** [influxdb/influxdb#4323]
We're provisioning (in some of our environments) influxdb using Puppet, that means creating databases and users, etc. It would help a lot if we could conditionally create databases, rather than listing, grep'ing, and trying to guess if the database already exists on subsequent Puppet runs to avoid errors such as:

```
==> e2e: Error: /opt/influxdb/influx -execute "CREATE DATABASE metrics"
         returned 1 instead of one of [0] 
==> e2e: Error: /Stage[main]/Influxdb/Exec[/opt/influxdb/influx -execute
         "CREATE DATABASE metrics"]/returns: change from notrun to 0 failed:
         /opt/influxdb/influx -execute "CREATE DATABASE metrics" returned 1 instead of
         one of [0]
```

**Comment by corylanou** [comment]
Support for this was added in `0.9.4` #3892 

Syntax is: 

`CREATE DATABASE IF NOT EXISTS metrics`

**Comment by leehambley** [comment]
Thanks Cory, documentation is then out of date, thanks.

**Comment by corylanou** [comment]
I added a ticket to have the documentation updated as well.  Thanks! https://github.com/influxdb/influxdb.com/issues/360

**Comment by gdmello** [comment]
For anyone coming here first, the syntax has [changed](https://github.com/influxdata/influxdb-java/commit/8511af1855f291093d18f8037017a0d39f1f90a0#diff-23360835991a654afd56314b41590521R200) to-
`CREATE DATABASE <dbname>` for version > 1.0
