### ISSUE TITLE
TestParser_ParseExpr fails on Go tip

### ISSUE THREAD

**Issue by kostya-sh** [influxdb/influxdb#4341]
go test -run TestParser_ParseExpr

    --- FAIL: TestParser_ParseExpr (0.00s)
    	parser_test.go:1858: 7. "'2000-01-32 00:00:00'": error mismatch:
    		  exp=unable to parse datetime at line 1, char 1
    		  got=%!s(<nil>)
    		
    	parser_test.go:1858: 9. "'2000-01-99'": error mismatch:
    		  exp=unable to parse date at line 1, char 1
    		  got=%!s(<nil>)
		
FAIL
exit status 1
FAIL	github.com/influxdb/influxdb/influxql	0.006s

This is due to https://github.com/golang/go/commit/8b96be15f6632b33c7341840002bc5b0744b2977

**Comment by otoolep** [comment]
This is marked as "difficult" since it involves building the latest Go tool chain. 

We need to help determining if this test case is no longer valid, or if there is a different string we can use within this test case.

**Comment by otoolep** [comment]
This file in question is `influxql/parser_test.go`.

**Comment by kostya-sh** [comment]
Starting from Go 1.6 time.Parse will not return an error when parsing a date where date component is greater than 31. (e.g. 36 Jan 2015).

The test checks that influxdb doesn't accept invalid dates. Due to the choice of date strings it passes with Go 1.5. However the validation is still not correctly implemented for dates like 30 Feb, 29 of Feb on non-leap year, 31 Nov, etc.

Depending on the desired influxdb behaviour there are two different ways to fix this issue.

If you decide to reject invalid dates then the parser should validate number of days depending on date's month and year. Relying on time.Parse error checking is not enough.

If you decide to ignore invalid dates then the test should be removed.

**Comment by e-dard** [comment]
@otoolep I started taking a look at this, but the solution depends on the expected behaviour when parsing date(times).

Given the input `2000-01-32` Go 1.6 will parse that as a `time.Time` equivalent to `2000-02-01`. There will be no error returned (hence the failing test case).

So should influx allow this to happen or is it important that the input is a valid date prior to it being parsed (and therefore `2000-01-32` _should_ be a parse error.

Given an answer to this question I could put a fix in for this.

**Comment by otoolep** [comment]
It seems to me the test is just about checking that the system catches parse errors when they happen. If this string is no longer a parse error, then perhaps the test is no longer valid and should just be removed? (When we move to Go 1.6).

Any comment @dgnorton ?

**Comment by kostya-sh** [comment]
This is no longer an issue. See https://github.com/golang/go/commit/5ef899111e581b1e57aa1546caa204d48bdf5503 for more details.

**Comment by otoolep** [comment]
Thanks very much for the update, @kostya-sh
