### ISSUE TITLE
Expose Client Precision value

### ISSUE THREAD

**Issue by nathanielc** [influxdb/influxdb#4344]
As it stands now when writing `BatchPoints` the `precision` does not default to the client's precision. See https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L226

Would it make sense to default `bp.precision` if empty to `c.precision`? Might be a breaking change in some cases :( Or we could just add a `Client.Precision()` method to return the precision and then use that when creating the `BatchPoints` object.

Thoughts?

**Comment by otoolep** [comment]
cc @sparrc 

Cameron was in this code recently, there was significant resistance to breaking changes here.

**Comment by sparrc** [comment]
This is slightly different than what I was looking at, this doesn't seem like it would be a very breaking change. Unless someone was setting their client's `precision` to something other than `ns` and _expecting_ it not to get applied?

**Comment by nathanielc** [comment]
@sparrc If you thinks it not a big change then I say we just default it. See https://github.com/influxdb/influxdb/issues/4361

**Comment by nathanielc** [comment]
closed by #4361
