### ISSUE TITLE
[pd-storage-engine] memory leak or data set growth?

### ISSUE THREAD

**Issue by parisholley** [influxdb/influxdb#4350]
Here are two SVGs take about an hour apart, one with about ~4GB of usage, the other with around ~8GB.

http://imgh.us/heap_3.svg (Lower Usage)
http://imgh.us/heap_high.svg (Higher Usage)

Assuming that the number of unique series rises over time due to tags, does this seem normal? Ingestion has been at a steady rate.

**Comment by parisholley** [comment]
As an update, it appears it may just be normal. New storage engine has been rock solid at 21 hours now, and currently less than 6GB of usage.

**Comment by jwilder** [comment]
If number of unique series rises over time, it will cause the in-memory index size to increase as well.  You'll need to size the available RAM on your hosts to account for the number of series you are likely to store.
