### ISSUE TITLE
Add regex filtering for SHOW MEASUREMENTS

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#4351]
To help Grafana users make the transition from 0.8 to 0.9, we need to add the ability to filter measurement names based on a regex. Syntax should look like:

```
SHOW MEASUREMENTS WHERE name =~ /.*some regex.*/
```

**Comment by dgnorton** [comment]
Would this be better or worse?
```
SHOW MEASUREMENTS FROM /.*some regex.*/
```

**Comment by beckettsean** [comment]
closing as duplicate of https://github.com/influxdb/influxdb/issues/3523

**Comment by beckettsean** [comment]
And for the record, I prefer Paul's syntax as it matches the other SHOW queries. In them `FROM` refers to the database or the measurement, not the where conditions.

**Comment by dgnorton** [comment]
The problem with `WHERE name...` is that `name` can no longer be used as a tag key.

**Comment by beckettsean** [comment]
@dgnorton that's a very good point. 

What about `SHOW MEASUREMENTS WHERE MEASUREMENT =~ /.../`?

**Comment by kostya-sh** [comment]
How about `SHOW MEASUREMENTS LIKE /.../`?
