### ISSUE TITLE
Write timeout on InfluxDb influxdb-0.9.4.2-1

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#4355]
I was trying to do performance testing on influxdb-0.9.4.2-1 using wrk2 tool. I wrote a lua script and using below wrk command to send write request.

    test.lua
    =========
    wrk.method = "POST"
    wrk.body   = "cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000"
    wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"

    wrk command
    ============
    ./wrk -s /tmp/test.lua -t2 -c40 -d30s -R2000 --timeout 15 http://localhost:8086/write?db=demo_db

My observation is that I am receiving 500 error resp (write timeout) if I increase number of connections (-c). Default write timeout in config file is 5s. I have increased write timeout to 15s. Then I was able to survive for sometime, but if I increase number of connections then write time also getting increased on DB and getting more 500 error resp. 

Any advice how to get rid of this error. I want to reach 2k to 3k req/sec.

**Comment by jwilder** [comment]
#4308 is in the latest nightly and should address this issue.  The `tsm1` engine is not enabled by default though so you need to enable it in your config. See: https://influxdb.com/docs/v0.9/introduction/tsm_installation.html
