### ISSUE TITLE
CQ: Aggregation grouping by tagging - Not working

### ISSUE THREAD

**Issue by syepes** [influxdb/influxdb#4356]
Hello,

Just upgraded to the last master verison #fb83158 to test drive the new SE: tsm1, and I have just noticed the following issue:

I can no longer create a CQ using the grouping by tagging 'server' feature:

Does no longer works:
```
CREATE CONTINUOUS QUERY cpu_coreUtilization_average_percent_1h ON ESXi BEGIN
SELECT MAX(value)/100 as MAX, MIN(value)/100 as MIN INTO cpu_coreUtilization_average_percent_1h FROM "raw"."cpu_coreUtilization_average-percent" WHERE instance = 'avg' GROUP BY time(1h), server
END
```
```
ERR: error parsing query: found SERVER, expected identifier, string, number, bool at line 1, char 265
```

This works:
```
CREATE CONTINUOUS QUERY cpu_coreUtilization_average_percent_1h ON ESXi BEGIN
SELECT MAX(value)/100 as MAX, MIN(value)/100 as MIN INTO cpu_coreUtilization_average_percent_1h FROM "raw"."cpu_coreUtilization_average-percent" WHERE instance = 'avg' GROUP BY time(1h), *
END
```

**Comment by KiNgMaR** [comment]
You have to quote `server`, i.e. `"server"`. It appears to be a reserved word now.

**Comment by syepes** [comment]
Yes, that did the trick.

**Comment by beckettsean** [comment]
Thanks, @KiNgMaR! I added `SERVER` to the reserved keywords with https://github.com/influxdb/influxdb.com/commit/ba1c2453b3e2d3d8a464fe8bb3fd752a2055a433
