### ISSUE TITLE
Unlock() is missing in tsdb/engine/tsm1.Log.flush()?

### ISSUE THREAD

**Issue by runner-mei** [influxdb/influxdb#4368]
l.cacheLock.Lock() at https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L538
l.writeLock.Lock() at https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L554
return at https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L560
panic at https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L568

**Comment by jwilder** [comment]
Fixed as part of #4538
