### ISSUE TITLE
l.cacheLock.RLock() is missing?

### ISSUE THREAD

**Issue by runner-mei** [influxdb/influxdb#4369]
RLock() is missing at https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L617
 and  https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L602

thread1 run at [wal.go#L616](https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L616) and yield.
thread2 run at enter cacheLock and  write l.flushCache at  [wal.go#L580](https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L580), then exit cacheLock and yield。
thread1 is continue, .at this time, cacheLock is newest, it is modified by the thread2.

flushCache as field of Log is insignificant. flushCache is only assigned in the flush(), and clear at end of this function.  flushCache is read in Log.Cursor()  [wal.go#L177](https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/wal.go#L177), but it is always empty.

Sorry, I am a Chinese, my English is very poor.

**Comment by jwilder** [comment]
Fixed as part of #4538.

**Comment by runner-mei** [comment]
It isn't Fixed.

**Comment by otoolep** [comment]
Can you elaborate @runner-mei ? That will help us.
