### ISSUE TITLE
Go client unable to parse Equals

### ISSUE THREAD

**Issue by johnjelinek** [influxdb/influxdb#4376]
```
Version: 0.9.4.1 on Docker tutum/influxdb via Ubuntu Trusty
Golang 1.5
```

```
var points = make([]client.Point, len(requests))
for idx, request := range requests {
	points[idx] = influx.Point{
		Measurement: "requests",
		Tags: map[string]string{
			"requestpath": request.RequestPath,
		},
		Time: request.RequestTime,
	}
}

batchPoints := client.BatchPoints{
	Points:          points,
	Database:        "request",
	RetentionPolicy: "default",
}
log.Println(batchPoints)
```

```
2015/10/08 16:43:45 {[{requests map[requestpath:C=S&N=QID&Flg=false] 2015-10-01 00:00:00.153 +0000 +0000 map[]  }] request default map[] 0001-01-01 00:00:00 +0000 UTC  }
2015/10/08 16:43:48 unable to parse 'requests,requestpath=C\=S&N\=QID&Flg\=false  1443657600153000000': invalid field format
```

**Comment by johnjelinek** [comment]
Note: if I add `Fields`, it succeeds:
```
var points = make([]client.Point, len(requests))
for idx, request := range requests {
    points[idx] = influx.Point{
        Measurement: "requests",
        Tags: map[string]string{
            "requestpath": request.RequestPath,
        },
	Fields: map[string]interface{}{
		"value": 1.0,
	},
        Time: request.RequestTime,
    }
}
```

**Comment by mjdesa** [comment]
@johnjelinek points in InfluxDB are required to have fields. As you note, if you add `Fields` to the point, the request succeeds.

**Comment by johnjelinek** [comment]
@mjdesa: oh .. I guess that wasn't clear. I think the error shouldn't be `Unable to parse` but instead `Fields required`.

**Comment by mjdesa** [comment]
```
2015/10/08 16:43:48 unable to parse 'requests,requestpath=C\=S&N\=QID&Flg\=false  1443657600153000000': invalid field format
```

At the end of the error message it says `invalid field format`.

**Comment by johnjelinek** [comment]
@mjdesa: it inserts without fields when I don't have `=` in the tags.

**Comment by mjdesa** [comment]
@johnjelinek can you send me an example so I can try to repro the issue.

**Comment by beckettsean** [comment]
@johnjelinek in the line protocol, the exact syntax is

`measurement[,tag_key=tag_value] field_key=field_value [timestamp]`

If you don't put an `=` in the tags, that space is interpreted as denoting the beginning of the field set. I'm not sure how it would parse, since the key=value pairs shouldn't match up, but as @mjdesa says, please provide an example of a point inserting without a valid field. Given the large number of escaped `=` in your example error, I suspect that the key=value pairs do somehow line up and you're simply writing a point with mistaken fields.

**Comment by johnjelinek** [comment]
I am mistaken. I cannot repro this today. Now that I look back on the error message, I was interpreting it to mean a field (but not specific to "Fields") in the line protocol is in the incorrect format, rather than the "Fields" property is missing/invalid. I'll make sure that Fields is provided (but also a cool feature would be to have go complain at compile time if Fields is missing).
