### ISSUE TITLE
Arithmetic expressions should work with aggregations

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#438]
`select (-100 * mean(value) + 100) from /.*/ group by time(30m) where time > now() - 2d`

**Comment by mmikulicic** [comment]
My use case is to be able to aggregate rates of some event:

```
select derivative(i1.value) as d + derivative(i2.value) as f from "foo.i1" as i1 inner join "foo.i2" as i2 group by time(60s) limit 100
```

```
Server returned (400): Value cannot be evaluated for type &{derivative d 10 [0xc2081b9040] <nil> false}
```

**Comment by beckettsean** [comment]
Excellent use case writeup in #1299

**Comment by mjdesa** [comment]
I think this is no longer an issue. Closing issue.

**Comment by alexiri** [comment]
@mjdesa I'm confused, is this no longer an issue because it's been implemented? It doesn't look like it's working.

**Comment by jessetan** [comment]
Is this fixed or not? I see a lot of linked issues that are also closed, but on my 0.9.6.1 install I can not do math on aggregates:
This works: `SELECT 1.5 + value FROM "processes_user" WHERE time > now() - 5m`
This works: `SELECT 1.5 + mean(value) FROM "processes_user" WHERE time > now() - 5m GROUP BY time(10s)`
This does not work: `SELECT 1.5 + derivative(mean(value)) FROM "processes_user" WHERE time > now() - 5m GROUP BY time(10s)`, returns the same as `SELECT derivative(mean(value)) FROM "processes_user" WHERE time > now() - 5m GROUP BY time(10s)` although the column name is gone.

**Comment by mjdesa** [comment]
@jessetan `derivative` isn't an aggregation. Please open an issue for the problem you've cited.

**Comment by jessetan** [comment]
Thanks @mjdesa, opened #5571
