### ISSUE TITLE
Aggregate query with Group By time produces 1 result when many expected.

### ISSUE THREAD

**Issue by llevar** [influxdb/influxdb#4383]
I have collectd feeding data into influxdb at 10s intervals from a cluster of 50 nodes. I'm interested in looking at network stats.

If I select the actual data I get this:

SELECT value FROM interface_rx WHERE host = 'tracker' and type = 'if_packets' and instance = 'eth0' and time < now() - 1h limit 1000;

Overall there are 145652 samples during this time period.

![image](https://cloud.githubusercontent.com/assets/5853959/10392291/02569676-6e86-11e5-85c9-18e5b1c02b71.png)

If I then try to get bucketed counts, I only get 1 value, while I expect to get 6:

SELECT count(value) FROM interface_rx WHERE host = 'tracker' and type = 'if_packets' and instance = 'eth0' and time < now() - 1h GROUP BY time(10m)   limit 1000;

![image](https://cloud.githubusercontent.com/assets/5853959/10392342/69c0782c-6e86-11e5-83d9-f3836a30e88a.png)

Any clues to why this is happening?

**Comment by beckettsean** [comment]
First, for reporting bugs please use `curl` or the CLI, as the Admin UI introduces too many variables around browsers, JSON rendering, etc.

Second, why do you have a LIMIT clause on the aggregation? If you take that off what happens?

**Comment by Pomyk** [comment]
I think you should use ">" instead of "<" in the query.

**Comment by beckettsean** [comment]
Indeed, please see https://influxdb.com/docs/v0.9/troubleshooting/frequently_encountered_issues.html#getting-unexpected-results-with-group-by-time
