### ISSUE TITLE
Compactions create files bigger than 4GB

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#4388]
Data files can't be bigger than 4GB because the index positions are kept in `uint32`s. There's a bug right now that if a shard gets bigger than 4GB it will get compacted into 1 file instead of being spread out over multiple files.

* Test that ensures compaction doesn't do this
* Test that a flush from the wal to an old area of time that would cause the file to go over the limit doesn't cause a problem (the file should be split in two)

**Comment by otoolep** [comment]
I thought the fix for this issue was much more complex, no? Is it the one-line fix shown in #4402?

**Comment by otoolep** [comment]
OK, this must be the auto-close from github.
