### ISSUE TITLE
[0.9.3] memory leak in three node cluster

### ISSUE THREAD

**Issue by harryshayne** [influxdb/influxdb#4396]
I just write 1000 series per second into one node,after a week, mem leak--- ,here is the 'top' cmd screen:

```
   PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                    
 79132 root      20   0 33.0g  26g 9.3g S  7.0 84.3  18425:13 influxd   
```
anyone can tell me why,is this fixed in new edition? 

PS:influxdb0.9.3, cluster, three node

**Comment by beckettsean** [comment]
@harryshayne the output you give is too limited to be diagnostic, and 0.9.3 has known issues with clustering. I don't know that 0.9.4 will address the memory issues, you can read up about [the new storage engine](https://influxdb.com/blog/2015/10/07/the_new_influxdb_storage_engine_a_time_structured_merge_tree.html) and decide for yourself if you want to test it before the official 0.9.5 release.
