### ISSUE TITLE
0.9.5-nightly-64cef0f restart no http port 8086 open

### ISSUE THREAD

**Issue by gaochenchao** [influxdb/influxdb#4398]
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago)
        Linux BJ-YF-8-2 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

Influxdb: 0.9.5-nightly-64cef0f

my influxdb use a lot of memory, and last grow. from 5G(first notice) to 6.9G
   
 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                           
30164 influxdb  20   0 25.4g 6.9g 3.3g S 77.0  7.3 801:05.87 influxd 

when i restart the influxdb process. http port can't open.

the log print:
[monitor] 2015/10/10 15:52:47 Storing statistics in database '_internal' retention policy '', at interval 10s
[store] 2015/10/10 15:52:47 Using data dir: /home/influxdb/data
[metastore] 2015/10/10 15:52:47 Updated node id=1 hostname=localhost:8088
[monitor] 2015/10/10 15:53:03 failed to store statistics: timeout
[monitor] 2015/10/10 15:53:13 failed to store statistics: timeout
[monitor] 2015/10/10 15:53:23 failed to store statistics: timeout
[monitor] 2015/10/10 15:53:33 failed to store statistics: timeout
[monitor] 2015/10/10 15:53:43 failed to store statistics: timeout
[monitor] 2015/10/10 15:53:53 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:03 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:13 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:23 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:33 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:43 failed to store statistics: timeout
[monitor] 2015/10/10 15:54:53 failed to store statistics: timeout
[monitor] 2015/10/10 15:55:03 failed to store statistics: timeout
[monitor] 2015/10/10 15:55:13 failed to store statistics: timeout
[monitor] 2015/10/10 15:55:23 failed to store statistics: timeout

What can i do?

**Comment by otoolep** [comment]
What may be happening is data that is currently in the WAL is being flushed out to disk. Until that happens the node is not ready to accept any writes, including statistical information.

Let it sit there, it should resolve itself, though this may take minutes.

**Comment by gaochenchao** [comment]
Thanks for your answer!
After about fifteen minute, it's work. but i think the time of it spend is too long.  nobody can bear it.
