### ISSUE TITLE
[0.9.4.2] invalid DELETE query doesn't return error

### ISSUE THREAD

**Issue by caoli5288** [influxdb/influxdb#4404]
30m ago, I run `delete from xxx where time < now() -7d` and it lag till now. 
By the way, the process `influxd` always use 200% cpu time.

**Comment by caoli5288** [comment]
2 hours past :-)

**Comment by beckettsean** [comment]
DELETE FROM is not yet a valid query. https://github.com/influxdb/influxdb/issues/1647 is the open issue for making it work.

The query should give a parser error, though.

**Comment by caoli5288** [comment]
@beckettsean So how can I delete a specific record?

**Comment by beckettsean** [comment]
@caoli5288 you cannot delete a specific record.

**Comment by caoli5288** [comment]
@beckettsean Never can not?

**Comment by beckettsean** [comment]
@caoli5288 it is possible to overwrite a point, or to delete a series or measurement, or use a retention policy to bulk delete older data, but InfluxDB does not support the deletion of a single point. It is one of the [optimizations](https://influxdb.com/blog/2015/06/03/InfluxDB_clustering_design.html) that allows for much higher throughput than a traditional RDBMS.

**Comment by caoli5288** [comment]
@beckettsean Thanks!

**Comment by nathanielc** [comment]
I can reproduce the hang on 0.9.4.2 but not in master. @caoli5288 Do you still see the issue on a newer version?

**Comment by caoli5288** [comment]
@nathanielc When I knew it was an not supported operation , I never tried it again. THX.
