### ISSUE TITLE
using multiple database with collectd input

### ISSUE THREAD

**Issue by thebinary** [influxdb/influxdb#4405]
Can I use multiple database in influxd for the collectd input from different source, segregating for example network devices and server metrics. 
I tried using different block of collectd in config file defining different ports and different database but it thows the following error:

__run: parse config: Near line 79 (last key parsed ''): Key 'collectd' has already been defined.__

My config file includes follow:

[collectd]
  enabled = true
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

[collectd]
  enabled = true
  bind-address = ":25801"
  database = "server"
  retention-policy = ""
  batch-size = 1000
  batch-pending = 5
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

**Comment by caoli5288** [comment]
Obviously cannot.

**Comment by otoolep** [comment]
Collectd support is limited to a single database.

Instead, enable Carbon output for collectd and then send that to a Graphite
input on InfluxDB. You can have multiple Graphite inputs.

**Comment by thebinary** [comment]
can i use graphite inout and use tags?

**Comment by otoolep** [comment]
I don't understand the question. Can you clarify?

**Comment by thebinary** [comment]
inout -> *input

I already found the answer. I can use regex to separate dot separation into tags. Apologies for posting the comment. I had removed the comment it actually. Still thanks for the reply.

**Comment by thebinary** [comment]
how do i separate databases for multiple graphite inputs?

**Comment by crazy-canux** [comment]
how did you fix this problem?

**Comment by febrez** [comment]
`[[collectd]]` ?

**Comment by satishdotpatel** [comment]
I have same question, i want to run multiple [[collectd]] on same influxdb box, how do i do that?
