### ISSUE TITLE
How to migrate data from 0.9.4 to new tsm engine in 0.9.5

### ISSUE THREAD

**Issue by abolinhas** [influxdb/influxdb#4408]
Hi
as the backup / restore don't work in version 0.9.4 exists or will exist a tool to migrate data from 0.9.4 to new tsm engine in 0.9.5?
If not, what the best way?
Best regards

**Comment by mimmovele** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by beckettsean** [comment]
There will be a tool for migrating `b1` or `bz1` shards into the `tsm1` format but it probably won't come with 0.9.5. More likely with 0.9.6.

**Comment by abolinhas** [comment]
But while the migration tool is not ready, there is other (hard) way?

**Comment by beckettsean** [comment]
You could export all your data, stop the service, enable the `tsm1` engine in the config, delete the `/data` and `/meta` directories, and then load all the points back in. Otherwise there is no way to migrate shards to `tsm1` until the tool exists.

**Comment by abolinhas** [comment]
@beckettsean
I will try this method. I will back to you a soon as possible with the output of this operation. 
Thanks

**Comment by abolinhas** [comment]
@beckettsean
When you say 
|You could export all your data, stop the service

You mean copy the database folder or use something like Dump action? In mysql we can dump the query into a file
SELECT * FROM db FILEINTO /home/mydump

I can do it in influx? 
Your dump command don't work

root@stats-appliance:~# /opt/influxdb/influx -database proxydb -dump
flag provided but not defined: -dump
Usage of influx:
  -version
       Display the version and exit.
  -host 'host name'
       Host to connect to.
  -port 'port #'
       Port to connect to.
  -database 'database name'
       Database to connect to the server.
  -password 'password'
      Password t

Or
/opt/influxdb/influx -host 127.0.0.1 -database proxydb -dump
flag provided but not defined: -dump

**Comment by beckettsean** [comment]
@abolinhas unfortunately if that is not working I don't know of a way to export the data except as query results.

**Comment by abolinhas** [comment]
@beckettsean I found a way to dump the record into json file
|curl -G 'http://192.168.0.18:8086/query?pretty=true' --data-urlencode "db=proxydb" --data-urlencode "q=SELECT * FROM access_log limit 2" > series_name.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1587  100  1587    0     0   139k      0 --:--:-- --:--:-- --:--:--  154k
Output
|root@articaproxy:~# cat series_name.json
{
    "results": [
        {
            "series": [
                {
                    "name": "access_log",
                    "columns": [
                        "time",
                        "FAMILYSITE",
                        "IPADDR",
                        "MAC",
                        "RQS",
                        "SITE",
                        "SIZE",
                        "USERID",
                        "ZDATE",
                        "proxyname"
                    ],
                    "values": [
                        [
                            "2015-10-12T17:00:00Z",
                            "google.com",
                            "192.168.0.11",
                            "68:5d:43:61:e2:f2",
                            2,
                            "clients1.google.com",
                            6337,
                            "abolinhas",
                            1.4446728e+09,
                            "articaproxy.srv.home.local"
                        ],
                        [
                            "2015-10-12T17:00:00Z",
                            "sapo.pt",
                            "192.168.0.11",
                            "68:5d:43:61:e2:f2",
                            8,
                            "24.sapo.pt",
                            12666,
                            "abolinhas",
                            1.4446728e+09,
                            "articaproxy.srv.home.local"
                        ]
                    ]
                }
            ]
        }
    ]

Now I need to know how to import the json into Influx, is there any way?

**Comment by beckettsean** [comment]
The JSON write protocol is deprecated and the docs are no longer online, but I tossed the old doc into a [gist](https://gist.github.com/beckettsean/13e42cb3da92207b50dd) so you can see the syntax.

I'm honestly not sure which will be easier, but you'll need to parse the results JSON into either valid write JSON or the [line protocol](https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html) in order to submit the points to InfluxDB 0.9.

**Comment by otoolep** [comment]
This is being handled by https://github.com/influxdb/influxdb/issues/4517
