### ISSUE TITLE
Clustering documentation - Update ?

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb#4412]
Hi Influx team !

Is it possible to have an update on the clustering documentation ? based here https://influxdb.com/docs/v0.9/guides/clustering.html

You mention file /etc/default/influxdb which is not present after an fresh influxdb installation (0.9.4.1).

Thanks.

**Comment by otoolep** [comment]
It is best if documentation changes are be opened against the influxdb.com repo, not this one.

`/etc/default/influxdb` is a file you must create yourself, if you want to configure such things are logging and clustering. It is not included in the package. Make sense?

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb.com/issues to file documentation issues.

**Comment by JulienChampseix** [comment]
thanks @otoolep
