### ISSUE TITLE
Multiple MIN and MAX aggregations in one query give incorrect results

### ISSUE THREAD

**Issue by hughescr** [influxdb/influxdb#4417]
It looks like if you have more than one min()/max() in a query, the results give the value of the last of them as the value for all of them:

```
> select count(CHILL),min(HUM),max(CHILL),min(CHILL) from station where time >= '2015-10-11' and time < '2015-10-12' group by time(6h)
name: station
-------------
time			count	min	max	min
1444521600000000000	360	44	44	44
1444543200000000000	360	46	46	46
1444564800000000000	360	44	44	44
1444586400000000000	360	52	52	52

> select count(CHILL),min(HUM),min(CHILL),max(CHILL) from station where time >= '2015-10-11' and time < '2015-10-12' group by time(6h)
name: station
-------------
time			count	min	min	max
1444521600000000000	360	66	66	66
1444543200000000000	360	49	49	49
1444564800000000000	360	53	53	53
1444586400000000000	360	65	65	65
```

This is happening whether it's min() or max(), and regardless of what field you're querying.  With or without grouping, with or without time constraint.

**Comment by hughescr** [comment]
Note how in the above, with the same underlying data, swapping the order of "min(CHILL)" and "max(CHILL)" returns different results.

**Comment by otoolep** [comment]
Can you please tell us what version you are running?

**Comment by corylanou** [comment]
This should be fixed by https://github.com/influxdb/influxdb/issues/4360

**Comment by hughescr** [comment]
I believe I'm using 86b5ad2 but the server just reports "0.9" which it seems to do for any built-from-source version (at least that I've noticed).  Running on a raspberry pi installed and built from sources using go get.

**Comment by hughescr** [comment]
Will rebuild and check with #4360 now

**Comment by hughescr** [comment]
Confirm; looks fixed now in HEAD
