### ISSUE TITLE
Can not write data with empty tag value

### ISSUE THREAD

**Issue by decker502** [influxdb/influxdb#4421]
When data is written in below form, server returns "missing tag value"
````
cpu,key1=f1,key2=f2,key3= value=xxx 1444718454
````
But it's successful in below form

````
cpu,key1=f1,key3=,key2=f2 value=xxx 1444718454
````

influxdb version is 0.9.4.1

**Comment by jwilder** [comment]
That second one _should_ fail too with a `missing tag value` error.
