### ISSUE TITLE
[0.9.4.2] raft issues in InfluxDB Docker volumes: new bolt store: invalid argument

### ISSUE THREAD

**Issue by derailed** [influxdb/influxdb#4425]
Hi,

   I've seen many references to this issue but haven't seen a definite resolve anywhere as of yet...

   Here is the scoop, I have a prelim deploy of influx on a test server using docker + ecs. 
   I want to be able to export the data volume so that the data survives restarts + enable backups. 
   The problem I am seeing right now is if I map a data volume outside the container or setup a container volume (no difference)
    I get the following error which looking at the code might indicate a permission issue??

```
2015/10/07 19:58:30 InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543
2015/10/07 19:58:30 Go version go1.5, GOMAXPROCS set to 8
2015/10/07 19:58:30 Using configuration at: /config/config.toml
[metastore] 2015/10/07 19:58:30 Using data dir: /data/meta
[retention] 2015/10/07 19:58:30 retention policy enforcement terminating
[monitor] 2015/10/07 19:58:30 shutting down monitor system
run: open server: open meta store: raft: new bolt store: invalid argument
```
   Thought a more detailed error would be nice...

   Can anyone shade some light on this? If so any ideas? What's causing it/ work arounds?

   Not using volumes causes the container to happily start and happily blow away all my data once it's stopped. Kind of a big deal...

Thanks!!

**Comment by jwilder** [comment]
That error sounds like this might be an issue related to how you are starting the container and the something with volume being mounted in (wrong perms, NFS, etc..).  If you can provide some steps so we can reproduce this, we can probably get it resolved.  

A few questions:
* Can you provide your Dockerfile?
* What are the exact commands you are running to start your container?
* Where are you running this?  Is your volume directly on a linux host, under vagrant, docker-machine/virtualbox, etc..?

**Comment by derailed** [comment]
Thanks for the reply. I can't share the docker image since it's a private repo but here are the specifics:

Dockerfile

VOLUME ["/data"]

config.toml 

NOTE: config is straight from your repo sample. 

Changed All path references to ref the volume namely /data

[meta]
  dir = "/data/meta"
  ...
[data]
  dir = "/data/db"
  wal-dir = "/data/wal"

[hinted-handoff]
  dir = "/data/hh"

DockerCompose

influx:
  image: influxdb
  ports:
    - "8086:8086"
  volumes:
     - /var/data/influxdb:/data

Container start
influxd run -d /config/config.toml

Running on osx - tried both a straight mount or mounting from a container image. Same results.

Results:
run: open server: open meta store: raft: new bolt store: invalid argument

**Comment by jwilder** [comment]
If you are running on OS X, with `docker-machine`/`virtualbox`, then this is very likely a limitation of `vboxsf` storage driver and `mmap`ed files.  Bolt uses `mmap` for the database files and returns is returning errors in this case when the bolt file exists on a volume that doesn't support `mmap`ed files.  There is a very old (and still open) issue for `virtualbox` which might be related here: https://www.virtualbox.org/ticket/819.

Not sure if there is much we can do about this though as it's a issue with docker and virtualbox.  

Some workarounds:
* You could try running docker and your influxdb container from within a vagrant VM and use a volume that is not mounted/shared from your host (e.g. something other than `/Vagrant`).  
* You could also try using a different VM provider that might have better support for OS X (maybe VMWare?).  
* Other than that, you'll probably need to run this on linux where docker volumes are better supported.

**Comment by derailed** [comment]
Thanks Jason! Think I've found a solution. Might help others so posting here

Here is my docker-compose setup

influxdata:
  image: influxdb
  container_name: influxdata
  volumes:
    - /data
  command: /bin/true

influx1:
  image: influxdb
  container_name: influx1
  volumes_from:
    - influxdata

This setup will launch an influx instance correctly and sync the data into
a container image provided the toml config paths points to /data/xxx.

Using docker run you can then inspect the data volume and backup data if
needs be.

**Comment by jwilder** [comment]
@derailed Good to know a data container works.  Thanks!

**Comment by beckettsean** [comment]
@rossmcdonald @gunnaraasen in case you missed the Docker details here
