### ISSUE TITLE
unable to parse: invalid number

### ISSUE THREAD

**Issue by snakeye** [influxdb/influxdb#4433]
Hello,

I have met strange issue with the HTTP API:

```
curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test value=4.4 1444766780000000000'
HTTP/1.1 204 No Content

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test value=4.4e-7 1444766780000000000'
HTTP/1.1 204 No Content

curl -i -XPOST 'http://localhost:8086/write?db=test' --data-binary 'test value=4.4E-7 1444766780000000000'
HTTP/1.1 400 Bad Request
unable to parse 'test value=4.4E-7 1444766780000000000': invalid number
```

Interesting point that the issue occurs not every time, but only one-two times per minute while influxdb receives ~20 messages per second. From my point of view it should either every float value or no error at all.

**Comment by otoolep** [comment]
@jwilder -- is the fix as simple as https://github.com/influxdb/influxdb/pull/4434 ?

**Comment by otoolep** [comment]
Thanks for the report @snakeye -- the fix will be in the next nightly build.
