### ISSUE TITLE
IN Clause

### ISSUE THREAD

**Issue by abolinhas** [influxdb/influxdb#4456]
Hi,
In mysql I have the IN clause to select multiple values on same field
mysql> SELECT * FROM employee_tbl 
    -> WHERE daily_typing_pages IN ( 250, 220, 170 )

In Influx there are similar clause?

Best regards

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/issues/2157 -- dupe.

**Comment by otoolep** [comment]
We might have this in 0.9.5 depending on how development goes.

**Comment by abolinhas** [comment]
@otoolep many thanks, 
The regex trick for now does the job
SELECT * from mydb WHERE service =~ /aa|bb/
