### ISSUE TITLE
regular expression on columns that are NOT tags does not work, v0.9.4

### ISSUE THREAD

**Issue by gitRahul** [influxdb/influxdb#4457]
regular expression on columns that are NOT tags does not work
Below is a query on a column that is a TAG
![tagcolumn](https://cloud.githubusercontent.com/assets/6994838/10520819/ff2f5b44-7331-11e5-9dae-2527ee269ef7.png)
Belew is a query on a column that is NOT a TAG but just a regular field
![nontagcolumn](https://cloud.githubusercontent.com/assets/6994838/10520863/465fadac-7332-11e5-89b0-d475a34b1648.png)

**Comment by beckettsean** [comment]
duplicate of https://github.com/influxdb/influxdb/issues/2715
