### ISSUE TITLE
[questions] collectd test client generated more fields

### ISSUE THREAD

**Issue by joyhope** [influxdb/influxdb#4482]
I uses collectd/test_client. The test_client only insert one field data. I try to insert more field data as following, but it cause the influxd database unable to work.

###
		vl := api.ValueList{
			Identifier: api.Identifier{
				Host:   "tagvalue" + strconv.Itoa(int(rand.Int31n(int32(*tagVariance)))),
				Plugin: "golang" + strconv.Itoa(int(rand.Int31n(int32(*nMeasurments)))),
				Type:   "gauge",
			},
			Time:     time.Now(),
			Interval: 10 * time.Second,
/*
absolute		value:ABSOLUTE:0:U
apache_bytes		value:DERIVE:0:U
apache_connections	value:GAUGE:0:65535
apache_idle_workers	value:GAUGE:0:65535
apache_requests		value:DERIVE:0:U
apache_scoreboard	value:GAUGE:0:65535
ath_nodes		value:GAUGE:0:65535
ath_stat		value:DERIVE:0:U
backends		value:GAUGE:0:65535
bitrate			value:GAUGE:0:4294967295
bytes			value:GAUGE:0:U
*/
			Values:   []api.Value{api.Gauge(42.0), 
				                  api.Derive(rand.Int63n(100)),    <==I added here
				                  api.Gauge(rand.Float64()*100+100),
				                  api.Gauge(rand.Float64()*100+50),
				                  api.Derive(rand.Int63n(200)),
				                  api.Gauge(rand.Float64()*200+50), <== end add	                  
				                  },
		}
###

Where is the problem?

**Comment by otoolep** [comment]
We need more information.

How do you know it doesn't work? Where are the queries? I also don't know what you mean by the the test client in this context?

**Comment by otoolep** [comment]
Also, please read about, and try out, the stats and diagnostics that are available to help you debug issues working with the database. There are collectd stats.

https://influxdb.com/blog/2015/09/22/monitoring_internal_show_stats.html
https://github.com/influxdb/influxdb/blob/master/monitor/README.md

**Comment by joyhope** [comment]
I am a beginner for influxdb. Collectd seems is a good data source to generated more data.  Your suggestion is helpful, I try.

**Comment by joyhope** [comment]
The log: it seems my code cause problem.  

goroutine 29 [running]:
github.com/kimor79/gollectd.Packets(0xc82049a000, 0x54, 0x5ac, 0xc82045c4b0, 0xc81ffd8814, 0x0, 0x0)
        /tmp/build/src/github.com/kimor79/gollectd/gollectd.go:225 +0x1a84
github.com/influxdb/influxdb/services/collectd.(*Service).handleMessage(0xc820117180, 0xc82049a000, 0x54, 0x5ac)
        /tmp/build/src/github.com/influxdb/influxdb/services/collectd/service.go:220 +0x5e
github.com/influxdb/influxdb/services/collectd.(*Service).serve(0xc820117180)
        /tmp/build/src/github.com/influxdb/influxdb/services/collectd/service.go:214 +0x302
created by github.com/influxdb/influxdb/services/collectd.(*Service).Open
        /tmp/build/src/github.com/influxdb/influxdb/services/collectd/service.go:137 +0x1092

**Comment by otoolep** [comment]
What version are you running?

**Comment by joyhope** [comment]
influxdb_0.9.4.1_amd64.deb .  My code is a problem. My try to create multi field result, but my solutions is not correct.
