### ISSUE TITLE
[0.9.4.2] unable to redirect stderr, unable to stop service under systemd  

### ISSUE THREAD

**Issue by yamagoya** [influxdb/influxdb#4490]
I am evaluating Influxdb and am running into a logging problem.
I've installed it from the nightly build on a Fedora-21 machine
and it seems to work ok when started interactive in a console but
want to get it to start under systemd.  I used the included
influxdb.service file.

I haven't been able to redirect the log messages.  As suggested
I created an /etc/defaults/influxdb file containing
   STDOUT=/var/log/influxdb/stdout.log
   STDERR=/var/log/influxdb/stderr.log
and created those two files, verified owner is "influxdb" user,
permissions ok.  However log messages still go to the journal. 
At two lines every 10 seconds they outnumber all other journal
messages by nearly an order of magnitude which is an unacceptable
level of log spam. 

I have not had to do much with systemd so my knowledge is pretty
limited, but judging from the fact that the ExecStart command
doesn't use STDERR or STDOUT in the command line, these effect
influxd by being environment variables?  FWIW, running influxd
interactively as "STDERR=/var/log/... influxd ..." doesn't
redirect logging messages either.

I changed the service file ExecStart command to be
  sh -c "/opt/influxdb/influxd .... 2>/var/log/..."
which does finally redirect the log messages, but now influxd
doesn't stop when a  "systemctl stop influxdb" command is issued.
[the above was originally posted on the influxdb mailing list, 2015-10-16]

A little more info...
After starting influxd with systemd:
\# ps -AF | grep influxd
influxdb 15402     1  0 28385  2888   0 Oct16 ?        00:00:00 /bin/sh -c /opt/influxdb/influxd -config /opt/influxdb/soga.conf $INFLUXD_OPTS >/var/log/influxdb/stdout.log 2>/var/log/influxdb/stderr.log
influxdb 15403 15402  0 128827 61492  1 Oct16 ?        00:07:27 /opt/influxdb/influxd -config /opt/influxdb/soga.conf

After doing a 'systemctl stop influxdb':
\# ps -AF | grep influxd
influxdb 15403     1  0 128827 61492  1 Oct16 ?        00:07:27 /opt/influxdb/influxd -config /opt/influxdb/soga.conf

Perhaps the influxd process is daemonizing itself?  As I said, I know little
about systemd but I think most processes running under it should be run
in foreground.   

Of course, getting the original STDERR=... and STDOUT=... to work (and
better documented!) would be better, but the systemd problem should be 
fixed regardless.

**Comment by rossmcdonald** [comment]
Try replacing the existing unit file (`/etc/systemd/system/influxd.service`) with the following:

```
[Unit]
Description=InfluxDB is an open-source, distributed, time series database
Documentation=https://influxdb.com/docs/
After=network.target

[Service]
User=influxdb
Group=influxdb
LimitNOFILE=65536
EnvironmentFile=-/etc/default/influxdb
ExecStart=/bin/sh -c "/usr/bin/influxd -config /etc/influxdb/influxdb.conf ${INFLUXD_OPTS}"
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=influxd.service
```

Namely this changes the formatting of the environment variable and killmode for the service. The reason why you were unable to kill InfluxDB once started is because you created two separate processes to redirect the log output, one for `sh` and one for `influxd`. Since the original killmode was set to the process level, all you were originally killing was just the `sh` process. By switching this to `control-group`, you will kill everything in the same control group (`influxd` included).

And then in the defaults file `/etc/default/influxdb`, you can use:

```
INFLUXD_OPTS="&>/var/log/influxdb/influxd.log"
```

To redirect all logging to the log file. I'm unfamiliar with the `STDERR` and `STDOUT` variables, so I'm not sure what the problem could be there.

Regarding the level of logging, if you are finding that the default configuration generates too much data, I would recommend modifying your InfluxDB configuration (`/etc/opt/influxdb/influxdb.conf`) to disable some of the more chattier log functionality. Mainly the `wal-enable-logging` under `[data]` and `log-enabled` under `[http]`:

```
...
[data]
  wal-enable-logging = false
...
[http]
  log-enabled = false
...
```

I will leave this issue open as a reminder to update the default systemd configuration, and then link to the PR once submitted.

**Comment by otoolep** [comment]
Also this line:

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L81

but if you disable *all* this stuff, it may become quite difficult for us to help you debug any issues.

**Comment by sergzin** [comment]
I have similar issue with InfluxDB running on debian 8.2 
version 0.9.5-nightly-d9f0413, branch master, commit d9f04132ef567bb9671690e4db226ff3dab9feb5, built '2015-10-17T04:00:42+0000'

all messages are forwarded to /var/log/syslog
even if I start influx like this:
STDOUT=/var/log/influxdb/stdout.log STDERR=/var/log/influxdb/stderr.log /opt/influxdb/influxd -config /etc/opt/influxdb/influxdb.conf

**Comment by rossmcdonald** [comment]
@sergzin Can you try using the following unit file and let me know if you hit the same problem?

`/etc/systemd/system/influxd.service`:

```
[Unit]
Description=InfluxDB is an open-source, distributed, time series database
Documentation=https://influxdb.com/docs/
After=network.target

[Service]
User=influxdb
Group=influxdb
LimitNOFILE=65536
Environment='STDOUT=/dev/null'
Environment='STDERR=/var/log/influxdb/influxd.log'
EnvironmentFile=-/etc/default/influxdb
ExecStart=/bin/sh -c "/opt/influxdb/influxd -config /etc/opt/influxdb/influxdb.conf ${INFLUXD_OPTS} > ${STDOUT} 2> ${STDERR}"
KillMode=control-group
Restart=on-failure

[Install]
WantedBy=multi-user.target
Alias=influxd.service
```

**Comment by sergzin** [comment]
Redirecting STDERR works fine.

```
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/lib/systemd/system/influxdb.service; enabled)
   Active: active (running) since Tue 2015-10-20 20:12:55 CEST; 11s ago
     Docs: https://influxdb.com/docs/
 Main PID: 6308 (sh)
   CGroup: /system.slice/influxdb.service
           ├─6308 /bin/sh -c /opt/influxdb/influxd -config /etc/opt/influxdb/influxdb.conf -hostname at-vie01a-osd03 > /dev/null 2> /var/log/influxdb/influxd.log
           └─6309 /opt/influxdb/influxd -config /etc/opt/influxdb/influxdb.conf -hostname at-vie01a-osd03

```

In `/var/log/influxdb/influxd.log`  i see startup messages and queries.
