### ISSUE TITLE
Writing with InfluxDB API got HTTP 500

### ISSUE THREAD

**Issue by zxsimple** [influxdb/influxdb#4492]
I'm writing metrics with HTTP API, however got 500 status occasionally as follow:

```
[http] 2015/10/19 11:49:34 192.168.30.29 - root [19/Oct/2015:11:49:29 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 668b4df7-7614-11e5-ae45-000000000000 5.111829163s
[http] 2015/10/19 11:49:34 192.168.30.28 - root [19/Oct/2015:11:49:29 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 669777f0-7614-11e5-ae46-000000000000 5.140964539s
```
I see the writing timeout configured is 5s:
```
[cluster]
  shard-writer-timeout = "5s" # The time within which a shard must respond to write.
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.
```
I am not wrting much data simutaenously, perhaps less than 10 records per second, also I see the data file reaches 60GB, however I've already deleted old data.

Any tips on tunning writing performance of InfluxDB? I don't think simply increase the writing timeout is a good idea.
```
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:55 10
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:54 11
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:54 12
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:54 13
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:54 14
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:55 15
-rw-r--r-- 1 influxdb influxdb 1.0G Oct 19 11:55 16
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:55 17
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:55 18
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:55 19
-rw-r--r-- 1 influxdb influxdb  32M Oct 19 11:54 5
-rw-r--r-- 1 influxdb influxdb 128K Oct 19 11:54 6
-rw-r--r-- 1 influxdb influxdb 512M Oct 19 11:54 7
-rw-r--r-- 1 influxdb influxdb  57G Oct 19 11:45 8
-rw-r--r-- 1 influxdb influxdb 1.0G Oct 19 11:55 9
```

**Comment by zxsimple** [comment]
It's really terrible, after I reduce the WAL size from 100M to 10M, the writing cost increase too.

[http] 2015/10/19 12:17:34 192.168.30.28 - root [19/Oct/2015:12:17:07 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 42d6ea65-7618-11e5-89d5-000000000000 26.618662821s
[http] 2015/10/19 12:17:34 192.168.30.26 - root [19/Oct/2015:12:16:57 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 3c82fc7f-7618-11e5-89c3-000000000000 37.235748578s
[http] 2015/10/19 12:17:34 192.168.30.27 - root [19/Oct/2015:12:17:07 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 42d65639-7618-11e5-89d2-000000000000 26.625067186s
[http] 2015/10/19 12:17:34 192.168.30.44 - root [19/Oct/2015:12:16:57 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 3c7cb984-7618-11e5-89c1-000000000000 37.279376876s
[http] 2015/10/19 12:17:34 192.168.30.18 - root [19/Oct/2015:12:17:08 +0800] POST /write?u=root&p=root&db=bird&rp=default&precision=n&consistency=all HTTP/1.1 500 32 - okhttp/2.4.0 43839b72-7618-11e5-89dc-000000000000 25.495872316s

**Comment by beckettsean** [comment]
@zxsimple the HTTP 500 response means that the database is too busy to accept more writes, and your submitters should back off for a bit while the database recovers.

You've told us nothing about your system or your writes, so we can't say whether the database should be able to handle the load, but this is expected behavior when the system is stressed.

What version of InfluxDB?

> I am not wrting much data simutaenously, perhaps less than 10 records per second, also I see the data file reaches 60GB, however I've already deleted old data.

60GB of data is a fair amount. How many points are you sending per batch? How many batches per second? I see that it's taking multiple seconds to write so I assume they are very large batches.

How much RAM is on the machine? How many CPUs?

**Comment by zxsimple** [comment]
The version of InfluxDB I'm using is 0.9.2.
My server RAM is 128G, CPU 12 cores. There are other server and services installed on the same server, 100RAM used CPU load is around 10%.

In my senario, I deployed serveral services on distributed servers, each service count the invocations and the duration of invocation. Each 10s it does this calculation and form a point like {totoal_invokes: 1000, avg_invoke_time: 20} then write to InfluxDB. So only 1 point written to InfluxDB each time from each Web application service.

I increased the write timeout to be 10s, the problem gone. Still I don't think it resolve the problem, because InfluxDB is not stressed.

-------------------------------------------------------------------------------------------------------------------------------
I'm not sure whether it is proper to post another issue here. InfluxDB crashes with the error below, I'll look this issue first.

goroutine 1715203 [running]:
github.com/influxdb/influxdb/tsdb.func·022(0x249, 0x7fffffff)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:1164 +0xca
sort.Search(0x492, 0xc20a589780, 0x1b)
        /root/.gvm/gos/go1.4.2/src/sort/search.go:66 +0x59
github.com/influxdb/influxdb/tsdb.(*shardCursor).Seek(0xc27b068de0, 0xc2098ae130, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:1165 +0x1b0
github.com/influxdb/influxdb/tsdb.(*seriesCursor).SeekTo(0xc277b95200, 0x140e716c35787000, 0xc245cd8300, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:633 +0xa1
github.com/influxdb/influxdb/tsdb.(*AggMapper).NextChunk(0xc2080aa460, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/mapper.go:431 +0x533
github.com/influxdb/influxdb/tsdb.(*StatefulMapper).NextChunk(0xc215c98d20, 0xc2108722a0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:54 +0x5c
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc28d21eff0, 0xc20cb4a8a0)
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:387 +0x7fd
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
        /root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:337 +0x5a

goroutine 1 [chan receive, 1366 minutes]:
main.(*Main).Run(0xc20808fa80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x73b
main.main()
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc

goroutine 6 [syscall, 1367 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 18 [chan receive, 1367 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc20803adf0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208072140)
        /root/go/src/github.com/influxdb/influxdb/meta/store.go:470 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /root/go/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2

goroutine 17 [syscall, 1367 minutes, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

**Comment by otoolep** [comment]
I strongly suggest you upgrade to 0.9.4.2. There are been a large number of bug fixes committed to the source since 0.9.2.

https://influxdb.com/download/index.html

**Comment by zxsimple** [comment]
Thanks @otoolep and @beckettsean , I've already upgrated it to date. Till now everything looks good, I'll keep on looking at it further.

**Comment by cblomart** [comment]
It would look like the golang v2 client doesn't handle well this.
When inserting large amount of point (40000) in one request i do recieve some 500 errors from influxdb.
More anoyingly, the client seems to simply panicing instead of handling it gracefully.
