### ISSUE TITLE
how to make query where tag value is null?

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#4495]
`where somekey !=""`
didn't work. So what's the right way?

**Comment by beckettsean** [comment]
From https://influxdb.com/docs/v0.9/query_language/data_exploration.

"Return data where the tag key location has no tag value:

`> SELECT * FROM h2o_feet WHERE location !~ /.*/`"

**Comment by airyland** [comment]
thx. `https://influxdb.com/docs/v0.9/query_language/data_exploration.html`

**Comment by robertsLando** [comment]
UPDATE Influx 1.5.

To query values where tag value is null use:

`SELECT * FROM "h2o_feet" WHERE "location" !~ /./`

Check example here (example 5): https://docs.influxdata.com/influxdb/v1.5/query_language/data_exploration/#examples-14
