### ISSUE TITLE
select cause panic: runtime error: index out of range (tsm1)

### ISSUE THREAD

**Issue by balookrd** [influxdb/influxdb#4496]
2015/10/19 10:52:54 InfluxDB starting, version 0.9.5-nightly-cc54cba, branch master, commit cc54cba87f419c0ad43b0f9c2f77d9a4c41a73ea, built '2015-10-19T04:00:41+0000'
2015/10/19 10:52:54 Go version go1.5.1, GOMAXPROCS set to 2

[query] 2015/10/19 11:39:19 SELECT att_pdp_ctxt - att_deact_pdp_ms FROM "bulkstat_saegw"."default".apn LIMIT 10
panic: runtime error: index out of range

goroutine 998 [running]:
github.com/influxdb/influxdb/influxql.newEchoProcessor.func1(0xc820f8e240, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/influxql/result.go:98 +0x42
github.com/influxdb/influxdb/influxql.newBinaryExprEvaluator.func2(0xc820f8e240, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/influxql/result.go:129 +0xb3
github.com/influxdb/influxdb/tsdb.processForMath(0xc820024038, 0x1, 0x1, 0xc8206bc300, 0xa, 0x10, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/executor.go:1039 +0x44c
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc8213fe180, 0xc8215bc000, 0xa, 0x2710, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/executor.go:923 +0xdb1
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Add(0xc8213fe180, 0xc8215a4000, 0x2710, 0x3000, 0xc820f8e1a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/executor.go:795 +0x474
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc82144cc30, 0xc820f61260)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/executor.go:338 +0xc06
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/executor.go:62 +0xa1

goroutine 1 [chan receive, 46 minutes]:
main.(*Main).Run(0xc820055f10, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/main.go:96 +0xa39
main.main()
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b

goroutine 17 [syscall, 46 minutes, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 46 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /root/.gvm/gos/go1.5.1/src/os/signal/signal_unix.go:28 +0x37

goroutine 34 [select, 46 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc82008ca00, 0xc8200168a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:578 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:371 +0xc7f

goroutine 8 [IO wait, 46 minutes]:
net.runtime_pollWait(0x7efeed2a6e50, 0x72, 0xc82000e190)
        /root/.gvm/gos/go1.5.1/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82005b330, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82005b330, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82005b2d0, 0x0, 0x7efeeac52000, 0xc820148000)
        /root/.gvm/gos/go1.5.1/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820024160, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820024160, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820132e00, 0x7efeed2a6fd8, 0xc820024160, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:365 +0xafb

goroutine 9 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024168, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc8201440f0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/store.go:2155 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc82005b340)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/net_transport.go:362 +0x79
created by github.com/hashicorp/raft.NewNetworkTransportWithLogger
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/net_transport.go:154 +0x279

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc82009a1c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc82009a1c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc82009a1c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82009a1c0, 0xc82013d720)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 11 [select, 46 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc82009a1c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82009a1c0, 0xc82013d730)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 12 [select, 2 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc82009a1c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82009a1c0, 0xc82013d740)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /tmp/tmp.Zr5dXhOkZV/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 13 [select, 46 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc82000b9f0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/state.go:189 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/state.go:179 +0x1344

goroutine 14 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024170, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc82008c8c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 15 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024178, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc82008c8c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 35 [select]:
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc820088620)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/monitor/service.go:359 +0x1017
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/monitor/service.go:138 +0x349

goroutine 47 [select, 46 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc82008b9a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:164 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:94 +0x259

goroutine 45 [select, 2 minutes]:
github.com/influxdb/influxdb/tsdb.(*Store).periodicMaintenance(0xc82008c780)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/store.go:320 +0x11c
created by github.com/influxdb/influxdb/tsdb.(*Store).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/store.go:375 +0x3b7

goroutine 46 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc82008b9a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:136 +0x37e
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:93 +0x237

goroutine 48 [select, 46 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).deleteInactiveQueues(0xc82008b9a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:181 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/hh/service.go:95 +0x27b

goroutine 49 [chan receive]:
github.com/influxdb/influxdb/services/subscriber.(*Service).writePoints(0xc820016a80)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/subscriber/service.go:201 +0xac
created by github.com/influxdb/influxdb/services/subscriber.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/subscriber/service.go:76 +0x13f

goroutine 977 [chan receive]:
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc820091100, 0x7efeeac7c800, 0xc82126e500, 0xc8208f40e0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:286 +0xc2c
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveQuery)-fm(0x7efeeac7c800, 0xc82126e500, 0xc8208f40e0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:98 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0x7efeeac7c800, 0xc82126e500, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:673 +0x70
net/http.HandlerFunc.ServeHTTP(0xc82013e3c0, 0x7efeeac7c800, 0xc82126e500, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:734 +0x2af
net/http.HandlerFunc.ServeHTTP(0xc82013e3e0, 0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:743 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc82013e400, 0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:776 +0x328
net/http.HandlerFunc.ServeHTTP(0xc82013e420, 0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:786 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc82013e440, 0x7efeeac7c728, 0xc82126e440, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0x7efeeac7c728, 0xc82126e420, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:794 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc82013e460, 0x7efeeac7c728, 0xc82126e420, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0x7efeeac7c6f0, 0xc8203a0210, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:813 +0x168
net/http.HandlerFunc.ServeHTTP(0xc82013e480, 0x7efeeac7c6f0, 0xc8203a0210, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc820024110, 0x7efeeac7c6f0, 0xc8203a0210, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc820091100, 0x7efeeac7c6f0, 0xc8203a0210, 0xc8208f40e0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/handler.go:172 +0x357
net/http.serverHandler.ServeHTTP(0xc820017f20, 0x7efeeac7c6f0, 0xc8203a0210, 0xc8208f40e0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc820096580)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1910 +0x3f6

goroutine 51 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024180, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc82005b180)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cluster/service.go:98 +0xdb
created by github.com/influxdb/influxdb/cluster.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cluster/service.go:75 +0x135

goroutine 52 [select, 8 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc820132940)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x44f
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x21f

goroutine 53 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024188, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc82000b310)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xa9
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x130

goroutine 54 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820024190, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/copier.(*Service).serve(0xc8201329c0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/copier/service.go:78 +0xa9
created by github.com/influxdb/influxdb/services/copier.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/copier/service.go:51 +0x130

goroutine 55 [IO wait, 46 minutes]:
net.runtime_pollWait(0x7efeed2a6d90, 0x72, 0xc82000e190)
        /root/.gvm/gos/go1.5.1/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc821181480, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821181480, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc821181420, 0x0, 0x7efeeac52000, 0xc820236ba0)
        /root/.gvm/gos/go1.5.1/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820024200, 0x455640, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820024200, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820371da0, 0x7efeed2a6fd8, 0xc820024200, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7efeed2a6fd8, 0xc820024200, 0x7efeed2cee00, 0xc821164560, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc82000b400)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x12f
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x491

goroutine 56 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc820091080)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:184 +0x55f
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:118 +0x255

goroutine 57 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7efeed2a6cd0, 0x72, 0xc82000e190)
        /root/.gvm/gos/go1.5.1/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8211814f0, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8211814f0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc821181490, 0x0, 0x7efeeac52000, 0xc82121a520)
        /root/.gvm/gos/go1.5.1/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820024208, 0xc82055adc0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820024208, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820017f20, 0x7efeed2a6fd8, 0xc820024208, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7efeed2a6fd8, 0xc820024208, 0x7efeeac77118, 0xc820091100, 0x0, 0x0)
        /root/.gvm/gos/go1.5.1/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc820016d80)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/service.go:133 +0x6e
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/httpd/service.go:101 +0x6ca

goroutine 58 [select, 18 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc82000b590)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x351
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b4

goroutine 59 [select, 18 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc82000b590)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x7a0
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x1d9

goroutine 60 [chan receive, 46 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc82008ca00)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:476 +0x1ee
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:403 +0x13c0

goroutine 61 [select, 46 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc8200805a0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:145 +0x2c8
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:127 +0xf97

goroutine 62 [select, 46 minutes, locked to thread]:
runtime.gopark(0xd9e0f0, 0xc8213d2728, 0xc49470, 0x6, 0x18, 0x2)
        /root/.gvm/gos/go1.5.1/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc8213d2728, 0x0, 0x18)
        /root/.gvm/gos/go1.5.1/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc8213d2728)
        /root/.gvm/gos/go1.5.1/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /root/.gvm/gos/go1.5.1/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /root/.gvm/gos/go1.5.1/src/runtime/asm_amd64.s:1696 +0x1

goroutine 997 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeStatement(0xc82005b110, 0x0, 0x7efeeac7d1c8, 0xc8213fe0c0, 0xc8201880ec, 0x9, 0xc820f61140, 0x2710, 0x0, 0x0)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/query_executor.go:688 +0x14a
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc82126e620, 0xc8201880ec, 0x9, 0xc82005b110, 0xc820f61140, 0x2710)
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/query_executor.go:173 +0x933
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /tmp/tmp.Zr5dXhOkZV/src/github.com/influxdb/influxdb/tsdb/query_executor.go:230 +0x9b

**Comment by pfennema** [comment]
If I do a SELECT with 2 fields substracted from each other I get the same index out of range error. Applies to  version 0.9.4.2 as well.

**Comment by otoolep** [comment]
Dupe https://github.com/influxdb/influxdb/issues/4046
