### ISSUE TITLE
Ensure DATABASE RENAME works across restarts

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4503]
Need to ensure https://github.com/influxdb/influxdb/pull/4291 works across restarts.

cc @dgnorton

**Comment by dgnorton** [comment]
Two potential problems:
* Not all OSes support renaming files / directories while they're open.  E.g., this works on Linux but not on Windows... https://gist.github.com/dgnorton/c338407b750af0c983df
* Multiple things need to be renamed (raft meta data, `data/mydb`, `hh/mydb`, `wal/mydb`), which could lead to corruption if an interruption occurs in the middle of renaming.

**Comment by DanielMorsing** [comment]
We have the database name encoded in so many places where we construct paths that I don't think we can reliably update the name at runtime without missing something.

We could rename at startup, but that becomes difficult when you have more than one rename per process run. You then have to keep track of every rename until the process is restarted, which could be a while.

Another way to do this is to generate a Unique ID every time a database is created and having a map from name to UID persisted to disk. That way, you don't have to worry about moving files that are open. It does lose the property of database name as a directory though.

**Comment by dgnorton** [comment]
We've decided to revert database renaming from 0.9.5.  It may be added in a later release if the issues above can be addressed.  https://github.com/influxdb/influxdb/pull/4512

**Comment by beckettsean** [comment]
We could use symlinks as the friendly directory name, with the db id being the actual hard link.

**Comment by linearb** [comment]
The symlink suggestion looks like it would work. 

Using db id as actual hard link might be more robust. But less impactfully
could continue to use (initial) db name as directory name, adding symlinks when db name changes.
(Although this would come with a restriction of not being able to reuse db names on a process run
after renaming.) Could also tidy up on restart, removing symlinks and renaming directories.
