### ISSUE TITLE
The latest version does not startup after upgrade from 0.8.8 to 0.9.4.2

### ISSUE THREAD

**Issue by yonger1516** [influxdb/influxdb#4509]
I get the latest package and install directly on the machine with previous version.
Then I restart the service,and connect the server with CLI tool and it gives me these message back:

Connected to http://localhost:8086 version InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
InfluxDB shell 0.9.4.2

Also, command can't be execute successful in this shell.

**Comment by yonger1516** [comment]
Even I change the soft link of the current dir by manual:

[root@test201 /opt/influxdb]$ ll
total 8
lrwxrwxrwx. 1 root     root       30 Oct 20 11:29 current -> /opt/influxdb/versions/0.9.4.2
lrwxrwxrwx. 1 root     root       37 Oct 20 11:20 influx -> /opt/influxdb/versions/0.9.4.2/influx
lrwxrwxrwx. 1 root     root       38 Oct 20 11:20 influxd -> /opt/influxdb/versions/0.9.4.2/influxd
lrwxrwxrwx. 1 root     root       46 Oct 20 11:20 init.sh -> /opt/influxdb/versions/0.9.4.2/scripts/init.sh
drwxr-xr-x. 3 influxdb influxdb 4096 Oct 20 00:03 shared
drwxr-xr-x. 4 influxdb influxdb 4096 Oct 20 11:20 versions

**Comment by gunnaraasen** [comment]
@yonger1516 Due to the [large differences between InfluxDB versions 0.8 and 0.9](https://influxdb.com/docs/v0.9/concepts/08_vs_09.html), existing 0.8 databases need to be [migrated to version 0.9](https://github.com/influxdb/influxdb/blob/master/importer/README.md).
