### ISSUE TITLE
Memory and CPU usage definition

### ISSUE THREAD

**Issue by mboussaa** [influxdb/influxdb#4510]
cadvisor container export resource usage data to influxDB. Among the metrics that he is exporting there is: memory_usage, cpu_cumulative_usage, among others...

How can you define the memory usage metric provided by google cadvisor? Is it dynamic stack size, heap requirement, cache misses, code size, swap memory or RAM memory? 

as well for cpu cumulative usage, in which measure unit it is calculated? How can you define it? Is there any documentation on that ?

**Comment by beckettsean** [comment]
@mboussaa why is this a question for InfluxDB instead of cadvisor? Are the memory numbers coming from telegraf or another InfluxData product?

**Comment by otoolep** [comment]
I think we can close this, nothing to here.
