### ISSUE TITLE
How to store strings

### ISSUE THREAD

**Issue by mattdlh** [influxdb/influxdb#4519]
Is there a way to store text values in influxdb?

If not, please consider my use case: I need to store a list of device names grouped by some tag value. What is the best way to store and retrieve these names (which are strings)?

Thank you!

**Comment by otoolep** [comment]
Text values are supported natively by InfluxDB, as both fields and tag values.

Be sure to check out the extensive documentation.

https://influxdb.com/docs/v0.9/introduction/overview.html

**Comment by otoolep** [comment]
For example:

```
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server02 value="my string"'
```

to write a string value using the HTTP API to a local node.

**Comment by mattdlh** [comment]
Ah, I was trying the API but did not know that the field could only use one type of value (string or int). If I am interpreting the following error correctly:

```
time			key	test	value
2015-10-21T04:30:38Z	test9	test	h

> INSERT int1,key=test0,test=test value=1 1445401838000000000
ERR: write failed: field type conflict: input field "value" on measurement "int1" is type float64, already exists as type string
```

**Comment by otoolep** [comment]
You are interpreting it correctly. First type in wins.

**Comment by Gopalvenu** [comment]
Hi ,
Error:

"influxdb.exceptions.InfluxDBClientError: 400: {"error":"field type conflict: input field \"cpu_usage\" on measurement \"custom_usage\" is type float64, already exists as type integer"}"

How to resolve this error?

Thanks,
Gopal

**Comment by biker73** [comment]
Not sure you solved this but you will need to remove the measurement and recreate with a set of values that specify the data types of the fields (like in a SQL db you have a column int and you are trying to write type float).  If you try to write to these fields with a different data type than they were created with (same tag keys and thus existing measurement and series) you will get a conflict which is what you have. There may be a way to remove an individual individual field and recreate but that would be in the documentation if it's possible.

**Comment by beakos** [comment]
> Hi ,
> Error:
> 
> "influxdb.exceptions.InfluxDBClientError: 400: {"error":"field type conflict: input field "cpu_usage" on measurement "custom_usage" is type float64, already exists as type integer"}"
> 
> How to resolve this error?
> 
> Thanks,
> Gopal

Just drop the measurement and try again

> drop measurement custom_usage
