### ISSUE TITLE
Writes using the Line protocol

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4520]
Hi, 

If I have a batch of 4,000 datapoints and (due to a syntax error)  2 of those points fail to write, will the other 3,998 rows be stored? 

The reason I ask is I am trying to handle the situation where sometimes I get a 500 error (too busy back off) and sometimes I get a syntax error due to the shape of my data and I wish to handle the cases differently. 

Ivan

**Comment by beckettsean** [comment]
@ivanscattergood currently the entire batch fails if any individual points fail.
