### ISSUE TITLE
Number of Tag sets in a measurement

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4522]
From https://influxdb.com/docs/v0.9/concepts/glossary.html
>The total number of series under a given measurement is thus identical to the number of distinct tag sets applied to points within that measurement.

Is query that tells you the number of distinct tag sets applied to points in a measurement?

**Comment by beckettsean** [comment]
`SELECT * FROM measurement GROUP BY * LIMIT 1` will return one point from every distinct series in the measurement. The `tags` value in the return shows the full tag set for each series.

Note that if you have a lot of points in the measurement this an expensive query. `LIMIT` is due for some refactoring. It takes about the same amount of time as `SELECT count(value) FROM measurement`

**Comment by ivanscattergood** [comment]
Thanks,  unfortunately that query takes too long to return.

I'll have to do my own calculations for the moment

Keep up the good work :-)


---- Sean Beckett wrote ----


SELECT * FROM measurement GROUP BY * LIMIT 1 will return one point from every distinct series in the measurement. The tags value in the return shows the full tag set for each series.

Note that if you have a lot of points in the measurement this an expensive query. LIMIT is due for some refactoring. It takes about the same amount of time as SELECT count(value) FROM measurement

-
