### ISSUE TITLE
[0.9.5-nightly] trivial bug: USER can parse as USE in the CLI

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#4544]
```
> user _internal
Using database _internal
> use _internal
Using database _internal
> 
```

**Comment by beckettsean** [comment]
I would expect a parser error instead of it "knowing" that I meant `use` and not `user`

**Comment by otoolep** [comment]
The command parsing in the CLI code needs to be a little bit more sophisticated to solve this issue. Ideally the CLI code would parse tokens, allowing more intelligent behaviour.

**Comment by otoolep** [comment]
Some initial work is here: https://github.com/influxdb/influxdb/pull/4588/files

But the tests don't pass, so the CLI needs some more work to fix this bug.

**Comment by pires** [comment]
While working on #4628 I had a similar idea, so on it :)
