### ISSUE TITLE
Downsample downsampled data

### ISSUE THREAD

**Issue by benidroe** [influxdb/influxdb#4546]
I have one more question:

I need this downsampling:

1 day -> RAW
7 days -> average 5min
1 year -> average 30min

Now I know from your documentation, that I can make a continious query to downsample the data from 1 day to 7 days. 

How can I use a rentention policy, that the 7 days data is deleted after 7 days? Is there a way to define this in my CQ? Or is there a way to add a RP to the 7 days measurement?

Can you please make me a example? I didn´t found how to do this in the docs.

**Comment by beckettsean** [comment]
Docs are forthcoming soon, but when you make your CQ you can explicitly declare the target database, retention policy, and measurement for the aggregated data.

```
CREATE CONTINUOUS QUERY foo ON mydb BEGIN
   SELECT MEAN(value) INTO database.retention_policy.measurement FROM database.retention_policy.measurement GROUP BY time(5m)
END
```

If you want to sample from the `alice` measurement in the `raw` retention policy and write into the `bob` measurement in the `seven_day` policy, all in `mydb` database, it would look like this:

```
CREATE CONTINUOUS QUERY foo ON mydb BEGIN
   SELECT MEAN(value) INTO seven_day.bob FROM raw.alice GROUP BY time(5m)
END
```

**Comment by benidroe** [comment]
I´ve tried this cq to downsample all the data from my switchports.

 CREATE CONTINUOUS QUERY onedaycq ON monitoring BEGIN
 SELECT 
 MEAN(ifInOctets) AS ifInOctets, 
 MEAN(ifOutOctets) AS ifOutOctets,
 MEAN(ifInNUcastPkts) as ifInNUcastPkts, 
 MEAN(ifOutNUcastPkts) as ifOutNUcastPkts,
 MAX(ifInErrors) as IfInErrors, 
 MAX(ifOutErrors) as ifOutErrors, 
 MAX(ifInDiscards) as ifInDiscards, 
 MAX(ifOutDiscards) as ifOutDiscards 
 INTO onemonth.Switches FROM Switches GROUP BY switch, port, time(5m), * 
 END

But it doesn´t work. It writes random portnumbers.

**Comment by beckettsean** [comment]
@benidroe I recommend testing the query as a normal ad hoc query first. Are the results of 

```
SELECT 
MEAN(ifInOctets) AS ifInOctets, 
MEAN(ifOutOctets) AS ifOutOctets,
MEAN(ifInNUcastPkts) as ifInNUcastPkts, 
MEAN(ifOutNUcastPkts) as ifOutNUcastPkts,
MAX(ifInErrors) as IfInErrors, 
MAX(ifOutErrors) as ifOutErrors, 
MAX(ifInDiscards) as ifInDiscards, 
MAX(ifOutDiscards) as ifOutDiscards 
FROM Switches GROUP BY switch, port, time(5m), * 
```

what you expect them to be?

Also, why are you using a `GROUP BY` clause with both the explicit group by tags and also a `GROUP BY *`?  `GROUP BY *` means group by every tag, so supplying the other two tags is at best unnecessary and might be the source of the issue.
