### ISSUE TITLE
My web interface is different from all images I found about InfluxDB

### ISSUE THREAD

**Issue by Tak-MK** [influxdb/influxdb#4549]
Also, clicking on the gear lets me to put login credentials (with a visible password), but it doesn't matter; always connect.

My web:
![Mine](https://i.imgur.com/wI808LB.png)

Other screenshots:
![Other](https://assets.digitalocean.com/articles/influxdb/CPrvI85.png)

Because of that, I can't continue with any tutorial I found, because they say things like "In the top menu on the next page, click on Cluster Admins.", but obviously I don't have that option (or any other).

Example tutorial --> https://www.digitalocean.com/community/tutorials/how-to-analyze-system-metrics-with-influxdb-on-centos-7

How to reproduce (at least in my case):
* Install the deb or rpm (I've tried on a Amazon EC2 (rpm) and on my working laptop (deb).
I've tried versions 0.8.8 and 0.9.4.
* Go to http://IP:8083/

What's happening? How can I solve this?

Thanks a lot!

**Comment by airyland** [comment]
since 0.9, the web UI has changed, so what you saw is the right version and the tutorial is too old..

**Comment by Tak-MK** [comment]
But when I installed v0.8.8 I got the same web UI :/ Not the old interface.

**Comment by toddboom** [comment]
@Tak-MK It sounds like either a) your browser is caching the old page or b) the 0.9.x version is still running somewhere and serving up the pages. The admin UI is statically compiled into the binaries, so it's unlikely that you're actually getting the new version of the UI served up by the old binary.

**Comment by beckettsean** [comment]
@Tak-MK that is an 0.8 Admin UI page in your screenshot. It can only come from an 0.8 instance.

The tutorial to which you link was built using InfluxDB 0.8. The Admin UI is [substantially different](https://influxdb.com/docs/v0.9/concepts/08_vs_09.html#admin-ui) in InfluxDB 0.9, as all administrative functions have been moved into simple query commands.

> Also, clicking on the gear lets me to put login credentials (with a visible password), but it doesn't matter; always connect.

Authentication is [disabled by default](https://influxdb.com/docs/v0.9/administration/authentication_and_authorization.html#authentication) in InfluxDB 0.9, so if you haven't enabled it, it's not running.

> Because of that, I can't continue with any tutorial I found, because they say things like "In the top menu on the next page, click on Cluster Admins.", but obviously I don't have that option (or any other).

You cannot use any documentation for InfluxDB 0.8 with InfluxDB 0.9 and vice versa. The two are quite [different in many ways](https://influxdb.com/docs/v0.9/concepts/08_vs_09.html).

**Comment by Tak-MK** [comment]
I see... thanks a lot! :D
