### ISSUE TITLE
Revert ability to select engine via env variable

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4558]
This is dangerous functionality so will be removed once tsm1 is shipped. Right now it's the easiest way to ensure that some CI testing takes place against tsm1.

**Comment by otoolep** [comment]
This functionality already exists, so consider simply reverting the log message when tsm1 ships.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/pull/4557

**Comment by otoolep** [comment]
The Circle CI container count can also be reduced to 3.

**Comment by pauldix** [comment]
0.10.0 will ship with only one engine so this doesn't need to be reverted
