### ISSUE TITLE
unable to run select queries

### ISSUE THREAD

**Issue by priyadarsh** [influxdb/influxdb#4561]
I am unable to run select queries while writes are happening fine. I tried on both web UI and CLI.

Build no. 0.9.5-nightly-827c513

> show measurements
ERR: json: cannot unmarshal array into Go value of type tsdb.MapperOutputJSON

![web-ui](https://cloud.githubusercontent.com/assets/5320320/10709804/812fe7e8-7a59-11e5-9f36-a7bfe23ebb5e.png)

**Comment by otoolep** [comment]
Looks like a dupe of https://github.com/influxdb/influxdb/issues/4561

**Comment by otoolep** [comment]
I mean https://github.com/influxdb/influxdb/issues/4550
