### ISSUE TITLE
Too many open file on client

### ISSUE THREAD

**Issue by sergeylanzman** [influxdb/influxdb#4569]
I do monitoring data.
I have a long running code and samples data and sends them to influxdb.
To save data in influxdb I that users of this code.
```
func sendToInfluxDB(s Store, data Metric) {
	u, _ := url.Parse(s.Address)
	c := client.NewClient(client.Config{
		URL:      u,
		Username: s.Username,
		Password: s.Password,
	})

	// Create a new point batch
	bp, _ := client.NewBatchPoints(client.BatchPointsConfig{
		Database:  s.Database,
		Precision: "s",
	})

	// Create a point and add to batch
	tags := map[string]string{string(data.Name): string(data.Name)}
	fields := map[string]interface{}{
		string(data.Name): data.Value,
	}
	pt := client.NewPoint(string(data.Name), tags, fields, time.Now())
	bp.AddPoint(pt)

	// Write the batch
	c.Write(bp)
}
```
Function calls 20 times a minute. After a few hours I get an error that too many files open on client.
```
netstat -n | grep "192.168.23.215:8086     ESTABLISHED" | wc
    443    2658   35440
```
I saw a client code as close connection end.
What could be wrong?

**Comment by jwilder** [comment]
I believe you need to re-use your client between calls.  Internally the client uses an `http.Client` that pools  connections so if you create a new one each time, the old connections will live on for a while.

**Comment by otoolep** [comment]
+1, this probably the issue, I think we can close this.

@sergeylanzman -- please re-open if you still have issues after changing your code.

**Comment by sergeylanzman** [comment]
I use several different bases and therefore more comfortable to use a function that accepts data settings and then sends it to InfluxDB. This is not always true to reuse the same client. For me it creates problems after they discover them.
I did added a solution DisableKeepAlives true.
Recommend add this setting or do NewClientWithHttpClient so that everyone can give http.client but he wants.
I already have a ready source can do pull request.
What's more correct?

**Comment by otoolep** [comment]
The second option is already being developed here: https://github.com/influxdb/influxdb/pull/4598
