### ISSUE TITLE
InfluxDB 0.9.4.2: What's the exact sql to query the last absolute hour data in InfluxDB?

### ISSUE THREAD

**Issue by VincentAtC** [influxdb/influxdb#4572]
For example,
Now is 2015-10-26 10:10:00
The expect period is from 2015-10-26 09:00:00 to 2015-10-26 10:00:00

Thanks,
Vincent

**Comment by beckettsean** [comment]
This is neither a bug nor a feature request. Please send questions to the mailing list, influxdb@googlegroups.com

The answer is that if you want an exact time range you must specify absolute time ranges. For example, `SELECT * FROM foo WHERE time >= '2015-10-26 09:00:00' and time <= '2015-10-26 10:00:00'`
