### ISSUE TITLE
[0.9.5-nightly] Continuous queries for downsampling not preserving meta tags

### ISSUE THREAD

**Issue by priyadarsh** [influxdb/influxdb#4579]
CREATE CONTINUOUS QUERY book_response_counts_hourly on mydb BEGIN
SELECT count(responsetime) INTO hourly_roll_up_book FROM "book" GROUP BY time(1h), *
END

Build 0.9.5-nightly-827c513

I have created a down sampling continuous query as above. I wanted to preserve all the meta tags. But when this query executes I see only one record with time as "1970-01-01T00:00:00Z" and some random meta tag values with count field. Am I missing something here?

**Comment by beckettsean** [comment]
@priyadarsh can you give an example of the output from both `SELECT * FROM hourly_roll_up_book WHERE time > now() - 6h` and also `SELECT count(responsetime) FROM "book" WHERE time > now() -6h GROUP BY time(1h), *`

**Comment by beckettsean** [comment]
@priyadarsh are you using the `bz1` engine or the `tsm1` engine?

**Comment by priyadarsh** [comment]
@beckettsean I am using tsm1 engine. I recreated all the continuous again and it seems to be working fine now. Not sure what happened then. You may close this for now. If I face this again I will provide the mentioned data and open the issue again. Sorry for the trouble.

**Comment by beckettsean** [comment]
Thanks for the update, @priyadarsh. Closing the ticket until it recurs.
