### ISSUE TITLE
RESTful API returns 204 but data not got persistent

### ISSUE THREAD

**Issue by WayneYe** [influxdb/influxdb#4581]
I have been using v0.9.2 since 3 months ago, it was all running fine, but this morning I noticed that during a period (9 hours), it didn't get my data stored at all, below was the querying result:
```
time				message	response_time	status
----				-------	-------------	------
2015-10-26T07:56:21.617091181Z	Health OK!					0.195014953613	Operational
2015-10-26T07:57:21.608316979Z	Health OK!					0.18492603302	Operational
2015-10-26T07:58:21.657732938Z	Health OK!					0.19704413414	Operational
2015-10-26T07:59:21.573305386Z	Health OK!					0.150962114334	Operational
2015-10-26T08:00:21.595418011Z	Health OK!					0.171375989914	Operational
2015-10-26T08:01:21.562332534Z	Health OK!					0.137006998062	Operational
2015-10-26T08:02:21.579362949Z	Health OK!					0.151744842529	Operational
2015-10-26T08:04:21.540773114Z	Health OK!					0.118921995163	Operational
--------------------------------------------------------------------------------------
2015-10-26T17:34:21.614339219Z	Health OK!					0.196357011795	Operational
2015-10-26T17:35:21.566347776Z	Health OK!					0.145502090454	Operational
2015-10-26T17:36:21.558258173Z	Health OK!					0.138634204865	Operational
2015-10-26T17:37:21.600137489Z	Health OK!					0.176239013672	Operational
2015-10-26T17:38:21.532443997Z	Health OK!					0.106864929199	Operational
2015-10-26T17:39:21.561829901Z	Health OK!					0.136914968491	Operational
2015-10-26T17:40:21.569315704Z	Health OK!					0.144639015198	Operational
2015-10-26T17:41:21.587080861Z	Health OK!					0.159435987473	Operational
```
The dash-line "---" was added by me to highlight the missing part, I checked into the influxdb.log (`/var/log/influxdb/influxd.log`), got the following output:

```
[shard] 2015/10/26 17:33:54 flush 2 points in 0.002s
[http] 2015/10/26 17:33:55 52.21.89.215 - - [26/Oct/2015:17:33:55 +0000] POST /write?db=hds HTTP/1.1 204 0 - python-requests/2.7.0 CPython/2.7.10 Linux/2.6.32-504.12.2.el6.x86_64 bb7208d0-7c07-11e5-98fd-000000000000 1.878416ms
[shard] 2015/10/26 17:33:56 flush 2 points in 0.003s
[http] 2015/10/26 17:33:58 52.23.239.242 - - [26/Oct/2015:17:33:58 +0000] POST /write?db=hds HTTP/1.1 204 0 - python-requests/2.7.0 CPython/2.7.10 Linux/2.6.32-573.3.1.el6.x86_64 bd438029-7c07-11e5-98fe-000000000000 2.157747ms
[shard] 2015/10/26 17:33:58 flush 3 points in 0.002s
[shard] 2015/10/26 17:34:00 flush 1 points in 0.002s
[http] 2015/10/26 17:34:01 52.21.89.215 - - [26/Oct/2015:17:34:01 +0000] POST /write?db=hds HTTP/1.1 204 0 - python-requests/2.6.0 CPython/2.6.6 Linux/2.6.32-504.12.2.el6.x86_64 bf23fa77-7c07-11e5-98ff-000000000000 2.164451ms
[shard] 2015/10/26 17:34:02 flush 1 points in 0.002s
[http] 2015/10/26 17:34:04 54.173.121.195 - - [26/Oct/2015:17:34:04 +0000] POST /write?db=hds HTTP/1.1 204 0 - python-requests/2.6.0 CPython/2.6.6 Linux/2.6.32-573.3.1.el6.x86_64 c0bf1a0b-7c07-11e5-9900-000000000000 1.877442ms
[shard] 2015/10/26 17:34:04 flush 22 points in 0.005s
```
So it does return 204 stauts code, however, the data did lost according to my querying, I really have no clew now why during that 9 hours the data were lost.

**Comment by otoolep** [comment]
Until you show us your questions, we can't help you. Perhaps your queries are incorrect? Perhaps you changed the retention policy? 

Please also show us your config file.

**Comment by otoolep** [comment]
Also, 0.9.2 is quite old. You should upgrade to 0.9.4.2, as there have been an enormous number of bug fixes since then.

**Comment by WayneYe** [comment]
@otoolep Thank you so much for the quick reply, my query does not have problem: `SELECT * FROM hds WHERE time > now - 1d`, since as I've mentioned, I've been using 0.9.2 for 3 months, means 3 months of programmatically: )

As My query was simply showing all the points during the past 1 day, and it displayed as I pasted above, there was a clear "gap": from 08AM to 17PM, there were no points at all.

I understand that I provided insufficient information, but what does the "flush x points" mean please? Meaning "Writing/dumping data into hard disk"? Is there any possibilities that my data didn't get stored?

**Comment by otoolep** [comment]
Those messages mean the system is flushing data from the write-ahead-log to the the database. It is perfectly normal. Versions after 0.9.2 include stats and diagnostics, to help debug issues like this. You can just drop in the code and will not lose any data that is data already.

Upgrading will help us help you.

**Comment by WayneYe** [comment]
@otoolep Thanks for the explanation, I realized that this might be the issue in my side, nothing to do with influxDB, I close this issue for now.

Thank you very much again for the help!
