### ISSUE TITLE
[0.9.4.2] - No Raft leader on single node after upgrade

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb#4594]
Hi Team,

Apparently the stats storage are not working, anymore : 

[monitor] 2015/10/28 10:14:30 Storing statistics in database '_internal' retention policy '', at interval 10s
[monitor] 2015/10/28 10:14:31 failed to create database '_internal', terminating storage: rpc Error failed: no leader

Version:
InfluxDB v0.9.4.2 (git: 0.9.4 da1b59e7d7764d36786253b2db13b97f42ed4e1d)

Is there something planned to fix it ?

Julien.

**Comment by rossmcdonald** [comment]
Is this a brand new installation, or was this from an upgrade? And are you running a single-node setup (not clustered)? 

Also does the same error occur every time you attempt to start the service?

**Comment by JulienChampseix** [comment]
The upgrade was done this morning from 0.9.4.1 to 0.9.4.2.
Mode : Single-node setup
Yes the error appear every time i start the service. (tested to restart it several times for be sure and same result no stats available).
After that , i tested also to remove the _internal database due maybe corruption inside the database but nothing changed (note: the _internal was not recreated also at the restart if the database dont exist), so i recreated manually but nothing changed still no stats.

**Comment by otoolep** [comment]
Whatever is going is not specific to the internal database. The underlying node has got into a bad state and has no leader. I'd be surprised if anything works.

We have had no other reports of issues in this area. Something obviously happened during upgrade, or we don't have the full picture here.

**Comment by otoolep** [comment]
Even with a single node, there is a Raft leader.

**Comment by JulienChampseix** [comment]
Upgrade process was : 
1. service influxdb stop
2. dpkg -i influxdb_0.9.4.2_amd64.deb
3. service influxdb start

So nothing special during the upgrade.

More details when i start the service : 
`
2015/10/28 19:04:31 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/10/28 19:04:31 Go version go1.5, GOMAXPROCS set to 12
2015/10/28 19:04:31 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/10/28 19:04:31 Using data dir: /data/influxdb/meta
[metastore] 2015/10/28 19:04:31 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/10/28 19:04:31 Node at localhost:8088 [Follower]
[metastore] 2015/10/28 19:04:33 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/10/28 19:04:33 Node at localhost:8088 [Follower]. peers=[localhost:8088]
[monitor] 2015/10/28 19:04:33 Starting monitor system
[monitor] 2015/10/28 19:04:33 'build' registered for diagnostics monitoring
[monitor] 2015/10/28 19:04:33 'runtime' registered for diagnostics monitoring
[monitor] 2015/10/28 19:04:33 'network' registered for diagnostics monitoring
[monitor] 2015/10/28 19:04:33 'system' registered for diagnostics monitoring
[store] 2015/10/28 19:04:33 Using data dir: /data/influxdb/data
[metastore] 2015/10/28 19:04:33 Updated node id=1 hostname=localhost:8088
[monitor] 2015/10/28 19:04:33 Storing statistics in database '_internal' retention policy '', at interval 10s
[metastore] 2015/10/28 19:04:35 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[monitor] 2015/10/28 19:04:35 failed to create retention policy 'monitor', terminating storage: rpc Error failed: no leader
`

**Comment by otoolep** [comment]
OK, it's quite strange.

However, it may be a transient issue, and the handling of those issues was improved significantly in master. If you can, I suggest you upgrade to a nightly, which should address the issues related to stats storage.

**Comment by JulienChampseix** [comment]
is the nightly build is 0.9.5 ? is it pretty stable or planned to be released stable soon ?

**Comment by otoolep** [comment]
Yes, the nightly is from the planned 0.9.5 release.

https://influxdb.com/download/index.html#

Our internal testing shows the nightly to be generally much improved relative to 0.9.4.2, due to the large number of bug fixes in place. But it isn't an official release yet, so you should be cautious.

**Comment by JulienChampseix** [comment]
Something is strange, if i check the monitor section in my config i have this config (/etc/opt/influxdb/influxdb.conf) : 

###
### Controls the system self-monitoring, statistics and diagnostics.
###

[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "_internal" # The destination database for recorded statistics
  store-retention-policy = "monitor" # The destination retention policy
  store-retention-duration = "168h" # How long to keep the data
  store-replication-factor = 1 # How many copies of the data to keep
  store-interval = "10s" # The interval at which to record statistics


When i restart my service influxdb, i got that:

It look like only the monitor dont works, regarding a fresh restart of influxdb : 
>
2015/10/29 12:23:06 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/10/29 12:23:06 Go version go1.5, GOMAXPROCS set to 12
2015/10/29 12:23:06 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/10/29 12:23:06 Using data dir: /data/influxdb/meta
[metastore] 2015/10/29 12:23:06 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/10/29 12:23:06 Node at localhost:8088 [Follower]
[metastore] 2015/10/29 12:23:08 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/10/29 12:23:08 Node at localhost:8088 [Follower]. peers=[localhost:8088]
[monitor] 2015/10/29 12:23:08 Starting monitor system
[monitor] 2015/10/29 12:23:08 'build' registered for diagnostics monitoring
[monitor] 2015/10/29 12:23:08 'runtime' registered for diagnostics monitoring
[monitor] 2015/10/29 12:23:08 'network' registered for diagnostics monitoring
[monitor] 2015/10/29 12:23:08 'system' registered for diagnostics monitoring
[store] 2015/10/29 12:23:08 Using data dir: /data/influxdb/data
[metastore] 2015/10/29 12:23:08 Updated node id=1 hostname=localhost:8088
[monitor] 2015/10/29 12:23:08 Storing statistics in database '_internal' retention policy '', at interval 10s
[metastore] 2015/10/29 12:23:08 No leader
[monitor] 2015/10/29 12:23:08 ''' failed to set default retention policy on '_internal' ''', terminating storage: read response size: read tcp 127.0.0.1:46518->127.0.0.1:8088: read: connection reset by peer
[metastore] 2015/10/29 12:23:09 Node at localhost:8088 [Leader]. peers=[localhost:8088]
>

It look like it dont use information present into the [monitor] section, it dont take the retention policy regarding log from start : 
> 
[monitor] 2015/10/29 12:23:08 Storing statistics in database '_internal' retention policy '', at interval 10s
>
it should use policy 'monitor' not '', isnt it ?

If i run 'show stats' in my cli it's working so here the issue looks like around monitor.

**Comment by otoolep** [comment]
store-retention-policy = "monitor" # The destination retention policy
store-retention-duration = "168h" # How long to keep the data
store-replication-factor = 1 # How many copies of the data to keep

https://github.com/influxdb/influxdb/blob/0.9.4/monitor/config.go

Where did you get these? They have never been supported.

Philip

**Comment by JulienChampseix** [comment]
Dunno was provided over influxdb release (never touched this section, it's the default i have)

I'll try 0.9.5 night build. From a single-node setup, is it possile to move to cluster mode ? or what the best way to do that ? (Using 0.9.5 night build)

**Comment by jgerschk** [comment]
@otoolep  you mention above no other reports of this, well today after doing a stop and start of the influxdb service, I am in the same boat here.

We have stopped and started this service many times, but today, it won't start....

This is it from the logs....


[wal] 2015/11/02 16:48:24 reading WAL files to flush to index
[wal] 2015/11/02 16:48:24 writing 24873 series from WAL file /opt/influxdb/wal/checkmk/sixmonths/108/01.000691.wal to index
[metastore] 2015/11/02 16:48:24 unable to write rpc response: write tcp [::1]:8088->[::1]:51767: use of closed network connection
[metastore] 2015/11/02 16:48:24 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[monitor] 2015/11/02 16:48:24 failed to create database '_internal', terminating storage: rpc Error failed: no leader


We've been on this version for sometime, it was not a recent upgrade either.

version = 0.9.4.1

**Comment by jgerschk** [comment]
After a reboot of the server, and several stop start attempts it does seem to be moving along trying to start now -- at least it's processing series from WAL at this time....

**Comment by otoolep** [comment]
All these errors are addressed in master, so there is nothing more to do here.
