### ISSUE TITLE
query results in `runtime error: slice bounds out of range`

### ISSUE THREAD

**Issue by bwhaley** [influxdb/influxdb#4603]
Running a query resulted in this panic. `0.9.5-nightly-2fe5e6b` [Stack trace here.](https://gist.github.com/bwhaley/50e2e73c33a5b417bae0)

**Comment by jwilder** [comment]
Looks like the `tsm1` cursor is accessing the `dataFile` mmaps without acquiring a lock.  Fixed some similar issues like this today in #4608.

**Comment by bwhaley** [comment]
Updated to the latest nightly, will report back if I encounter this again.

**Comment by ryan-williams** [comment]
I just saw this using `tsm1` on a nightly build from 905437cc5aa179901ece90a99bd991c825129362, which seems to have #4608.

[This gist](https://gist.github.com/ryan-williams/cabf4dd06d9a63756348) has my conf file and stack trace.

**Comment by ryan-williams** [comment]
Update: I think the above was actually a source build from 3821872129a2cc575140b58bd0fb15885968674a, which also should have #4608.

I'll run again with a more recent source build from `HEAD` and see if I see it again.

**Comment by jwilder** [comment]
Should be fixed in `0.9.6` release.
