### ISSUE TITLE
 WAL backed up flushing to index, hit max memory

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4609]
Hi, 

Is there a way I can tune the WAL to stop the following error occurring: 

**WAL backed up flushing to index, hit max memory**

I am writing about 6,000 points per second, due to the hardware I am running on I am limited on memory (16GB)

**Comment by daviesalex** [comment]
We see this with 0.0.5 under load with or without clustering and have reported it a few times, e.g.  https://github.com/influxdb/influxdb/issues/4552

I understand from @pauldix that there are some tsm1 changes due this week that may fix this.

**Comment by otoolep** [comment]
Unless @ivanscattergood reports otherwise I assume the report is about the bz1 engine. But nothing will be changing that can effect the bz1 engine since we are only focusing on tsm1.

**Comment by otoolep** [comment]
The tsm1 engines changes in the works will not alleviate this condition. The only thing to do it to back-off on the load.

**Comment by otoolep** [comment]
@ivanscattergood -- you may wish to try out the experimental tsm1 engine, but keep in mind you will need to wipe your database between upgrades until 0.9.5 is released.

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L52

**Comment by ivanscattergood** [comment]
If this message is the equivalent of back off and retry I will treat it as such.

I have now moved to the tsm1 engine and I'm no longer seeing the error.


---- otoolep wrote ----


Unless @ivanscattergood<https://github.com/ivanscattergood> reports otherwise I assume the report is about the bz1 engine. But nothing will be changing that can effect the bz1 engine since we are only focusing on tsm1.

-

**Comment by otoolep** [comment]
Yes @ivanscattergood -- backoff and retry is a good way to think about it.
