### ISSUE TITLE
Point time overwrite?

### ISSUE THREAD

**Issue by emitle** [influxdb/influxdb#4614]
Hi influxdb developers, I have encountered a problem when using influxdb to analyze user event. The measurement (event.btn.click) is used to store user button click event. Tag label represents button name. After the following tests I found out that if two users clicked certain button at the same time, influxdb would overwrite the date of former user when inserting the second user event.

```sql
> insert event.btn.click,category=home,label=push userId="user01",ip="192.168.1.175" 1446122841000000000
```

```sql
> select * from "event.btn.click"
name: event.btn.click
---------------------
time					category	ip				label	userId
2015-10-29T12:47:21Z	home		192.168.1.175	push	user01
```

```sql
> insert event.btn.click,category=home,label=push userId="user02",ip="192.168.1.120" 1446122841000000000
```

```sql
> select * from "event.btn.click"
name: event.btn.click
---------------------
time					category	ip				label	userId
2015-10-29T12:47:21Z	home		192.168.1.120	push	user02
```

```sql
# Aggregate unique clicks of each button
> select count(distinct(userId)) from "event.btn.click" group by label
name: event.btn.click
tags: label=push
time			count
----			-----
1970-01-01T00:00:00Z	1
```

I have googled it, and it seems that it may be caused by influxdb using timestamp+tag as primary key?
So if I change userID to tag, everything will be alright?

```sql
> insert event.btn.click02,category=home,label=push,userId="user01" ip="192.168.1.175" 1446122841000000000
> insert event.btn.click02,category=home,label=push,userId="user02" ip="192.168.1.120" 1446122841000000000
> insert event.btn.click02,category=home,label=edit,userId="user03" ip="192.168.1.121" 1446122841000000000
```

```sql
> select * from "event.btn.click02"
name: event.btn.click02
-----------------------
time					category	ip				label	userId
2015-10-29T12:47:21Z	home		192.168.1.120	push	"user02"
2015-10-29T12:47:21Z	home		192.168.1.175	push	"user01"
2015-10-29T12:47:21Z	home		192.168.1.121	edit	"user03"
```

However, when I aggregate the unique clicks of each button, the data returned is 0

```sql
> select count(distinct(userId)) from "event.btn.click02" group by label
name: event.btn.click02
tags: label=edit
time					count
----					-----
1970-01-01T00:00:00Z	0


name: event.btn.click02
tags: label=push
time					count
----					-----
1970-01-01T00:00:00Z	0
```

What should I do?

**Comment by beckettsean** [comment]
> I have googled it, and it seems that it may be caused by influxdb using timestamp+tag as primary key?

Correct. A point is uniquely identified by the measurement, tag set, and timestamp. If a new point is received with the same measurement, timestamp, and tag set, it will silently overwrite the previous point's fields.

> So if I change userID to tag, everything will be alright?

That will guarantee that each point has a unique tag set, and they will no longer overwrite each other.

> However, when I aggregate the unique clicks of each button, the data returned is 0

The `DISTINCT()` and `COUNT()` functions only operate on fields, not tags. In fact, that query should throw a parser error. I've opened a [new issue](https://github.com/influxdb/influxdb/issues/4618) for that.

> What should I do?

If COUNT and DISTINCT are functions you need to perform on `userId`, then it must be a field. There are a few ways to prevent the duplicate point issue:

1. write `userId` as a field, and write `user_id` or some related but not identical name as a tag. That way the user ID is available for functions, and for uniqueness and `GROUP BY clauses`. It won't significantly increase storage needs, as tags are stored once per series, not per point.
2. keep `userId` exclusively a field, but add some random jitter to the timestamps. You're using 1s precision on the timestamps, which makes timestamp collisions between users much more likely than if they were milli-, micro-, or nanosecond timestamps.

**Comment by yifeikong** [comment]
However, there is a setting called max-values-per-tag, you just can't freely use everything as a tag
