### ISSUE TITLE
[0.9.5] Large timestamps panic openTSDB plugin

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#4622]
Giving openTSDB a point with a timestamp that is more than 13 digits long causes panic. However the database is still up and running.

```json
{
  "metric": "sys.cpu.nice",
  "timestamp": 12345678901234,
  "value": 9,
  "tags": {
    "host": "web02",
    "dc": "lga"
  }
}
```

```
2015/10/29 17:14:05 TSDB listener accept  &{0xc82032e368 0xc8202586c0}
2015/10/29 17:14:05 http: panic serving [::1]:53092: runtime error: invalid memory address or nil pointer dereference
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc82030b8c0, 0xf46de8, 0xc8203f6100)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1287 +0xb5
github.com/influxdb/influxdb/cluster.(*PointsWriter).MapShards(0xc820134240, 0xc82030f980, 0xc82026d000, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:207 +0x70e
github.com/influxdb/influxdb/cluster.(*PointsWriter).WritePoints(0xc820134240, 0xc82030f980, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cluster/points_writer.go:240 +0x1df
github.com/influxdb/influxdb/services/opentsdb.(*Handler).servePut(0xc820108380, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/opentsdb/handler.go:121 +0xb0a
github.com/influxdb/influxdb/services/opentsdb.(*Handler).ServeHTTP(0xc820108380, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/opentsdb/handler.go:36 +0xa5
net/http.serverHandler.ServeHTTP(0xc8202a00c0, 0xf470e0, 0xc82030b970, 0xc82012e700)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc82030b8c0)
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/Users/michaeldesa/.gvm/gos/go1.5.1/src/net/http/server.go:1910 +0x3f6
```

**Comment by otoolep** [comment]
How did you discover this? Are you testing via the HTTP protocol?

**Comment by mjdesa** [comment]
I was looking into how the graphite and openTSDB plugins work for stress. At the moment I've only tested this against the http protocol.

**Comment by otoolep** [comment]
I know @gunnaraasen has been poking around this code recently, so perhaps he'd also like to take a stab at fixing this.

**Comment by gunnaraasen** [comment]
I can take a look this weekend. @mjdesa is the full stack track posted somewhere?

**Comment by mjdesa** [comment]
@gunnaraasen that was the full stack trace. It didn't bring the server down, just caused that panic and kept going.

**Comment by gunnaraasen** [comment]
I see, thanks @mjdesa.

**Comment by nathanielc** [comment]
I looked into this. It is caused by the fact that InfluxDB cannot support time greater than UnixNano int64 can express. Basically during the shard create command the time is serialized via proto buf via this line: https://github.com/influxdb/influxdb/blob/master/meta/store.go#L1232 

Since 12345678901234 is interpreted in microseconds it is the date  `2361-03-19` but with an int64 in nanoseconds the max  and min dates we can express are:

```
2262-04-11 23:47:16.854775807 +0000 UTC
1677-09-21 00:12:43.145224192 +0000 UTC
```

Do we care? We were just testing the API. I'll add a sanity check on the provided timestamps so we don't panic.
