### ISSUE TITLE
Slow query performance

### ISSUE THREAD

**Issue by bwhaley** [influxdb/influxdb#4626]
As per discussion on the mailing list, I'm having trouble with a slow query. To summarize the original problem statement:

```
 $ time influx -database graphitedb -execute "SELECT mean(system) FROM cpu WHERE env='prod' AND time > now() - 6h GROUP BY time(10m)"
name: cpu
---------
time			mean
[snip]
real	0m6.300s
```

> There are 8 fields on the cpu measurement, 5 tags. and 42 matches for env='prod'.
> This similar query takes < 500ms:

```
$ time influx -database graphitedb -execute "SELECT mean(midterm) FROM load WHERE env='prod' AND time > now() - 6h GROUP BY time(10m)"
name: load
----------
time			mean
[snip]
real	0m0.449s
```

> There are only 3 fields on the load measurement and 4 tags.

> Any ideas why one takes so much longer than the other? It's only a 6h window, and if I group by 1m instead of 10m the query takes a minute or more.

`env` is a tag. Both `load` and `cpu` have about the same amount of data - 10s resolution and being sent from the same client, collectd. 

@otoolep suggested I open an issue. I am able to provide the data, let me know the best way to get that to you. Philip also suggested that we profile that query and that you could provide the instructions on how to do it. 

Thanks!

**Comment by otoolep** [comment]
Can you run the node with CPU profiling enabled:

https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#profiling

and provide us with the CPU profile file, after you shutdown the node? If you could also include the influxd binary you run, that would be great.

@beckettsean -- can you provide upload details for us?

**Comment by otoolep** [comment]
cc @benbjohnson

**Comment by otoolep** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/influxdb/_q0OKNSnH9M/8GgbCOyfCwAJ

**Comment by bwhaley** [comment]
Thanks, I have the profiling data. Let me know how to send the profile info, `influxd`, and the data via whatever mechanism is easiest.

**Comment by otoolep** [comment]
If you are up for it, the easiest thing might be to run the profiling tool yourself and send us the svg image.
```
$ ./influxd -cpuprofile ~/cpuprof
.
.
)$ go tool pprof ./influxd ~/cpuprof  
Entering interactive mode (type "help" for commands)
(pprof) web
```
Save the image and attach it here. You might need to run the slow query a few times so the profiling data provides us a good picture. Shut down the node immediately after running the queries.

**Comment by bwhaley** [comment]
Attached. CPU profile for the query with 1m and 10m time intervals in the `GROUP BY` clause.

![cpu](https://cloud.githubusercontent.com/assets/503816/10857973/add30096-7f0e-11e5-9ea7-e5d136349d0e.png)

**Comment by otoolep** [comment]
cc @benbjohnson 

Ben is actually working is the `decodeFloatBlock` code right now, trying to optimize it. (Correct me if wrong, Ben). So that should help.

Why one query takes so much longer than the other is difficult to know. Perhaps we need profiles for each query. Then we could compare.

**Comment by otoolep** [comment]
Looks like I may have been mistaken and @benbjohnson is working on a different area.

**Comment by bwhaley** [comment]
Here's a profile of the query on the `load` measurement which is much faster.

![load](https://cloud.githubusercontent.com/assets/503816/10858479/9f69949e-7f12-11e5-9cfc-cabf52d8689d.png)

**Comment by otoolep** [comment]
Great, thank you.

**Comment by otoolep** [comment]
From @jwilder 
```
influxdb:influxdb jason$ go test -run none -bench Decoder -benchmem ./tsdb/engine/tsm1/
PASS
BenchmarkInt64DecoderPackedSimple-8      300000          5544 ns/op           0 B/op           0 allocs/op
BenchmarkInt64DecoderRLE-8               500000          3518 ns/op           0 B/op           0 allocs/op
BenchmarkTimeDecoder-8                   200000          7762 ns/op           0 B/op           0 allocs/op
BenchmarkFloatDecoder-8                  200000          6410 ns/op         160 B/op           3 allocs/op
```
We are wondering if the 3 allocs per op can be avoided.

**Comment by otoolep** [comment]
Actually @benbjohnson is reworking the code in the query engine, with an eye to reducing allocations. While not directly related to this issue, he points out that the profiles above show the majority time *is* spent in allocation, so we're going to attack that first. We hope to have significantly better QE performance in the near future.

So any specific work on this issue will wait until that work is completed.

**Comment by bwhaley** [comment]
Turns out that I was wrong about the size of the queries. The "slow" query on cpu has one series per cpu core, or 16x more than load. So it makes sense and there is no issue here. Sorry about that.
