### ISSUE TITLE
Disk space won't reclaim after removing point using retention policy

### ISSUE THREAD

**Issue by kureikain** [influxdb/influxdb#4634]
I'm not sure if this is an issue.

I have telegraf run for 2 days and it use up to  500MB. I realized that 0.9.4 takes more space than LevelDB, which makes sense. So I set retention policy default to 6hour.

```
SHOW RETENTION POLICIES ON "telegraf"
default	"6h0m0s"	1	false
```

Once the data is removed, mean I don't see any old data when I tried to query it. However, when I'm using 

```
du -sch data
```

I saw the same disk space usage as before, nothing is reduce...

Is this expected?

**Comment by otoolep** [comment]
We would need to see the full output from `du -sch` to know if there is a problem -- before and after.

**Comment by beckettsean** [comment]
What was the retention duration before you changed it to 6 hours?

**Comment by kureikain** [comment]
Before, it was infinity(default one). 

Then I was so frustrated so I manually add a another retention policy one(non default) and now I can see disk space be reclaim correctly.

```

name	duration	replicaN	default
default	"6h0m0s"	1	false
6h	"6h0m0s"	1	true
```

```
sudo du -sch data
213M	data
213M	total
```

I will monitoring for a couple days and will close this issue out once I confirm that the disk space get reclaim.

**Comment by otoolep** [comment]
I presume this is OK now. Please let us know if not.
