### ISSUE TITLE
Log file is empty after logrotate

### ISSUE THREAD

**Issue by Issif** [influxdb/influxdb#4635]
Hi,

After logrotate execution, my log file is empty :

```
root@clagra-pn20:/var/log/influxdb# ll
total 224
-rw-r--r-- 1 influxdb influxdb      0 Oct 31 06:25 influxd.log
-rw-r--r-- 1 influxdb influxdb 225433 Oct 31 06:25 influxd.log.1.gz
```

A restart of influxdb daemon fixes the problem (influxd.log is filled again).

My release is :
```
2015/10/30 12:09:43 InfluxDB starting, version 0.9.5-nightly-4e2a16c, branch master, commit 4e2a16c459183e0adc5946b242d014b2090de206, built '2015-10-29T04:00:42+0000'
2015/10/30 12:09:43 Go version go1.5.1, GOMAXPROCS set to 16
```

Thanks

**Comment by rossmcdonald** [comment]
@Issif What Linux distribution and version are you using?

**Comment by Issif** [comment]
Sorry :

```
OS ................... Debian 7.8 "wheezy"
Kernel ............... 3.2.0-4-amd64
```
```
Logrotate release
3.8.1-4
```
```
InfluxDB :
version 0.9.5-nightly-4e2a16c, branch master, commit 4e2a16c459183e0adc5946b242d014b2090de206, built '2015-10-29T04:00:42+0000'

Go version :
go1.5.1, GOMAXPROCS set to 16
```

Thanks

**Comment by otoolep** [comment]
@rossmcdonald -- perhaps we should confirm that the distros we do run on actually work? Force a rotate to take place and check if `influxd` writes to the new file?

**Comment by beckettsean** [comment]
@Issif are you using the logrotate file that shipped with the package or one you write yourself?

@rossmcdonald does our logrotate file have `copytruncate` set?

**Comment by otoolep** [comment]
copytruncate is set.

https://github.com/influxdb/influxdb/blob/master/scripts/logrotate

Nothing has changed in this file since you wrote it.

**Comment by beckettsean** [comment]
The behavior strongly suggests that `copytruncate` is not working. This is the exact issue that flag is meant to prevent.

@Issif when the log file rolls over, does the inode of `influxdb.log` stay the same? It should, if `copytruncate` is working as expected.

**Comment by Issif** [comment]
I think I found why ```copytruncate ``` doesn't work.

I still have a relic of a previous install :
```
root@clagra-pn20:/etc/logrotate.d# ll influx*
-rw-rw-r-- 1 root root 113 Sep 29 19:51 influxd
-rw-r--r-- 1 root root 110 Jul  3 16:43 influxdb
```
with :

```
root@clagra-pn20:/etc/logrotate.d# cat influxd
/var/log/influxdb/influxd.log {
    daily
    rotate 7
    missingok
    dateext
    copytruncate
    compress
}
```
and 

```
root@clagra-pn20:/etc/logrotate.d# cat influxdb
/var/log/influxdb/*.log {
    daily
    maxsize 512M
    rotate 7
    compress
    missingok
    notifempty
}

```

So, with ABC order, ```influxd``` has been played and  ```influxdb``` just after. The first one keeps  ```inode``` and the second doesn't.

I'll remove ```/etc/logrotate.d/influxdb```  and restart the daemon, I'll see tomorrow if it works.

Thanks.

**Comment by rossmcdonald** [comment]
@Issif Thank you for the update. That would make sense if there were conflicting logrotate files. We will be adding a check for legacy logrotate files in the post-installation step of the next release, so hopefully this problem will be avoided in the future.

Let us know what you find out.

**Comment by Issif** [comment]
Hi,

It works fine, you can close this issue.

```
-rw-r--r-- 1 influxdb influxdb 978216 Nov  9 09:45 influxd.log
-rw-r--r-- 1 influxdb influxdb 483636 Nov  6 06:24 influxd.log-20151106.gz
-rw-r--r-- 1 influxdb influxdb 249525 Nov  7 06:24 influxd.log-20151107.gz
-rw-r--r-- 1 influxdb influxdb 249833 Nov  8 06:22 influxd.log-20151108.gz
-rw-r--r-- 1 influxdb influxdb 277320 Nov  9 06:24 influxd.log-20151109.gz
```

Thanks again.
