### ISSUE TITLE
[0.9.5-nightly] retention policy is filtering data

### ISSUE THREAD

**Issue by handfreezer** [influxdb/influxdb#4658]
Hello,

   I got a measurement in a db, added values, then changing the dfault retention policy as for result to filtered previous data. If I set back the previous retention policy as default, I get back my previous data, but data inserted in middle time get filtered.

An extract of CLI is available here (it is a .txt file): http://we.tl/7t4hXtASOJ

Version of Influxdb: 0.9.5-nightly-6682752

Best regards

**Comment by jackzampolin** [comment]
@handfreezer in InfluxDB data is stored based on `"database"."retention_policy"."measurement"` so in your example the first query actually runs the following query: 

`SELECT * FROM "graphite"."default"."JAVA_heap"`

or written another way

`SELECT * FROM "graphite".."JAVA_heap"`

And the second query, after changing the retention policy is running:

`SELECT * FROM "graphite"."retention_14jours"."JAVA_heap"`

The data you added in the 'middle time' should be stored in the retention policy that was specified as default at that time.  More information about [retention policies](https://influxdb.com/docs/v0.9/query_language/database_management.html#retention-policy-management).

**Comment by handfreezer** [comment]
OK, sorry, I missed this point.
Thanks.
