### ISSUE TITLE
Support "DROP DATABASE IF EXISTS"

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4659]
This useful command would allow clients to idempotently drop a database. If `IF EXISTS` is present, no error would be returned if the database does not exist.

https://github.com/influxdb/influxdb/pull/3892 introduced `CREATE DATABASE IF NOT EXISTS`, so using that PR as a guide, along with investigating the current implementation of `DROP DATABASE` should make it relatively easy to implement this feature.

**Comment by ch33hau** [comment]
Hi @otoolep , can I have a try for this issue? I have create a pull request for it.
If someone is already working on it then just ignore mine ya

**Comment by otoolep** [comment]
@ch33hau - email me your address so we can send you a tshirt. philip at influxdb

**Comment by ch33hau** [comment]
@otoolep Thanks for your Monday early good news! =)
I have sent my address to your email.
