### ISSUE TITLE
[0.9.4.2]How to change shard period

### ISSUE THREAD

**Issue by ryanjin** [influxdb/influxdb#4670]
the command 
```
show shards
```
return
```
id	start_time	end_time	expiry_time	owners
1	"2015-10-10T00:00:00Z"	"2015-10-11T00:00:00Z"	"2015-10-18T00:00:00Z"	"1"
3	"2015-10-11T00:00:00Z"	"2015-10-12T00:00:00Z"	"2015-10-19T00:00:00Z"	"1"
4	"2015-10-12T00:00:00Z"	"2015-10-13T00:00:00Z"	"2015-10-20T00:00:00Z"	"1"
```

i want to know how to change the period from start_time to end_time(now is 7d)

**Comment by otoolep** [comment]
You can't directly change a shard's end time. All you can do is change the duration of a retention policy, which will create shards of different duration when it next creates shards.
