### ISSUE TITLE
Add SetReadBuffer() to collectd and Graphite

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4678]
Started with https://github.com/influxdb/influxdb/pull/4676/

@sparrc discovered we can increase the OS buffers to improve performance.

**Comment by otoolep** [comment]
The buffer size should be configurable.

**Comment by otoolep** [comment]
@sparrc -- I believe this is fixed.

**Comment by sparrc** [comment]
Not quite, it's in PR #4681
