### ISSUE TITLE
[0.9.4.1] Errors consuming collectd "battery" plugin values

### ISSUE THREAD

**Issue by ryan-williams** [influxdb/influxdb#4687]
When I enable `collectd`'s battery plugin and configure its `types.db` (cf. https://github.com/collectd/collectd/issues/1338) to send `capacity` as a 'GAUGE', i.e.:

```
capacity        value:GAUGE:0:U
```

I get errors trying to query the measurement in the Influx (0.9.4.1) console:

```
> select * from battery_
ERR: invalid character 'j' looking for beginning of value
```

If I instead configure `capacity` as `ABSOLUTE` in `collectd`, i.e.:
```
capacity        value:ABSOLUTE:0:U
```

I am able to query the values in the Influx console:

```
> select * from battery_
name: battery_
--------------
time				host		instance	type		type_instance	value
2015-11-05T22:05:18.004543Z	mbp.local	0		capacity	charged		9.221120237041091e+18
2015-11-05T22:05:18.004544Z	mbp.local	0		capacity	discharged	9.221120237041091e+18
2015-11-05T22:05:18.004545Z	mbp.local	0		capacity	degraded	9.221120237041091e+18
2015-11-05T22:05:27.746246Z	mbp.local	0		capacity	charged		9.221120237041091e+18
2015-11-05T22:05:27.746252Z	mbp.local	0		capacity	discharged	9.221120237041091e+18
2015-11-05T22:05:27.746255Z	mbp.local	0		capacity	degraded	9.221120237041091e+18
2015-11-05T22:05:37.667902Z	mbp.local	0		capacity	charged		9.221120237041091e+18
2015-11-05T22:05:37.667908Z	mbp.local	0		capacity	discharged	9.221120237041091e+18
2015-11-05T22:05:37.66791Z	mbp.local	0		capacity	degraded	9.221120237041091e+18
```

However, they don't seem to be stored as numbers, and downstream Grafana doesn't seem to understand them as such.

I've looked at the few issues discussing nuances of integer-parsing in Influx, e.g. #3583 and #4433, and it seems like Influx 0.9.4.1 should be able to handle values that look like `9.221120237041091e+18` (as floats?), and yet something is going wrong and I'm not sure how to debug from here. Any pointers as to why the battery values are being rejected as `GAUGE`s would be appreciated. Thanks!

**Comment by beckettsean** [comment]
I have limited familiarity with collectd, but every other instance of InfluxDB spitting out `ERR: invalid character 'j' looking for beginning of value` has turned out to be because of `NaN` values. Does collectd spit out `NaN` for gauges?

> However, they don't seem to be stored as numbers, and downstream Grafana doesn't seem to understand them as such.

It is possible they are going in as strings, although InfluxDB does understand scientific notation for floats and should store them as numbers. Does `SELECT SUM(value) FROM battery_` return something reasonable?

**Comment by ryan-williams** [comment]
hm yea when I have `collectd` send them as `ABSOLUTE` and I have the `9.221120237041091e+18` values, I can `sum` them as you suggest:

```
> select sum(value) from battery_
name: battery_
--------------
time			sum
1970-01-01T00:00:00Z	5.532672142224654e+19

> select sum(value) from battery_
name: battery_
--------------
time			sum
1970-01-01T00:00:00Z	1.1065344284449309e+20
```

Trying to plot them in Grafana, I see:

![](http://cl.ly/image/3u2h0d0G1m1A/Screen%20Shot%202015-11-05%20at%206.25.06%20PM.png)

So maybe the issue is Grafana's handling of numbers this large?

In any case, influx seems to be correctly consuming collectd `ABSOLUTE`s as floats so we can close this.
