### ISSUE TITLE
failed to store statistics: timeout

### ISSUE THREAD

**Issue by ntquyen** [influxdb/influxdb#4693]
```
...
2015/11/06 00:31:11 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/11/06 00:31:11 Go version go1.5, GOMAXPROCS set to 4
2015/11/06 00:31:11 Using configuration at: /config/config.toml
[metastore] 2015/11/06 00:31:11 Using data dir: /data/meta
[metastore] 2015/11/06 00:31:11 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/11/06 00:31:11 Node at localhost:8088 [Follower]
[metastore] 2015/11/06 00:31:13 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[monitor] 2015/11/06 00:31:13 Starting monitor system
[monitor] 2015/11/06 00:31:13 'build' registered for diagnostics monitoring
[monitor] 2015/11/06 00:31:13 'runtime' registered for diagnostics monitoring
[monitor] 2015/11/06 00:31:13 'network' registered for diagnostics monitoring
[monitor] 2015/11/06 00:31:13 'system' registered for diagnostics monitoring
[store] 2015/11/06 00:31:13 Using data dir: /data/db
[monitor] 2015/11/06 00:31:13 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/11/06 00:31:13 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/06 00:31:13 WAL writing to /data/wal/_internal/monitor/1
[metastore] 2015/11/06 00:31:14 Updated node id=1 hostname=localhost:8088
[monitor] 2015/11/06 00:31:28 failed to store statistics: timeout
[monitor] 2015/11/06 00:31:38 failed to store statistics: timeout
[monitor] 2015/11/06 00:31:48 failed to store statistics: timeout
[monitor] 2015/11/06 00:31:58 failed to store statistics: timeout
2015/11/06 00:31:11 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/11/06 00:31:11 Go version go1.5, GOMAXPROCS set to 4
2015/11/06 00:31:11 Using configuration at: /config/config.toml
...
```

I'm using influxdb 0.9.4.2 (https://github.com/tutumcloud/influxdb) inside Kubernetes cluster, data is persistent to one of the nodes. From a fresh start (data is empty) it run just fine, after a few hundreds MB the error above occurs and influxdb hangs (not crash, but cannot access to it, admin or driver). Restart doesn't help, the error still there, unless I clear all  the data.

Thanks for any help!

**Comment by otoolep** [comment]
Try doubling these timeouts:

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L126

**Comment by otoolep** [comment]
What kind of load are you putting on the system? What are the resources underneath the system?

**Comment by ntquyen** [comment]
@otoolep Thanks I'll try that. Anyway, it seems working when I removed the resource limits for the container. Before it was set to 2GB of RAM. At least I can restart it and been running for 1 hours now, keep watching.

**Comment by ntquyen** [comment]
I got one question: what's is the behavior of influxdb when a write is timeout?

**Comment by otoolep** [comment]
In a single-node system it probably means nothing was written. Your code should backoff and retry if your client code receives. For internals stats, it's not that serious.

Generally it's a sign the system is too busy, which it can be particularly when starting up.

**Comment by mtzaurus** [comment]
I have ran into this issue on 0.9.5 nightly:

My InfluxDb was under high load for an hour or two, then OOM happened.
When I restarted the database and tried to reinitialize, I got the following:

query] 2015/11/10 20:50:48 DROP DATABASE analytics

[monitor] 2015/11/10 20:50:57 failed to store statistics: timeout

[monitor] 2015/11/10 20:51:08 failed to store statistics: timeout
[monitor] 2015/11/10 20:51:17 failed to store statistics: timeout
[monitor] 2015/11/10 20:51:27 failed to store statistics: timeout
[monitor] 2015/11/10 20:51:37 failed to store statistics: timeout
[monitor] 2015/11/10 20:51:47 failed to store statistics: timeout
[monitor] 2015/11/10 20:51:57 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:07 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:17 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:27 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:37 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:47 failed to store statistics: timeout
[monitor] 2015/11/10 20:52:57 failed to store statistics: timeout
[monitor] 2015/11/10 20:53:07 failed to store statistics: timeout
[monitor] 2015/11/10 20:53:17 failed to store statistics: timeout
[monitor] 2015/11/10 20:53:27 failed to store statistics: timeout
[monitor] 2015/11/10 20:53:38 failed to store statistics: timeout
[monitor] 2015/11/10 20:53:47 failed to store statistics: timeout

**Comment by mtzaurus** [comment]
P.S: single-node setup, not clustered.

**Comment by beckettsean** [comment]
@otoolep sounds like an `_internal` write issue, perhaps. Any workarounds?

**Comment by otoolep** [comment]
This is most likely not specific to the internal database, the system simply couldn't accept any more load.

Did the issue ever resolve @mtzaurus ?

**Comment by mtzaurus** [comment]
Today I had it again, it was hanging for 20+ minutes, so I just killed to process.

What I can say for sure, is that it's again DATABASE DROP - related.


[query] 2015/11/11 11:47:36 DROP DATABASE analytics
[monitor] 2015/11/11 11:47:41 failed to store statistics: timeout

[monitor] 2015/11/11 11:47:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:48:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:49:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:50:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:51:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:52:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:53:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:54:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:55:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:56:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:57:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:58:51 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:01 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:11 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:21 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:31 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:41 failed to store statistics: timeout
[monitor] 2015/11/11 11:59:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:00:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:00:11 failed to store statistics: timeout
[retention] 2015/11/11 12:00:16 retention policy enforcement check commencing
[retention] 2015/11/11 12:00:16 retention policy shard deletion check commencing
[monitor] 2015/11/11 12:00:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:00:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:00:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:00:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:01:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:02:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:03:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:04:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:05:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:41 failed to store statistics: timeout
[monitor] 2015/11/11 12:06:51 failed to store statistics: timeout
[monitor] 2015/11/11 12:07:01 failed to store statistics: timeout
[monitor] 2015/11/11 12:07:11 failed to store statistics: timeout
[monitor] 2015/11/11 12:07:21 failed to store statistics: timeout
[monitor] 2015/11/11 12:07:31 failed to store statistics: timeout
[monitor] 2015/11/11 12:07:41 failed to store statistics: timeout

**Comment by CVTJNII** [comment]
I'm seeing this on Influx 0.9.5.1.  When I hop on the box I don't see any obvious system contention, the load is low, CPU idle, and there is plenty of memory and disk free.  InfluxDB appears to be wedged and not storing or querying data.  I see the following in the logs, query and http logs are off as they cause the log to grow to multiple gigs:

```
{"log":"[wal] 2015/12/02 21:15:28 Flush due to idle. Flushing 51 series with 51 points and 1947 bytes from partition 1\n","stream":"stderr","time":"2015-12-02T21:15:28.305797744Z"}
{"log":"[wal] 2015/12/02 21:15:28 write to index of partition 1 took 14.9136ms\n","stream":"stderr","time":"2015-12-02T21:15:28.321011441Z"}
{"log":"[wal] 2015/12/02 21:15:38 Flush due to idle. Flushing 51 series with 51 points and 1947 bytes from partition 1\n","stream":"stderr","time":"2015-12-02T21:15:38.32964811Z"}
{"log":"[wal] 2015/12/02 21:15:38 write to index of partition 1 took 16.21831ms\n","stream":"stderr","time":"2015-12-02T21:15:38.346211589Z"}
{"log":"[monitor] 2015/12/02 21:15:48 failed to store statistics: timeout\n","stream":"stderr","time":"2015-12-02T21:15:48.287640874Z"}
{"log":"[monitor] 2015/12/02 21:15:58 failed to store statistics: timeout\n","stream":"stderr","time":"2015-12-02T21:15:58.286771226Z"}
{"log":"[monitor] 2015/12/02 21:16:08 failed to store statistics: timeout\n","stream":"stderr","time":"2015-12-02T21:16:08.288266584Z"}
{"log":"[monitor] 2015/12/02 21:16:18 failed to store statistics: timeout\n","stream":"stderr","time":"2015-12-02T21:16:18.288594376Z"}
{"log":"[monitor] 2015/12/02 21:16:28 failed to store statistics: timeout\n","stream":"stderr","time":"2015-12-02T21:16:28.28714024Z"}
```

Restarting InfluxDB resolves it, though it takes some time to restart while logging about writing from WAL.  I am running InfluxDB in a container as non-root, but I'm not applying any limits.

```
# ps awwux | grep '[0-9] /usr/bin/influx[d]'
904       9823 50.9 11.5 3992448 468408 ?      Sl   00:13  15:54 /usr/bin/influxd -config=/etc/influxdb/influxdb.conf -hostname=10.113.42.37:8088
# cat /proc/9823/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             524288               1048576              processes 
Max open files            524288               1048576              files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       31449                31449                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 
```

Which resources can cause this?

**Comment by CVTJNII** [comment]
Is this duplicate of 4121?

**Comment by beckettsean** [comment]
@CVTJNII looks like it

**Comment by iL-Mattone** [comment]
Does anyone know if this issue been fixed and if so where the relevant patch / fix details are ?

**Comment by dstrbad** [comment]
Any updates on this?
