### ISSUE TITLE
Add packages for Ubuntu 12.04 (precise) to apt repo

### ISSUE THREAD

**Issue by cgunther** [influxdb/influxdb#4694]
Can packages for 12.04 be added to the apt repo (https://repos.influxdata.com/)? I see it currently requires 14.04 (trusty) or higher. 12.04 is an LTS release and is supported until 2017 so it'd be great to be able to install packages directly from the apt repo.

**Comment by rossmcdonald** [comment]
@cgunther Thanks for letting us know. We have now added repo support for Ubuntu precise.

Let me know if you run into any issues!

**Comment by cgunther** [comment]
Terrific, thank you!
