### ISSUE TITLE
[0.9.4.2] Failed to write point batch: timeout

### ISSUE THREAD

**Issue by pcable3d** [influxdb/influxdb#4712]
Running a client's soak test over the weekend I come back to a crashed influxDB.

The timeouts begin after a query from a simultaneously running Grafana session:
```
[wal] 2015/11/09 01:54:26 Flush due to idle. Flushing 38 series with 38 points and 2050 bytes from partition 1
[wal] 2015/11/09 01:54:26 write to index of partition 1 took 24.644672ms
[wal] 2015/11/09 01:54:27 Flush due to idle. Flushing 6 series with 6 points and 691 bytes from partition 1
[wal] 2015/11/09 01:54:27 write to index of partition 1 took 17.03848ms
[query] 2015/11/09 01:54:27 SELECT mean(load1min) AS "load1min" FROM "udp"."default".loadavg WHERE time > now() - 1h GROUP BY time(10s)
[query] 2015/11/09 01:54:28 SELECT mean(cpu_total) AS "cpu_total" FROM "udp"."default".cpu WHERE time > now() - 1h GROUP BY time(15s)
[query] ...
[wal] 2015/11/09 01:54:37 Flush due to idle. Flushing 38 series with 38 points and 2050 bytes from partition 1
[wal] 2015/11/09 01:54:37 write to index of partition 1 took 19.854104ms
[udp] 2015/11/09 01:54:38 failed to write point batch to database "udp": timeout
[udp] 2015/11/09 01:54:44 failed to write point batch to database "udp": timeout
[wal] 2015/11/09 01:54:46 Flush due to idle. Flushing 38 series with 38 points and 2059 bytes from partition 1
[wal] 2015/11/09 01:54:46 write to index of partition 1 took 11.185573ms
[udp] 2015/11/09 01:54:50 failed to write point batch to database "udp": timeout
[udp] 2015/11/09 01:54:56 failed to write point batch to database "udp": timeout
[wal] 2015/11/09 01:54:56 Flush due to idle. Flushing 38 series with 38 points and 2059 bytes from partition 1
[wal] 2015/11/09 01:54:56 write to index of partition 1 took 24.754869ms
```

Apparently the heap started exploding at 01:50, after a total of 320K points at 5s period were received during that session, the timeouts begin at 01:54.

![image](https://cloud.githubusercontent.com/assets/15105872/11036501/31d5fd8e-86f9-11e5-9f97-b4d42e99493c.png)

What is going on there, hope this helps debugging!

**Comment by otoolep** [comment]
You have neglected to tell us the version you are running. Without that information we cannot help you.

**Comment by pcable3d** [comment]
We are running latest stable 0.9.4.2.

**Comment by otoolep** [comment]
This may be an indication that your system is under excessive load. What load are you putting on the system in terms of points/sec? What are the technical specifications of the host system?

**Comment by pcable3d** [comment]
Not that many, 20 points every 5s coming through UDP, with flush at 1s.
The VM has 4GB memory and is running on a recent Xeon octacore host.

**Comment by pcable3d** [comment]
we are a little concerned here, the flush time keeps growing to >200ms, only 20h into the testrun and after last db purge. A total of 9 MB of datapoints were received through UDP.

![image](https://cloud.githubusercontent.com/assets/15105872/11058607/447e9b8a-8794-11e5-83fc-cf354916ab19.png)

![image](https://cloud.githubusercontent.com/assets/15105872/11058929/afa14e6a-8796-11e5-8358-4f72c1847433.png)

Shard stats show that the database is split every 7d. Is there a way to force spliting into new shards every 1d?
```
> show shards
name: _internal
---------------
id	start_time		end_time		expiry_time		owners
1	2015-10-27T00:00:00Z	2015-10-28T00:00:00Z	2015-11-04T00:00:00Z	1
3	2015-10-28T00:00:00Z	2015-10-29T00:00:00Z	2015-11-05T00:00:00Z	1
...
name: udp
---------
id	start_time		end_time		expiry_time		owners
27	2015-11-09T00:00:00Z	2015-11-16T00:00:00Z	2015-11-16T00:00:00Z	1
```

What are your thoughts on this? This behavior is concerning me a little bit.

**Comment by pcable3d** [comment]
Apperently #4354 describes a similar memory leak in a compareable environment. I will update to the latest nightly and run on tsm1.

**Comment by beckettsean** [comment]
@pcable3d the shard duration is a function of the retention policy. If your RP duration is between two days and six months, shards will live for a day. If the RP duration is longer than six months, the shards will live for a week. Less than two days and the shards live for an hour.

**Comment by beckettsean** [comment]
There are known memory issues with the `bz1` engine, so updating to `tsm1` is definitely a good thing to try.

**Comment by pcable3d** [comment]
The leaking memory could not be reproduced with `0.9.5 nightly`. However the problem seemed to be related to an ever changing `uid` tag which resulted in creation of thousand of series by the engine.

**Comment by otoolep** [comment]
This is not a leak. With more series, more memory is required.
