### ISSUE TITLE
Query performance

### ISSUE THREAD

**Issue by varche1** [influxdb/influxdb#4713]
Hi!

Starting from version 0.9.2 noticed a strong degradation of query performance. Using the 0.9.2 version I can get around the business logic but using the 0.9.4.2 version, this problem has become so acute that I had to turned off the InfluxDB at production because the server could not cope with the load, even evaluate a single query.

How to reproduce:
* Create a database issues_db1: `/ opt / influxdb / influx -execute" create database issues_db1 "`
* Create a database issues_db2: `/ opt / influxdb / influx -execute" create database issues_db2 "`
* Create a database issues_db3: `/ opt / influxdb / influx -execute" create database issues_db3 "`
* Download https://gist.github.com/varche1/38963b47f8a66a083e0c
* Run the script: `python issue_client.py issues_db1 leads 100000 ''`
* Run the script: `python issue_client.py issues_db2 leads_with_some_tags 100,000 meta.year,meta.month`
* Run the script: `python issue_client.py issues_db3 leads_with_full_tags 100,000 meta.year,meta.month,meta.day,meta.weekday,meta.hour`

InfluxDB 0.9.2
Python client influxdb == 2.8.0

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db1"`
=> 
`/opt/influxdb/influx -execute  -database "issues_db"  0,01s user 0,01s system 3% cpu 0,658 total`

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_some_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db2"`
=>
`/opt/influxdb/influx -execute  -database "issues_db"  0,02s user 0,01s system 3% cpu 0,809 total`

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_full_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db3"`
=>
`/opt/influxdb/influx -execute  -database "issues_db"  0,01s user 0,01s system 0% cpu 21,532 total` (too long but it works. Using 0.9.4.2 it doesn't work)

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_full_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by meta.year order by asc" -database "issues_db3"`
=>
`/opt/influxdb/influx -execute  -database "issues_db"  0,00s user 0,01s system 0% cpu 25,171 total` (too long as well, but at 0.9.4.2 its longer)

InfluxDB 0.9.4.2 or night build at 6 of november 2015 (even try `tsm` engine)
Python client influxdb==2.9.2

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db1"`
=> 
`/opt/influxdb/influx -execute  -database "issues_db"  0,01s user 0,01s system 3% cpu 0,658 total`

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_some_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db2"`
=>
`/opt/influxdb/influx -execute  -database "issues_db3"  0,01s user 0,01s system 0% cpu 21,532 total` (25 times longer!)

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_full_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db3"`
=>
```
ERR: Get http://localhost:8086/query?db=issues_db&epoch=ns&q=select+sum%28sign%29+as+value+from+%2Fleads_full%2F+where+time+%3E+%272010-11-06T00%3A00%3A00%2B00%3A00%27+and+time+%3C+%272015-11-10T16%3A20%3A00%2B00%3A00%27+group+by+time%281d%29+order+by+asc: net/http: transport closed before response was received
/opt/influxdb/influx -execute  -database "issues_db"  0,00s user 0,01s system 0% cpu 1:57,22 total
```
It can not be completed - out of memory. http://joxi.ru/4vAW1xyU76OvmW

`time /opt/influxdb/influx -execute "select sum(sign) as value from /leads/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by meta.year order by asc" -database "issues_db3"`
=>
`/opt/influxdb/influx -execute  -database "issues_db3"  0,01s user 0,00s system 0% cpu 40,138 total`

According to the business logic I have to make inquiries with the obligatory grouped by time(...) or meta.XXX field (meta.year, meta.month, meta.day, meta.weekday, meta.hour)

Is this expected behavior or a bug? Am I using data model of InfluxDB in right way?

I am using Ubuntu 14.04 LTS 64-bit.
Intel® Core ™ i7-4771 CPU @ 3.50GHz × 8
24 GB RAM

Used: https://s3.amazonaws.com/influxdb/influxdb_0.9.2_amd64.deb and https://s3.amazonaws.com/influxdb/influxdb_0.9.4.2_amd64.deb

I'm using config file out of the box.

**Comment by beckettsean** [comment]
@jackzampolin can you repro the performance numbers? 

@varche1 roughly how many points are involved in the queries? A five year time span of test data might be thousands of points or it might be billions of points. We would expect query response time to rise linearly with the number of points pulled from disk.

**Comment by varche1** [comment]
@beckettsean In the examples of this issue (script https://gist.github.com/varche1/38963b47f8a66a083e0c), I used a fixed number of points equal to 100,000 from what I understand, it's a little

**Comment by jackzampolin** [comment]
@beckettsean on it!

**Comment by jackzampolin** [comment]
@varche1 having a little issue using the `issue_client.py`.  Trying all the commands you listed results in the following stacktrace:

```
$ python issue_client.py issues_db2 leads_with_some_tags 100000 meta.year,meta.month

Traceback (most recent call last):
  File "issue_client.py", line 68, in <module>
    main(db, measurement, points_to_generate, tags_to_use)
  File "issue_client.py", line 59, in main
    client.write_points(points, batch_size=MAX_BATCH_COUNT)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 380, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 432, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 277, in write
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 247, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: unable to parse 'leads_with_some_tags,meta.month=1,meta.year=2011 sign=-1i,value=125i 1296360101000000000': invalid number
```

**Comment by varche1** [comment]
@jackzampolin please, show me yours python version, python Influxdb client version and influx version. I'll check at localhost

**Comment by jackzampolin** [comment]
```
$ python -V
Python 2.7.6
$ /opt/influxdb/influx -version
InfluxDB shell 0.9.2
$ pip show influxdb
--
Name: influxdb
Version: 2.9.3
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, python-dateutil, pytz, requests
```
I prob need to install the older version of the python-influxdb package and try again.

**Comment by jackzampolin** [comment]
@varche1 Got it working with 2.8.0.  Sorry for the false alarm!

**Comment by jackzampolin** [comment]
@varche1 Having trouble getting it to write.  How long does the python script take to execute? After trying a couple of times and having the process hang I killed it with `cmd-C` after about a minute. Then when I `select count(value) from leads_with_some_tags` I get `300` points in the database.

**Comment by varche1** [comment]
@jackzampolin each script executes about 6 minutes on my machine if using influxdb client 2.8.0 (too long I think, but any way, it's 2.8.0 spesific behavor)

Any way, try to reproduce problem at 0.9.4.2 Influxdb version.

**Comment by jackzampolin** [comment]
@varche1 Thanks! Will do.

**Comment by jackzampolin** [comment]
```
Ubuntu 14.04 
32GB RAM
InfluxDB 0.9.2
Python client influxdb == 2.8.0

time /opt/influxdb/influx -execute "select sum(sign) as value from /leads/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db1"`

real	0m2.717s
user	0m0.037s
sys	0m0.044s

time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_some_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db2"

real	0m1.931s
user	0m0.023s
sys	0m0.053s

time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_full_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by time(1d) order by asc" -database "issues_db3"

real	1m14.244s
user	0m0.028s
sys	0m0.037s

time /opt/influxdb/influx -execute "select sum(sign) as value from /leads_with_full_tags/ where time > '2010-01-01T00:00:00+00:00' and time < '2015-11-10T16:20:00+00:00' group by meta.year order by asc" -database "issues_db3"

real	1m5.532s
user	0m0.010s
sys	0m0.023s
```

@varche1 You are correct these queries are taking forever!  The reason for the performance hit is that you have extremely high series cardinality in this data set.  For the `leads_with_full_tags` measurement there are `5 (years) * 12 (months) * 365 (days) * 7 (days of week) * 12 (hours) = 1,839,600` different series.  Is this a similar tag set to the business data you are using?  I would advise pulling the series cardinality down to in the order of 100k for the hardware you are running.

**Comment by jackzampolin** [comment]
@varche1 Also using regular expressions also incurs a performance hit.
