### ISSUE TITLE
CLI history should skip blank lines

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4719]
Started with https://github.com/influxdb/influxdb/pull/4702

The 'history' command in the CLI should not show blank lines. E.g.:
```
> history
alter retention policy "default" on db duration 3400s
alter retention policy "default" on db duration 10m
show retention policies on db
show shards

show shards

show shards

show shards

show shards
```

This can either be done by a) not writing blank lines to the history file, or b) skipping them during display. Option a) might be easiest.

**Comment by otoolep** [comment]
cc @pires @corylanou

**Comment by otoolep** [comment]
Basically update `influx/main.go` so that it implements option a) or b).

**Comment by pires** [comment]
I want to take care of this with my refactoring of the CLI. Namely, write only valid commands and queries.
Can you assign this to me?

**Comment by otoolep** [comment]
No, it can only be assigned to members of the org. But your comment should capture -- thanks.
