### ISSUE TITLE
SHOW SHARD GROUPS

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#4728]
To complement `SHOW SHARDS`, `SHOW SHARD GROUPS` would operate at the higher level, allowing groups of shards that represent the same time to be deleted.

**Comment by otoolep** [comment]
This command involves 2 pieces:
- add the new command `SHOW SHARD GROUPS`.
- add support to the `meta` package for this command.

The change would be *very* similar to this PR: https://github.com/influxdb/influxdb/pull/3815. By following that, this change should be quite straightforward.

**Comment by otoolep** [comment]
The columns should be the same as `SHOW SHARDS`, but without the shard IDs.

**Comment by otoolep** [comment]
For extra points it would be worth factoring out the two commands, such that the logic which gathers the common data is factored out.

**Comment by mateuszdyminski** [comment]
Hi everyone,

That's my first contribution so if I don't understand something properly you could be a little bit more patient : )

I started working on this Issue, but I encountered some problems with the data which should be printed out. 

"The columns should be the same as SHOW SHARDS, but without the shard IDs." 
Is it means that I should group the shards by database and groupID? Here is the output from 'SHOW SHARDS':

name: _internal
---------------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time	owners
1	_internal	monitor			1		        2015-11-13	2015-11-14	2015-11-21	1


name: mydb
----------
id	database	retention_policy	shard_group	start_time		end_time		expiry_time	owners
2	mydb	default			2		        2015-11-09	2015-11-16	2015-11-16	1


The result of 'SHOW SHARD GROUPS' should look like this?

name: _internal
--------------------
group: 1
----------
database	retention_policy	shard_group	start_time		end_time		expiry_time	owners
_internal	monitor			1		        2015-11-13	2015-11-14	2015-11-21	1


name: mydb
----------------
group: 2
-----------
database	retention_policy	shard_group	start_time		end_time		expiry_time	owners
mydb	default			2		        2015-11-09	2015-11-16	2015-11-16	1
.
.
.
group: N
database	retention_policy	shard_group	start_time		end_time		expiry_time	owners
mydb	default			N		        2015-11-09	2015-11-16	2015-11-16	1

Thanks a lot for help! My PR almost ready by I want to be sure that I understand the scope of this task properly.

**Comment by otoolep** [comment]
Thanks @mateuszdyminski 

I was thinking it would be simpler than that. A single table with the columns: id, database, retetion_policy, start_time, end_time, expiry_time.

So you see, very similar to the output of `SHOW SHARD`. Make sense?

**Comment by mateuszdyminski** [comment]
@otoolep Sure. That makes sense.

I have created a PR.
