### ISSUE TITLE
[0.9.5-nightly] derivative return large value or  negative value

### ISSUE THREAD

**Issue by axingblog** [influxdb/influxdb#4741]
I use influxdb influxdb-0.9.5_nightly_7d4bdc1-1.x86_64  and telegraf 0.2.0
  
some time the  derivative funtion return a  negative  on last  point
non_negative_derivative   return a   very large numer  on last  point

sql:
```
SELECT derivative(mean("value"),10s) AS "value"  FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb'  AND time > now() - 1m GROUP BY time(10s), "name"  fill(previous)

SELECT non_negative_derivative(mean("value"),10s) AS "value"  FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb'  AND time > now() - 1m GROUP BY time(10s), "name"  fill(previous)
```

```
> {alue"  FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb'  AND time > now() - 1m GROUP BY time(10s), "name"  fill(previous)
name: io_writes
tags: name=memdiska
time			value
----			-----
1447202550000000000	
1447202560000000000	498
1447202570000000000	575.6666666716337
1447202580000000000	576.3333333283663
1447202590000000000	500.6666666716337
1447202600000000000	-473549.3333333358


>name: io_writes
tags: name=sdb
time			value
----			-----
1447202550000000000	
1447202560000000000	1270.75
1447202570000000000	771.25
1447202580000000000	464.5
1447202590000000000	1786.75
1447202600000000000	-1.24215528125e+09



> {alue"  FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb'  AND time > now() - 1m GROUP BY time(10s), "name"  fill(previous)
name: io_writes
tags: name=memdiska
time			value
----			-----
1447202620000000000	
1447202630000000000	544.6666666641831
1447202640000000000	537.6666666716337
1447202650000000000	555.3333333283663
1447202660000000000	534.6666666716337
1447202670000000000	0


>name: io_writes
tags: name=sdb
time			value
----			-----
1447202620000000000	
1447202630000000000	501.25
1447202640000000000	351.25
1447202650000000000	443.75
1447202660000000000	1.163072174666667e+09
1447202670000000000	7.908941483333302e+07
```

**Comment by beckettsean** [comment]
@axingblog can you share the underlying data along with the query results? It's tough to figure out whether there's something wrong without the source data to analyze. 

`SELECT * FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb'  AND time > now() - 1m`

Might make sense to put it in a [gist](https://gist.github.com/), since it is likely a lot of data.

**Comment by axingblog** [comment]
> SELECT * FROM "io_writes" WHERE "host" =~ /java-ecproxy$/ AND "name" = 'sda' OR "name" = 'memdiska' OR "name" = 'sdb' AND time > now() - 1m
name: io_writes
---------------
time			host		name		serial					value
1447204030000000000	s110	memdiska						37630999
1447204030000000000	s107	memdiska						35709734
1447204030000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720277738
1447204030000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742875891
1447204030000000000	s79	sdb		36b82a720d31c21001b45478751364832	4494184791
1447204030000000000	s14	sdb		ST31500341AS_9VS4M90H			4
1447204030000000000	s106	memdiska						35408285
1447204040000000000	s79	sdb		36b82a720d31c21001b45478751364832	4494184817
1447204040000000000	s106	memdiska						35408515
1447204040000000000	s110	memdiska						37633039
1447204040000000000	s14	sdb		ST31500341AS_9VS4M90H			4
1447204040000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742878415
1447204040000000000	s107	memdiska						35709974
1447204040000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720277738
1447204050000000000	s110	memdiska						37635016
1447204050000000000	s107	memdiska						35710205
1447204050000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720277742
1447204050000000000	s106	memdiska						35408777
1447204050000000000	s79	sdb		36b82a720d31c21001b45478751364832	4494184830
1447204050000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742880300
1447204050000000000	s14	sdb		ST31500341AS_9VS4M90H			4
1447204060000000000	s14	sdb		ST31500341AS_9VS4M90H			4
1447204060000000000	s110	memdiska						37637377
1447204060000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720277748
1447204060000000000	s107	memdiska						35710434
1447204060000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742883200
1447204060000000000	s106	memdiska						35409010
1447204060000000000	s79	sdb		36b82a720d31c21001b45478751364832	4494184890
1447204070000000000	s79	sdb		36b82a720d31c21001b45478751364832	4494184894
1447204070000000000	s106	memdiska						35409252
1447204070000000000	s110	memdiska						37639906
1447204070000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720280813
1447204070000000000	s14	sdb		ST31500341AS_9VS4M90H			4
1447204070000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742886799
1447204070000000000	s107	memdiska						35710693
1447204080000000000	s78	sdb		36b82a720d31d66001b442dd788194557	4742889726
1447204080000000000	s110	memdiska						37642084
1447204080000000000	s81	sdb		36b083fe0d0bb6c001bd7c51f488e9907	4720280817

**Comment by beckettsean** [comment]
@axingblog what prompted you to close the issue?
