### ISSUE TITLE
configure the ttl of data in a database

### ISSUE THREAD

**Issue by yuankui** [influxdb/influxdb#4743]
In my circumstance, the metrics produces speed is very fast, ie 1000/qps.

so it will produces 36 million metrics per day. that's a big amount, for a single node influxdb, I think.

But in my circumstance, We only care about the most recent metrics, so we can and hope to evict the old data as soon as possible.

Is there any configuration? for a database ttl settings

**Comment by otoolep** [comment]
Everything you need to know is in the docs:

https://influxdb.com/docs/v0.9/introduction/overview.html

Specifically the documentation on retention polices, which is exactly what you want.

https://influxdb.com/docs/v0.9/query_language/database_management.html#retention-policy-management

Please send all further general questions like this to the mailing list.

https://groups.google.com/forum/#!forum/influxdb

**Comment by yuankui** [comment]
thanks @otoolep
