### ISSUE TITLE
[0.9.5_nightly_6ecb62e] Multiple [[udp]] sections in config cause panic

### ISSUE THREAD

**Issue by KiNgMaR** [influxdb/influxdb#4745]
A single [[udp]] section is working great. Adding a second one crashes in the toml parser. Possibly related: https://github.com/BurntSushi/toml/pull/68

    2015/11/11 07:15:32 InfluxDB starting, version 0.9.5-nightly-6ecb62e, branch master, commit 6ecb62e4d2f6cb9cd55a5aaa59e5273a2a48a557, built 2015-11-11T05:00:44+0000
    2015/11/11 07:15:32 Go version go1.5.1, GOMAXPROCS set to 8
    2015/11/11 07:15:32 Using configuration at: /etc/opt/influxdb/influxdb.conf
    panic: reflect: slice index out of range

    goroutine 1 [running]:
    reflect.Value.Index(0xa06f80, 0xc8201502b0, 0xd7, 0x1, 0x0, 0x0, 0x0)
            /root/.gvm/gos/go1.5.1/src/reflect/value.go:847 +0x151
    github.com/BurntSushi/toml.(*MetaData).unifySliceArray(0xc820113578, 0xa08060, 0xc8201708e0, 0x57, 0xa06f80, 0xc8201502b0, 0xd7, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:321 +0x12e
    github.com/BurntSushi/toml.(*MetaData).unifySlice(0xc820113578, 0xa08060, 0xc8201708e0, 0xa06f80, 0xc8201502b0, 0xd7, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:314 +0x253
    github.com/BurntSushi/toml.(*MetaData).unify(0xc820113578, 0xa08060, 0xc8201708e0, 0xa06f80, 0xc8201502b0, 0xd7, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:206 +0xdf7
    github.com/BurntSushi/toml.(*MetaData).unifyStruct(0xc820113578, 0xa1e3c0, 0xc82011c840, 0xc1f9c0, 0xc820150000, 0xd9, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:252 +0x69c
    github.com/BurntSushi/toml.(*MetaData).unify(0xc820113578, 0xa1e3c0, 0xc82011c840, 0xc1f9c0, 0xc820150000, 0xd9, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:200 +0xe8f
    github.com/BurntSushi/toml.Decode(0xc820155000, 0x2ac3, 0x9dff80, 0xc820120040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:114 +0x1ed
    github.com/BurntSushi/toml.DecodeFile(0x7ffe05939957, 0x1f, 0x9dff80, 0xc820120040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
            /tmp/tmp.hviQS4L7E4/src/github.com/BurntSushi/toml/decode.go:124 +0x13d
    github.com/influxdb/influxdb/cmd/influxd/run.(*Command).ParseConfig(0xc820148000, 0x7ffe05939957, 0x1f, 0x0, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:205 +0x2e8
    github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc820148000, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:84 +0x738
    main.(*Main).Run(0xc820113f00, 0xc82000a0b0, 0x4, 0x4, 0x0, 0x0)
            /tmp/tmp.hviQS4L7E4/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x6a1
    main.main()
            /tmp/tmp.hviQS4L7E4/src/github.com/influxdb/influxdb/cmd/influxd/main.go:46 +0x29b

**Comment by otoolep** [comment]
Please show us your config file. I cannot reproduce this with the following section:

```
###
### [[udp]]
###
### Controls the listeners for InfluxDB line protocol data via UDP.
###

[[udp]]
  enabled = true
  bind-address = ":2000"
  
[[udp]]
  enabled = true
  bind-address = ":2001"
  # database = ""
```

**Comment by otoolep** [comment]
Everything is fine when I build with 6ecb62e4d2f6cb9cd55a5aaa59e5273a2a48a557

**Comment by KiNgMaR** [comment]
Panic:

    ###
    ### [[udp]]
    ###
    ### Controls the listeners for InfluxDB line protocol data via UDP.
    ###

    [[udp]]
      enabled = true
      bind-address = "10.100.20.40:4444"
      database = "offer_prod"
      batch-size = 10000
      batch-timeout = "5s"

    [[udp]]
      enabled = false
      bind-address = "10.100.20.40:4445"
      database = "offer_nonprod"
      batch-size = 1000
      batch-timeout = "10s"

      # bind-address = ""
      # database = "udp"
      # retention-policy = ""

      # These next lines control how batching works. You should have this enabled
      # otherwise you could get dropped metrics or poor performance. Batching
      # will buffer points in memory if you have many coming in.

      # batch-size = 1000 # will flush if this many points get buffered
      # batch-pending = 5 # number of batches that may be pending in memory
      # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit
      # read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.


No panic:

    ###
    ### [[udp]]
    ###
    ### Controls the listeners for InfluxDB line protocol data via UDP.
    ###

    [[udp]]
      enabled = true
      bind-address = "10.100.20.40:4444"
      database = "offer_prod"
      batch-size = 10000
      batch-timeout = "5s"

    #[[udp]]
    #  enabled = false
    #  bind-address = "10.100.20.40:4445"
    #  database = "offer_nonprod"
    #  batch-size = 1000
    #  batch-timeout = "10s"

      # bind-address = ""
      # database = "udp"
      # retention-policy = ""

      # These next lines control how batching works. You should have this enabled
      # otherwise you could get dropped metrics or poor performance. Batching
      # will buffer points in memory if you have many coming in.

      # batch-size = 1000 # will flush if this many points get buffered
      # batch-pending = 5 # number of batches that may be pending in memory
      # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit
      # read-buffer = 0 # UDP Read buffer size, 0 means OS default. UDP listener will fail if set above OS max.

**Comment by KiNgMaR** [comment]
Was running b2e99c1 before, no panic there.

**Comment by otoolep** [comment]
Thanks for the report @KiNgMaR -- I can repro this issue. I suspect 4f8b0aca

**Comment by otoolep** [comment]
Thanks again @KiNgMaR for this important bug report. I have reverted the change on our side that caused this (unfortunately) and we will have to wait for the toml parsing to be fixed.
