### ISSUE TITLE
[0.9.4.2]runtime: out of memory on write 

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4746]
Hi 

Had the following error this morning whilst writing data to 0.9.4.2 
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58aa0, 0x16)
        /home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc7dfa0c000, 0x45a0000, 0xcfa0a50000, 0x1023658)
        /home/philip/.gvm/gos/go1.5/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_MapBits(0x1003980, 0xd02be50000)
        /home/philip/.gvm/gos/go1.5/src/runtime/mbitmap.go:144 +0xcc
runtime.mHeap_SysAlloc(0x1003980, 0x8b400000, 0xffffffffd4a33ff0)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:424 +0x186
runtime.mHeap_Grow(0x1003980, 0x45a00, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x1003980, 0x459ff, 0x100)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x1003980, 0x459ff, 0x100000000, 0xcb00000001)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7ff284f21d88)
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x1003980, 0x459ff, 0x10100000000, 0xc820018000)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x8b3fcbec, 0x1, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:745 +0xb3
runtime.mallocgc.func3()
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:634 +0x33
runtime.systemstack(0xc82001c000)
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /home/philip/.gvm/gos/go1.5/src/runtime/proc1.go:674


goroutine 76 [running]:
runtime.systemstack_switch()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:216 fp=0xcb4358b4e8 sp=0xcb4358b4e0
runtime.mallocgc(0x8b3fcbec, 0x9bd800, 0x65756c6100000001, 0x312038302e35313d)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:635 +0x9c4 fp=0xcb4358b5b8 sp=0xcb4358b4e8
runtime.newarray(0x9bd800, 0x8b3fcbec, 0x616e205c6e6d756c)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:777 +0xc9 fp=0xcb4358b5f8 sp=0xcb4358b5b8
runtime.makeslice(0x9a6700, 0x8b3fcbec, 0x8b3fcbec, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/slice.go:32 +0x165 fp=0xcb4358b648 sp=0xcb4358b5f8
github.com/golang/snappy.Encode(0x0, 0x0, 0x0, 0xce4ee66000, 0x775b40f8, 0xd37b2cc3, 0x0, 0x0, 0x0)
        /tmp/build/src/github.com/golang/snappy/encode.go:84 +0xb0 fp=0xcb435ab6e0 sp=0xcb4358b648
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).writeSeries(0xc8bd762e00, 0xcb25599110, 0xc9950e5bf0, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:331 +0x151 fp=0xcb435ab7a8 sp=0xcb435ab6e0
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).writeNewSeries(0xc8bd762e00, 0xcb25599110, 0xcb698cc000, 0x2f0a, 0x3000, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:322 +0x16c fp=0xcb435ab820 sp=0xcb435ab7a8
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).WriteIndex.func1(0xcb25599110, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:241 +0x87 fp=0xcb435ab9c0 sp=0xcb435ab820
github.com/boltdb/bolt.(*DB).Update(0xc8e180f380, 0xcb435aba38, 0x0, 0x0)
        /tmp/build/src/github.com/boltdb/bolt/db.go:547 +0xb3 fp=0xcb435aba18 sp=0xcb435ab9c0
github.com/influxdb/influxdb/tsdb/engine/bz1.(*Engine).WriteIndex(0xc8bd762e00, 0x0, 0xca4c9b4330, 0xcb698cc000, 0x2f0a, 0x3000, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/bz1/bz1.go:254 +0x86 fp=0xcb435aba78 sp=0xcb435aba18
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).flushMetadata(0xc88177e620, 0x0, 0x0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:688 +0x8d4 fp=0xcb435abd58 sp=0xcb435aba78
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc88177e620, 0xc98d20a0c0)
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:616 +0x3be fp=0xcb435abf40 sp=0xcb435abd58
runtime.goexit()
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1 fp=0xcb435abf48 sp=0xcb435abf40
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

```

**Comment by jakefoster** [comment]
+1 on this exact crash (happened twice in the past 12 hours)

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58aa0, 0x16)
	/home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90

**Comment by jakefoster** [comment]
UPDATE: Seems to happen every twelve hours or so in my environment under what I would consider to be light load: <200 writes per minute.  AWS t2.small instance running Ubuntu 14.04.

**Comment by otoolep** [comment]
t2.small has only 2GB of RAM. Depending on the cardinality of your data (# tags and their values) this could easily eat that up. We need more information about the data you are sending in.

**Comment by jakefoster** [comment]
Thanks for the quick reply.

Thought I could get away with the t2.small since I'm not dealing with much throughput.  Weirdly, the service now fails to start with the following:

[monitor] 2015/11/15 05:28:32 failed to set default retention policy on '_internal', terminating storage: read response size: read tcp 127.0.0.1:42571->127.0.0.1:8088: read: connection reset by peer
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc58aa0, 0x16)
        /home/philip/.gvm/gos/go1.5/src/runtime/panic.go:527 +0x90
runtime.sysMap(0xc879b50000, 0x16370000, 0x4cf6200, 0x10235f8)
        /home/philip/.gvm/gos/go1.5/src/runtime/mem_linux.go:143 +0x9b
runtime.mHeap_SysAlloc(0x1003980, 0x16370000, 0xc820015220)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:423 +0x160
runtime.mHeap_Grow(0x1003980, 0xb1b8, 0x0)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:628 +0x63
runtime.mHeap_AllocSpanLocked(0x1003980, 0xb1b6, 0xc85e75f4d0)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:532 +0x5f1
runtime.mHeap_Alloc_m(0x1003980, 0xb1b6, 0x100000000, 0xc81ff8bd48)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:425 +0x1ac
runtime.mHeap_Alloc.func1()
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:484 +0x41
runtime.systemstack(0x7f63e37f2de8)
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:278 +0xab
runtime.mHeap_Alloc(0x1003980, 0xb1b6, 0x10100000000, 0x20)
        /home/philip/.gvm/gos/go1.5/src/runtime/mheap.go:485 +0x63
runtime.largeAlloc(0x1636bb09, 0xc800000001, 0xc8200e6078)
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:745 +0xb3
runtime.mallocgc.func3()
        /home/philip/.gvm/gos/go1.5/src/runtime/malloc.go:634 +0x33
runtime.systemstack(0xc820014000)
        /home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
        /home/philip/.gvm/gos/go1.5/src/runtime/proc1.go:674

**Comment by otoolep** [comment]
Can you try upgrading to 0.9.5-rc2? Bugs related to what you were seeing were fixed after 0.9.4.2 was released.

**Comment by jakefoster** [comment]
Yes - can and will upgrade.  Working on migrating to a bigger instance first.  Thanks again for the responsiveness!

**Comment by jakefoster** [comment]
Update: Upgraded VM to c4.large and everything is holding steady for now.  Next is .9.5.x upgrade.  Will update then.

Eventually we'll move to the full recommended AWS config mentioned in the Influx docs.  For now we're trying to keep it simple (and cheap... :)

Again, thanks for the support on this one.  I totally own responsibility for this.  My one minor suggestion here is to push HW config requirements (at least the min 8 GB one) up higher so that it's really obvious for the impatient and the "doc skimmers" like myself.

**Comment by pauldix** [comment]
Closing this one out since it looks like it's fixed. We'll update the docs and information with recommended hardware. We also have a "frequently encountered issues" page going up soon that will talk about this.

**Comment by jakefoster** [comment]
Thanks Paul.  I hope we're good here!
