### ISSUE TITLE
[0.9.4.2] failed to store statistics on startup 

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4747]
HI Guys, 

When restarting the Database I frequently see the following error: 

[monitor] 2015/11/11 06:20:54 failed to store statistics: timeout

Is there anything I can do to fix this type of error?

**Comment by otoolep** [comment]
This error is relatively harmless. Once the database is fully initialized these errors will stop.

This issue should no longer occur once tsm1 is released.

**Comment by otoolep** [comment]
These errors should no longer occur with tsm1.

**Comment by otoolep** [comment]
Try the latest code 0.9.6. and tsm1.
