### ISSUE TITLE
[0.9.5-nightly] Weird values for a field name `counter`

### ISSUE THREAD

**Issue by caligula1989** [influxdb/influxdb#4748]
BEFORE ANYTHING: **I am using  version 0.9.5-nightly-6682752.**

I have a field named `counter`, which ALWAYS has a value of 1 (that's hard coded in the only place I use to write data to influxdb).

Running sum(counter) and count(counter) yield very different results:
```
> select count(counter), sum(counter) from request
name: request
-------------
time    count   sum
0       704553  1005290
```
However I can't find points with a counter that isn't 1:
```
> select * from request where counter != 1
```

But when querying without the * - apparently there are points with such a counter:
```
> select counter from request where counter != 1 limit 10
name: request
-------------
time                    counter
1447165108241315971     202
1447165108384590078     203
1447165108439296904     6
1447165109509690769     203
1447165109730234222     202
1447165110074731967     203
1447165110559640333     203
1447165111029257479     5
1447165111700766181     5
1447165112291525729     202
```
The values here are typical values of a different field I have.

**Comment by beckettsean** [comment]
@caligula1989 this sounds more like an issue with the write syntax than anything else. `counter` isn't a reserved word.

Can you share how you are writing points to the database? Particularly in light of "The values here are typical values of a different field I have." That makes me think somehow the write path is confusing the inputs.
