### ISSUE TITLE
influx client exits if it doesn't connect to a server when launching

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#4767]
Currently, if you invoke the `influx` cli and it can't connect to the default `localhost:8086` the program exits.

It should show the warning, but not exit, as you may not have a server on that port.

```
$ influx
Failed to connect to http://localhost:8086
Please check your connection settings and ensure 'influxd' is running.
```

**Comment by otoolep** [comment]
It's been like this for a while. Remember I fixed the bug where we were actually trying to connect?

**Comment by otoolep** [comment]
When I fixed it, it exited, you reviewed the code. :-)

**Comment by otoolep** [comment]
I actually think it should exit. Other CLIs do the same thing:

```
~ $ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by corylanou** [comment]
Ok, after thinking about this I'm fine with it.  You can easily pass `-host` and `-port` if you want to connect to a different server.
