### ISSUE TITLE
v0.9.5-rc2 - Thank you

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb#4779]
Will there be a RPM, or - how do we compile influxdb from source.

**Comment by otoolep** [comment]
Just check out the 0.9.5 branch and compile as per the CONTRIBUTING.md doc. Packages will be available very soon.

**Comment by skynet** [comment]
:+1:

**Comment by rossmcdonald** [comment]
@skynet RPM for 0.9.5 RC2 available here:

https://s3.amazonaws.com/influxdb/influxdb-0.9.5-0.1.rc2.x86_64.rpm
