### ISSUE TITLE
[0.9.5-nightly] installs influxdb-0.9.6_nightly_664b20e-1.x86_64

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4782]
Hi, 

I have just downloaded the latest nightly version, and it seems to be version 0.9.6 (rather than 0.9.5) 

https://s3.amazonaws.com/influxdb/influxdb-nightly-1.x86_64.rpm

Am I using the right download? 

Also the CLI seems to have disappeared: 

[root@RBC-visual-edge pe]# ls /opt/influxdb/influx
/opt/influxdb/influx

**Comment by skynet** [comment]
Master was switched to v 0.9.6. We are all waiting for a v0.9.5-rc2 rpm.

**Comment by corylanou** [comment]
It's part of our our release process works.  We create a release branch that has a release candidate on it, and lock it down.  We move master to the next point release so development can continue while the release candidate is finalized.  I can see how this is confusing.  I'll see if we can get some clarification in our documents on how our release cycles work.  /cc @beckettsean @otoolep

**Comment by ivanscattergood** [comment]
I can see there is a influxdb-0.9.5-0.1.rc2.x86_64.rpm that was updated this morning, should I be using that? 

I am keen to use a version with the fix for #4701

**Comment by corylanou** [comment]
It is on master (which should be in the nightly):

https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#bugfixes-1

**Comment by ivanscattergood** [comment]
I am hoping that it won’t be there until tonight’s build? As the nightly I installed a few hours ago didn’t fix my problem.




Ivan Scattergood



Business Driven IT



Office:  +44(0)207 0971639
Mobile:  +44 (0)7813 79 7753
Skype:  BusinessDrivenIT



Ivan@BusinessDrivenIT.com<mailto:Ivan@BusinessDrivenIT.com>



http://www.BusinessDrivenIT.com<http://www.businessdrivenit.com/>

**Comment by rossmcdonald** [comment]
@ivanscattergood That fix should be in the new RC:

https://s3.amazonaws.com/influxdb/influxdb-0.9.5-0.1.rc2.x86_64.rpm

If not, there is a nightly available here: 

https://s3-us-west-1.amazonaws.com/influxdb-nightly/influxdb-nightly.x86_64.rpm

That is current with `master` up to a few hours ago.

**Comment by beckettsean** [comment]
@ivanscattergood the fix for #4701 that is in RC2 is not complete. The main bug is still present and I reproduced it this morning with 0.9.5-RC2, just to save you some time.

**Comment by beckettsean** [comment]
> Also the CLI seems to have disappeared

@rossmcdonald can you shed light on what might have happened there? Perhaps the symlink didn't work?

**Comment by rossmcdonald** [comment]
> Also the CLI seems to have disappeared:

The location of the InfluxDB binaries has been moved to `/usr/bin` with this release, so (assuming `/usr/bin` is on your path) then all you should have to do is run `influx` from the CLI from now on. This is mentioned as a breaking change in the CHANGELOG here:

https://github.com/influxdb/influxdb/blob/0.9.5/CHANGELOG.md#release-notes

**Comment by ivanscattergood** [comment]
@rossmcdonald Awesome thanks! 

@beckettsean @corylanou I have now had a chance to read the Blog update. I'll try and be a bit more patient in future
