### ISSUE TITLE
Disabling verbose openTSDB logging

### ISSUE THREAD

**Issue by razb** [influxdb/influxdb#4783]
I have the opentsdb plugin enabled and I am getting warning output for each point being written. It does appear to be accepting the data, however the log  gets somewhat large given the volume of data being pushed in...

its been running for a few hours and its up over 50GB so far. Is there a way to limit logging to errors?

**Comment by otoolep** [comment]
Can you show us a sample of the errors you are seeing?

**Comment by beckettsean** [comment]
@razb please do share the exact errors from the logs, as well as the version of InfluxDB you are running.

**Comment by razb** [comment]
The error appears to be for each put request:

<code>[opentsdb] 2015/11/13 17:24:29 malformed line '' from 10.219.3.65:59997</code>

This is from 0.95 nightly build

<code>0.9.5-nightly-905437c</code>

Its possible that the requests are indeed malformed. I'm just hoping that I can disable the logging until I figure out where the error is originating. At 20k requests a second, the log file builds up awfully fast.

**Comment by otoolep** [comment]
Unfortunately these log messages cannot be disabled right now. We had assumed anyone hitting these would fix their systems and it wouldn't happen that much.

However, it's an easy change.

**Comment by otoolep** [comment]
This feature will be available in tonight's nightly.

https://github.com/influxdb/influxdb/blob/master/etc/config.sample.toml#L280
