### ISSUE TITLE
[0.9.5-0.2.rc2] Unable to download

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4784]
I am unable to download 

https://s3.amazonaws.com/influxdb/influxdb-0.9.5-0.2.rc2.x86_64.rpm

Is the path correct on your download page?

**Comment by rossmcdonald** [comment]
@ivanscattergood Thanks for letting us know. We are about to push a fix that corrects the link to:

https://s3.amazonaws.com/influxdb/influxdb-0.9.5-0.1.rc2.x86_64.rpm
