### ISSUE TITLE
Build issue on Solaris

### ISSUE THREAD

**Issue by fazalmajid** [influxdb/influxdb#4787]
tsdb/engine/tsm1/tsm1.go is using the obsolete syscall.Mmap and Munmap instead of golang.org/x/sys/unix.Mmap like BoltDB.

Compilation fails with:

    local64 ~/build/influxdb-0.9.4.2/src/github.com/influxdb/influxdb>go build ./...
    # github.com/influxdb/influxdb/tsdb/engine/tsm1
    tsdb/engine/tsm1/tsm1.go:1974: undefined: syscall.Mmap
    tsdb/engine/tsm1/tsm1.go:2033: undefined: syscall.Munmap

See:
* https://github.com/golang/go/issues/11113
* https://github.com/boltdb/bolt/issues/345

**Comment by pauldix** [comment]
Can you try to build this against master now? We just removed a bunch of stuff that may have caused this problem.

**Comment by fazalmajid** [comment]
@pauldix yes, I had to create a Solaris-specific mmap_solaris.go (straight copy-paste job from the BoltDB version), and tsm1 now passes its unit tests. Thanks for the help!.

The pull request is #5027

**Comment by pauldix** [comment]
merged, will go into the 0.9.6 release
