### ISSUE TITLE
[0.9.6-nightly] A single continuous query for many fields

### ISSUE THREAD

**Issue by bwhaley** [influxdb/influxdb#4793]
Per [mailing list discussion](https://groups.google.com/forum/#!topic/influxdb/T9uimWSVm88):

Is it possible to create a continuous query for a bunch of fields at the same time? 

Ideally something like this would roll up 1 hour groups of mean() for each field in load, giving each field the same name in the 4weeks retention policy:

```
create continuous query "1h_rollup" on mydb begin 
  select mean(*) into "4weeks".load from load group by time(1h),* 
end
```

Of course that's not supported by mean(), but I did expect this to work:

```
create continuous query "1h_rollup" on mydb begin 
  select mean(shortterm) as shortterm,mean(midterm) as midterm,mean(longterm) as longterm into "4weeks".load from load group by time(1h),* 
end
```

That seems to do nothing. Instead I must have a separate CQ for each field:

```
> show continuous queries
name: mydb
----------------
name query
1h_rollup_short CREATE CONTINUOUS QUERY "1h_rollup_short" ON mydb BEGIN SELECT mean(shortterm) AS "shortterm" INTO "mydb"."4weeks".load FROM "mydb"."1week".load GROUP BY time(1h), * END
1h_rollup_long CREATE CONTINUOUS QUERY "1h_rollup_long" ON mydb BEGIN SELECT mean(longterm) AS "longterm" INTO "mydb"."4weeks".load FROM "mydb"."1week".load GROUP BY time(1h), * END
1h_rollup_mid CREATE CONTINUOUS QUERY "1h_rollup_mid" ON mydb BEGIN SELECT mean(midterm) AS "midterm" INTO "mydb"."4weeks".load FROM "mydb"."1week".load GROUP BY time(1h), * END
```

This seems inefficient, especially when it must be done for every field in every measurement.

A nice feature would be to do the same thing for all fields, all measurements. I'd like to have a downsampled version of my database so queries over longer intervals are faster. The current CQ system can work for this but requires creating a query for each.

**Comment by bwhaley** [comment]
`InfluxDB shell 0.9.6-nightly-664b20e`

**Comment by beckettsean** [comment]
@jackzampolin can you attempt a repro on the latest 0.9.6 nightly?

**Comment by jackzampolin** [comment]
Also running 0.9.6-nightly.  Was unable to reproduce. Below is command line output.
```
> insert foo,thing=thing field1=1,field2=1,field3=1
> insert foo,thing=thing field1=2,field2=2,field3=2
> insert foo,thing=thing field1=3,field2=4,field3=3
> insert foo,thing=thing field1=4,field2=4,field3=4
> insert foo,thing=thing field1=5,field2=5,field3=5
> insert foo,thing=thing field1=6,field2=6,field3=6
> insert foo,thing=thing field1=7,field2=7,field3=7
> insert foo,thing=thing field1=8,field2=8,field3=8
> insert foo,thing=thing field1=9,field2=9,field3=9
> insert foo,thing=thing field1=10,field2=10,field3=10
> select mean(field1), mean(field2), mean(field3) from foo
name: foo
---------
time	mean	mean	mean
0	    5.5     5.6     5.5
 
> create continuous query "foo_rollup" on mydb begin select mean(field1) as field1, mean(field2) as field2, mean(field3) as field3 into foo_derived from foo group by time(5m) end
> select * from foo_derived
name: foo_derived
-----------------
time		        	field1	field2	field3
1447883400000000000	    5.5	    5.6	    5.5

> drop continuous query foo_rollup on mydb
> drop measurement foo_derived
> create continuous query "foo_rollup" on mydb begin select mean(field1) as field1, mean(field2) as field2, mean(field3) as field3 into foo_derived from foo group by time(5m), * end
> select * from foo_derived
name: foo_derived
-----------------
time			      field1	field2	field3	thing
1447883400000000000   5.5     	5.6	    5.5    	thing

```

**Comment by bwhaley** [comment]
Yep, seems to work for me with `0.9.6-nightly-1e9e7c2`. What about the broader question of more easily supporting rollups for all measurements on a database? It seems like it would be a common use case. 

If I have system and app level measurements (load, cpu, memory, disk, app requests, app errors, etc), I'm most likely wanting to build some dashboards for them, and I'm going to want to zoom in & out of that data. All of it. It'd be nice to have a continuous query that performed a rollup of everything at once.

**Comment by jackzampolin** [comment]
There is currently a feature that allows you to do that: https://github.com/influxdb/influxdb/issues/4775
