### ISSUE TITLE
Need official up to date guide how to build from source

### ISSUE THREAD

**Issue by sammy007** [influxdb/influxdb#4795]
I spend some time and didn't find any official guide. Could you add one?

**Comment by Wind0r** [comment]
The recommended way to get it running with the pre-built packages.
If you really want to build influxdb you can use the contributing guide.
[Contributing](https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#build-and-test)

[See the README] (https://github.com/influxdb/influxdb#building)

**Comment by otoolep** [comment]
Thanks @Wind0r
