### ISSUE TITLE
tsm1 in v0.9.5-rc2

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb#4797]
Is tsm1 included in v0.9.5-rc2. Previous storage engines take up a ridiculous amount of disk space.

**Comment by otoolep** [comment]
Yes it is.

**Comment by otoolep** [comment]
@skynet - please send questions like this to the mailing list. GitHub tickets are not the best place for general questions about the system.

**Comment by otoolep** [comment]
Check the config file to learn how to enable it.

**Comment by skynet** [comment]
Thank you!
