### ISSUE TITLE
Can't connect to influx web ui: "admin server listening on :0"

### ISSUE THREAD

**Issue by M425** [influxdb/influxdb#4810]
I deployed influxdb on a 3-nodes-cluster but I can't access the web ui:
`version 0.9.0`
in the config file there is a section:

    [admin]
      enabled = true
      port = 8083

but in the log once I start the service it shows:
`admin server listening on :0`

i paste even the command `sudo netstat -anp | grep influx`:

    tcp        0      0 127.0.0.1:51641         127.0.0.1:8086          ESTABLISHED 13824/influxd   
    tcp        0      0 127.0.0.1:51640         127.0.0.1:8086          ESTABLISHED 13824/influxd   
    tcp6       0      0 :::47831                :::*                    LISTEN      13824/influxd   
    tcp6       0      0 :::8086                 :::*                    LISTEN      13824/influxd   
    tcp6       0      0 127.0.0.1:8086          127.0.0.1:51641         ESTABLISHED 13824/influxd   
    tcp6       0      0 127.0.0.1:8086          127.0.0.1:51640         ESTABLISHED 13824/influxd

**Comment by otoolep** [comment]
Version 0.9.0 is months old. You should upgrade to 0.9.5-rc2.

**Comment by beckettsean** [comment]
There have been no similar reports for recent versions, and we will not be releasing a patch for 0.9.0. I recommend upgrading to 0.9.4 or 0.9.5-RC3, which was just released.
