### ISSUE TITLE
How to configure multiple Collectd Clients for InfluxDB

### ISSUE THREAD

**Issue by zhaohangbo** [influxdb/influxdb#4831]
How to configure multiple Collectd Clients for InfluxDB ?
There is still no doc for Collectd Plugin Part on the https://influxdb.com/docs/v0.9/introduction/getting_started.html

**Comment by beckettsean** [comment]
GitHub Issues should be used for feature requests and bug reports. Please send questions to the [mailing list](mailto:influxdb@googlegroups.com).
