### ISSUE TITLE
[ 0.9.6-nightly-43a4201] open engine: snappy: corrupt input

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4836]
Hi, 

After a crash of the database, I have attempted a restart and got the following message: 

[tsm1wal] 2015/11/18 13:01:59 startup flush of /ext_data/influxdb/data/_internal/monitor/8 with 45 keys and 45 total values of 720 bytes
[tsm1] 2015/11/18 13:01:59 rewriting index file /ext_data/influxdb/data/_internal/monitor/8/0001427.tsm1 with /ext_data/influxdb/data/_internal/monitor/8/0001429.tsm1
[tsm1wal] 2015/11/18 13:01:59 /ext_data/influxdb/data/_internal/monitor/8 flush to index took 567.808828ms
[tsm1wal] 2015/11/18 13:02:13 tsm1 WAL starting with 5242880 flush memory size threshold and 104857600 max memory size threshold
[tsm1wal] 2015/11/18 13:02:13 tsm1 WAL writing to /ext_data/influxdb/data/open_access_db/detail/13
[tsm1wal] 2015/11/18 13:03:00 memory flush of /ext_data/influxdb/data/open_access_db/detail/13 with 613284 keys and 6725334 total values of 105331265 bytes
[tsm1wal] 2015/11/18 13:06:12 failed to flush to index: snappy: corrupt input
[registration] 2015/11/18 13:06:12 registration service terminating
[retention] 2015/11/18 13:06:12 retention policy enforcement terminating
[monitor] 2015/11/18 13:06:12 shutting down monitor system
[handoff] 2015/11/18 13:06:12 shutting down hh service
[subscriber] 2015/11/18 13:06:12 closed service
run: open server: open tsdb store: failed to open shard 13: open engine: snappy: corrupt input

**Comment by ivanscattergood** [comment]
I have moved the offending shard, and the database now starts ok

**Comment by otoolep** [comment]
tsm1 has been significantly re-written, this issue should no longer occur.
