### ISSUE TITLE
Passing version info to `go build` doesn't work

### ISSUE THREAD

**Issue by ryan-williams** [influxdb/influxdb#4847]
I build Influx from source and try to set version/commit info, but it doesn't show up when I run the built `influxd`:

```
 Thu 20:35:34  ryan@mbp: influxdb:master$ go get -u -f -t ./...
 Thu 20:36:11  ryan@mbp: influxdb:master$ sha="$( cd influxdb/ && git --no-pager log --no-walk --format='%h' HEAD )"; echo $sha
1e9e7c2
 Thu 20:36:26  ryan@mbp: influxdb:master$ now=`date +%s`; echo $now
1447965388
 Thu 20:36:28  ryan@mbp: influxdb:master$ go build -ldflags="-X main.version $sha -X main.branch master -X main.commit $sha -X main.buildTime $now" ./...
 Thu 20:36:43  ryan@mbp: influxdb:master$ go install ./...
 Thu 20:36:53  ryan@mbp: influxdb:master$ ls -l $GOPATH/bin/influx*
-rwxr-xr-x 1 ryan staff 12269780 Nov 19 20:36 /Users/ryan/c/go/bin/influx
-rwxr-xr-x 1 ryan staff 13453996 Nov 19 20:36 /Users/ryan/c/go/bin/influx_inspect
-rwxr-xr-x 1 ryan staff  7497692 Nov 19 20:36 /Users/ryan/c/go/bin/influx_stress
-rwxr-xr-x 1 ryan staff 18898900 Nov 19 20:36 /Users/ryan/c/go/bin/influxd
 Thu 20:37:00  ryan@mbp: influxdb:master$ $GOPATH/bin/influxd -config ~/influxdb.conf

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

2015/11/19 20:37:14 InfluxDB starting, version 0.9, branch unknown, commit unknown, built unknown
2015/11/19 20:37:14 Go version go1.5.1, GOMAXPROCS set to 4
```

I've tried to pass appropriate `-ldflags` to `go build` per the docs, but still get `version 0.9, branch unknown, commit unknown, built unknown`.

This is compounding problems I'm having building Influx from source at different SHAs; is there a preferred way to `go build` / `go install` a version after I'd already built/installed a different version? 

In the above excerpt, I'd `rm -rf`d all influx-related files under `go/{bin,var,pkg,src}` in an attempt to get a clean build, but `go build` finished quickly with no output, which makes me suspicious that it did anything.

However, it created `influx*` binaries in `$GOPATH/bin` seemingly as expected…

**Comment by otoolep** [comment]
You're not building the way we build, perhaps something is up there. Descend into `cmd/influxd` and run:

```
go build -ldflags="-X main.version 0.9.5 -X main.branch^Caster -X main.commit 1234 -X main.buildTime today
```

It will then work. There may be some subtlety with the Go tool chain in this case. If you determine what it is, let us know.

**Comment by atulguptaag** [comment]
Don't run "go build".

Just pass the -ldflags options to go install. The "go install ./...", as I notice in your build logs, is rebuilding the code and overwriting the executable without the flags being passed to the linker.

**Comment by otoolep** [comment]
Yep, @atulguptaag looks right to me -- thanks @atulguptaag .

@ryan-williams - closing this. Let me know if you make no progress.

**Comment by ryan-williams** [comment]
Thanks for the responses, but I'm still stuck.

[The docs say run `go build` one way](https://github.com/influxdb/influxdb/blob/3ae624e502af9262e40334cf8b346cc4f11336fe/CONTRIBUTING.md#build-and-test).
@otoolep says run it a different way.
@atulguptaag says don't run `go build`.

[Here is a gist](https://gist.github.com/ryan-williams/52c4f8f1ae37dcf40baa) of my attempting what each of you suggested, with go `1.4` and `1.5.1` each, and getting various errors that I don't know what to do with. This is my first time trying to build a `go` project so sorry if I'm just missing obvious things.

**Comment by otoolep** [comment]
@ryan-williams -- have you followed the step-by-step directions in CONTRIBUTING.md? From looking at your log you haven't followed the steps correctly because `GOPATH` is not set correctly. Can you try again?

Also you don't need to set the version etc for the build to work.

**Comment by otoolep** [comment]
https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#getting-the-source

**Comment by otoolep** [comment]
@ryan-williams -- I tweaked the instructions slightly to make them even more clear. Please try again.

**Comment by ryan-williams** [comment]
> have you followed the step-by-step directions in CONTRIBUTING.md?

Yes, I'd followed those steps. `$GOPATH` was set to a local directory that I was working in, albeit not `$HOME/gocodez` but rather `$HOME/c/go`, and I had run `go get -u -f -t ./...` since setting it.

[Here is another gist](https://gist.github.com/ryan-williams/c672bc0d078791350702) showing all the steps from CONTRIBUTING.md in order, and the resulting `influxd` reflecting none of the info that I'd passed in `-ldflags`.

One strange-seeming thing is that the `influxd` in `$GOPATH/bin` [is timestamped](https://gist.github.com/ryan-williams/c672bc0d078791350702#file-gistfile1-txt-L23) around [the time that I ran `go get -u -f -t ./...`](https://gist.github.com/ryan-williams/c672bc0d078791350702#file-gistfile1-txt-L14), and not when I later ran `go install`.

**Comment by otoolep** [comment]
Remove the binary in `$GOPATH/bin` first. Does it work for you then?

**Comment by atulguptaag** [comment]
@ryan-williams - you may want to run "go clean ./..." between go get and go install and check if that solves the issue for you.

**Comment by otoolep** [comment]
Thanks @atulguptaag -- do you recommend we add that step to our CONTRIBUTING.md file?

**Comment by atulguptaag** [comment]
Yes, I would. That's how I build InfluxDB from source and I have seen the version, branch and commit information compiled into the executable.

**Comment by ryan-williams** [comment]
Running `go clean ./...`, `rm -rf $GOPATH/bin/influx*`, and then `go install -ldflags="-X main.version $sha -X main.branch master -X main.commit $sha -X main.buildTime $now" ./...` seems to give me an `influxd` in `$GOPATH/bin` that has the build info set appropriately.

**Comment by mvadu** [comment]
@otoolep I think you need to update Contributing.md to say the difference in ldflags format based on go version. The current prescribed go version for Influx is 1.4.3, and it uses `variable value` format, while the docs say `variable=value`, which is opt for go 1.5.
