### ISSUE TITLE
TestCluster_OpenRaft is timeout

### ISSUE THREAD

**Issue by runner-mei** [influxdb/influxdb#4853]
````
=== RUN   TestCluster_OpenRaft
[metastore] 2015/11/20 22:50:53 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\0
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57193 [Follower]
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57193 [Leader]. peers=[]
[metastore] 2015/11/20 22:50:54 Created local node: id=1, host=127.0.0.1:57193
[metastore] 2015/11/20 22:50:54 spun up monitoring for 1
[metastore] 2015/11/20 22:50:54 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\1
[metastore] 2015/11/20 22:50:54 Node at 127.0.0.1:57215 [Follower]
[metastore] 2015/11/20 22:50:54 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:54 adding new raft peer: nodeId=2 addr=127.0.0.1:57215
[metastore] 2015/11/20 22:50:54 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:54 nodeId=2 raftEnabled=true peers=[127.0.0.1:57215 127.0.0.1:57193]
[metastore] 2015/11/20 22:50:54 spun up monitoring for 2
[metastore] 2015/11/20 22:50:54 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\2
[metastore] 2015/11/20 22:50:54 Updated node id=2 hostname=127.0.0.1:57215
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57220 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 adding new raft peer: nodeId=3 addr=127.0.0.1:57220
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=3 raftEnabled=true peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Updated node id=3 hostname=127.0.0.1:57220
[metastore] 2015/11/20 22:50:55 spun up monitoring for 3
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\3
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57224 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=4 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 spun up monitoring for 4
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\4
[metastore] 2015/11/20 22:50:55 Updating metastore to term=1 index=7
[metastore] 2015/11/20 22:50:55 Updated node id=4 hostname=127.0.0.1:57224
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57229 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=5 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 Updating metastore to term=1 index=8
[metastore] 2015/11/20 22:50:55 spun up monitoring for 5
[metastore] 2015/11/20 22:50:55 Updated node id=5 hostname=127.0.0.1:57229
[metastore] 2015/11/20 22:50:55 Using data dir: C:\Users\meifakun\AppData\Local\Temp\influxdb-meta-156530767\5
[metastore] 2015/11/20 22:50:55 Node at 127.0.0.1:57234 [Follower]
[metastore] 2015/11/20 22:50:55 Joining cluster at: [127.0.0.1:57193]
[metastore] 2015/11/20 22:50:55 Joined remote node 127.0.0.1:57193
[metastore] 2015/11/20 22:50:55 nodeId=6 raftEnabled=false peers=[127.0.0.1:57220 127.0.0.1:57193 127.0.0.1:57215]
[metastore] 2015/11/20 22:50:55 Switching to remote raft
[metastore] 2015/11/20 22:50:55 spun up monitoring for 6
[metastore] 2015/11/20 22:50:55 database 'db0' created
[metastore] 2015/11/20 22:50:55 database 'db1' created
[metastore] 2015/11/20 22:50:56 database 'db2' created
*** Test killed: ran too long (10m0s).
FAIL    github.com/influxdb/influxdb/meta       600.444s
````

**Comment by runner-mei** [comment]
goroutine profile: total 82
1 @ 0x5a44bf 0x5a428a 0x59fafb 0x731e45 0x732067 0x710051 0x7118e4 0x712355 0x70faf5 0x45ebb1
#	0x5a44bf	runtime/pprof.writeRuntimeProfile+0xbf	c:/go/src/runtime/pprof/pprof.go:545
#	0x5a428a	runtime/pprof.writeGoroutine+0x9a	c:/go/src/runtime/pprof/pprof.go:507
#	0x59fafb	runtime/pprof.(*Profile).WriteTo+0xdb	c:/go/src/runtime/pprof/pprof.go:236
#	0x731e45	net/http/pprof.handler.ServeHTTP+0x385	c:/go/src/net/http/pprof/pprof.go:199
#	0x732067	net/http/pprof.Index+0x207		c:/go/src/net/http/pprof/pprof.go:211
#	0x710051	net/http.HandlerFunc.ServeHTTP+0x41	c:/go/src/net/http/server.go:1422
#	0x7118e4	net/http.(*ServeMux).ServeHTTP+0x184	c:/go/src/net/http/server.go:1699
#	0x712355	net/http.serverHandler.ServeHTTP+0x1a5	c:/go/src/net/http/server.go:1862
#	0x70faf5	net/http.(*conn).serve+0xbf5		c:/go/src/net/http/server.go:1361

1 @ 0x42f5fc 0x42f6cb 0x404240 0x403d7b 0x4837b4 0x4822f7 0x40129d 0x42f1ee 0x45ebb1
#	0x4837b4	testing.RunTests+0x8b4	c:/go/src/testing/testing.go:562
#	0x4822f7	testing.(*M).Run+0x77	c:/go/src/testing/testing.go:494
#	0x40129d	main.main+0x11d		github.com/influxdb/influxdb/meta/_test/_testmain.go:308
#	0x42f1ee	runtime.main+0x27e	c:/go/src/runtime/proc.go:111

1 @ 0x42f5fc 0x42f6cb 0x42f3e6 0x45ebb1
#	0x42f5fc	runtime.gopark+0x17c		c:/go/src/runtime/proc.go:186
#	0x42f6cb	runtime.goparkunlock+0x5b	c:/go/src/runtime/proc.go:191
#	0x42f3e6	runtime.forcegchelper+0xc6	c:/go/src/runtime/proc.go:152

1 @ 0x42f5fc 0x42f6cb 0x41e2cb 0x45ebb1
#	0x42f5fc	runtime.gopark+0x17c		c:/go/src/runtime/proc.go:186
#	0x42f6cb	runtime.goparkunlock+0x5b	c:/go/src/runtime/proc.go:191
#	0x41e2cb	runtime.bgsweep+0x15b		c:/go/src/runtime/mgcsweep.go:67

1 @ 0x42f5fc 0x42f6cb 0x415d98 0x45ebb1
#	0x42f5fc	runtime.gopark+0x17c		c:/go/src/runtime/proc.go:186
#	0x42f6cb	runtime.goparkunlock+0x5b	c:/go/src/runtime/proc.go:191
#	0x415d98	runtime.runfinq+0xb8		c:/go/src/runtime/mfinal.go:154

1 @ 0x40f0c4 0x440a39 0x807baf 0x45ebb1
#	0x807baf	os/signal.loop+0x1f	c:/go/src/os/signal/signal_unix.go:22

1 @ 0x40f0c4 0x44999c 0x45ebb1
#	0x40f0c4	runtime.notetsleepg+0x94	c:/go/src/runtime/lock_sema.go:265
#	0x44999c	runtime.timerproc+0xec		c:/go/src/runtime/time.go:209

1 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x62ff7e 0x643b8b 0x560a76 0x66743b 0x667548 0x49cfd7 0x49aee7 0x4a2350 0x4b6f6d 0x4a2c87 0x4b85e4 0x4b83b5 0x4b7383 0x4b2684 0x50764f 0x502f12 0x48222f 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67						c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41						c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177						c:/go/src/net/fd_windows.go:182
#	0x62ff7e	net.(*netFD).Read+0x17e							c:/go/src/net/fd_windows.go:463
#	0x643b8b	net.(*conn).Read+0xeb							c:/go/src/net/net.go:172
#	0x560a76	bytes.(*Buffer).ReadFrom+0x246						c:/go/src/bytes/buffer.go:173
#	0x66743b	io/ioutil.readAll+0x15b							c:/go/src/io/ioutil/ioutil.go:33
#	0x667548	io/ioutil.ReadAll+0x58							c:/go/src/io/ioutil/ioutil.go:42
#	0x49cfd7	github.com/influxdb/influxdb/meta.(*rpc).call+0xc97			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:465
#	0x49aee7	github.com/influxdb/influxdb/meta.(*rpc).fetchMetaData+0x387		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:354
#	0x4a2350	github.com/influxdb/influxdb/meta.(*remoteRaft).invalidate+0x50		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/state.go:392
#	0x4b6f6d	github.com/influxdb/influxdb/meta.(*Store).invalidate+0x4d		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1651
#	0x4a2c87	github.com/influxdb/influxdb/meta.(*remoteRaft).sync+0x37		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/state.go:487
#	0x4b85e4	github.com/influxdb/influxdb/meta.(*Store).sync+0x64			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1739
#	0x4b83b5	github.com/influxdb/influxdb/meta.(*Store).remoteExec+0xea5		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1730
#	0x4b7383	github.com/influxdb/influxdb/meta.(*Store).exec+0x3e3			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1669
#	0x4b2684	github.com/influxdb/influxdb/meta.(*Store).CreateDatabase+0x104		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1001
#	0x50764f	github.com/influxdb/influxdb/meta_test.assertDatabaseReplicated+0x1af	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store_test.go:1392
#	0x502f12	github.com/influxdb/influxdb/meta_test.TestCluster_OpenRaft+0x322	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store_test.go:973
#	0x48222f	testing.tRunner+0x9f							c:/go/src/testing/testing.go:456

1 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x63115c 0x6316c3 0x64b944 0x713258 0x71262a 0x7124ed 0x712bb6 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67			c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41			c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177			c:/go/src/net/fd_windows.go:182
#	0x63115c	net.(*netFD).acceptOne+0x26c			c:/go/src/net/fd_windows.go:564
#	0x6316c3	net.(*netFD).accept+0x173			c:/go/src/net/fd_windows.go:594
#	0x64b944	net.(*TCPListener).AcceptTCP+0x54		c:/go/src/net/tcpsock_posix.go:254
#	0x713258	net/http.tcpKeepAliveListener.Accept+0x48	c:/go/src/net/http/server.go:2135
#	0x71262a	net/http.(*Server).Serve+0xba			c:/go/src/net/http/server.go:1887
#	0x7124ed	net/http.(*Server).ListenAndServe+0x13d		c:/go/src/net/http/server.go:1877
#	0x712bb6	net/http.ListenAndServe+0x96			c:/go/src/net/http/server.go:1967

6 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x63115c 0x6316c3 0x64b944 0x64bb94 0x732512 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67				c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41				c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177				c:/go/src/net/fd_windows.go:182
#	0x63115c	net.(*netFD).acceptOne+0x26c				c:/go/src/net/fd_windows.go:564
#	0x6316c3	net.(*netFD).accept+0x173				c:/go/src/net/fd_windows.go:594
#	0x64b944	net.(*TCPListener).AcceptTCP+0x54			c:/go/src/net/tcpsock_posix.go:254
#	0x64bb94	net.(*TCPListener).Accept+0x44				c:/go/src/net/tcpsock_posix.go:264
#	0x732512	github.com/influxdb/influxdb/tcp.(*Mux).Serve+0x52	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:48

6 @ 0x42f5fc 0x42f6cb 0x404240 0x403dab 0x733266 0x4bd5e8 0x673e60 0x45ebb1
#	0x733266	github.com/influxdb/influxdb/tcp.(*listener).Accept+0x76	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:129
#	0x4bd5e8	github.com/influxdb/influxdb/meta.(*raftLayer).Accept+0x58	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:2298
#	0x673e60	github.com/hashicorp/raft.(*NetworkTransport).listen+0x80	F:/developing/go/influxdb/src/github.com/hashicorp/raft/net_transport.go:346

1 @ 0x42f5fc 0x43dcb2 0x43d202 0x67f585 0x67e1e5 0x67c272 0x68fff7 0x69102b 0x45ebb1
#	0x67f585	github.com/hashicorp/raft.(*Raft).leaderLoop+0xcd5				F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:826
#	0x67e1e5	github.com/hashicorp/raft.(*Raft).runLeader+0x895				F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:798
#	0x67c272	github.com/hashicorp/raft.(*Raft).run+0xc2					F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:595
#	0x68fff7	github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm+0x27	F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:245
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b			F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

3 @ 0x42f5fc 0x43dcb2 0x43d202 0x67c1a2 0x690037 0x69102b 0x45ebb1
#	0x67c1a2	github.com/hashicorp/raft.(*Raft).runFSM+0x10f2					F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:502
#	0x690037	github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm+0x27	F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:246
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b			F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

3 @ 0x42f5fc 0x43dcb2 0x43d202 0x687b8a 0x690077 0x69102b 0x45ebb1
#	0x687b8a	github.com/hashicorp/raft.(*Raft).runSnapshots+0x49a					F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:1613
#	0x690077	github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm+0x27	F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:247
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b				F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

3 @ 0x42f5fc 0x43dcb2 0x43d202 0x4a0efc 0x45ebb1
#	0x4a0efc	github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges+0x4fc	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/state.go:192

6 @ 0x42f5fc 0x42f6cb 0x404240 0x403dab 0x733266 0x4b0675 0x45ebb1
#	0x733266	github.com/influxdb/influxdb/tcp.(*listener).Accept+0x76		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:129
#	0x4b0675	github.com/influxdb/influxdb/meta.(*Store).serveExecListener+0xb5	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:737

6 @ 0x42f5fc 0x42f6cb 0x404240 0x403dab 0x733266 0x4b1619 0x45ebb1
#	0x733266	github.com/influxdb/influxdb/tcp.(*listener).Accept+0x76		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/tcp/mux.go:129
#	0x4b1619	github.com/influxdb/influxdb/meta.(*Store).serveRPCListener+0xa9	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:847

6 @ 0x42f5fc 0x43dcb2 0x43d202 0x4ada69 0x45ebb1
#	0x4ada69	github.com/influxdb/influxdb/meta.(*Store).monitorPeerHealth+0x299	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:445

2 @ 0x42f5fc 0x43dcb2 0x43d202 0x67cbb4 0x67c248 0x68fff7 0x69102b 0x45ebb1
#	0x67cbb4	github.com/hashicorp/raft.(*Raft).runFollower+0x924				F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:606
#	0x67c248	github.com/hashicorp/raft.(*Raft).run+0x98					F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:591
#	0x68fff7	github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm+0x27	F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:245
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b			F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

2 @ 0x42f5fc 0x43dcb2 0x43d202 0x68ccd2 0x68a30b 0x690460 0x69102b 0x45ebb1
#	0x68ccd2	github.com/hashicorp/raft.(*Raft).pipelineReplicate+0x7f2	F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:348
#	0x68a30b	github.com/hashicorp/raft.(*Raft).replicate+0x2db		F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:124
#	0x690460	github.com/hashicorp/raft.(*Raft).startReplication.func1+0x30	F:/developing/go/influxdb/src/github.com/hashicorp/raft/raft.go:817
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b	F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

2 @ 0x42f5fc 0x43dcb2 0x43d202 0x68c4c6 0x690f59 0x69102b 0x45ebb1
#	0x68c4c6	github.com/hashicorp/raft.(*Raft).heartbeat+0x736		F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:295
#	0x690f59	github.com/hashicorp/raft.(*Raft).replicate.func1+0x39		F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:92
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b	F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

4 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x62ff7e 0x643b8b 0x738610 0x738e91 0x674b9c 0x674548 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67						c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41						c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177						c:/go/src/net/fd_windows.go:182
#	0x62ff7e	net.(*netFD).Read+0x17e							c:/go/src/net/fd_windows.go:463
#	0x643b8b	net.(*conn).Read+0xeb							c:/go/src/net/net.go:172
#	0x738610	bufio.(*Reader).fill+0x1f0						c:/go/src/bufio/bufio.go:97
#	0x738e91	bufio.(*Reader).ReadByte+0x81						c:/go/src/bufio/bufio.go:229
#	0x674b9c	github.com/hashicorp/raft.(*NetworkTransport).handleCommand+0x4c	F:/developing/go/influxdb/src/github.com/hashicorp/raft/net_transport.go:386
#	0x674548	github.com/hashicorp/raft.(*NetworkTransport).handleConn+0x368		F:/developing/go/influxdb/src/github.com/hashicorp/raft/net_transport.go:370

2 @ 0x42f5fc 0x43dcb2 0x43d202 0x676012 0x45ebb1
#	0x676012	github.com/hashicorp/raft.(*netPipeline).decodeResponses+0x482	F:/developing/go/influxdb/src/github.com/hashicorp/raft/net_transport.go:538

2 @ 0x42f5fc 0x43dcb2 0x43d202 0x68d3ab 0x690fd1 0x69102b 0x45ebb1
#	0x68d3ab	github.com/hashicorp/raft.(*Raft).pipelineDecode+0x28b		F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:399
#	0x690fd1	github.com/hashicorp/raft.(*Raft).pipelineReplicate.func1+0x61	F:/developing/go/influxdb/src/github.com/hashicorp/raft/replication.go:340
#	0x69102b	github.com/hashicorp/raft.(*raftState).goFunc.func1+0x4b	F:/developing/go/influxdb/src/github.com/hashicorp/raft/state.go:152

3 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x62ff7e 0x643b8b 0x560a76 0x66743b 0x667548 0x49cfd7 0x49aee7 0x4c1076 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67					c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41					c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177					c:/go/src/net/fd_windows.go:182
#	0x62ff7e	net.(*netFD).Read+0x17e						c:/go/src/net/fd_windows.go:463
#	0x643b8b	net.(*conn).Read+0xeb						c:/go/src/net/net.go:172
#	0x560a76	bytes.(*Buffer).ReadFrom+0x246					c:/go/src/bytes/buffer.go:173
#	0x66743b	io/ioutil.readAll+0x15b						c:/go/src/io/ioutil/ioutil.go:33
#	0x667548	io/ioutil.ReadAll+0x58						c:/go/src/io/ioutil/ioutil.go:42
#	0x49cfd7	github.com/influxdb/influxdb/meta.(*rpc).call+0xc97		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:465
#	0x49aee7	github.com/influxdb/influxdb/meta.(*rpc).fetchMetaData+0x387	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:354
#	0x4c1076	github.com/influxdb/influxdb/meta.(*remoteRaft).open.func1+0x86	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/state.go:440

4 @ 0x42f5fc 0x41953c 0x45ebb1
#	0x42f5fc	runtime.gopark+0x17c		c:/go/src/runtime/proc.go:186
#	0x41953c	runtime.gcBgMarkWorker+0x10c	c:/go/src/runtime/mgc.go:1289

5 @ 0x42f5fc 0x42f6cb 0x4046d6 0x403d7b 0x4963f1 0x496c22 0x49766b 0x4c288c 0x45ebb1
#	0x4963f1	github.com/influxdb/influxdb/meta.proxy+0x2a1				F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/proxy.go:42
#	0x496c22	github.com/influxdb/influxdb/meta.(*rpc).proxyLeader+0x482		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:72
#	0x49766b	github.com/influxdb/influxdb/meta.(*rpc).handleRPCConn+0x83b		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:94
#	0x4c288c	github.com/influxdb/influxdb/meta.(*Store).serveRPCListener.func1+0x7c	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:861

5 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x62ff7e 0x643b8b 0x54305e 0x542ddb 0x645e38 0x649d18 0x542f97 0x542ddb 0x4966b6 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67			c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41			c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177			c:/go/src/net/fd_windows.go:182
#	0x62ff7e	net.(*netFD).Read+0x17e				c:/go/src/net/fd_windows.go:463
#	0x643b8b	net.(*conn).Read+0xeb				c:/go/src/net/net.go:172
#	0x54305e	io.copyBuffer+0x24e				c:/go/src/io/io.go:381
#	0x542ddb	io.Copy+0x6b					c:/go/src/io/io.go:351
#	0x645e38	net.genericReadFrom+0xb8			c:/go/src/net/net.go:559
#	0x649d18	net.(*TCPConn).ReadFrom+0x2f8			c:/go/src/net/tcpsock_posix.go:63
#	0x542f97	io.copyBuffer+0x187				c:/go/src/io/io.go:375
#	0x542ddb	io.Copy+0x6b					c:/go/src/io/io.go:351
#	0x4966b6	github.com/influxdb/influxdb/meta.broker+0xb6	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/proxy.go:53

1 @ 0x42f5fc 0x428a05 0x427ec7 0x62ca61 0x62dc77 0x62ff7e 0x643b8b 0x560a76 0x66743b 0x667548 0x49cfd7 0x49aee7 0x4a2350 0x4b6f6d 0x4b6dd7 0x4b1ade 0x4c19ce 0x4abdd2 0x45ebb1
#	0x427ec7	net.runtime_pollWait+0x67						c:/go/src/runtime/netpoll.go:157
#	0x62ca61	net.(*pollDesc).Wait+0x41						c:/go/src/net/fd_poll_runtime.go:73
#	0x62dc77	net.(*ioSrv).ExecIO+0x177						c:/go/src/net/fd_windows.go:182
#	0x62ff7e	net.(*netFD).Read+0x17e							c:/go/src/net/fd_windows.go:463
#	0x643b8b	net.(*conn).Read+0xeb							c:/go/src/net/net.go:172
#	0x560a76	bytes.(*Buffer).ReadFrom+0x246						c:/go/src/bytes/buffer.go:173
#	0x66743b	io/ioutil.readAll+0x15b							c:/go/src/io/ioutil/ioutil.go:33
#	0x667548	io/ioutil.ReadAll+0x58							c:/go/src/io/ioutil/ioutil.go:42
#	0x49cfd7	github.com/influxdb/influxdb/meta.(*rpc).call+0xc97			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:465
#	0x49aee7	github.com/influxdb/influxdb/meta.(*rpc).fetchMetaData+0x387		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/rpc.go:354
#	0x4a2350	github.com/influxdb/influxdb/meta.(*remoteRaft).invalidate+0x50		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/state.go:392
#	0x4b6f6d	github.com/influxdb/influxdb/meta.(*Store).invalidate+0x4d		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1651
#	0x4b6dd7	github.com/influxdb/influxdb/meta.(*Store).read+0xb7			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:1629
#	0x4b1ade	github.com/influxdb/influxdb/meta.(*Store).Node+0x6e			F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:901
#	0x4c19ce	github.com/influxdb/influxdb/meta.(*Store).syncNodeInfo.func1+0x9e	F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:288
#	0x4abdd2	github.com/influxdb/influxdb/meta.(*Store).syncNodeInfo+0x62		F:/developing/go/influxdb/src/github.com/influxdb/influxdb/meta/store.go:283

1 @ 0x42f5fc 0x42f6cb 0x418309 0x45ebb1
#	0x42f5fc	runtime.gopark+0x17c		c:/go/src/runtime/proc.go:186
#	0x42f6cb	runtime.goparkunlock+0x5b	c:/go/src/runtime/proc.go:191
#	0x418309	runtime.backgroundgc+0x99	c:/go/src/runtime/mgc.go:900

**Comment by otoolep** [comment]
@runner-mei -- did you produce this locally? If so, what machine are running it on? We see this in CircleCI, but have found it difficult to repro locally.

cc @dgnorton @corylanou

**Comment by runner-mei** [comment]
@otoolep Yes.

````patch
diff --git a/meta/proxy.go b/meta/proxy.go
index bb0fa75..de84e9f 100644
--- a/meta/proxy.go
+++ b/meta/proxy.go
@@ -26,15 +26,15 @@ func proxy(dst, src *net.TCPConn) error {
                // useful, so we can optionally SetLinger(0) here to recycle the port
                // faster.
                dst.SetLinger(0)
-               dst.CloseRead()
+               dst.CloseWrite()
                waitFor = serverClosed
        case <-serverClosed:
-               src.CloseRead()
+               src.CloseWrite()
                waitFor = clientClosed
        case err := <-errors:
-               src.CloseRead()
+               src.CloseWrite()
                dst.SetLinger(0)
-               dst.CloseRead()
+               dst.CloseWrite()
                return err
        }
````

**Comment by otoolep** [comment]
Is this diff a proposed fix?

**Comment by runner-mei** [comment]
Yes

**Comment by otoolep** [comment]
Great -- thanks @runner-mei . Can you generate a PR for us?

**Comment by runner-mei** [comment]
OK
This bug is produce by tcp buffer,  must flush tcp stream after the copy [L53](https://github.com/influxdb/influxdb/blob/master/meta/proxy.go#L53), but Flush is not exists in the net.TcpConn struct.
