### ISSUE TITLE
[Repo] - Not containing the latest release

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb#4881]
Hi Team,

Apparently the repository (https://repos.influxdata.com/ubuntu/pool/stable/i/influxdb/) dont contain the version 0.9.5.
Is it possible to have the 0.9.5 on it ?

Thanks,
Julien

**Comment by rossmcdonald** [comment]
@JulienChampseix It was added to the repo as of about 15:37 UTC today. Let me know if you run into any issues downloading it.

**Comment by JulienChampseix** [comment]
@rossmcdonald perfect ! thanks
