### ISSUE TITLE
[0.9.5] show measurements broken

### ISSUE THREAD

**Issue by allen13** [influxdb/influxdb#4885]
From the influxdb admin interface:
Server returned error: json: cannot unmarshal array into Go value of type tsdb.MapperOutputJSON

**Comment by otoolep** [comment]
Thanks for the report, please be sure to look for similar issues though.

Dupe of https://github.com/influxdb/influxdb/issues/4550 and should be fixed by https://github.com/influxdb/influxdb/pull/4833
