### ISSUE TITLE
0.9.5 ansible cluster

### ISSUE THREAD

**Issue by allen13** [influxdb/influxdb#4887]
I put together a fully featured system metrics cluster using ansible:
https://github.com/allen13/influxdb-ansible 
What would be the best way to share this with the InfluxDB community?

**Comment by otoolep** [comment]
Thanks @allen13 

A good way to start is to send a message to the mailing list:

https://groups.google.com/forum/#!forum/influxdb

**Comment by otoolep** [comment]
You might also like to review the documentation, and see if there is a good place a link to your project might go:

https://github.com/influxdb/influxdb.com
