### ISSUE TITLE
UNION in Influxdb?

### ISSUE THREAD

**Issue by Advoskr** [influxdb/influxdb#4893]
Hi!

How can i achieve some sort of SQL Union or Union All in 0.9.5? 
Here is my usecase: I have 2 or more different series (each having own fields, but all of them have some common tag names) from which i want to make some sort of journal, which, in simpliest scenario, will just merge them in single time-series (by time, ofc), so that i can show this journal to users with paging or by period. A little bit more complicated scenario involves transformation of field to a single field, say, MessageText, so that my "journal" serie'll look like ime+MessageText and will agregate data from different series.

In  RDBMS i can achieve this by UNION operator and in Influx i cannot find any way to merge different series in 0.9.5.

Sorry if i'm not very precise with my explanation, i can provide some real examples if needed.

I'll be very gratefull for help!

**Comment by beckettsean** [comment]
This operator does not exist, and there is no similar functionality available. See https://influxdb.com/docs/v0.9/concepts/08_vs_09.html#joins for more detail.
