### ISSUE TITLE
no leader error after upgrade from 0.9.2 to 0.9.5

### ISSUE THREAD

**Issue by gucki** [influxdb/influxdb#4903]
# service influxdb start
    Starting the process influxdb [ OK ]
    influxdb process was started [ OK ]

    ----

    root@monitoring:/var/log/influxdb# cat influxd.log
    2015/11/25 15:36:09 InfluxDB starting, version 0.9.5, branch 0.9.5, commit 770b0ecf9f1f61a9d3a97136d5b6d7dd21afea1e, built 2015-11-20T15:30:37+0000
    2015/11/25 15:36:09 Go version go1.4.2, GOMAXPROCS set to 2
    2015/11/25 15:36:09 Using configuration at: /etc/influxdb/influxdb.conf
    [metastore] 2015/11/25 15:36:09 Using data dir: /var/lib/influxdb/meta
    [metastore] 2015/11/25 15:36:09 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:09 Node at localhost:8088 [Follower]
    [metastore] 2015/11/25 15:36:10 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:10 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:10 spun up monitoring for 1
    [store] 2015/11/25 15:36:10 Using data dir: /var/lib/influxdb/data
    [wal] 2015/11/25 15:36:11 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
    [wal] 2015/11/25 15:36:11 WAL writing to /var/lib/influxdb/wal/xyz/default/2428
    [metastore] 2015/11/25 15:36:12 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:12 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:14 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:14 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:16 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:16 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:18 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:36:18 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]
    [handoff] 2015/11/25 15:36:18 Starting hinted handoff service
    [monitor] 2015/11/25 15:36:18 'hh' registered for diagnostics monitoring
    [handoff] 2015/11/25 15:36:18 Using data dir: /var/lib/influxdb/hh
    [subscriber] 2015/11/25 15:36:18 opened service
    [monitor] 2015/11/25 15:36:18 Starting monitor system
    [monitor] 2015/11/25 15:36:18 'build' registered for diagnostics monitoring
    [monitor] 2015/11/25 15:36:18 'runtime' registered for diagnostics monitoring
    [monitor] 2015/11/25 15:36:18 'network' registered for diagnostics monitoring
    [monitor] 2015/11/25 15:36:18 'system' registered for diagnostics monitoring
    [cluster] 2015/11/25 15:36:18 Starting cluster service
    [shard-precreation] 2015/11/25 15:36:18 Starting precreation service with check interval of 10m0s, advance period of 30m0s
    [registration] 2015/11/25 15:36:18 Starting registration service
    [monitor] 2015/11/25 15:36:18 Storing statistics in database '_internal' retention policy '', at interval 10s
    [monitor] 2015/11/25 15:36:18 'registration' registered for diagnostics monitoring
    [snapshot] 2015/11/25 15:36:18 Starting snapshot service
    [copier] 2015/11/25 15:36:18 Starting copier service
    [admin] 2015/11/25 15:36:18 Starting admin service
    [admin] 2015/11/25 15:36:18 Listening on HTTP: [::]:8083
    [continuous_querier] 2015/11/25 15:36:18 Starting continuous query service
    [httpd] 2015/11/25 15:36:18 Starting HTTP service
    [httpd] 2015/11/25 15:36:18 Authentication enabled: false
    [httpd] 2015/11/25 15:36:18 Listening on HTTP: [::]:8086
    [retention] 2015/11/25 15:36:18 Starting retention policy enforcement service with check interval of 30m0s
    [run] 2015/11/25 15:36:18 Listening for signals
    [http] 2015/11/25 15:36:18 x.x.x.x - - [25/Nov/2015:15:36:18 +0100] POST /write?db=xyz&precision=s HTTP/1.1 500 95 - Ruby e3c37ca4-9381-11e5-8001-000000000000 12.502527ms
    [http] 2015/11/25 15:36:18 x.x.x.x - - [25/Nov/2015:15:36:18 +0100] POST /write?db=xyz&precision=s HTTP/1.1 500 95 - Ruby e3cda03c-9381-11e5-8002-000000000000 12.233458ms
    [http] 2015/11/25 15:36:18 x.x.x.x - - [25/Nov/2015:15:36:18 +0100] POST /write?db=xyz&precision=s HTTP/1.1 500 95 - Ruby e3d58518-9381-11e5-8003-000000000000 12.751398ms
    [http] 2015/11/25 15:36:18 x.x.x.x - - [25/Nov/2015:15:36:18 +0100] POST /write?db=xyz&precision=s HTTP/1.1 500 95 - Ruby e3ef46a9-9381-11e5-8004-000000000000 13.302598ms

I cannot issue any query, I always get "no leader" errors:

    > USE xyz
    Using database xyz

    > SHOW RETENTION POLICIES ON "xyz"
    ERR: error fetching meta data: rpc Error failed: no leader detected during proxyLeader

    > SELECT * FROM "xyz"."1m"."derivative" WHERE host = 'h100' and interface = '1'
    ERR: error fetching meta data: no leader detected during fetchMetaData

    > SELECT * FROM "xyz"."1m"."derivative" WHERE host = 'h100' and interface = '1'
    ERR: error fetching meta data: no leader detected during fetchMetaData

The log is filling with:

    [metastore] 2015/11/25 15:42:02 Node at localhost:8088 [Leader]. peers=[127.0.0.1:8088 localhost:8088]
    [metastore] 2015/11/25 15:42:02 Node at localhost:8088 [Follower]. peers=[127.0.0.1:8088 localhost:8088]

I compared the config files and they look identical in the relevant sections (I used the sample configuration before and just upgraded it to the latest one). How can I get it fixed asap?

**Comment by beckettsean** [comment]
@gucki it looks like one config used `127.0.0.1` and the other is using `localhost`. To the system, those appear to be two different servers.

Shut down the process, delete any `peers.json` file that exists in the `/meta` directory, and then restart the process. That should fix the raft issues.

**Comment by gucki** [comment]
@beckettsean That's strange, because I double checked it and it's the same:

Old:
    [meta]
      dir = "/var/opt/influxdb/meta"
      hostname = "localhost"
      bind-address = ":8088"
      retention-autocreate = true
      election-timeout = "1s"
      heartbeat-timeout = "1s"
      leader-lease-timeout = "500ms"
      commit-timeout = "50ms"

New:
    [meta]
      dir = "/var/lib/influxdb/meta"
      hostname = "localhost"
      bind-address = ":8088"
      retention-autocreate = true
      election-timeout = "1s"
      heartbeat-timeout = "1s"
      leader-lease-timeout = "500ms"
      commit-timeout = "50ms"
      cluster-tracing = false

Anyway your fix worked and deleting "peers.json" solved it! :+1:
