### ISSUE TITLE
Capacity Capabilities using the InfluDB data

### ISSUE THREAD

**Issue by gopalvd** [influxdb/influxdb#4915]
Hi,

We are currently using InfluxDB for collecting the server metrics from the Sensu. Is there a way we can use the data available in the InfluxDB for the Capacity Management Capabilities, like using the history of the data, can I get a forecasting, trending, modelling, collecting the server configuration details (like hardware, OS versions). 

For displaying the forecasting, trending data, is there any open source tool available to display these graphs?

**Comment by beckettsean** [comment]
We try to keep GitHub issues for bugs and feature requests. General usage questions should go to the influxdb@googlegroups.com mailing list.

> can I get a forecasting, trending, modelling, collecting the server configuration details (like hardware, OS versions

I don't understand what you're asking for. InfluxDB is a data storage tool, it does not have any built-in analysis tools, other than the query language where you can craft your own questions. 

> For displaying the forecasting, trending data, is there any open source tool available to display these graphs?

Check out [grafana](http://grafana.org/) or [chronograf](https://influxdb.com/chronograf/index.html).
