### ISSUE TITLE
[0.9.5]: High Memory consumption

### ISSUE THREAD

**Issue by dtouzeau** [influxdb/influxdb#4919]
Hi we have upgraded Influx to 0.9.5 but this behavior can be seen in 0.9.3/0.9.4
We have a database of 8GB size on a server with 4 CPUs and 12GB of memory
After 5 minutes, InfluxDB take 11GB of memory.
After 7 minutes server is swapping and oom killer start doing it's job.
After 9 minutes server is down.

I would like to know if there are some parameters that tweak how InfluxDB should consume memory ?

**Comment by ekini** [comment]
How many tag values do you have? I've seen 100Gb memory consumption before oom on a smaller database, where tag value contained hash or timestamp.

**Comment by tomeucapo** [comment]
Hi 
I have same situation, upgraded influx 0.9.4 to 0.9.5.1-1, and use same data, wal, ... data files. Works, comes up but consumes high volumes of RAM (RES and VIRT). I have a server with 8CPUs and 6GB used exclusively for InfluxDB, don't use cluster configuration.

Using tsm1 engine, when startup influx appers this lines into log:


2015/11/27 12:20:36 InfluxDB starting, version 0.9.5.1, branch 0.9.5, commit 9eab56311373ee6f788ae5dfc87e2240038f0eb4, built 2015-11-25T23:01:58+0000
2015/11/27 12:20:36 Go version go1.4.2, GOMAXPROCS set to 8
2015/11/27 12:20:36 Using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2015/11/27 12:20:36 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/11/27 12:20:36 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[bebd8tse01.ods:8088]
[metastore] 2015/11/27 12:20:36 Node at bebd8tse01.ods:8088 [Follower]
[metastore] 2015/11/27 12:20:37 Node at bebd8tse01.ods:8088 [Leader]. peers=[bebd8tse01.ods:8088]
[metastore] 2015/11/27 12:20:37 spun up monitoring for 1
[store] 2015/11/27 12:20:37 Using data dir: /var/opt/influxdb/data
[metastore] 2015/11/27 12:20:37 Updated node id=1 hostname=bebd8tse01.ods:8088
[wal] 2015/11/27 12:20:37 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2015/11/27 12:20:37 WAL writing to /var/opt/influxdb/wal/internal_metrics/internal/100
[wal] 2015/11/27 12:20:38 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2015/11/27 12:20:38 WAL writing to /var/opt/influxdb/wal/internal_metrics/internal/105
[wal] 2015/11/27 12:20:38 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold
[wal] 2015/11/27 12:20:38 WAL writing to /var/opt/influxdb/wal/internal_metrics/internal/111
[wal] 2015/11/27 12:20:38 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 52428800 partition size threshold

**Comment by tomeucapo** [comment]
Hi again

I have a tags for environment, hostname and servicename. Is a problem?

Thanks

**Comment by dtouzeau** [comment]
We have about 6 TAG values
a piece of what is sent to the Influx
access_log,IPADDR=10.10.1.1,SITE=paris1.speedtest.orange.fr,FAMILYSITE=orange.fr,proxyname=routeur.touzeau.biz SIZE=4700,ZDATE=1438722000,RQS=10 1438714800
access_log,IPADDR=10.10.1.1,SITE=speedtest.neotelecoms.com,FAMILYSITE=neotelecoms.com,proxyname=routeur.touzeau.biz SIZE=4600,ZDATE=1438722000,RQS=10 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=speedtest.net,FAMILYSITE=speedtest.net,proxyname=routeur.touzeau.biz SIZE=1103,ZDATE=1438722000,RQS=2 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=www.speedtest.net,FAMILYSITE=speedtest.net,proxyname=routeur.touzeau.biz SIZE=134669,ZDATE=1438722000,RQS=2 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=speedtest.proceau.net,FAMILYSITE=proceau.net,proxyname=routeur.touzeau.biz SIZE=10967892,ZDATE=1438722000,RQS=24 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=massy.testdebit.info,FAMILYSITE=testdebit.info,proxyname=routeur.touzeau.biz SIZE=4900,ZDATE=1438722000,RQS=10 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=paris1.speedtest.orange.fr,FAMILYSITE=orange.fr,proxyname=routeur.touzeau.biz SIZE=4700,ZDATE=1438722000,RQS=10 1438714800
access_log,IPADDR=192.168.1.197,MAC=00:0c:29:47:80:24,SITE=speedtest.neotelecoms.com,FAMILYSITE=neotelecoms.com,proxyname=routeur.touzeau.biz SIZE=4600,ZDATE=1438722000,RQS=10 1438714800
access_log,IPADDR=192.168.1.50,MAC=00:0c:29:5b:40:37,SITE=www.artica.fr,FAMILYSITE=artica.fr,proxyname=routeur.touzeau.biz SIZE=1324,ZDATE=1438722000,RQS=4 1438714800
access_log,USERID=iphone-david,IPADDR=192.168.1.219,MAC=60:03:08:7b:7c:fd,SITE=ui.skype.com,FAMILYSITE=skype.com,proxyname=routeur.touzeau.biz SIZE=757,ZDATE=1438722000,RQS=1 1438714800
access_log,USERID=iphone-david,IPADDR=192.168.1.219,MAC=60:03:08:7b:7c:fd,SITE=191.233.95.169,FAMILYSITE=191.233.95.169,proxyname=routeur.touzeau.biz SIZE=3903,ZDATE=1438722000,RQS=1 1438714800
access_log,USERID=iphone-david,IPADDR=192.168.1.219,MAC=60:03:08:7b:7c:fd,SITE=23.15.67.205,FAMILYSITE=23.15.67.205,proxyname=routeur.touzeau.biz SIZE=9939,ZDATE=1438722000,RQS=1 1438714800
access_log,IPADDR=192.168.1.231,MAC=00:0c:29:bd:88:3b,SITE=91.121.49.165,FAMILYSITE=91.121.49.165,proxyname=routeur.touzeau.biz SIZE=3112,ZDATE=1438722000,RQS=1 1438714800
access_log,IPADDR=192.168.1.213,SITE=localhost.company.tld,FAMILYSITE=company.tld,proxyname=articaad2.company.tld SIZE=37800,ZDATE=1438722000,RQS=3 1438714800
access_log,IPADDR=192.168.1.200,MAC=00:0c:29:3d:7f:36,SITE=articatech.net,FAMILYSITE=articatech.net,proxyname=routeur.touzeau.biz SIZE=30828,ZDATE=1438722000,RQS=3 1438714800
access_log,USERID=iphonealex,IPADDR=192.168.1.160,MAC=d8:9e:3f:34:2d:8d,SITE=captive.apple.com,FAMILYSITE=apple.com,proxyname=routeur.touzeau.biz SIZE=1300,ZDATE=1438722000,RQS=4 1438714800
access_log,USERID=iphone-david,IPADDR=192.168.1.219,MAC=60:03:08:7b:7c:fd,SITE=17.154.65.163,FAMILYSITE=17.154.65.163,proxyname=routeur.touzeau.biz SIZE=23754,ZDATE=1438722000,RQS=6 1438714800
access_log,USERID=ipadalex,IPADDR=192.168.1.155,MAC=28:6a:ba:59:f3:f9,SITE=17.110.225.88,FAMILYSITE=17.110.225.88,proxyname=routeur.touzeau.biz SIZE=3305,ZDATE=1438722000,RQS=1 1438714800
access_log,USERID=ipadalex,IPADDR=192.168.1.155,MAC=28:6a:ba:59:f3:f9,SITE=17.134.62.236,FAMILYSITE=17.134.62.236,proxyname=routeur.touzeau.biz SIZE=9069,ZDATE=1438722000,RQS=2 1438714800
access_log,USERID=ipadalex,IPADDR=192.168.1.155,MAC=28:6a:ba:59:f3:f9,SITE=17.134.126.211,FAMILYSITE=17.134.126.211,proxyname=routeur.touzeau.biz SIZE=4464,ZDATE=1438722000,RQS=1 1438714800

**Comment by beckettsean** [comment]
@dtouzeau Series cardinality is the primary driver of RAM usage for InfluxDB. You have six tags, but each tag has many possible values. Tag cardinality is the unique combinations of all tag keys AND values. Your write sample contains 20 points that belong to 20 different series. Your series cardinality is likely very very high. 

What are the results of the following command line query?

`influx -database <db_name> -execute 'show tag values with key in (IPADDR, SITE, FAMILYSITE, MAC, USERID, proxyname)' | wc -l`

**Comment by dtouzeau** [comment]
Result is 36 929 on a 3GB database and influx take about 1.8GB memory.
Did you think that some points can be optimized ?
According sent rows, is influx is the appropriate database engine. ?

This piece of log are sent by a proxy service.
Average is around 4 000 000 rows per day for 365 days = 1 460 000 000 rows

**Comment by beckettsean** [comment]
> Result is 36 929 on a 3GB database and influx take about 1.8GB memory.

Please give the results for the database that is causing the OOM errors. You mention "We have a database of 8GB size on a server with 4 CPUs and 12GB of memory" as the machine with the issue. Please give replies regarding only that machine, since that's the one with the OOM errors.

> Did you think that some points can be optimized ?

Optimized how? There's no way to reduce RAM usage except to have fewer series. That would mean removing some tags or tag values, or inserting them as fields instead.

> According sent rows, is influx is the appropriate database engine. ?

That's not enough data to say yes, but there's nothing about your use case that says InfluxDB is a poor choice.

**Comment by dtouzeau** [comment]
.... That would mean removing some tags or tag values, or inserting them as fields instead ...
In this case, no aggregate function can be used like GROUP BY.

Installed PostgreSQL, injecting all datas, database size divided per 3, ( from 3GB to 1.2GB) memory used 540MB instead 1.8GB, same query time to get results...

Major changes, server still running and UP....

I think InfluxDB should be good to inject/query numeric values and extract rows with best performance if no aggregation made...
For us, definitively InfluxDB is not the right answer to store events/logs from proxies or FireWall...
