### ISSUE TITLE
[0.9.5] Updating InfluxDB overwrites the configuration

### ISSUE THREAD

**Issue by willemdh** [influxdb/influxdb#4941]
Hello,

I updated my InfluxDB from 0.9.4-rc1 to 0.9.5.1 and just noticed that my default database I created has been deleted. Is an upgrade supposed to delete the databases of previous versions?

I updated like this:

    wget http://influxdb.s3.amazonaws.com/influxdb-0.9.5.1-1.x86_64.rpm
    sudo yum localinstall influxdb-0.9.5.1-1.x86_64.rpm

Thanks for any info on this. This was a test database but I'd rather prevent this from happening again in the future.

Willem

**Comment by rossmcdonald** [comment]
@willemdh Upgrades should not modify or move data directories, so I believe your configuration may have been changed. Can you double check your configuration file at `/etc/influxdb/influxdb.conf` to ensure the data directories are correct and pointing to the right directories?

**Comment by willemdh** [comment]
Well in the meantime I've done many things, including reconfiguring /etc/influxdb/influxdb.conf as that seemed to be the default again. For example authentication was also off. it's working all normally again. So this wasn't supposed to happen then. Well maybe it wasn't so bad as my old default db was kind of polluted. It's all working 'normally' again. In what directory would the database information be located? I can have a look there if you like. But I can't remember settiing things like that to non-default settings..

**Comment by CVTJNII** [comment]
The data directory was changed from /var/opt/influxdb to ~/.influxdb and the config directory was changed from /etc/opt/influxdb to /etc/influxdb.  This should be considered a breaking change as it can cause InfluxDB to revert to defaults unexpectedly, which a user would not expect on a patch level change.  I was stung by this as well, but fortunately #9496 made this issue obvious in my environment.

**Comment by rossmcdonald** [comment]
@willemdh Correct, that is definitely not supposed to happen. The default data directories for `0.9.4.2` are `/var/opt/influxdb`, so, if you were using the default package directories, then your data should still be residing there. With `0.9.5`, we modified the default directory from `/var/opt/influxdb` to `/var/lib/influxdb`.

The full list of changes to the filesystem hierarchy are listed in the CHANGELOG of the `0.9.5` branch here:

https://github.com/influxdb/influxdb/blob/0.9.5/CHANGELOG.md#release-notes

**Comment by rossmcdonald** [comment]
@CVTJNII To be clear, the default packaged data directory for 0.9.4 was `/var/opt/influxdb`. With the 0.9.5 release, the default has been switched to `/var/lib/influxdb`. The `~/.influxdb` directory is only used if no configuration is passed to `influxd` at runtime or if you generate a configuration file yourself using the `influxd config` command.

**Comment by willemdh** [comment]
Well I checked and indeed there seems to be:
```
ls -la /var/lib/influxdb/
total 4
drwxr-xr-x   6 influxdb influxdb   47 Dec  1 14:57 .
drwxr-xr-x. 35 root     root     4096 Dec  1 17:08 ..
drwxr-xr-x   4 influxdb influxdb   41 Dec  1 15:45 data
drwx------   2 influxdb influxdb    6 Dec  1 14:57 hh
drwxr-xr-x   3 influxdb influxdb   62 Dec  1 14:57 meta
drwx------   4 influxdb influxdb   41 Dec  1 15:45 wal
```

and 

```
ls -la /var/opt/influxdb/
total 0
drwxr-xr-x. 6 influxdb influxdb 47 Sep 15 13:17 .
drwxr-xr-x. 3 root     root     21 Sep 15 13:14 ..
drwxr-xr-x. 4 influxdb influxdb 41 Sep 15 13:34 data
drwx------. 2 influxdb influxdb  6 Sep 15 13:17 hh
drwxr-xr-x. 3 influxdb influxdb 62 Sep 15 13:17 meta
drwx------. 4 influxdb influxdb 41 Sep 15 13:34 wal
```
You can clearly see when I did the upgrade. So next upgrade I should not fear loosing my database and configfile by doing

    wget http://influxdb.s3.amazonaws.com/influxdb-0.9.5.1-1.x86_64.rpm
    sudo yum localinstall influxdb-0.9.5.1-1.x86_64.rpm

But then with a newer version number...?

**Comment by rossmcdonald** [comment]
@willemdh Correct, you should not expect to lose your configuration (or data) with future upgrades.

You are free to delete the old data if you want to. You can also just point your configuration at the old data directories to get the original databases back.

**Comment by willemdh** [comment]
Gonna close this up I guess. Thanks for the help!
