### ISSUE TITLE
Please provide a 'stable' download link

### ISSUE THREAD

**Issue by CVTJNII** [influxdb/influxdb#4945]
Per https://influxdb.com/download/# current stable requires a download via a specific version.  This makes updates difficult, as upgrading requires manually changing a version pin from the previous version to the current version.  This can also impact testing if the version pin is missed or forgotten and an admin thinks they're running latest stable but they're not.

Please provide a latest stable link similar to https://s3.amazonaws.com/influxdb/influxdb_nightly_amd64.deb to help us stay up to date.  Thanks.

**Comment by beckettsean** [comment]
Stable releases are available via https://repos.influxdata.com/. Blog post coming soon.
