### ISSUE TITLE
Uninstall 0.9.5.1 still keeps the Web Admin 

### ISSUE THREAD

**Issue by crudbug** [influxdb/influxdb#4947]
I am trying to uninstall influx from Fedora 22, but the web admin is till running on port 8083. 

How to completely uninstall Influx ? 

Also, the installation creates lot of noise (multiple files at different location). Having a single location for InfluxDB related files would make it easy to uninstall. 

Better:  uninstall script along with installation script.

**Comment by beckettsean** [comment]
@crudbug can you paste in the steps you took to uninstall InfluxDB?

The admin UI is not a separate process or piece of code, so if it's still there, you must still be running InfluxDB on the machine.

**Comment by rossmcdonald** [comment]
@crudbug It sounds like the service wasn't stopped before the package was removed. You can see if InfluxDB is still running by using the command:

```
ps -ef | grep influxd
```

If the process is still active, then you can kill it with `sudo kill <pid of influxd>` which should close the listeners.

**Comment by crudbug** [comment]
@rossmcdonald this was one of the issues.

I followed few pointers from

```
https://groups.google.com/forum/#!msg/influxdb/5R_G3I_MaeI/SLwvBRr3CQAJ
```

After cleaning my system, I still had these files/directories left behind. In the end, I had to perform manual deletion :-1:  

```
/etc/influxdb
/etc/default/influxdb
/etc/influxdb/influxdb.conf
/etc/logrotate.d/influxdb
/etc/opt/influxdb
/etc/rc.d/rc2.d/S50influxdb
/etc/rc.d/rc3.d/S50influxdb
/etc/rc.d/rc4.d/S50influxdb
/etc/rc.d/rc5.d/S50influxdb
/etc/systemd/system/influxd.service
/etc/systemd/system/multi-user.target.wants/influxdb.service
/opt/influxdb
/opt/influxdb/current
/opt/influxdb/shared
/opt/influxdb/versions
/opt/influxdb/shared/benchmark_config.toml
/opt/influxdb/shared/config.toml
/opt/influxdb/shared/log.txt
/opt/influxdb/versions/0.8.9
/opt/influxdb/versions/0.8.9/scripts
/usr/bin/influx
/usr/bin/influx_inspect
/usr/bin/influx_stress
/usr/bin/influxd
/usr/bin/influxdb
/usr/bin/influxdb-benchmark
/usr/bin/influxdb-daemon
/usr/lib/influxdb
/usr/lib/influxdb/scripts
/usr/lib/influxdb/scripts/influxdb.service
/usr/lib/influxdb/scripts/init.sh
/usr/lib/systemd/system/influxdb.service
/var/lib/influxdb
/var/lib/influxdb/data
/var/lib/influxdb/hh
/var/lib/influxdb/meta
/var/lib/influxdb/wal
/var/lib/influxdb/data/_internal
/var/lib/influxdb/data/recap
/var/lib/influxdb/meta/id
/var/lib/influxdb/meta/peers.json
/var/lib/influxdb/meta/raft.db
/var/lib/influxdb/meta/snapshots
/var/log/influxdb
/var/log/influxdb/influxd.log
/var/log/influxdb/influxd.log-20151202.gz
```

**Comment by rossmcdonald** [comment]
@crudbug Thanks for letting us know. We are going to be improving the way InfluxDB is uninstalled with the next release, so this should be less of an issue moving forward. That said, your removal of InfluxDB should not have left behind that many files, especially the binaries (`/usr/bin/influx*`). Can you provide us with the steps that you used to uninstall InfluxDB?
