### ISSUE TITLE
[0.9.6-nightly-43a4201 tsm] Large number of series affecting write performance?

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#4950]
Hi, 
I am using influxdb to store many series of data. All series have the same columns (value, Severity, Error, Warning). They all share some Tags: 
* Gateway
* Managed Entity
* Data view
* Sampler 
* Netprobe
* Row name 
* Column name

Some series will also contain a set of other Tags, but these are dynamically generated. 

I am using the Java API (with the line protocol) to write the data to the database. I batch the data into writes of 10000 based on the Gateway, Managed Entity and Data view tags. The data is taken in real time, I send timestamps with the data in ascending chronological order. I store the data to millisecond precision (although most data will be sampled at 20 second intervals). 
The process is running on a 4 core Intel(R) Xeon(R) CPU           X5560  @ 2.80GHz with 64GB ram

Could this be affecting my write performance:
*I am storing all these series against the same measurement. 
*Due to the nature of the data, I end up with a large number of series (over 200,000) 

If it is, are there recommendations on how to improve write speed?

**Comment by beckettsean** [comment]
> I am storing all these series against the same measurement. 

That is almost entirely irrelevant to write performance.

> Due to the nature of the data, I end up with a large number of series (over 200,000)

That's not a huge number of series. Anything under a half a million should be fine for performance reasons.

You didn't say what is bad about your performance. How many points per second are you able to submit?

**Comment by ivanscattergood** [comment]
I'm getting a much lower write speed (around 300 per sec). Even at this rate I still get timeouts when writing data, if it fails once I hold off and retry. On the second failed attempt I throw the data away.

Should I just keep trying? 

>Anything under a half a million should be fine for performance reasons
If I were writing over half a million (I can see this happening), is there anything I could do to help e.g. move one of the Tags to a field in the series? 

>That is almost entirely irrelevant to write performance.
Good news :-) What about read performance?

**Comment by beckettsean** [comment]
> I'm getting a much lower write speed (around 300 per sec). Even at this rate I still get timeouts when writing data, if it fails once I hold off and retry after a short pause. On the second failed attempt I throw the data away. Should I just keep trying?

There's something very badly wrong if you're only getting 300 points per second. That's a feasible load for a Raspberry Pi. 

Are you actually hitting HTTP timeouts, not HTTP status 500 responses? That's very strange. Can you show `curl` write statements with the `-v` option?

> If I were writing over half a million (I can see this happening), is there anything I could do to help e.g. move one of the Tags to a field in the series? Or use separate Measurements?
> What about read performance?

We are going to publish some general performance and tuning guidelines this month. But, over half a million series you just need more RAM to contain the index. The number of measurements is mostly irrelevant provided it's only a few dozen or a few hundred measurements. As total series increase writes get a bit slower, but nothing that requires significant tuning.

The number of series is mostly irrelevant for read performance, too. Above 1 million series things get slower/more complex, and the box will need 16GB+ of RAM.

**Comment by beckettsean** [comment]
What write performance do you see if you submit the points directly using `curl` rather than the `influxdb-java` library?

**Comment by ivanscattergood** [comment]
>There's something very badly wrong if you're only getting 300 points per second
I am running a summarisation process at the same time, so the overall effect will be more than 300 points per second, but I'm assuming I should NOT get any timeouts with this kind of load. 

>What write performance do you see if you submit the points directly using  curl  
I am using a Java library to get the data as well, so to write the data via Curl would require a complete re-write. 

>Are you actually hitting HTTP timeouts, not HTTP status 500 responses? That's very strange. Can you show  curl  write statements with the  -v  option?
The timeout error is being thrown by the Java Library, so I need to get to the bottom if this error is coming actually just a HTTP status 500 response.

**Comment by beckettsean** [comment]
> I'm assuming I should NOT get any timeouts with this kind of load.

correct.

> to write the data via Curl would require a complete re-write.

I don't mean all data, but can you try to submit a few thousand points and see how long the write takes? I strongly suspect that `influxdb-java` is at fault, and removing it from the test will help determine if that is a valid suspicion.

> The timeout error is being thrown by the Java Library, so I need to get to the bottom if this error is coming actually just a HTTP status 500 response.

When InfluxDB is under too high a write load it will issue 500 responses to incoming writes. That indicates the system is healthy but too busy. Actual timeouts means the system is not healthy, and we need to find out why. It's important that we determine which is happening in this case.

**Comment by ivanscattergood** [comment]
Ok, let me investigate and get back to you.

**Comment by ivanscattergood** [comment]
This was a bug in my Batch logic.
