### ISSUE TITLE
[0.9.5] InfluxDB Intermittently Hangs (Doesn't Send Response), perhaps environmental cause

### ISSUE THREAD

**Issue by andremleblanc** [influxdb/influxdb#4963]
The issue I'm having is during querying Influx, occasionally no response is sent and the process hangs until terminated. I've experienced this problem in my Rails application locally using the Influx Ruby adapter and also in simple test scenarios using the CLI and cURL. Interestingly, when I used the UI on :8083 it worked without any issues.

System: OS X 10.11.1
Influx Version: 0.9.5.1
Installed with Homebrew

Steps to Reproduce Issue:
```
$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
> CREATE DATABASE mydb
> USE mydb
Using database mydb
> INSERT cpu,host=serverA,region=us_west value=0.64
> SELECT * FROM cpu
name: cpu
---------
time      host  region  value
1449091283892011550 serverA us_west 0.64

> SELECT * FROM cpu
name: cpu
---------
time      host  region  value
1449091283892011550 serverA us_west 0.64
```
After some amount of tries later:
```
> SELECT * FROM cpu
(nothing)
```

I also tried the same query using cURL.
```
curl -G http://localhost:8086/query  --data-urlencode 'db=mydb' --data-urlencode 'q=SELECT * from cpu'
```

Works most of the time, but eventually nothing is returned and the terminal just hangs there until I ctrl-c out of it.

When tailing the Influx log, I normally see the normal query/response.
```
[query] 2015/12/02 16:56:01 SELECT * FROM "mydb"."default".cpu
[http] 2015/12/02 17:01:05 ::1 - - [02/Dec/2015:17:01:05 -0500] GET /query?db=mydb&q=SELECT%20%2A%20from%20cpu HTTP/1.1 200 154 - curl/7.43.0 2f93ac95-9940-11e5-82c0-000000000000 386.568µs
```

When it fails, nothing shows in the log (no query or response or anything else).

I should also mention, that a coworker is working on the same Rails application with the new feature implementing Influx and has had no issues. He setup a loop to cURL Influx 1000 times and it didn't fail. I'm certain this is something to do with my environment, but I can't determine the source.

I'm not sure what other information to provide, but I could definitely use some help figuring out what is going on here.

**Comment by beckettsean** [comment]
`SELECT * FROM foo` can be an expensive query. Is the machine starved for CPU, RAM, or IOPS?

**Comment by andremleblanc** [comment]
Thanks for the quick response @beckettsean! I don't think it's any of those concerns. I captured my stats when experiencing the issue.

Idle CPU: 89%
Free Memory: 10GB
Reads in/sec: 1
Writes out/sec: 14

The trivial scenario I'm using to troubleshoot the issue only has a single point in the measurement.

**Comment by andremleblanc** [comment]
Ahh, turns out this was an issue with Forticlient. I turned it off an ran 1000 queries in about 10 seconds with no issue :smile:

**Comment by andremleblanc** [comment]
If anyone is interested, this is the error I found in my syslog that pointed me in the right direction.
```
Dec  3 11:28:36 Andres-AC-MBP kernel[0] <Notice>: fctwfnke : error! - please unload again because unregister is not completed yet
Dec  3 11:28:36 Andres-AC-MBP kernel[0] <Notice>: Kext com.fortinet.fct.kext.fctwfnke did not stop (return code 0x5).
Dec  3 11:28:36 Andres-AC-MBP kernel[0] <Notice>: Kext com.fortinet.fct.kext.fctwfnke can't unload - module stop returned 0xdc008017.
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: WARNING: The Gestalt selector gestaltSystemVersion is returning 10.9.1 instead of 10.11.1. This is not a bug in Gestalt -- it is a documented limitation. Use NSProcessInfo's operatingSystemVersion property to get correct system version number.
  Call location:
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 0   CarbonCore                          0x9e07bf1d ___Gestalt_SystemVersion_block_invoke + 135
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 1   libdispatch.dylib                   0x936d86c3 dispatch_once_f + 78
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 2   libdispatch.dylib                   0x936d9f4d dispatch_once + 31
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 3   CarbonCore                          0x9dff79e1 _Gestalt_SystemVersion + 1047
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 4   CarbonCore                          0x9dff718a Gestalt + 154
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 5   ftgdagent                           0x00076fa1 main + 1297
Dec  3 11:28:56 Andres-AC-MBP ftgdagent[23847] <Error>: 6   libdyld.dylib                       0x960c56ad start + 1
```

**Comment by beckettsean** [comment]
Thanks for the followup, @andremleblanc.
