### ISSUE TITLE
Admin UI and Grafana do not show points in the future

### ISSUE THREAD

**Issue by mukatee** [influxdb/influxdb#4964]
InfluxDB version: 0.9.5.1
OS: Ubuntu 14.04LTS 64bit
Installed from: pre-built package on InfluxDB website

Description:
The admin UI only seems to show measurement points that are in the "past" for the host where it is running on. Here is my test case:

1. Install InfluxDB on a VM. The VM clock is maybe 2-3 minutes behind my laptop clock.
2. Collect measurements on my laptop, use current time on laptop as timestamp, store these to InfluxDB (over the network to the InfluxDB running in the VM).
3. From the laptop, open browser and log in to the Admin UI on the VM.
4. Query for measurements "select * from my_measurement". Get "no results".
5. Query for tag keys with the template query 'SHOW TAG KEYS FROM "my_measurement"' and get the tags for the measurement data that is not shown with "select * from my_measurement" -> add to the confusion
6. Wait 3 minutes (the clock diff) while drinking coffee and doing nothing on the InfluxDB
7. Repeat query on Admin UI. Get the results because clock on VM has caught up.

If you replace "Grafana" with "Admin UI" in the above, the result is the same (the graphs update only after the 3 mins even if they seem to have the full time there so a gap on the right is always there).

So I should probably set up some NTP server and synchronize better. But besides that, is this the intended behaviour? I would expect to see the data and the timestamp even if it is few minutes in the "future".

**Comment by otoolep** [comment]
If you don't set an upper bound on the time in your query, it defaults to
now. That is why you're not seeing any data later than now.

**Comment by otoolep** [comment]
Now on the InfluxDB node, that is.

https://influxdb.com/docs/v0.9/query_language/data_exploration.html#time-syntax-in-queries

**Comment by mukatee** [comment]
Yes, I understand it picks now() on the node. But the UI does not show this in any way it just says "Success! (no results to display)". My point is simply that I have a different expectation for a query such as "select * from my_measure" when I am not specifying any time and I know I just inserted data. Maybe if the UI had some time indicator for what time frame was queried or something.

In a Grafana graph it is even more confusing since I guess Grafana picks the time from the browser host and as such shows the graph with different time than what the data it gets from InfluxDB... Meaning the graph shows a longer time and drawing starts from the middle after a few minutes.

**Comment by beckettsean** [comment]
@mukatee you should follow https://github.com/influxdb/influxdb/issues/4461 which is the issue already open about the default time range boundaries.
