### ISSUE TITLE
Import JSON

### ISSUE THREAD

**Issue by Sanosukeyy** [influxdb/influxdb#4970]
Hi !

I'm using InfluxDB for Grafana and I have some JSON to import on my db.
I don't know how to do because my JSON files are too long (1'000'000+ rows) and i can't import with curl -X POST ...

Anyone have an idea ?

**Comment by beckettsean** [comment]
We try to keep GitHub issues for bug reports and feature requests. Please send general questions to the mailing list: influxdb@googlegroups.com.

In that email, please outline why you can't split your JSON files into smaller chunks.
