### ISSUE TITLE
data "compression"

### ISSUE THREAD

**Issue by schmurfy** [influxdb/influxdb#498]
@pauldix  Some time ago (when influxdb was in the 0.4.x releases range) you mentioned discussions about compressing redundant data, for example when you have:
```json
[
  {
    "type" : "something",
    "value" : 32
  },
  {
    "type" : "something_else",
    "value" : 42
  },
  {
    "type" : "something",
    "value" : 5.6
  }
]
```

Influxdb could provide a way to declare that the type column store a string and should be compressed, that way the string itself would be stored only once and an integer would be used instead in each records mentioning the same value.

Is this idea still around ?:)

**Comment by toddboom** [comment]
We probably won't be doing any explicit compression for v0.9.0, but the new datastore should be fairly intelligent about not wasting space. Closing this out since there's nothing actionable left to do for the next release.
