### ISSUE TITLE
UDP service stops processing the queue if gets a bad route in a message

### ISSUE THREAD

**Issue by lekz** [influxdb/influxdb#4991]
#UDP service stops processing the queue if gets a bad route in a message

I had a configured listener via UPD and it stopped processing data from time to time. At the same time via netstat tool I saw a huge queue for the UDP port I used and I did not find any new data in my DB. 
After some time I found that influxdb stopped processing data just after it got a message with the tags with empty values. There were messages about empty tags in my log-file.
After I improved my code and stopped sending bad tags influxdb started to work well.

**Comment by beckettsean** [comment]
@lekz Can I ask why you closed the issue? If the UDP port really does hang after a bad point we should address that.
