### ISSUE TITLE
[0.9.5] UDP service stops processing the queue if gets a bad tag in a message

### ISSUE THREAD

**Issue by lekz** [influxdb/influxdb#4992]
*UDP service stops processing the queue if gets a bad route in a message*

I had a configured listener via UPD and it stopped processing data from time to time. At the same time via netstat tool I saw a huge queue for the UDP port I used and I did not find any new data in my DB. 
After some time I found that influxdb stopped processing data just after it got a message with the tags with empty values. There were messages about empty tags in my log-file.
After I improved my code and stopped sending bad tags influxdb started to work well.

**Comment by jhhayden** [comment]
Believe I am experiencing the same issue. I am using 0.9.6_nightly_d85f3c3-1. What version are you using?

**Comment by jhhayden** [comment]
Reverted to 0.9.5.1-1 and the same behavior

**Comment by beckettsean** [comment]
@lekz what version of InfluxDB are you running?

**Comment by jhhayden** [comment]
Not sure if this is helpful but this is from the _internal db on my machine the the last 10 entries in the udp measurement:

select * from udp order by desc limit 10
name: udp
---------
time			batchesTx	batches_tx	batches_tx_fail	bind	bytesRx	bytes_rx	clusterID		hostname	nodeID	pointsParseFail	pointsRx	pointsTx	points_parse_fail	points_rx	points_tx
1449259557000000000	1						:8125	169677			6831629435102081664	ip-10-25-2-151	1	1		8		8
1449259557000000000	1						:8126	155307			6831629435102081664	ip-10-25-2-151	1	1		5		5
1449259547000000000	1						:8125	169677			6831629435102081664	ip-10-25-2-151	1	1		8		8
1449259547000000000	1						:8126	155307			6831629435102081664	ip-10-25-2-151	1	1		5		5
1449259537000000000	1						:8125	169677			6831629435102081664	ip-10-25-2-151	1	1		8		8
1449259537000000000	1						:8126	155307			6831629435102081664	ip-10-25-2-151	1	1		5		5
1449259527000000000	1						:8125	169677			6831629435102081664	ip-10-25-2-151	1	1		8		8
1449259527000000000	1						:8126	155307			6831629435102081664	ip-10-25-2-151	1	1		5		5
1449259517000000000	1						:8125	169677			6831629435102081664	ip-10-25-2-151	1	1		8		8
1449259517000000000	1						:8126	155307			6831629435102081664	ip-10-25-2-151	1	1		5		5

**Comment by jhhayden** [comment]
Ok, more info:
We have a system taking incomming data correctly. If we attempt to send a packet via udp using this command: echo 'nate_test value=1 place=host'|nc -uvv -w1 influx.whoop.in 8126`

influx is no longer able to process udp packets. The packets are still coming in but they are not being processed?
If we restart influxdb, everything goes back to normal, so it looks like there may be a problem with malformed data coming in.

**Comment by lekz** [comment]
Yes, I use v0.9.5.

**Comment by KiNgMaR** [comment]
:+1: - also UDP packets with tags only (no fields) cause this behavior.

**Comment by otoolep** [comment]
Thanks for the report @lekz et al. -- fixed by #5029

**Comment by otoolep** [comment]
Will be fixed in 0.9.6.
