### ISSUE TITLE
[feature request] Allow home, end, ctrl+left, ctrl+right in CLI

### ISSUE THREAD

**Issue by clongbottom** [influxdb/influxdb#5008]
The CLI is great, but it's quite hard to edit an old query. What makes it much quicker in other CLIs is being able to move to the beginning or end of a query quickly, and being able to move quickly by word by using the ctrl+left/right functions. 

I don't think this would be too difficult to implement, but could save developers lots of time?

**Comment by mark-rushakoff** [comment]
The Influx CLI uses [liner](https://github.com/peterh/liner), whose README has a helpful table of the keyboard shortcuts available.

I found that depending on which terminal (and OS settings for that matter) you're using, some of the shortcuts might get swallowed. For example, `^a` and `^e` move to the front/end of the line as expected everywhere I tried it, but `alt-b` was swallowed by iTerm and accepted by the OSX native terminal.

**Comment by clongbottom** [comment]
Perfect- works fine, thanks.
