### ISSUE TITLE
[0.9.6_nightly_bcc1ad0] It seem we can not use 'name' in a where condition.

### ISSUE THREAD

**Issue by mail2fish** [influxdb/influxdb#5012]
Ex: select * from Requests where name='H_POST_ATTACK_MARCH' limit 1

Got an error: Server returned error: error parsing query: found NAME, expected identifier, string, number, bool at line 1, char 30

**Comment by mail2fish** [comment]
The same problem happend  when 'name' in the select field.

ex: select name from a_db

**Comment by mark-rushakoff** [comment]
`name` is a keyword. Put double quotes around it to inform the parser it's an identifier, not a keyword: e.g. `SELECT "name" FROM a_db`.

@beckettsean @dgnorton People seem to be stumbling over this quite a bit – do you think there's a way we can improve the parser error message to "help people help themselves"?

**Comment by dgnorton** [comment]
Yeah, anywhere we're expecting an identifier and we get a keyword instead, we can suggest surrounding it with double quotes.

**Comment by mail2fish** [comment]
Actually I tried: select "name" from a_db. but I got this:

Server returned error: statement must have at least one field in select clause

**Comment by mail2fish** [comment]
Well,  I got this.  In our database the name is a tag. So I have to put a field in select statement.

Ex: select "name", count from a_db.

That's work.

Thanks

If the error show an example, that would be nice.
