### ISSUE TITLE
Site(influxdb.com) down for more than two days now

### ISSUE THREAD

**Issue by sambhavsharma** [influxdb/influxdb#5014]
influxdb.com is down for more than two days now. That restricts access to all official tutorials, documentation and downloads. Please get it up and running asap.

**Comment by rapport** [comment]
It has worked for me in the UK! What network/location are you accessing it from? Can you provide a way to reproduce  i.e. http://www.webpagetest.org/?

**Comment by sambhavsharma** [comment]
Hi,
Apologies, some one from our networking team have messed up our wifi. I tried this from my phone's internet and is working fine. Closing this.
