### ISSUE TITLE
Can store measurement with name "measurement" but not query it

### ISSUE THREAD

**Issue by mukatee** [influxdb/influxdb#5015]
It is possible to store measurements for a measurement named "measurement" but not query it. Example code in Python:

import time
from influxdb import InfluxDBClient
from influxdb.exceptions import InfluxDBClientError

client = InfluxDBClient("localhost", 8086, "my_user", "my_pass", "my_test_db")
try:
    client.create_database("my_test_db")
except InfluxDBClientError as e:
    print("Error while creating database, assuming it already exists:"+str(e))

item = [{"measurement": "measurement",
      "time": int(time.time()),
      "fields": {"value": "1"}
     }
    ]
result = client.write_points(item, time_precision='ms')
print(result)
result = client.query('select * from measurement;')
print("Result: {0}".format(result))

The code above results "True" for the "write_points". But the query "select * from measurement" gives an error 

influxdb.exceptions.InfluxDBClientError: 400: {"error":"error parsing query: found MEASUREMENT, expected identifier at line 1, char 15"}

I also get the same error from the admin UI when performing the same query. "show measurements" shows that I have a measurement named "measurement" but the query to "select * from measurement" gives the same error.

Looking at the line protocol, it gives the code 204 back on write so it seems to also pass fine from that view.

This was on InfluxDB 0.9.5.1. 

Maybe it could just tell me that the measurement name is invalid when trying to create? Or then accept it as a name in query..

**Comment by mark-rushakoff** [comment]
Put double quotes around measurement to inform the parser that it's an identifier, not a keyword: e.g. `SELECT * FROM "measurement"`.

**Comment by otoolep** [comment]
I think we can close this.

**Comment by beckettsean** [comment]
For future reference: https://influxdb.com/docs/v0.9/query_language/query_syntax.html#identifiers-double-quoted
