### ISSUE TITLE
Issue with time precision, while writing into the database.

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb#5021]
I am trying to insert points into influxdb using default time precision(nanoseconds), the write succeeds  but looks like it is written badly as querying the same time series returns nothing.

*influxDB version: InfluxDB v0.9.4.2 (git: 0.9.4 da1b59e7d7764d36786253b2db13b97f42ed4e1d)*

**Document says by default it is inserted in nanoseconds** -> doesn't work

**current time in epoch**
$ date +%s
1449516333
**insert using line protocol**
$ curl -i -XPOST 'http://10.91.39.34:8086/write?db=metrics' --data-binary 'cpu_load_short,host=server02,region=us-west value=0.55 1449516333000000000'
HTTP/1.1 204 No Content
Request-Id: 92a447e3-9d17-11e5-8026-000000000000
X-Influxdb-Version: 0.9.4.2
Date: Mon, 07 Dec 2015 19:20:27 GMT

 **query the inserted series**: *returns an empty result*
$ curl -G 'http://10.91.39.34:8086/query?pretty=true' --data-urlencode "db=metrics"   --data-urlencode "q=select * from cpu_load_short"
{
    "results": [
        {}
    ]
}

**Comment by jackzampolin** [comment]
On `0.9.6` the following curl commands return the proper results:

```
$ curl i -XPOST 'http://localhost:8086/write?db=metrics' --data-binary "cpu_load_short,host=server02,region=us-west value=0.55 1449516333000000000"

HTTP/1.1 204 No Content
Request-Id: 85e540c7-9eb8-11e5-8006-000000000000
X-Influxdb-Version: 0.9
Date: Wed, 09 Dec 2015 21:05:06 GMT

$ curl -G "http://localhost:8086/query?pretty=true" --data-urlencode "db=metrics" --data-urlencode "q=select * from cpu_load_short"
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "host",
                        "region",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-12-07T19:25:33Z",
                            "server02",
                            "us-west",
                            0.55
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by beckettsean** [comment]
@prashleo Your timestamp is incorrect somehow. 1449516333 translates to Mon, 07 Dec 2015 19:**25**:33 GMT, but your `curl` output shows Mon, 07 Dec 2015 19:**20**:27 GMT.

You wrote a point into the future, which is why it was not returned. See https://docs.influxdata.com/influxdb/v0.9/troubleshooting/frequently_encountered_issues/#querying-after-now for more info.
