### ISSUE TITLE
Build problems building 0.9.5.1 from source on ubuntu and linux

### ISSUE THREAD

**Issue by rapport** [influxdb/influxdb#5024]
When I try to build influxdb from source I get lots of errors from the tsdb code and the build fails. Can anyone help resolve this?

C:\Go\projects\src\github.com\influxdb\influxdb>go build ./...

...

tsdb\engine\tsm1\mmap_windows.go:13: too many arguments to return
tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.Mmap
tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.PROT_READ
tsdb\engine\tsm1\tsm1.go:1974: undefined: syscall.MAP_SHARED
tsdb\engine\tsm1\tsm1.go:2033: undefined: syscall.Munmap

I am able to hack around with code and get it to build but am not really sure why it fails. I wonder if the official build environment is using caching and not picking up on these errors from libraries that could be obsolete.

This issue is possibly related to the issue #4787 on solaris

Also, do we really need this tsdb, nmaps stuff to run influxdB? I guess it is just collecting some internal metrics and won't break anything when I comment it out to get a build the working!

**Comment by otoolep** [comment]
@rapport -- do we need to build the tsdb package? The tsdb package *is* the time-series storage code. 

We are working through Windows build issues, but have no timeline for when they will be fixed, except master will be buildable on Windows by 1.0. In the meantime you might like to build the 0.9.4 branch, as that does compile on Windows.

Closing as known issue. Please let me know if this incorrect.

**Comment by rapport** [comment]
I think I have a similar issues building 0.9.5.1 on linux ubuntu 14.04 with the tsdb package and it sounds like fazalmajid has similar problems on Unix Solaris. 

However, I am actually most interested in trying something on windows 32-bit at the moment with some of the recent windows IoT sensors and appreciate that you have pointed me to 0.9.4 branch!
