### ISSUE TITLE
0.9.6-nightly-9637446, Timeout  issue 

### ISSUE THREAD

**Issue by hiepsikhokhao** [influxdb/influxdb#5030]
Hi,

I use influxdb to aggregate nginx access log. Sometime many line of logs are same ( time and content ), so i add a random number ( 0 - 1000000) as tag to unique log and push to influxdb.

My input current: ~ 1000 line/s  , expect in production: 100k line/s

I run CQ calculate logs  group by 1h.  

Do I used influxdb right for this purpose ? I must always restart influxdb when it's timeout. 
Could  you  give me some advise on my case ?

Error log: after line  "write to index of partition 1" , all push requests  timeout.  I have just restarted influxdb  some minutes before.

[http] 2015/12/08 09:28:41 ::1 - mecdn [08/Dec/2015:09:28:41 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 204 0 - Ruby 65448c83-9d53-11e5-8011-000000000000 2.055148ms
[http] 2015/12/08 09:28:44 ::1 - mecdn [08/Dec/2015:09:28:44 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 204 0 - Ruby 673d895f-9d53-11e5-8012-000000000000 7.48704ms
[http] 2015/12/08 09:28:47 ::1 - mecdn [08/Dec/2015:09:28:47 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 204 0 - Ruby 68d95787-9d53-11e5-8013-000000000000 2.799846ms
[wal] 2015/12/08 09:28:52 Flush due to idle. Flushing 1641 series with 1641 points and 283366 bytes from partition 1
[wal] 2015/12/08 09:28:52 write to index of partition 1 took 65.163637ms
[http] 2015/12/08 09:29:30 ::1 - mecdn [08/Dec/2015:09:28:29 +0700] POST /write?db=cdn_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby 5e6206cc-9d53-11e5-800d-000000000000 1m0.757836015s
[http] 2015/12/08 09:29:50 ::1 - mecdn [08/Dec/2015:09:28:50 +0700] POST /write?db=dns_raw_log&p=%5BREDACTED%5D&precision=s&u=mecdn HTTP/1.1 500 44 - Ruby 6aa389a4-9d53-11e5-8014-000000000000 1m0.000965556s

**Comment by otoolep** [comment]
Using a random number as a tag will result in a very poor performance, as
the cardinality of the tag could be very high. Each different tag value
will result in a different series on disk, which will mean a different
random access.

Try making your random number a value (which will not mean a new series
each time) and see if performance improves.

Philip

**Comment by hiepsikhokhao** [comment]
Hi 
Thank @otoolep . I knew it. 

I use tag = random number  to make nginx access log (in same time and same content) will be appeared in influxdb. 
if i make random number a value , my log will be missed. 
Do you have different ideas ?

Regards

**Comment by otoolep** [comment]
If the log line and the time are exactly the same why bother keeping more than 1 copy? If you must don't use tag for your random value, use a field, which won't impact performance too much.

**Comment by hiepsikhokhao** [comment]
Hi,

Oh. Thanks so much. It's very simple ... why i dont know it before . 

Regards
