### ISSUE TITLE
WAL backed up flushing to index, hit max memory

### ISSUE THREAD

**Issue by pfischermx** [influxdb/influxdb#5033]
Hello,

So, we been running tsm1 for a while, we switched to nightly and then we tried the 0.9.5 release (0) and that did not went well (influx had frequent crashes), so we rolled back to the previous nightly version and all has been good for about 3 weeks.

... up until now that we decided we wanted to add more retention to our data, we moved from 1h to a 1w (so that our folks can ask for graphs for the last 7 days / 1 week). And now we are hitting this:

```
[write] 2015/12/08 08:52:59 write failed for shard 14799 on node 1: engine: WAL backed up flushing to index, hit max memory
[udp] 2015/12/08 08:52:59 failed to write point batch to database "metrics": write failed: engine: WAL backed up flushing to index, hit max memory
```

We write a lot of metrics and we add them via UDP, that _has_ been working great with a retention of 1d. 

I looked for this error and there seems to be a lot of report of it but not many of them point to exactly what settings one should be looking at and also, should be flush/memory be increased or decreased (perhaps to add more flushing). Our settings are:

```
  max-wal-size = 1073741824
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-logging-enabled = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5s"
  wal-partition-size-threshold = 20971520
```
fwiw, the version that we been running with no issues is:
```
$ influxd version
InfluxDB v0.9.5-nightly-9633410 (git: master 96334108e2479543b3235943c1e5d144a62514a5, built '2015-10-26T04:00:42+0000')
```
Yes I know it is a bit behind but as I said, the 0.9.5 versions have been quiet a bit unstable and we needed to keep the data stable otherwise our dashboards wouldn't have data.

So, what settings should we be looking/modifying too? Please note that the max-wal-size was increased to 500MB and that did not help, now (a couple of minutes ago) we bumped to 1G.

Thanks

**Comment by beckettsean** [comment]
@pfischermx it sounds like the machine is starved for RAM when trying to flush the WAL. How much RAM is available to the process?

**Comment by beckettsean** [comment]
Have you tried with 0.9.6.1?

**Comment by pfischermx** [comment]
I'm _just_ (as of few minutes ago) started testing 0.9.6.1, I wiped our DB so this is a "fresh" start. I'll see what it goes.

Related to RAM, I don't recall seeing any of those hosts suffering from RAM or starvation but I'll check again and update if I see the same issue with 0.9.6.1. In the mean time this is the configuration we are using with 0.9.6.1:

https://gist.github.com/pfischermx/2e5c791f9fad1b95ffeb

**Comment by pfischermx** [comment]
Ok. Now running 0.9.6.1 on 80% of our hosts and I still don't see that error back so maybe it has been fixed (I also noted that RAM usage reduced a LOT on 0.9.6.1).

... however from time to time I see that the metrics show some "holes" on grafana however I'm not able to pin-point to any error. I'm closing this issue and will open a new one if I find something odd.

Thanks!
