### ISSUE TITLE
[feature request] Run FIRST, LAST, TOP, BOTTOM without specifying time or group

### ISSUE THREAD

**Issue by clongbottom** [influxdb/influxdb#5038]
I don't see why it is necessary to  specify time, for example how do I find out how long ago an event was, that might be 1s, 1h, or 1 month ago? selecting LAST(value) WHERE time > now() - 30d is going to be really inefficient if the event was only 1 second ago, and grouping isn't going to help in this situation.

The common use case is simply to know how stale your most recent data is. Is there another solution to this problem?

**Comment by otoolep** [comment]
What you actually want is to order by time descending and do `LIMIT 1`

**Comment by otoolep** [comment]
Check out the docs here:

https://influxdb.com/docs/v0.9/guides/querying_data.html

Let us know if this doesn't solve your issue.
