### ISSUE TITLE
fill(none) does not apply to count()

### ISSUE THREAD

**Issue by hoomanv** [influxdb/influxdb#5042]
I have this query
```
select count(value) from event where time > now() - 1d and time < now() group by time(1m) fill(none)
```
And the result has 1440 records even for those empty intervals
If I change the query to
```
select count(value),max(value) from event where time > now() - 1d and time < now() group by time(1m) fill(none)
```
It will leave empty intervals out

So basically count() alone is not taken into account by fill(none).
But I believe it should have.

**Comment by corylanou** [comment]
Are you on nightly?  This got pushed to master yesterday and might fix that issue: https://github.com/influxdb/influxdb/pull/5000

**Comment by hoomanv** [comment]
No I'm not. I will see if I can install the rpm and test it

**Comment by hoomanv** [comment]
I just tested it against 0.9.7_nightly_9c65e17-1 and still seems broken

**Comment by corylanou** [comment]
Ok. Thanks.  @nathanielc is this something you want to look at since you were just in there?  Adding a test should be easy enough based on the info above I think.

**Comment by otoolep** [comment]
Count should always returns 0 for intervals without points. That is the
definition of count, and therefore doesn't return an empty interval. The
interval will have a value zero.

Fill does not apply to count.

**Comment by corylanou** [comment]
@otoolep I think he is saying he isn't getting intervals, and he should because count should always be zero.  I agree that `fill(none)` shouldn't have an affect, but still feels like a bug in here.

@hoomanv can you show us some sample outputs in a gist for each query so we can understand this better?

**Comment by hoomanv** [comment]
May be I wasn't clear enough. I am getting 0 counts for intervals without points. But I expected that fill(none) would eliminate 0 counts. This can be more illustrative with an example:

We write a point to the QueueEvent measurement every time a token arrives or leaves a queue.
Line protocol looks something like this: QueueEvent,queue=1 token="abc",length=8i
There is a CQ that rolls up the number of QueueEvents that occurred by 1 minute intervals.
That is generating a lot of zeros which are useless and just waste storage.

If count() is not meant for this, then we need another count function that excludes zeros if fill(none)

**Comment by otoolep** [comment]
You make a good point.

@pauldix -- after we changed `count` to always return 0, it is now not possible to suppress zero values in the output.

**Comment by nathanielc** [comment]
I agree fill none should suppress counts of zero. This should be similar to
my previous change.

**Comment by pauldix** [comment]
agree

**Comment by otoolep** [comment]
OK, sending your way @nathanielc - sound good?

**Comment by hoomanv** [comment]
Thank you for your great support.
