### ISSUE TITLE
0.9.6-rc1 deletes .tsm files before closing file descriptor

### ISSUE THREAD

**Issue by dswarbrick** [influxdb/influxdb#5046]
This might be jumping the gun a little, but I noticed strange / conflicting values from `df` and `du` on my 0.9.6-rc1 system:
```
$ df -h /srv
Filesystem      Size  Used Avail Use% Mounted on
/dev/md0        738G   26G  676G   4% /srv

$ sudo du -skh /srv
3.0G	/srv
```
If I restart InfluxDB, the used space reported by `df` then lines up with `du`. Digging deeper, it appears that the influxd process has file descriptors to non-existent files:
```
$ sudo lsof -c influxd -a -d DEL
COMMAND   PID     USER  FD   TYPE DEVICE SIZE/OFF     NODE NAME
influxd 13214 influxdb DEL    REG    9,0          35520616 /srv/influxdb/data/perfdb/default/2/000000180-000000003.tsm
influxd 13214 influxdb DEL    REG    9,0          35520613 /srv/influxdb/data/perfdb/default/2/000000178-000000003.tsm
influxd 13214 influxdb DEL    REG    9,0          35520618 /srv/influxdb/data/perfdb/default/2/000000182-000000002.tsm
influxd 13214 influxdb DEL    REG    9,0          35520617 /srv/influxdb/data/perfdb/default/2/000000181-000000002.tsm
influxd 13214 influxdb DEL    REG    9,0          35520612 /srv/influxdb/data/perfdb/default/2/000000178-000000002.tsm
...
```
I suspect that InfluxDB is unlinking these files before closing the FD. Peeking inside `/proc/$(pidof influxd)/fd` however, there are only descriptors to legitimate files / sockets. I have to admit, I've never seen this behaviour before, but my gut feeling is that the ext4 superblock "free block count" is not being updated as a result of these orphaned FDs - hence the disagreement between `df` and `du`. And I'm pretty sure I know what will happen when ext4 says there are no free blocks left...

**Comment by otoolep** [comment]
@jwilder

**Comment by jwilder** [comment]
I'll take a look.  The code should be closing before deleting any TSM files.  It's done here: https://github.com/influxdb/influxdb/blob/master/tsdb/engine/tsm1/file_store.go#L346-L352, but possibly something else is going on.

**Comment by jwilder** [comment]
@dswarbrick Fix for this should be in the next nightly/RC build.  Thanks!

**Comment by dswarbrick** [comment]
@jwilder awesome! I'll check it out tomorrow morning. Thanks for the quick resolution!
