### ISSUE TITLE
Continuous Query : Writing 'Nulls' When Upstream Table has no Data

### ISSUE THREAD

**Issue by ericjmiller** [influxdb/influxdb#5048]
I have written a continuous query that should store the minimum of several fields every 5 seconds, grouped by a tag called job_name (hence the * at the end).  Here is the query:

    CREATE CONTINUOUS QUERY min_scores on nba_hadoop_jobs begin 
    select min(best_score) as min_best_score, min(bus_dim) as min_bus_dim, 
    min(net_dim) as min_net_dim, min(struct_dim) as min_struct_dim, 
    min(travel_dim) as min_travel_dim 
    into min_scores from para_sched_scores group by time(5s), * end

This query runs at a rapid pace in the logs, and also fills up with 'nulls' when there is no data in the last 5 seconds in the upstream table.  Eventually, it does stop writing 'nulls', but not before there are a while bunch of them.

What am I doing wrong here?

**Comment by beckettsean** [comment]
@rkuchan I think you were doing some research on this very behavior, yes?

**Comment by rkuchan** [comment]
I've come across the same thing. Continuous queries (and queries with `INTO`) that have more than one function in the `SELECT` statement store nulls by default. Continuous queries with just one function don't store nulls by default. Here's the issue: https://github.com/influxdb/influxdb/issues/5116. 

Appending `fill(none)` to the end of your CQ should take care of this issue for now. See [Data exploration](https://docs.influxdata.com/influxdb/v0.9/query_language/data_exploration/#the-group-by-clause-and-fill) for more on `fill()`.

**Comment by rkuchan** [comment]
@ericjmiller, on a related note, have you changed the configuration settings for continuous queries? The short length of your CQ's `GROUP BY time()` interval wouldn't work well with the default settings; InfluxDB might miss intervals with valid data. 

Depending on your data, it might be good to change the `recompute-previous-n` setting to `11` and the `compute-no-more-than` setting to `1m0s`. This makes InfluxDB generate 12 queries (one for the current `GROUP BY time()` interval and 11 for the previous 11 intervals) every minute.

We have some documentation in progress on configuring CQs if you'd like more context on this: https://github.com/influxdb/docs.influxdata.com/pull/93

**Comment by ericjmiller** [comment]
@rkuchan 

Thanks for the '''fill()''' tip - I'll check it out!

Regarding your CQ config suggestions: I need the downsample to be somewhat real-time.  I can't wait 1 minute for the downsample to pull from the higher table for the last 12 5-second intervals.  I was thinking of '''compute-runs-per-interval''' set to 1, '''compute-no-more-than''' set to '''5s''', and '''recompute-previous-n''' set to 2 (maybe even 0).  Ultimately, I just want a real time downsample every 5 seconds.

**Comment by rkuchan** [comment]
@ericjmiller, those settings will work for what you want  :)

Closing this in favor of  https://github.com/influxdb/influxdb/issues/5116
