### ISSUE TITLE
[0.9.5.1] COUNT() doesn't work ?

### ISSUE THREAD

**Issue by Nurza** [influxdb/influxdb#5049]
Hello, I am using InfluxDB 0.9.5.1, when I want to count how many points I have, I do:

SELECT COUNT(ft) FROM haproxy

But I have this error (in WebUI and InfluxDB shell):

```
ERR: statement must have at least one field in select clause
```

Am I doing it wrong? Thank you!

**Comment by otoolep** [comment]
From the error message, `ft` is not a field. Did you make it a tag? Does it even exist? Please show us the data you are inserting.

**Comment by Nurza** [comment]
Thank you for you response, ft is a tag indeed. I did not know tags can't be used with COUNT. It's the same with all the functions (https://influxdb.com/docs/v0.9/query_language/functions.html) ?

**Comment by otoolep** [comment]
Yes, it's the same.

**Comment by Nurza** [comment]
Thank you very much, the error should display a warning saying "ft is a tag, not a field you can't do that omg!!!"
