### ISSUE TITLE
[0.9.5] - Issue show measurement

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb#5050]
Hi Team,

On cluster based on 0.9.5, i got this error when running show measurement on database _internal : 

Server returned error: json: cannot unmarshal array into Go value of type tsdb.MapperOutputJSON

Version used: 
InfluxDB v0.9.5.1 (git: 0.9.5 9eab56311373ee6f788ae5dfc87e2240038f0eb4, built 2015-11-25T23:01:58+0000)

Is it a know issue ?
do you know if the 0.9.6 will fix it and when it'll be released ?

Thanks,
Julien.

**Comment by otoolep** [comment]
Yes, it is @JulienChampseix 

Should be fixed in 0.9.6, let us know if you still see it with that release.

**Comment by JulienChampseix** [comment]
@otoolep good news !! where can i find the 0.9.6 deb package ? is it released the 0.9.6 version ? cuz changelog was noticed as unreleased this morning

**Comment by otoolep** [comment]
0.9.6 is still pending, should be out shortly. Keep an eye on the blog page.
