### ISSUE TITLE
using parens in query math broken

### ISSUE THREAD

**Issue by jhhayden** [influxdb/influxdb#5054]
When using parens in a query calculation, the resulting data is not returned: ie select field1 -field2 from measuremnt returns 2 columns - timestamp and calculated data but select field1 - field2 from measurement returns only 1 column, the timestamp. We will need the parens to work correctly for any calculation that involves determining order of precedence. See examples below:

> select * from memory limit 10
name: memory
------------
time			buffers		cached		dirty	duration	free		freeWOBuffersCaches	host			swapFree	swapTotal	swapUsed	total			used			usedWOBuffersCaches
1449597912000000000	4.0574976e+08	2.02121216e+09	32768	0.102		8.9714688e+08	3.3241088e+09		utils-sigProcNFS	0		0		0		4.147191808e+09		3.250044928e+09		8.23083008e+08
1449597912000000000	1.43507456e+08	3.00621824e+08	200704	0.13		6.0059648e+07	5.04188928e+08		prod-api-server-15	0		0		0		7.84656384e+09		7.786504192e+09		7.342374912e+09
1449597912000000000	1.48922368e+08	1.573494784e+09	28672	0.12		2.09580032e+09	3.818217472e+09		utils-sensuServer	0		0		0		4.147191808e+09		2.051391488e+09		3.28974336e+08
1449597912000000000	2.30084608e+08	9.77952768e+08	36864	0.135		1.96038656e+08	1.404076032e+09		prod-upcalc-worker-1	0		0		0		1.57745152e+10		1.5578476544e+10	1.4370439168e+10
1449597912000000000	2.0959232e+08	1.304064e+09	20480	0.114		2.336739328e+09	3.850395648e+09		utils2-bastion		0		0		0		4.14793728e+09		1.811197952e+09		2.97541632e+08
1449597912000000000	8.2362368e+07	2.31645184e+08	253952	0.752		2.8311552e+07	3.42319104e+08		qa-api-server-5		0		0		0		3.950567424e+09		3.922255872e+09		3.60824832e+09
1449597912000000000	3.15895808e+08	9.53696256e+08	184320	0.123		1.230589952e+09	2.500182016e+09		prod-api-server-16	0		0		0		1.57745152e+10		1.4543925248e+10	1.3274333184e+10
1449597912000000000	1.790976e+08	5.69434112e+08	204800	0.131		1.25640704e+08	8.74172416e+08		prod-upcalc-worker-2	0		0		0		1.5773765632e+10	1.5648124928e+10	1.4899593216e+10
1449597912000000000	1.96386816e+08	1.175334912e+09	122880	0.119		8.430239744e+09	9.801961472e+09		stg-api-server-24	0		0		0		1.5774511104e+10	7.34427136e+09		5.972549632e+09
1449597912000000000	2.28794368e+08	1.29849344e+09	45056	0.113		2.299899904e+09	3.827187712e+09		utils-opentsdbFE-001	0		0		0		4.14793728e+09		1.848037376e+09		3.20749568e+08

> select (free - dirty) from memory limit 10
name: memory
------------
time
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000
1449597912000000000

> select free - dirty from memory limit 10
name: memory
------------
time
1449597912000000000	2.095771648e+09
1449597912000000000	8.430116864e+09
1449597912000000000	8.777043968e+09
1449597912000000000	1.25435904e+08
1449597912000000000	1.837514752e+09
1449597912000000000	1.0315415552e+10
1449597912000000000	1.06901504e+08
1449597912000000000	7.08026368e+08
1449597912000000000	2.336718848e+09
1449597912000000000	1.7391616e+08

**Comment by jhhayden** [comment]
ok, more info: apparently parens DO work 

select (free - dirty)/free from memory limit 10
name: memory
------------
time
1449597912000000000	0.9998502181821813
1449597912000000000	0.9999854239020797
1449597912000000000	0.9910300925925926
1449597912000000000	0.9999804095822076
1449597912000000000	0.999986319307366
1449597912000000000	0.9983699550107583
1449597912000000000	0.996146295353741
1449597912000000000	0.9999634753230151
1449597912000000000	0.9999882358477248
1449597912000000000	0.9966582554729592

**Comment by otoolep** [comment]
All fixed.
