### ISSUE TITLE
[DOC]  What does it mean that it's not recommended to use timestamp with "NewPoint" ?

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5061]
Documentation needs clarification:
(https://godoc.org/github.com/influxdb/influxdb/client/v2#NewPoint)

func NewPoint
func NewPoint(
    name string,
    tags map[string]string,
    fields map[string]interface{},
    t ...time.Time,
) (*Point, error)
NewPoint returns a point with the given timestamp. If a timestamp is not given, then data is sent to the database without a timestamp, in which case the server will assign local time upon reception. NOTE: it is recommended to send data without a timestamp.

Kind request:
Add more documentation on why it's recommended not to supply a time stamp.

**Comment by sparrc** [comment]
This is wrong, it should say it _is_ recommended to send data with a timestamp
