### ISSUE TITLE
[0.9.6] Limit clause not respected for count

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#5063]
The queries should say it all.
```
> select count(response_time) from performance where method='read' limit 10
name: performance
-----------------
time	count
0	250

> select count(response_time) from performance where method='read'
name: performance
-----------------
time	count
0	250
```

**Comment by mark-rushakoff** [comment]
The queries don't say it all to me. Were you expecting the first query to have count = 10? I would expect the LIMIT to constrain the total number of rows returned, and you're only getting one row back, not hitting the limit of 10.

**Comment by mjdesa** [comment]
@mark-rushakoff I was thinking that it should return count of 10 or less. But on second though you're right.
