### ISSUE TITLE
 Best practise - upgrade influxdb cluster

### ISSUE THREAD

**Issue by JulienChampseix** [influxdb/influxdb#5073]
Hi Influx Team,

I would know what's the best practise to upgrade influxdb cluster having 3 nodes where node 1 is the first node, node2 is the second node (having join to node1 in default/influxdb file), node3 is the third node (having join to node1, node2 in default/influxdb file).

What's the plan bellow is the best practise to follow :

    1/ stop all influxdb on every nodes (starting by node3, node2 and node1)
    2/ dpkg -i the latest influxdb package
    3/ check config influxdb is ok after upgrade
    4/ start node1 & check log for be sure influxdb started well
    5/ start node2 & check log for be sure influxdb started well
    6/ start node3 & check log for be sure influxdb started well
    7/ Party ! Cluster upgraded

Thanks influxdb team for your feedback !

Julien.

**Comment by jackzampolin** [comment]
@JulienChampseix Thats the way we do it here! Closing this in favor of a docs repo issue: https://github.com/influxdb/docs.influxdata.com/issues/22

**Comment by JulienChampseix** [comment]
@jackzampolin FYI the link return 404 page not found (maybe it's a private repo not open to public)

**Comment by jackzampolin** [comment]
@JulienChampseix Its a private repo that we will be opening up in the next couple of days as we finish migration to our new site: [InfluxData](https://www.influxdata.com)
