### ISSUE TITLE
influx non-interactive mode - INSERT must be handled

### ISSUE THREAD

**Issue by marinonjalsson** [influxdb/influxdb#5078]
if I try to insert measurement though non-interactive mode like:
```
influx -database measure -execute 'INSERT sensor,floor=1 value=2'
ERR: error parsing query: found INSERT, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 1
```
Where is the insert function non-interactive mode?

version:
```
 influx -version
InfluxDB shell 0.9.6
```

Marinó

**Comment by otoolep** [comment]
Thanks for the report @marinonjalsson 

What is most likely happening here is that `INSERT` is not a real keyword. Instead it is intercepted by the CLI and converted into a write query. The CLI code should be updated to check for that in non-interactive mode.

Marking this as "help-wanted" as it should not be too difficult for someone who would like to help out with the source.

In the meantime, you know you can insert data via `curl`, right? That will get you exactly the same thing (it's basically what the CLI would do).

**Comment by grange74** [comment]
I'd like to try fixing this. I've looked at code and can see where this is happening.
I just want to confirm the expected behaviour is to allow inserts in non-interactive mode just like it does for interactive mode?
Also does it need to support multiple insert statements?

**Comment by gunnaraasen** [comment]
@grange74 That seems like expected behavior. I think the following changes could significantly improve the CLI's non-interactive feature.
- Make the non-interactive mode send everything through the CLI's parser the same way the interactive mode works.
- Add options to execute non-interactive mode so that it does not use the CLI's parser, e.g. `-execute-write` and `-execute-query`.
- Add multiline support to all non-interactive mode options.

A PR for any of the above would be greatly appreciated.

**Comment by otoolep** [comment]
@gunnaraasen -- I don't see the point of the second idea. Can you explain why one would want that?

**Comment by gunnaraasen** [comment]
If `-execute` goes through the CLI parser, then a file containing a bunch of line protocol points would need to have `INSERT` appended to every line. An `-execute-write` option would not use the CLI's parser, e.g. it would be equivalent to `curl`. Maybe `-execute-raw-write` would be a better name for that option.

**Comment by otoolep** [comment]
I see.

Yeah, that could be handy.

**Comment by grange74** [comment]
Thanks, i'll have a go at the first idea. It makes a lot of sense. 
For other two, i'll see if i get time, i'm assuming they should probably be separate PRs.
