### ISSUE TITLE
yum repository (RHEL7): Wrong path

### ISSUE THREAD

**Issue by bbczeuz** [influxdb/influxdb#5083]
Using the description at https://influxdb.com/blog/2015/12/04/introducing_repos_influxdata.html
to install the influxdb via yum repository on a RHEL 7 server results in:

[root@pub influxdb]# yum install influxdb
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
https://repos.influxdata.com/rhel/7Server/x86_64/stable/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
[...]

--> The path in the influxdb.repo is wrong for RHEL7 (server)

Temporary fix:
- Replace $releasever to '7' in /etc/yum.repos.d/influxdb.repo

Proposed solution:
- Add at a symlink on https://repos.influxdata.com/rhel/7 to  https://repos.influxdata.com/rhel/7Server

**Comment by rossmcdonald** [comment]
@bbczeuz Fixed. Thanks for letting us know!
