### ISSUE TITLE
Influxdb v0.9.5.1 throwing OOM

### ISSUE THREAD

**Issue by mdeora** [influxdb/influxdb#5084]
trying on a dual core, 2 gigs of RAM Ubuntu 12.04, on writing 200k series it throws OOM and the service gets killed.

**Comment by otoolep** [comment]
@mdeora -- this is not a good report. We need way more detail than this.

**Comment by otoolep** [comment]
What were you doing with the system at time? What was the query load? What engine were you running? Is the same issue as https://github.com/influxdb/influxdb/issues/5067#issuecomment-163683345? If so, please close.

**Comment by mdeora** [comment]
same as #5067
