### ISSUE TITLE
0.9.6 tsm1 

### ISSUE THREAD

**Issue by ivanscattergood** [influxdb/influxdb#5090]
Hi, 

I have just upgraded to 0.9.6, and switched to using tsm1 

the database crashes after a very short time: 

[wal] 2015/12/10 22:44:35 Flush due to idle. Flushing 7 series with 7 points and 425 bytes from partition 1
[wal] 2015/12/10 22:44:35 write to index of partition 1 took 2.622036ms
[tsm1wal] 2015/12/10 22:44:37 tsm1 WAL starting with 10485760 segment size
[tsm1wal] 2015/12/10 22:44:37 tsm1 WAL writing to /var/lib/influxdb/wal/open_access_db/detail/3
[http] 2015/12/10 22:44:38 127.0.0.1 - root [10/Dec/2015:22:44:37 +0000] POST /write?consistency=any&db=open_access_db&p=%5BREDACTED%5D&precision=n&rp=detail&u=root HTTP/1.1 204 0 - okhttp/2.4.0 974cf704-9f8f-11e5-8007-00
0000000000 1.24184768s
panic: runtime error: index out of range

goroutine 36 [running]:
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WriteWALEntry).Encode(0xc208036050, 0xc22392a000, 0x900000, 0x900000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:377 +0x1295
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WAL).writeToLog(0xc20819a400, 0x7f5ad8148410, 0xc208036050, 0x0, 0x0, 0x0)
        /tmp/tmp.QrWAFdTR6B/src/github.com/influxdb/influxdb/tsdb/engine/tsm1/wal.go:208 +0xbb
github.com/influxdb/influxdb/tsdb/engine/tsm1.(*WAL).WritePoints(0xc20819a400, 0xc2179ac540, 0x0, 0x0, 0x0)

**Comment by otoolep** [comment]
This was fixed in master a few minutes ago.

Can you build master? It will also be available in tonight's nightly.

**Comment by ivanscattergood** [comment]
Superb work sir! 

I'll wait for tonight's nightly

**Comment by otoolep** [comment]
Actually 0.9.6.1 has been released with the fix. If you still see an issue
with this release let us know.
