### ISSUE TITLE
Versions when compiling from source

### ISSUE THREAD

**Issue by Merrindale** [influxdb/influxdb#5103]
Hi All,

Apologies if this is an obvious issue.

When compiling from source I can obtain the binaries with no problem by following your instructions. However the produced binary always shows version 0.9 (see attachment -influxdb)

What is required to obtain a 0.9.6 build?
Thanks and my compliments on the database.

![influxdb](https://cloud.githubusercontent.com/assets/16275170/11770340/c6741464-a24f-11e5-8e3e-201ae32ebb37.png)

Michael Turnbull

**Comment by gunnaraasen** [comment]
The [contributing guide](https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md) mentions the version, branch, and commit hash can all be passed in as build flags. The full command to build version 0.9.6.1 with the build flags is

```
git checkout v0.9.6.1
go install -ldflags="-X main.version=0.9.6.1 -X main.branch=0.9.6 -X main.commit= -X main.buildTime=$TIME" ./...
```

Note the git checkout of the `v0.9.6.1` tag. `go install` will not automatically check out the right tag/branch based on the build flags.
