### ISSUE TITLE
"accept remote connection" cluster logs

### ISSUE THREAD

**Issue by hervenicol** [influxdb/influxdb#5118]
I'm having thousands of **"[cluster] 2015/12/15 10:23:36 accept remote connection from xxx.xxx.xxx.xxx:xxxx"** messages in my influxdb logs.
It seems these logs are normal across my cluster, they are not errors, but I did not find a way to disable these logs.

According to cluster/service.go, I guess there is no config directive to disable these logs.

**Comment by jackzampolin** [comment]
The config setting to cut off those messages is:
```
[meta]
  logging-enabled = false
```
