### ISSUE TITLE
Backfilling with "time(1w)" yields the same result as with "time(1d)"

### ISSUE THREAD

**Issue by pootzko** [influxdb/influxdb#5121]
Hi,

I noticed that backfilling with "time(1w)" yields the same result as with "time(1d)" if the interval for which you're doing the backfill is equal or less than 1w of data. Is this by design? 

In my mind, I don't think that the query should fallback to that kind of behavior - I would expect it to not do anything instead. This way the backfill silently does the thing that you do not expect it to do and the data in there ends up being not correct.

By a backfill I mean an ad-hoc query that uses the `INTO` statement.

For example, a query such as this one:

```sql
SELECT min(temp) as min_temp, max(temp) as max_temp INTO "reading.minmax.1w" FROM reading 
WHERE time >= '2015-09-01 00:00:00' AND time < '2015-09-08 00:00:00'
GROUP BY time(1w), fill(none)
```

causes that kind of behaviour.

Does the `1w` require a time interval that begins on Monday? In anyway, I wouldn't expect it to fallback to `1d`, it seems pretty not what you would expect.

I'm using Influx v0.9.6.

**Comment by pootzko** [comment]
Actually sorry, this was my mistake :S It all works as expected..

**Comment by pootzko** [comment]
I am still wondering though how the first day of the week is picked? I now have these two `time` records in the _reading.downsample.1w_ serie:

```
2015-08-27T00:00:00Z
2015-09-03T00:00:00Z
```

Both of which are Thursdays which is a bit odd.. Any ideas?

**Comment by beckettsean** [comment]
@pootzko I don't actually know why the 1w groupings start on Thursday. There are open issues for the code and the docs to address this: https://github.com/influxdb/influxdb/issues/1837 and https://github.com/influxdb/docs.influxdata.com/issues/41
