### ISSUE TITLE
Document limits of `GROUP BY`?

### ISSUE THREAD

**Issue by zstyblik** [influxdb/influxdb#5123]
Hello,

I'm playing around with InfluxDB v0.9.6(.x) and TSM and bz1 storage engines. I was surprised to find out there is a limit for `GROUP BY` which, strange enough for me, is enforced only at bz1, but I haven't encountered it at TSM.

> Server returned error: too many points in the group by interval. maybe you forgot to specify a where time clause?

Is that correct? Or is it a bug? Can I make this limit somehow larger?

I mean, it seems to me like the limit is between 500k and 600k points which really isn't that much, eg. if 100 servers emit `system_load1` then you aren't left with that much if you want to run something `SELECT mean(value) FROM system_load1 WHERE time > now() - 7d GROUP BY time(1m)`.

Or am I doing something wrong/wrong assumptions which is completely possible.

Thank you for clarification.

EDIT: the point is, if there really is/are limits on `GROUP BY`, then it would be great to document these limits. And may be hint how to achieve desired query other way, if there is one?

**Comment by zstyblik** [comment]
I guess this is related to https://github.com/influxdb/influxdb/issues/2702?

**Comment by e-dard** [comment]
@zstyblik Yes it's related to that. Currently you can't adjust that [limit](https://github.com/influxdb/influxdb/blob/da0830478007f54fe9f49a716bc56b68ccd3303a/tsdb/raw.go#L16)

In terms of approach, is it a usual use-case for you to want a query to return more than 100,000 points? You could use a smaller time-window at the same grouping interval, or a larger grouping interval?

**Comment by zstyblik** [comment]
@e-dard I hope it's not rude thing to ask, but can you present couple use cases/how to use InfluxDB then? Even link to blog will do. I must be missing something.

btw 7 days should be equal to roughly 10k buckets. I believe the limit you've referenced is something else or being randomly enforced or not being enforced at all in case of TSM. As I've said, I'm able to query 500-600k data points before hitting some kind of limit. Or I got it all wrong.

as for the usual use-case, 100+ servers which emit 100 metrics each in 10s intervals and you want to keep this data for 1-3 years ... yes, that's the usual use-case for me. Query past the 7 days with 1minute aggregation? Actually, why not? It's not like I want one year minute by minute.

And don't get me wrong. I don't mind aggregations. Fetching 10MB+ of data from <anything> and then working with it doesn't seem like nice thing to do. But I really do miss those ``how to use properly''.

Thanks.

**Comment by beckettsean** [comment]
@zstyblik the limit is not on the number of points, it is on the number of buckets. A GROUP BY query can return at most 99,999 buckets.

If you are getting the error with less than 100k buckets, please give the full query and error output, as well as a COUNT over the same range and WHERE conditions (no GROUP BY needed).

**Comment by zstyblik** [comment]
@beckettsean you could say I know. I've read the other issue. Also, I've provided all the information except the `COUNT()` which is simply more than 600k data points. Probably even more than double the size. I'm not sure if I still have the data. I will have to check.

**Comment by beckettsean** [comment]
@zstyblik can you paste in a CLI session that shows the query and the error message being returned? Your initial report mentions a lot of things but doesn't actually show anything but the error. (Is the later q

**Comment by zstyblik** [comment]
@beckettsean as funny as it is, I cannot replicate the issue now. As for the query in question, yes, it should hit that limit, but I don't think that really was the query. And perhaps there really wasn't any WHERE limit.
Anyway, 1 metric, 10s intervals, 100 servers = 6M data points per week.

On the other hand ...

```
> SELECT mean(value) FROM disk_inodes_free WHERE time > 1 GROUP BY time(1m)
ERR: too many points in the group by interval. maybe you forgot to specify a where time clause?
> SELECT count(value) FROM disk_inodes_free
name: disk_inodes_free
----------------------
time    count
0       1.058391e+06
```

Yet ...
```
> SELECT count(value) FROM disk_inodes_free WHERE time > now() - 7d
name: disk_inodes_free
----------------------
time                    count
1450169854141058149     1.058542e+06
> SELECT mean(value) FROM disk_inodes_free WHERE time > now() - 7d GROUP BY time(1m)
[... VERY LONG OUTPUT ...]
```

and InfluxDB happily obliges. In some cases, this means really, really long time ...

```
> SELECT count(value) FROM metric01
name: metric01
--------------
time    count
0       2.59201e+07

> SELECT count(value) FROM metric01 WHERE time > now() - 7d GROUP BY time(1m)
[... I'm still waiting on this one ...]
```

So I'm thinking, may be the `GROUP BY` limit is being applied only in specific cases, but not all of them? On the other hand, if it really is only about time buckets, then one week is 10k time buckets.

As the conclusion, I'm unable to hit the issue unless `time > 0` or `time > 1` is specified. Other queries do seem to pass even for very large data set/data points.

**Comment by zstyblik** [comment]
Let's close this issue since I'm unable to reproduce it. If I stumble at it again, I'll reopen it or open a new one.
