### ISSUE TITLE
Adding more granular permissions

### ISSUE THREAD

**Issue by szank** [influxdb/influxdb#5124]
Hi, 
I was wondering if you have considered adding read/write/create permissions on measurement level ?
We are sending a lot of data to InfluxDB and want to use Grafana to analyse it. Performing reads over a large time span causes InfluxDB to allocate a lot of RAM, which is not good. The obvious solution is using continues queries. 

In our use case, we would use Grafana to pull the data from the InfluxDB continues queries, but we would like to prevent our admins from performing Grafana queries over the raw data, even if it is by mistake. 

We would like our admins to see only the continues queries measurement by setting the appropriate read permissions on those measurements, and cleaning the permissions on the raw measurements. 

What do you think about this idea ?

**Comment by beckettsean** [comment]
Per-measurement permissions introduces a serious and probably unsupportable load on the query engine.

You can accomplish the same goal with multiple databases. User permissions are already scoped to databases, and continuous queries can trivially write from one database to another.

``` 
CREATE CONTINUOUS QUERY foo ON source_database BEGIN
    SELECT MEAN(value) INTO destination_database.[retention_policy].measurement FROM source_database.[retention_policy].measurement WHERE ... GROUP BY time(...)
END
```

[retention_policy] is optional, and if not specified will use the `default` retention policy for each database.

**Comment by szank** [comment]
Great, thanks :)
In the docs it wasn't clear that I can create continuous query in a different database than the source measurements.
