### ISSUE TITLE
tcp.Mux: handler not registered: 71

### ISSUE THREAD

**Issue by zapient** [influxdb/influxdb#5138]
Version: 0.9.6.1

Using simple sensu plugin to test availability and we keep getting sporadic error messages

```
Dec 16 07:35:58 core05 bash[5613]: [tcp] 2015/12/16 07:35:58 tcp.Mux: handler not registered: 71
Dec 16 07:35:58 core05 bash[5613]: [tcp] 2015/12/16 07:35:58 tcp.Mux: handler not registered: 71
```

**Comment by otoolep** [comment]
Please show us your config file. You can also get this by sending your HTTP API requests to the wrong port.

**Comment by benbjohnson** [comment]
I agree with @otoolep. The 71 is ASCII for `G` which would be the start of a `GET` HTTP request.

**Comment by zapient** [comment]
So sorry for the confusion. This was a user error as my HAProxy instance was sending requests to both port 8086 and 8088.
