### ISSUE TITLE
Regarding Documentation on Continuous Queries

### ISSUE THREAD

**Issue by zachary822** [influxdb/influxdb#5139]
As a novice to influxdb and TSDBs in general, the documentation does a very good job on demonstrating how to create a continuous query. What it fails to mention is, what is the `INTO` for, what happens after you create a continuous query, and why would I want to create one.

I can create a continuous query no problem, I just don't know what to do next now that I have.

**Comment by beckettsean** [comment]
Requests for documentation should be opened on the docs repo: https://github.com/influxdb/docs.influxdata.com/issues/new. Your request is already covered by an in-progress PR: https://github.com/influxdb/docs.influxdata.com/pull/94

**Comment by zachary822** [comment]
Thank you!
