### ISSUE TITLE
display of time values incorrect?

### ISSUE THREAD

**Issue by jhhayden** [influxdb/influxdb#5162]
when using the influx shell, time values are only displayed as epoch. Per documentation:
> SELECT * FROM h2o_feet LIMIT 5
name: h2o_feet
--------------
time			                 level description	      location	       water_level
2015-08-18T00:00:00Z	   below 3 feet		          santa_monica	   2.064
2015-08-18T00:00:00Z	   between 6 and 9 feet	   coyote_creek	   8.12
2015-08-18T00:06:00Z	   between 6 and 9 feet	   coyote_creek	   8.005
2015-08-18T00:06:00Z	   below 3 feet		          santa_monica	   2.116
2015-08-18T00:12:00Z	   between 6 and 9 feet	   coyote_creek	   7.887

Per my shell:

[root@influxDB ~]# influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.10.0-nightly-8004f11
InfluxDB shell 0.10.0-nightly-8004f11
> use NOAA_water_database
Using database NOAA_water_database
> SELECT * FROM h2o_feet LIMIT 5
name: h2o_feet
--------------
time			level description	location	water_level
1439856000000000000	below 3 feet		santa_monica	2.064
1439856000000000000	between 6 and 9 feet	coyote_creek	8.12
1439856360000000000	between 6 and 9 feet	coyote_creek	8.005
1439856360000000000	below 3 feet		santa_monica	2.116
1439856720000000000	between 6 and 9 feet	coyote_creek	7.887

Has this display feature been removed?

**Comment by jackzampolin** [comment]
@jhhayden 

This is undocumented but if you type

```
> precision rfc3339
```

In the command line it will change the timestamps to the desired state.  I have started an issue on the docs repo to track this: https://github.com/influxdb/docs.influxdata.com/issues/109
