### ISSUE TITLE
[0.9.6.1] DROP RETENTION is missing `ON`

### ISSUE THREAD

**Issue by zstyblik** [influxdb/influxdb#5163]
Hello,

command `DROP RETENTION POLICY "rp_name"` is missing `ON "db_name"` in web management. This leads to error:

> Server returned error: error parsing query: found EOF, expected ON at line 1, char 28

Thanks

**Comment by Vidhuran** [comment]
The pull request https://github.com/influxdb/influxdb/pull/4286 that would fix this was merged to master branch.

**Comment by beckettsean** [comment]
closed by #4286
