### ISSUE TITLE
[CLI] "show field values" not working  [0.9.5.1]

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5176]
```
[ksengal@csdev-ksengal testInflux]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
%> show databases
name: databases
---------------
name
FAKEDBNAME

%> use FAKEDBNAME
Using database FAKEDBNAME
%> show series
name: TABLENAME
---------------
_key					FAKETAG1	FAKETAG2
TABLENAME,FAKETAG1=F1,FAKETAG2=F2	F1		F2

%> show field 
ERR: error parsing query: found EOF, expected KEYS, VALUES at line 1, char 12
%> show field keys
name: TABLENAME
---------------
fieldKey
FIELD1
FIELD2

%> show field values
ERR: error parsing query: found VALUES, expected KEYS, VALUES at line 1, char 12
```

(( See right above, it says it found VALUES but expected one of KEYS or VALUES ))

**Comment by beckettsean** [comment]
@bigKS please note, `SHOW FIELD VALUES` is what `SELECT field FROM measurement` does. There is no `SHOW FIELD VALUES` query. The error message is recycled from the `SHOW TAG [KEYS,VALUES]` query. Thanks @pires for looking at a fix for that!

**Comment by mlowicki** [comment]
@beckettsean is there a way to use SELECT field from measurement but without time? Right now I'm getting:
```
> select distinct(value) from response2;
name: response2
---------------
time    distinct
0       5
```

I would like to get one column only.

**Comment by beckettsean** [comment]
@mlowicki all `SELECT` queries in InfluxDB return a time column. There is no way to execute a `SELECT` and not get back a timestamp with the results.
