### ISSUE TITLE
[0.9.5.1] Cannot use a string with a space as a tag value (nonsensical error about unbalanced quotes)

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5181]
[ksengal@csdev-ksengal Desktop]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
%> use cs
Using database cs
%> select * from subUsage
name: subUsage
--------------
time			subName	upstream
1450661904511205707	"Ken"	453
1450661911681291315	"Bush"	453

%> insert subUsage,subName="G. Bush" upstream=453
ERR: unable to parse 'subUsage,subName="G. Bush" upstream=453': unbalanced quotes

%> 

BUT, space filled strings DO work for field values:

**Comment by beckettsean** [comment]
Please read the syntax for the line protocol. Your statements are not syntactically correct. https://docs.influxdata.com/influxdb/v0.9/write_protocols/write_syntax/

The correct line protocol syntax is `insert subUsage,subName=G.\ Bush upstream=453`

**Comment by beckettsean** [comment]
@bigKS I appreciate the enthusiasm you are showing for InfluxDB, but please consider reading through the documentation and searching the already open issues before filing a new GitHub Issue.

**Comment by kernc** [comment]
Any rationale as to why this was designed in this unintuitive, inconsistent way?
