### ISSUE TITLE
Changing the port that InfluxDB admin website uses

### ISSUE THREAD

**Issue by pootzko** [influxdb/influxdb#5192]
Hi,

is there a way to change the port that the administration website is using to fetch the data? We have a couple of VM's that are behind the same DNS but are on different ports. This works if I programmatically query the data but as soon as I try to go to the Web GUI that's on a non-default port, the website tries to connect to 8086 which means it's actually connecting to the wrong database.

Any way to set this up?

I'm using Influx v0.9.6 and I tried changing ports in `bind-address` fields for both _admin_ and _http_ sections in `influxdb.conf`

This is the error that I get through the web interface:

```
0 error - Could not connect to http://domain.com:8086
Hint: the InfluxDB API runs on port 8086 by default
```

Also, I see that the port is set in the `admin.js`, but I can't find that file on my filesystem on the VM so I guess it's probably a part of the website binary (not sure how you build and package the admin GUI). Is there a way to modify the admin.js on the fly?

Thanks

**Comment by pootzko** [comment]
Ok, I feel a bit stupid right now, the "settings" section that shows up when you click the cog in the upper-right corner allows you to specify the port, not sure how I missed that.. Although it would be nice if one was able to set it up through the config as well.

**Comment by diogobaeder** [comment]
I was bitten by it as well. :-(
