### ISSUE TITLE
always get one localhost server by "SHOW SERVERS".

### ISSUE THREAD

**Issue by just2d** [influxdb/influxdb#5197]
version 0.9.6.1
I followed the instructions here:[https://influxdb.com/docs/v0.9/guides/clustering.html](https://influxdb.com/docs/v0.9/guides/clustering.html),start three raft servers.

all 3 raft servers configured like below,hostname is the real ip.

```
[meta]
  hostname = "10.125.25.51"
  bind-address = ":8088"
```

but there always one "localhost:8088" server,I wanna know which server is that.

Connected to http://localhost:8086 version 0.9.6.1
InfluxDB shell 0.9.6.1
> show servers
```
id	cluster_addr		raft	raft-leader
1	10.125.25.51:8088	true	false
2	localhost:8088		false	false
3	10.125.25.34:8088	true	true
4	10.125.25.63:8088	true	false
```

**Comment by beckettsean** [comment]
@just2d can you paste in the contents of the `meta/peers.json` file from each of the three nodes?

**Comment by just2d** [comment]
@beckettsean they are all identical
```
#cat peers.json 
["10.125.25.34:8088","10.125.25.51:8088","10.125.25.63:8088"]
```

**Comment by just2d** [comment]
I stopped all three node, deleted everything under /var/lib/influxdb/meta,and restarted them one by one. everything seems fine till now.
I'll let you know if the error occur again :)

**Comment by rossmcdonald** [comment]
@just2d Thank you for the update. Let us know if the problem comes back.
