### ISSUE TITLE
Implement subqueries

### ISSUE THREAD

**Issue by jvshahid** [influxdb/influxdb#52]

**Comment by ross-nordstrom** [comment]
+1

**Comment by Dragomir-Ivanov** [comment]
+1

**Comment by pasancario** [comment]
+1

**Comment by multilinear** [comment]
When you do this, please make it arbitrarilly recursive, rather than just adding one-level. In other words, subqueries should be allowed to have subqueries :). Limiting it to 2 levels is as silly as limiting it to 1.

**Comment by gillesdemey** [comment]
+1, here's a sentence that explains my use-case:

I want to retrieve all data points from my latency measurement that are within the 90th percentile.

`SELECT ms FROM latency WHERE time > now() - 2h AND ms < (SELECT percentile(ms, 90) FROM latency)`

**Comment by paul91** [comment]
+1

**Comment by salanki** [comment]
+1

**Comment by Melevir** [comment]
Does "revisit in the future" means it won't be implemented in 0.9.x?

**Comment by beckettsean** [comment]
@Melevir that is correct. The "revisit in the future" label is for features beyond the 0.9 line.

**Comment by hotsnow77** [comment]
+1
I my case I'd like to do a first aggregation with a small group time and over that another aggregation with a bigger group time

**Comment by morganda** [comment]
+1

**Comment by timgriffiths** [comment]
+1

**Comment by 13h3r** [comment]
+1

**Comment by siddarth7** [comment]
+1

**Comment by notes-jj** [comment]
+1

**Comment by bedrin** [comment]
+1

**Comment by asimell** [comment]
+1

**Comment by lexmag** [comment]
Rather than +1 in comments it's way better to react 👍 under initial comment.
There are many people who have subscribed to this issue to get a notification when it will be closed (hopefully implemented), and those +1 only create unnecessary noise for everyone.
