### ISSUE TITLE
influx_stress -database switch not effective

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#5237]
./influx_stress -database=test1

has no effect. The created database is still called "stress".

**Comment by mjdesa** [comment]
@otoolep the `-database` flag actually specifies the database where the results of the stress test will persist.

I'll add another flag for specifying the db to use during the stress test.

**Comment by otoolep** [comment]
Ah, OK @mjdesa -- perhaps make that clearer in the usage output.
