### ISSUE TITLE
Why asymmetric behaviour of tags (column vs. special-and-not-a-column) in JSON query responses?

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5241]
Where are there two different ways a tag can be tried with a query response?

Sometimes tags are treated as a regular column and show up in the columns fields (and there is no tags field at all) in the JSON response.
And...
Sometimes the tags are treated as special (and not in the the columns field) and show up in a tags field.

A) Sometimes (e.g. aggregate functions used) response is split up into multiple "series" fields, where each has a tags field:
----------------------------------------------------------
 ~]$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cs" --data-urlencode "q=SELECT sum(f1) FROM table where time < now() group by time(1s),t1"
{
    "results": [
        {
            "series": [
                {
                    "name": "table",
                    "tags": {
                        "t1": "\"hi\""
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            8.8
                        ]
                    ]
                },
                {
                    "name": "table",
                    "tags": {
                        "t1": "\"jello\""
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            1991.1999999999994
                        ]
                    ]
                }
            ]
        }
    ]
}

B) But most of the cases there is no tags field in response, but the tags are buried within the columns fields:
---------------------------------------------------------------------------

~]$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cs" --data-urlencode "q=SELECT * FROM table"
{
    "results": [
        {
            "series": [
                {
                    "name": "table",
                    "columns": [
                        "time",
                        "f1",
                        "f2",
                        "t1",
                        "t2"
                    ],
                    "values": [
                        [
                            "2005-07-15T16:51:56.098433058Z",
                            52.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-01-16T22:11:56.098433058Z",
                            52.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:09:46.236058993Z",
                            3.4,
                            9.6,
                            "\"hi\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:10:12.293548087Z",
                            5.4,
                            10.2,
                            "\"hi\"",
                            "\"hasta luego\""
                        ],
                        [
                            "2015-12-30T03:31:30.887919382Z",
                            542.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:31:56.098433058Z",
                            542.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:31:56.650898083Z",
                            542.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:32:37.556795537Z",
                            52.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:32:43.167551377Z",
                            52.12,
                            122.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T03:32:44.684432633Z",
                            52.12,
                            1232.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T04:12:59.773062901Z",
                            52.12,
                            122.1,
                            "\"jello\"",
                            "\"bye\""
                        ],
                        [
                            "2015-12-30T04:13:05.152630207Z",
                            52.12,
                            0.12,
                            "\"jello\"",
                            "\"bye\""
                        ]
                    ]
                }
            ]
        }
    ]
}

VERSION INFO:
-----------------------------
~]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1

**Comment by bigKS** [comment]
In the cases where tags are used and multiple series are returned (case A), isn't it always the case that every series will have the same columns, and same depth of values? So why split it out like this (forcing users to trap for this and "join" the various series back up into a single table where tags are simply columns like case B) ?

**Comment by beckettsean** [comment]
@bigKS the influxdb@googlegroups.com mailing list is a more appropriate forum for questions and high-level discussions. We try to keep GitHub Issues to goal-oriented things like bug reports and feature requests. 

That said, the query response is different because the query is different. In the first case, you asked for a function to be applied and grouped by a tag. So, the response has groups at the tag level. In the second query, you asked for all points, with no function or group by, so the system responds with each point in time order.

Remember, this isn't a relational database, so responses are always chronologically ordered unless there's an over-riding grouping. In that case, responses are grouped, and then given in chronological order.

If you want the latter return for the former query, why group by the tag `t1

**Comment by bigKS** [comment]
Now the meaning of "columns" in the query responses is not well defined. Sometimes it includes tags, sometimes it does not (in which case, multiple series are returned with an extra 'tags' section in the responses).
