### ISSUE TITLE
[Minor] Invalid tag in group by is not caught for error, returns weird results without failing...

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5242]
~]$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5.1
InfluxDB shell 0.9.5.1
~]$ curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=cs" --data-urlencode "q=SELECT sum(f1) FROM table where time < now() group by time(1s),T1"
{
    "results": [
        {
            "series": [
                {
                    "name": "table",
                    "tags": {
                        "T1": "" <------ SEE HERE.  My typo of a real field t1 as T1 caused this
                    },
                    "columns": [
                        "time",
                        "sum"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            1999.9999999999993
                        ]
                    ]
                }
            ]
        }
    ]
}

**Comment by beckettsean** [comment]
This is a consequence of the schemaless design. The system doesn't have a central record of every tag that exists and therefore cannot detect the `T1` tag as invalid.
