### ISSUE TITLE
Named Continuous Queries

### ISSUE THREAD

**Issue by tisba** [influxdb/influxdb#525]
Managing CQ is quite limited right now, because you can list them and get an "id" back which you need in order e.g. to drop it (via `drop continuous query $id`).

To ease automatic management of CQs. What I do right now, is list CQs, compare(!) the query strings in order to determine if the CQs was created. I'd like to propose the ability to provide a user defined name when creating a CQ:

```sql
SELECT COUNT(name)
  FROM clicks
  GROUP BY time(1h)
  INTO clicks.count.1h
  NAMED AS click-count-aggregation
```

Because the name has to be unique, this would also allow to reject duplicated CQs (which happens quite easily otherwise).

The name should be returned on `list continuous queries`.

To drop the CQ, you should be able to use the name as well:

`drop continuous query 'click-count-aggregation'`.

**Comment by toddboom** [comment]
This is officially supported in v0.9.0. This pull request will complete the change:

https://github.com/influxdb/influxdb/pull/1285

**Comment by tisba** [comment]
That's great to hear, thanks @toddboom! I'm really looking forward to 0.9, mostly for the CQ enhancements.
