### ISSUE TITLE
Can't write to InfluxDB v0.9.6.1

### ISSUE THREAD

**Issue by DenysBez** [influxdb/influxdb#5251]
installed InfluxDB 0.9.6.1 with Telegraf 0.2.4

after some time noticed these messages inside /var/log/telegraf/telegraf.log

2016/01/01 17:41:10 ERROR: Post http://localhost:8086/write?consistency=&db=telegraf&precision=s&rp=: dial tcp 127.0.0.1:8086: getsockopt: connection refused
2016/01/01 17:41:10 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
2016/01/01 17:41:20 Gathered metrics, ({10s} interval), from 6 plugins in 17.060089ms
2016/01/01 17:41:20 ERROR: Post http://localhost:8086/write?consistency=&db=telegraf&precision=s&rp=: dial tcp 127.0.0.1:8086: getsockopt: connection refused
2016/01/01 17:41:20 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
2016/01/01 17:41:20 ERROR: Post http://localhost:8086/write?consistency=&db=telegraf&precision=s&rp=: dial tcp 127.0.0.1:8086: getsockopt: connection refused
2016/01/01 17:41:20 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
2016/01/01 17:41:30 Gathered metrics, ({10s} interval), from 6 plugins in 18.800241ms

after some time...
2016/01/01 17:49:40 FATAL: Write to output [influxdb] failed 3 times, dropping 246 metrics
2016/01/01 17:49:50 Gathered metrics, ({10s} interval), from 6 plugins in 16.413655ms
2016/01/01 17:49:50 ERROR: {"error":"user is required to write to database \"telegraf\""}

2016/01/01 17:49:50 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
2016/01/01 17:49:50 ERROR: {"error":"user is required to write to database \"telegraf\""}

2016/01/01 17:49:50 Error in output [influxdb]: Could not write to any InfluxDB server in cluster, retrying in 10s
2016/01/01 17:49:50 ERROR: {"error":"user is required to write to database \"telegraf\""}

restarted everything, but influxdb is still broken and is not accessible via http. I think this happened because I used "SELECT * FROM /.*/" in the admin GUI on the telegraf database with many records. 

How I can recover database to the normal state without any data loss?

**Comment by wuxiaomin98** [comment]
Hi @DenysBez , I have the same issue with you. I'm wondering how could I handle this problem? Below is part of the log:

2016/06/07 00:22:10 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2016/06/07 00:22:20 Output [influxdb] buffer fullness: 98 / 10000 metrics. Total gathered metrics: 98. Total dropped metrics: 0.
2016/06/07 00:22:20 Database creation failed: Get http://ec2-54-183-98-101.us-west-1.compute.amazonaws.com:8086/query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22telegraf%22: dial tcp 172.31.17.92:8086: getsockopt: connection refused
2016/06/07 00:22:20 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2016/06/07 00:22:30 Output [influxdb] buffer fullness: 108 / 10000 metrics. Total gathered metrics: 108. Total dropped metrics: 0.
2016/06/07 00:22:30 Database creation failed: Get http://ec2-54-xx-xx-xx-xxx.us-west-1.compute.amazonaws.com:8086/query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22telegraf%22: dial tcp 172.31.17.92:8086: getsockopt: connection refused
2016/06/07 00:22:30 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster
2016/06/07 00:22:40 Output [influxdb] buffer fullness: 118 / 10000 metrics. Total gathered metrics: 118. Total dropped metrics: 0.
2016/06/07 00:22:40 Database creation failed: Get http://ec2-54-183-98-101.us-west-1.compute.amazonaws.com:8086/query?db=&q=CREATE+DATABASE+IF+NOT+EXISTS+%22telegraf%22: dial tcp 172.31.17.92:8086: getsockopt: connection refused
2016/06/07 00:22:40 Error writing to output [influxdb]: Could not write to any InfluxDB server in cluster

Thanks!

**Comment by tamasgal** [comment]
Btw. the same happened to me today, out of nowhere...
