### ISSUE TITLE
InfluxDB Crash

### ISSUE THREAD

**Issue by bigg33k** [influxdb/influxdb#5261]
I've found a scenario that consistently crashes InfluxDB with no useful output to identify why.
I've created a database called 'smokeping' with the goal of importing Smokeping's RRD lastupate info into Influx. Shortly after 
`[query] 2016/01/04 14:42:59 SELECT mean(value) FROM smokeping."default".smokeping WHERE host =~ /do2$/ AND label =~ /b-gtld$/ AND point = 'median' AND time > now() - 1h GROUP BY time(1s)
[query] 2016/01/04 14:42:59 SELECT mean(value) FROM smokeping."default".smokeping WHERE host =~ /do2$/ AND label =~ /b-gtld$/ AND point = 'ping1' OR point = 'ping2' AND time > now() - 1h GROUP BY time(1s)
` is issued (from Grafana), Influx just stops with no output.

InfluxDB is running on a Vagrant/VirtualBox on 'Linux vagrant-ubuntu-trusty-64 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux' 

Any hep would be appreciated

**Comment by zstyblik** [comment]
Are you sure it stops? Are you sure it doesn't take a lot of time to actually process the query and come up with the result? I mean, are you sure there is no subsequent `... [http] ...GET /query?q= ` in the log later on?

**Comment by otoolep** [comment]
Help us help you, @bigg33k -- what version of InfluxDB are you running?

**Comment by bigg33k** [comment]
@zstyblik  yes. a ps -ef | grep influx shows no influxd process running.
@otoolep  version 0.9.6.1
Thanks

**Comment by otoolep** [comment]
Have you checked the logs?

**Comment by otoolep** [comment]
Including the system logs, where the OS will log killing it due to out-of-memory issues.

**Comment by bigg33k** [comment]
spot on. Thanks for the help.
