### ISSUE TITLE
Derivative should handle counter wrapping

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#549]
Derivatives are used to get rates when feeding in counter values. It's common to have these values either wrap to 0 or to get reset to 0 when a host restarts. We should handle this gracefully and compute a rate based on the wrap.

**Comment by konrade** [comment]
:+1:

**Comment by mmikulicic** [comment]
+1

**Comment by carl-amplidata** [comment]
+1

**Comment by pauldix** [comment]
Closing this out as it will be resolved in the 0.9.0 release. We're using #1477 to track the implementation of this feature.
