### ISSUE TITLE
Support type cast or custom scheme

### ISSUE THREAD

**Issue by chobie** [influxdb/influxdb#554]
Scheme less is very handy but in some language (for example, PHP) might insert wrong data type as it has weak data type.

For example:

``` php
#php -r 'var_dump([["value" => 1], ["value" => "2"], ["value" => 3]]);'
array(3) {
  [0]=>
  array(1) {
    ["value"]=>
    int(1)
  }
  [1]=>
  array(1) {
    ["value"]=>
    string(1) "2"
  }
  [2]=>
  array(1) {
    ["value"]=>
    int(3)
  }
}
```

If we insert this variables into InfluxDB. and execute `select * from mixed_type where value > 1` query. Unfortunately, this result only shows `{"value": 3}`.

Essentially, just coding carefully solve the problem. but It's hard to find bad data if once inserted wrong one.

to avoid this unwanted behaviour.  adding type cast or custom scheme would be helpful.

### References
* Hive: type cast
https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF#LanguageManualUDF-TypeConversionFunctions

* Treasure Data: custom scheme
http://docs.treasuredata.com/articles/schema#setting-custom-schema

feedback is appreciated.

**Comment by beckettsean** [comment]
In 0.9.0 values are type-agnostic until the first value is written, and then all subsequent values must match the type of the first one written.
