### ISSUE TITLE
Graphite migration

### ISSUE THREAD

**Issue by hunter** [influxdb/influxdb#580]
I'm starting to consider a move from Graphite to Influxdb for some of our environments and starting to do some testing and investigation into migration strategies.

It occurred to me that it might be a common thing for a lot of people. It could be a useful addition to include a page in the docs and perhaps include some tools to help those migrating. Things like:

* A comparison to Graphite (similar to how hashicorp does a 'vs' with other tools for Consul)
* Steps to replace a Graphite installation
* A list of tools to assist in migration (influxdb's carbon config, graphite-api, etc. @Dieterbe had a few good suggestions in a recent blog)

I'm not sure if there are supporting tools around to help but it also might be useful for ways to import existing whisper data or even Docker images that could be run as a replacement.

We're still getting familiar and learning as we go but happy to assist where we can.

**Comment by otoolep** [comment]
May be covered by https://github.com/influxdb/influxdb/issues/2102

**Comment by Dieterbe** [comment]
whisper to influxdb: https://github.com/vimeo/whisper-to-influxdb

**Comment by otoolep** [comment]
We have detailed Graphite documentation available now.

https://github.com/influxdb/influxdb/blob/master/services/graphite/README.md
