### ISSUE TITLE
Add support for column indexes

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#582]
We should add support for column indexes. Everything will still be indexed by time, but you'll be able to additionally index by column values. For example if you have a series:

```json
{
  "name": "memory_used",
  "columns": ["host", "datacenter", "value"],
  "points" : ["serverA", "us-east", 2343223]
}
```

Later when you're doing queries, if you do `select sum(value) from memory_used where host = 'serverA'` it has to do a range scan to get at all of that data. Indexes would make it efficient to pull back the data.

Another possible win on indexes, is if a column is indexed, we should convert the value into a `uint64`, which will be more efficient to store. Note that the indexes are intended for hash lookups (i.e. `=`) and not range indexes.

Adding an index could look something like this:

```sql
create index memory_used_hosts
on memory_used (host)

-- or do it against a regex

create index hosts
on /.*\.h\..*/ (host)
```

The second example will index any series by host that has `.h.` in the series name. You can then create conventions around putting things in series names to have those values be indexed.

Because of the way I imagine this being implemented, you'd want to keep the total number of indexes in each DB fairly small (< 100). But only real testing will reveal what makes sense.

One other idea I heard floated for how to do this is to update the input format. Instead of specifying this as a configuration option, have a new section on ingestion like this:

```json
{
  "name": "memory_used",
  "columns": ["value"],
  "tags": ["host", "datacenter"]
  "points" : [[2343223, "serverA", "us-east"]]
}
```

The idea being that `tags` would be automatically indexed and would be the last values in the array of a point.

This would be more efficient because we wouldn't need to worry about looking up indexes every time we write data in. Would like to hear what other people think about the two approaches.

**Comment by dashesy** [comment]
+1 Is the tags implementation ready now? I cannot find any documentation on how to use this great feature.

**Comment by naparuba** [comment]
+1 Too. What is the current status of this (great) feature? ^^ Thanks

**Comment by otoolep** [comment]
Seems like we have this now @pauldix ?

**Comment by pauldix** [comment]
Something like it. Tags in 0.9.0 should take care of this feature.

**Comment by mageddo** [comment]
Where can I found the documentation about how to use column indexes? All influxdb pages comes to here
