### ISSUE TITLE
Official repository for Debian and Redhat

### ISSUE THREAD

**Issue by markusr** [influxdb/influxdb#585]
Hi,

is there a plan to create official repository for Debian and RedHat distributions?
So that the users can use packet managers for getting influxdb instead of downloading the releases manually. 

This could help with the initial start up and maintenance. 

Thanks
 MarkusR

**Comment by go8ose** [comment]
I would also like this. It makes a lot more sense to me to add an apt source line under /etc/apt/sources.list.d, than to wget download a deb file.

**Comment by rossmcdonald** [comment]
We've setup an official repository for new InfluxDB packages on Ubuntu/Debian and RHEL/CentOS.

For `apt-get` on Debian/Ubuntu, you can run the following command (as root):
```
curl -sL https://repos.influxdata.com/influxdb.key | apt-key add -
source /etc/lsb-release
echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | tee -a /etc/apt/sources.list
```
And then a `sudo apt-get update && sudo apt-get install influxdb` to install InfluxDB.

For `yum` on CentOS/RHEL, you can run the following command (as root):
```
cat <<EOF>/etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxDB Repository - RHEL \$releasever
baseurl = https://repos.influxdata.com/centos/\$releasever/\$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
EOF
```
And then a `sudo yum install influxdb` to install InfluxDB. 

Let us know if you run into any issues!

**Comment by damm** [comment]
Thank you!

**Comment by wzph** [comment]
Thank you.

**Comment by kozlice** [comment]
If you're getting “Failed to fetch file [..] binary-i386/Packages” error while updating apt repos (I've got this in Ubuntu 14.04), set amd64 explicitly:

`deb [arch=amd64] https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable`

**Comment by StianOvrevage** [comment]
Maybe you should also consider adding (or even replacing) the existing installation instructions on https://influxdata.com/downloads/ ? :)

**Comment by StianOvrevage** [comment]
Also, the examples above include sudo prefix for apt-get commands but not the apt-key and tee commands. Consider creating separate, or at least consistent, examples for Ubuntu/Debian users to avoid confusion for newbies. 

Otherwise, good work on the repo! Worked like a charm on Ubuntu 14.04.

**Comment by StianOvrevage** [comment]
Not sure if this is the right place (could not find a separate Chronograf project on GH) - But the current repo is missing the chronograf packages.

**Comment by rossmcdonald** [comment]
@StianOvrevage I've updated the comment above to use all `sudo` commands, thanks for pointing that out.

Regarding the installation instructions, the InfluxDB documentation already has them:

https://docs.influxdata.com/influxdb/v0.9/introduction/installation/

But we will also be updating the Downloads page later this week.

Lastly, Chronograf has also been added to the stable channel of the repository, so it should now be available using `apt-get install chronograf` and `yum install chronograf`.

**Comment by StianOvrevage** [comment]
Awesome stuff, thanks!

**Comment by ptx0** [comment]
Looks like there's no Debian Wheezy support?

**Comment by rossmcdonald** [comment]
@ptx0 There is documentation [here](https://docs.influxdata.com/influxdb/latest/introduction/installation/#ubuntu-debian) which covers how to install InfluxDB on Debian Wheezy (which is supported).

**Comment by ptx0** [comment]
ah, I think it requires HTTPS for Apt which I do not have.

**Comment by Apollon77** [comment]
@rossmcdonald: Was there a change for chronograf? No longer in official repo and only available as download?

**Comment by rossmcdonald** [comment]
@Apollon77 Nope, Chronograf is still available in the `stable` channel of the repository. Are you having issues pulling it?

**Comment by Apollon77** [comment]
I checked for  Ubuntu Trusti, Xenial and Debian Wheezy ... but may it be that it is not available for armhf platform? I checked and seems only be there for amd64 :-( Then it would be a different topic ...

**Comment by rossmcdonald** [comment]
@Apollon77 Yes, Chronograf is currently only available for amd64 systems. Sorry about that!

**Comment by Apollon77** [comment]
:-( Any chance to change for the future? I use some Cubietrucks for my home automation stuff and wanted to use it together with InfluxDB

**Comment by lGuillaume124** [comment]
Hi,

Can I find the Debian packaging instructions somewhere (ie. the ``debian/`` folder)?

**Comment by rossmcdonald** [comment]
@lGuillaume124 The Debian packaging is handled by [fpm](https://github.com/jordansissel/fpm). You can see how fpm is called in the packaging script here:

https://github.com/influxdata/influxdb/blob/master/build.py#L697
