### ISSUE TITLE
Add support to select the top value from a collection of series

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#586]
As mentioned by @samuraraujo in #551. Should be able to query top values on a regex of series. The syntax on this needs to be figured out.

```sql
select top(10, value) from /cpu.*/
```

Doesn't make sense because in every other query the aggregate is applied on a per series basis. What is needed is the series with the top 10 values. Maybe something like

```sql
select * from top(10, value, /cpu.*/)
```

Where the first argument is the number to select, then the column to use, and finally the set of series to run the function over. Feedback on syntax is welcome. Nothing seems very clean here

**Comment by mihaicostin** [comment]
I would also like to see this feature in

**Comment by beckettsean** [comment]
New TOP supports this, assuming the series are all in the same measurement. Any tag can be used as a uniqueness constraint.
