### ISSUE TITLE
Track resource usage of queries and clients (memory, I/O)

### ISSUE THREAD

**Issue by PAStheLoD** [influxdb/influxdb#639]
Hello,

We've started to use Influxdb behind a Grafana dashboard, quite happily I might add, but then on this experimental two-node cluster the node receiving the time series input and the grafana reads started to consume more and more memory, ultimately I had to send a few SIGTERMs to it (luckily there was no need for more drastic measures). The node was keeping up with IO, so iostat -xm 1 indicated low util%. And the same pattern repeated after restarts. (Finally forcing packets to TCP/8086 to get dropped via iptables, and letting influx run for a bit before reenabling traffic helped to stabilize it.)

We have just 14 continuous queries, one DB, it takes up about 40G HDD on each node (replication factor 2, so not surprising).

**Comment by beckettsean** [comment]
`SHOW DIAGNOSTICS` in 0.9 accomplishes much of this.
