### ISSUE TITLE
influxdb daemon stdout/stderr discarded, panics not visible

### ISSUE THREAD

**Issue by Dieterbe** [influxdb/influxdb#650]
Hi,
currently, any error that happens in `influxdb` ( `daemon`) that goes into stdout or stderr, gets lost because `scripts/influxdb-daemon.sh`, wraps it and sends all stdout and stderr to /dev/null.

there was probably a reason for this, see https://github.com/influxdb/influxdb/commit/d40ed03272566643228f8943c4b392eb3bc91397 I wonder why this change was made ( @jvshahid ?)

but i'm thinking we should probably track those streams into a logfile.
Some things can't be logged by the process and appear on stdout/stderr, such as panics.

**Comment by otoolep** [comment]
Panics are fully visible in the log as part of 0.9.0.
