### ISSUE TITLE
Hierarchical Data in InfluxDB

### ISSUE THREAD

**Issue by calben** [influxdb/influxdb#693]
I was looking at Grafana's "play" dashboard before I set up my own Grafana and noticed while editing one of the charts that there were nested tables/series in the tool for selecting data.
Is this supported in InfluxDB?
If so, how is it done?

An example of the selection tool can be reached by selecting the title of one of the charts, selecting edit, and then editing the query bar beneath the chart.

Thanks!

**Comment by dandv** [comment]
3+ years later, any plans to implement structured data storage in InfluxDB?

**Comment by pauldix** [comment]
@dandv This is a very old issue based on the 0.8 version of Influx, which had a different data model than Influx 0.9 and beyond. This is a request to support a data model like Graphite's.

We chose to go with a tag based approach as opposed to a hierarchy based one. The widespread adoption of Prometheus and the coming changes to Graphite to add tagging support bear this out as a good decision.

Changing the data model to support hierarchies would be incredibly challenging from both an implementation and an API/documentation/consistency of approach perspective. I think we're unlikely to ever add this. Unless it's something we consider for 3.0, which is at best at least three years away.
