### ISSUE TITLE
Add armhf deb build step for 0.8?

### ISSUE THREAD

**Issue by pspeter3** [influxdb/influxdb#786]
Just having a deb for it since you're already building with crosstools would be awesome.

**Comment by DonHugo** [comment]
+1

**Comment by beckettsean** [comment]
will revisit packaging for 0.9.x, do plan to have debian and ARM packages, no reason not to have a debian ARM package.

**Comment by cobyism** [comment]
Bump. Having an `armhf` build for this in addition to `armel` would be :sparkles:.

**Comment by beckettsean** [comment]
@cobyism this is a closed issue, and refers to 0.8, which is end of life. Please open a new issue to request an 0.9 Debian ARM package

**Comment by cobyism** [comment]
Thanks @beckettsean. Just opened https://github.com/influxdb/influxdb/issues/3557 :+1:
