### ISSUE TITLE
Allow using 'T' as a date and time delimiter

### ISSUE THREAD

**Issue by neuroid** [influxdb/influxdb#788]
Hi,

Currently the format of date time strings in queries is `YYYY-MM-DD HH:MM:SS.mmm`. It might be useful to also handle `YYYY-MM-DDTHH:MM:SS.mmm`, which is an `ISO 8601` compatible format.

**Comment by beckettsean** [comment]
0.9.0 uses RFC3339 nano.

**Comment by jufemaiz** [comment]
@beckettsean can you confirm that this means that the T delimiter has been adopted or not (as per recommendations in Section 5.6)? Cheers!

**Comment by beckettsean** [comment]
I cannot immediately confirm that the T delimiter is valid, but if not valid it's a bug. We intend to be fully RFC3339 compliant including the recommendations in section 5.6 of that doc.

Do you see issues with RC28 in using the T delimiter?

**Comment by jufemaiz** [comment]
HI @beckettsean thanks for that. Haven't had a chance to do any testing yet. Will try in the coming week.

Cheers,
Joel

**Comment by gunnaraasen** [comment]
I can confirm that, as of v0.9.0-rc28, InfluxDB only accepts writes with
- a strict RFC3339 timestamp (only the T delimiter is accepted, no space allowed)
- or unix epoch + precision ([source](https://github.com/influxdb/influxdb/blob/master/client/influxdb.go#L340)).
For querying data, the syntax parses RFC3339 strings with both the T and space delimiters, but has no support for epochs ([source](https://github.com/influxdb/influxdb/blob/master/influxql/parser.go#L1793)).
