### ISSUE TITLE
New continuous queries don't work after previously dropping continuous query that was being initialized

### ISSUE THREAD

**Issue by jcellary** [influxdb/influxdb#789]
I created a continuous query with group by time(1ms) which caused the server to initialize it for a very long time, so I decided to stop this process and drop it before initialization finished. After that all newly created continuous queries remain empty (eg. the destination time series is not listed with "list series"). It seems that continuous query initialization process did not recover properly after dropping the first query.

Please let me know how I can recover from this situation. Below the logs:
https://www.dropbox.com/s/gise1y3ta28w0em/log-yesterday.txt
https://www.dropbox.com/s/k4ugod0vy6qeoel/log-today.txt

Server info:
```
root@graph-s3:/opt/influxdb/shared# ../current/influxdb -v
InfluxDB vdev (git: 9089da6) (leveldb: 1.15)
root@graph-s3:/opt/influxdb/shared# cat /etc/issue
Ubuntu 12.04.2 LTS \n \l
root@graph-s3:/opt/influxdb/shared# uname -a
Linux graph-s3 3.5.0-36-generic #57~precise1-Ubuntu SMP Thu Jun 20 18:21:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
root@graph-s3:/opt/influxdb/shared# mount
[...]
/dev/sda5 on /data type ext4 (rw)
```
InfluxDB version: 0.7.3 + hotfix for #702

**Comment by toddboom** [comment]
Continuous queries were completely rewritten for v0.9.0, so this will likely be resolved. Closing it out.
