### ISSUE TITLE
Aggregate functions should take a wildcard to work on all columns

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#814]
As a shortcut in the query language, it would be great to be able to aggregate all columns with a given function. Like this:

```sql
select sum(*), mean(*) from some_series group by time(10m)
```

Where it would expand the query out into a sum for each column. Previously, we didn't have a definition of what columns existed over all time for a series. Now that metadata is in Raft, we know the columns by just looking it up.

This would have to have some intelligent failure logic to deal with column types where it doesn't make sense like strings. In that case it should just omit that from the results.

**Comment by reardencode** [comment]
:+1: It would also be great if the resulting data could be grouped by the column name (eg. for making lines in grafana)

**Comment by blewa** [comment]
+1!

**Comment by beckettsean** [comment]
Seems less relevant with 0.9.0 data structure. Closing.

**Comment by akruman** [comment]
It could be very useful for continues queries; so i could put one query to back all my high precision 1 day retention data, into lower precision 1 week retention data.

something like:
CREATE CONTINUOUS QUERY rp1w_query ON mydb BEGIN
  SELECT max(*) INTO "rp1w1".:MEASUREMENT FROM /.*/ GROUP BY time(1m) 
END

**Comment by beckettsean** [comment]
closing in favor of https://github.com/influxdb/influxdb/issues/4708
