### ISSUE TITLE
classical debian package

### ISSUE THREAD

**Issue by athoune** [influxdb/influxdb#816]
Debian packages should respect the rules.

 * Config should be in /etc/influxdb.toml
 * Data should be in /var/lib/influxdb/*
 * Files should be in /usr/lib/influxdb/*
 * Binary should be in /usr/sbin/influxdb
 * Pid file should be in /var/run/influxdb/influxdb.pid 
 * Logs should be in /var/log/influxdb/*.log and can use logrotate
 * Some docs in /usr/share/doc/influxdb/

With a clean path, admins will love you, can install, manage, backup and restore Influxdb.

Do you need some help?

**Comment by otoolep** [comment]
The newest packaging script https://github.com/influxdb/influxdb/blob/master/package.sh follows the file system hierarchy.

**Comment by otoolep** [comment]
http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by damm** [comment]
not exactly a debian style package script but it's something.
