### ISSUE TITLE
Users should be able to rename metadata

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#828]
Since this is only a metadata update, it should be fast and efficient. Change the series name from one thing to another. Maybe:

```sql
rename series "foo" to "bar"
```

Changing column name:

```sql
modify table t1 rename column c1 to c2
```

Or database:

```sql
rename database d1 to d2
```

Or something like that.

**Comment by bouthors** [comment]
+1

**Comment by Jhors2** [comment]
+1

**Comment by morganchristiansson** [comment]
+1

**Comment by jheusser** [comment]
+1

**Comment by fxstein** [comment]
+100
Really a must have. Also been asked before: What is the manual workaround in the meantime?

**Comment by corylanou** [comment]
Should it be:

```sql
ALTER TABLE t1 MODIFY c1 to c2
```
to stay with standard sql convention?

**Comment by jheusser** [comment]
@fxstein Currently I merge the two series in a query `select .. from A merge B where ..` where A was renamed to B or the other way around.

@corylanou sounds good

**Comment by fxstein** [comment]
@jhausser Thanks for the reply!
I fully understand the SELECT query part but that is not really what I am asking for.  I need to take the two timeseries and permanently merge it into a new one. Otherwise you have to modify all application logic that sits on top of that data. e.g. Grafana dashboards would all have to be rewritten with manual queries that perform the merge for every graph out of that series. 
I need to be able to take the select .... merge .... and persist the result into a new or existing series. INSERT SELECT for most databases.

@corylanou ALTER TABLE would be an option, I would even take INSERT SELECT to create a new series, RENAME TABLE would also be an option.

**Comment by otoolep** [comment]
@pauldix -- if a database is renamed, will writes to the older database then start failing (no database exists)? I'm talking about 0.9. We're not talking about any kind of symlink-style functionality, right?

**Comment by toddboom** [comment]
Since the examples @pauldix mentioned in the beginning are probably out of date now, I'm proposing the following

```
RENAME DATABASE d1 TO d2
```

```
RENAME MEASUREMENT "db"."rp"."m1" TO "db"."rp"."m2"
```

```
ALTER MEASUREMENT "db"."rp"."m1" RENAME COLUMN "c1" to "c2"
```

Perhaps these should be broken into separate stories? I think these are in increasing order of importance. Any strong feelings?

**Comment by Glavin001** [comment]
+1 It would be great to rename series and other metadata. And *not* symlink-style functionality.

**Comment by dennisjac** [comment]
@toddboom Shouldn't these be called "rename series" and "alter series" instead? I don't think the terms series, table and measurement should be used interchangeably througout influxdb but one should be chosen and then used everywhere consistently.

**Comment by beckettsean** [comment]
@dennisjac in 0.9 the Measurement is the string that appears in the SELECT clause. The tags, which define the series within the measurement, appear in the WHERE clause. Therefore this is renaming the measurement, not the series. A series doesn't really have a name, it's just the unique combination of a measurement and a tag set.

**Comment by pauldix** [comment]
It should also be noted that series can be synthetic as well. For instance if you write this data:

```
cpu,region=uswest,host=serverA value=23.2
cpu,region=useast,host=serverB value=45.9
cpu,region=useast,host=serverB value=33.1
```

Under the covers that creates three unique series in the data store. However, if you issue this query:

```sql
select mean(value) from cpu
where time > now() - 4h
group by region, time(5m)
```

You'll get two series back, whose keys are `cpu,region=uswest` and `cpu,region=useast`. Note that those two series don't explicitly exist under the hood in the database.

Anyway, this is a long way of saying that there's no idea of renaming a `series` since they are created in many cases on the fly. You either rename measurements, or maybe you rename tag keys.

It should also be noted that given the new underlying structure of how InfluxDB stores data, this would be an incredibly expensive operation. We'll likely punt on this one for a while (post 0.9.1).

**Comment by beckettsean** [comment]
decomposed into relevant issues #4154, #4155, #4156, #4157

**Comment by bcutter** [comment]
So after **more than 6 years nothing of those splitted feature requests is implemented** (one has been auto-closed without a solution/an implementation) - really? I was searching for HOURS to find a way to rename a series. In the end it's still impossible. Unbelievable. This lowers my personal amount of trust in the whole InfluxDB tbh.
