### ISSUE TITLE
Specifying the time_precision when using UDP

### ISSUE THREAD

**Issue by tpitale** [influxdb/influxdb#841]
Time precision on written data as described (http://influxdb.com/docs/v0.7/api/reading_and_writing_data.html#time-precision-on-written-data) should be passed through the query params for the HTTP API.

There does not appear to be any information on what happens with the UDP handler. Is there a value that can be placed in the POST body for `time_precision`?

From reading the code, the default precision appears to be 'ms', essentially.

Thanks!

**Comment by sammy007** [comment]
Must have feature, +1
