### ISSUE TITLE
can't set a replicationFactor of 2 from admin interface

### ISSUE THREAD

**Issue by prune998** [influxdb/influxdb#940]
in the dropdown menu you can only choose from 1,3,4 and so on.. not 2.
2 is a valid choice if using http API...

While I'm here, I can't find any doc on HTTP API, for example, what is the "$$hashKey":"00M" value set when using the admin interface ?

````
curl 'http://localhost:8086/cluster/database_configs/graphite?u=root&p=root' -H 'Content-Type: application/json' --data-binary '{"spaces":[{"name":"default","regEx":"/.*/","retentionPolicy":"inf","shardDuration":"1d","replicationFactor":2,"split":1,"$$hashKey":"00M"}]}'
````

**Comment by toddboom** [comment]
This is no longer relevant to v0.9.0 since replication is handled through retention policies.
